### ISSUE TITLE
make necessary `/etc/kubernetes/manifests` in workers to avoid unnecessary error logs

### ISSUE THREAD

**Issue by brightzheng100** [kubernetes-sigs/kind#1001]
**What happened**:

In workers, as the folder of `/etc/kubernetes/manifests` doesn't exist by default to cater for static pods, `kubelet` will keep throwing errors complaining `path does not exist, ignoring`.

```
# journalctl -f
...
Oct 23 07:35:58 kind-cluster-worker kubelet[508]: E1023 07:35:58.547619     508 file_linux.go:61] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
...
```

**What you expected to happen**:

The folder should be created by default to avoid such annoying warnings prompting up in `journalctl` logs.

**How to reproduce it (as minimally and precisely as possible)**:

Spin up a `kind` cluster and run:

```
$ docker exec --privileged -i kind-cluster-worker journalctl -f
```

**Anything else we need to know?**:

Simply create that folder can stop such warnings:

```
docker exec --privileged -i kind-cluster-worker mkdir -p /etc/kubernetes/manifests
```

**Environment:**

- kind version: (use `kind version`): v0.5.1
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`): MacBook Pro

**Comment by BenTheElder** [comment]
IMO kubeadm is nominally responsible for this but I'd be Ok with creating it to avoid log spam

Cc @neolit123

**Comment by BenTheElder** [comment]
Re-upgrading to a bug. Kubeadm expects to be installed by Deb or RPM, apparently it is ensured there.

`mkdir -p /etc/kubernetes/manifests` is in the post-install for kubelet.

/remove-kind feature
/kind bug
/assign

**Comment by neolit123** [comment]
> mkdir -p /etc/kubernetes/manifests is in the post-install for kubelet.

yes, joining nodes don't need the path but the package just ensures it's there.
joining workers still have the option to create static pods.
