### ISSUE TITLE
 FailedMount  hostPath type check failed

### ISSUE THREAD

**Issue by jerryhu1234** [kubernetes-sigs/kind#1002]
**What happened**:
15m         Normal    Starting                  node/kind1-control-plane                      Starting kube-proxy.
3m6s        Normal    Scheduled                 pod/singlecluster-parallel-555v9-1569980942   Successfully assigned default/singlecluster-parallel-555v9-1569980942 to kind1-control-plane
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-1569980942   MountVolume.SetUp failed for volume "docker-lib" : hostPath type check failed: /var/lib/docker is not a directory
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-1569980942   MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
63s         Warning   FailedMount               pod/singlecluster-parallel-555v9-1569980942   Unable to mount volumes for pod "singlecluster-parallel-555v9-1569980942_default(4c8aff17-b63b-45ef-8ee9-6a470701c1ab)": timeout expired waiting for volumes to attach or mount for pod "default"/"singlecluster-parallel-555v9-1569980942". list of unmounted volumes=[docker-lib docker-sock]. list of unattached volumes=[podmetadata docker-lib docker-sock argo-workflow-token-wjcnk]
3m6s        Normal    Scheduled                 pod/singlecluster-parallel-555v9-176533334    Successfully assigned default/singlecluster-parallel-555v9-176533334 to kind1-control-plane
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-176533334    MountVolume.SetUp failed for volume "docker-lib" : hostPath type check failed: /var/lib/docker is not a directory
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-176533334    MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
63s         Warning   FailedMount               pod/singlecluster-parallel-555v9-176533334    Unable to mount volumes for pod "singlecluster-parallel-555v9-176533334_default(2c613a10-0899-4517-ac1c-8cb593cb3957)": timeout expired waiting for volumes to attach or mount for pod "default"/"singlecluster-parallel-555v9-176533334". list of unmounted volumes=[docker-lib docker-sock]. list of unattached volumes=[podmetadata docker-lib docker-sock argo-workflow-token-wjcnk]
3m6s        Normal    Scheduled                 pod/singlecluster-parallel-555v9-2694783744   Successfully assigned default/singlecluster-parallel-555v9-2694783744 to kind1-control-plane
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-2694783744   MountVolume.SetUp failed for volume "docker-lib" : hostPath type check failed: /var/lib/docker is not a directory
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-2694783744   MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
63s         Warning   FailedMount               pod/singlecluster-parallel-555v9-2694783744   Unable to mount volumes for pod "singlecluster-parallel-555v9-2694783744_default(80ef3c4a-b7be-4cc6-98ac-d7bec51c08e7)": timeout expired waiting for volumes to attach or mount for pod "default"/"singlecluster-parallel-555v9-2694783744". list of unmounted volumes=[docker-lib docker-sock]. list of unattached volumes=[podmetadata docker-lib docker-sock argo-workflow-token-wjcnk]
3m6s        Normal    Scheduled                 pod/singlecluster-parallel-555v9-2733973002   Successfully assigned default/singlecluster-parallel-555v9-2733973002 to kind1-control-plane
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-2733973002   MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-2733973002   MountVolume.SetUp failed for volume "docker-lib" : hostPath type check failed: /var/lib/docker is not a directory
63s         Warning   FailedMount               pod/singlecluster-parallel-555v9-2733973002   Unable to mount volumes for pod "singlecluster-parallel-555v9-2733973002_default(73a38365-6d0b-436b-be4a-bcafef3da112)": timeout expired waiting for volumes to attach or mount for pod "default"/"singlecluster-parallel-555v9-2733973002". list of unmounted volumes=[docker-lib docker-sock]. list of unattached volumes=[podmetadata docker-lib docker-sock argo-workflow-token-wjcnk]
3m6s        Normal    Scheduled                 pod/singlecluster-parallel-555v9-3810855066   Successfully assigned default/singlecluster-parallel-555v9-3810855066 to kind1-control-plane
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-3810855066   MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-3810855066   MountVolume.SetUp failed for volume "docker-lib" : hostPath type check failed: /var/lib/docker is not a directory
63s         Warning   FailedMount               pod/singlecluster-parallel-555v9-3810855066   Unable to mount volumes for pod "singlecluster-parallel-555v9-3810855066_default(41f1c7f8-d685-4f19-9f3b-b450debba0bd)": timeout expired waiting for volumes to attach or mount for pod "default"/"singlecluster-parallel-555v9-3810855066". list of unmounted volumes=[docker-lib docker-sock]. list of unattached volumes=[podmetadata docker-lib docker-sock argo-workflow-token-wjcnk]
3m6s        Normal    Scheduled                 pod/singlecluster-parallel-555v9-414213271    Successfully assigned default/singlecluster-parallel-555v9-414213271 to kind1-control-plane
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-414213271    MountVolume.SetUp failed for volume "docker-lib" : hostPath type check failed: /var/lib/docker is not a directory
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-414213271    MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
63s         Warning   FailedMount               pod/singlecluster-parallel-555v9-414213271    Unable to mount volumes for pod "singlecluster-parallel-555v9-414213271_default(a45b67f3-a465-4b0f-821c-d72e64db0536)": timeout expired waiting for volumes to attach or mount for pod "default"/"singlecluster-parallel-555v9-414213271". list of unmounted volumes=[docker-lib docker-sock]. list of unattached volumes=[podmetadata docker-lib docker-sock argo-workflow-token-wjcnk]
3m6s        Normal    Scheduled                 pod/singlecluster-parallel-555v9-513887230    Successfully assigned default/singlecluster-parallel-555v9-513887230 to kind1-control-plane
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-513887230    MountVolume.SetUp failed for volume "docker-lib" : hostPath type check failed: /var/lib/docker is not a directory
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-513887230    MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
63s         Warning   FailedMount               pod/singlecluster-parallel-555v9-513887230    Unable to mount volumes for pod "singlecluster-parallel-555v9-513887230_default(fc8d7dc9-0241-4b86-a8a7-4681b97428f6)": timeout expired waiting for volumes to attach or mount for pod "default"/"singlecluster-parallel-555v9-513887230". list of unmounted volumes=[docker-lib docker-sock]. list of unattached volumes=[podmetadata docker-lib docker-sock argo-workflow-token-wjcnk]
3m6s        Normal    Scheduled                 pod/singlecluster-parallel-555v9-591647462    Successfully assigned default/singlecluster-parallel-555v9-591647462 to kind1-control-plane
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-591647462    MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-591647462    MountVolume.SetUp failed for volume "docker-lib" : hostPath type check failed: /var/lib/docker is not a directory
63s         Warning   FailedMount               pod/singlecluster-parallel-555v9-591647462    Unable to mount volumes for pod "singlecluster-parallel-555v9-591647462_default(8e44b4eb-b6ad-4124-b8ee-8193e0cc0712)": timeout expired waiting for volumes to attach or mount for pod "default"/"singlecluster-parallel-555v9-591647462". list of unmounted volumes=[docker-lib docker-sock]. list of unattached volumes=[podmetadata docker-lib docker-sock argo-workflow-token-wjcnk]
3m6s        Normal    Scheduled                 pod/singlecluster-parallel-555v9-678032122    Successfully assigned default/singlecluster-parallel-555v9-678032122 to kind1-control-plane
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-678032122    MountVolume.SetUp failed for volume "docker-lib" : hostPath type check failed: /var/lib/docker is not a directory
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-678032122    MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
63s         Warning   FailedMount               pod/singlecluster-parallel-555v9-678032122    Unable to mount volumes for pod "singlecluster-parallel-555v9-678032122_default(80e28ae0-1813-4078-9fbb-108ef364cbe8)": timeout expired waiting for volumes to attach or mount for pod "default"/"singlecluster-parallel-555v9-678032122". list of unmounted volumes=[docker-lib docker-sock]. list of unattached volumes=[podmetadata docker-lib docker-sock argo-workflow-token-wjcnk]
3m6s        Normal    Scheduled                 pod/singlecluster-parallel-555v9-681146570    Successfully assigned default/singlecluster-parallel-555v9-681146570 to kind1-control-plane
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-681146570    MountVolume.SetUp failed for volume "docker-lib" : hostPath type check failed: /var/lib/docker is not a directory
58s         Warning   FailedMount               pod/singlecluster-parallel-555v9-681146570    MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
63s         Warning   FailedMount               pod/singlecluster-parallel-555v9-681146570    Unable to mount volumes for pod "singlecluster-parallel-555v9-681146570_default(dde00ba4-284c-4da2-824a-4e7c0fbb6a22)": timeout expired waiting for volumes to attach or mount for pod "default"/"singlecluster-parallel-555v9-681146570". list of unmounted volumes=[docker-lib docker-sock]. list of unattached volumes=[podmetadata docker-lib docker-sock argo-workflow-token-wjcnk]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
0.51
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Docker version: (use `docker info`):
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
- OS (e.g. from `/etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by BenTheElder** [comment]
kind nodes do not run dockerd, therefore there is no docker socket to mount.

You can mount on from the physical host by using extraMounts on a kind node, but I wouldn't recommend it.

This is working as intended. Mounting the socket is not portable.
