### ISSUE TITLE
Failed to pull image. certificate signed by unknown authority. Proxy

### ISSUE THREAD

**Issue by Sispheor** [kubernetes-sigs/kind#1010]
Hello there.
I'm behind a proxy that wrap the docker.io certificate by a compagny certificate. This result in pull error.
here the pod log when trying to deploy the kubernetes dashboard:
```
Type     Reason     Age                  From                         Message
  ----     ------     ----                 ----                         -------
  Normal   Scheduled  11m                  default-scheduler            Successfully assigned kubernetes-dashboard/kubernetes-dashboard-6bb65fcc49-hfgx8 to kind-control-plane
  Normal   Pulling    9m42s (x4 over 11m)  kubelet, kind-control-plane  Pulling image "kubernetesui/dashboard:v2.0.0-beta4"
  Warning  Failed     9m42s (x4 over 11m)  kubelet, kind-control-plane  Failed to pull image "kubernetesui/dashboard:v2.0.0-beta4": rpc error: code = Unknown desc = failed to resolve image "docker.io/kubernetesui/dashboard:v2.0.0-beta4": no available registry endpoint: failed to fetch anonymous token: Get https://auth.docker.io/token?scope=repository%3Akubernetesui%2Fdashboard%3Apull&service=registry.docker.io: x509: certificate signed by unknown authority
  Warning  Failed     9m42s (x4 over 11m)  kubelet, kind-control-plane  Error: ErrImagePull
  Warning  Failed     6m (x22 over 11m)    kubelet, kind-control-plane  Error: ImagePullBackOff
  Normal   BackOff    55s (x44 over 11m)   kubelet, kind-control-plane  Back-off pulling image "kubernetesui/dashboard:v2.0.0-beta4"
```

So my question is: how can I inject CA cert of my company into the cluster?

Thanks a lot !

**Comment by BenTheElder** [comment]
Hi! See discussion in: https://github.com/kubernetes-sigs/kind/issues/941
I don't have such an environment but one user reported success there.

**Comment by Sispheor** [comment]
Thanks !

**Comment by Sispheor** [comment]
I don't really see the answer in the issue you pointed.
Is there a way to mount a volume into the node container? So I could add my corporate proxy.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/941#issuecomment-541279662

you can mount volumes with extraMounts in the config.
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
   extraMounts:
    - hostPath: /some/path
      containerPath: /some/path
```

**Comment by Sispheor** [comment]
Oh ok. I'll give a try to this config then. Thanks.
I haven't seen this part in the [doc](https://kind.sigs.k8s.io/docs/user/quick-start/#configuring-your-kind-cluster).

**Comment by Sispheor** [comment]
It works ! Thanks. 

The config I used:
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
  extraMounts:
   - hostPath: /home/nico/Desktop/corporate.crt
     containerPath: /usr/share/ca-certificates/corporate.crt
```
Then started the cluster
```
kind create cluster --config kind-config.yml
```

Then connect into the container
```
docker exec -it kind-control-plane /bin/bash
```

Then update certs
```
root@kind-control-plane:/# update-ca-certificates
```

BTW, it would be nice to have the possibility of executing command at the end the deployment by placing them in the config file. 

Thanks for you support and your work on this project !

**Comment by Hokwang** [comment]
In my case, 
`containerPath: /usr/local/share/ca-certificates/corporate.crt`
is correct.

**Comment by stevenpeh** [comment]
> It works ! Thanks.
> 
> The config I used:
> 
> ```yaml
> kind: Cluster
> apiVersion: kind.sigs.k8s.io/v1alpha3
> nodes:
> - role: control-plane
>   extraMounts:
>    - hostPath: /home/nico/Desktop/corporate.crt
>      containerPath: /usr/share/ca-certificates/corporate.crt
> ```
> 
> Then started the cluster
> 
> ```
> kind create cluster --config kind-config.yml
> ```
> 
> Then connect into the container
> 
> ```
> docker exec -it kind-control-plane /bin/bash
> ```
> 
> Then update certs
> 
> ```
> root@kind-control-plane:/# update-ca-certificates
> ```
> 
> BTW, it would be nice to have the possibility of executing command at the end the deployment by placing them in the config file.
> 
> Thanks for you support and your work on this project !

This works for me.  Additional step I had to add is to restart the kind-control-plane container, i.e. docker stop and then docker start.

**Comment by BenTheElder** [comment]
i would probably restart containerd instead of the entire node, `docker
exec kind-control-plane systemctl restart containerd` or something like
that.

**Comment by superbrothers** [comment]
I created a small script to send cert files and restart containerd in all kind nodes.

- https://gist.github.com/superbrothers/c3e1432ab28e313bac40f30cf345aab5OF

```
./kind-load-cafile [-n name] certfile...
```

In actuality, I want kind to officially support loading cert files, like `kind load certfile`.

**Comment by jamesdube** [comment]
> > It works ! Thanks.
> > The config I used:
> > ```yaml
> > kind: Cluster
> > apiVersion: kind.sigs.k8s.io/v1alpha3
> > nodes:
> > - role: control-plane
> >   extraMounts:
> >    - hostPath: /home/nico/Desktop/corporate.crt
> >      containerPath: /usr/share/ca-certificates/corporate.crt
> > ```
> > 
> > 
> > Then started the cluster
> > ```
> > kind create cluster --config kind-config.yml
> > ```
> > 
> > 
> > Then connect into the container
> > ```
> > docker exec -it kind-control-plane /bin/bash
> > ```
> > 
> > 
> > Then update certs
> > ```
> > root@kind-control-plane:/# update-ca-certificates
> > ```
> > 
> > 
> > BTW, it would be nice to have the possibility of executing command at the end the deployment by placing them in the config file.
> > Thanks for you support and your work on this project !
> 
> This works for me. Additional step I had to add is to restart the kind-control-plane container, i.e. docker stop and then docker start.

Thanks, that was the final step I needed for mine to work

**Comment by tppalani** [comment]
Hi @jamesdube 

Hi, I'm running kind cluster in my local computer windows 10 VM, could you please how  i can point hostpath?

- hostPath: /home/nico/Desktop/corporate.crt
     containerPath: /usr/share/ca-certificates/corporate.crt

**Comment by tppalani** [comment]
> docker exec -it kind-control-plane /bin/bash

I'm not sure how you connecting to control plane command

```
$ kubectl get nodes
NAME                 STATUS   ROLES           AGE     VERSION
kind-control-plane   Ready    control-plane   7m49s   v1.27.1

$ kubectl exec -it kind-control-plane /bin/sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Error from server (NotFound): pods "kind-control-plane" not found

```

**Comment by BenTheElder** [comment]
@tppalani they're exec-ing against the kind node container, not the pods running in the cluster. (`docker exec` instead of `kubectl exec`)

The paths should be similar whatever you'd use if you were doing `docker run -v host_path:/container-path ...` the `host_path` part. I don't use docker on windows and it may depend on what variant you're using.

**Comment by tppalani** [comment]
> It works ! Thanks.
> 
> The config I used:
> 
> ```yaml
> kind: Cluster
> apiVersion: kind.sigs.k8s.io/v1alpha3
> nodes:
> - role: control-plane
>   extraMounts:
>    - hostPath: /home/nico/Desktop/corporate.crt
>      containerPath: /usr/share/ca-certificates/corporate.crt
> ```
> 
> Then started the cluster
> 
> ```
> kind create cluster --config kind-config.yml
> ```
> 
> Then connect into the container
> 
> ```
> docker exec -it kind-control-plane /bin/bash
> ```
> 
> Then update certs
> 
> ```
> root@kind-control-plane:/# update-ca-certificates
> ```
> 
> BTW, it would be nice to have the possibility of executing command at the end the deployment by placing them in the config file.
> 
> Thanks for you support and your work on this project !

Hi All,

As per the above note i have added extra mount inside my kubd-config.yaml file, when the cluster is ready i used below command to entre into control plane node, but i don't see my certificate inside the container path, Note inside my host path cert file is present.

```
C:\Users\viswa>podman exec -it kind-control-plane /bin/bash
root@kind-control-plane:/# cd /usr/local/share/ca-certificates
root@kind-control-plane:/usr/local/share/ca-certificates#
root@kind-control-plane:/usr/local/share/ca-certificates#
root@kind-control-plane:/usr/local/share/ca-certificates# ls -lrt
total 0
```

**Comment by lbg-wilsonli** [comment]
Appreciate the time this ticket was raised (2019) it seems to be an issue for including a CA for corporate infrastructure. Apart from building an image is there a way around this out of the box?
