### ISSUE TITLE
Unable to update the default storage class on Kind

### ISSUE THREAD

**Issue by reshdebug** [kubernetes-sigs/kind#1017]
**What you expected to happen**:
Not able update  default storage class. Expected to set, is-default-class":"false" for standard storage class

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubectl patch storageclass standard -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
storageclass.storage.k8s.io/standard patched

```

```
$ kubectl describe sc standard
Name:            standard
IsDefaultClass:  Yes
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"},"labels":{"addonmanager.kubernetes.io/mode":"EnsureExists"},"name":"standard"},"provisioner":"kubernetes.io/host-path"}
,storageclass.beta.kubernetes.io/is-default-class=false
Provisioner:           kubernetes.io/host-path
Parameters:            <none>
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>


```
```
$ kubectl get sc
NAME                 PROVISIONER                            AGE
standard (default)   kubernetes.io/host-path                3h14
```

**Anything else we need to know?**: 
Did try to refer existing bug #66222, no luck!

**Environment:** 

- kind version: (use `kind version`): v0.5.1
- Kubernetes version: (use `kubectl version`):v1.15.3
- Docker version: (use `docker info`): Docker version 18.09.3
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 10

**Comment by BenTheElder** [comment]
I'm pretty sure you need to create another storage class first.
kind does nothing special here beyond installing one.

**Comment by BenTheElder** [comment]
by 66222I assume you mean https://github.com/kubernetes/kubernetes/issues/66222#issuecomment-449121999, which leads to this change, https://github.com/kubernetes/kubernetes/pull/66235/files

kind is already using EnsureExists, but it also doesn't deploy the addon manager.

**Comment by reshdebug** [comment]
Did try creating new storage class and updated the Standard storage class but same behavior. In fact, I have 2 default storage class:

`kubectl get sc
NAME                  PROVISIONER                            AGE
test-class(default)   kubernetes.io/local-path-provisioner   3h16m
standard (default)    kubernetes.io/host-path                3h52m
`

**Comment by BenTheElder** [comment]
re-read this, the patch is patching `storageclass.kubernetes.io/is-default-class=false` but the actual resource has `storageclass.beta.kubernetes.io/is-default-class=true`

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/68345

**Comment by reshdebug** [comment]
Ah! Completely, missed to noticed that. After pointing to the correct resource, I am able to update the default storage class.

Thank you so much for the quick response @BenTheElder

**Comment by BenTheElder** [comment]
sorry about that, I'm also updating it to match the docs, it looks like upstream did this a year ago and we missed it

**Comment by reshdebug** [comment]
Thank you once again! @BenTheElder
