### ISSUE TITLE
Build node-image using apt build type fails

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes-sigs/kind#103]
Trying to build the `node-image` using the `apt` type fails:
```
INFO[15:00:54] Pulling image: k8s.gcr.io/kube-apiserver:v1.12.2 ... 
ERRO[15:00:55] Image build Failed! exit status 1            
FATA[15:00:56] Error building node image: exit status 1
```

The problems seems to be that during the build process, `kind` tries to save the required images to a temporary directory of the type `/tmp/kind-node-imageXXXXXXXXX/bits/images`:
https://github.com/kubernetes-sigs/kind/blob/6177a98223feedc7b8ab2e860b2311cb1f739acf/pkg/build/node/node.go#L368-L369

Extracting the output from the `docker.Save` command:
```
INFO[15:00:55] exit status 1                                
INFO[15:00:55] failed to save image: unable to validate output path: directory "/tmp/kind-node-image241009176/bits/images" does not exist
```

## Possible solution
During a previous step in the build process, build artifacts are moved to the temporary build directory by `populateBits`. This call will create the sub directory `bits` within the build directory `/tmp/kind-node-imageXXXXXXXX`.

https://github.com/kubernetes-sigs/kind/blob/6177a98223feedc7b8ab2e860b2311cb1f739acf/pkg/build/node/node.go#L150-L167

We could add another `exec.Command` here to create the `images` sub directory within `bits`.

Another possibility, would be to do this when the images are being pulled in (here we could more easily track where directories are being created)
https://github.com/kubernetes-sigs/kind/blob/6177a98223feedc7b8ab2e860b2311cb1f739acf/pkg/build/node/node.go#L359-L375

/kind bug

**Comment by BenTheElder** [comment]
So this directory is missing on the host AFAICT, we should add an os.MkdirAll()

https://github.com/kubernetes-sigs/kind/blob/6177a98223feedc7b8ab2e860b2311cb1f739acf/pkg/build/node/node.go#L368-L369

->
something like:
```go
  // outside the loop
 pullDir := path.Join(dir, "bits", "images")
 os.MkdirAll(pullDir, 0777) // we should handle this error in the real code

  // in the loop
 pullTo := path.Join(pullDir, pullName)
 err = docker.Save(image, pullTo) 
```
Thanks for reporting and looking into this!
