### ISSUE TITLE
Support runtimeClass feature 

### ISSUE THREAD

**Issue by gnmahanth** [kubernetes-sigs/kind#1042]
**What would you like to be added**: 
Support Kubernetes runtimeClass feature
(https://kubernetes.io/docs/concepts/containers/runtime-class/)

**Why is this needed**:
If there is a need to test untrusted workload having a runtime like gvisor, ignite or kata will be helpful.
Since kind already have containerd as CRI and it can support multiple runtime through containerd plugins.

**Comment by BenTheElder** [comment]
Ignite and kata are not going to work well inside the kind nodes (kvm being a non-containerized resource that we'd leak), though we'd like to use them as a backend for kind's _nodes_ possibly at some point.

runsc in the default ptrace mode would actually probably be fine though 🤔

We'd have to look into the overhead.

**Comment by aojea** [comment]
For reference

https://github.com/gnmahanth/kind-runsc

thanks @gnmahanth , awesome work documenting it

**Comment by BenTheElder** [comment]
revisiting this in the next cycle.

**Comment by BenTheElder** [comment]
One issue is:
> gVisor builds on x86_64 and ARM64. Other architectures may become available in the future.

But Kubernetes supports more than this.

**Comment by BenTheElder** [comment]
Technically runtimeClass is supported, but we don't ship any special runtimeclasses[^1]. 

We're opting not to ship non-standard extensions otherwise at this time.
 
[^1]: We actually have to ship one "test" runtime class for testing Kubernetes, it is actually the same as the "normal" runtimeClass.
