### ISSUE TITLE
cobra errors are not logged

### ISSUE THREAD

**Issue by prometherion** [kubernetes-sigs/kind#1047]
**What happened**:

I tried to load images into my brand new KinD cluster but didn't know how `load docker-images` works, so I started typing and notice I was missing the first argument that has to be the Docker image to load.

**What you expected to happen**:

Expecting to see the error `name of image is required` printed on _standard output_ but wasn't there.

**How to reproduce it (as minimally and precisely as possible)**:

Just issue `kind load docker-image`: nothing is printed.

**Anything else we need to know?**:

Going to prepare little PR: just need to handle it at Cobra level with a simple `fmt.Println`

**Environment:**

- kind version: (use `kind version`): v0.6.0-alpha+0ff0546bc81543
- Kubernetes version: (use `kubectl version`): _not relevant_
- Docker version: (use `docker info`): _not relevant_
- OS (e.g. from `/etc/os-release`): _not relevant_

**Comment by BenTheElder** [comment]
They should be logged now.
Thanks again for reporting this and sending a patch!
