### ISSUE TITLE
'kind get kubeconfig' returns internal host/IP instead of docker-forwarded port

### ISSUE THREAD

**Issue by maelvls** [kubernetes-sigs/kind#1051]
In https://github.com/kubernetes-sigs/kind/pull/1029 (see [discussion](https://github.com/kubernetes-sigs/kind/pull/1029/files/e3fafcd3edee0bb1c63953ee5aade82af6992832#r342542332)), the 'rewrite' of the container's host and port instead of 127.0.0.1 + the forwarded port when running `kind get kubeconfig` [was removed](https://github.com/kubernetes-sigs/kind/pull/1029/files/e3fafcd3edee0bb1c63953ee5aade82af6992832#diff-7905fe94b72f54cdd03add9ff06088c8L139-L143). It looked like:

```go
// matches kubeconfig server entry like:
//    server: https://172.17.0.2:6443
// which we rewrite to:
//    server: https://$ADDRESS:$PORT
var serverAddressRE = regexp.MustCompile(`^(\s+server:) https://.*:\d+$`)
```

It seems like `kind get kubeconfig` doesn't reflect 127.0.0.1 + forwarded port anymore; instead, it contains the container's host & port.

As a result, `kind get kubeconfig --internal` does the same as `kind get kubeconfig` (as of aea9a47)

Maybe something off in the `docker inspect` command issued GetAPIServerEndpoint: https://github.com/kubernetes-sigs/kind/blob/aea9a47507085fe7bf89f7f65d31ead92876a42d/pkg/internal/cluster/kubeconfig/kubeconfig.go#L92-L100

**How to reproduce it**:

```
$ GO111MODULE=on go get sigs.k8s.io/kind@aea9a47
$ kind create cluster

$ docker ps --format '{{ .Image }} {{ .Ports }}'
kindest/node:v1.16.2 127.0.0.1:54882->6443/tcp

$ kind get kubeconfig
apiVersion: v1
clusters:
- cluster:
    server: https://172.17.0.2:6443
```

But I expected:

```
$ kind get kubeconfig
apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:54882
```

**Environment:**

- kind version: (use `kind version`): aea9a47 installed with `GO111MODULE=on go get sigs.k8s.io/kind@master`
- Kubernetes version: (use `kubectl version`): v1.16.2
- Docker version: (use `docker info`): engine 19.03.4, client 19.03.4
- OS (e.g. from `/etc/os-release`): macOS 10.14.6

**Comment by maelvls** [comment]
looks like external and internal are inverted:

https://github.com/kubernetes-sigs/kind/blob/aea9a47507085fe7bf89f7f65d31ead92876a42d/pkg/cluster/provider.go#L82-L87

but Get expects 'external'

**Comment by BenTheElder** [comment]
d'oh :(

**Comment by BenTheElder** [comment]
thanks for spotting, reporting, and fixing this!
