### ISSUE TITLE
Use ComponentConfig

### ISSUE THREAD

**Issue by luxas** [kubernetes-sigs/kind#107]
See my talk on how to do it, but you probably already know ;)
https://sched.co/FuKB
Sample repo: https://github.com/luxas/sample-config

**Comment by BenTheElder** [comment]
Yeah! Definitely one of the reasons I used go, we should get around to fixing this :-)
/assign @munnerz

**Comment by neolit123** [comment]
BTW, the codecs in api-machinery are bound to json-iter and do not support strict unmarshalling. json-iter supports it except that it's options are hardcoded.

so if there is a plan for a switch to unmarshaling from codecs instead of plain yaml.UnsmarshalStrict, possibly yaml.UnmarshalStrict has to be moved as a pre-step before decoding.

**Comment by neolit123** [comment]
> I'm not sure I follow there, what would that look like roughly?

```
sigs.k8s.io/yaml.UnmarshalStrict(bytes, externalConfigStructInstance) // #1
...
k8s.io/apimachinery/pkg/runtime.DecodeInto(myScheme.Codecs.UniversalDecoder(), bytes, internalConfigStructInstance);
```

validation happens at `#1`.

**Comment by neolit123** [comment]
commented: https://github.com/kubernetes/community/pull/2354#issuecomment-439631806
i think that was the KEP thread.

**Comment by BenTheElder** [comment]
Hmm, I think we should teach the decoder to handle strict instead then, our homebrew GVK thing works OK if not being the best thing to maintain long term. It seems like everyone will benefit from a strict option as discussed here now by @neolit123 and co. https://github.com/kubernetes/community/pull/2354#issuecomment-439633827

**Comment by luxas** [comment]
@BenTheElder @neolit123 Please redirect discussion to actionable, generic work items of the upcoming `k8s.io/component` repo you'll utilize. https://docs.google.com/document/d/1nZnzJD9dC0xrtEla2Xa-J6zobbC9oltdHIJ3KKSSIhk/edit
Thanks!

**Comment by alejandrox1** [comment]
@BenTheElder @munnerz is there any chance that I could help with this? :-)

**Comment by BenTheElder** [comment]
currently we aren't configuring things covered by k8s.io/component directly (potentially kubeadm is). we'll adopt it when we configure them.

**Comment by neolit123** [comment]
kind is already doing parts of the componentconfig spec:
https://github.com/kubernetes-sigs/kind/tree/master/pkg/cluster/config

**Comment by luxas** [comment]
That's very cool, thanks @fabriziopandini. Do you think there's anything more that needs to be done yet or is this initially done?

**Comment by fabriziopandini** [comment]
@luxas after https://github.com/kubernetes-sigs/kind/pull/147 merge there will be internal/external config, conversions, defaulting, scheme that is what required for implementing multi-node. 
Let's do a pair code review afterwards to see if something is missing/could be improved

**Comment by luxas** [comment]
> Let's do a pair code review afterwards to see if something is missing/could be improved

Sounds good @fabriziopandini!

**Comment by neolit123** [comment]
this timeout out it seems.

kind already supports component configuration.
once component-base is ready for wider consumption some of it's utils can be leveraged here if appropriate.

**Comment by BenTheElder** [comment]
I'm pretty happy with our component configuration even if it does use a small inline implementation that is not the component-base tooling. 

We can revisit that in the future, but I don't see much upside now that we have it, pulling in those tools makes it harder to embed in projects like kinder, which is probably not relevant to most component-base projects but is to kind.
