### ISSUE TITLE
v1alpha4

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#1070]
In order to minimize the odds of notably breaking releases in the future we should round out v0.6 with a trivial `v1alpha4` config version that at least moves us out of the `*.k8s.io` namespace into `x-k8s.io` for kind's APIs to clarify that they are not official kubernetes APIs, in line with the API review requirements and guidelines.

### I propose the following minimal changes:

- Updated GVK:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
```
- Simply use strings (instead of string -> int) for "enums" I.E. for `MountPropagation` and `PortMappingProtocol`.  This will simplify parsing and make the on-disk format match the in-memory format. It's technically more expensive but not in a way that is material for kind ...

### And the following tentative additional feature:

Support for containerd config patches. This is necessary to sanely solve https://github.com/kubernetes-sigs/kind/issues/110. 

Rather than adding these to `v1alpha3` and possibly not working with previous versions of kind (especially now that we strict parse config!) these should be added to a new API version. 

Essentially these should work like kubeadm config patches, but the non-json-6902 format should parse as toml initially instead of yaml, and we don't need document separation or any GVK sniffing / matching so it should be much simpler.

Concretely this means `containerdConfigPatches []string` and `containerdConfigPatchesJSON6902 []string` fields, and some minor-ish work to apply them.

Originally I intended to leverage the built in merging in v1.3.0, but it is quite insufficient / the design does not seem to be intended for this use case (rather, for kata / gVisor runtime drop-ins).

### Additionally ...

We should transform `kind.sigs.k8s.io` docker labels to `kind.x-k8s.io` labels, but in v0.6 we should apply and list BOTH forms so as to continue to detect and manage existing clusters etc.

In the future we can drop the k8s.io labels.

When this apiVersion exists, we should start a new "Configuration" guide / page under /users in the docs to cover all of the features instead of making the quick start too long or relying on the godoc contents. 

We should still link to the godoc contents for completeness.

**Comment by aojea** [comment]
Now that the provider code is properly isolated, should we add provider to the API?
I think that  we should also add the provider bridge too

```// Provider contains kind runtime provider settings
type Provider struct {
	// Provider is the runtime provider, currently it can be docker
	Provider string `yaml:"provider,omitempty"`
	// Bridge is the bridge used by the provider runtime
	Bridge string `yaml:"bridge,omitempty"`
```

**Comment by BenTheElder** [comment]
> can you elaborate more what's the trade-off ?

Pro: We can use struct literals to represent the types on disk

Con: Int32 uses less ram than the string values. (Except we only have a few of these and the valid values are short)

Con: Comparing Int32 is cheaper than comparing strings (except we only have a few of these and the valid values are short and this is not even on our performance radar).

AKA: We mimic-ed the upstream types which have different considerations regarding internal representation.

> Now that the provider code is properly isolated, should we add provider to the API?

No. We only have one implementation so we don't actually know that we have everything sufficiently decoupled from that implementation and even once we do the same kind config should generally work across providers in the same way that it works across cluster names.

This should be a flag or env, the latter would allow an identical test setup to run across hosts using different backends easily.

> I think that we should also add the provider bridge too

We should not add fields that are not implemented, and we lack details on how this will be implemented correctly.

We should add something like this in a future version when we have a plan and it probably should be under networking.

It also probably shouldn't be called bridge when that happens because users will use it to specify existing non-bridge networks.

**Comment by tao12345666333** [comment]
> Support for containerd config patches. This is necessary to sanely solve #110.

SGTM.

**Comment by BenTheElder** [comment]
Should add -- Prior art for a project actually being in x-k8s.io is in cluster API which has:
- Group: cluster.x-k8s.io
- Version: v1alpha2

=> `apiVersion: cluster.x-k8s.io/v1alpha2`
For the primary API of Cluster.

**Comment by BenTheElder** [comment]
The base types are added, the patch fields are not yet.

**Comment by BenTheElder** [comment]
I wrote the TOML patch runtime, but need to test it more extensively.

**Comment by BenTheElder** [comment]
ref: https://github.com/kubernetes-sigs/kind/issues/1084 for applying patches to individual nodes.

**Comment by BenTheElder** [comment]
fixed by https://github.com/kubernetes-sigs/kind/pull/1081
