### ISSUE TITLE
consider using klog for logging

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#109]
I think https://github.com/kubernetes/klog is the way forward for the ecosystem, and after some experimenting I think structured logging makes the most sense for server / syslog type logs, not debugging a CLI.

I don't love glog/klogs's line formatting, but it seems like the way forward to integrate in the ecosystem.

cc @munnerz

**Comment by BenTheElder** [comment]
@alejandrox1 FYI you should not reference issues from commits, because github will reference them across forks. so when someone merges your PR to another fork github will try to close it here :grimacing: 

The UX for those references is a bit wonky and has been a problem across the project.

**Comment by alejandrox1** [comment]
@BenTheElder :+1: won't happen again. 
Should I amend the commit on #115 ?

**Comment by BenTheElder** [comment]
That would be great 🙂

Also don't worry about it though, just a note. We have a few issues in k8s that get spammed & closed with this very badly 😅

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/klog/tree/master/klogr needs investigating

**Comment by neolit123** [comment]
i'm mostly -1 on structured logging for kind at this point.
due to the scope of the project, i doubt it will face the need for structured logging.

also, the current logr usage in e.g. C-API seems a bit underwhelming and i don't see obvious benefits.

**Comment by BenTheElder** [comment]
we can use it without stuctured logging
mainly my concern is improving the library use case. I have also been thinking about your point about logging to a file though... :thinking:

**Comment by neolit123** [comment]
> we can use it without stuctured logging
mainly my concern is improving the library use case

but there might be no benefits from using logr if we are not using it with structures.

> I have also been thinking about your point about logging to a file though

i was talking about Ilya from Weave about this recently in a PR review as k/k has a similar problem in a lot of places.

front end and back end should have a single point of connection in terms of logging.
this is the point where the front end decides to which streams the backend is going to write to.

we can consider the consumers of the kind library to be a "frontend".

also the go stdlib has cool features like:
https://golang.org/pkg/io/#MultiWriter
which allows you to pipe to a standard stream and a file at the same time, so consumers can do that.

**Comment by BenTheElder** [comment]
realistically though they will want control over EG how much logging, /shrug
most ecosystem projects are klog/glog including kubeadm, cluster-api, etc. right?

The benefit is seamlessly integrating with their stacks. we don't depend heavily on logging anyhow.

**Comment by neolit123** [comment]
> realistically though they will want control over EG how much logging

well logrus has that, so i don't think that's a problem comparing klog vs logrus.

> most ecosystem projects are klog/glog including kubeadm, cluster-api, etc. right?

that is true.
we can easily make a switch to klog and hardcode klog in the backend too.

**Comment by BenTheElder** [comment]
there is more discussion about logging ongoing it seems.. but I think we should align with the ecosystem for easiest embedding. I imagine the cluster-api would appreciate this.

**Comment by neolit123** [comment]
the only consumers that will suffer from klog being in the backend would be those that want to vender kind as a backend but use a different logger for their frontend.

**Comment by BenTheElder** [comment]
let's look at https://github.com/go-logr, we could use zap or klog as the default backend but leave our global logr.Logger instance swappable in our own tiny log package. Consumers could wire up their logging backend to logr.

**Comment by BenTheElder** [comment]
/assign
xref: https://github.com/kubernetes-sigs/kind/issues/176 which will make this not so bad for users of other libraries, it will be possible to wire up an alternative
/lifecycle active

**Comment by BenTheElder** [comment]
We considered it, there will be a logging shim of some sort that makes it possible to wire to your own logging backend, but we will probably not depend on klog in the kind CLI.
