### ISSUE TITLE
support `KIND_CLUSTER_NAME`

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#1094]
needs a little more thought but roughly see https://github.com/kubernetes-sigs/kind/issues/850

moving tracking over here, the bulk of #850 (the breaking and most useful parts imho) landed for v0.6.0, this will be an interesting additional feature for v0.7.0

**Comment by prksu** [comment]
@BenTheElder can i do this one?

some question. currently, we have `"kind"` as `DefaultClusterName` should we replace it with env variable? or still used it if KIND_CLUSTER_NAME env not set?

**Comment by BenTheElder** [comment]
Hi, you can but I recommend a "good first issue" or "help wanted" for starting usually. We are not going to merge this before v0.6.0

> some question. currently, we have "kind" as DefaultClusterName should we replace it with env variable? or still used it if KIND_CLUSTER_NAME env not set?

The environment variables should only be used when set and when the flag is not set. Otherwise we should maintain the default. (See #850)

This logic should be de-duplicated in an internal package (something like pkg/cmd/internal/flag).

**Comment by prksu** [comment]
@BenTheElder just created a PR on #1099 

please take a look 😁
