### ISSUE TITLE
Question about "kind build base-image"

### ISSUE THREAD

**Issue by chenliu1993** [kubernetes-sigs/kind#1095]
Hi, 
    I am new to kind and I am using 'kind build base-image' to build a base image to run, but while I am running this image with docker, the 'entrypoint' will throw an error "no kind directory". So I checked the file about kind/build image and found that '/kind' folder is 'mkdir'ed while creating a node image. Is this a logically step or '/kind' folder is created somewhere else while execing 'kind build base-image'?
    Thanks for the answer.

**Comment by BenTheElder** [comment]
You need a checkout of kind to run this

In the future we may remove it, it's basically just a docker build now.

**Comment by chenliu1993** [comment]
> You need a checkout of kind to run this
> 
> In the future we may remove it, it's basically just a docker build now.

Got it! Thank you
