### ISSUE TITLE
Docker not running results in unclear error message during kind create cluster

### ISSUE THREAD

**Issue by asaf-erlich** [kubernetes-sigs/kind#1101]
**What happened**:
For the first time after installing kind on my mac I ran `kind create cluster --name=clusterapi` and saw the error message:
`Error: could not list clusters: failed to list nodes: exit status 1`.

**What you expected to happen**:
A cluster to be created? After starting up docker on mac it worked correctly. Since I was following instructions for the first time I wasn't sure exactly what to expect, but these are the documented steps for creating a first cluster.

**How to reproduce it (as minimally and precisely as possible)**:
On mac (potentially on any other OS as well where you can disable docker daemon) do not turn on / disable docker daemon. Then run `kind create cluster`. The first attempt it makes to list nodes should fail with the above error message.

**Anything else we need to know?**:
To me this is just a problem with error messaging. Arguably documentation could be updated to mention the dependency, but clear error messaging is more important in my opinion.

**Environment:**

- kind version: (use `kind version`): v0.5.1
- Kubernetes version: (use `kubectl version`) :v1.16.3
- Docker version: (use `docker info`): 19.03.4
- Docker desktop version: 2.1.0.4
- OS (e.g. from `/etc/os-release`): Mac OS version 10.14.6

**Comment by BenTheElder** [comment]
Are you on v0.5.1?
In HEAD this has changed a bit.

**Comment by BenTheElder** [comment]
Sorry yes I see that you are.

In HEAD we have different messaging. 

Please do have docker running to use Kubernetes IN Docker, or pretty much any docker based tool 😅
