### ISSUE TITLE
404 url

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes-sigs/kind#1103]
|file_path|url|
|----|----|
|kind/site/content/docs/user/quick-start.md |https://github.com/kubernetes-sigs/kind/tree/master/pkg/build/base/sources|
|kind/site/content/docs/design/initial.md| https://github.com/kubernetes-sigs/kind/tree/master/images/base/entrypoint|

**Comment by hwdef** [comment]
I will fix these

**Comment by tao12345666333** [comment]
#1104  and #1105 

/close
