### ISSUE TITLE
Helm 3 in Kind

### ISSUE THREAD

**Issue by minxuancao** [kubernetes-sigs/kind#1118]
Does Kind have any plan to use helm 3 in the near future?

**Comment by BenTheElder** [comment]
helm should work with kind but we have no plans to do anything special there

**Comment by tao12345666333** [comment]
Yep, all of Helm v2 and v3 can work with kind. We don't need to do anything for it. 

> Helm v2 with kind, need you install Tiller, but Helm v3 will use your KUBECONFIG directly (unless you want more granular control over Helm's permissions)

**Comment by phcollignon** [comment]
I tested Helm 3 with Kind 0.5.1 and no issues so far ..
Helm 3 does not use Tiller server component anymore so it is even easier to install

**Comment by BenTheElder** [comment]
Hoping this is answered now :-)
