### ISSUE TITLE
Cannot create cluster in Arch Linux with ZFS Storage Driver

### ISSUE THREAD

**Issue by selfuryon** [kubernetes-sigs/kind#1121]
**What happened**:
Tried to create a cluster with `kind create cluster` and get:
```
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.16.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
```
In kubelet service logs:
```
ov 22 00:03:27 kind-control-plane kubelet[262]: E1122 00:03:27.228069     262 kuberuntime_manager.go:710] createPodSandbox for pod "kube-scheduler-kind-control-plane_kube-system(4e1bd6e5b41d60d131353157588ab020)" failed: rpc error: code = Unknown desc = failed to create containerd task: failed to mount rootfs component &{overlay overlay [workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/73/work upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/73/fs lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1/fs]}: invalid argument: unknown
```
Is it a problem with zfs storage driver? Why we see  overlayfs there? 
**What you expected to happen**:
Get a working cluster

**How to reproduce it (as minimally and precisely as possible)**:
Don't think that it's exactly a reason but I use Arch Linux with ZFS and docker with ZFS Storage Driver 

**Anything else we need to know?**:
No.
**Environment:**

- kind version: kind v0.6.0 go1.13.4 linux/amd64
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
- Docker version: $ docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0lugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: a
  Stopped: 0
 Images: 2
 Server Version: 19.03.5-ce
 Storage Driver: zfs
  Zpool: zroot
  Zpool Health: ONLINE
  Parent Dataset: zroot/images/docker
  Space Used By Parent: 126976
  Space Available: 385054380032
  Parent Quota: no
  Compression: on
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc version: d736ef14f0288d6993a1845745d6756cfc9ddd5a
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.3.11-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.36GiB
 Name: yakovlev-pc
 ID: F254:ZUHI:6HRC:JJRP:TBVP:5WP3:EV2V:P2HZ:JC2H:7AQW:H4ES:CUNG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
- OS (e.g. from `/etc/os-release`): Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
$ uname -a
Linux yakovlev-pc 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64 GNU/Linux
Also including some logs:
* ` kind create cluster  -v7 --retain `: [logs-err.txt](https://github.com/kubernetes-sigs/kind/files/3877370/logs-err.txt)
* `kind export logs`: [logs.tar.gz](https://github.com/kubernetes-sigs/kind/files/3877372/logs.tar.gz)

**Comment by cunei** [comment]
Same here on Ubuntu, using the ZFS storage driver for Docker.

**Comment by BenTheElder** [comment]
Please see the known issues in the docs. Overlay and AUFS are known to
work, but not ZFS/btrfs. Afaik both Kubernetes and docker in docker have
issues with them.

Unfortunately you'll need to use a different storage driver. There's
nothing we can do in kind as far as I know

**Comment by BenTheElder** [comment]
However it seems we're missing ZFS there, I thought we had that :(
https://kind.sigs.k8s.io/docs/user/known-issues/#docker-on-btrfs

We'll need to update that

**Comment by BenTheElder** [comment]
documented in https://github.com/kubernetes-sigs/kind/issues/1121

I wish we could fix this, but this is way out of scope for us -- the issues should be in the upstream projects and I'm not a filesystem expert :sweat_smile: 

Highly recommend `overlay2` as the container filesystem for using kind (and docker in general).

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes-sigs/kind/issues/1416#issuecomment-600438973
