### ISSUE TITLE
how can i create a cluster ? should i fanqiang to use internet   it is not ok use domestic network ?

### ISSUE THREAD

**Issue by licslan** [kubernetes-sigs/kind#1125]

**Comment by tao12345666333** [comment]
You can use kind directly.

Kind's node image include all images. You just need to make sure you can access dockerhub.

**Comment by BenTheElder** [comment]
xref https://github.com/kubernetes-sigs/kind/issues/1124 there is currently a bug in which case the most recent images will be missing an image from dockerhub

Though again they only need to pull from docker hub, not gcr.io

**Comment by BenTheElder** [comment]
except for #1124 kind should work as long as you can pull the `kindest/node` docker image matching the one you create the cluster with via `--image` or config, the set of images including the default is listed in the release notes.

you should not need any internet access once this is pulled to your host.

hope that answers your question, please re-open or file another one if not!
