### ISSUE TITLE
Add option to specify kubeconfig when creating kind clusters

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/kind#113]
The `kind create cluster` command creates a `~/.kube/kind-config-<name>` kubeconfig file to access that kind cluster. When working with multiple clusters, you end up with multiple of these files. Could we add an option to the `kind create cluster` command (e.g. `--kubeconfig`) so that the user can provide a file to use for all the kubeconfigs such as `~/.kube/config`. I've also filed #112, which would need to be resolved first.

**Comment by BenTheElder** [comment]
We've also debated just writing to this in the first place like most deployers, cc @Katharine @munnerz @justinsb 

We can definitely add a `--kubeconfig` as well
/assign

**Comment by font** [comment]
> We've also debated just writing to this in the first place like most deployers

Yeah I think that would be consistent with most other tools. Then the `--kubeconfig` option could be used to implement the existing default behavior i.e. separate `kind-config-<name>` files.

**Comment by BenTheElder** [comment]
Yeah, I just dislike that this seems racy (writing to the shared file) but it seems to be done by like, every other deployer in existence, so I guess that's OK.

We'd also have to consider if deleting the cluster should remove those then, since before we were going to just implement deleting the file.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/112 seems less trivial than initially expected, so far I think users have ultimately been pretty fine with how the kubeconfig works and it's been reliable.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/850

**Comment by aojea** [comment]
/close

fixed by #1029
