### ISSUE TITLE
kind need to mount /usr/src to node container

### ISSUE THREAD

**Issue by vazhem** [kubernetes-sigs/kind#1135]
**What happened**:
Kind fail to start cluster when running inside a docker container in Ubuntu 18.04.
Kind fails to write config for kubelet because it cannot detect config of the kernel.
Similar change was added to k8s https://github.com/kubernetes/kubernetes/pull/69614

**What you expected to happen**:
cluster created successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Install Ubuntu 18.04 (used Ubuntu in vmplayer)
Run SLES-SP4 docker container in it.
Try to create cluster using kind 0.6.0 inside this docker container.

**Anything else we need to know?**:
Issue is fixed once I change kind to mount /usr/src in provision.go https://github.com/kubernetes-sigs/kind/blob/v0.6.0/pkg/internal/cluster/providers/docker/provision.go#L185
(same should be mounted to the docker container where kind is running of course).

**Environment:**

- kind version: 0.6.0:
- Kubernetes version: v1.16.3
- Docker version: 17.09.1-ce
- OS (e.g. from `/etc/os-release`): SLES-SP4 docker container in Ubuntu 18.04

**Comment by BenTheElder** [comment]
Could you please share logs from the failure?

kind only slightly supports running inside your own docker in docker and there's frequently issues with this that are not related.

https://github.com/kubernetes/kubernetes/pull/69614 does not seem related.

IIRC kubeadm should only be warning based on kernel config, NOT failing.

**Comment by BenTheElder** [comment]
17.09 is quite old. (~2 years?) https://kind.sigs.k8s.io/docs/user/known-issues/#older-docker-installations

**Comment by vazhem** [comment]
Re-run it without modified kind... You are right, seems the problem appears only when kind docker container itself does not get /usr/src mounted, but when kind does not mount it inside node container does not matter.
