### ISSUE TITLE
Pull image failed

### ISSUE THREAD

**Issue by IzekChen** [kubernetes-sigs/kind#1146]
While I try to create the cluster, I wasn't able to pull the image.
Seems like the k8s.gcr.io is not exist anymore.
Probably rename to something else or mirrorgooglecontainers
I have try to pull the image by myself and give them a tag
But still have no luck to get it work.

I1206 08:01:15.538165     118 checks.go:249] validating the existence and emptiness of directory /var/lib/etcd
I1206 08:01:15.545436     118 checks.go:844] pulling k8s.gcr.io/kube-apiserver:v1.18.0-alpha.0.1502_93c9085e8a934c
I1206 08:01:15.560767     118 checks.go:844] pulling k8s.gcr.io/kube-controller-manager:v1.18.0-alpha.0.1502_93c9085e8a934c
I1206 08:01:15.574422     118 checks.go:844] pulling k8s.gcr.io/kube-scheduler:v1.18.0-alpha.0.1502_93c9085e8a934c
I1206 08:01:15.587863     118 checks.go:844] pulling k8s.gcr.io/kube-proxy:v1.18.0-alpha.0.1502_93c9085e8a934c
I1206 08:01:15.602597     118 checks.go:844] pulling k8s.gcr.io/pause:3.1
I1206 08:01:15.615892     118 checks.go:844] pulling k8s.gcr.io/etcd:3.4.3-0
I1206 08:01:15.629013     118 checks.go:844] pulling k8s.gcr.io/coredns:1.6.5
	[WARNING ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.18.0-alpha.0.1502_93c9085e8a934c: output: time="2019-12-06T08:01:15Z" level=fatal msg="pulling image failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService"
, error: exit status 1
	[WARNING ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.18.0-alpha.0.1502_93c9085e8a934c: output: time="2019-12-06T08:01:15Z" level=fatal msg="pulling image failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService"
, error: exit status 1
	[WARNING ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.18.0-alpha.0.1502_93c9085e8a934c: output: time="2019-12-06T08:01:15Z" level=fatal msg="pulling image failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService"
, error: exit status 1
	[WARNING ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.18.0-alpha.0.1502_93c9085e8a934c: output: time="2019-12-06T08:01:15Z" level=fatal msg="pulling image failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService"
, error: exit status 1
	[WARNING ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: time="2019-12-06T08:01:15Z" level=fatal msg="pulling image failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService"
, error: exit status 1
	[WARNING ImagePull]: failed to pull image k8s.gcr.io/etcd:3.4.3-0: output: time="2019-12-06T08:01:15Z" level=fatal msg="pulling image failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService"
, error: exit status 1
	[WARNING ImagePull]: failed to pull image k8s.gcr.io/coredns:1.6.5: output: time="2019-12-06T08:01:15Z" level=fatal msg="pulling image failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService"
, error: exit status 1
I1206 08:01:15.635417     118 kubelet.go:64] Stopping the kubelet

**Comment by chenliu1993** [comment]
hi, I run into the same issue, how you solve this problem? thanks

**Comment by IzekChen** [comment]
I1206 08:01:15.545436 118 checks.go:844] pulling k8s.gcr.io/kube-apiserver:v1.18.0-alpha.0.1502_93c9085e8a934c
I1206 08:01:15.560767 118 checks.go:844] pulling k8s.gcr.io/kube-controller-manager:v1.18.0-alpha.0.1502_93c9085e8a934c
I1206 08:01:15.574422 118 checks.go:844] pulling k8s.gcr.io/kube-scheduler:v1.18.0-alpha.0.1502_93c9085e8a934c
I1206 08:01:15.587863 118 checks.go:844] pulling k8s.gcr.io/kube-proxy:v1.18.0-alpha.0.1502_93c9085e8a934c

From the logs above, there have a docker version, go search the same image then pull it.
Or you can give the image a tag with the specific name.
Then it will works

**Comment by chenliu1993** [comment]
got it, thanks!

**Comment by BenTheElder** [comment]
uh, creating a cluster shold not pull any of these. how are you creating the cluster?

**Comment by BenTheElder** [comment]
are you building a custom node image?

**Comment by chenliu1993** [comment]
No, actually I am using crictl to consume containerd.sock without docker on OS. Maybe this is a version issue I found others also mentioning this problem but I still cannot found a workaround. Sorry for not making issue clearly and for your reply.

**Comment by errordeveloper** [comment]
I've noticed this when I enabled devmapper in containerd, also I can see this in containerd logs:

```
msg="failed to load plugin io.containerd.grpc.v1.cri" error="failed to create CRI service: failed to find snapshotter \"devmapper\""
```
So I'm guessing the devmapper snapshotter is not supported in CRI, but it does work otherwise as I'm able to run `ctr images pull`.
