### ISSUE TITLE
`kind get kubeconfig` cannot handle additional containers linked to the control plane

### ISSUE THREAD

**Issue by electrofelix** [kubernetes-sigs/kind#1153]
**What happened**: Using a NodePort ingress with kind and running additional socat containers in order to provide predictable local ports for communication with the internal ports results in kind being unable to retrieve the kubeconfig.yaml

See https://banzaicloud.com/blog/kind-ingress/ for an example on what was run

**What you expected to happen**: Attaching additional containers to forward ports should not cause any issues

**How to reproduce it (as minimally and precisely as possible)**:
```
kind create cluster
# cluster creation

kind get kubeconfig
# kubeconfig displayed

kubectl config use-context kind-kind
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/baremetal/service-nodeport.yaml

PORT_OFFSET=8200
for port in 80 443
do
    node_port=$(kubectl get service -n ingress-nginx ingress-nginx -o=jsonpath="{.spec.ports[?(@.port == ${port})].nodePort}")
    offset_port=$((${PORT_OFFSET}+${port}))
    docker run --rm -d --name ${KIND_CLUSTER_NAME:-kind}-kind-proxy-${port} \
      --publish 127.0.0.1:${offset_port}:${port} \
      --link ${KIND_CLUSTER_NAME:-kind}-control-plane:target \
      alpine/socat -dd \
      tcp-listen:${port},fork,reuseaddr tcp-connect:target:${node_port}
done
# two container IDs outputted

kind get kubeconfig

ERROR: failed to get role for node: command "docker inspect --format '{{ index .Config.Labels "io.k8s.sigs.kind.role"}}' kind-control-plane,kind-kind-proxy-443/target,kind-kind-proxy-80/target" failed with error: exit status 1
```

**Anything else we need to know?**:

The problem appears to be either in https://github.com/kubernetes-sigs/kind/blob/69e0c92e79ef897307cb7ad3d7cc3b7c2886fd4f/pkg/cluster/internal/providers/docker/provider.go#L93-L102 or in the function that would call that in this case failing to remove the additional linked nodes before looking to do additional parsing.
In running the following command directly locally:
```
$ docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster=kind --format {{.Names}}
kind-control-plane,kind-kind-proxy-443/target,kind-kind-proxy-80/target
```
the output contains the additional containers that are attached and shows how they appear in the output above in getting passed to the docker inspect command. Removing `--no-trunc` results in just the name of the container appearing, however it's unclear whether that is the correct behaviour as it's possible other functions may want the full details to include any linked containers.

**Environment:**

- kind version: (use `kind version`): `kind version 0.6.0`
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-16T01:01:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
```
Client:
 Debug Mode: false

Server:
 Containers: 16
  Running: 8
  Paused: 0
  Stopped: 8
 Images: 815
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-72-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 23.52GiB
 Name: ######
 ID: ######
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: #########
 HTTPS Proxy: #########
 No Proxy: localhost,127.0.0.1,localaddress,.localdomain.com,192.168.0.0/16
 Username: #######
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/1116

**Comment by electrofelix** [comment]
Is there any alternative here in this case to link until kind makes use of the user defined network?

Or would it be acceptable to code up the equivalent of retrieving the container ID and then asking docker for the container name instead of attempting to retrieve it directly with `docker ps`?:
```
for i in $(docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster=kind --format {{.ID}}); do docker inspect ${i} --format {{.Name}}; done
```

I couldn't find a definition of what `--no-trunc` is supposed to truncate or not regarding output even within the docker codebase (though I couldn't find the exact location to see what it would truncate from the output), so I'm presuming it was included because it was assumed that it would be possible for the container name to be truncated if not present.

**Comment by BenTheElder** [comment]
> Is there any alternative here in this case to link until kind makes use of the user defined network?

use port forwards on the nodes

https://kind.sigs.k8s.io/docs/user/resources/#using-contour-ingress-with-kind

we need to get an ingress guide up in the official docs soon.

> Or would it be acceptable to code up the equivalent of retrieving the container ID and then asking docker for the container name instead of attempting to retrieve it directly with docker ps?:

unfortunately not, the internal API for kind revolves around node names. this would be a fairly breaking change.

see #1116 for reasoning, but basically docker chose to strongly deprecate linked containers upstream so we're not going to invest complexity in supporting them.

I am however working on user defined networks.

**Comment by electrofelix** [comment]
> use port forwards on the nodes
>
> https://kind.sigs.k8s.io/docs/user/resources/#using-contour-ingress-with-kind

My understanding was I can only talk directly to the individual containers and cannot use this to talk to the ingress? But I see I can do a port-forward to the `service/ingress-nginx`, thanks I was assuming this wouldn't work in the expected way. Thanks hadn't thought of that.

It does make some things a little more awkward that running two socat docker containers would have access to the ports 80 & 443 on the local machine so that redirects would work as expected, but I'm guessing I should be able to customize the ingress to run on suitable ports that can be forwarded by a userspace process so that redirects go to the expected port?

> unfortunately not, the internal API for kind revolves around node names. this would be a fairly breaking change.

Sorry if it wasn't clear, didn't mean to suggest that internally switch to IDs, more just change how the container names are retrieved by having `docker inspect` resolve the IDs to a name instead of trying to retrieve the name directly via `docker ps`.

e.g. completely untested idea:
```
	cmd := exec.Command("docker",
		"ps",
		"-q",         // quiet output for parsing
		"-a",         // show stopped nodes
		"--no-trunc", // don't truncate
		// filter for nodes with the cluster label
		"--filter", fmt.Sprintf("label=%s=%s", clusterLabelKey, cluster),
		// format to retrieve just the ID initially
		"--format", `{{.ID}}`,
	)
	lines, err := exec.OutputLines(cmd)
	if err != nil {
		return nil, errors.Wrap(err, "failed to list clusters")
	}
        cids := strings.Join(lines, " ")
        cmd := exec.Command("docker",
		"inspect",
		// format to retrieve the container name only for each ID
		"--format", `{{.Name}}`,
		cids,
	)
       	lines, err = exec.OutputLines(cmd)
	if err != nil {
		return nil, errors.Wrap(err, "failed to inspect containers")
	}
	// convert names to node handles
	ret := make([]nodes.Node, 0, len(lines))
	for _, name := range lines {
		// skip first character returned in name as it will be '/'
		ret = append(ret, p.node(name[1:]))
	}
	return ret, nil
```


> see #1116 for reasoning, but basically docker chose to strongly deprecate linked containers upstream so we're not going to invest complexity in supporting them.

I presume there is nothing else that can appear as part of `.Names` other than linked containers? I'd also agree in not trying to parse the output of .Names as that does appear to be unnecessarily complex. Would switching to inspect as suggested above be considered not complex or is the overhead of an additional docker call to much?

> I am however working on user defined networks.

I guess the above provides a reasonable user story to help support that ;-)

**Comment by BenTheElder** [comment]
> My understanding was I can only talk directly to the individual containers and cannot use this to talk to the ingress? But I see I can do a port-forward to the service/ingress-nginx, thanks I was assuming this wouldn't work in the expected way. Thanks hadn't thought of that.

Er, this part from the post (partial kind config):
```yaml
- extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
```

means that you can port forward the ingress ports on the host to the node and then run the ingress on the node behind that.

**Comment by BenTheElder** [comment]
> It does make some things a little more awkward that running two socat docker containers would have access to the ports 80 & 443 on the local machine so that redirects would work as expected, but I'm guessing I should be able to customize the ingress to run on suitable ports that can be forwarded by a userspace process so that redirects go to the expected port?

Er, you should check https://projectcontour.io/kindly-running-contour/, none of that should be necessary.

 > Sorry if it wasn't clear, didn't mean to suggest that internally switch to IDs, more just change how the container names are retrieved by having docker inspect resolve the IDs to a name instead of trying to retrieve the name directly via docker ps. ...

Yeah no, that is expensive. kind is built around the assumption that nodes can be indexed cheaply by name. Which is correct except when this extremely deprecated docker feature is used.

> I presume there is nothing else that can appear as part of .Names other than linked containers?

Not as far as I know. kind has operated for more than a year without any issues related to this until someone made a post using linked containers :|

> I'd also agree in not trying to parse the output of .Names as that does appear to be unnecessarily complex. Would switching to inspect as suggested above be considered not complex or is the overhead of an additional docker call to much?

The overhead of another call per container is pretty not great. The extra code is not awesome either, because we only need it when this feature is used, and this feature should not be necessary anyhow (see the extraPortMappings example, you can map ports on the kind nodes instead of trying to use an extra container to map them...)

> I guess the above provides a reasonable user story to help support that ;-)

We already want this for other purposes, unfortunately it's a bit of a mess. Docker user defined networks have breaking behavior versus the default ... and this does in fact break kind.

**Comment by BenTheElder** [comment]
basically the entirety of https://banzaicloud.com/blog/kind-ingress/ should work fine, but instead of using the bit about socat containers, use

`config.yaml`:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane 
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
```

`kind create cluster --config=config.yaml`

**Comment by BenTheElder** [comment]
I left a similar comment on the post https://banzaicloud.com/blog/kind-ingress/#comment-4719044201

**Comment by electrofelix** [comment]
> Er, you should check https://projectcontour.io/kindly-running-contour/, none of that should be necessary.

I've tried to apply the same idea to the nginx ingress, since that is what is used in production and unfortunately it doesn't appear to work, but I'm guessing I'm doing something dumb as the contour one worked via the http (though it would return an SSL error when trying to access via https), thanks for the pointers. Might just follow this up in the slack channel to get the fine details down.

> The overhead of another call per container is pretty not great. The extra code is not awesome either, because we only need it when this feature is used, and this feature should not be necessary anyhow (see the extraPortMappings example, you can map ports on the kind nodes instead of trying to use an extra container to map them...)

Just to clear up something in my head, the function at https://github.com/kubernetes-sigs/kind/blob/69e0c92e79ef897307cb7ad3d7cc3b7c2886fd4f/pkg/cluster/internal/providers/docker/provider.go#L92 gets executed per node in the cluster?

**Comment by BenTheElder** [comment]
[thread with more discussion here] https://kubernetes.slack.com/archives/CEKK1KTN2/p1576000804422800?thread_ts=1575998693.415500&cid=CEKK1KTN2

**Comment by BenTheElder** [comment]
we have some basic docs for ingress now, will continue to work on more.
