### ISSUE TITLE
Add new k8s IPv6 configuration improvements to KIND

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#1154]
**What would you like to be added**:

Currently we have to overcome kubernetes IPv6 configuraiton limitations in kind, i.e, hardcoding node ip 

- [x] https://github.com/kubernetes/kubernetes/pull/85850

- [x] https://github.com/kubernetes/kubernetes/pull/84727

**Why is this needed**:

This will simplify the Kind glue and test better upstream IPv6 support on k8s

We can get rid of the NodeAddress dependency
https://github.com/kubernetes-sigs/kind/blob/4c7854c1347860ef04a7a8caef625ac4491afa4b/pkg/cluster/internal/kubeadm/config.go#L43

https://github.com/kubernetes-sigs/kind/blob/4c7854c1347860ef04a7a8caef625ac4491afa4b/pkg/cluster/internal/kubeadm/config.go#L408

https://github.com/kubernetes-sigs/kind/blob/4c7854c1347860ef04a7a8caef625ac4491afa4b/pkg/cluster/internal/kubeadm/config.go#L401

**Comment by BenTheElder** [comment]
that'll be nice :-)

**Comment by BenTheElder** [comment]
we can still add this, we just need to guard on the k8s version, right?

**Comment by aojea** [comment]
> we can still add this, we just need to guard on the k8s version, right?

yeah, see https://github.com/kubernetes-sigs/kind/pull/1195 for reference

**Comment by aojea** [comment]
:/

**Comment by aojea** [comment]
/close

Fixed by #1154
