### ISSUE TITLE
Support for force-loading images

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/kind#1155]
**What would you like to be added**:
A `--force` flag to `kind load docker-image`  to overwrite images if already present.

**Why is this needed**:
In local development, often I find myself loading new images into kind and have to change the tag to accomplish this.

**Comment by BenTheElder** [comment]
they should be reloaded if the tag is the same but the image ID is not.

what kind version are you using? you should not need to change the tag.

**Comment by vincepri** [comment]
I'll try again in v0.6.1 tomorrow and report back

**Comment by BenTheElder** [comment]
ACK -- we definitely had a bug with this before but it was theoretically fixed in 0.6 IIRC

**Comment by ncdc** [comment]
FYI, I had mentioned this to Vince as something that I ran into, but I haven't tried it with 0.6.x yet.

**Comment by amwat** [comment]
@vincepri were you able to try this on 0.6.1 ?

**Comment by vincepri** [comment]
Not yet, will probably get around to it next week

**Comment by BenTheElder** [comment]
nudge :+)
if we can repro, I'd like to get this fixed. I _think_ it is already.

**Comment by vincepri** [comment]
just confirmed it works.

Steps:
- Build image with tag
- Load image, shows:
```
$ kind load docker-image gcr.io/vincepri-dev/cluster-api-controller-amd64:dev
Image: "gcr.io/vincepri-dev/cluster-api-controller-amd64:dev" with ID "sha256:207351bf38c413daf1eb1ebbef4b0e1ed1332f6e925eda1327440db8e4fe3947" not present on node "kind-control-plane"
```
- Make change, rebuild image with same tag
- Load image, shows:
```
$ kind load docker-image gcr.io/vincepri-dev/cluster-api-controller-amd64:dev
Image: "gcr.io/vincepri-dev/cluster-api-controller-amd64:dev" with ID "sha256:37e1ee7b8242e33d3ccfbabba2144dbc99ecef72de842a65a8234f802b7b8ed2" not present on node "kind-control-plane"
```

/close

🎉

**Comment by BenTheElder** [comment]
Thank you!
