### ISSUE TITLE
Could not find the requested resource(pods/log)

### ISSUE THREAD

**Issue by FlomeWorld** [kubernetes-sigs/kind#1158]
**What happened**:
I cant get the log of pods after restart kind node(docker stop and start)
shell cmd: 
    kubectl logs app-5c464d7d4f-lzbhl -n esko
Error info:
    Error from server (NotFound): the server could not find the requested resource ( pods/log pod-5c464d7d4f-lzbhl)

**What you expected to happen**:

Print my pod log

**How to reproduce it (as minimally and precisely as possible)**:

step1: Stop the kind node
step2: Start the kind node

**Anything else we need to know?**:

1. The kind node image is compiled with k8s source code
2. There are 3 node in my system(1 control plane,2 workers)

**Environment:**

- kind version: (use `kind version`): 
v0.5.1
- Kubernetes version: (use `kubectl version`):
v1.15.3
- Docker version: (use `docker info`):
19.03.5
- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by BenTheElder** [comment]
Stopping and starting kind nodes is NOT supported currently.

**Comment by BenTheElder** [comment]
You should upgrade though, v0.5.1 is two releases old and we made some improvements to allow stopping and starting to behave better

**Comment by BenTheElder** [comment]
see https://github.com/kubernetes-sigs/kind/issues/148, which i'm working on again for the tracking issue with restarts. de-duping with that.

i'd love to know if v0.6.1 solves `docker start` / `docker stop` issues for you though.
