### ISSUE TITLE
Dynamic volume provisioning support

### ISSUE THREAD

**Issue by rimusz** [kubernetes-sigs/kind#118]
Dynamic volume provisioning support would be handy to have to test apps which need persistence.

**Comment by BenTheElder** [comment]
So we do have a default storage class (host-path), though I haven't really tested it out yet. This is required for some conformance tests.

https://github.com/kubernetes-sigs/kind/blob/4d7dded365359afeb1831292cd1a3a3e15fff0b2/pkg/cluster/const.go#L21-L31

**Comment by BenTheElder** [comment]
I _think_ we just need to document this
/kind documentation

If not, I'll update this issue with what else is required and follow-up.
/help
/priority important-longterm

**Comment by alejandrox1** [comment]
I can document this and test it out

**Comment by rimusz** [comment]
yes, I there is default storage class, but it doesn’t work for dynamic volumes prisioning, deployments get stuck waiting for PVCs

**Comment by BenTheElder** [comment]
Ok, thanks.
We'll need to look into options for providing something more suitable. Any
ideas @davidz627 ?

**Comment by BenTheElder** [comment]
We're inherently not on a cloud provider (these clusters are locally like
minikube etc.) - is NFS the only option? Could we write one that handed out
"local disks" that are just dirs or docker volumes or something..?

I'm not the most experienced with stateful Kubernetes yet, admittedly, but
it seems like we could come up with something. 🤔

**Comment by msau42** [comment]
Sorry can someone explain some context to me? Is this for testing only, or do we actually want to run real production workloads?  If it's testing only, there's a hostpath dynamic provisioner that uses the new volume topology feature to schedule correctly to nodes.  However, it doesn't handle anything like capacity isolation or accounting.

I forgot, someone at rancher was working on this project.  I can't remember the name at the moment though :(

**Comment by BenTheElder** [comment]
Just testing. If anyone uses this project for production workloads they're
crazy 😆

I'll try to look around for that, if you remember or have any other ideas
that would be appreciated though. I wonder if minikube or kinvolk have
tried to sort this out yet as well.

**Comment by msau42** [comment]
I found it @yasker https://github.com/rancher/local-path-provisioner

**Comment by rimusz** [comment]
also https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume

**Comment by rimusz** [comment]
OK, been messing with storage:
1) https://github.com/kubernetes-incubator/external-storage/tree/master/nfs fails to work in `kind`
2) https://github.com/rancher/local-path-provisioner / https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume nothing good went for there as well.

I go luck with https://github.com/MaZderMind/hostpath-provisioner
1) deleted default storage class witch comes with `kind` 
2) replaced it with https://github.com/MaZderMind/hostpath-provisioner/blob/master/manifests/storageclass.yaml
3) installed deployment.yaml and rbac.yaml from https://github.com/MaZderMind/hostpath-provisioner/tree/master/manifests
Then installed with helm 3 releases of postgress to test that it can handle multiple pods using local volume, did same for mysql, all worked fine:
```
mysql         mysql-5dbd494d67-fw7g6                         1/1     Running   0          4m
mysql2        mysql2-67976cdbc9-zd59h                        1/1     Running   0          4m
mysql3        mysql3-c79b9d5dd-tfkgp                         1/1     Running   0          4m
mysql4        mysql4-66d69d4ffc-l2c87                        1/1     Running   0          38s
pg            pg-postgresql-0                                1/1     Running   0          34m
pg2           pg2-postgresql-0                               1/1     Running   0          31m
pg3           pg3-postgresql-0                               1/1     Running   0          28m
```

```
$ k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                       STORAGECLASS   REASON   AGE
pvc-14f6a7e0-ecc8-11e8-906e-02425a7d6bdf   8Gi        RWO            Delete           Bound    pg3/data-pg3-postgresql-0   hostpath                27m
pvc-46e3201b-ecc7-11e8-906e-02425a7d6bdf   8Gi        RWO            Delete           Bound    pg/data-pg-postgresql-0     hostpath                33m
pvc-6116f05a-eccb-11e8-906e-02425a7d6bdf   8Gi        RWO            Delete           Bound    mysql/mysql                 hostpath                4m
pvc-7027dff3-eccb-11e8-906e-02425a7d6bdf   8Gi        RWO            Delete           Bound    mysql2/mysql2               hostpath                3m
pvc-7668b7ae-eccb-11e8-906e-02425a7d6bdf   8Gi        RWO            Delete           Bound    mysql3/mysql3               hostpath                3m
pvc-99b0f805-ecc7-11e8-906e-02425a7d6bdf   8Gi        RWO            Delete           Bound    pg2/data-pg2-postgresql-0   hostpath                31m
pvc-f191c00d-eccb-11e8-906e-02425a7d6bdf   8Gi        RWO            Delete           Bound    mysql4/mysql4               hostpath                11s
```
I think for the time being I will stick with this solution.

It should not too difficult to port to `kind` :)

**Comment by yasker** [comment]
@rimusz What the issue with https://github.com/rancher/local-path-provisioner? Just curious.

**Comment by rimusz** [comment]
it did not work for me, PV did not get created, so I did not spend too much time digging why.
`hostpath-provisioner` worked for me straight away :-)

**Comment by yasker** [comment]
@rimusz Weird... If you got time, can you open an issue with the log? You can see how to get the log using `kubectl -n local-path-storage logs -f local-path-provisioner-d744ccf98-xfcbk`(as seen in the doc). Though if you don't have time, I totally understand.

**Comment by rimusz** [comment]
@yasker next time when I get free cycles I will look to `local-path-provisioner` again.
But when `kind` supports multi-node then we need something else.

**Comment by msau42** [comment]
Oh if you are currently only supporting single node, then the intree hostpath provisioner should have worked fine.  It's the same one that localup.sh uses

**Comment by BenTheElder** [comment]
Ah, yeah currently only a single-node, and it should indeed look like `hack/local-up-cluster.sh`'s default storage, but multi-node will happen in the near future I suspect, an implementation exists but is not in currently and may take a bit.

**Comment by phisco** [comment]
confirm @rimusz solution is working for me too

**Comment by BenTheElder** [comment]
exciting! perhaps we should ship this by default then :-)

**Comment by BenTheElder** [comment]
Very cool, I haven't managed to dig too deep into this yet (just starting to look more now) - is it feasible to adapt to multi-node at all? (I'd guess not so much...)
If not, perhaps we should check in documentation / example config for how to do this in the user guide(s).

**Comment by BenTheElder** [comment]
I do really think we should try to offer a solution to this, and FWIW I think single-node clusters will be most common, but multi-node exists in limited capacity now and will be important for some CI scenarios.

**Comment by aojea** [comment]
https://github.com/rancher/local-path-provisioner is working for me in a kind multi node cluster

**Comment by rohansingh** [comment]
I can confirm that rancher/local-path-provisioner works for me as well, with no modification.

**Comment by BenTheElder** [comment]
Excellent! Thank you for investigating and confirming, with #62 in we should be able to actually back this with a directory on the real host as well :smile:

**Comment by rimusz** [comment]
yup https://github.com/rancher/local-path-provisioner worked for me this time as well:
I updated it's storage class with annotation `storageclass.kubernetes.io/is-default-class: "true"`
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
```
Then:
```
kubectl delete storageclass standard
kubectl apply -f local-path-provisioner.yaml
```
Result:
![screenshot 2019-02-21 12 45 56](https://user-images.githubusercontent.com/5215395/53170142-426a1500-35d7-11e9-872e-6c46109956f5.png)

**Comment by unguiculus** [comment]
While [rancher/local-path-provisioner](https://github.com/rancher/local-path-provisioner) generally seems to support multi-node clusters, volumes always seem to be mounted using `root` as group irrespective of a specified security context.

See https://github.com/rancher/local-path-provisioner/issues/7

**Comment by rimusz** [comment]
I was able to reproduce `rancher/local-path-provisioner` security context issue too.

**Comment by yasker** [comment]
@unguiculus @rimusz Unfortunately, fsGroup support is something outside of local path provisioner's control.

 The `hostpath` type PV doesn't support security context. It has to be root for the volume to be written in. See https://github.com/kubernetes/minikube/issues/1990 and https://unofficial-kubernetes.readthedocs.io/en/latest/concepts/storage/volumes/#hostpath

>the directories created on the underlying hosts are only writable by root. You either need to run your process as root in a privileged container or modify the file permissions on the host to be able to write to a hostPath volume

At the end of https://github.com/kubernetes/minikube/issues/1990 there is a workaround provided.

I also found a PR to add fsGroup support to hostpath volume, but it wasn't accepted. https://github.com/kubernetes/kubernetes/pull/39438

**Comment by BenTheElder** [comment]
I wonder if we can borrow ideas from minikube's storageclass addons? surely they've found a work around.

**Comment by msau42** [comment]
@yasker could you amend the hostpath provisioner to use the local PV type? Local PV supports fsgroup

**Comment by yasker** [comment]
@msau42 seems local PV doesn't create the directory automatically...

**Comment by msau42** [comment]
Oh that's right. I guess you would have to deploy the provisioner as a DaemonSet so it can create a directory beforehand.

**Comment by yasker** [comment]
@BenTheElder Seems Minikube wrote it's own provisioner for host path, and relax the permission on the directory. https://github.com/kubernetes/minikube/blob/a7485e738f912828268cf2196a21b8e1ea6fc61d/pkg/storage/storage_provisioner.go#L60

@msau42 I realized I may not need to deploy the provisioner as DaemonSet if I choose to create the directory beforehand. I should able to create a job/pod to create a directory with e.g. 0770 (if it works) on the host before provisioner return with the volume, then it should be able to work with both host path or local pv.

**Comment by yasker** [comment]
@BenTheElder @unguiculus @rimusz @msau42 Alright, Local Path Provisioner v0.0.3 has been released and the issue with security context should be fixed.

**Comment by BenTheElder** [comment]
I would like to see a solution ship by default in 0.3. I will try to do some more testing with Local Path Provisioner soon, thank you @yasker 🙏

**Comment by jdolitsky** [comment]
Using `kind` for the first time tonight (..wow and thank you) and I came across this issue-

Just wanted to confirm that rancher/local-path-provisioner does indeed successfully and dynamically provision volumes with a fresh install of both kind and local-path-provisioner.

Had to make a few tweaks after install in order to toggle the default storage class:
```
# Install local-path-provisioner
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml

# Set local-path as default storage class (and unset the current default, i.e standard)
kubectl patch storageclass standard -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false", "storageclass.beta.kubernetes.io/is-default-class":"false"}}}'
kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true", "storageclass.beta.kubernetes.io/is-default-class":"true"}}}'
```

I was then able to install the [HackMD helm chart](https://github.com/helm/charts/tree/master/stable/hackmd) with default values, which requires 2 persistent volumes, and the PVs were auto-created and the PVCs became bound pretty much immediately:
```
$ helm install stable/hackmd
NAME:   loping-dingo
...
==> v1/PersistentVolumeClaim
NAME                        STATUS   VOLUME      CAPACITY  ACCESS MODES  STORAGECLASS  AGE
loping-dingo-postgresql     Pending  local-path  0s
loping-dingo-hackmd         Pending  local-path  0s
...


$ kubectl get pvc
NAME                         STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
loping-dingo-hackmd          Bound     pvc-1fc9f202-4ba9-11e9-9396-0242d8d39a56   2Gi        RWO            local-path     6s
loping-dingo-postgresql      Bound     pvc-1fc933d4-4ba9-11e9-9396-0242d8d39a56   8Gi        RWO            local-path     6s
...


$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                 STORAGECLASS   REASON   AGE
pvc-1fc933d4-4ba9-11e9-9396-0242d8d39a56   8Gi        RWO            Delete           Bound    default/loping-dingo-postgresql       local-path              17s
pvc-1fc9f202-4ba9-11e9-9396-0242d8d39a56   2Gi        RWO            Delete           Bound    default/loping-dingo-hackmd           local-path              16s
...

$ kubectl get pods
NAME                                          READY   STATUS    RESTARTS   AGE
loping-dingo-hackmd-85f8b9cbf9-xm9rh          1/1     Running   0          55s
loping-dingo-postgresql-6ffbf7d5ff-98w26      1/1     Running   0          55s
```

Would love to see the next release ship with local-path-provisioner baked-in and as default ❤️

**Comment by joejulian** [comment]
volumes are not being automatically provisioned because kube-controller-manager doesn't have `--enable-hostpath-provisioner` set

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/397 will enable the kubernetes built in host-path provisioner, but for multi-node we probably still want local-path-provisioner. today we meet about kind 0.3 planning :sweat_smile:

**Comment by BenTheElder** [comment]
should be fixed for out of the box clusters (thanks @joejulian !), re-opening to track for for multi-node clusters

**Comment by BenTheElder** [comment]
It looks like we will need ARM and PPC images, punting to the next milestone since we're overdue for 0.3

**Comment by armab** [comment]
Just a relevant heads up here, switching to `rancher/local-path-provisioner` as default will fix https://github.com/kubernetes-sigs/kind/issues/622 when some official Helm charts failed to work in `KinD` with existing `hostPath` due to its limitations like volume/directory write permissions.

**Comment by aojea** [comment]
> It looks like we will need ARM and PPC images, punting to the next milestone since we're overdue for 0.3

Seems that's been worked https://github.com/rancher/local-path-provisioner/pull/24

**Comment by meyerbro** [comment]
Hey @yasker, I'm having the same issue as @rimusz had... No PV gets created... Tried with 2 clusters (v1.14.1 and v1.13.5)... I created an issue there: https://github.com/rancher/local-path-provisioner/issues/39

**Comment by fspaniol** [comment]
Has anyone been able to deploy NFS dynamic provisioning in KinD? When I try to follow the steps [here ](https://github.com/kubernetes-incubator/external-storage/tree/master/nfs#quickstart) I run into [this](https://github.com/kubernetes-incubator/external-storage/issues/1101) issue. It seems that NFS provisioning can't work on top of overlay, according to [this ](https://github.com/kubernetes-incubator/external-storage/issues/1101#issuecomment-469304786) comment.

**Comment by aojea** [comment]
> Has anyone been able to deploy NFS dynamic provisioning in KinD? When I try to follow the steps [here ](https://github.com/kubernetes-incubator/external-storage/tree/master/nfs#quickstart) I run into [this](https://github.com/kubernetes-incubator/external-storage/issues/1101) issue. It seems that NFS provisioning can't work on top of overlay, according to [this ](https://github.com/kubernetes-incubator/external-storage/issues/1101#issuecomment-469304786) comment.

You need to run with a kernel +4.16 https://www.phoronix.com/scan.php?page=news_item&px=OverlayFS-NFS-Export-Linux-4.16

**Comment by fspaniol** [comment]
@aojea I am running with kernel `4.18`:

```
kubectl exec -it nfs-provisioner-69c7d9b45-kcdpz -- bash -c "uname -r"
4.18.0-25-generic
```

**Comment by aojea** [comment]
@fspaniol I was able to mount nfs volumes inside the pods manually, don't know about the NFS provisioner, sorry.
Can you try to first to mount and export a nfs volume manually?

**Comment by aojea** [comment]
Also, I forget to mention that you have to install `apt install -y nfs-common ` on the kind nodes :sweat_smile:

**Comment by BenTheElder** [comment]
we should track possibly installing those by default in another issue

**Comment by fspaniol** [comment]
Hi,

I got NFS dynamic provisioning to work with basically:

- Install nfs-common in the node
- [Deploy nfs server](https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-volumes-example-nfs-persistent-volume.html)
- [Use nfs-client-provisioner helm chart](https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner)

I've also written this in more detail [here](https://gist.github.com/fspaniol/41b1e74adefb4a80ef282f2bd367075d).

Cheers 👍

**Comment by BenTheElder** [comment]
this looks pretty promising! https://github.com/kubernetes-csi/csi-driver-host-path/pull/88/files

**Comment by BenTheElder** [comment]
(also: thanks for the writeup @fspaniol !)

**Comment by msau42** [comment]
The hostpath topology support still has the limitation that the provisioner (and plugin) still only runs on one node. More work is needed to be able to deploy the csi-provisioner as a daemonset (and if anyone is interested in helping with that, I would be glad to guide)

**Comment by Xtigyro** [comment]
I can confirm that the `local-path` provisioner from Rancher has been working quite well on a multi-node kINd cluster for me.

**Comment by n-able-consulting** [comment]
dito msau42

**Comment by yasker** [comment]
Just a heads up, local path provisioner has added arm support in v0.0.11 release. https://github.com/rancher/local-path-provisioner/releases/tag/v0.0.11

**Comment by Xtigyro** [comment]
One limitation of Rancher's provisioner - it does not support `selector`.

For example:
`  Warning  ProvisioningFailed    5s (x2 over 20s)  rancher.io/local-path_local-path-provisioner-ccbdd96dc-796tn_f1095857-fa93-11e9-a90a-4a79b109c4fc  failed to provision volume with StorageClass "local-path": claim.Spec.Selector is not supported
`

**Comment by aojea** [comment]
> One limitation of Rancher's provisioner - it does not support `selector`.
> 
> For example:
> ` Warning ProvisioningFailed 5s (x2 over 20s) rancher.io/local-path_local-path-provisioner-ccbdd96dc-796tn_f1095857-fa93-11e9-a90a-4a79b109c4fc failed to provision volume with StorageClass "local-path": claim.Spec.Selector is not supported`

I'm sure they would love the feedback 😄 
cc: @yasker

**Comment by Xtigyro** [comment]
> If there is a PV matched the selector, Kubernetes should already handle it before it reaches the provisioner. Btw, I haven't seen a provisioner support the field yet.
> 
> And if you're looking for a way to specify a PV for PVC, you can use `pvc.spec.volumeName` instead.

@yasker Are we talking about dynamic provisioning? Because that's why I need it - so that the PVC can match the dynamically provisioned PV. 

The standard K8s `hostPath` provisioner supports it though you're right - the one from AWS (`AWS EBS`), for example, does not support it, too. I haven't tried the others from GCP/Azure/etc.

**Comment by yasker** [comment]
@Xtigyro I am not sure why you need the selector in the case above. The provisioners are always doing dynamic provisionings. You don't need to have a selector to ensure the matching between PVC and PV, since PV is always created based on the spec of PVC.

As for host path, is this the one you mentioned? https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/master/examples/hostpath-provisioner/hostpath-provisioner.go#L64

I didn't see the usage of the selector in it. It seems just ignored it.

**Comment by Xtigyro** [comment]
> @Xtigyro I am not sure why you need the selector in the case above. The provisioners are always doing dynamic provisionings. You don't need to have a selector to ensure the matching between PVC and PV, since PV is always created based on the spec of PVC.

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
Well - it appears if the pod and its PVC is created on one node, sometimes without a `selector` it does not bind to the correct PV.

**Comment by yasker** [comment]
@Xtigyro As the Kubernetes document said, the selector is used to select `existing` volumes. The provisioner is used to create `new` volumes.

Since the provisioner is always creating a new volume, it should match the spec of PVC 100% of the time (since the new volume was created according to the requirement specified in the PVC spec), otherwise, it sounds like a Kubernetes's bug.

If you can provide reproduce steps for the issue, we can look more into it.

**Comment by averri** [comment]
> I found it @yasker https://github.com/rancher/local-path-provisioner

This saved my day, thanks.

**Comment by yashbhutwala** [comment]
@BenTheElder seems many issues have crept up with regards to storage and volume provisioning, I know I've had some too 😃 (#830, #430, https://github.com/pivotal/kpack/issues/217, https://github.com/pivotal/kpack/issues/201).  Is making [rancher/local-path-provisioner](https://github.com/rancher/local-path-provisioner/releases/tag/v0.0.11) the default up for consideration, at least for the near future until upstream [`csi-driver`](https://github.com/kubernetes-csi/csi-driver-host-path) stabilizes?  Especially since `local-path-provisioner` also works well for multi-node setups 😄

**Comment by BenTheElder** [comment]
> @BenTheElder seems many issues have crept up with regards to storage and volume provisioning, I know I've had some too smiley (#830, #430, pivotal/kpack#217, pivotal/kpack#201). Is making rancher/local-path-provisioner the default up for consideration, at least for the near future until upstream csi-driver stabilizes?

It is but I'm not sure if we'd be leaving some people on other architectures SOL, and right now it should be ~two commands to swap out kind's for this 😅

If we add it upstream, it becomes an API 🙃

I'm also not sure the CSI driver is less stable. I'll take another look next week. Right now looking at the host restart issue again finally 🙃

> Especially since local-path-provisioner also works well for multi-node setups smile

AFAICT local-path-provisioner "works" for multi-node setups to the same degree as the CSI driver...? I.E. all volumes will wind up on the same node where the single driver instance is running, which is not super acceptable for Kubernetes testing purposes. The CSI driver should "soon" actually support multi-node. The driver basically does, but CSI provisioner needs to support a daemonset.

kind would also need to drop support for old kubernetes versions, which is not something we've done yet.

**Comment by yasker** [comment]
@BenTheElder Just one thing. Local Path Provisioner is able to provision the volume on any node from the beginning, not only the node running the provisioner. For example, you can configure it at https://github.com/rancher/local-path-provisioner#configuration

If there is anything I can help to make Local Path Provisioner better suit for the kind's usage, let me know.

**Comment by BenTheElder** [comment]
Thanks @yasker, I looked into this deeper and we are shipping this with some customization :sweat_smile: #1157 is WIP to ship it.

See also https://github.com/kubernetes-sigs/kind/issues/1151#issuecomment-563790700

Kubernetes testing is going OK at the moment, so I am focusing on:
> this, host restarts, user defined networks, and registries are on my near term list, in that order, other than ongoing maintenance stuff etc...

To fix local development issues. I appreciate everyone's patience with getting this right and juggling priorities.

**Comment by BenTheElder** [comment]
Fixed in https://github.com/kubernetes-sigs/kind/pull/1157, kind at HEAD should work fully with dynamic PVC. Thanks @yasker. https://kubernetes.slack.com/archives/C92G08FGD/p1576098305111500
