### ISSUE TITLE
Test failing: SchedulerPredicates [Serial] validates that taints-tolerations is respected if matching [Disruptive] [Conformance]

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#1180]
**What happened**:

The conformance test `SchedulerPredicates [Serial] validates that taints-tolerations is respected if matching [Disruptive] [Conformance]` was promoted in https://github.com/kubernetes/kubernetes/pull/83652 passing the kind-ipv6 job but it keeps failing after that in both ipv4 and ipv6 conformance jobs
https://k8s-testgrid.appspot.com/conformance-all#kind%20(IPv6),%20master%20(dev)
https://testgrid.k8s.io/sig-testing-kind#Summary

**What you expected to happen**:

Test should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by BenTheElder** [comment]
Failing test bugs should be opened against Kubernetes unless you have reason to suspect they involve a bug in *kind*.

**Comment by BenTheElder** [comment]
This is not a bug in kind https://testgrid.k8s.io/conformance-gce#Conformance%20-%20GCE%20-%20master

![Screenshot_20191218-025248](https://user-images.githubusercontent.com/917931/71080182-84091500-2141-11ea-9f45-3a3fc1b9a299.png)

**Comment by BenTheElder** [comment]
It is clearly broken in GCE too. Moving to tracking upstream, this test needs to be fixed or moved out of conformance. Probably the latter until a fix is proposed

**Comment by aojea** [comment]
> Failing test bugs should be opened against Kubernetes unless you have reason to suspect they involve a bug in _kind_.

I was thinking that only kind was affected :sweat_smile:
