### ISSUE TITLE
Redis on multi-node kind cluster

### ISSUE THREAD

**Issue by daneel3001** [kubernetes-sigs/kind#1185]
Hello

I am currently experimenting with Kind on Windows 10 Insider Slow with Ubuntu 18.04 on WSL2.
I am stuck with trying to get Redis to work on a multinode Kind cluster, Redis installed with Helm 3.
Both pods, master and slave, fail with the following error:
Can't open the append-only file: Permission denied

Redis does make use of permanent volumes which in this case are stored in /tmp/ location.

So my question will be whether anyone managed to get stable/redis chart to work on Kind.

Thanks for this great application by the way!

**Comment by BenTheElder** [comment]
this is probably https://github.com/kubernetes-sigs/kind/issues/1151 / https://github.com/kubernetes-sigs/kind/issues/830 / https://github.com/kubernetes-sigs/kind/issues/118

we've fixed it, but not in a released version yet, if you try installing from the latest commit and use the default image this is fixed.

we'll get a release out soon.

**Comment by BenTheElder** [comment]
try https://github.com/appscodelabs/e2e-test-setup/blob/ed88ec5bf451534e97fa264f13ccb2b997e5d29e/run.sh#L24 until the next kind release is out.

**Comment by daneel3001** [comment]
Hello

I have built master and the redis cluster I installed via Helm (master, 2 nodes) is certainly not complaining at the moment.
Is there any recommendation re running Kind out of one home built ?
I'm sorry if this sounds daft as I am pretty new to linux/go.

Thanks again for the pointer!

**Comment by aojea** [comment]
> Hello
> 
> I have built master and the redis cluster I installed via Helm (master, 2 nodes) is certainly not complaining at the moment.
> Is there any recommendation re running Kind out of one home built ?

as Ben commented previously this problem will be solved in the next release, until then, the best option is building it from master

https://github.com/kubernetes-sigs/kind/issues/1185#issuecomment-568118713
