### ISSUE TITLE
Add versioning to kind

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/kind#119]
This issue is to track adding a `version` option/sub-command that displays the `kind` version. This would help in debugging to know what version a user is working with and to support released versions of kind.

**Comment by BenTheElder** [comment]
/cc @munnerz 
/lifecycle active
/assign

https://github.com/kubernetes-sigs/kind/pull/81 has this, it just hasn't gone through yet while we finish sorting out how we want to handle the actual versions

**Comment by rimusz** [comment]
can with `kind` versioning different kubernetes versions be supported?

**Comment by BenTheElder** [comment]
Different Kubernetes versions are supported today by using `--image`s with different versions. I will document this further soon.

**Comment by BenTheElder** [comment]
done in #140 
will loop back with details on kubernetes versions
