### ISSUE TITLE
Cannot create cluster in on ubuntu on IBM PPC64LE machine

### ISSUE THREAD

**Issue by shdmitry2000** [kubernetes-sigs/kind#1194]
**What happened**:
Tried to create a cluster with kind create cluster and get:

Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.16.3) 🖼
 ✓ Preparing nodes 📦
 ✗ Writing configuration 📜
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 1
**What you expected to happen**:
creating cluster
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):kind v0.6.1 go1.13.4 linux/ppc64le
- Kubernetes version: (use `kubectl version`):
no
- Docker version: (use `docker info`):
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-60-generic
Operating System: Ubuntu 18.04.3 LTS
OSType: linux
Architecture: ppc64le
CPUs: 160
Total Memory: 255.3GiB
Name: PWRAI-2
ID: QZYB:Z2XW:ZBXP:AWJS:HE3S:MIM6:HVFO:UYO3:54OA:3OE4:JFO7:AHTW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

- OS (e.g. from `/etc/os-release`):
Linux 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:54:48 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux

**Comment by BenTheElder** [comment]
Did you build an image?

We do not have PPC hardware to test / build with, you have to build your own base and node image before you can use kind on non amd64

**Comment by BenTheElder** [comment]
Given the output I'm going to assume not.

We need to add this to known issues.

**Comment by BenTheElder** [comment]
documented:
https://kind.sigs.k8s.io/docs/user/known-issues/#nonamd64-architectures
https://kind.sigs.k8s.io/docs/user/quick-start/#building-images
