### ISSUE TITLE
Autosync images from regular local Docker cache to kind registry

### ISSUE THREAD

**Issue by mcandre** [kubernetes-sigs/kind#1196]

**Comment by BenTheElder** [comment]
I've thought about this but uh, how would it be implemented?

How do you deal with the cost of 2x-ing the storage of an unbounded data set behind the scenes?

If you want to sync images to a registry right now you can do it with a pretty simple shell script to list and push all the images periodically.

A slightly smarter scipt could look for images that aren't pushed yet.

But I don't think most users actually want to push _all_ images, just the ones they are using.

**Comment by BenTheElder** [comment]
closing for now, lacking any answers to how to deal with these problems, may revisit in the future.
