### ISSUE TITLE
Add versioned releases for kind

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/kind#120]
As other projects begin to depend on `kind` for dev and CI testing, it will be useful to have versioned releases for `kind` instead of having those projects rely on `master` using `go get sigs.k8s.io/kind` or running extra commands to `git checkout` a specific SHA (no branches or tags currently exist). That way if there is ever a new default behavior that other project maintainers are not expecting, or a regression, they can remain fixed to a version that they know works. This would depend on #119 for versioning info.

**Comment by BenTheElder** [comment]
see https://github.com/kubernetes-sigs/kind/pull/81 and docs/todo.md

this is intended, the reason a release doesn't exist yet is:
- still possibly making breaking changes leading up to the first release
- we're working out how we want to handle versioning

#81 also adds the version subcommand for https://github.com/kubernetes-sigs/kind/issues/119

/cc @munnerz 
/lifecycle active
/assign

**Comment by BenTheElder** [comment]
discussed an updated strategy for this today with @munnerz, I want to get this + #119 next week ideally.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/releases/tag/0.0.1, with binaries for linux amd64 and darwin amd64, if someone needs another architecture I'm happy to update, but it's unlikely to work elsewhere except possibly windows (we don't have very active testing there, and I'm unsure if it works currently)
