### ISSUE TITLE
Allow kind to directly use images without "kind load docker-image ..."

### ISSUE THREAD

**Issue by RafalSkolasinski** [kubernetes-sigs/kind#1202]
**What would you like to be added**:

It would be great if by usage of some flag / configuration option kind's node would have direct access to docker images build locally.

**Why is this needed**:

Executing `kind load ...` is quite a hassle and unnecessarily takes time.
Especially for images > 1GB.

**Comment by BenTheElder** [comment]
This is simply not possible at the moment.

We are however looking at local registry UX, a very rough way to do it is here https://kind.sigs.k8s.io/docs/user/local-registry/

**Comment by xenithorb** [comment]
```
  Warning  Failed     5m39s (x4 over 7m11s)  kubelet, kind-control-plane  Failed to pull image "registry:5000/busybox:latest": rpc error: code = Unknown desc = failed to pull and unpack image "registry:5000/busybox:latest": failed to resolve reference "registry:5000/busybox:latest": failed to do request: Head https://registry:5000/v2/busybox/manifests/latest: http: server gave HTTP response to HTTPS client
```

**Comment by BenTheElder** [comment]
Hmm I'll have to double check the script, it did get refactored recently.

> That script also does not belong having set -o errexit at the beginning

Why..? I would say nearly all scripts should...

**Comment by RafalSkolasinski** [comment]
What kind of speed up may one expect using the local registry shared with kind node?
One still need to push to local registry (do not remember how much time it takes).

Good thing is that it will for sure reuse already existing layers.

**Comment by BenTheElder** [comment]
pushing over the network will be faster than over docker exec because of the way these are implemented, particularly in docker for mac.
the layer reuse is also important.
