### ISSUE TITLE
Specify Names Without --name 

### ISSUE THREAD

**Issue by danielhelfand** [kubernetes-sigs/kind#1203]
**What would you like to be added**:

I would like to specify the name argument without using `--name`. Instead of using `kind create cluster --name name`, I think it would be more user friendly to be able to run `kind create cluster name`. This would also apply to other commands where a name argument is needed.

**Why is this needed**:

It's a more common pattern to specify a name of a resource without needing a flag. It is my personal opinion that this would be a more common CLI experience that users would be familiar with.

**Comment by BenTheElder** [comment]
Possibly, but it will lose consistency with the rest of the commands.

You can think of name as more like --namespace if we compare to kubectl.

**Comment by BenTheElder** [comment]
It would be a huge breaking change to add name as a required argument to all commands, and having it as an optional positional argument doesn't work if we ever want to allow variadic arguments (eg something like `kind load docker-images ...`)

**Comment by danielhelfand** [comment]
Ah, I see. I wasn't aware of these other thoughts around kind. This is an admittedly minor issue, so no worries if it would be a major pain to implement. While it would be nice to have, I can close this. Thanks for the explanation of the thought process around `--name`.

**Comment by BenTheElder** [comment]
I'm not a massive fan of the --name thing but I also don't want to break users without a big improvement.

Currently this is the rough non-breaking plan to offer another way to specify this https://github.com/kubernetes-sigs/kind/issues/1094
