### ISSUE TITLE
feature: can we support docker run param ,like --add-host?

### ISSUE THREAD

**Issue by zgfh** [kubernetes-sigs/kind#1206]
**What would you like to be added**:
feature: can we support docker run param ,like --add-host?
**Why is this needed**:
i want add hosts for registry domain

**Comment by aojea** [comment]
can you expand more on this?
What do you mean by 
>add hosts for registry domain
😅

**Comment by BenTheElder** [comment]
sorry, but no.

for specific features we will support a portable abstraction, but kind is not directly coupled to docker's CLI and we have no intention of becoming coupled to it.
