### ISSUE TITLE
Mounting docker volumes in kind?

### ISSUE THREAD

**Issue by sokoow** [kubernetes-sigs/kind#1207]
**What would you like to be added**:

Is there any way to allow docker volumes to be mounted in kind ?

**Why is this needed**:

1. Well, first of all to avoid 10 gig docker container size on some OSes. As you work with your kind stack, it swallows a lot, especially if you have hostpaths mounted. 

2. Secondly, it'd be nice to have some extra persistence on host machine for repeatable tests that require persistence.

**Comment by amwat** [comment]
Duplicate of https://github.com/kubernetes-sigs/kind/issues/1045

https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts

**Comment by sokoow** [comment]
thanks! :D
