### ISSUE TITLE
Bail out if "ensuring node image" fails (e.g. because of non-existent image)

### ISSUE THREAD

**Issue by jpetazzo** [kubernetes-sigs/kind#1208]
*Note: depending on the reader's perspective, this could be a bug report or a clean up. YMMV.*

**What would you like to be added**:

When "Ensuring node image" fails to pull the image, kind should abort (instead of displaying a misleading "everything is ok!" checkmark).

Example:
```
[jp@hex ~]$ kind create cluster --name=wrongimage --image=nope:nope
Creating cluster "wrongimage" ...
 ✓ Ensuring node image (nope:nope) 🖼 
 ✗ Preparing nodes 📦 
docker run error: command "docker run --hostname wrongimage-control-plane --name wrongimage-control-plane --label io.x-k8s.kind.role=control-plane --label io.k8s.sigs.kind.role=control-plane --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=wrongimage --label io.k8s.sigs.kind.cluster=wrongimage --publish=127.0.0.1:34677:6443/TCP nope:nope" failed with error: exit status 125
```

**Why is this needed**:

I personally think it's a *bad idea™* to show a green checkmark when there was, in fact, an error.

It's not a huge issue (since it's fairly easy to copy-paste the Docker command and check its result to see what was the actual problem) but I suspect this might be a low hanging fruit! <3

**Comment by aojea** [comment]
:)

https://github.com/kubernetes-sigs/kind/blob/a389a5c28c9f2aa334489aa9ffe67377f7146ca6/pkg/cluster/internal/providers/docker/images.go#L44-L46

**Comment by BenTheElder** [comment]
we at the very least should not show a happy green check mark indeed..

thanks for reporting this
