### ISSUE TITLE
Missing v1.16.0 In Dockerhub

### ISSUE THREAD

**Issue by maximillianbrain1** [kubernetes-sigs/kind#1211]
Hello, I really want to use kind with v1.16.0, but there is only v1.16.1, v1.16.2, and v1.16.3 in Dockerhub. Can someone please build and upload that version?

Thanks!

**Comment by aojea** [comment]
This topic was commented in different issues, 

https://github.com/kubernetes-sigs/kind/issues/863

the image publishing is not being automated but is easy to create your own images

https://kind.sigs.k8s.io/docs/user/quick-start/#building-images

**Comment by BenTheElder** [comment]
yep, we do not publish all images yet, for prebuilt images you must choose one from the release notes https://github.com/kubernetes-sigs/kind/releases

to build your own at an arbitrary version, see the docs linked above.

note that we may not support the built image in a future version of kind, as kind is still alpha and you may have to build it again.
this is part of why we are not building for every possible patch version yet, however we do have builds for all minor versions at the latest patch during every kind release.
