### ISSUE TITLE
Update kind-with-registry.sh to work out of the box.

### ISSUE THREAD

**Issue by finn-ball** [kubernetes-sigs/kind#1215]
https://kind.sigs.k8s.io/docs/user/local-registry/

When following these instructions and create the shell script but get:

```
Error: No such object: kind-registry
```

**What would you like to be documented**:

I'd like the documentation to be updated to reflect how to create a local registry that can be used with Kind.

**Why is this needed**:

For easier local development.

**Comment by BenTheElder** [comment]
fixed by https://github.com/kubernetes-sigs/kind/pull/1220

**Comment by marcindulak** [comment]
FYI: there still seem to be an issue when pulling images from the insecure local registry configured by  `kind-with-registry.sh` https://github.com/containerd/cri/issues/1367

**Comment by marcindulak** [comment]
> FYI: there still seem to be an issue when pulling images from the insecure local registry configured by `kind-with-registry.sh` [containerd/cri#1367](https://github.com/containerd/cri/issues/1367)

It looks like already from the containerd version up in https://hub.docker.com/layers/kindest/node/v1.16.2/images/sha256-2c68d327c2833fa9c0f81b5fd36499cf969646cd50affecd21b4725d37931e21 the problem of pulling from insecure registry has been fixed.

```sh
docker exec -it kind-control-plane bash -c "containerd -v"
containerd github.com/containerd/containerd v1.3.0-27-g54658b88 54658b8831a7382bc79bf0b11ca591951c56aa6b
```

**Comment by BenTheElder** [comment]
sorry about that, yeah we should be on 1.3.2+ now for future images
