### ISSUE TITLE
networking issue - dns stops working when used calico cni

### ISSUE THREAD

**Issue by bjethwan** [kubernetes-sigs/kind#1216]
**What happened**:
```
networking issue - when deploying calico
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "192.168.0.0/16"
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker

kind create cluster --config=kind-configs/cluster-calico.yaml
kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml
```

```
k run nginx --image=bjethwan/nginx --replicas=2 --expose=true --port=80
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
service/nginx created
deployment.apps/nginx created
```

```
$ k run busybox --image=busybox --rm -it --restart=Never
If you don't see a command prompt, try pressing enter.
/ # 
/ # wget -q google.com -O -
wget: bad address 'google.com'
/ # wget -q nginx -O -
<!DOCTYPE html>
<html>
...
<h1>Welcome to nginx!</h1>
</html>
/ # exit
pod "busybox" deleted
```

**What you expected to happen**:
I didn't apply any network policies.
So I expected dns to work fine for external names.

exact same setup and aws worked fine (used kops to create the cluster using networking=calico)

**Environment:**
```
$ kind version
kind v0.6.1 go1.13.4 darwin/amd64

$ kubectl version --short
Client Version: v1.14.1
Server Version: v1.16.3
```

**Comment by aojea** [comment]
Can you please check the known issues?
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues

if that's ok, can you paste the logs with the errors trying to resolve the external domains?
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#are-dns-queries-being-received-processed

**Comment by BenTheElder** [comment]
Note that calico etc. are not really supported as well, installing a different CNI is a power user feature that we do not test.

do your pod AND service subnets match calico?
also https://github.com/kubernetes-sigs/kind/issues/1216#issuecomment-569814303

**Comment by BenTheElder** [comment]
I just realized your example uses busybox.

busybox does not respect DNS settings appropriately, namely search paths.

https://github.com/kubernetes/website/pull/18001

**Comment by s3than** [comment]
@BenTheElder I can replicate this error with a none busybox container

`networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16`

and setting

`kubectl -n=kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=true`

I had noticed in https://github.com/kubernetes-sigs/kind/issues/891 that rp_filter settings should be ok in the 0.6.1 release so tried without setting the IGNORE and got the same issue

Effectively Coredns never becomes ready

I can't see any errors in coredns though

**Comment by s3than** [comment]
@BenTheElder I'm seeing the error even with the default network will debug more

kube-system     coredns-5644d7b6d9-cvtpw                           0/1     Running   0          11m
kube-system     coredns-5644d7b6d9-jrg27                           0/1     Running   0          11m

**Comment by s3than** [comment]
Removing this from my config allowed it to work again with Calico. I'll create a separate issue

`
    # kubeadmConfigPatches:
    # - |
    #   apiVersion: kubeadm.k8s.io/v1beta2
    #   kind: InitConfiguration
    #   nodeRegistration:
    #     kubeletExtraArgs:
    #       node-labels: "ingress-ready=true"
    #       authorization-mode: "AlwaysAllow"
    # extraPortMappings:
    # - containerPort: 80
    #   hostPort: 80
    # - containerPort: 443
    #   hostPort: 443
`

**Comment by BenTheElder** [comment]
can you narrow down which part of this config caused the issue?

**Comment by s3than** [comment]
I'll narrow it down today

**Comment by s3than** [comment]
I've completed the following investigations around config

Default Networking, works as expected

Disable Default networking, with FELIX_IGNORELOOSERPF not set for Calico appears to resolve the issue

@BenTheElder Without digging into Calico to determine the issue I'd say it's resolved on the kind side. 

`
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
`

**Comment by BenTheElder** [comment]
ACK, thanks :-)

**Comment by crixo** [comment]
@s3than I'm using your cluster configuration and I also removed the env variable from calico pod but I still have the same issue: i'm not able to get external service (eg. www.google.com).
Which image did you use for testing it?

**Comment by bjethwan** [comment]
@s3than @BenTheElder 

I am sorry but it's still not working.
I installed latest KIND (kind v0.7.0 go1.13.6 darwin/amd64)
 ✓ Ensuring node image (kindest/node:v1.17.0)
Used latest calico (calico/node:v3.13.3)
And tried both 
kubectl -n=kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=true
kubectl -n=kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=false

But nothing worked for me. 
I didn't create a new issue as  you mentioned that calico is not officially supported in KIND clusters. Let us know. I use KIDN pretty heavily, so I feel like badly struck.

**Comment by s3than** [comment]
I'll put together my installation details shortly

**Comment by myazid** [comment]
> @s3than I'm using your cluster configuration and I also removed the env variable from calico pod but I still have the same issue: i'm not able to get external service (eg. [www.google.com](http://www.google.com)).
> Which image did you use for testing it?

Did u resolve the external service?

**Comment by s3than** [comment]
See the configuration below.

This is the kind config

```
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
nodes:
  - role: control-plane
  - role: worker
  - role: worker
```

I'm using this for calico

`kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml`

Wait for a while... and it starts working

Nothing else configured.

I'm using the latest Calico and 

`kind v0.7.0 go1.13.6 linux/amd64`

and 

`kindest/node:v1.17.0`

**Comment by s3than** [comment]
I've just tested with 3.13 and it's failing again..

**Comment by s3than** [comment]
```
❯ kubectl get pods -A
NAMESPACE            NAME                                               READY   STATUS    RESTARTS   AGE
kube-system          calico-kube-controllers-75f6c789b6-lvw5z           1/1     Running   0          3m42s
kube-system          calico-node-b5rdt                                  1/1     Running   0          3m42s
kube-system          calico-node-jvrfd                                  1/1     Running   0          3m42s
kube-system          calico-node-v9hz2                                  1/1     Running   0          3m42s
kube-system          calico-node-vnrgf                                  1/1     Running   0          3m42s
kube-system          coredns-6955765f44-k7pbm                           1/1     Running   0          4m4s
kube-system          coredns-6955765f44-p75vx                           1/1     Running   0          4m4s
kube-system          etcd-clusterapi-control-plane                      1/1     Running   0          4m17s
kube-system          kube-apiserver-clusterapi-control-plane            1/1     Running   0          4m16s
kube-system          kube-controller-manager-clusterapi-control-plane   1/1     Running   0          4m17s
kube-system          kube-proxy-45wkx                                   1/1     Running   0          4m3s
kube-system          kube-proxy-6w6jk                                   1/1     Running   0          3m50s
kube-system          kube-proxy-8zcrw                                   1/1     Running   0          3m50s
kube-system          kube-proxy-g2c9w                                   1/1     Running   0          3m50s
kube-system          kube-scheduler-clusterapi-control-plane            1/1     Running   0          4m17s
local-path-storage   local-path-provisioner-7745554f7f-k6hvr            1/1     Running   0          4m4s
```

**Comment by s3than** [comment]
```
❯ kubectl run -it --rm --image=infoblox/dnstools dns-client
If you don't see a command prompt, try pressing enter.
dnstools# dig google.com

; <<>> DiG 9.11.3 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48761
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		30	IN	A	172.217.167.78

;; Query time: 23 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Wed Apr 29 11:01:42 UTC 2020
;; MSG SIZE  rcvd: 65

dnstools# curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
dnstools#
```

**Comment by myazid** [comment]
I followed the same setting and even tried the latest Calico 3.13.
When everything running, 

`dnstools# dig google.com

; <<>> DiG 9.11.3 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 46011
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: a80954d19fa30b4f (echoed)
;; QUESTION SECTION:
;google.com.			IN	A

;; Query time: 2001 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Wed Apr 29 14:32:36 UTC 2020
;; MSG SIZE  rcvd: 51`

coredns log shows 
`│ coredns [ERROR] plugin/errors: 2 google.com. AAAA: read udp 192.168.49.193:52380->192.168.65.1:53: i/o timeout         ││ coredns [ERROR] plugin/errors: 2 google.com. A: read udp 192.168.49.193:55128->192.168.65.1:53: i/o timeout`

**Comment by myazid** [comment]
I found that removing this line make it work

  podSubnet: 192.168.0.0/16

**Comment by aojea** [comment]
> I found that removing this line make it work
> 
> podSubnet: 192.168.0.0/16

Kind and kubeadm defaults the podSubnet, you should check calico the configuration options to configure the right parameters, otherwise the cluster and calico will  run out of sync and I don't know if this can be the cause of your issues... there are many more users and also Calico devs using kind, I mean, it seems to me that this has to be something related to the specific environment or a misconfiguration somewhere
