### ISSUE TITLE
Is there an option to build kind node image using pre-pulled images/binaries?

### ISSUE THREAD

**Issue by jiatongw** [kubernetes-sigs/kind#1230]
I noticed that kind node image is built programmatically. It uses a pre-cloned kubernetes source to build/install kubernetes bits. 

Is there an option to build kind node image using pre-pulled images/binaries, other than building from the pre-cloned kubernetes source code? For example, can I pre-pull all the kubernetes artifacts, either images tar file, or binaries (binaries are preferred) and save them in a customized path, and `kind build node-image` will start from that path and use the binaries to build?

**Comment by BenTheElder** [comment]
Currently no, though also worth noting that KIND's published images and programmatic build do not use the defaults that the k8s releases do, this would result in larger node images.

**Comment by BenTheElder** [comment]
For developers working on Kubernetes this isn't terribly helpful. For users developing on top of kubernetes we're more focused on how we'll manage prebuilding lots of node images so no building is required.

**Comment by jiatongw** [comment]
Thanks @BenTheElder
