### ISSUE TITLE
Kubectl connection refused

### ISSUE THREAD

**Issue by msumner91** [kubernetes-sigs/kind#1240]
On CI, we startup kind via the command below. This results in a successful startup according to Kind, but we are unable to interact with the cluster via kubectl.

**Create command:**
kind create cluster --name $CLUSTER_NAME --image kindest/node:v1.16.3 --loglevel=debug --wait 5m

However kubectl appears to be unable to connect to the cluster kind started (even when the context is set with --context kind-$CLUSTER_NAME.

**Example:**
kubectl get pods --context kind-$CLUSTER_NAME

**Results in:**
The connection to the server 127.0.0.1:35219 was refused - did you specify the right host or port?

**Looking at $HOME/.kube/config it appears to have been set by Kind:**
clusters:
 - cluster:
     certificate-authority-data: xxx
     server: https://127.0.0.1:35219
   name: kind-cluster
 contexts:
 - context:
     cluster: kind-cluster
     user: kind-cluster
   name: kind-cluster
 current-context: kind-cluster
 users:
- name: kind-cluster
   user:
     client-certificate-data: xxx
    client-key-data: xxx

**Comment by msumner91** [comment]
I believe this is a port issue rather than Kind related so closing

**Comment by Wenshiqi222** [comment]
dude ,i had the same problem,have u fixed it?
