### ISSUE TITLE
kubeconfig file created by Kind is missing `apiVersion` and `kind`

### ISSUE THREAD

**Issue by frankfarzan** [kubernetes-sigs/kind#1242]
**What happened**:

In recent versions, Kind automatically populates ~/.kube/config

However, if ~/.kube/config is missing or empty, Kind doesn't populate it correctly.

It's does not include `apiVersion` and `kind`.

**What you expected to happen**:

If Kind is going to automatically mess with kube config, it needs to set it correctly.

Kubernetes client libraries, such as the official Javascript library, will fail if they cannot find these fields.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start with an empty kubeconfig file
2. Run `kind create`
3. Look at ~/kube/.config

**Anything else we need to know?**:

Kubernetes client library failing as a result:

TypeError: unknown version: undefined
    at KubeConfig.loadFromString (node_modules/@kubernetes/client-node/dist/config.js:100:19)

**Environment:**
kind v0.6.1 go1.13.4 darwin/amd64

- kind version: (use `kind version`): v0.6.1
- Kubernetes version: (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-20T19:26:38Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Docker version: (use `docker info`):

Server Version: 19.03.5
 Kernel Version: 4.9.184-linuxkit

- OS (e.g. from `/etc/os-release`):

**Comment by BenTheElder** [comment]
These fields are:
- legacy
- optional
- always the same (Config, v1)
- omitempty

See the upstream type definition here:
https://github.com/kubernetes/client-go/blob/940f07561929308fc33fc58bfa185f0544b84846/tools/clientcmd/api/types.go#L32-L41

**Comment by BenTheElder** [comment]
... Pretty sure this client library is broken.
Are you observing this with any client libraries other than the javascript one?

**Comment by frankfarzan** [comment]
No, just the javascript client. Does it make sense for Kind to add these fields for the time being given other tools depend on it (albeit incorrectly)?

**Comment by frankfarzan** [comment]
Also note that kubectl includes these fields when generating kube config. Given kubectl is the reference implementation for other clients, I think being consistent with it is reasonable.

**Comment by BenTheElder** [comment]
Yeah, i'd definitely prefer not to break people, but AFAICT the original
client intends for these not to be used and we tried to follow the upstream
go client kubecinfig logic *very* closely without actually pulling it in
(as we don't actually need the client bits)

**Comment by BenTheElder** [comment]
Also worth noting that kind fully passes conformance tests with this file,
so libraries and tools *should* be accepting it.

**Comment by BenTheElder** [comment]
Fixed upstream in https://github.com/kubernetes-client/javascript/pull/391

**Comment by frankfarzan** [comment]
Thanks!
