### ISSUE TITLE
Chatty nginx ingress logs

### ISSUE THREAD

**Issue by mitar** [kubernetes-sigs/kind#1245]
**What should be cleaned up or changed**:

I followed instructions [here](https://kind.sigs.k8s.io/docs/user/ingress/) on how to setup nginx ingress. But when I run:

```
kubectl logs --namespace ingress-nginx nginx-ingress-controller-6876b49448-svzvl
```

I see many lines like:

```
W0111 08:08:11.996211       7 queue.go:130] requeuing &ObjectMeta{Name:sync status,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[]OwnerReference{},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},}, err services "ingress-nginx" not found
```

Looking [here](https://kubernetes.github.io/ingress-nginx/deploy/#bare-metal) I run the following:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.26.2/deploy/static/provider/baremetal/service-nodeport.yaml
```

And now there are no such messages anymore. Maybe it should be added to documentation?

**Why is this needed**:

It seems it is just not fully configured.

**Comment by amwat** [comment]
Thanks for finding the issue! 
addressed in: https://github.com/kubernetes-sigs/kind/pull/1251

**Comment by mitar** [comment]
Awesome!
