### ISSUE TITLE
Running curl on Kube-dns and kube master encounters a kind error

### ISSUE THREAD

**Issue by raizik** [kubernetes-sigs/kind#1246]
Hi,

1. Why do I get this error?
Also - this is after configuring `service/kubernetes` to listen on port 80 rather than 443. 

![image](https://user-images.githubusercontent.com/38348846/72209605-d6c3bb80-34b8-11ea-9d9b-58b265139d69.png)

2. Is it possible in `kind` to have a pod that lives on control-plane-node to send `http POST` requests to the kubernetes code? If yes - am I meant to wrap this pod with the `service/kubernetes` for this purpose? How do I make this work network-wise in kind?

Thanks in advance.

**Comment by BenTheElder** [comment]
1. Changing the port does not change the security. You are still curling TLS and not presenting authorization, the API server is configured to require authorization by kubeadm for security purposes.

2. Yes, you are reaching the server. I wouldn't use raw HTTP post though, if you use one of the client libraries it will make auth etc. easier.

I'm not sure what you mean by "wrap the pod".

Network wise you are already getting a response that you are not authorized.

**Comment by BenTheElder** [comment]
closing for now due to lack of activity
