### ISSUE TITLE
number of loop devices is fixed and unpredictable

### ISSUE THREAD

**Issue by pohly** [kubernetes-sigs/kind#1248]
**What happened**:

Block device tests running inside the KinD cluster are flaky (https://github.com/kubernetes-csi/csi-driver-host-path/issues/119). It looks like this is because the Docker container  in which kubelet runs has a static copy of the host's `/dev`. In `devfs`, new loop devices are added by the kernel as needed. But inside the container only those `/dev/loop*` devices are available which existed already on the host when the container was created, causing losetup to fail:
```
losetup: /tmp/testfile: failed to set up loop device: No such file or directory
```

**What you expected to happen**:

`/dev` needs to be shared with the host. This isn't nice from a security perspective, but I don't see another solution.

**How to reproduce it (as minimally and precisely as possible)**:

Create a KinD cluster, pick one container with `docker ps`, then run `losetup` repeatedly:
```
$ docker exec f049e80f378a sh -c 'ls /dev/loop*'
/dev/loop-control
/dev/loop0
/dev/loop1
/dev/loop2
/dev/loop3
/dev/loop4
/dev/loop5
/dev/loop6
/dev/loop7
$ docker exec f049e80f378a sh -c 'truncate -s 1G /tmp/testfile; losetup -f --show /tmp/testfile'
/dev/loop0
....
$ docker exec f049e80f378a sh -c 'truncate -s 1G /tmp/testfile; losetup -f --show /tmp/testfile'
/dev/loop7
$ docker exec f049e80f378a sh -c 'truncate -s 1G /tmp/testfile; losetup -f --show /tmp/testfile'
losetup: /tmp/testfile: failed to set up loop device: No such file or directory
```

**Environment:**
- kind version: (use `kind version`): v0.6.0-alpha

**Comment by BenTheElder** [comment]
I'd generally be concerned mounting all of dev that we'll wind up touching other devices.

- If we pre-allocated more on the prow nodes would that work?
- How many do we need? is it predictable at all?
- Can we reduce our dependency on this and / or use something else that is namespaced?

**Comment by pohly** [comment]
> If we pre-allocated more on the prow nodes would that work?

Yes, but it's just a band-aid. But sometimes those are enough :grin: 

> How many do we need? is it predictable at all?

It's not predictable how many will be needed. Pre-allocation would impose a limit that doesn't exist otherwise. On the other hand, calling `mknod /dev/loopX b 7 X` a thousand times would be cheap (it just creates a device node entry in the filesystem, without actually creating the device in the kernel) and that "should be enough for everyone" (famous last words...).

> Can we reduce our dependency on this and / or use something else that is namespaced?

In kubelet, the loop device is used to keep a file descriptor for the device and thus the device itself open without having a process running which owns that file descriptor. I'm not aware of any other Linux kernel mechanism which achieves that.

The CSI hostpath driver could perhaps provide a block device via some other way (Network Block Device = NBD), but a loop device is the simplest approach.

What might work is to change the implementation of https://github.com/kubernetes/kubernetes/tree/master/pkg/volume/util/volumepathhandler:
- instead of invoking `losetup`, do the necessary ioctl calls directly
- in the situation where `losetup` fails to open a non-existent `/dev/loopX`, create that device node and continue

**Comment by BenTheElder** [comment]
/priority important-soon
too many things going on :/

prow would probably accept running a daemonset that allocated many loop devices on the build nodes if we could hack one up, we have a daemonset right now for increasing inotify watches ...

**Comment by pohly** [comment]
@BenTheElder Do you have a pointer to how that existing daemonset is written?

**Comment by BenTheElder** [comment]
It is here: https://github.com/kubernetes/test-infra/blob/b2d632960440e47f671dd3b997709aa299911456/prow/cluster/tune-sysctls_daemonset.yaml

**Comment by BenTheElder** [comment]
bumping up due to flakes, we'll need to get https://github.com/kubernetes/test-infra/pull/16212 or stop running these tests

**Comment by BenTheElder** [comment]
not quite closed yet, needs to be deployed.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/16230 is deployed now

**Comment by BenTheElder** [comment]
status update: @pohly filed https://github.com/kubernetes/test-infra/pull/16278, which is now deployed

we discussed in slack and confirmed on a prow build node that /dev/loopN are block now. :crossed_fingers:

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/1333 for more followup
