### ISSUE TITLE
kind delete clusters --all Doesn't Account for Different Cluster kubeconfig Paths

### ISSUE THREAD

**Issue by danielhelfand** [kubernetes-sigs/kind#1260]
**What would you like to be added**:

The current implementation of `kind delete clusters --all` only takes into account [one kubeconfig path](https://github.com/kubernetes-sigs/kind/pull/1204#discussion_r367097369) at a time. It would be nice to take into account if clusters created by kind have different kubeconfig paths. 

**Why is this needed**:

The purpose of `kind delete clusters --all` is to delete all clusters, not just clusters associated with a particular kubeconfig. It's by no means a major issue to only delete all clusters by a particular kubeconfig, and I believe this should satisfy most users of kind. 

However, it would be nice to support both options of deleting all by a kubeconfig and actually deleting all clusters regardless of kubeconfig path.

**Comment by danielhelfand** [comment]
Closing this as of this [comment](https://github.com/kubernetes-sigs/kind/pull/1264#discussion_r368183399). If there is a need for a true delete all approach where kubeconfig does not need to be provided explicitly, then this can be reopened.

**Comment by webern** [comment]
> Closing this as of this [comment](https://github.com/kubernetes-sigs/kind/pull/1264#discussion_r368183399). If there is a need for a true delete all approach where kubeconfig does not need to be provided explicitly, then this can be reopened.

I found my way here because a command that does the following would be convenient:

```
kind get clusters | xargs -t -n1 kind delete cluster --name
```

**Comment by BenTheElder** [comment]
Note that a cluster may actually have multiple kubeconfig on the host (see kind export) or this may be done by other tools + kind get.

The rules for which Kubeconfig file is modified based on the inputs follow the official client library (client-go) that nearly all tools are using (we've actually reimplemented this subset of logic because that is a heavy dependency and we only need to manipulate these files). 

Additionally: we don't record where you chose to export Kubeconfig to (which you can do repeatedly into multiple files for a single cluster) and I don't think this is worth the complexity on our end -- the happy path is using a single file and selecting clusters by context. Power users doing something that depends on multiple files could e.g. place all of them in a common directory and rm the contents when deleting the clusters.

**Comment by webern** [comment]
> The rules for which Kubeconfig file is modified

I wouldn't expect the deletion of a cluster to modify the kubeconfig. I wouldn't notice if it did or didn't, in fact. I might be a little weird in that:
- I never have more than one cluster in a kubeconfig (we hates it precious).
- I use kind for testing and treat these kubeconfig as throw away artifacts to be garbage collected.

In any event, `kind get clusters | xargs -t -n1 kind delete cluster --name` does what I need and I just need to alias it or paste it.

**Comment by BenTheElder** [comment]
> I wouldn't expect the deletion of a cluster to modify the kubeconfig.

Hmm, well most cluster tools will remove the cluster's entries from the KUBECONFIG as the opposite of adding them upon creating the cluster. Off the top of my head this includes major cluster tools predating KIND like GKE, kOps, minikube ...

The cluster credentials are of course no longer valid and if you created and deleted many clusters it would eventually bloat the file.

> I use kind for testing and treat these kubeconfig files as throw away artifacts to be garbage collected.

This is why the kubeconfig contents pertaining to the cluster are pruned when deleting the cluster (though not here, when it is across many files).

> In any event, `kind get clusters | xargs -t -n1 kind delete cluster --name` does what I need and I just need to alias it or paste it.

This is confusing though, the snippet you have here should produce identical results to running `kind delete clusters --all`, just more slowly.

**Comment by webern** [comment]
Oh I see, I was running the wrong command:


```
$ kind delete cluster --all
ERROR: unknown flag: --all
FAIL: 1
```

Oops: `kind delete clusters --all` works, sorry.
