### ISSUE TITLE
DualStack UX

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#1275]
**What would you like to be added**:

The more we dig into dual-stack with kubernetes the more doubts it generates, instead of implementing blindly I'd like first to define a good UX from KIND perspective.
At least, we should define the API so it covers most of the use cases.

**Why is this needed**:

DualStack clusters can have several combinations based on the following parameters:

- podSubnets
- serviceSubnets
- IPv6DualStack featureGate

The first subnet determines the default family of the cluster for dual-stack clusters.

Based on that the cluster can be:
- ipv4 only
- ipv6 only
- ipv4 only with dual-stack enabled
- ipv6 only with dual-stack enabled
- dual stack and ipv4 default
- dual stack and ipv6 default

How should we define the API?
```
networking:
  ipfamily: ipv4ipv6-dualstack # or whatever we want to call this
```

**Comment by BenTheElder** [comment]
We definitely want to track upstream closely, it seems currently the APIs there need some rethinking..

**Comment by BenTheElder** [comment]
adding external label until upstream seems settled 🙃

**Comment by aledbf** [comment]
Any update on this?

**Comment by BenTheElder** [comment]
last I checked in upstream was still struggling with this, when upstream is
ready we'll do our best to follow.

**Comment by aojea** [comment]
Dual Stack KEP is going to be updated soon, as soon as it's clearly defined the next steps will update the issue

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/enhancements/pull/1679

**Comment by BenTheElder** [comment]
We should PR kubelet upstream to allow setting multiple node IPs natively.

**Comment by khenidak** [comment]
There are two prevailing thoughts (rest is mechanics). Services are single stack by default (if user want to different default, they should use webhooks). Dualstack is set to be `preferred` or `required` depending on how the api is expressed. Sorry it is taking time. promise we code fast once we get the kep agreed upon.

**Comment by BenTheElder** [comment]
No worries, it will be good to get this right :-)

Thanks for the update!

**Comment by khenidak** [comment]
@BenTheElder time unfreeze this :-)

**Comment by BenTheElder** [comment]
I've been reviewing the PR!

**Comment by BenTheElder** [comment]
this is explicitly a priority for v0.11.0 #2024

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/692
