### ISSUE TITLE
Adding API Options?

### ISSUE THREAD

**Issue by robotica72** [kubernetes-sigs/kind#1291]
Ive been playing around with trying to get kind to deploy using an OIDC provider.  Overall I dont see why it wouldnt work, but I cant get the install to add the options to the API server.  Ive tried using the kubeadm format in my create cluster file, similar to the featuregates but the install fails with:

ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1

Happy to add what I tried in the config, but I thought I would ask to make sure it was possible at all before digging into it more.

**Comment by BenTheElder** [comment]
You can set options on the api server.

can you share:
- the full CLI you used
- the kind version

when debugging, increasing verbosity of `kind` helps (`-v 1`)

**Comment by robotica72** [comment]
Hi Ben - That was a quick reply!   Thanks for the information.

I just managed to get it working - when I had an issue I backed off the extra options and I forgot the add the oidc-client-id option, so with both required options it does start the API server with the two API options.

Im using multiple pods, so my install uses a config yaml, so this works:

nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        oidc-issuer-url: "https://xxxx.xxx.xxx"
        oidc-client-id: "kubernetes"
- role: worker

Thanks again for the quick reply - I really appreciate that.

**Comment by BenTheElder** [comment]
awesome!

yeah, this sort of issue can be frustrating to debug, what you can do is use `kind export logs` while the node is still running (`--retain` will avoid kind deleting it on failure) or yourself look for the pod log in the node. the API server logs would surface the flag issue.

**Comment by robotica72** [comment]
Excellent - Thanks for that note, The API logs would have helped, without a doubt :)
