### ISSUE TITLE
Fish shell completion

### ISSUE THREAD

**Issue by h1nk** [kubernetes-sigs/kind#1303]
**What would you like to be added**:
Fish shell completions.
**Why is this needed**:
For fish shell users.

**Comment by BenTheElder** [comment]
Sorry but we just use the completion tooling provided by the CLI toolkit (cobra), we're not really focused on this.

We'd probably accept a PR if it was done in some maintainable way...

**Comment by BenTheElder** [comment]
fixed by @sayboras in #1516 :-)
