### ISSUE TITLE
no_proxy takes no effect when pulling images from a local registry

### ISSUE THREAD

**Issue by zlwfrank** [kubernetes-sigs/kind#1304]
I'm testing kind kubernetes cluster and the local registry behind corporate proxy. I simply follow the documentations @ https://kind.sigs.k8s.io/docs/user/local-registry/

**What happened**:
Even if 172.17.0.0/16 (the created docker network) is automatically added in the no_proxy environment variable when creating cluster, the request of pulling image from a local registry (whose IP is 172.17.0.2 in my case) is directed to my http proxy, leading to pulling failure.

The proxy configuration of the master node:
```
> docker inspect test-control-plane --format={{.Config.Env}}
[no_proxy=172.17.0.0/16, ...... NO_PROXY=172.17.0.0/16, ...... HTTP_PROXY=corporate_proxy http_proxy=corporate_proxy PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin container=docker]
```

Local registry connection test:
```
> docker exec -it test-control-plane /bin/bash
test-control-plane> curl GET -v registry:5000/v2/_catalog
* Uses proxy env variable no_proxy == 172.17.0.0/16, ......
* Uses proxy env variable http_proxy == "corporate_proxy"
*   Trying "corporate_proxy"...
* TCP_NODELAY set
* Connected to "corporate_proxy_ip" ("corporate_proxy_ip") port "corporate_proxy_port" (#0)
* Proxy auth using Basic with user 'myuser'
> GET http://GET/ HTTP/1.1
> Host: GET
> Proxy-Authorization: Basic xxxxxxxxxx
> User-Agent: curl/7.65.3
> Accept: */*
> Proxy-Connection: Keep-Alive
>
```

With no http_proxy setting, the connection test above lists the images available in the local registry successfully. 

**What you expected to happen**:
Image pulling request from local registry shouldn't touch the http proxy. 

**How to reproduce it (as minimally and precisely as possible)**:
In my case, different way of setting environment variable before creating cluster leads to results as follow:
no http_proxy and https_proxy: 
- Pulling images from a local registry succeeds. 
- Pulling images from a public hub (e.g., hello-world) fails (which is expected).

setting http_proxy, and 172.17.0.0/16 in no_proxy: 
- Pulling images from a local registry fails.
- Pulling images from a public hub (e.g., hello-world) succeeds.

**Anything else we need to know?**:
N/A

**Environment:**
- kind version: (use `kind version`): v0.7.0 
- Kubernetes version: (use `kubectl version`): v1.17.0
- Docker version: (use `docker info`): 18.09.6
- OS (e.g. from `/etc/os-release`): CentOS 7

**Comment by BenTheElder** [comment]
probably `registry` has to be in `no_proxy` ?

**Comment by BenTheElder** [comment]
we're going to be replacing that registry system with something more advanced, we can auto inject this then, but for now I think `NO_PROXY` must contain `registry` when creating the cluster.

we can add this to that script

```
[bentheelder@bentheelder:~/go/src/sigs.k8s.io/yaml·2020-01-31T14:23:55-0800·bump-dep@8582da0]
$ export HTTP_PROXY=foo

[bentheelder@bentheelder:~/go/src/sigs.k8s.io/yaml·2020-01-31T14:24:00-0800·bump-dep@8582da0]
$ export NO_PROXY=""

[bentheelder@bentheelder:~/go/src/sigs.k8s.io/kind·2020-01-31T14:25:22-0800·master@15163922]
$ ./site/static/examples/kind-with-registry.sh 
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋

[bentheelder@bentheelder:~/go/src/sigs.k8s.io/kind·2020-01-31T14:25:44-0800·master@15163922
$ docker exec -it kind-control-plane /bin/bash
root@kind-control-plane:/# curl GET -v registry:5000/v2/_catalog
* Uses proxy env variable no_proxy == '192.168.9.1/24,2001:db8:1::/64,10.96.0.0/12,10.244.0.0/16'
* Uses proxy env variable http_proxy == 'foo'
* Could not resolve proxy: foo
curl: (5) Could not resolve proxy: foo
* Uses proxy env variable no_proxy == '192.168.9.1/24,2001:db8:1::/64,10.96.0.0/12,10.244.0.0/16'
* Uses proxy env variable http_proxy == 'foo'
* Found bundle for host foo: 0x556e2fe5d6a0 [serially]
* Server doesn't support multiplex (yet)
* Connection #0 is still name resolving, can't reuse
* Could not resolve proxy: foo
curl: (5) Could not resolve proxy: foo
root@kind-control-plane:/# export no_proxy="${no_proxy}:,registry"
root@kind-control-plane:/# curl GET -v registry:5000/v2/_catalog
* Uses proxy env variable no_proxy == '192.168.9.1/24,2001:db8:1::/64,10.96.0.0/12,10.244.0.0/16:,registry'
* Uses proxy env variable http_proxy == 'foo'
* Could not resolve proxy: foo
curl: (5) Could not resolve proxy: foo
* Uses proxy env variable no_proxy == '192.168.9.1/24,2001:db8:1::/64,10.96.0.0/12,10.244.0.0/16:,registry'
*   Trying 192.168.9.3:5000...
* TCP_NODELAY set
* Connected to registry (192.168.9.3) port 5000 (#1)
> GET /v2/_catalog HTTP/1.1
> Host: registry:5000
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< X-Content-Type-Options: nosniff
< Date: Fri, 31 Jan 2020 22:27:01 GMT
< Content-Length: 20
< 
{"repositories":[]}
* Connection #1 to host registry left intact
```

**Comment by zlwfrank** [comment]
@BenTheElder Thanks for the quick response. I've conducted several tests and they're all working. Previously, I thought adding `registry` in the `/etc/hosts` is enough to make it work. 

I would suggest to mention it in the documentation if you don't plan to replace the current registry system very soon, since I think it seems to be required to make the local registry work behind a proxy.

I appreciate your help.
