### ISSUE TITLE
Add doc explaining how to access one kind cluster from another

### ISSUE THREAD

**Issue by hossainemruz** [kubernetes-sigs/kind#1305]
**What would you like to be documented**:
We would like to have a documentation on how to access one kind cluster from another.

**Why is this needed**:
We are facing a use case where we need to connect between two clusters. One cluster need to be able to perform some operations on another. For, two kind cluster, we need to modify the kubeconfig (`kind-config-kind`) file before using it inside one of the clusters. We have to replace the address of
```
server: https://127.0.0.1:32769
```
with
```
server: https://<cluster's control-pane ip >:6443
```

I would like to submit a PR with necessary explanation.

**Comment by BenTheElder** [comment]
You just need to use `kind get kubeconfig --internal` to get the contents of one with the internal IP. Or `kind export kubeconfig --internal`. No manual IP swapping required.

There is help usage for these commands in the CLI.

**Comment by hossainemruz** [comment]
Wow. That's cool. Thank you @BenTheElder.
