### ISSUE TITLE
Any way to patch the API server after deployment without losing the current cluster state?

### ISSUE THREAD

**Issue by robotica72** [kubernetes-sigs/kind#1307]
I think I may be getting a bit complex in what I would like to do, but it has a huge use case for me and some labs I am doing.  

What I hoping to figure out is if I am able to deploy Kind, but afterwards I want to update the API options with a parameter for OIDC.  In this case the requirement is that I use K8s to generate the cert for the OIDC and of course, I cant do that before the cluster is up and running.  I know I can add the API parameters during the installation of Kind but I wont have the cert until after its all up and request, so on a standard cluster I would normally just patch the API server POD with the new cert and everything is good.   Of course, we cant restart the Kind master since it will lose the state of the cluster.

Any ideas?   The only potential one I saw was to script a kubectl exex into the master node which will add the required changes and restart the API server?

**Comment by BenTheElder** [comment]
>  ... so on a standard cluster I would normally just patch the API server POD with the new cert and everything is good. 

Why can't you do that here? :upside_down_face: 

> Of course, we cant restart the Kind master since it will lose the state of the cluster.

You shouldn't need to restart a node to update a pod.

**Comment by robotica72** [comment]
Hey Ben - Sorry, my description was probably a bit vague.   So on a different K8s install that run each K8s component in a dedicated container, I could patch the API server deployment with my changes and it would just restart the POD.   

I cant do that with Kind since the master container is running all of the control plane and of course restarting the container will cause the cluster to have issues.  (Unless I missed some update - Last I knew, restarting the container breaks everything).

So I need to add an API option that I cant add during initial deployment - I can only add the option after the cluster is up and running and it approves a cert request that is submitted through a deployment I use.   With that cert, I need to patch the API options and restart the API server for that to take effect.

I did test it by execing into the container, made the changes I needed to, and I killed the api server process which started back up with my changed options loaded.

**Comment by BenTheElder** [comment]
kind runs the api server as a pod, it's a bit confusing since that is "inside" the "node container"

```console
$ kubectl get po -A
NAMESPACE     NAME                                         READY   STATUS    RESTARTS   AGE
kube-system   etcd-kind-control-plane                      1/1     Running   0          13s
kube-system   kube-apiserver-kind-control-plane            1/1     Running   0          13s
kube-system   kube-controller-manager-kind-control-plane   1/1     Running   0          13s
kube-system   kube-scheduler-kind-control-plane            1/1     Running   0          13s
```

**Comment by robotica72** [comment]
lol  -- DOH!   I heavily over looked that, I was so focused on the Kind image in Docker that I ignored the POD in K8s!   Wow, its a Monday and not a good one for me :)  Apologies for wasting your time on this one.  Thanks for the quick reply (as always)!

**Comment by BenTheElder** [comment]
no worries!
I think what you would normally do will just work, except possibly how you
go about executing it, might need to swap an ssh call for docker exec.

**Comment by robotica72** [comment]
I think so too - It should work similar to other cluster deployment I have used.  Exciting stuff, this will make a lab Im working on so easy to implement!   Cant thank you and the team enough for Kind - and, on a side note, even more so if/when you can maintain a cluster state.   My fix right now is to have a script for every "lab" that will rebuild the cluster up to the latest lesson, just in case a student reboots or does something with Docker.

**Comment by BenTheElder** [comment]
should we close this one out or do you have further questions?
🙃

**Comment by ssurovich** [comment]
Hi Ben - Sorry, I should have closed it, Ill do that now - Thanks again for the information.

**Comment by robotica72** [comment]
Hey @BenTheElder - Yep, Ill lose it now, Thanks again for the help!

**Comment by BenTheElder** [comment]
thanks! :-)
