### ISSUE TITLE
Improve logging when using kind load docker-image

### ISSUE THREAD

**Issue by jroper** [kubernetes-sigs/kind#1322]
Here's the current output when loading a docker image:

```
Image: "my-image:latest" with ID "sha256:cc850a8c6a875325fcb385496e7f3eeed15ea8514babdce95f09c03379a07904" not present on node "kind-control-plane"
```

This message looks like an error message. It gets me every time, I'm scanning through the logs of a failed build, I see it and I think "oh it's failed to find the docker image". And then I remember no, that's what kind outputs when everything's ok. People who are less experienced with kind on my team have often assumed that that is the problem, and wasted time going down rabbit holes trying to debug a problem that doesn't exist.

A small change in wording of the message would make a huge difference to UX here, eg:

```
Image: "my-image:latest" with ID "sha256:cc850a8c6a875325fcb385496e7f3eeed15ea8514babdce95f09c03379a07904" not yet present on node "kind-control-plane", loading...
```

Note the addition of the words `yet` and `loading...`.

**Comment by BenTheElder** [comment]
"yet" makes sense. commented on #1323 

FWIW Note that our errors have big red `ERROR:` prefixes, and warnings have a similar yellow one. If you ever try to create a cluster by the same name while it already has resources (a common encounter with the default in particular) you will see one then. Anything else is not an error.
