### ISSUE TITLE
spinning up kind cluster directly with docker run ...

### ISSUE THREAD

**Issue by RafalSkolasinski** [kubernetes-sigs/kind#1338]
First of all, `kind` is awesome!

I also believe that simple `kind create cluster` works perfectly in 99% of use cases.

I wonder though, it is possible to spin up `kind` cluster with something like
```bash
docker run -d kindest/node:latest ...
```
and if this is not available out of the box how much of work it would be to modify `kindest/node` image to make it possible? Any pointers or rough list of required steps would be very helpful!

Ideally, I'd like to craft `docker-compose` file with two containers: one for `kind` cluster and one for `kubectl` and other custom stuff to interact with `kind` cluster in first container

**Comment by BenTheElder** [comment]
This is not supported, the complexity isn't currently worth it to us as we already need to orchestrate multi node clusters which is simpler with host logic (though perhaps feasible without) besides the kind config handling for complex scenarios.

We ask that you use one small binary with a simple interface to give us more flexibility in implementing the bringup.

It would be possible to wrap this binary in a container if you *must* use docker-compose, there is at least one previous closed issue about this with details 😅

**Comment by RafalSkolasinski** [comment]
@BenTheElder Thanks for the reply. It is just that sometimes it may be handy to have image with cluster already ready to go with default configuration. 

I gonna experiment with some dirty hacks of doing `docker commit ...` on already provisioned cluster :sweat_smile: 

Will let you know if I came up with anything useful...

**Comment by BenTheElder** [comment]
note that you're going to need a lot of flags beyond just `docker run -d`, that's a lot of what the kind binary actually handles.

please do update if you find anything, but for now i'm closing this out while triaging the issue tracker.
