### ISSUE TITLE
Is KinD ingress hostname addressable inside the cluster

### ISSUE THREAD

**Issue by ivorywang** [kubernetes-sigs/kind#1339]
I am currently trying to debug an issue I am facing with some of my pods while running KinD. Essentially what it boils down to is that I need 2 pods in my KinD cluster to be able to communicate on the ingress hostname I give to the cluster. Right now I can verify that my ingress is working because my webapp is accessible on the hostname (after making a change to my local machine's etc/hosts). I also notice that inside the KinD cluster, specifically in one of the containers running there, that hostname is not addressable. Can someone with more networking understanding enlighten me as to what might be going on here and why I can't use the ingress hostname for inter-pod communication?

**Comment by amwat** [comment]
Ingress is used only to enable access to the cluster services from outside the cluster.
https://kubernetes.io/docs/concepts/services-networking/ingress/#what-is-ingress

Inside the cluster you should be able to use the service FQDN directly https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#services

If you want the same hostname to resolve to the service ip, you might need to try out https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/ 

ref: https://github.com/kubernetes/kubernetes/issues/39792

**Comment by ivorywang** [comment]
@amwat Thanks for the comment man appreciate the clarification! Unfortunately I cannot use option 2 because the inter-pod communication needs to also be accessible to the user outside the cluster. I am going to have a look at option 3 you have provided, thanks again!

**Comment by aburgos02** [comment]
I am seeing the same behavior in my deployment. I have pod that is trying to resolve the hostname of the KinD container and is unable to do so. Pinging the KinD container IP address from within the pod works but no luck with the hostname. Are there any suggestions on how I can make that hostname routable from within the pod without having to add an entry in the pod;s /etc/hosts file?

**Comment by amwat** [comment]
@aburgos02 I think your situation is a bit different. IIUC you want to be able to resolve the hostname of the docker container "node" itself from inside the cluster.

Might be useful to know the exact use case you are trying to achieve with this?

IIRC the docker hostname is just an entry in `/etc/hosts` inside the "node" container, and the pods inside the cluster will not inherit it by default 
https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/#why-does-kubelet-manage-the-hosts-file. 
So in general you would want to use the `hostAliases` method.

That being said, you might be able to achieve what you want by using `hostNetwork:true` https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces in your pod spec. 
But note that it would result in the pod using the node's (which wrt KIND is the docker container) networking directly.

**Comment by aojea** [comment]
For completeness, @rpkatz just tweeted an example on how to use hostAliases 
https://twitter.com/rpkatz/status/1231727728539377664?s=19

> 
> Need to run metrics-server inside KinD but it cannot reach kubelet metrics? Get the  KinD container IP, edit metrics-server deploy and put a hostAliases (https://t.co/3d76Czy7iq) pointing to that IP:
> 
> hostAliases
> - ip: "172.17.0.2”
>    hostnames:
>    - "kind-control-plane"

**Comment by BenTheElder** [comment]
I think this has been answered?
If not please file a new issue or `/reopen`
/close
