### ISSUE TITLE
zsh: command not found: kubectl

### ISSUE THREAD

**Issue by darshanparab** [kubernetes-sigs/kind#1343]
**What happened**:
kubectl throws command not found error post cluster creation using kind create cluster

**What you expected to happen**:
Should be able to run kubectl

**How to reproduce it (as minimally and precisely as possible)**:
Download and add kind to path as mentioned below
```
curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64"
chmod +x ./kind
mv ./kind /some-dir-in-your-PATH/kind
```
**Anything else we need to know?**:
This is how I created the cluster
```
➜  ~ kind create cluster --name hello-world --config=.kube/config
Creating cluster "hello-world" ...
 ✓ Ensuring node image (kindest/node:v1.16.4) 🖼 
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
 ✓ Preparing nodes 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-hello-world"
You can now use your cluster with:

kubectl cluster-info --context kind-hello-world

Thanks for using kind! 😊
➜  ~ kubectl
zsh: command not found: kubectl
```
config file:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  image: kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55
```

**Environment:**

- kind version: (use `kind version`): kind v0.7.0 go1.13.6 linux/amd64
- Kubernetes version: (use `kubectl version`): unabel to run kubectl
- Docker version: (use `docker info`): 19.03.6-ce
- OS (e.g. from `/etc/os-release`):
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

**Comment by BenTheElder** [comment]
ah, you're going to need to install `kubectl`.

https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by darshanparab** [comment]
Thanks a lot @BenTheElder for pointing that out. That was silly of me. I thought, like minikube, this will also make kubectl available.

**Comment by BenTheElder** [comment]
imho it's bad that our documentation assumes kubectl is available though, we should update it with a reference to this.

**Comment by boddumanohar** [comment]
@bentheelder Created an PR for this.

**Comment by boddumanohar** [comment]
```
➜  ~ kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?
➜  ~ kind             
/usr/local/bin/kind: 1: /usr/local/bin/kind: Not: not found
```
I installed kubectl and kind using instruction in documentation, I still get this error.

**Comment by maxpaj** [comment]
> ```
> ➜  ~ kubectl get nodes
> The connection to the server localhost:8080 was refused - did you specify the right host or port?
> ➜  ~ kind             
> /usr/local/bin/kind: 1: /usr/local/bin/kind: Not: not found
> ```
> 
> I installed kubectl and kind using the below instructions in documentation, I still get this error.
> 
> ```
> curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64
> chmod +x ./kind
> mv ./kind /some-dir-in-your-PATH/kind
> ```

Did you find a solution to this?

**Comment by zachradtka** [comment]
I am using Windows with WSL 2. For me `uname` was resolving to "Linux" so the contents of the file kind was "Not Found"
```
❯ uname
Linux
❯ cat kind
Not Found%
```
So I used the following command to download kind:
```
curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.9.0/kind-linux-amd64
```

**Comment by BenTheElder** [comment]
we may need to upgrade the guide.
when it was written, github served files case-insensitively

**Comment by zachradtka** [comment]
Not sure if all the releases are lowercase, but a simple fix would be:
```
curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname | tr '[:upper:]' '[:lower:]')-amd64
```
