### ISSUE TITLE
Add a CommandContext to the exec package

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/kind#1364]
The standard library exposes the `exec.CommandContext` function that takes a context. It would be great if kind's exec library also exposed the context version of the exec.Command function.

This could be an additional function added to `LocalCmder` and either a new interface or a new function added to the `Cmder` interface.

I would be happy to open a PR for this if y'all are interested in adding this to your exec package!

**What should be cleaned up or changed**:
This should be added because there is no convenient way to pass a context into the command library. Sometimes commands can hang indefinitely and it would be really nice to add a timeout in some cases.

**Why is this needed**:
Being able to cancel long running functions in a reasonable amount of time is nice.

**Comment by BenTheElder** [comment]
Adding this to Cmder SGTM!

I personally think Context is a fairly bad API ... BUT it is what the stdlib gives us for cancellation which is definitely useful to have and we probably should not reinvent cancelling a process 🙃
