### ISSUE TITLE
kind failed to create cluster on RHEL 8.0

### ISSUE THREAD

**Issue by morningspace** [kubernetes-sigs/kind#1365]
**What happened**:

When I use kind to create cluster on a RHEL 8.0 machine, I get below error message:
```shell
$ kind create cluster --config kind-config.yaml
ERROR: failed to list clusters: command "docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster=kind --format '{{.Names}}'" failed with error: exit status 125
```

**What you expected to happen**:

Cluster can be created successfully.

**Anything else we need to know?**:

I think that's related to the different behavior between Docker CLI and the one emulated by Podman. Because when I run the following command directly in terminal. I can see the actual error that causes the problem:
```shell
$ docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster=kind --format '{{.Names}}'
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
error with flags passed: quiet conflicts with size, namespace, and format with go template
```

**Environment:**

- kind version: (use `kind version`): kind v0.7.0 go1.13.6 linux/amd64
- Docker version: (use `docker info`): podman 1.0.5
- OS (e.g. from `/etc/os-release`): RHEL 8.0 (Ootpa)

**Comment by BenTheElder** [comment]
there is actual podman support in HEAD, please give that a try.

**Comment by BenTheElder** [comment]
this was fixed already in https://github.com/kubernetes-sigs/kind/pull/1276

**Comment by BenTheElder** [comment]
prior to the KIND internal podman specific backend this was not supported behavior though, as we expect `docker` in your path to in fact be compatible with well docker ... we consider incompatibilites to be a podman bug.

given that these bugs do exist though, (and some non-bug outright incompatibility e.g. networking and rootless) we simply have an internal podman node backend now.

you can try this by installing the latest KIND source code until we have a new release.

after cloning the repo:
`make build DOCKER=podman && ./bin/kind create cluster`

**Comment by BenTheElder** [comment]
I do not recommend putting a fake `docker` in your path, the emulation is not sufficient.

Since you do have a fake `docker`, you may also need to set the experimental option:
`export KIND_EXPERIMENTAL_PROVIDER=podman` before running `kind` so it does not select `docker` given the presence of """docker"""

**Comment by morningspace** [comment]
Thanks for your help. This is greatly helpful! @BenTheElder
