### ISSUE TITLE
docker windows desktop can't set up kind-control-plane container restart policy

### ISSUE THREAD

**Issue by liweilun0408** [kubernetes-sigs/kind#1385]
PS C:\Users\liweilun\Desktop> kubectl.exe get pods --all-namespaces
NAMESPACE            NAME                                         READY   STATUS    RESTARTS   AGE
kube-system          coredns-6955765f44-m4w7h                     1/1     Running   0          26s
kube-system          coredns-6955765f44-q7wvs                     1/1     Running   0          26s
kube-system          etcd-kind-control-plane                      1/1     Running   0          23s
kube-system          kindnet-pqm7f                                1/1     Running   0          26s
kube-system          kube-apiserver-kind-control-plane            1/1     Running   0          23s
kube-system          kube-controller-manager-kind-control-plane   1/1     Running   0          23s
kube-system          kube-proxy-5j597                             1/1     Running   0          26s
kube-system          kube-scheduler-kind-control-plane            1/1     Running   0          22s
local-path-storage   local-path-provisioner-85445b74d4-kbx8z      1/1     Running   0          26s
PS C:\Users\liweilun\Desktop> kubectl.exe get nodes --all-namespaces
NAME                 STATUS   ROLES    AGE   VERSION
kind-control-plane   Ready    master   56s   v1.17.2
PS C:\Users\liweilun\Desktop> docker update kind-control-plane --restart always
Error response from daemon: Cannot update container 33ae8e309c97e593641d5114cf2996c4349102a3d26fdbce8e16dc0bf5ce486e: runc did not terminate sucessfully: failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/docker/33ae8e309c97e593641d5114cf2996c4349102a3d26fdbce8e16dc0bf5ce486e/devices.allow: invalid argument
: unknown

**Comment by liweilun0408** [comment]
docker version is 19.03.5 , kind version is 0.7.0

**Comment by BenTheElder** [comment]
We will include a restart policy when #148 is resolved.

Until then don't expect it to work at all unfortunately.
