### ISSUE TITLE
how to connect between multiple clusters

### ISSUE THREAD

**Issue by hiromaily** [kubernetes-sigs/kind#1386]
I created 2 clusters each cluster has different roles.
My question is how to connect from one of pods in ClusterA to one of pods in ClusterB.
Is there any good solution? Thanks.

**Comment by aojea** [comment]
We have a PR with documentation on this topics

https://github.com/kubernetes-sigs/kind/pull/1337

There is an example there on how to connect pods between different clusters

**Comment by hiromaily** [comment]
@aojea Thanks :)
