### ISSUE TITLE
Use community-owned GCS bucket for kind ci builds

### ISSUE THREAD

**Issue by spiffxp** [kubernetes-sigs/kind#1392]
**What should be cleaned up or changed**:
Instead of using gs://bentheelder-kind-ci-builds use something that's been provisioned through wg-k8s-infra

**Why is this needed**:
As kind is used for merge-blocking and release-blocking jobs for kubernetes/kubernetes, this ensures the community can own and support where the kind artifacts are stored

Opening this issue to reference in TODO

ref: https://github.com/kubernetes/test-infra/pull/16704#pullrequestreview-371629510

**Comment by justaugustus** [comment]
Thanks for opening this, Aaron!

**Comment by BenTheElder** [comment]
Just to clarify:
- we do not support KIND CI builds for any purpose other than testing Kubernetes currently
- these are purely an optimization over go get
- the bucket name is to highlight the need to move to a wg k8s supplied bucket
- prow has full ownership over the bucket so I'm not too worried about continuity even if we somehow absolutely depend on the optimization

**Comment by BenTheElder** [comment]
(in addition to the TODOs I've left about this)
/assign

**Comment by BenTheElder** [comment]
Basically for now these binaries are an open secret optimization for Kubernetes CI. For everyone else we ask that you use a tagged release with binaries on GitHub or build and host at your own at your own risk.

We should still establish officially unsupported hosting 😛

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/k8s.io/issues/654

**Comment by BenTheElder** [comment]
some progress in https://github.com/kubernetes/k8s.io/issues/654

**Comment by BenTheElder** [comment]
per discussion I sent https://github.com/kubernetes/k8s.io/pull/744 and we have a staging project now (thanks @spiffxp for actuating).

next up we'll setup a proper trusted cloudbuild job.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1483
https://github.com/kubernetes/test-infra/pull/17246

**Comment by BenTheElder** [comment]
looks like something is actually building finally https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-kind-push-binaries/1250972940258775042

**Comment by BenTheElder** [comment]
`gs://k8s-staging-kind/latest/...` is populated.

I'm going to take the opportunity to clean up how we upload these slightly and then migrate CI to consuming these.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/17258 will move a test job.

**Comment by BenTheElder** [comment]
test job is up and running tests https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-e2e-kind-canary/1251005530344787968

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/17260 will fix

**Comment by BenTheElder** [comment]
We'll look at moving some or all of this to the prod bucket with permanent retention in the future.

I'm unsure how much we should be tossing in there. Right now these builds are created after every merge in this repo and each platform is 9MB, with the new tarballs etc. it's about 84MB total for what we build and upload, or about a gigabyte in GCS every 12 merges.

The current bucket has 60 day retention.
