### ISSUE TITLE
Add CLI command to list images installed on Nodes

### ISSUE THREAD

**Issue by JamesLaverack** [kubernetes-sigs/kind#1393]
**What would you like to be added**:

A new CLI subcommand that would list images present in a given kind cluster.

I have no particular opinion on the exact semantics, but a few ideas:

- `kind images`, most like `docker images`
- `kind get images`, fits with the other `kind get` commands
- `kind images list`, possibly combined with moving other image-related commands (such as `kind load`) under a new `images` subcommand.

I'd imagine that this command would accept the `--name` flag to specify which cluster is being referred to, and a `--nodes` flag to list images from (likely with some de-duplication, or column in a tabular result that shows which nodes an image is on).

**Why is this needed**:

- Aid in debugging, understanding why Pods are failing to pull images by allowing a user to inspect the image store in the nodes.
- Verify that a `kind load` command completed successfully.

**Comment by BenTheElder** [comment]
I don't think we have a good pattern for doing this on multiple nodes we don't have the CLI machinery for this atm, is `docker exec kind-control-plane crictl ...` insufficient?
