### ISSUE TITLE
expose insecure ports

### ISSUE THREAD

**Issue by xuejipeng** [kubernetes-sigs/kind#1396]
Can I expose insecure ports, like 8080.

**Comment by aojea** [comment]
yes, but bear in mind those are insecure :wink:

**Comment by xuejipeng** [comment]
@aojea Thank you, but where is the relevant documentation?

**Comment by aojea** [comment]
ahh, ok, sorry

https://kind.sigs.k8s.io/docs/user/quick-start/#mapping-ports-to-the-host-machine

**Comment by xuejipeng** [comment]
@aojea thx
