### ISSUE TITLE
Difficult to find documentation on extraMounts

### ISSUE THREAD

**Issue by jsolbrig** [kubernetes-sigs/kind#1398]
**What would you like to be documented**

The word "volume" needs to be added to documentation for [extraMounts](https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts) to make it easier to find.

**Why is this needed**:

Currently, since mounting volumes into the kind containers uses the noun "mount" rather than "volume", it doesn't match well with the rest of the k8s ecosystem and is very difficult to find in the documentation. There is no mention of the word "volume", which is the more obvious noun to look for.

Honestly, it would be nice to change "extraMounts" to "extraVolumes" to make it match better with the language commonly used in k8s.

**Comment by BenTheElder** [comment]
So "mounts" are the correct Kubernetes language. Volumes are a medium of allocated storage. volume **mounts** are how they are mounted into pods.

These are specifically bind mounts, a Linux concept that is in effect similar to using a hostPath volume + mount.

The actual APJ spec comes from Kubernetes container runtime interface's mount type.

We don't currently actively support arbitrary volumes, nodes normally wouldn't have these in Kubernetes, but we understand that it may be useful to bind mount something from the host in a local cluster.

**Comment by BenTheElder** [comment]
These are essentially the `volumeMounts` field, except instead of referencing a named volume they reference a path to bind mount.

The original type spec is here https://github.com/kubernetes/cri-api/blob/f133380b3b509940f180cb0e94cc154c2d71122d/pkg/apis/runtime/v1alpha2/api.proto#L188
