### ISSUE TITLE
Can I test on different K8s versions?

### ISSUE THREAD

**Issue by AceHack** [kubernetes-sigs/kind#1400]
Will kind allow testing on different K8s versions?

**Comment by aojea** [comment]
The k8s veesion used by kind is "embedded" on the node image.

So, the answer is yes, there are official kind images with different kubernetes version, you can find the ids in the releases notes:

https://github.com/kubernetes-sigs/kind/releases

but you can always create your own image from a specific kubernetes branch or commit 
https://kind.sigs.k8s.io/docs/user/quick-start/#building-images

There are some talks about that too:
 https://kind.sigs.k8s.io/docs/user/resources

**Comment by BenTheElder** [comment]
Yep, see the images in the release notes and the --image flag or the image field in nodes in config.

Please be sure to include the image digest.
