### ISSUE TITLE
Kind load docker-image failed

### ISSUE THREAD

**Issue by AlexsJones** [kubernetes-sigs/kind#1406]
**What happened**:

_Thanks in advance for any help_

- Create cluster
- Build docker image locally
- Load docker image into cluster 
- Exit 1

**What you expected to happen**:

- Create cluster
- Build docker image locally
- Load docker image into cluster 
- Exit 0

**How to reproduce it (as minimally and precisely as possible)**:

Example repo : https://github.com/AlexsJones/kubeops
( Run run make up && make to repro )

```
VERSION=`cat VERSION`
kind create cluster --name "kind"
docker build -t kubeops:$(VERSION) .
kind load docker-image kubeops:$(VERSION) --name=kind
```

**Anything else we need to know?**:

The inner error is this 

```
 command "docker save -o /tmp/image-tar627419818/image.tar kubeops" failed with error: exit status 1

```

And `/tmp/image-tar627419818/image.tar ` does not exist

Here is a recording: https://asciinema.org/a/arRlnKSv1qTCx4RQaJG5AuYNt

**Environment:**

- kind version: (use `kind version`): 0.7.0
- Kubernetes version: (use `kubectl version`): 1.17.3 
- Docker version: (use `docker info`): 18.09.9
- OS (e.g. from `/etc/os-release`): ubuntu 18.04.4 LTS

**Comment by BenTheElder** [comment]
`docker save -o /tmp/image-tar627419818/image.tar kubeops`

That's the problem right there it is trying to save an image `kubeops` with no image tag. which means `kubeops:latest` to docker etc.

You ran the shell with `kind load docker-image kubeops:$(VERSION) --name=kind`, but shells expand `${VERSION}` to expand a variable `$(VERSION)` in a shell means "run a subshell and evaluate `VERSION` in this shell which evaluates to nothing so kind is receiving image == `kubeops`

**Comment by BenTheElder** [comment]
run `kind load docker-image "kubeops:${VERSION}" --name=kind` instead
