### ISSUE TITLE
Retry kubeconfig modification if locking fails

### ISSUE THREAD

**Issue by Arnavion** [kubernetes-sigs/kind#1425]
**What would you like to be added**:

Currently, if `kind` is unable to lock the kubeconfig during `create cluster` or `delete cluster`, it just gives up on the modification and fails. It would be nice if it retried until it succeeded. It's fine if it's opt-in via a new option to the two commands instead of the default.

**Why is this needed**:

My workflow involves deploying many clusters to the same machine, and it would be nice if I was able to parallelize it by trivially running `kind` in parallel.

---

Workaround:

- For `create cluster`, pass it `--kubeconfig` with a throwaway tempfile so that it doesn't modify the real `~/.kube/config`. Then, after all the clusters have been created, run `kind export kubeconfig` serialized to update the real `~/.kube/config`.

- For `delete cluster`, pass it `--kubeconfig` with a throwaway tempfile so that it doesn't modify the real `~/.kube/config`. Then, after all the clusters have been deleted, run `kubectl config delete-cluster`, `delete-context` and `unset users.<>` serialized to update the real `~/.kube/config`.

**Comment by BenTheElder** [comment]
I think a single retry if the failure is specifically due to locking would be a reasonable approach, we don't want to hang forever on this but it does stink to fail setting up kubeconfig or cluster creation due to this race.

The current code is from a very close following of `client-go`, the official implementation of this for general purpose usage (which we don't pull in to avoid chicken-and-egg issues with testing kubernetes and to keep our tiny binary size down), this was definitely an oversight.

**Comment by Arnavion** [comment]
A single retry wouldn't be enough. I agree that you don't want to hang forever, which is why I suggested adding an option for it so that it's opt-in.

**Comment by BenTheElder** [comment]
I don't think users should be specifying yet another flag for this. Though we should follow whatever the best practices from the existing tooling. A lot of tools write to this file; I'll look again into how other tools in the project handle this (e.g. `kops`).

We need to lock it for a pretty short period of time, and only once per invocation.

**Comment by Arnavion** [comment]
>We need to lock it for a pretty short period of time, and only once per invocation.

Yes, and nevertheless I see the lock errors very reliably every time I deploy, so just retrying once will probably also only let one instance of `kind` make progress and the rest will fail again.

**Comment by BenTheElder** [comment]
only if there's insufficient jitter to the retry. s/once/some bounded number of times/
