### ISSUE TITLE
A few questions about keepalived+haproxy for a new user with kind~

### ISSUE THREAD

**Issue by Wenshiqi222** [kubernetes-sigs/kind#1427]
Recently，i create a HA cluster with 3 control-planes and 3 worker nodes through kind，it is really convenient for new users! Thanks for all the developers. But my intention to create this HA-cluster is that i wanna set a High availability clusers with keepalived+haproxy！ Fortunately，with kind 0.7 ，which automatically started a haproxy container for me，but i got a few questions:
1、I create 3 control-planes, can i regard them as 3 masters?
2、There is only 1 haproxy container running，as i want 3，how can i setup the other 2？
3、How can i install the keepalived，i only konw how to install and config them in  a normal cluster installed with kubeadm，but with kind， i only got one machine，i got confued.

**Comment by tao12345666333** [comment]
> Recently，i create a HA cluster with 3 control-planes and 3 worker nodes through kind，it is really convenient for new users! Thanks for all the developers.

Thanks for feedback!



> 1、I create 3 control-planes, can i regard them as 3 masters?

Yes, you can. 



> 2、There is only 1 haproxy container running，as i want 3，how can i setup the other 2？

We currently use it as our LB,
you can get the internal configuration file through `kind get kubeconfig --internal`.

If you want to add new haproxy and make it work, you need to change a lot of certificate-related things. There is currently no very straightforward method, IIRC.



> 3、How can i install the keepalived，i only konw how to install and config them in a normal cluster installed with kubeadm，but with kind， i only got one machine，i got confued.

The Docker bridge network we currently use, if you want keepalived to work, you need to add some privileges, such as `NET_ADMIN`.
But I am not sure if it is possible to make keepalived work in kind cluster.

**Comment by Wenshiqi222** [comment]
> > Recently，i create a HA cluster with 3 control-planes and 3 worker nodes through kind，it is really convenient for new users! Thanks for all the developers.
> 
> Thanks for feedback!
> 
> > 1、I create 3 control-planes, can i regard them as 3 masters?
> 
> Yes, you can.
> 
> > 2、There is only 1 haproxy container running，as i want 3，how can i setup the other 2？
> 
> We currently use it as our LB,
> you can get the internal configuration file through `kind get kubeconfig --internal`.
> 
> If you want to add new haproxy and make it work, you need to change a lot of certificate-related things. There is currently no very straightforward method, IIRC.
> 
> > 3、How can i install the keepalived，i only konw how to install and config them in a normal cluster installed with kubeadm，but with kind， i only got one machine，i got confued.
> 
> The Docker bridge network we currently use, if you want keepalived to work, you need to add some privileges, such as `NET_ADMIN`.
> But I am not sure if it is possible to make keepalived work in kind cluster.

thanks man, i am considering to use kubeadm to create  two masters and one node to reach my goal,which my computer can accept at most ~ o(╥﹏╥)o

**Comment by BenTheElder** [comment]
I think you will be best off using kubeadm directly on some VMs if you really want to play around with the exact details, currently we're focused first on testing kubernetes itself and then secondly on users developing on top of kubernetes, the loadbalancer details are unlikely to be pluggable in the near future.

this also sounds like a "production" setup, kind is purely for testing, for production HA I'd look at a distro instead of docker-in-docker hacks :-)

**Comment by BenTheElder** [comment]
you *can* hack around this to customize it (e.g. you could delete the kind provisioned LB and replace it) but it won't be supported, and it will be somewhat involved (e.g. you will need to sort out the certs...)
