### ISSUE TITLE
Add support for PVC resizing.

### ISSUE THREAD

**Issue by machine424** [kubernetes-sigs/kind#1429]
Hello,

**What would you like to be added**:
 I’d like to make sure that PVC expanding isn’t yet possible using provisioner: `rancher.io/local-path` or `provisioner: kubernetes.io/host-path`
Are you planning to support this: https://github.com/kubernetes-csi/csi-driver-host-path ?

**Why is this needed**:
To test a tool that automatically resizes PVCs.

**Comment by BenTheElder** [comment]
CSI driver host path can't do multi node properly yet (and we support k8s older than CSI..) but you can certainly install this and either specify a storage class on your pods or change the default storage class. Doing so shouldn't require any changes to kind.

**Comment by machine424** [comment]
Thanks for your response and for confirming that PVC expanding isn't supported by these two provisioners.
I was not suggesting to make it the provisioner by default (although we'll end up ding it).
I only spawn one node clusters, I'll try to install it.

**Comment by BenTheElder** [comment]
please let me know if this works for you.

**Comment by machine424** [comment]
It worked like a charm, I set up a kind one-node cluster, cloned the repo https://github.com/kubernetes-csi/csi-driver-host-path, ran: https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/docs/deploy-pre-1.17.md#deployment, deployed the storageclass in `./examples/csi-storageclass.yaml` (and marked it as the default).
I've only tested the PVC extending feature not the others (snapshotting...)
```
kind v0.7.0 go1.13.6 darwin/amd64
& kindest/node:v1.16.3@sha256:bced4bc71380b59873ea3917afe9fb35b00e174d22f50c7cab9188eac2b0fb88
```

**Comment by BenTheElder** [comment]
thanks for the info

we'll reconsider this in the future, but at the moment this driver is not suitable OOTB for kind

the other driver https://github.com/rancher/local-path-provisioner may be interested in this functionality though, for now we'll be shipping that for various reasons ...
