### ISSUE TITLE
Typo in https://kind.sigs.k8s.io/docs/user/quick-start/ 

### ISSUE THREAD

**Issue by ldurandadomia** [kubernetes-sigs/kind#1432]
Hello,

There is a small typo into the quick-start page on your web site:

Currently it is written:
For example, let's say you create two clusters:

kind create cluster # Default cluster context name is `kind`.
...
kind create cluster --name kind-2
When you list your kind clusters, you will see something like the following:

kind get clusters
kind
**kind-2**
In order to interact with a specific cluster, you only need to specify the cluster name as a context in kubectl:

kubectl cluster-info --context kind-kind
**kubectl cluster-info --context kind-2**

But this is inaccurate.
Creating a cluster with following command:
$ kind create cluster --name kind-2

You  have to query it with:
$ kubectl cluster-info --context kind-kind-2
Kubernetes master is running at https://127.0.0.1:32770 ...

This command does not work:
ldurand@ubuntu:~$ kubectl cluster-info --context kind-2
error: context "kind-2" does not exist

Thanks a lot for this nice tool.

Laurent DURAND

**Comment by aojea** [comment]
Hi @ldurandadomia , thanks for reporting this.
This is a good opportunity to contribute to the project, do you want to send a PR to our docs to fix this?

**Comment by narendrakangralkar** [comment]
Created a pull request for the same. Please visit: https://github.com/kubernetes-sigs/kind/pull/1434

**Comment by tao12345666333** [comment]
/close

thanks!
