### ISSUE TITLE
CertSAN issue's ?

### ISSUE THREAD

**Issue by FLavalliere** [kubernetes-sigs/kind#1435]
We are trying to use KIND with Traefik (We added insecureVerify).
Setting up Kubernetes Dashboard returns in the kubectl an 500 error:

Failed to connect to database:  x509: cannot validate certificate for <ip> because it doesn't contain any IP SANs

I wonder if it is cause by a wrong configuration via kind/kubeadm configs or something else?

**Comment by BenTheElder** [comment]
we definitely have the cert SANs for all ways we expect the components we control to be reachable.... I don't know about traefik or the dashboard though, or what database is being referenced here.

**Comment by FLavalliere** [comment]
I actually digged down the configuration of Kind and how to add certsSans's using The Custom  json patch... it seems it works. 

Though, i could not get the kubernetes-dashboard to work in HTTPS / 8443 using the recommended.yaml (which use the -auto-generate-certificate secret..)

It seems like many people have issue with kubernetes-dashboard ....  i though though that the kubernetes dashboad would request the API Server for certs generation / API and thus could of been an misconfiguration in the kind-config or someting else.

I think its not a "Kind" issue unless i'm mistaken?

**Comment by BenTheElder** [comment]
I'm not sure, I have no recent experience with the dashboard, I tend to use other tools (mostly `kubectl` at the moment...) :sweat_smile:

**Comment by BenTheElder** [comment]
I'm going to suggest filing an issue with the dashboard instead or asking in the kubernetes slack, this is outside of our scope and I don't think any of the active contributors use the dashboard.

**Comment by BenTheElder** [comment]
sorry :(
