### ISSUE TITLE
RROR: failed to create cluster: failed to init node with kubeadm

### ISSUE THREAD

**Issue by latermonk** [kubernetes-sigs/kind#1437]
**What happened**:
use kind create cluster  then prompt:
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1

**What you expected to happen**:
create the cluster ok 

**How to reproduce it (as minimally and precisely as possible)**:
Mac  vagrant centos/7
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):kind v0.7.0 go1.13.6 linux/amd64
- Kubernetes version: (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
- Docker version: (use `docker info`):19.03.8
- OS (e.g. from `/etc/os-release`):CentOS Linux release 7.6.1810 (Core)

**Comment by BenTheElder** [comment]
can you run kind with `-v 1` when creating the cluster?

>Mac vagrant centos/7

is that docker inside vagrant on mac? any reason not to use docker desktop?

do you have enough disk space in the VM? this error usually occurs when most docker things would have failed because the host is not capable.

**Comment by Seshirantha** [comment]
Same error

ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1

**Comment by BenTheElder** [comment]
I'm going to need more information about your failure and your host environment to know why it isn't working for you but common reasons are:
- using an unsupported version of docker (I mean supported by docker upstream... some of the older versions etc. have issues)
- not having enough disk / memory / CPU available to docker to run a kubernetes node (generally disk, occasionally memory, you need something like 600MB memory for one node and at least 2gb disk space to pull the node image and have some space to do things after)
- using a filesystem that doesn't work out of the box with docker in docker https://github.com/kubernetes-sigs/kind/issues/1416#issuecomment-600438973
- using a host environment that cannot nest containers like this (e.g. crostini) https://github.com/kubernetes-sigs/kind/issues/763

please check the [known issues](https://kind.sigs.k8s.io/docs/user/known-issues/)

**Comment by BenTheElder** [comment]
This error just means that [kubeadm](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/) was unable to bring up the control plane successfully, which generally means the host environment is unhealthy.

**Comment by Seshirantha** [comment]
@BenTheElder I appreciate your help.

I'm getting that error when i trying to create a cluster using a config file.  The config file is as follows.
[config.txt](https://github.com/kubernetes-sigs/kind/files/4373714/config.txt)

**Comment by Seshirantha** [comment]
After changing containerPath, from /etc/containerd/config.toml to /dev/mapper/config.toml it worked.

**Comment by BenTheElder** [comment]
I would recommend using something like this in the kind config instead of trying to mount the config file:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches: 
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://blah:5000"]
```
(replace the patch contents with whatever you're setting in this config file)

**Comment by BenTheElder** [comment]
closing due to lack of follow-up details.

**Comment by miry** [comment]
How it could be possible to debug.
The last log message is stuck on:

```
[  OK  ] Started Update UTMP about System Runlevel Changes.
```

How to check the kubeadm command runs after the init process and where the logs of init?

**Comment by BenTheElder** [comment]
`kind create cluster --retain -v 1`
`kind export logs`
lots of log files there.

check against https://kind.sigs.k8s.io/docs/user/known-issues/

**Comment by miry** [comment]
@BenTheElder thanks for the command.

I see logs. It seems kubelete could not be started.

But because was not created I could not get kubelet logs:

```
 $ kind export logs           
ERROR: unknown cluster "kind"
```

Is there any other way to extract logs during the boot?

**Comment by miry** [comment]
Another warning from the logs:

```
I0416 20:58:34.895732      93 checks.go:649] validating whether swap is enabled or not
	[WARNING Swap]: running with swap on is not supported. Please disable swap
```

**Comment by BenTheElder** [comment]
--retain will not clean up, you need that flag when creating it, then
export will work.

**Comment by BenTheElder** [comment]
warnings are not failures.

swap is a normal warning, kubernetes doesn't support this but we set it to allow it and it works, except for memory limits

you will also see failures early on due to cni not being configured.

kubeadm has many "normal" kubelet crashes early on, it's part of the design of kubeadm + kubelet that kubelet just restarts many times.

**Comment by BenTheElder** [comment]
please open a new support issue or join the slack for more interactive support help, I do not monitor closed issues as reliably.

**Comment by TomLan42** [comment]
please check that the name of your cluster should not contain any underscore...
i bumped into the same error when i include an '_' in my cluster name

**Comment by BenTheElder** [comment]
PRs welcome 🙃

**Comment by dbousquet** [comment]
Hello,
I faced similar issue (I'm using Fedora 32), I solved it with:
# sysctl net.bridge.bridge-nf-call-iptables=0
# sysctl net.bridge.bridge-nf-call-arptables=0
# sysctl net.bridge.bridge-nf-call-ip6tables=0
# systemctl restart docker

Note: modify sysctl.conf for persistent kernel setting

**Comment by deecasas** [comment]
> please check that the name of your cluster should not contain any underscore...
> i bumped into the same error when i include an '_' in my cluster name

this one worked for me, thank you!

**Comment by viktor-slavchev-vmware** [comment]
Had the same issue - got resolved after increasing the Docker ram

**Comment by nfelicio1976** [comment]
I used this comand and worked :)

kind create cluster --retain -v 1

**Comment by lkravi** [comment]
I experienced the same issue in Mac OS with Docker Desktop. Once I increase the resources issue went away. basically added more memory.

**Comment by piyushvj** [comment]
SAME ISSUE :

ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1

if issue is because of memory, can someone tell me how to increase it ? I have ubuntu via wsl2.

**Comment by BenTheElder** [comment]
Hi: please see: https://github.com/kubernetes-sigs/kind/issues/1437#issuecomment-602975963

I am going to lock this issue now, _please_ file new issues with your specific environment details. The current issue title is a _symptom_ not a specific bug, and it is difficult to help with N different bugs threaded within the same issue.

Regarding the specific issues so far: 
- https://github.com/kubernetes-sigs/kind/issues/1437#issuecomment-751673993 this comment is resolved in current kind release, we validate this. https://github.com/kubernetes-sigs/kind/pull/2226


- https://github.com/kubernetes-sigs/kind/issues/1437#issuecomment-857608626 depends on too many factors, but yes, docker desktop app has memory limits and if your limits are too low for your usage things like kind will break. the defaults are sufficient for a cluster and some workloads, but it really depends on what you are doing if you will exceed them.

- cc @aojea re: https://github.com/kubernetes-sigs/kind/issues/1437#issuecomment-715315693, we should probably update docs somewhere for fedora regarding this / a known issues-entry?

For everyone else:

If you find this issue and you are having issues creating a cluster:
1. Please reference https://kind.sigs.k8s.io/docs/user/known-issues/ first
2. If you can't find anything there, please do file a new issue, fill out the template and include all of the relevant info including:
- your operating system and version
- your docker or podman version and `docker info` / `podman info` so we can see if you are e.g. trying to use rootless etc.
- your kind version, so we know which version you're using
- your exact command / configuration used, so we can see what image you're using etc.

**Comment by BenTheElder** [comment]
For WSL2: please start with https://kind.sigs.k8s.io/docs/user/using-wsl2/

**Comment by aojea** [comment]
> * cc @aojea re: [#1437 (comment)](https://github.com/kubernetes-sigs/kind/issues/1437#issuecomment-715315693), we should probably update docs somewhere for fedora regarding this / a known issues-entry?

I don't think is a good idea because that completely disables  iptables on the host bridges, for sure it will work for that user if he has an environment that adds more iptables rules to the bridges, but we shouldn't promote in the website because that can also cause another undesired behaviours, ie. if there are legit iptables rules to drop traffic on a bridge those will stop to work.

I think that current known issues and documentation are ok, install docker and configure firewalld correctly https://kind.sigs.k8s.io/docs/user/known-issues/#fedora32-firewalld
