### ISSUE TITLE
Makefile in root(kind/) should add build base image rule 

### ISSUE THREAD

**Issue by jiatongw** [kubernetes-sigs/kind#1439]
**What would you like to be added**:

Hi, I noticed that `kind build base-image` recently been removed and it is can be built with `make quick` command in `images/base` directory. It would be better if this can be added into Makefile in root directory also.

**Why is this needed**:
All the information for making base image are in a subdirectory. It takes a while to look for instructions. Adding a rule to Makefile in root directory would make it easier.

**Comment by BenTheElder** [comment]
Hi, I'd rather not clutter the root makefile. The images are relatively isolated subprojects, e.g. kindnetd is actually it's own go module.

How to build this image is documented in the docs site, and we're not expecting many users to need to build it.

**Comment by jiatongw** [comment]
Thanks
