### ISSUE TITLE
Multinode cluster creation failed 

### ISSUE THREAD

**Issue by rajalokan** [kubernetes-sigs/kind#1440]
**What happened**:
While creating a multinode cluster, I'm getting this error 
```
Creating cluster "kind" ...                                                                                                                                                                                         
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼                                                                                                                                                                     
 ✓ Preparing nodes 📦 📦 📦                                                                                                                                                                                         
 ✗ Writing configuration 📜                                                                                                                                                                                         
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-worker cat /kind/version" failed 
with error: exit status 1
```

**What you expected to happen**:
Should be a success like any other `kind create cluster` command.

**How to reproduce it (as minimally and precisely as possible)**:
Run this 
```
cat <<EOF | kind create cluster --config -
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
EOF
```

**Anything else we need to know?**:
Following document from here https://kind.sigs.k8s.io/docs/user/configuration/

**Environment:**

- kind version: (use `kind version`):
```
kind v0.7.0 go1.13.6 linux/amd64
```

- Kubernetes version: (use `kubectl version`):
`1.16.1`

- Docker version: (use `docker info`):
`18.06.1-ce`

- OS (e.g. from `/etc/os-release`):
`Ubuntu 18.04`

**Comment by rajalokan** [comment]
However I tried this suggestion from Ben [here](https://github.com/kubernetes-sigs/kind/issues/1416#issuecomment-600438973)  and this works. My new config is 

```
cat <<EOF | kind create cluster --config -
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /dev/mapper
    containerPath: /dev/mapper
- role: worker
EOF
```

Should this be added to the documentation bit [here](https://kind.sigs.k8s.io/docs/user/configuration/#nodes) ( as a side note)?

**Comment by BenTheElder** [comment]
/dev/mapper is a different issue related to using filesystems that require it.

docker in docker / kubernetes used to not work at all on zfs/btrfs/...

this is a different issue, de-duping. https://github.com/kubernetes-sigs/kind/issues/1416

**Comment by BenTheElder** [comment]
we're going to handle this OOTB ideally.
