### ISSUE TITLE
Request: Support for ppc64/ppc64le for base image

### ISSUE THREAD

**Issue by runlevel5** [kubernetes-sigs/kind#1444]
I would like to ask if there is any plan to build base image for ppc64 / ppc64le architecture. 

NOTE: Travis CI does offer ppc64 build

**Comment by BenTheElder** [comment]
We've started experimenting with multi-arch support *for the base image*. Currently that includes arm64 as the most requested architecture.

I'm not thrilled with it so far as it's *really* slow to build by comparison and this is hurting iteration time on what is still something of an alpha project. Users on PowerPC / ARM can always build the base image themselves, that one is actually just a normal docker image build anyhow.

> NOTE: Travis CI does offer ppc64 build

We don't have access to travis-ci currently. The Kubernetes organization uses Prow. https://github.com/kubernetes/test-infra/tree/master/prow

**Comment by BenTheElder** [comment]
The base image and all of it's dependencies should build fine on PowerPC as far as I know.
I'm not sure that we will plan to build it by default in the pre-built images. The tradeoff between time / maintenance cost and users / contributors seems poor currently.

**Comment by runlevel5** [comment]
@BenTheElder Thanks for sharing the insight. The OpenPOWER community is growing and I could see many DevOps/SysAdmins/Developers are embracing it. If there is anything I could help to get ppc64le better supported, please let me know. I know integricloud.com has been very supportive to OSS, they might be able to help the project with host to build the image.

**Comment by BenTheElder** [comment]
I'm lacking a reason why kind is the place to invest in this. IMO if someone wants better kubernetes support on power hardware they should come supply real upstream CI to _Kubernretes_ with real clusters (e.g. actually using kubeadm), KIND is meant for use in our own CI (amd64) and developer workstations...

Lacking any progress on that, this seems like an unnecessary distraction for the kind project.

cc @mkumatag

**Comment by BenTheElder** [comment]
If this support is to get better *kubernetes* support on power, that should be done upstream ideally with bare metal or "cloud" and I'd ask someone else to do this work, not us.

If this support is about development, I'd still suggest using something else, kind is for *local* clusters, not for hosting remote clusters. AIUI the majority of power hardware out there is big metal, not workstations, and I'm certainly not aware of any kubernetes developers on power hardware, it's all amd64..

**Comment by runlevel5** [comment]
> If this support is to get better kubernetes support on power, that should be done upstream ideally with bare metal or "cloud" and I'd ask someone else to do this work, not us.

This is a good question for IBM. From my knowledge, there are k8s on POWER platform by IBM but they aren't popular outside the circle. I believe IBM/RedHat would extend the support for OpenPOWER in the the near future.

> If this support is about development, I'd still suggest using something else, kind is for local clusters, not for hosting remote clusters. AIUI the majority of power hardware out there is big metal, not workstations, and I'm certainly not aware of any kubernetes developers on power hardware, it's all amd64..

Atm, I am hosting a local cluster using QEMU/KVM after failing to get `minikube` (of which base image is based on top kindest/base) up running.

Lastly, I do not want to cause any distraction for the project, however if the project decides to support ppc64le, I am more than happy to help.

**Comment by BenTheElder** [comment]
[revisiting in the next milestone]

**Comment by BenTheElder** [comment]
This was actually fixed already, I just missed closing it.
When #381 lands we'll also have good footing to pre-publish node images for other architectures.

Right now you can build a node image yourself for ppc64 using `kind build node-image` and a kubernetes checkout.
