### ISSUE TITLE
Pods are still running after stopping the simulated Node.

### ISSUE THREAD

**Issue by lenhattan86** [kubernetes-sigs/kind#1445]
**What happened**:
There are pods running on a worker node. 
After we stop the node by stopping its container, the pods are still running on the node.

**What you expected to happen**:
Pods need to be deleted and restart on another node.

**How to reproduce it (as minimally and precisely as possible)**:
1. run 1 pod.
2. Stop the container of the node that the pod is running on. (do not delete the container).
3. check the status of the node: not ready
4. check the status of the pod: 
kubectl get pod -o=custom-columns=NAME:.metadata.name,STATUS:.status.phase,NODE:.spec.nodeName --all-namespaces
running on the same pod.

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): kind v0.7.0 go1.13.6 darwin/amd64
- Kubernetes version: (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- Docker version: (use `docker info`):2.2.0.4
- OS (e.g. from `/etc/os-release`): MacOS 10.14.6

![image](https://user-images.githubusercontent.com/4497095/77716298-10c23b00-6f9b-11ea-8cfa-42e887687ada.png)

**Comment by BenTheElder** [comment]
`docker stop` is not supported. please use `kind delete cluster`.

**Comment by BenTheElder** [comment]
this might be a feature at some point, but interacting with the nodes to directly stop / start / pause etc. is simply not supported right now. if we did support them it would probably be with our own command to do fixup, not with `docker stop` directly.
