### ISSUE TITLE
HAproxy Configuration?  Adding NGINX or other services?

### ISSUE THREAD

**Issue by ssurovich** [kubernetes-sigs/kind#1452]
First, the HAproxy that comes with KinD is a great addition and of course, easy to use and perfect for dev clusers.

I was looking at adding a rule to the HAproxy config that would forward 80 and 443 to the worker nodes (each on their own port, of course) - and while I think that is easy to do, the real issue is that I don't know of any config options to expose additional ports when the HAproxy container is created?

Any ideas?

**Comment by BenTheElder** [comment]
The HAProxy built into kind is an implementation detail of multiple control plane nodes and is not configurable.

If you want some custom routing to the workers you should run an LB seperate from this.

**Comment by ssurovich** [comment]
Hey @BenTheElder - Makes sense, I thought that may be the stance and makes sense - Thanks for the reply.
