### ISSUE TITLE
Programmatically updating a Kubernetes cluster's "CA Cert" and "Service Token" (as Unix root)...

### ISSUE THREAD

**Issue by nmvega** [kubernetes-sigs/kind#1453]
Hello KinD Friends:

This is just a FYI on [a question I asked the folks at `GitLab`](https://gitlab.com/gitlab-org/gitlab/-/issues/212990), which I pasted below in case someone here might know how to do it. =:)

**The Question**:

I have installed `GitLab CE`.

Is there a way to -- as UNIX `root` -- `programmatically` create and update the `Add Kubernetes Cluster` UI-Form located at `GitLab-UI` --> `Admin-Area` --> `Kubernetes`?

**Why**:

I'm integrating `GitLab CE` with the `KinD` (https://kind.sigs.k8s.io/) Kubernetes distribution, which is not running all the time, and when restarted, creates a new `CA Cert` and `Service Token` (in `~/root/.kube/config`).

So if I can write a wrapper script that can `programmatically` create the `Add Kubernetes Cluster` form; `--OR--` at least update an existing Kubernetes cluster's `CA Cert` and `Service Token` values, that would be grand.

Thank you very much in advance!

Noelle

**Comment by BenTheElder** [comment]
I don't think the active contributors have much experience with GitLab, this very much sounds like a gitlab question :sweat_smile: 

These things are sometimes rotated with other clusters though, ideally they should have some way to update it...

**Comment by nmvega** [comment]
@BenTheElder Definitely a GitLab question. I'll close this question. If I solve it at the mentioned link, people will be able to follow it. Thank you. :)

**Comment by nmvega** [comment]
@BenTheElder An alternative option that I didn't originally think of: I use the same `yaml` file each time I boot a `kind` cluster (so nothing practically changes). It is possible to over-write `~/.kube/config` after `kind` boot is complete? Essentially this would mean over-writing it with the same content each time so that the `CA Cert` and `Service Token` don't change across boots. Assuming that nothing in the resulting `docker containers` are tied to `~/.kube/config`, this may be an option?

**Comment by BenTheElder** [comment]
the CA cert and service token are related to the cluster bootstrap, a CA etc. are setup, the entries in kube config reflect those created for that cluster.

we should solve this with #148. O(soon)

**Comment by nmvega** [comment]
Thank would be grand @BenTheElder (ie. being able to pin the "`CA Cert` and `Service Tocken` across cluster boots). Sorry that I cannot contribute here, but I appreciate your work. I'll `watch` the other issue you pointed out. Thank you.
