### ISSUE TITLE
failed to get file: command "docker exec --privileged kind-control-plane cat /kind/version

### ISSUE THREAD

**Issue by steren** [kubernetes-sigs/kind#1458]
I am on Linux in ChomeOS 
I am trying to create a kind cluster:

```
$ kind create cluster -v 5
Creating cluster "kind" ...
DEBUG: docker/images.go:61] Image: kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62 present locally
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
 ✓ Preparing nodes 📦  
 ✗ Writing configuration 📜 
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 137

Output:

Stack Trace: 
sigs.k8s.io/kind/pkg/errors.WithStack
        /src/pkg/errors/errors.go:51
sigs.k8s.io/kind/pkg/exec.(*LocalCmd).Run
        /src/pkg/exec/local.go:116
sigs.k8s.io/kind/pkg/cluster/internal/providers/docker.(*nodeCmd).Run
        /src/pkg/cluster/internal/providers/docker/node.go:130
sigs.k8s.io/kind/pkg/exec.CombinedOutputLines
        /src/pkg/exec/helpers.go:67
sigs.k8s.io/kind/pkg/cluster/nodeutils.KubeVersion
        /src/pkg/cluster/nodeutils/util.go:58
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.getKubeadmConfig
        /src/pkg/cluster/internal/create/actions/config/config.go:172
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.(*Action).Execute.func1.1
        /src/pkg/cluster/internal/create/actions/config/config.go:84
sigs.k8s.io/kind/pkg/errors.UntilErrorConcurrent.func1
        /src/pkg/errors/concurrent.go:30
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

**Comment by BenTheElder** [comment]
Please check the existing issues in the tracker and the known issues page https://kind.sigs.k8s.io/docs/user/known-issues/

At this time no known kubernetes installations work on chromeOS

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/763

**Comment by giulio-giunta** [comment]
Hello, 
I have tried several times to create a cluster, but without success
![kind-create-cluster](https://user-images.githubusercontent.com/56529931/104505781-57d9f500-55dc-11eb-8f82-f00a46e05835.png)

I also tried to create a container out of the kindest/node:v1.20.0 image that I pulled from Docker Hub, but it trew an error, as shown in the picture below:
![docker-run-kindestNode](https://user-images.githubusercontent.com/56529931/104506069-c4ed8a80-55dc-11eb-8726-01b1ff6a7ac5.png)

Is there a workaround to deploy a Kubernetes cluster by using kind? Any help will be highly appreciated.
Thanks!

**Comment by germainlefebvre4** [comment]
Kind version: `kind v0.10.0 go1.15.7 linux/amd64`

## `docker run` command issue
The error is expected if you run your `kind` container without privileged rights.
In your example, you need to add `--privileged` flag to the `docker run` command.

```bash
$ docker run --privileged kindest/node:v1.20.0
```
```raw
INFO: ensuring we can execute mount/umount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: fix cgroup mounts for all subsystems
INFO: clearing and regenerating /etc/machine-id
Initializing machine ID from random generator.
INFO: setting iptables to detected mode: legacy
INFO: Detected IPv4 address: 172.17.0.2
```

## `kind create cluster` command issue
I faced the same issue on WSL2 (Windos 10 with WSL2 Ubuntu-18.04).
WSL2 is sensible to the `cgroups` mounting and somatimes it unmounted by itself (memory GC or whatever).

Your problem would be solved on fixing again the `cgroups` mount point with: 
```bash
$ sudo mkdir /sys/fs/cgroup/systemd
$ sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
```

Then your `kind` creating cluster would be fine:
```bash
$ kind create cluster --config=cluster-config.yml --name kind-test -v 1
```
```raw
Creating cluster "kind-test" ...
DEBUG: docker/images.go:58] Image: kindest/node:v1.20.0 present locally
 ✓ Ensuring node image (kindest/node:v1.20.0) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind-test"
You can now use your cluster with:

kubectl cluster-info --context kind-kind-test

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
```

And here is my `cluster-config.yml` configuration file:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
nodes:
  - role: control-plane
    image: kindest/node:v1.20.0
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
```

**Comment by germainlefebvre4** [comment]
> Hello,
> I have tried several times to create a cluster, but without success
> ![kind-create-cluster](https://user-images.githubusercontent.com/56529931/104505781-57d9f500-55dc-11eb-8f82-f00a46e05835.png)
> 
> I also tried to create a container out of the kindest/node:v1.20.0 image that I pulled from Docker Hub, but it trew an error, as shown in the picture below:
> ![docker-run-kindestNode](https://user-images.githubusercontent.com/56529931/104506069-c4ed8a80-55dc-11eb-8726-01b1ff6a7ac5.png)
> 
> Is there a workaround to deploy a Kubernetes cluster by using kind? Any help will be highly appreciated.
> Thanks!

Kind version: `kind v0.10.0 go1.15.7 linux/amd64`

## `docker run` command issue
The error is expected if you run your `kind` container without privileged rights.
In your example, you need to add `--privileged` flag to the `docker run` command.

```bash
$ docker run --privileged kindest/node:v1.20.0
```
```raw
INFO: ensuring we can execute mount/umount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: fix cgroup mounts for all subsystems
INFO: clearing and regenerating /etc/machine-id
Initializing machine ID from random generator.
INFO: setting iptables to detected mode: legacy
INFO: Detected IPv4 address: 172.17.0.2
```

## `kind create cluster` command issue
I faced the same issue on WSL2 (Windos 10 with WSL2 Ubuntu-18.04).
WSL2 is sensible to the `cgroups` mounting and somatimes it unmounted by itself (memory GC or whatever).

Your problem would be solved on fixing again the `cgroups` mount point with: 
```bash
$ sudo mkdir /sys/fs/cgroup/systemd
$ sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
```

Then your `kind` creating cluster would be fine:
```bash
$ kind create cluster --config=cluster-config.yml --name kind-test -v 1
```
```raw
Creating cluster "kind-test" ...
DEBUG: docker/images.go:58] Image: kindest/node:v1.20.0 present locally
 ✓ Ensuring node image (kindest/node:v1.20.0) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind-test"
You can now use your cluster with:

kubectl cluster-info --context kind-kind-test

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
```

And here is my `cluster-config.yml` configuration file:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
nodes:
  - role: control-plane
    image: kindest/node:v1.20.0
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
```

**Comment by BenTheElder** [comment]
> I also tried to create a container out of the kindest/node:v1.20.0 image that I pulled from Docker Hub, but it trew an error, as shown in the picture below:

This is not supported. please use the tool. There are a lot of runtime options that must be set correctly.
Also please file a new issue in the future, old issues are not as closely monitored and should be on the original issue topic. This issue is about chromeOS, on which kind will not work https://github.com/kubernetes-sigs/kind/issues/1458#issuecomment-607016695

thanks for the follow up @germainlefebvre4

**Comment by giulio-giunta** [comment]
Hi Benjamin,
I ran the command indicated by @germainlefebvre4
<https://github.com/germainlefebvre4> , but it didn't work. I will open a
new issue as you suggested.
Thanks.

Giulio
