### ISSUE TITLE
Is there an easy way to change the cluster.local default domain deployed with kind?

### ISSUE THREAD

**Issue by wpfnihao** [kubernetes-sigs/kind#1466]
I've checked the [configuration page](https://kind.sigs.k8s.io/docs/user/configuration/), it looks that I can change both Pod Subnet and Service Subnet, but would it be also possible to change the default domain? 

Thanks in advance!

**Comment by stealthybox** [comment]
Use `kubeadmConfigPatches` to set:
```
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
networking:
  dnsDomain: "cluster.local"
```
`kind` config example:
https://github.com/kubernetes-sigs/kind/blob/ba26f74/site/content/docs/user/kind-example-config.yaml#L6-L11

**Comment by wpfnihao** [comment]
> Use `kubeadmConfigPatches` to set:
> 
> ```
> ---
> apiVersion: kubeadm.k8s.io/v1beta1
> kind: ClusterConfiguration
> networking:
>   dnsDomain: "cluster.local"
> ```
> 
> `kind` config example:
> https://github.com/kubernetes-sigs/kind/blob/ba26f74/site/content/docs/user/kind-example-config.yaml#L6-L11

Great! Many thanks!

**Comment by an-tex** [comment]
`apiVersion: kubeadm.k8s.io/v1beta1` needs to be set to `apiVersion: kubeadm.k8s.io/v1beta1` now

**Comment by BenTheElder** [comment]
if you're using the latest kind you can drop the `apiVersion` field from the patch, and it will match on `kind` only if unset (unlike kustomize), this is safe for most things as v1beta1 and v1beta2 of the kubeadm API are nearly identical

v1beta2 is used for >= kubernetes 1.15.0 (when it was introduced)

**Comment by an-tex** [comment]
thanks for the tip!
