### ISSUE TITLE
Nginx Ingress Assigning Inaccessible IPs

### ISSUE THREAD

**Issue by nickwebha** [kubernetes-sigs/kind#1469]
**What Happened**

I wrote myself a little build script just to make my life easier of bits from here and there:
```
reg_name='kind-registry'
reg_port='5000'

running="$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)"

if [ "${running}" != 'true' ]; then
	docker run -d --restart=always -p "${reg_port}:5000" --name "${reg_name}" "registry:2"
fi

reg_ip="$(docker inspect -f '{{.NetworkSettings.IPAddress}}' "${reg_name}")"

cat <<EOF | kind create cluster --name "[clustername]" --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches: 
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
    endpoint = ["http://${reg_ip}:${reg_port}"]
EOF

kubectl create secret generic regcred --from-file=.dockerconfigjson="${HOME}/.docker/config.json" --type=kubernetes.io/dockerconfigjson

kubectl apply -f "https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/mandatory.yaml"
kubectl apply -f "https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/provider/baremetal/service-nodeport.yaml"
kubectl patch deployments -n ingress-nginx nginx-ingress-controller -p '{"spec":{"template":{"spec":{"containers":[{"name":"nginx-ingress-controller","ports":[{"containerPort":80,"hostPort":80},{"containerPort":443,"hostPort":443}]}],"nodeSelector":{"ingress-ready":"true"},"tolerations":[{"key":"node-role.kubernetes.io/master","operator":"Equal","effect":"NoSchedule"}]}}}}'

kubectl create namespace "development"
```

If I run this everything works great except for my three Ingress controllers (meant for outside access on ports 80 and 443 from the outside world). They just do not pull an IP no matter how long I wait. If I remove
`kubectl patch deployments -n ingress-nginx nginx-ingress-controller -p '{"spec":{"template":{"spec":{"containers":[{"name":"nginx-ingress-controller","ports":[{"containerPort":80,"hostPort":80},{"containerPort":443,"hostPort":443}]}],"nodeSelector":{"ingress-ready":"true"},"tolerations":[{"key":"node-role.kubernetes.io/master","operator":"Equal","effect":"NoSchedule"}]}}}}'`
and run the script again (after deleting the cluster) then they do pull IPs after a bit but I can not access or ping them from the host. None of the IPs pulled (when it does pull IPs) are part of any network I am on (`ifconfig`/`ip addr`).

**Environment**

Ubuntu MATE 19.04
kind v0.7.0 go1.14.2 linux/amd64
Docker 19.03.6

**Next Steps**

I do not know enough to be able to know where to go from here.

**Comment by amwat** [comment]
I'm not exactly sure what you mean when you say it's failing to "pull an ip" .

I'm guessing you are probably referring to the fact that the controller pod is stuck in `pending` state and shows it's pod IP as `<none>`.
That IP comes from https://kind.sigs.k8s.io/docs/user/configuration/#pod-subnet  and is only accessible from inside the cluster.
you can refer https://kind.sigs.k8s.io/docs/user/ingress/#using-ingress to see a basic example of using ingress from outside the cluster.

Anyway, the controller is most likely not becoming ready since you seem to be missing the `extraPortMappings` and `kubeadmConfigPatches` as described in 
https://kind.sigs.k8s.io/docs/user/ingress/#create-cluster
Can you try adding those to your create config?

**Comment by nickwebha** [comment]
First things first, thank you for the-- very fast at that-- response. Many communities are not as welcoming.

Second, I am sorry if I was unclear. I was referring to `ADDRESS` under `ingress.extensions/[XXX]`.

Alright then.

First I just wanted to mention I had to add
```
containerdConfigPatches: 
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
    endpoint = ["http://${reg_ip}:${reg_port}"]
```
right under `apiVersion: kind.x-k8s.io/v1alpha4` or it could not find the Docker images (note my script above). Pointing all domain names to `127.0.0.1` in `/etc/hosts` did the trick. Awesome.

One final issue to solve (I hope). My remote client (outside Kubernetes/kind) relies on WebSocket. When I open a browser and point it to the domain name I get _The WebSocket handshake Connection field is missing_ when it works in Minikube (which I am trying to get away from, thus this issue). HTTP[S] on the other ingres controllers work great.

Adding `nginx.org/websocket-services: "[service]"` does not seem to help as suggested in [https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/websocket](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/websocket) and neither does `nginx.ingress.kubernetes.io/websocket-services: "[service]"` nor `ingress.kubernetes.io/websocket-services: "[service]"`.

How can I allow WebSocket to come through?

**Comment by aojea** [comment]
> First things first, thank you for the-- very fast at that-- response. Many communities are not as welcoming.

You are very welcome 😄 

> You can close this issue.

Thanks
/close
