### ISSUE TITLE
Ability to disable emoji

### ISSUE THREAD

**Issue by karolinepauls** [kubernetes-sigs/kind#1470]
**What would you like to be added**:
An option/env var to disable emojis in output (honestly, they should be disabled by default, since there's no reason for them to be there in the first place but I know this won't pass).

**Why is this needed**:
Not all terminals and default fonts used by them handle emojis well. Non-Apple users generally don't care about such trivialities and just want to get the job done. Emojis badly interact with re-drawing procedures used and leave users with no feedback.

![image](https://user-images.githubusercontent.com/43616133/79073925-411b1080-7ce1-11ea-8166-662988362b96.png)

**Comment by BenTheElder** [comment]
TERM=dumb

https://github.com/kubernetes-sigs/kind/blob/c68a1cf537d6801e2750b3ce0f3e478ad44619a5/pkg/internal/env/term.go#L42

**Comment by BenTheElder** [comment]
We've overwhelmingly received positive feedback about this, and they work correctly in gnome terminal, the new open source windows terminal, macOS's terminal etc. Modern terminals have no problem with UTF8. You can already disable the terminal escape sequences though and they're disabled for non-TTY.
