### ISSUE TITLE
Release v0.8.0

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#1475]
We've been slow getting this one out, but some gnarly changes are landing.

It's past time to prioritize these and get a release out.

- An earnest attempt at finishing up the PRs and good-enough #148 needs to happen.
- #1471 must be fixed.

Integrated test workflow can be punted.

/assign
I've mostly finished catching up on some administrative stuff, I'm going to start temporarily de-prioritizing things like PR review to actually ship these.

**Comment by BenTheElder** [comment]
needed to fix up https://github.com/kubernetes-sigs/kind/issues/1392, this got a bit more pressing. nearly done with that.

**Comment by BenTheElder** [comment]
eep https://github.com/kubernetes-sigs/kind/issues/1498

**Comment by BenTheElder** [comment]
double eep, newer k8s is broken on iptables-nft which is becoming more common. going to see about fixing.

https://github.com/kubernetes-sigs/kind/issues/1461

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/1471 is sorted. though we need to follow up on why the containerd upgrade (abandoned) seemingly caused more CI timeouts. holding off on that for now because the iptables-nft issue is alarming and the fix I hope to apply also solves host reboot and most DNS issues.

**Comment by BenTheElder** [comment]
Pr open for https://github.com/kubernetes-sigs/kind/issues/148

**Comment by BenTheElder** [comment]
getting closer on #148, PR more or less does what we want but has some rough spots particularly around ipv6. did some more testing.

**Comment by BenTheElder** [comment]
#148 is nominally resolved, but we need a bit of follow-up with network management and IPv6 clusters in particular.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/1520 / ipv6 being worked on

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/issues/90568 today's main distraction. back at it. had a good improptu soundboard / brainstorming session w/ @amwat PRs on the way..

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1526 solves some of the ipv6 woes

**Comment by BenTheElder** [comment]
#1526 is in, fixing our CI, then #273 + https://github.com/kubernetes-sigs/kind/pull/1527/ / handling ipv6 subnet collisions to avoid failing to create clusters when the user happens to be using our preferred subnet

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/17443 fixes CI the rest of the way

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1534 re-discovered when vetting for release. pushing this fix.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1536 to push the fix

**Comment by BenTheElder** [comment]
busy day ... after https://github.com/kubernetes-sigs/kind/pull/1538 and some validation I'll push new images for all the k8s versions and write notes.

**Comment by BenTheElder** [comment]
Drafting release notes

**Comment by BenTheElder** [comment]
Last image is pushing. This time is slow because we have so many kubernetes versions.
Will be working on a support policy for these in v0.9.0 timeframe.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.0#contributors

**Comment by jglick** [comment]
Working in CI tests for the Jenkins plugin for Kubernetes: https://github.com/jenkinsci/kubernetes-plugin/pull/774. Thanks!
