### ISSUE TITLE
Improve FeatureGates documentation

### ISSUE THREAD

**Issue by bygui86** [kubernetes-sigs/kind#1481]
**What would you like to be documented**:
[Here](https://kind.sigs.k8s.io/docs/user/quick-start#enable-feature-gates-in-your-cluster) is described how to configure KinD with specific feature gates.
The description is too short and does not provide suitable examples.
For example, is the following example correct?
```yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        metadata:
          name: config
        apiServer:
          extraArgs:
            "feature-gates": "AuthorizationMode=RBAC"
  - role: worker
    image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
  - role: worker
    image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
```
I don't thinks so because I tried several times but I received always this error:
```shell
$ kind create cluster --config=~/.kind/kind-config.yaml --wait=60s

Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.0) 🖼
 ✓ Preparing nodes 📦 📦 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
```

**Why is this needed**:
Because there is a complete lack of examples and it's difficult to guess how to write configurations in KinD configuration yaml file in the proper format.

**Comment by bygui86** [comment]
I opened also a specific question about my configuration issues:
https://github.com/kubernetes-sigs/kind/issues/1482

**Comment by BenTheElder** [comment]
The patches are *kubeadm* config which has its own format.

There's been no changes to kind's docs for feature gates yet because instead of trying to explain this mess we've made it easier. In the next release there will be one too level *kind* confog field to enable feature gates across all kubernetes versions.

You can try it now by installing from head.
`featureGates` field is a map of gate name to value.

The gates themselves come from kubernetes.

**Comment by BenTheElder** [comment]
Here's an example for the time being https://github.com/kubernetes-sigs/kind/issues/1480#issuecomment-614515104

**Comment by bygui86** [comment]
thank you @BenTheElder!

`There's been no changes to kind's docs for feature gates yet because instead of trying to explain this mess we've made it easier.`
That's actually a very good idea. Those configs are really a mess to understand and write.

`In the next release there will be one too level kind confog field to enable feature gates across all kubernetes versions.`
When do you plan to release the next version?

`Here's an example for the time being #1480 (comment)`
Great, I will try.

**Comment by BenTheElder** [comment]
There's another issue tracking the release. We need to fix a few urgentish
issues.

Yes, the patches are meant to be a backdoor for power users to fiddle with
*any* underlying option, but for typically used options we're aiming to
provide smoother abstractions. We have a better idea from surveying patches
in use which things to focus on.

Featuregates were the first, but not the last.

We'll expand the docs when this is landed.
