### ISSUE TITLE
Feature gates YAML configurations

### ISSUE THREAD

**Issue by bygui86** [kubernetes-sigs/kind#1482]
I tried to enable specific feature gates in the KinD config yaml file as follow:
```yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        metadata:
          name: config
        apiServer:
          extraArgs:
            "feature-gates": "AuthorizationMode=RBAC"
  - role: worker
    image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
  - role: worker
    image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
```

I tried several times but I received always this error:
```shell
$ kind create cluster --config=~/.kind/kind-config.yaml --wait=60s

Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.0) 🖼
 ✓ Preparing nodes 📦 📦 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
```

I tried also:
- `feature-gates: "AuthorizationMode=RBAC"`
- `feature-gates: AuthorizationMode=RBAC`
- `AuthorizationMode: RBAC`

I received every time the same error.

What is the error in the yaml?
I need to enable RBAC and CNI, how can I configure them?

**Comment by BenTheElder** [comment]
RBAC and CNI are enabled on all supported kubernetes versions by default with no configuration.

You can see more failure details currently by passing --verbosity 1 and --retain, then `kind export logs` to dump lots of cluster lots for debugging of the more verbose output isn't enough.

You don't need to touch feature gates for RBAC though.

The problem is that this is an invalid feature gate.

**Comment by BenTheElder** [comment]
`--authorization-mode=RBAC` is an API server flag, not a feature gate.

It's on by default. Virtually no modern clusters use ABAC.

**Comment by bygui86** [comment]
Thank you @BenTheElder !

`You can see more failure details currently by passing --verbosity 1 and --retain, then kind export logs to dump lots of cluster lots for debugging of the more verbose output isn't enough.`
Great suggestion!

`--authorization-mode=RBAC is an API server flag, not a feature gate.`
I'm really sorry, I made confusion between options/flags and feature gates!

I think I can close this question.
