### ISSUE TITLE
Consider installing ipvsadm in the node image

### ISSUE THREAD

**Issue by njuettner** [kubernetes-sigs/kind#1497]
**What would you like to be added**:

When choosing ipvs for kube-proxy via `kubeadmConfigPatches` in kind config.yaml, it would be helpful to install ipvsadm as a package for the base image:

https://github.com/kubernetes-sigs/kind/blob/f34ddc3bee003b50bfab9d39917c361b0ae3497f/images/base/Dockerfile#L68

**Why is this needed**:

This is helpful for inspecting the virtual server table in the Linux kernel similar to iptables.

**Comment by BenTheElder** [comment]
We currently strictly install necessary runtime packages to keep the image size down, it's still bigger than we'd like.

Preferred debugging tools can be installed by creating a custom base or node image using a trivial dockerfile like:
```dockerfile
FROM <image>
RUN clean-install <tool>
```
kind should work fine with the custom node or base image as long as you're just adding a few tools.

**Comment by njuettner** [comment]
Thanks for the info, this also works for me 👍, didn't know about this option TBH. Closing the issue.
