### ISSUE TITLE
Kind on btrfs

### ISSUE THREAD

**Issue by jonay2000** [kubernetes-sigs/kind#1498]
**What happened**:

```
kind create cluster
```

errors with the following error:

```
docker run error: command "docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --volume /dev/mapper /dev/mapper --publish=127.0.0.1:39139:6443/TCP kindest/node:v1.17.2@sha256:59df31fc61d1da5f46e8a61ef612fa53d3f9140f82419d1ef1a6b9656c6b737c" failed with error: exit status 125
ERROR: failed to create cluster: docker run error: command "docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --volume /dev/mapper /dev/mapper --publish=127.0.0.1:39139:6443/TCP kindest/node:v1.17.2@sha256:59df31fc61d1da5f46e8a61ef612fa53d3f9140f82419d1ef1a6b9656c6b737c" failed with error: exit status 125
exit status 1
```

And doesn't create a cluster.

**What you expected to happen**:

It should just set up the cluster

**How to reproduce it (as minimally and precisely as possible)**:

```
git clone https://github.com/kubernetes-sigs/kind kind
cd kind
go run main.go create cluster
```

**Anything else we need to know?**:

this issue is related to #1416 where I also commented. 
There seems to be a bug introduced in #1464 . In this commit you added

```go
	if mountDevMapper() {
		args = append(args, "--volume", "/dev/mapper", "/dev/mapper")
	}
```
But I think this has to be

```go
	if mountDevMapper() {
		args = append(args, "--volume", "/dev/mapper:/dev/mapper")
	}
``` 

Which results in the following command:

```docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --volume /dev/mapper:/dev/mapper --publish=127.0.0.1:46023:6443/TCP kindest/node:v1.17.2@sha256:59df31fc61d1da5f46e8a61ef612fa53d3f9140f82419d1ef1a6b9656c6b737c```

instead of 

```docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --volume /dev/mapper /dev/mapper --publish=127.0.0.1:46023:6443/TCP kindest/node:v1.17.2@sha256:59df31fc61d1da5f46e8a61ef612fa53d3f9140f82419d1ef1a6b9656c6b737c```

being run

(sorry, one char difference. It's a colon after /dev/mapper)

It might also be useful to know that I run btrfs as a root filesystem (btrfs-progs v5.6)

**Environment:**

- kind version: (use `kind version`): kind v0.8.0-alpha go1.14.2 linux/amd64
- Docker version: (use `docker info`): 19.03.8-ce
- OS (e.g. from `/etc/os-release`): Arch linux (Linux 5.6.5-arch3-1)

**Comment by aojea** [comment]
:facepalm:

**Comment by aojea** [comment]
@jonay2000 can you confirm that running this command manually works ?

```
docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --volume /dev/mapper:/dev/mapper --publish=127.0.0.1:46023:6443/TCP kindest/node:v1.17.2@sha256:59df31fc61d1da5f46e8a61ef612fa53d3f9140f82419d1ef1a6b9656c6b737c
```

I can't test it and prefer to not introduce an error again,

**Comment by jonay2000** [comment]
Can confirm. Works flawlessly

**Comment by jonay2000** [comment]
Thanks for the quick response :)
