### ISSUE TITLE
PortMapping in multi master mode

### ISSUE THREAD

**Issue by guidtz** [kubernetes-sigs/kind#1501]
Hello,
   with multi master node is cool to have haproxy as laod balancer. So how can I map http and https port of my vm to haproxy contener ? So when users post request on Ip all gone to haproxy and after it load balance to worker nodes http port.

I'll done the same manually with haproxy and kubeadm so how could I done that with kind ?

Regards

**Comment by BenTheElder** [comment]
you can run your own LB, we don't natively support something like this and I don't think we plan to currently.

we do run an HAProxy container, but purely as an implementation detail of the API server in this mode.

**Comment by BenTheElder** [comment]
> So how can I map http and https port of my vm to haproxy contener ?

not quite sure what you're doing here but https://kind.sigs.k8s.io/docs/user/configuration/#api-server
