### ISSUE TITLE
Eclipse Che atop KinD 

### ISSUE THREAD

**Issue by nmvega** [kubernetes-sigs/kind#1509]
Hello Again Friends:

I run `KinD` on a single server (a robust `Linux PC`), but for small remote instructional classes.

I'm interested in installing `Eclipse Che 7` for a multi-user web-based `IDE` for them, but documents say it requires `Kubernetes`. I'm trying to avoid heavy `Minikube`. 

Can I use `KinD` for this use-case, and over `https` (secure IDE) sessions.

I'm not yet fully up to speed on Kubernetes in general (because of other commitments), so please bare with me. This would be a great solution it worked because `KinD`is simple and lightweight.

Thank you! :relaxed:

**Comment by BenTheElder** [comment]
see the security goose note: https://kind.sigs.k8s.io/docs/user/configuration/#api-server

I wouldn't recommend putting kind or minikube on the internet.
I highly recommend a more managed solution with an upgrade path, or at least carefully maintaining a kubeadm install yourself (I've done this sort of thing).

A kubernetes cluster without an update strategy is hacker bait :-)

**Comment by nmvega** [comment]
@BenTheElder Thank you.

It's for informal, throw-away use. In fact, the lessons `docker` container (separate from `KinD` containers) are meant to be disposable, and even OAuth is used for authentication, so no local passwords either.

But I agree with your response and sentiment.

I'm trying to keep things simple yet reasonably secure (and hoped `KinD` would assist in simplicity), but, alternatively, do you think something `k3s` (not `k8s`) would fit the bill? Looks promising.

Meanwhile, I'll look around for an all-in-one-box command / tutorial with `kubeadm`. :relaxed:

**Comment by BenTheElder** [comment]
If I were going to endorse a downstream kubernetes solution it would probably have to be GKE ;-)

**Comment by nmvega** [comment]
Okay :wink:
