### ISSUE TITLE
Add user stories

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/kind#152]
Before we dive too deep into execution lets outline some of the concrete user stories. 

/cc @kubernetes/sig-cluster-lifecycle

**Comment by rimusz** [comment]
I have implemented for helm charts testing if that is what you are looking for:
https://github.com/rimusz/charts/tree/master/test
https://github.com/jfrog/charts/tree/master/test
https://github.com/keel-hq/keel/tree/master/.test

all these are part go the testing pipeline run in circles/travisci

Also an example in https://github.com/helm/chart-testing/tree/master/examples/kind

**Comment by timothysc** [comment]
Right now we're planning to outline the following user stories. 

- kubeadm user stories 
    - local developer 
    - advanced developer (HA) 
    - CI signal 
- cluster-api stories 
    - bootstrap integration 
- K8s integrator 
    - CI automation tooling 
...

**Comment by BenTheElder** [comment]
@munnerz @Katharine if you get some time, might helping provide a few details for your existing usage?

**Comment by BenTheElder** [comment]
Maybe docs/design/* -> docs/design/user-stories/* ? Open to suggestions, but probably somewhere within docs/*

**Comment by BenTheElder** [comment]
We opted to cover this with https://kind.sigs.k8s.io/docs/contributing/project-scope/ I think.
