### ISSUE TITLE
kind --help command wont show --config option

### ISSUE THREAD

**Issue by gitdotvaibhav** [kubernetes-sigs/kind#1532]
**What happened**:
when I ran kind --help command config option was not shown

**What you expected to happen**:
--config option with details

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**
mac
- kind version: (use `kind version`):

kind v0.7.0 go1.13.6 darwin/amd64

- Kubernetes version: (use `kubectl version`):
v1.18.2
- Docker version: (use `docker info`):
v1.18.2
- OS (e.g. from `/etc/os-release`):

**Comment by sayboras** [comment]
I don't think --config is valid flag for root command kind. You can try with other command such as kind create cluster --help

```shell scripts
$ kind create cluster --help                      
Creates a local Kubernetes cluster using Docker container 'nodes'

Usage:
  kind create cluster [flags]

Flags:
      --config string       path to a kind config file
  -h, --help                help for cluster
      --image string        node docker image to use for booting the cluster
      --kubeconfig string   sets kubeconfig path instead of $KUBECONFIG or $HOME/.kube/config
      --name string         cluster context name (default "kind")
      --retain              retain nodes for debugging when cluster creation fails
      --wait duration       wait for control plane node to be ready (default 0s)

Global Flags:
      --loglevel string   DEPRECATED: see -v instead
  -q, --quiet             silence all stderr output
  -v, --verbosity int32   info log verbosity
```

**Comment by gitdotvaibhav** [comment]
Sure my bad
