### ISSUE TITLE
Kind create cluster fails on Windows Server 2019 physical machine

### ISSUE THREAD

**Issue by saarram** [kubernetes-sigs/kind#1535]
**What happened**:
Tried creating kind cluster on Windows Server 2019 with docker with linux support enabled. But the cluster creation fails with couple of errors.
**Error 1 :** 
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.17.0) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
 • Preparing nodes 📦   ...
 ✗ Preparing nodes 📦
proxy setup error: failed to get subnets: command "docker network inspect -f '{{range (index (index . "IPAM") "Config")}}{{index . "Subnet"}} {{end}}' bridge" failed with error: exit status 1
ERROR: failed to create cluster: proxy setup error: failed to get subnets: command "docker network inspect -f '{{range (index (index . "IPAM") "Config")}}{{index . "Subnet"}} {{end}}' bridge" failed with error: exit status 1

_**I see that it is expecting "bridge" network to be present which is not present by default on windows. I could get around this issue by creating network named bridge using 'docker network create -d nat bridge'. Then this error disappeared but I encountered different error after this.**_
**Error - 2**
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.17.0) 🖼  ...
DEBUG: docker/images.go:61] Image: kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62 present locally
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
 • Preparing nodes 📦   ...
 ✗ Preparing nodes 📦
docker run error: command "docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind -e https_proxy=http://100.127.20.21:8080/ -e NO_PROXY=172.20.240.0/20,10.96.0.0/12,10.244.0.0/16 -e no_proxy=172.20.240.0/20,10.96.0.0/12,10.244.0.0/16 -e HTTP_PROXY=http://100.127.20.21:8080/ -e http_proxy=http://100.127.20.21:8080/ -e HTTPS_PROXY=http://100.127.20.21:8080/ --publish=127.0.0.1:0:6443/TCP kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62" failed with error: exit status 125
ERROR: failed to create cluster: docker run error: command "docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind -e https_proxy=http://100.127.20.21:8080/ -e NO_PROXY=172.20.240.0/20,10.96.0.0/12,10.244.0.0/16 -e no_proxy=172.20.240.0/20,10.96.0.0/12,10.244.0.0/16 -e HTTP_PROXY=http://100.127.20.21:8080/ -e http_proxy=http://100.127.20.21:8080/ -e HTTPS_PROXY=http://100.127.20.21:8080/ --publish=127.0.0.1:0:6443/TCP kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62" failed with error: exit status 125

Output:
docker: Error response from daemon: Windows does not support privileged mode.
See 'docker run --help'.

Stack Trace:
sigs.k8s.io/kind/pkg/errors.WithStack
        /src/pkg/errors/errors.go:51
sigs.k8s.io/kind/pkg/exec.(*LocalCmd).Run
        /src/pkg/exec/local.go:116
sigs.k8s.io/kind/pkg/cluster/internal/providers/docker.createContainer
        /src/pkg/cluster/internal/providers/docker/provision.go:99
sigs.k8s.io/kind/pkg/cluster/internal/providers/docker.planCreation.func2
        /src/pkg/cluster/internal/providers/docker/provision.go:85
sigs.k8s.io/kind/pkg/errors.UntilErrorConcurrent.func1
        /src/pkg/errors/concurrent.go:30
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
**What you expected to happen**:
I expect the cluster to be created successfully.
**How to reproduce it (as minimally and precisely as possible)**:
Download kind stable binary (windows-amd variant). Enable linux container support in Windows Server 2019 machine and execute 'kind create cluster'
**Anything else we need to know?**:
Similar issues I found online couldn't help. As I am already using docker on windows with Linux containers mode. 
**Environment:**

- kind version: (use `kind version`): 
kind v0.7.0 go1.13.6 windows/amd64
- Kubernetes version: (use `kubectl version`): 
- Docker version: (use `docker info`): 
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.10.0-ee-preview-3
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 48
Total Memory: 127.9GiB
Name: CY02NAP0000A82A
ID: J5XG:3QOQ:KBCJ:IF2U:PUTF:SRMI:RMH3:RFFW:OXYA:RQ4E:KMT3:OBGL
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://100.127.20.21:8080/
HTTPS Proxy: http://100.127.20.21:8080/
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
- OS (e.g. from `/etc/os-release`):  Windows Server 2019 Datacenter (10.0.17763)

Is kind supported on Windows Server 2019 ? Any solution to get this working would be greatly appreciated.

Thanks.

**Comment by BenTheElder** [comment]
https://kind.sigs.k8s.io/docs/user/known-issues/#windows-containers

> docker: Error response from daemon: Windows does not support privileged mode.

this error suggests that docker is in windows container mode, it needs to be in linux container mode

**Comment by saarram** [comment]
It is already in docker linux containers mode which is why the confusion. See the docker info output pasted above. If it helps - I was able to run sample linux containers like busybox.

**Comment by BenTheElder** [comment]
I see, well kind does require privileged mode, I do not encounter this error with docker desktop on my own windows machine, and I'm not an expert in ways to run docker on windows.

currently I use docker desktop with hyper-v https://docs.docker.com/docker-for-windows/

you can see our WSL2 based guide here: https://kind.sigs.k8s.io/docs/user/using-wsl2/

**Comment by BenTheElder** [comment]
cc @PatrickLang

**Comment by BenTheElder** [comment]
_Windows_ definitely works and I personally support that, I have a windows machine to test on.

But figuring out how to get windows server 2019 with privileged Docker containers correctly seems like a support question for Microsoft or Docker, kind will not be able to not require this feature anytime soon and pretty much every environment we've encountered supports this...

Sorry but: I think you're going to need to take this up with those communities, there's nothing we can do here and none of the regular contributors work with Windows Server AIUI.

Patrick worked for Microsoft, but it seems he's switched companies now.

I will ask the members in our slack to take a look, but I'm going to move this out of being actively tracked now since the issue seems to be with your docker install rather than something kind is likely to change.

**Comment by BenTheElder** [comment]
https://kubernetes.slack.com/archives/CEKK1KTN2/p1588276876398800

**Comment by saarram** [comment]
Makes sense. Thanks. Will post here if I find any solution.

**Comment by saarram** [comment]
Turns out that - this is the feature gap with LCOW with Windows Server i.e. privileged Linux containers wouldn't work on Windows server and there is no plan yet to support it.
What happens if we just run container in non-privileged mode ? What would break in terms of features ?

**Comment by BenTheElder** [comment]
It won't function enough to run
