### ISSUE TITLE
local registry doesn't work anymore with kind v0.8.0

### ISSUE THREAD

**Issue by nicks** [kubernetes-sigs/kind#1541]
I'm having trouble getting Kind with a local registry to work on Kind v0.8.0. I'm using the instructions here:
https://kind.sigs.k8s.io/docs/user/local-registry/

I've tried running the registry with `--net=kind` (per the v0.8.0 release notes) and that didn't appear to help. 

Are these instructions expected to still work?

**Comment by nicks** [comment]
If I use the default network, I get this error when creating the pod:

```
Failed to pull image "localhost:5000/tilt-site:tilt-dda10ecac7392bfd": rpc error: code = Unknown desc = failed to pull and unpack image "localhost:5000/tilt-site:tilt-dda10ecac7392bfd": failed to resolve reference "localhost:5000/tilt-site:tilt-dda10ecac7392bfd": failed to do request: Head http://172.17.0.2:5000/v2/tilt-site/manifests/tilt-dda10ecac7392bfd: dial tcp 172.17.0.2:5000: i/o timeout
```

If I use --net=kind, I get this error when creating the pod:

```
Failed to pull image "localhost:5000/tilt-site:tilt-dda10ecac7392bfd": rpc error: code = Unknown desc = failed to pull and unpack image "localhost:5000/tilt-site:tilt-dda10ecac7392bfd": failed to resolve reference "localhost:5000/tilt-site:tilt-dda10ecac7392bfd": failed to do request: Head http://:5000/v2/tilt-site/manifests/tilt-dda10ecac7392bfd: dial tcp :5000: connect: connection refused
```

**Comment by nicks** [comment]
OK, here's the solution I ended up with:

```
#!/bin/sh
set -o errexit

# desired cluster name; default is "kind"
KIND_CLUSTER_NAME="${KIND_CLUSTER_NAME:-kind}"

# create registry container unless it already exists
reg_name='kind-registry'
reg_port='5000'
running="$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)"
if [ "${running}" != 'true' ]; then
  docker run \
    -d --restart=always -p "${reg_port}:5000" --name "${reg_name}" --net=kind \
    registry:2
fi
reg_ip="$(docker inspect -f '{{.NetworkSettings.Networks.kind.IPAddress}}' "${reg_name}")"
echo "Registry IP: ${reg_ip}"

# create a cluster with the local registry enabled in containerd
cat <<EOF | kind create cluster --name "${KIND_CLUSTER_NAME}" --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches: 
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
    endpoint = ["http://${reg_ip}:${reg_port}"]
EOF
```

Note that I had to change both the `docker run` call and the `docker inspect` call.

I think it needs a little bit of work to make sure it runs on both Kind 0.7.0 and Kind 0.8.0. How important it is it that the example on the website runs with both Kind versions?

**Comment by BenTheElder** [comment]
sorry about that, I'd intended to update it to just work with 0.8, 0.8 is certainly a breaking change wrt running things alongside the cluster, but I felt it was worth it for:
- restart just works (hopefully!)
- embedded DNS solves most of your host DNS resolution woes
- kubernetes 1.18+ should work on hosts with iptables_nft which is increasingly more common

**Comment by BenTheElder** [comment]
On v0.8 we should be able to do `--net=kind` + use the registry container's name instead of ip, falling back to IP on v0.7, we can detect the kind version with a regex I guess.

**Comment by nicks** [comment]
here's the script I'm playing with now:
https://github.com/windmilleng/kind-local/blob/d56f83df750cf2f7441904c34f4328b037e9d98f/kind-with-registry.sh

which has some guards for upgrading from 0.7 -> 0.8, happy to contribute it upstream

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1542

Your script looks great, I think I'd like people to upgrade to kind v0.8 if they're finding the upstream guide, but it makes sense that tilt would want to support older versions for some time.

at least during "alpha" I've been just rolling forward, we don't for example tend to maintain release branches yet.

I should at least add the tilt annotations though!

**Comment by BenTheElder** [comment]
Technically it's also possible to use a different network with `KIND_EXPERIMENTAL_DOCKER_NETWORK` but i also don't want to encourage that in this guide at least.

**Comment by shuhaowu** [comment]
I'm currently running a local registry inside the KinD cluster and it also appears to be broken in 0.8. I'm not sure why yet. I've documented it more in depth here: https://github.com/kubernetes-sigs/kind/issues/1543#issuecomment-627585452

In hind sight that issue may be the wrong place to document this problem.
