### ISSUE TITLE
Can't create ipv4 clusters if ipv6 is disabled at kernel level

### ISSUE THREAD

**Issue by marcosnils** [kubernetes-sigs/kind#1544]
**What happened**:
Due to https://github.com/kubernetes-sigs/kind/pull/1526, `docker network create` will constantly fail if `ipv6.disable=1` is set in boot time at kernel level.

**What you expected to happen**:

Kind cluster to be created

**How to reproduce it (as minimally and precisely as possible)**:

Set `ipv6.disable=1` in grub, and try to create a cluster

**Anything else we need to know?**:

Nope, this issue has been identified already

**Environment:**
All

**Comment by BenTheElder** [comment]
/assign
/priority critical-urgent

workaround for now is:
```
docker network rm kind
docker network create -d=bridge kind
```

we'll fix this and cut 0.8.1

**Comment by BenTheElder** [comment]
OK, set to repro and check exactly what behavior we can expect I think:
```console
$ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.4.0-28-generic root=UUID=<snip> ro quiet splash vt.handoff=7 ipv6.disable=1
```

**Comment by BenTheElder** [comment]
```console
$ kind create cluster
Creating cluster "kind" ...
ERROR: failed to create cluster: failed to ensure docker network: command "docker network create -d=bridge --ipv6 --subnet fc00:f853:ccd:e793::/64 kind" failed with error: exit status 1
Command Output: Error response from daemon: Cannot read IPv6 setup for bridge br-bc6b11ad1b57: open /proc/sys/net/ipv6/conf/br-bc6b11ad1b57/disable_ipv6: no such file or directory
```
I think we can detect this error and abort out of trying to do an IPv6 enabled network based on that.

@marcosnils is this what you see (presumably with a different bridge name)

**Comment by marcosnils** [comment]
> @marcosnils is this what you see (presumably with a different bridge name)

Exactly!

**Comment by BenTheElder** [comment]
in theory if you install (`go install .` or `make build && cp bin/kind /somewhere/kind`) this is fixed in HEAD (to confirm you'll want to delete the clusters and network first and see what happens creating a cluster)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.1 contains the fix
