### ISSUE TITLE
Command 'kind' not found,

### ISSUE THREAD

**Issue by may101** [kubernetes-sigs/kind#1553]
I followed installation steps from QuickStart Kind but still have an issue with kind not found. 
Here some information : 
1- go version go1.10.4 linux/amd64
2-kubectl version --client

> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

The issue : 

> $ kind create cluster
> 
> Command 'kind' not found, did you mean:
> 
>   command 'find' from deb findutils
>   command 'kino' from deb kino
>   command 'king' from deb king
>   command 'kfind' from deb kfind
>   command 'kid' from deb python-kid
> 
> Try: sudo apt install <deb name>

Any advice on how to solve this issue?

**Comment by artur-jablonski** [comment]
This is most likely because you don't have `kind` on your path.

If you followed the quick start then there's this step:
```
mv ./kind /some-dir-in-your-PATH/kind
```

Where did you move it to?

You can try  `./kind create cluster` from directory where you downloaded `kind`.

**Comment by may101** [comment]
Hi 

Thank you for your reply. Still, I am not sure about that 
when I installed kind by curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.0/kind-$(uname)-amd64
it installed in the same directory, please see the attache image 
![issue](https://user-images.githubusercontent.com/64691894/80865850-34318180-8ccf-11ea-82b4-c0f61f1ca37d.png)

**Comment by may101** [comment]
> You can try `./kind create cluster` from directory where you downloaded `kind`.

Yes I tried that it shows the following : 
![issue2](https://user-images.githubusercontent.com/64691894/80866100-44962c00-8cd0-11ea-8e49-d049c0b0346f.png)

**Comment by may101** [comment]
any advice on how can I solve the issue?

**Comment by artur-jablonski** [comment]
You have a typo in your command. It's `create` not `creat`

**Comment by may101** [comment]
Its works now, I can't believe it was a typo  
Thank you so much @artur-jablonski for your help

**Comment by may101** [comment]
Still, I couldn't make it to move "`kind`" to my path

`> mv ./kind /some-dir-in-your-PATH/kind
`
I am not sure how to do this step mv and use kind instead of `./kind ` , 
Based on previous images of my direct path,  can you give me an example of how to move ` ./kind `?

**Comment by BenTheElder** [comment]
replace /some-dir-in-your-PATH with the directory you'd like to install it to which must be in your PATH.

These aren't fully standard so we leave it up to you to choose

**Comment by artur-jablonski** [comment]
`sudo mv ./kind /usr/local/bin/kind`

**Comment by may101** [comment]
Thank you all for your help, 
Yes ! It works now, I been able now to use `kind` command instead of  `./kind`

**Comment by asok-mirror** [comment]
wish the document to be updated with the above command. 

https://kind.sigs.k8s.io/docs/user/quick-start/

**Comment by BenTheElder** [comment]
mv is in the above doc. There isn't technically a universal PATH location however.

**Comment by mrizwanashiq** [comment]
> `sudo mv ./kind /usr/local/bin/kind`

This WO

**Comment by adenisov-splunk** [comment]
> This will put kind in $(go env GOPATH)/bin

It's not always `./kind`. I would suggest `mv $(go env GOPATH)/bin/kind /usr/local/bin/kind `

**Comment by BenTheElder** [comment]
For the record, intend to merge a patch defaulting to `/usr/local/bin/kind` in the example on linux at least https://github.com/kubernetes-sigs/kind/pull/2859

**Comment by bryanSME** [comment]
`go install sigs.k8s.io/kind@v0.17.0` will install kind in a location like `/home/<user>/go/bin/kind`.  After installing it, add a symbolic link to it.

`cd /usr/local/bin`
`sudo ln -s /home/<user>/go/bin/kind`

**Comment by BenTheElder** [comment]
It's more common to add the go/bin dir to PATH when choosing to use go install to install things.

**Comment by krausis** [comment]
Here you solved it by copying the kind to /usr/local/bin/ with the command:
sudo cp ~/go/bin/kind /usr/local/bin/

**Comment by chaitanya-uniyal** [comment]
if  you are on linux or wsl and trying to install kind without go install then simply use these commands

curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
chmod +x ./kind
sudo mv ./kind /usr/local/bin/kind


hope this helps :))

**Comment by BenTheElder** [comment]
(these commands are also in the docs https://kind.sigs.k8s.io/docs/user/quick-start/#installation, I'd use something more recent than v0.17)
