### ISSUE TITLE
Kind-control plane hangs on shutdown

### ISSUE THREAD

**Issue by tdickman** [kubernetes-sigs/kind#1556]
**What happened**: When stopping `kind-control-plane`, docker fails to stop the container. If I run `docker top kind-control-plane`, I see a single docker process running. The last log statements I see are:

```
[  OK  ] Reached target Unmount All Filesystems.
[  OK  ] Stopped target Local File Systems (Pre).
[  OK  ] Stopped Create Static Device Nodes in /dev.
[  OK  ] Stopped Create System Users.
[  OK  ] Stopped Remount Root and Kernel File Systems.
[  OK  ] Reached target Shutdown.
[  OK  ] Reached target Final Step.
         Starting Halt...
```

When rebooting my computer this prevents my computer from fully shutting down, and I am forced to cut power manually.

**What you expected to happen**: Kind should gracefully exit - forcefully terminating processing after some timeout.

**How to reproduce it (as minimally and precisely as possible)**: Start kind and run `docker stop kind-control-plane`. Unclear if it's necessary to have a certain process running in the cluster?

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): `kind v0.8.0 go1.14.2 linux/amd64`
- Kubernetes version: (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
- Docker version: (use `docker info`): `19.03.8`
- OS (e.g. from `/etc/os-release`): `Ubuntu 20.04 LTS`

**Comment by BenTheElder** [comment]
/assign
I hadn't noticed it preventing reboots on my local 20.04 install but I might have only been doing poweroff / power on..

Will investigate

**Comment by BenTheElder** [comment]
```
$ time docker stop kind-control-plane
kind-control-plane

real	0m10.615s
user	0m0.023s
sys	0m0.045s

$ kind version
kind v0.8.1 go1.14.2 linux/amd64

$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 352
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-28-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.29GiB
 Name: gibson
 ID: KY7O:CITK:2IAO:IP3K:2IV3:GETG:FSIU:AH4S:33TF:25UQ:L5HI:BWVW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: bentheelder
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Comment by BenTheElder** [comment]
I can't reproduce this with a stock cluster on ubuntu 20.04 / stable docker-ce / stable kind (v0.8.1 has very minor alterations vs 0.8.0)

I'm going to need more info.
/triage needs-information

**Comment by BenTheElder** [comment]
@tdickman do you have any more details about reproducing? I'm unable to reproduce this so far.

> Start kind and run `docker stop kind-control-plane`. 

This works as expected and exits cleanly without hanging. Ditto for actually rebooting the host.

**Comment by tdickman** [comment]
@BenTheElder thanks for looking into this! I did some more testing, and docker does eventually stop after ~10 minutes. I think it has to do with the workload I'm running in my cluster, but unfortunately I am running a number of things in it, so it is hard to narrow it down.

**Comment by aojea** [comment]
high load + control plane smells etcd 🤔

**Comment by BenTheElder** [comment]
Without a reproducer we can't do much more here.

I haven't experienced this issue on any of my systems, regardless of workloads, and I've run very nearly the same system as yourd, minus whatever your workload is and hardware.

Can you tell us anything about your workloads?
Anything privileged? Anything with long pod delete times (maybe grace period)?
I'm grasping at straws to see this reproduced.

**Comment by BenTheElder** [comment]
please `/reopen` if you can create a reproducer.
