### ISSUE TITLE
kubectl cannot communicate with new cluster

### ISSUE THREAD

**Issue by xstevens** [kubernetes-sigs/kind#156]
I was trying out KIND on macOS. The cluster seems to startup fine and there's no indication of errors in the logs. However, kubectl cannot communicate with the server using the generated kubeconfig. 

```
$ kubectl cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: EOF
```

Here's a log of shell commands:

https://gist.github.com/xstevens/f43236505e7849d4079f8204c4a3f52b

**Comment by BenTheElder** [comment]
`kind export logs` will give us logs to look at, it does look like the cluster came up fine initially at least from what you posted.

/assign

**Comment by BenTheElder** [comment]
how much RAM does your docker daemon have configured?

docker for mac being low on RAM or disk space in the hyperkit vm is usually why something like this happens, that's something we need to cover more in the docs and maybe try to detect.

**Comment by xstevens** [comment]
I killed the previous cluster and tried 4 CPU / 4GB RAM for Docker and ended with the same result.
```
$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS              PORTS                      NAMES
c0261f7512fd        kindest/node:v1.12.2   "/usr/local/bin/entr…"   About a minute ago   Up About a minute   0.0.0.0:64907->64907/tcp   kind-1-control-plane
$ docker exec -it c0261f7512fd /bin/sh
# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
#
```

Attaching the export logs.
[kubelet.log](https://github.com/kubernetes-sigs/kind/files/2655457/kubelet.log)
[journal.log](https://github.com/kubernetes-sigs/kind/files/2655458/journal.log)
[kubernetes-version.txt](https://github.com/kubernetes-sigs/kind/files/2655459/kubernetes-version.txt)
[docker.log](https://github.com/kubernetes-sigs/kind/files/2655460/docker.log)
[docker-info.txt](https://github.com/kubernetes-sigs/kind/files/2655461/docker-info.txt)

**Comment by BenTheElder** [comment]
Thanks! looks like disk space from the kubelet log:
```
Dec 07 00:37:53 kind-1-control-plane kubelet[688]: I1207 00:37:53.229561     688 eviction_manager.go:340] eviction manager: must evict pod(s) to reclaim ephemeral-storage
Dec 07 00:37:53 kind-1-control-plane kubelet[688]: E1207 00:37:53.229638     688 eviction_manager.go:351] eviction manager: eviction thresholds have been met, but no pods are active to evict
```

If you EG build kubernetes (or kind node images) often, it will eat up all of the space in the docker for mac disk, something like `docker system prune` usually helps.

**Comment by xstevens** [comment]
Cleared up my images with prune and removed some other old ones. Works now, thanks!

**Comment by alejandrox1** [comment]
@BenTheElder I can help on the docs and possibly add some logging to make this type of issues easier to diagnose, if you haven't already started.

**Comment by hassanshamshir** [comment]
I am getting this error
kubectl get nodes
E0114 07:59:28.095214 2159766 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:38145/api?timeout=32s\": read tcp 127.0.0.1:55498->127.0.0.1:38145: read: connection reset by peer - error from a previous attempt: read tcp 127.0.0.1:55490->127.0.0.1:38145: read: connection reset by peer"
E0114 07:59:38.114113 2159766 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:38145/api?timeout=32s\": EOF - error from a previous attempt: read tcp 127.0.0.1:52492->127.0.0.1:38145: read: connection reset by peer"
E0114 07:59:48.129915 2159766 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:38145/api?timeout=32s\": EOF"
E0114 07:59:58.141718 2159766 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:38145/api?timeout=32s\": EOF"
E0114 08:00:08.177392 2159766 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:38145/api?timeout=32s\": EOF"
Unable to connect to the server: EOF
In k8s

<img width="1897" height="181" alt="Image" src="https://github.com/user-attachments/assets/98ec458e-fd1a-4737-89b2-e6536fa795a7" />

in docker 

<img width="1565" height="113" alt="Image" src="https://github.com/user-attachments/assets/5c1a9352-2015-43ca-93ca-18ff061b1329" />

**Comment by hassanshamshir** [comment]
Any instant fix

**Comment by BenTheElder** [comment]
This is a 7 year old issue ... it is unlikely to have any relation.

Please follow the bug filing guide to collect `kind export logs` and also please check for the most minimal reproducing case (e.g. a single node cluster since you seem to have a multi-node cluster).
