### ISSUE TITLE
Logging exec commands issued by kind with -v=5

### ISSUE THREAD

**Issue by maelvls** [kubernetes-sigs/kind#1563]
I wish I was able to see all the docker commands issued by `kind` "under the hood" (e.g. using `-v=5`). That would help me better understand how this magic works 😅

Investigating this idea of logging the `exec.Command` issued by Kind I came across this line:

https://github.com/kubernetes-sigs/kind/blob/077cd1650e2ad76c3aa59d719ee606ed60ae869f/pkg/exec/local.go#L122

It is quite simple to log the exec commands that are issued but the whole trick is to find a way to "inject" a logger down there. For now, I would just go with a blunt `log.Printf` but I wish to be able to inject a logger which would probably make more sense!

@BenTheElder Do you think this feature would make sense?

**Comment by BenTheElder** [comment]
I don't really want people depending on how the "magic" works at an any point in time, and you can determine what calls are being made by inspecting the code?

When we logged the commands previously people started trying to depend on using them independently of the kind binary which was pretty frustrating to support.

**Comment by BenTheElder** [comment]
Let me think about this, It also might get pretty ugly trying to inject this all over, some globals are used today.

I feel like reading the code is much more instructive about the intent of the magic, generally any magic flags etc. are well commented, or if they aren't I'd consider _that_ to be a bug.

**Comment by BenTheElder** [comment]
I think we should better document how things work, but some kind of trace might be useful in the future.
As it stands, I don't think this is the right refactor to focus on, and will require significant code changes (which is expensive even in just PR review).

Let's revisit this at a later date.
