### ISSUE TITLE
Error: failed to create cluster: failed to init node with kubeadm: exit status 1

### ISSUE THREAD

**Issue by williamaronli** [kubernetes-sigs/kind#1570]
I run the kind to create a cluster on a linux 

command like this: kind create cluster --name=testing --config ./prow/config/trustworthy-jwt.yaml --retain --image kindest/node:v1.18.2 --wait=60s

error like this:
Error: failed to create cluster: failed to init node with kubeadm: exit status 1

The debug level log
fss@fss:~/go/src/istio.io/istio$ kind create cluster --name=istio-testing --config ./prow/config/trustworthy-jwt.yaml --retain --image kindest/node:v1.18.2 --wait=60s --loglevel=debug
DEBU[01:06:33] Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\t{{.Label "io.k8s.sigs.kind.cluster"}}] 
Creating cluster "istio-testing" ...
DEBU[01:06:33] Running: /usr/bin/docker [docker inspect --type=image kindest/node:v1.18.2] 
INFO[01:06:33] Image: kindest/node:v1.18.2 present locally  
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼
DEBU[01:06:33] Running: /usr/bin/docker [docker info --format '{{json .SecurityOptions}}'] 
DEBU[01:06:33] Running: /usr/bin/docker [docker run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname istio-testing-control-plane --name istio-testing-control-plane --label io.k8s.sigs.kind.cluster=istio-testing --label io.k8s.sigs.kind.role=control-plane --expose 34967 --publish=127.0.0.1:34967:6443 kindest/node:v1.18.2] 
 ✓ Preparing nodes 📦 
DEBU[01:06:34] Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\t{{.Label "io.k8s.sigs.kind.cluster"}} --filter label=io.k8s.sigs.kind.cluster=istio-testing] 
DEBU[01:06:34] Running: /usr/bin/docker [docker inspect -f {{index .Config.Labels "io.k8s.sigs.kind.role"}} istio-testing-control-plane] 
DEBU[01:06:34] Running: /usr/bin/docker [docker exec --privileged istio-testing-control-plane cat /kind/version] 
DEBU[01:06:34] Running: /usr/bin/docker [docker inspect -f {{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}} istio-testing-control-plane] 
DEBU[01:06:34] Running: /usr/bin/docker [docker inspect -f {{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}} istio-testing-control-plane] 
DEBU[01:06:34] Configuration Input data: {istio-testing v1.18.2 192.168.9.2:6443 6443 127.0.0.1 true 192.168.9.2 abcdef.0123456789abcdef 10.244.0.0/16 10.96.0.0/12 false {}} 
DEBU[01:06:34] Configuration generated:
 # config generated by kind
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
metadata:
  name: config
kubernetesVersion: v1.18.2
clusterName: "istio-testing"
controlPlaneEndpoint: "192.168.9.2:6443"
# on docker for mac we have to expose the api server via port forward,
# so we need to ensure the cert is valid for localhost so we can talk
# to the cluster after rewriting the kubeconfig to point to localhost
apiServer:
  certSANs: [localhost, "127.0.0.1"]
controllerManager:
  extraArgs:
    enable-hostpath-provisioner: "true"
    # configure ipv6 default addresses for IPv6 clusters
    
scheduler:
  extraArgs:
    # configure ipv6 default addresses for IPv6 clusters
    
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
metadata:
  name: config
# we use a well know token for TLS bootstrap
bootstrapTokens:
- token: "abcdef.0123456789abcdef"
# we use a well know port for making the API server discoverable inside docker network. 
# from the host machine such port will be accessible via a random local port instead.
localAPIEndpoint:
  advertiseAddress: "192.168.9.2"
  bindPort: 6443
nodeRegistration:
  criSocket: "/run/containerd/containerd.sock"
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: "192.168.9.2"
---
# no-op entry that exists solely so it can be patched
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
metadata:
  name: config
controlPlane:
  localAPIEndpoint:
    advertiseAddress: "192.168.9.2"
    bindPort: 6443
nodeRegistration:
  criSocket: "/run/containerd/containerd.sock"
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: "192.168.9.2"
discovery:
  bootstrapToken:
    apiServerEndpoint: "192.168.9.2:6443"
    token: "abcdef.0123456789abcdef"
    unsafeSkipCAVerification: true
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
metadata:
  name: config
# configure ipv6 addresses in IPv6 mode

# disable disk resource management by default
# kubelet will see the host disk that the inner container runtime
# is ultimately backed by and attempt to recover disk space. we don't want that.
imageGCHighThresholdPercent: 100
evictionHard:
  nodefs.available: "0%"
  nodefs.inodesFree: "0%"
  imagefs.available: "0%"
---
# no-op entry that exists solely so it can be patched
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
metadata:
  name: config 
DEBU[01:06:34] Using kubeadm config:
apiServer:
  certSANs:
  - localhost
  - 127.0.0.1
  extraArgs:
    service-account-issuer: kubernetes.default.svc
    service-account-signing-key-file: /etc/kubernetes/pki/sa.key
apiVersion: kubeadm.k8s.io/v1beta2
clusterName: istio-testing
controlPlaneEndpoint: 192.168.9.2:6443
controllerManager:
  extraArgs:
    enable-hostpath-provisioner: "true"
kind: ClusterConfiguration
kubernetesVersion: v1.18.2
name: config
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler:
  extraArgs: null
---
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- token: abcdef.0123456789abcdef
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.9.2
  bindPort: 6443
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: 192.168.9.2
---
apiVersion: kubeadm.k8s.io/v1beta2
controlPlane:
  localAPIEndpoint:
    advertiseAddress: 192.168.9.2
    bindPort: 6443
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.9.2:6443
    token: abcdef.0123456789abcdef
    unsafeSkipCAVerification: true
kind: JoinConfiguration
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: 192.168.9.2
---
apiVersion: kubelet.config.k8s.io/v1beta1
evictionHard:
  imagefs.available: 0%
  nodefs.available: 0%
  nodefs.inodesFree: 0%
imageGCHighThresholdPercent: 100
kind: KubeletConfiguration
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration 
DEBU[01:06:34] Running: /usr/bin/docker [docker exec --privileged istio-testing-control-plane mkdir -p /kind] 
DEBU[01:06:34] Running: /usr/bin/docker [docker exec --privileged -i istio-testing-control-plane cp /dev/stdin /kind/kubeadm.conf] 
 ✓ Creating kubeadm config 📜 
DEBU[01:06:35] Running: /usr/bin/docker [docker exec --privileged istio-testing-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6] 
⠎⠁ Starting control-plane 
Error: failed to create cluster: failed to init node with kubeadm: exit status 1

**Comment by BenTheElder** [comment]
What is in that config?
What kind version?
What docker version?
Can you upload an archive of `kind export logs --name=testing-condig`?

**Comment by williamaronli** [comment]
1. config
# This configs KinD to spin up a k8s cluster with trustworthy jwt (Service Account Token Volume Projection) feature.
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        "service-account-issuer": "kubernetes.default.svc"
        "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"

2. Docker version: Docker version 19.03.5, build 633a0ea838
3. kind version v0.4.0
4. result of kind export logs --name=testing-condig
docker-info.txt
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.2.17-1rodete3-amd64
 Operating System: Debian GNU/Linux rodete
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 125.9GiB
 Name: fengxiangli.c.googlers.com
 ID: ISC4:JYNV:ZFYT:MVNZ:QPY5:HCQA:LKCK:PWJQ:UP3B:2F2D:MX6U:ZHMV
 Docker Root Dir: /usr/local/google/docker
 Debug Mode: true
  File Descriptors: 36
  Goroutines: 48
  System Time: 2020-05-07T07:30:40.623344809Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://mirror.gcr.io/
 Live Restore Enabled: false

WARNING: No swap limit support

**Comment by BenTheElder** [comment]
kind version 0.4.0 is the issue, please upgrade to v0.8.1, see the release notes for breaking changes.

This image requires minimum kind 0.5.0 and really 0.8.0+ to fully function.

I believe this should work fine once you upgrade

https://github.com/kubernetes-sigs/kind/releases
https://kind.sigs.k8s.io/docs/user/quick-start/#installation

**Comment by BenTheElder** [comment]
This is expected and in the release notes that the image requires newer versions.

Bumping this off the open tracker now.
