### ISSUE TITLE
Define a cluster level location for node level configurations

### ISSUE THREAD

**Issue by mauilion** [kubernetes-sigs/kind#1584]
**What would you like to be added**:
I'd like to expose some of the other fields at the cluster level the way we expose kubeadmconfigpatches.

Today you can provide a kubeadmconfigpatch at cluster and node level and they apply cluster first then node.

I think it would be pretty great to expose the other stuff that is only exposed at node level up at the cluster level to cut down on stuff that is repeated.

**Why is this needed**:

I want all nodes to mount storage at /tmp/local-shared
today I need to define the extraMount in each node I want to mount the path.
If we exposed this at the cluster level this would apply to all nodes and any more specific paths could be defined at the node level.
Another option would be to implement default: control-plane and default: node or something to specify that options at the "default" are inherited for all nodes of that role?

**Comment by mauilion** [comment]
@aojea @BenTheElder @munnerz Moving this to an issue.

**Comment by mauilion** [comment]
related: https://github.com/kubernetes-sigs/kind/issues/340

**Comment by BenTheElder** [comment]
going to circle back to this discussion, there's a lengthy slack thread here https://kubernetes.slack.com/archives/CEKK1KTN2/p1589230298289200

**Comment by aojea** [comment]
I think that it boils down to decide if we use yaml anchors or not 
🤣 🤣 🤣 🤣 🤣

**Comment by BenTheElder** [comment]
Yaml anchors do work afaict.
I think I'd rather punt the yaml templating wars to the ecosystem, what if you only want to mount this path to workers etc.?

I'm also not excited to encourage lots of nodes. The majority of users should be using a single node per cluster, at least for now.
