### ISSUE TITLE
Can I use docker run to run kind?

### ISSUE THREAD

**Issue by SamDecrock** [kubernetes-sigs/kind#1590]
Hi,

I'm on a limited system where I can only supply docker images and run them. I won't be able to install the kind CLI.

Can I run kind using the default `docker run` command?

**Comment by BenTheElder** [comment]
No, we do not support this. What happens during startup is pretty complex, you'll need to run the CLI.

**Comment by abdennour** [comment]
check `docker pull abdennour/kind-cli:v0.10.0`
