### ISSUE TITLE
Feature like minikube‘s docker-env， so docker images can directly built into kind

### ISSUE THREAD

**Issue by hatzhang** [kubernetes-sigs/kind#1609]
The eval $(minikube docker-env) command directs the local Docker client to communicate with the Docker engine in Minikube, for example, when building the Docker images.
It will be nice to have the same thing for kind. Is that possible?

**Comment by BenTheElder** [comment]
No, this is not possible.
This feature also doesn't make sense in a multi-node / milti-cluster network, but kind nodes do not run docker inside them anyhow (containerd) and that way of running kubernetes is on the way out (dockershim).

Please search the issue tracker for previous discussion (ideally before filing new issues!)
