### ISSUE TITLE
podman detection commonly foiled by fake "docker"

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#1611]
**What happened**:
There's a package `podman-docker` that symlinks `docker` to podman, defeating the auto detection of podman vs docker being installed and breaking the node provider because it thinks it's using docker when it's not.

**What you expected to happen**: We should auto detect this correctly. We can probably just check if docker is a symlink and resolve it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by BenTheElder** [comment]
correction: it's a script with roughly `exec /usr/bin/podman "$@"`

**Comment by BenTheElder** [comment]
though I think some users do symlink as well.
we might have to do something more slow like invoke the version subcommand and check the output.

**Comment by BenTheElder** [comment]
cc @amwat @aojea

**Comment by aojea** [comment]
if @amwat does not beat me ;) I can send something end of the week

**Comment by BenTheElder** [comment]
https://github.com/containers/libpod/blob/master/docker
