### ISSUE TITLE
kubelet commits suicide when running KIND in a DinD pod on a k8s cluster

### ISSUE THREAD

**Issue by porridge** [kubernetes-sigs/kind#1614]
**What happened**:

Kubelet gets confused about some unexpected cgroups and SIGKILLs everything including itself.

**What you expected to happen**:

KIND cluster creation to work... :unicorn: and :carousel_horse: 

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/porridge/kind-dind-kind-repro contains the minimum instructions I could come up with.

**Anything else we need to know?**:

I [reported this on slack](https://kubernetes.slack.com/archives/CEKK1KTN2/p1587988851297500?thread_ts=1575376979.206200&cid=CEKK1KTN2) earlier but only managed to come up with a fairly simple repro case now.

This was also described in [a blog post by Jie](https://d2iq.com/blog/running-kind-inside-a-kubernetes-cluster-for-continuous-integration) - look for

> However, when we try to run this in CI (in the production Kubernetes cluster), things start to fail.

That post describes a [workaround](https://github.com/jieyu/docker-images/tree/master/kind-cluster) that injects [some additional code](https://github.com/jieyu/docker-images/blob/master/kind-cluster/node/entrypoint-wrapper.sh) *around* the `kind` entrypoint to further massage the cgroup filesystem and requires [patching the kubelet config](https://github.com/jieyu/docker-images/blob/master/kind-cluster/kind-config.yaml).

Because of the maintenance burden of these rather invasive changes I'm looking for a better alternative.

**Environment:**

- kind version: (use `kind version`): kind v0.8.1 go1.14.2 linux/amd64
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.5.0-0.bpo.2-amd64
 Operating System: Debian GNU/Linux 10 (buster) (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.15GiB
 Name: 5bad58a9e2fb
 ID: HUJB:QY7M:643T:7OXM:L3I2:VU5C:5DHW:EEO7:53Y4:TBA4:DIXQ:A2RE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`):

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by porridge** [comment]
Oh, one important finding - commenting out the `fix_cgroup` function in the kind entrypoint is enough to make it work.

**Comment by BenTheElder** [comment]
/assign
fix_cgroup is part of host reboot.
Note that this (kind in a kubernetes pod being a supported and documented thing) already has a tracking issue. However, I'm inclined to use this to track landing some of Jie's fixes as built in.

**Comment by BenTheElder** [comment]
this should be fixed in the next release, namely the technique injected into the kind entrypoint is in the upstream entrypoint and improved now.

**Comment by BenTheElder** [comment]
v0.10.0 is shipped with aforementioned entrypoint changes. there's some additional tweaks to make it work in more environments as well.
