### ISSUE TITLE
kind build node-image supports skipping kubernetes build artifacts, only build image from docker output

### ISSUE THREAD

**Issue by zjj2wry** [kubernetes-sigs/kind#1616]
**What would you like to be added**:
```
kind build node-image --type=none
```

**Why is this needed**:

**Comment by BenTheElder** [comment]
huh? I don't understand the request.

**Comment by BenTheElder** [comment]
do you mean https://github.com/kubernetes-sigs/kind/issues/381 ?

**Comment by zjj2wry** [comment]
I understand that the behavior of `kind build node-image` will always execute some commands like` build / run.sh make KUBE_BUILD_PLATFORMS = linux / amd64`, but I want to use the existing binary under the `_output / dockerized` directory, only build node image instead of compile + build node image

**Comment by BenTheElder** [comment]
we need to ensure the right things are built at the same commit and be aware of where they were built to etc.

#381 concerns consuming pre-existing built output.

**Comment by BenTheElder** [comment]
the build system produces release tarballs, this will be covered by #381 

the set of targets we need will change with time, but it should always be a subset of `make quick-release`.
