### ISSUE TITLE
nginx ingress guide doesn't work

### ISSUE THREAD

**Issue by yene** [kubernetes-sigs/kind#1617]
Following the [nginx ingress guide](https://kind.sigs.k8s.io/docs/user/ingress/) and doing:

* docker desktop for mac 2.3.0.2
* brew install kind (kind v0.8.1 go1.14.2 darwin/amd64)
* kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
* kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml

Results in multiple problems like:
* nginx ingress controller not starting: 0/1 nodes are available: 1 node(s) didn't match node selector.
* kError from server (InternalError): error when creating "https://kind.sigs.k8s.io/examples/ingress/usage.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io":

Thank you for helping to improve the documentation.

**Comment by aojea** [comment]
are you creating the cluster with the configuration indicated in the docs?

https://kind.sigs.k8s.io/docs/user/ingress/#create-cluster

can you paste the output of `kubectl get nodes -o yaml`?

**Comment by BenTheElder** [comment]
When did you run this? quay.io was having major issues and the images for ingress-nginx upstream are currently hosted there.

I'm certain this guide has been tested and pretty confident it's correct, the author of ingress-nginx helps maintain it 🙃

**Comment by yene** [comment]
Thanks for the answer, I will test again tomorrow.

**Comment by yene** [comment]
Works today, I must have done a mistake during the setup steps.

**Comment by bwolf** [comment]
I still get this error. I'm also following the setup guide. Deploying either master or 0.32.0 (of ingress-nginx) fails with the following error.

```
$ Kubectl describe pod -n ingress-nginx ingress-nginx-controller-cc8dd9868-vd6s6y

Warning  FailedMount  35s (x5 over 43s)  kubelet, kind-control-plane  MountVolume.SetUp failed for volume "webhook-cert" : secret "ingress-nginx-admission" not found
```
