### ISSUE TITLE
Support custom node start commands

### ISSUE THREAD

**Issue by nadenf** [kubernetes-sigs/kind#1621]
**What would you like to be added**:

It would be nice to be able to specify startup commands for the nodes.
This would be a provide a simple way to customise them without requiring a new base image.

```
- role: worker
   onStartup:
     - sed -i 's/debug=0/debug=1/g' /etc/app.conf
```

This would then map to the following:
```
docker exec -it kind-worker bash -c "sed -i 's/debug=0/debug=1/g' /etc/app.conf"  
```
**Why is this needed**:

Because sometimes you just want to make some temporary changes to the nodes e.g. debugging. Or even to make what is being changed more visible to other developers.

**Comment by BenTheElder** [comment]
you can do this yourself in a script with docker exec or by using a docker image file that does:
FROM node-image
RUN temp-command
And then passing that image to kind

**Comment by BenTheElder** [comment]
The contents of the node images are unspecified currently, other than they contain what is necessary to run kubernetes.

We don't actually advertise that they are apt based or anything like that, until we decide that they are stable, I'd rather not make it easier to depend on details of their contents at runtime.

**Comment by nadenf** [comment]
@BenTheElder  .. Have updated the example. It's more just if you want to quickly enable something or make some changes without having to go through rebuilding a new base image.

**Comment by BenTheElder** [comment]
You don't need to build a base image, you can add this to a node image too, and it's quick, without any changes to kind.

**Comment by BenTheElder** [comment]
for now, closing. thanks for the input!
