### ISSUE TITLE
Support configuring shared memory size

### ISSUE THREAD

**Issue by nadenf** [kubernetes-sigs/kind#1622]
**What would you like to be added**:
Ability to specify the shared memory size for the node:

```
- role: worker
  sharedMemory: 1g
```

This would map to a docker flag like such:
```
docker run -it --shm-size=1g kind-worker
```

**Why is this needed**:
Some applications e.g. Alluxio require a custom shared memory size.

**Comment by BenTheElder** [comment]
does alluxio run using the host namespace for this? Otherwise ... https://github.com/kubernetes/kubernetes/issues/28272

**Comment by nadenf** [comment]
Looks like this will be handled by Kubernetes itself. Closing.
