### ISSUE TITLE
Unhelpful info log verbosity level

### ISSUE THREAD

**Issue by lukehinds** [kubernetes-sigs/kind#1624]
**What would you like to be added**: 

Better help description for `-v --verbosity`

**Why is this needed**:

Currently the help menu displays:

```
Global Flags:
      --loglevel string   DEPRECATED: see -v instead
  -q, --quiet             silence all stderr output
  -v, --verbosity int32   info log verbosity
```

Some guidance would be nice around `int32`,  what does that even mean? Any value up to `2,147,483,647`? I am guessing there is a map to the log verbosity level, but what is that mapping?

**Comment by BenTheElder** [comment]
This is a standard kubernetes / klog / glog thing. You increase the value it until it shows what you're looking for.

The verbose logs aren't a contract of any sort, they're for developing kind. The loglevel mapping is purely there to maintain that calling the CLI won't break until users get a chance to switch.

User facing information emits at the default, and can be silenced with the quiet flag.

**Comment by BenTheElder** [comment]
We can change the message a bit but, there are no advertised values. Kubernetes doesn't advertise any either.

**Comment by BenTheElder** [comment]
it would be helpful to at least update it with a terse reference to increasing the value to see more logs, the current description is surely too vague.

[I am sweeping all issues that were caught up by the bot, which I've now disabled in this repo]

**Comment by xinydev** [comment]
> it would be helpful to at least update it with a terse reference to increasing the value to see more logs, the current description is surely too vague.
> 
> [I am sweeping all issues that were caught up by the bot, which I've now disabled in this repo]

How about changing it like this

 `info log verbosity. higher value produces more output. value of zero or lower produces no output.`

**Comment by BenTheElder** [comment]
I think maybe just `info log verbosity. higher value produces more output`, as `-q` is the correct way to ensure no logs only command output
