### ISSUE TITLE
How to access the local registry from inside the cluster?

### ISSUE THREAD

**Issue by lolin9** [kubernetes-sigs/kind#1631]
I need to create, from within running pods, deployments that contain containers from the local registry. Is this possible? I can't see anything that implies so in https://kind.sigs.k8s.io/docs/user/local-registry/

**Comment by BenTheElder** [comment]
this part:

> 4. And now we can use the image kubectl create deployment hello-server --image=localhost:5000/hello-app:1.0

kubernetes doesn't care if your deployment object was created inside or outside of the cluster.

use localhost:500/foo:bar for deployments created from either.
