### ISSUE TITLE
Unable to create cluster with "kind create cluster" using KIND v0.8.0, always result into an error 

### ISSUE THREAD

**Issue by gupta-lakshay** [kubernetes-sigs/kind#1641]
**What happened**:
I tried creating kind cluster using "kind create cluster" but it results into error.

[root@kind-k8s ~]# **kind create cluster --retain**
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
**ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1**

LOGS after executing "kind export logs" are attached.
[kind-issue-logs.tar.gz](https://github.com/kubernetes-sigs/kind/files/4710953/kind-issue-logs.tar.gz)

**What you expected to happen**:
KIND cluster should create successfully with one control plane node.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install KIND v0.8.0 using GO111MODULE="on" go get sigs.k8s.io/kind@v0.8.0
2. Set the PATH using export PATH.
3. Execute "_kind create cluster_"

**Anything else we need to know?**:
I tried creating cluster on same environment with KIND v0.7.0 using "kind create cluster" and also using kind-with-registry.sh provided on user guide link https://kind.sigs.k8s.io/docs/user/local-registry/. I was successfully able to create cluster and use it. I only changed KIND version from 0.7.0 to 0.8.0 and I faced the problem while creation of cluster.

**Environment:**

- kind version: (use `kind version`):
[root@kind-k8s ~]# kind version
kind v0.8.1 go1.14.2 linux/amd64

- Kubernetes version: (use `kubectl version`):
[root@kind-k8s ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

- Docker version: (use `docker info`):
[root@kind-k8s ~]# docker info
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 19.03.1-ol
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc version: 4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.35-1818.0.9.el7uek.x86_64
 Operating System: Oracle Linux Server 7.5
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.9GiB
 Name: kind-k8s.novalocal
 ID: U6F2:YUFJ:CYBL:YCZX:DM7H:WO5C:CKVS:E4JY:5NJ3:VFN7:3KMR:CYX6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://www-proxy-hqdc.us.oracle.com:80
 HTTPS Proxy: http://www-proxy-hqdc.us.oracle.com:80
 No Proxy: localhost,127.0.0.1,chef,10.244.0.0/16,10.96.0.0/12,10.75.200.217,reg-1,kind-registry
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  kind-registry:5000
  reg-1:5000
  127.0.0.0/8
 Live Restore Enabled: false

Registries:

- OS (e.g. from `/etc/os-release`):
[root@kind-k8s ~]# cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.5"
ID="ol"
VERSION_ID="7.5"
PRETTY_NAME="Oracle Linux Server 7.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.5

**Comment by BenTheElder** [comment]
There are existing known issues with proxies that have since been fixed, please try from HEAD and check the issue tracker

https://github.com/kubernetes-sigs/kind/issues/1579
