### ISSUE TITLE
Failed to init node with kubeadm on a dind setup

### ISSUE THREAD

**Issue by fgimenez** [kubernetes-sigs/kind#1645]
**What happened**: 
I get an error when trying to start a cluster on a gitlab worker running on kubernetes.

**What you expected to happen**:
The cluster starts properly.

**How to reproduce it (as minimally and precisely as possible)**:

`kind create cluster` is executed from a container built from this image https://github.com/w3f/node-dind-docker/blob/master/Dockerfile It runs on a gitlab kubernetes runner that has declared `docker:18.03-dind` as service.  

**Anything else we need to know?**:
This is the complete log: https://gist.github.com/fgimenez/90a3f9e6bd5eb11cc864019480794bd7

**Environment:**

- kind version: (use `kind version`): 0.8.1
- Kubernetes version: (use `kubectl version`): 1.18.2
- Docker version: (use `docker info`): 18.03
- OS (e.g. from `/etc/os-release`): ubuntu (GKE)

**Comment by BenTheElder** [comment]
If you're running on kubernetes there's an existing issue covering all the things you have to do to run in kubernetes correctly, that we've found *so far*.

Running a kubernetes inside a kubernetes is full of problems but doable.

**Comment by BenTheElder** [comment]
For general kubernetes in kubernetes see existing issue https://github.com/kubernetes-sigs/kind/issues/303

You'll have to check various things we've found so far covered in the issue including e.g. increasing inotify watches on the hosts enough for multiple kubelets.

There have also been past GitLab issues, but From the docs resources page we link to this contrib repo for CI setups, we track CI specific config there https://github.com/kind-ci/examples

**Comment by fgimenez** [comment]
Great, thanks a lot for the pointers @BenTheElder <3
