### ISSUE TITLE
PSP enabled KIND cluster

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/kind#1648]
**What would you like to be documented**:
This is not a request per se. I was able to create a PSP enabled cluster using KIND. Here are my steps: https://github.com/appscodelabs/tasty-kube/tree/master/kind/psp . If anyone has any suggestion, I would like to hear.

**Why is this needed**:
I know that PSP issue has been discussed before: https://github.com/kubernetes-sigs/kind/pull/725 . We are increasingly seeing PSP usage among our userbase, meaning we get bug reports :smile: . Recently PSPs were standardized https://twitter.com/tallclair/status/1263611210273918976 . So, we are looking to test our operators against PSP enabled cluster in GitHub Actions.

**Comment by BenTheElder** [comment]
AIUI psp will not work portably still and is still not slayed to go GA, non GA features are now slated for eventual removal ... 🤔

**Comment by tamalsaha** [comment]
PSP in its current form will not GA but something will be done. https://github.com/kubernetes/enhancements/issues/5#issuecomment-637066475

**Comment by BenTheElder** [comment]
Sorry we haven't gotten to this yet. I was reminded when I saw that the latest is it's officially deprecated and going away https://github.com/kubernetes/kubernetes/pull/97171

**Comment by BenTheElder** [comment]
hopefully we will continue to see the PSP replacement @liggitt is working on work fine on kind, but PSP itself being on the way out I can't see us working on legacy PSP docs still. sorry we never got to that.

**Comment by xmcqueen** [comment]
This old ticket helped me get the cluster up with full psp support.  Thanks @tamalsaha  I used the psp's you linked.
