### ISSUE TITLE
Custom roles

### ISSUE THREAD

**Issue by nadenf** [kubernetes-sigs/kind#1653]
**What would you like to be added**:
Ability to specify custom roles in addition to control-plane or worker.

**Why is this needed**:
Because when you are kubectl or dashboards like k9s when you do a "kubectl get pods" it will return a pod spec that contains only the node name. This means you can't easily access the node labels.

It would be very useful to be able to see a worker named "cluster-ingress-0" or "cluster-storage-0" rather than "cluster-worker-15" and "cluster-worker-16".

**Idea**:
To make it easier to implement perhaps you could allow worker roles to have sub types e.g.

```
control-plane
worker
worker-ingress
worker-storage
```

And then just do a "starts with" instead of "equals" when checking for nodes.

**Comment by BenTheElder** [comment]
We might allow custom node names in the future but roles tell us what the node should be configured for, so no, I don't think I we're going to support non standard / arbitrary roles.

As for node names, pretty much all major cluster management automatically names nodes including all of SIG cluster lifecycle's tools, you should really leverage labels and label selectors.
