### ISSUE TITLE
How do I make requests to a service running in the kind cluster?

### ISSUE THREAD

**Issue by blake-mealey** [kubernetes-sigs/kind#1654]
Hey, I'm new to Kubernetes and I've been trying to get setup for local development using kind.

I first tried minikube but I want to be able to run kubernetes in my WSL 2 distro on Windows 10 and minikube does not have good support for it. Also, minikube on Windows is very slow (a few seconds for each command). So far kind has been easy to install and very fast on WSL and I've been happy with it.

However, I am having a lot of trouble doing something that seems like it should be pretty straightforward. My goal is to run a simple hello-world app in a pod, then make a request to that app from my host (using curl or the browser). I have been able to do this by running `kubectl port-forward ...` however this requires that command to be running, and only allows me to access one service at a time.

I first tried exposing my deployment as a service and attempted to request the node's IP with the NodePort of the service. I wasn't sure how to find the node's IP for this though. I tried my IP from `ip addr` output and localhost and neither worked.

Then I followed your guide on https://kind.sigs.k8s.io/docs/user/ingress/. I first tried the NGINX guide but had some errors so I deleted and re-created the kind cluster and tried again with the other two. Each of the other two (on a clean cluster) worked without errors and when I applied the example deployment it created all the right resources. However, when I tried the final `curl localhost/(foo|bar)` it failed to connect again.

Any ideas as to what I am missing? Is this a WSL issue?

Thanks in advance

**Comment by aojea** [comment]
can you paste the curl error adding the verbose flag?
`curl -v localhost/foo`

Also, what's the output of?
`docker ps -a`
`kubectl get nodes -o wide`

**Comment by blake-mealey** [comment]
Hey, I struggled with this yesterday and today, before trying Docker Desktop's integrated Kubernetes which worked for me out of the box with `localhost:NODE_PORT` so I have uninstalled kind and switched over to Docker Desktop Kubernetes and therefore can't get you that information anymore :(

Thanks for the response but I think we can close this one now

**Comment by aojea** [comment]
/close
no problem
Thanks
