### ISSUE TITLE
Custom node names

### ISSUE THREAD

**Issue by nadenf** [kubernetes-sigs/kind#1656]
I know this has been closed before but would be good to keep open.

**What would you like to be added**:

The ability to specify a custom node name or some prefix/suffix etc. Anything to identify what type of node it is.

**Why is this needed**:

Because unfortunately node labels are not a great solution in this case. When you run the following command:
```
kubectl get pods
```

The result i.e. PodSpec only contains the node name. If you need to access the node labels then you need to list all of the nodes and all of the pods and do a join. Which is why not a single UI or CLI shows the node labels and likely never will.

I understand that vendors will autogenerate node names but they usually allow you to specify some template, prefix, suffix etc so you can identify them.

**Comment by BenTheElder** [comment]
Please do not file a new issue for an existing, closed issue. We can reopen the old issue instead at such a time that we are actively reconsidering it.

Currently we are not.
None of the other cluster tools in the project do this. Node labels are the standard.

Many UIs do show labels.

**Comment by BenTheElder** [comment]
It's true that listing pods only shows the node name and you need to join, but you can show the label selectors on your pods which would be the relevant part here.

UIs will show the labels on the nodes, and you can do the join.

In kind there should not be particularly many nodes to search through.

It's also worth noting that unless you're testing kubernetes itself, or either rolling updates or distributed behavior in such a way that is actually sensitive to multi-node your tests should be using a single node cluster as these nodes are not real isolated nodes.

To my knowledge none of the upstream cluster tools have any user input in the node names except for the cluster or host project name, ditto for major hosted solutions.
Labels and taints are used for scheduling.
