### ISSUE TITLE
[lxc] command "docker exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 1

### ISSUE THREAD

**Issue by kstenerud** [kubernetes-sigs/kind#1658]
**What happened**:

```
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼 
 ✓ Preparing nodes 📦  
 ✗ Writing configuration 📜 
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 1
Command Output: Error response from daemon: Container 56e7b5b069c581064bade0ce01de6ef70557fbb16eef5406ec2f2a6cd06c5da9 is not running
```

**What you expected to happen**:

Something not an error

**How to reproduce it (as minimally and precisely as possible)**:

```
lxc launch ubuntu-daily:focal k8s && \
lxc config set k8s security.privileged true && \
lxc config set k8s  security.nesting true && \
lxc exec k8s bash

# Install software
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
apt update && \
apt install -y docker-ce docker-ce-cli containerd.io && \
usermod -a -G docker ubuntu && \
apt install -y golang-go && \
cat <<EOF >>~ubuntu/.profile
PATH="\$HOME/go/bin:\$PATH"
EOF

# Switch to user ubuntu
su - ubuntu

# Install kind
GO111MODULE="on" go get sigs.k8s.io/kind@v0.8.1 && kind create cluster
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): `kind v0.8.1 go1.13.8 linux/amd64`
- Kubernetes version: (use `kubectl version`): `kubectl: command not found`
- Docker version: (use `docker info`): `Server Version: 19.03.11`
- OS (e.g. from `/etc/os-release`): `Ubuntu 20.04 LTS`

**Comment by BenTheElder** [comment]
This error means the node exited during the entry point which shouldn't happen and generally means an unworkable environment.

Probably the lxc container cannot support kind.

Can you run with --retain and get the logs of the container? (kind-control-plane)

**Comment by BenTheElder** [comment]
Also does this need to be done inside lxc ...?

Last time someone tried to do this the issue was something like lxc being too restrictive with security policies for *kubernetes* to work IIRC ...

**Comment by BenTheElder** [comment]
I tried to reproduce your example (including first installing lxd...) but it doesn't work, the install instructions for docker are broken.

**Comment by BenTheElder** [comment]
so the issue is indeed that we can't call `mount` inside the kind node
kubernetes won't work well without `mount` calls

it sounds like you may be able to set apparmor unconfined in lxc somehow to enable this, but ... I don't recommend trying to run kubernetes inside lxc, and I don't think we're the right support channel for lxc issues.

there is no bug in kind here.

**Comment by BenTheElder** [comment]
```
ubuntu@k8s:~$ docker logs kind-control-plane
WARN: /dev/kmsg does not exist, symlinking /dev/console
INFO: ensuring we can execute /bin/mount even with userns-remap
INFO: remounting /sys read-only
mount: /sys: permission denied.
WARN: /dev/kmsg does not exist, symlinking /dev/console
INFO: ensuring we can execute /bin/mount even with userns-remap
INFO: remounting /sys read-only
mount: /sys: permission denied.
```
