### ISSUE TITLE
Is it possible to do multi server/machine setup?

### ISSUE THREAD

**Issue by bamzi** [kubernetes-sigs/kind#1665]
I've been experimenting with Kind multi worker setup on my laptop for dev env but my poor laptop is chokIng once microservices, kafka and elk stack are deployed. Since my work involves experimentation, quickly destroying and creating new cluster deployment with Kind is a huge time saver and I want to preserve that experience as much as possible.  

So I want to utilize some of the hardware I have around, but i'm having trouble figuring out an automated way to manage a single Kind cluster with multi workers on different machines.  Simple example would be trying to deploy Kind into a cluster of RaspeberryPis and distribute master+workers across multiple Raspberries. (I know current ARM32 is not supported, but with 64bit os most everything works)

I did manage extracting a master node join script and I can join from another machine with required software installed, but the other machines are running vanilla K8S stack and i have to manually run `kubeadm join...` and not Kind worker in docker. 

Any insight or knowledge sharing is much appreciated

**Comment by rvowles** [comment]
talos and sidero
