### ISSUE TITLE
kubectl exec failed

### ISSUE THREAD

**Issue by mengzyou** [kubernetes-sigs/kind#1666]
**What happened**:

After depoyed some pods, when use command `kubectl exec`, failed with error: unable to upgrade connection: pod does not exist'

For example:

```bash
❯ kubectl exec -i -t debugtool-5446d84c95-9nzrs -- bash
error: unable to upgrade connection: pod does not exist
```

**What you expected to happen**:  

Successfully executem the command, and go into container.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): kind v0.7.0 go1.13.6 linux/amd64
- Kubernetes version: (use `kubectl version`): v1.17.0
- Docker version: (use `docker info`): 19.03.11
- OS (e.g. from `/etc/os-release`): openSUSE Leap 15.1

**Comment by BenTheElder** [comment]
pod doesn't exist means the pod doesn't exist so you can't exec to it ...

**Comment by mengzyou** [comment]
Ok, Thanks for your help, I re-create a kind cluster, it works now.
