### ISSUE TITLE
how to install a custom CA certificate

### ISSUE THREAD

**Issue by torsten-liermann** [kubernetes-sigs/kind#1674]
How do I get a custom CA certificate in the containerd?

I install Kind from Windows on a remote docker daemon on a debian buster. The custom CA certificate is required to access an internal registry.

Thanks,
Torsten

(have not yet received an answer via slack)

**Comment by BenTheElder** [comment]
Hi I'll follow up on this in the morning but:
1) can you link to where you asked in slack? Theres no requirement to ask there before asking here at all but I don't remember seeing your question and I'm quite active in the slack ...

2) for a faster resolution search through the issue tracker / closed issues, this has come up before and other users have figured it out. Basically you install the cert to the node as you would install a system cert to an Ubuntu machine and then you restart containerd on the node. You can do things on each node via docker exec.

**Comment by torsten-liermann** [comment]
The slack link is: https://kubernetes.slack.com/archives/CEKK1KTN2/p1592420422115300

Thanks for the hints.

**Comment by torsten-liermann** [comment]
kind create cluster converts the hostpath /usr/local/share/ca-certificates/XYZ.crt to a windows path like --volume=C:\usr\local\share\ca-certificates\XYZ.crt:/usr/local/share/ca-certificates/XYZ.crt :-(

**Comment by BenTheElder** [comment]
what version are you using? that sounds like an old bug.

**Comment by torsten-liermann** [comment]
I'm using kind 0.7.0 

With kind 0.8.0 the create cluster crashes on a debian buster + docker 19.03.6

```
I0618 16:16:12.126652     157 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 114 milliseconds
I0618 16:16:12.549191     157 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 36 milliseconds

Unfortunately, an error has occurred:
        I0618 16:16:12.601008     157 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 51 milliseconds
timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
        - 'docker ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'docker logs CONTAINERID'
couldn't initialize a Kubernetes cluster
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runWaitControlPlanePhase
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:10
```

**Comment by torsten-liermann** [comment]
Does not work. The error message is

```
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.17.5) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.17.5) 🖼
 • Preparing nodes 📦   ...
 ✗ Preparing nodes 📦
ERROR: failed to create cluster: failed to get random host port for port mapping: listen tcp 172.18.146.182:0: bind: Die angeforderte Adresse ist in diesem Kontext ungültig.
```
172.18.148.182 is the address of the apiServer and of the docker daemon (tcp://172.18.148.182:3127)

**Comment by BenTheElder** [comment]
this is with a remote daemon?
are you configuring kind? if so you probably need to configure the port to -1 https://github.com/kubernetes-sigs/kind/pull/1353

**Comment by BenTheElder** [comment]
(follow the threads from there, I can explain more later)

**Comment by torsten-liermann** [comment]
The [same error](https://github.com/kubernetes-sigs/kind/issues/1674#issuecomment-646161239) occurs with kind 0.8.1, regardless of whether kind is run from Windows or directly on the Debian Buster VM

**Comment by BenTheElder** [comment]
is the VM WSL2 or something else?
WSL2 until _very_ recently required some fixes.

**Comment by torsten-liermann** [comment]
the VM is Hyper-V on Windows 10. Other Kubes like minikube, microk8s work

**Comment by BenTheElder** [comment]
can you please run `kind create cluster` with `--retain` (disable cleanup on failure) and then `kind export logs` the cluster and share those, along with the exact details of how you're running this? (cluster config etc.)

this sounds like a different, real bug, and I'd love to fix it, but https://github.com/kubernetes-sigs/kind/issues/1674#issuecomment-646161239 contains only symptoms (can't reach the api server) not the cause (it might not be running for example).

**Comment by torsten-liermann** [comment]
1. kind-0.8.1 create cluster --retain # without extra configuration and direct on the VM with debian buster 10 and Docker version 19.03.6, build 369ce74a3c 

2. kind-0.8.1 export logs # attacht as zip (tgz not supported as attachment format=
[logs.tgz.zip](https://github.com/kubernetes-sigs/kind/files/4805731/logs.tgz.zip)
)

Thanks for the support.

**Comment by BenTheElder** [comment]
this is a proxy issue, I beleive it should be fixed at `HEAD`.
in the ./kind-control-plane/kubelet.log you can see:
> Jun 19 15:42:00 kind-control-plane kubelet[290]: E0619 15:42:00.078252     290 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/kubelet.go:517: Failed to list *v1.Service: Get https://kind-control-plane:6443/api/v1/services?limit=500&resourceVersion=0: Proxy Authentication Required

you can work around this in 0.8.x by adding `*-control-plane,*-worker` to `NO_PROXY`, for a one node cluster just `kind-control-plane` is sufficient.

in the next release this will be automatic. this was an oversight when implementing host reboot support. we lack a testbed with proxy.

**Comment by torsten-liermann** [comment]
Thank you for the quick and successful support. 👍
