### ISSUE TITLE
Should we use a simple `build-node-image.sh` to replace `kind build node-image`?

### ISSUE THREAD

**Issue by brightzheng100** [kubernetes-sigs/kind#1679]
**What would you like to be added**:

While reading the `kind build node-image` code, it's...complicated...and relies heavily on upstream K8s's `build/run.sh`, `make quick-release-images` for building the K8s stuff and then manipulates the node image by using Docker tech.

So it's probably easier to use a simple bash script, say `build-node-image.sh`, to replace such go code for the same effort and then we can focus more on the cool commands like `kind start`, `kind stop` etc.

What do you think?

**Why is this needed**:

The `kind build node-image` code brings in too much go code for wrapping a lot of bash scripts and command line logic.
It might be much easier to achieve the same by simply using a (set of) bash script file(s).

**Comment by BenTheElder** [comment]
Rewriting this would be the opposite of focusing on other commands 🙃

I've found bash to be very brittle for maintaining complex logic. If you take a closer look you'll find all of the logic is necessary.

building kubernetes from source and running it is kind's number one priority and reason for being created as a project.

Thanks for the suggestion though.
