### ISSUE TITLE
Weird interference with cluster that causes timeouts

### ISSUE THREAD

**Issue by koxu1996** [kubernetes-sigs/kind#1682]
**What happened**:

I have simple cluster with local registry. Invoking command such as `sudo -E kubectl get nodes` should not have any interference on cluster, but instead it makes it sluggish! It looks like there is some interference, but I cannot explain it easily - just see reproduction steps.

**Reproduction**:

1. Create `prepare.sh` (based on [docs](https://kind.sigs.k8s.io/docs/user/local-registry/#create-a-cluster-and-registry)) script that runs registry and creates cluster:
```
#!/bin/sh
set -o errexit

# create registry container unless it already exists
reg_name='kind-registry'
reg_port='5000'
running="$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)"
if [ "${running}" != 'true' ]; then
  docker run \
    -d --restart=always -p "${reg_port}:5000" --name "${reg_name}" \
    registry:2
fi

kind delete cluster || true
# create a cluster with the local registry enabled in containerd
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
    endpoint = ["http://${reg_name}:${reg_port}"]
EOF

# connect the registry to the cluster network
docker network connect "kind" "${reg_name}" || true
```

2. Let's try base scenario:
```
$ ./prepare.sh
$ kubectl get all
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   84s
```
Great, we got response!

3. This time we execute additional (independent) command before `kubectl get all`:
```
$ ./prepare.sh
$ sudo -E kubectl get nodes
NAME                 STATUS     ROLES    AGE   VERSION
kind-control-plane   NotReady   master   11s   v1.18.2
$ kubectl get all
I0621 13:28:04.049891  259883 request.go:621] Throttling request took 1.152423918s, request: GET:https://127.0.0.1:41997/apis/storage.k8s.io/v1?timeout=32s
I0621 13:28:14.247440  259883 request.go:621] Throttling request took 5.587039509s, request: GET:https://127.0.0.1:41997/apis/autoscaling/v2beta2?timeout=32s
I0621 13:28:24.447183  259883 request.go:621] Throttling request took 1.783129521s, request: GET:https://127.0.0.1:41997/apis/apiregistration.k8s.io/v1?timeout=32s
...
```
Now cluster responds with quite long delay :disappointed:

**Environment:**

- **KinD version:** 0.8.1
- **Kubernetes version:** client 1.18.3, server 1.18.2
- **Docker version:** 19.03.11-ce
- **OS:** Arch Linux (5.7.4-arch1-1)

**Comment by BenTheElder** [comment]
Your node is not ready yet, during bootstrap there are other API calls going on, what happens if you call this *after* the nodes are ready?

You can use the --wait flag to cluster creation to help with this.

The kind command exits before the cluster is fully ready because it is ready enough to do many things, but it is still somewhat busy coming up.

**Comment by BenTheElder** [comment]
Er call get all that is.

**Comment by koxu1996** [comment]
It does not matter if cluster is ready:
```
$ ./prepare.sh
$ # Now I wait for over minute
$ sudo -E kubectl get nodes
NAME                 STATUS   ROLES    AGE   VERSION
kind-control-plane   Ready    master   93s   v1.18.2
$ kubectl get all
I0622 06:26:38.134910    8613 request.go:621] Throttling request took 1.183675423s, request: GET:https://127.0.0.1:37497/apis/apiregistration.k8s.io/v1?timeout=32s
I0622 06:26:48.134924    8613 request.go:621] Throttling request took 4.188755402s, request: GET:https://127.0.0.1:37497/apis/authorization.k8s.io/v1?timeout=32s
...
```
---
If I call:
```
$ kubectl get nodes
$ sudo -E kubectl get nodes
$ kubectl get all
```
then cluster is responding immediately, but if command with _sudo_ is first:
```
$ sudo -E kubectl get nodes
$ kubectl get nodes
$ kubectl get all
```
then cluster is responding with timeouts for 'get all'.

**Comment by BenTheElder** [comment]
I see. That ... Doesn't make sense.
I'll try to reproduce this ...

Out of curiosity, why are you calling sudo kubectl?

**Comment by BenTheElder** [comment]
If I had to guess this has something to do with kubectl's caching mechanisms and nothing to do with kind.

**Comment by koxu1996** [comment]
I am using bootstrap script that requires root permission to perform filesystem mounts, so running _kubectl_ with root privileges is just side-effect.

---

You are right - running _kubectl_ with `sudo -E` makes cache files unreadable:
```
$ ls -Al ~/.kube/cache/discovery
total 4
drwxr-x--- 22 root   root   4096 Jun 22 08:46 127.0.0.1_37435
```
Running `chown` fixes timeouts:
```
$ kubectl get all                                                                                                                                                                                                                                                  
I0622 08:42:49.992386   28936 request.go:621] Throttling request took 1.196683247s, request: GET:https://127.0.0.1:45449/apis/admissionregistration.k8s.io/v1beta1?timeout=32s 
...
$ sudo chown -R andrew:users ~/.kube/cache/discovery/*
$ kubectl get all
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   3m31s
```
---
Closing as it is not KinD issue.

**Comment by koxu1996** [comment]
Related issue: https://github.com/kubernetes/kubernetes/issues/86462
> Working without a cache means most calls fully rediscover available APIs, which unsurprisingly has an impact on performance.
