### ISSUE TITLE
Make a Dockerfile to build the kind binary

### ISSUE THREAD

**Issue by zoobab** [kubernetes-sigs/kind#169]
Make a Dockerfile to build the kind binary.

**Comment by neolit123** [comment]
hi, is this a feature request or something you would like to work on?

**Comment by BenTheElder** [comment]
Building the kind binary is just "go build", I don't think we need to maintain a special dockerfile for this. We can just use the upstream go image to accomplish this.

**Comment by tao12345666333** [comment]
I also agree that we don't need to maintain a special dockerfile for this.

**Comment by BenTheElder** [comment]
`make` will do the equivilant go build using docker now.
