### ISSUE TITLE
Create an example of how to access a service using WSL2 on windows 10

### ISSUE THREAD

**Issue by stephane303** [kubernetes-sigs/kind#1695]
**What would you like to be documented**:
I used this article https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/ to start learning about Kubernetes.
I have created a service, but I do not understand how to access it using the expose command ( ip + port).

**Why is this needed**:
I have seen an issue about the subject that was never replied to, so I guess some clarifications are needed. 
The only workaround I thought about at the moment is to use the master node API, but I guess there is a better ways.
Thank you.
Related issue:
https://github.com/kubernetes-sigs/kind/issues/1654

**Comment by BenTheElder** [comment]
/help
/good-first-issue
Probably a good addition to
https://kind.sigs.k8s.io/docs/user/using-wsl2/

**Comment by kobayashi** [comment]
Hi, I would like to document for this if I have chance though, it seems to be in [KinD: Kubernetes made easy in a container](https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/#kind-kubernetes-made-easy-in-a-container). Should it be set the link in kind docs?

**Comment by BenTheElder** [comment]
I would love an entry in
https://kind.sigs.k8s.io/docs/user/using-wsl2/ covering
this aspect, the thing about kubernetes.io blogposts is that they're only
allowed to be touched for minor typos etc., they're not edited after
release, so we can't keep it up to date.

The sources for this are in site/content/docs/user/using-wsl2.md

**Comment by kobayashi** [comment]
Yeah, that must be better. I will make a PR for this later.
