### ISSUE TITLE
ERROR: failed to load image: command "docker exec --privileged -i kind-control-plane ctr --namespace=k8s.io images import -" failed with error: exit status 1

### ISSUE THREAD

**Issue by gitlijian** [kubernetes-sigs/kind#1704]
![image](https://user-images.githubusercontent.com/15320599/86568552-9e042b00-bf9f-11ea-80af-74dcd0f90c02.png)

**Comment by gitlijian** [comment]
I don't no this why? anyone can address the probelm?

**Comment by dims** [comment]
please open an issue with kubeedge folks.

/close
