### ISSUE TITLE
low kube-proxy sync period potentially causing iptables lock conflicts in CI

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#1707]
This used to have a 2s min by default in usptream but it was reverted in https://github.com/kubernetes/kubernetes/pull/36332

At some point the GCE clusters set 10s as their own "default" in the kube-up scripts.

Found by @aojea in https://github.com/kubernetes/kubernetes/pull/92811#issuecomment-654123052

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1706 to adjust in kind, discussing adjusting in kube-proxy or kubeadm upstream.

**Comment by BenTheElder** [comment]
also discussing with SIG Network about kube-proxy defaults upstream
/sig network

**Comment by BenTheElder** [comment]
We're not the only ones affected by this 

Per @danwinship 
> minSyncPeriod is mostly to deal with the problem where you have 100 updates all at once. With minSyncPeriod: 0, you run iptables-restore 100 times. With minSyncPeriod: 1s , you run iptables-restore once. With minSyncPeriod: 10s , you also run iptables-restore once, but you might have to wait 10 seconds first

We should mitigate this in kind across kubernetes versions but also look to get this changed in kubernetes and elsewhere.
it looks like kubespray has an explicit 0s default (?) and GKE / GCE have the 10s default.

**Comment by danwinship** [comment]
> This used to have a 2s min by default in usptream but it was reverted in [kubernetes/kubernetes#36332](https://github.com/kubernetes/kubernetes/pull/36332)

It seems like maybe that was because the original pre-`BoundedFrequencyRunner` implementation of `minSyncPeriod` was bad and ended up causing delays when it shouldn't have? (@thockin maybe you can confirm? I don't remember exactly what was wrong with the old code.)

**Comment by BenTheElder** [comment]
see also: https://github.com/kubernetes/kubernetes/pull/92860
