### ISSUE TITLE
ensure we do not do reverse dns lookups in iptables

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#1710]
see upstream kubernetes iptables library fix: https://github.com/kubernetes/kubernetes/pull/92860

a quick scan suggests this bug exists in https://github.com/coreos/go-iptables, which [images/kindnetd](https://github.com/kubernetes-sigs/kind/tree/master/images/kindnetd) and the CNI plugins use IIRC.

we'll probably want to push changes into go-iptables and then the cni plugins, and then get those picked up in kind

related issue: https://github.com/kubernetes-sigs/kind/issues/1707

**Comment by aojea** [comment]
I've checked it and seems that go-iptables is using `-n` 

https://github.com/coreos/go-iptables/blob/521ee6c1700638dc6444e0a9a7511ad3fd7d966a/iptables/iptables.go#L225

**Comment by BenTheElder** [comment]
For the Stats call yes, but not to just ListChains I beleive.

**Comment by BenTheElder** [comment]
OK it looks like the only `-L` / `--list [chain]` usage is the one linked above, which is the only call with `-n` available, and `-n` is used there to avoid DNS lookups.

**Comment by BenTheElder** [comment]
Having trouble finding anything authoritative on this but it appears only list has this behavior.
Once we can confirm that we can close this.

**Comment by BenTheElder** [comment]
spoke to @aojea out of band.
