### ISSUE TITLE
status "terminating" forever

### ISSUE THREAD

**Issue by ozbillwang** [kubernetes-sigs/kind#1714]
**What happened**:
when delete a pod, its status is terminating forever. 

```
➤ kubectl get all
NAME                          READY   STATUS        RESTARTS   AGE
pod/author-64d579698f-x9nxv   2/2     Terminating   0          4d17h
```
**What you expected to happen**:
the pod can be deleted
**How to reproduce it (as minimally and precisely as possible)**:
not sure how to.

I try to loing kind node container, but I don't see any docker containers running in it. 
So not sure if any way to manually terminate these pods.

**Anything else we need to know?**:

**Environment:**
latest v1.18.2
- kind version: (use `kind version`): 
```
kind v0.8.1 go1.14.2 darwin/amd64
```
- Kubernetes version: (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
```
➤ docker info
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 83
 Server Version: 19.03.8
```
- OS (e.g. from `/etc/os-release`):
MacOS

**Comment by BenTheElder** [comment]
I need to know more about your pod.
As it stands we can't tell what's happening and this isn't a reproducible issue.

Can you get the pod with -oyaml?

**Comment by BenTheElder** [comment]
The kind nodes run containerd not docker. You can see the pods with crictl, or the containers with ctr.

**Comment by ozbillwang** [comment]
Thanks, @BenTheElder 

I should keep the environment, but I just delete and re-create the kind cluster. I can't re-product this problem any more. 

If I see the issue again, will re-open this issue.

**Comment by BenTheElder** [comment]
thanks, if you do see this again we'll want at least the events for the pod and the pod spec
