### ISSUE TITLE
Expanding the volume faild

### ISSUE THREAD

**Issue by blafry** [kubernetes-sigs/kind#1716]
**What happened**:

I tried to resize the pvc size:

```kubectl patch pvc data-consul-0 -p '{"spec":{"resources":{"requests":{"storage":"200Mi"}}}}'```

and got warning:

```Name:          data-consul-0
Namespace:     default
StorageClass:  standard
Status:        Bound
Volume:        pvc-3a7efc3e-706e-486f-9684-07c0409669de
Labels:        app=consul
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
               volume.kubernetes.io/selected-node: kind-control-plane
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Mi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    minikube-consul-0
Events:
  Type     Reason             Age   From           Message
  ----     ------             ----  ----           -------
  Warning  ExternalExpanding  12m   volume_expand  Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.waiting for an external controller to process this PVC.
```
although used StorageClass `standard` has set  `AllowVolumeExpansion:  True`

```kubectl describe sc standard
Name:            standard
IsDefaultClass:  Yes
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"standard"},"provisioner":"rancher.io/local-path","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
,storageclass.kubernetes.io/is-default-class=true
Provisioner:           rancher.io/local-path
Parameters:            <none>
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     WaitForFirstConsumer
Events:                <none>
```
**What you expected to happen**:

PVC size changed.

**How to reproduce it (as minimally and precisely as possible)**:

Try to change requested storage of pvc.

**Environment:**

- kind version: `v0.8.0 go1.14.2 linux/amd64`
- Kubernetes version: `v1.18.2`
- Docker version: `19.03.9`
- OS : `Debian GNU/Linux 10 (buster)`

**Comment by BenTheElder** [comment]
The default driver is https://github.com/rancher/local-path-provisioner which enforces no limits and cannot be expanded.

**Comment by chrislovecnm** [comment]
/reopen

@BenTheElder can we use a different volume provider?

**Comment by BenTheElder** [comment]
You could install your own if you find one that works, and if that works well we'd be happy to consider switching. But we don't currently have the bandwidth to run our own and suggest contributing to the existing provisioner.

**Comment by BenTheElder** [comment]
In general provisioners that support expanding seem to be using disks in the cloud or some other virtualization platform, which isn't really something we can ship.
