### ISSUE TITLE
How do I google for issues around this project?

### ISSUE THREAD

**Issue by amirdt22** [kubernetes-sigs/kind#1724]
Is there a convention for searching for issues around this project?  The name `kind` is extremely confusing and I have to tack on kubernetes to try to find the right information as opposed to someone talking about a "kind of _____".

**Comment by BenTheElder** [comment]
"kubernetes kind"

Also we maintain our own documentation which includes a resources page with external links to third party resources.

You can search the issue tracker for previous discussion.
