### ISSUE TITLE
kind create cluster failing

### ISSUE THREAD

**Issue by felixtran39** [kubernetes-sigs/kind#1730]
**What happened**:
Trying to call `kind create cluster` and it fails at the `Writing configuration` step. Here is the error message:
`ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 126`

**What you expected to happen**:
Successfully create a cluster when calling `kind create cluster`.

**How to reproduce it (as minimally and precisely as possible)**:
All I did was download kind (via `gcloud components install kind`) and then run `kind create cluster`.

**Anything else we need to know?**:
I ran with `-v 1` flag and got this:

```
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "process_linux.go:101: executing setns process caused \"exit status 1\"": unknown

Stack Trace: 
sigs.k8s.io/kind/pkg/errors.WithStack
        /src/pkg/errors/errors.go:51
sigs.k8s.io/kind/pkg/exec.(*LocalCmd).Run
        /src/pkg/exec/local.go:116
sigs.k8s.io/kind/pkg/cluster/internal/providers/docker.(*nodeCmd).Run
        /src/pkg/cluster/internal/providers/docker/node.go:130
sigs.k8s.io/kind/pkg/exec.CombinedOutputLines
        /src/pkg/exec/helpers.go:67
sigs.k8s.io/kind/pkg/cluster/nodeutils.KubeVersion
        /src/pkg/cluster/nodeutils/util.go:58
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.getKubeadmConfig
        /src/pkg/cluster/internal/create/actions/config/config.go:172
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.(*Action).Execute.func1.1
        /src/pkg/cluster/internal/create/actions/config/config.go:84
sigs.k8s.io/kind/pkg/errors.UntilErrorConcurrent.func1
        /src/pkg/errors/concurrent.go:30
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```
When calling `docker exec --privileged kind-control-plane cat /kind/version`, I get 
`Error: No such container: kind-control-plane`

**Environment:**

- kind version: (use `kind version`): kind v0.7.0 go1.13.6 linux/amd64
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-dispatcher", GitCommit:"f2a77f678d6baccda27740d700f6cba2754dfacf", GitTreeState:"clean", BuildDate:"2020-04-21T04:42:07Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.15", GitCommit:"8ce551a0c972a9f113e326df0537aa3f1798d93e", GitTreeState:"clean", BuildDate:"2020-05-05T18:38:03Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`): 19.03.12
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 10 (buster)

**Comment by BenTheElder** [comment]
> OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "process_linux.go:101: executing setns process caused \"exit status 1\"": unknown

this is a failure in docker / runc

can you tell me more about your environment?

an yreason to not use the latest kind release?

**Comment by BenTheElder** [comment]
This means we can't `docker exec` into the node container from the host. Probably your docker environment has a bug.

can you share `docker info`?

**Comment by BenTheElder** [comment]
https://github.com/opencontainers/runc/issues/1740
https://github.com/moby/moby/issues/40399

It appears this usually happens due to running out of memory, it can also happen with `userns-remap` enabled https://github.com/moby/moby/issues/31037, there seem to be a number of reasons.

https://github.com/moby/moby/issues/25929

they're not related to anything kind is doing though

**Comment by felixtran39** [comment]
Thank you for the replies. I am using Crostini and apparently that has issues with Docker so that seems to be why this error was happening.
