### ISSUE TITLE
Podman: json: cannot unmarshal object into Go value of type []podman.portMapping

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes-sigs/kind#1734]
**What happened**:

```
$ sudo KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.4) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾
ERROR: failed to create cluster: invalid network details: json: cannot unmarshal object into Go value of type []podman.portMapping
```

**What you expected to happen**:

Should work

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): v0.9.0-alpha (c9469c692b05baee85d27984f23670a1c9b68ff6)
- Podman version: containers/podman@c4843d4e9ce395f1bbcaae848e6172f5a4519a35  + https://github.com/containers/podman/pull/6949
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by AkihiroSuda** [comment]
seems being fixed in https://github.com/kubernetes-sigs/kind/pull/1728

**Comment by BenTheElder** [comment]
This is a podman breakage imho, dealing with networking in podman has been .. frustrating.

**Comment by giuseppe** [comment]
fixed by https://github.com/kubernetes-sigs/kind/pull/1728

**Comment by giuseppe** [comment]
we can close this issue (I've no privileges for doing it)

**Comment by AkihiroSuda** [comment]
Thanks!
