### ISSUE TITLE
Images node's README file contains a broken link

### ISSUE THREAD

**Issue by Cepxio** [kubernetes-sigs/kind#1742]
**What would you like to be documented**:
The README file contains a link to the 
https://github.com/kubernetes-sigs/kind/blob/master/pkg/build/node/node.go and that file doesn't exist

It seems that the directory layout has changed in the repository

```
mylaptop:~/github/kind (master)$ find . -name node.go
./pkg/cluster/internal/providers/podman/node.go
./pkg/cluster/internal/providers/docker/node.go
mylaptop:~/github/kind (master)$
```

**Why is this needed**:

To improve the code documentation.

**Comment by BenTheElder** [comment]
That documentation is part of the initial design, it is NOT the current design.
We should clarify that and archive it.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1796 fixed by @izzyleung 🙏
