### ISSUE TITLE
Accessing kubernetes API from another machine in the local lan

### ISSUE THREAD

**Issue by UlTriX** [kubernetes-sigs/kind#1743]
I am setting up a kind cluster with 

apiServerAddress: "0.0.0.0"
apiServerPort: 6443

Trying to connect to it from another machine in the local network but getting 

X509: certificate is valid for 10.96.0.1 ... not 192.168.1.99 (machine where the kind cluster is running)

How should I setup ?

Tried setting apiServerAddress: "192.168.1.99" but still not working. I am on Mac OS X 

Thank you

**Comment by BenTheElder** [comment]
If you put 0.0.0.0 we don't know what addresses to tell kubernetes to sign the certs for.

> Tried setting apiServerAddress: "192.168.1.99" but still not working. I am on Mac OS X

what failed in this case?

Possibly https://github.com/kubernetes-sigs/kind/issues/1732 ?

**Comment by UlTriX** [comment]
Thank you for the quick reply. 

Indeed setting the ip to 192.168.1.99 results in the kind control pane with 127.0.0.1 and a random port although I am setting one in the configuration file. 

Any workarounds ?

**Comment by BenTheElder** [comment]
I think it should work fine if you set the address in the config file as
mentioned in the other issue.
The port and IP are still there, just not where kind can see it.

**Comment by BenTheElder** [comment]
/triage duplicate
https://github.com/kubernetes-sigs/kind/issues/1732
