### ISSUE TITLE
Kube scheduler

### ISSUE THREAD

**Issue by srini1978** [kubernetes-sigs/kind#1754]
i have installed kind on local kubernetes cluster. i would like to extend the scheduler and was wondering what is the command in kind to do that

**Comment by BenTheElder** [comment]
I'm not sure what you mean by extend.

If you mean make changes to the scheduler source code and then running those, see https://kind.sigs.k8s.io/docs/user/quick-start/#building-images

**Comment by srini1978** [comment]
I am planning to extend the default kind scheduler by using the concept like https://developer.ibm.com/technologies/containers/articles/creating-a-custom-kube-scheduler.

However for doing that ineed to replace the scheduler pod yaml inside kind-control-plane container at path /etc/kubernetes/manifests. In the kind deployment that i have done on my ubuntu box, how can i find this scheduler pod yaml.

**Comment by BenTheElder** [comment]
you can get inside the node the same as any other docker container e.g. via docker exec.

The paths are standard kubeadm paths.

**Comment by BenTheElder** [comment]
see: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
