### ISSUE TITLE
failed to "docker exec --privileged kind-control-plane cat /kind/version" when kind create cluster

### ISSUE THREAD

**Issue by Thor-wl** [kubernetes-sigs/kind#1759]
**What happened**:
according to quick start, i tried three ways to create my cluster, but got the same error:
 `
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.6) 🖼
 ✓ Preparing nodes 📦  
 ✗ Writing configuration 📜 
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 1
Command Output: Error response from daemon: Container 5118aa6d69fec531f278229032650318ef6453d71acf6630e10711072bc9f10a is not running

`
my three tries:
1.  go get sigs.k8s.io/kind@v0.8.1 && kind create cluster
2. curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-arm64  && chmod +x ./kind && mv ./kind /some-dir-in-your-PATH/kind
3. git clone && make build

I'm sure i have built kind successfully. And my os arch is arm64. I've installed kind successfully on x86
 
**What you expected to happen**:
kind create cluster works
**How to reproduce it (as minimally and precisely as possible)**:
do as the quick start
**Anything else we need to know?**:
my kind version choice : v0.8.1(https://github.com/kubernetes-sigs/kind/releases/download/v0.8.1/kind-linux-arm64)
**Environment:**
CentOS 7.6 on arm64
- kind version: (use `kind version`): v0.8.1
- Kubernetes version: (use `kubectl version`): v1.5.2
- Docker version: (use `docker info`): v1.13.1
- OS (e.g. from `/etc/os-release`): CentOS 7.6 on arm64

**Comment by Thor-wl** [comment]
I tried v0.6.1 but got the same error

**Comment by BenTheElder** [comment]
Arm node images are not built by default yet. You'll have to build one.

See the existing issues in the tracker about arm.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.0#contributors this is out now.

**Comment by Thor-wl** [comment]
That's great! Thanks.
