### ISSUE TITLE
Also stuck at "Starting control-plane" with http proxy

### ISSUE THREAD

**Issue by fzyzcjy** [kubernetes-sigs/kind#1773]
**What happened**:
When running `kind start cluster`, it stucks at "Starting control-plane" if I use proxy.

**What you expected to happen**:
Start normally!

**How to reproduce it (as minimally and precisely as possible)**:

**NOTE**: If running without proxy, then it starts normally! (i.e. if I do `unset http_proxy; unset https_proxy; unset no_proxy; unset HTTP_PROXY; unset HTTPS_PROXY; unset NO_PROXY;` then it starts normally)

```
export http_proxy="http://192.168.0.103:10080"; export https_proxy="http://192.168.0.103:10080"; export no_proxy="localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24,172.17.0.0/24,192.168.64.0/24,172.17.0.0/16,192.168.65.0/24"; export HTTP_PROXY=$http_proxy; export HTTPS_PROXY=$https_proxy; export NO_PROXY=$no_proxy;
kind create cluster
```

p.s. my docker subnet is "192.168.65.0/24".

**Anything else we need to know?**:
N/A

**Environment:**

- kind version: (use `kind version`): kind v0.8.1 go1.14.4 darwin/amd64
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
- Docker version: (use `docker info`): (below)
- OS (e.g. from `/etc/os-release`): macos

```
Client:
 Debug Mode: false

Server:
 Containers: 48
  Running: 1
  Paused: 0
  Stopped: 47
 Images: 59
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 23.49GiB
 Name: docker-desktop
 ID: KUWF:46LT:2EZ6:RIBQ:HKXT:BLQR:RJMD:7W6X:TRXF:U57B:PMXS:EH7N
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 48
  Goroutines: 66
  System Time: 2020-08-08T02:08:35.365492455Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

p.s. I have read https://github.com/kubernetes-sigs/kind/issues/440 but after trying still cannot fix it.

**Comment by BenTheElder** [comment]
roll back to 0.7.X or use kind from the latest source code at HEAD, you can clone the repo and `make build` and then the binary will be at `bin/kind`

**Comment by fzyzcjy** [comment]
@BenTheElder Sorry I am a little bit confused. Is it a bug know to be in 0.8.x?

**Comment by BenTheElder** [comment]
yes, 0.8.X fails to insert enough things into NO_PROXY

**Comment by fzyzcjy** [comment]
Ah so sad :( Can I manually add things to NO_PROXY?

p.s. will I have problems using 0.7.0? it is a bit old

**Comment by BenTheElder** [comment]
you can, I forget which things you need though. if you look through the
past issues you should be able to find the patch.
or you can just install from the latest code.

you shouldn't have proxy issues with the latest release before 0.8

**Comment by fzyzcjy** [comment]
Thanks very much! Could you please suggest keywords to search? By the way, when using Google, which keyword do you suggest me to use - since "kind" will often lead to other things instead of this k8s in docker

**Comment by BenTheElder** [comment]
"kubernetes kind"
I don't recommend searching on google for this though, the issue will be in
this repo, which has native search.
Similarly documentation is linked from the repo. You should be able to find
everything from here.

**Comment by fzyzcjy** [comment]
Thanks very much! Running 0.7 works for me
