### ISSUE TITLE
Where is the "docker" executable inside the kind node?

### ISSUE THREAD

**Issue by fzyzcjy** [kubernetes-sigs/kind#1774]
I enter the kind node by `docker exec -it $(docker ps -aqf "name=kind-control-plane") /bin/bash`. However, I cannot run `docker`, neither can I run `/bin/docker` etc. I just want to examine those docker images/containers/etc inside the node.

p.s. I see a big "docker" in the figure in https://kind.sigs.k8s.io/docs/design/initial/, but I cannot find it :/

Thanks!

**Comment by BenTheElder** [comment]
Docker was in the initial design. It is not in the current design. The nodes run containerd.

In the resources page there are some kubecon talks, in those some of the changes are discussed.

**Comment by BenTheElder** [comment]
You should use crictl

**Comment by fzyzcjy** [comment]
Thanks!
