### ISSUE TITLE
Document how to enable NFS volume mounts

### ISSUE THREAD

**Issue by qlyoung** [kubernetes-sigs/kind#1806]
**What would you like to be documented**:

By default NFS volumes don't work in a standard kind cluster because the node image doesn't have the `nfs-common` package installed to provide support for the `nfs` fs, causing a mount failure:
```
Events:
  Type     Reason       Age                   From                         Message
  ----     ------       ----                  ----                         -------
  Warning  FailedMount  11m (x25 over 80m)    kubelet, kind-control-plane  Unable to attach or mount volumes: unmounted volumes=[nfsvol], unattached volumes=[nfsvol default-token-44d5q]: timed out waiting for the condition
  Warning  FailedMount  6m48s (x43 over 80m)  kubelet, kind-control-plane  (combined from similar events): MountVolume.SetUp failed for volume "nfs" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/e7aaeeb7-ebda-4632-b502-ad88784ddbd3/volumes/kubernetes.io~nfs/nfs --scope -- mount -t nfs nicobar:/opt/mymount /var/lib/kubelet/pods/e7aaeeb7-ebda-4632-b502-ad88784ddbd3/volumes/kubernetes.io~nfs/nfs
Output: Running scope as unit: run-r47f19381963a43ddaf0bdb39e45aa3c7.scope
mount: /var/lib/kubelet/pods/e7aaeeb7-ebda-4632-b502-ad88784ddbd3/volumes/kubernetes.io~nfs/nfs: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
```

After installing `nfs-common` by manually logging into the node with `docker exec -it <kind-node> sh; apt update; apt install nfs-common` this problem resolved.

**Why is this needed**:
I think this should be documented. Alternatively, the `nfs-common` package could be added to make this work out of the box.

**Comment by BenTheElder** [comment]
It's installed by default at HEAD already. It will be in the next release.

It was not installed previously because it would not have worked. The kernel has improved.

**Comment by BenTheElder** [comment]
This will be in v0.9.0, see previous discussion in https://github.com/kubernetes-sigs/kind/issues/1487

**Comment by qlyoung** [comment]
Excellent, thanks!

**Comment by BenTheElder** [comment]
> It did work for me shrug

Right, see the next sentence -- NFS on overlay didn't work when we started developing kind. The thing that was fixed was the linux kernel, not kind. Now we can ship it because people are running fixed kernels these days (the fix didn't even exist then, but it's widely available now) :upside_down_face:

**Comment by qlyoung** [comment]
ACK. Thanks!
