### ISSUE TITLE
google cloud shell support

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/kind#182]
```
$ go get sigs.k8s.io/kind
...
$ kind create cluster
Creating cluster 'kind-1' ...
 ✓ Ensuring node image (kindest/node:v1.12.3) 🖼
 ✓ [kind-1-control-plane] Creating node container 📦
 ✓ [kind-1-control-plane] Fixing mounts 🗻
 ✓ [kind-1-control-plane] Starting systemd 🖥
 ✓ [kind-1-control-plane] Waiting for docker to be ready 🐋
 ✗ [kind-1-control-plane] Starting Kubernetes (this may take a minute) ☸
Error: failed to create cluster: failed to apply overlay network: exit status 1
Usage:
  kind create cluster [flags]
Flags:
      --config string   path to a kind config file
  -h, --help            help for cluster
      --image string    node docker image to use for booting the cluster
      --name string     cluster context name (default "1")
      --retain          retain nodes for debugging when cluster creation fails
      --wait duration   Wait for control plane node to be ready (default 0s)
Global Flags:
      --loglevel string   logrus log level [panic, fatal, error, warning, info, debug] (default "warning")
failed to create cluster: failed to apply overlay network: exit status 1
```

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/182 is one of the blockers, there also appears to be something strange with the networking.

This _almost_ works, something is wrong with talking to the API server, will need to investigate further.
```console
$ cat ./kind-config.yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
networking:
  apiServerPort: 6443
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /sys/class/dmi/id/product_name
    hostPath: /home/bentheelder/product_name

$  cat ./product_name
kind

$ kind create cluster --config=./kind-config.yaml --loglevel=debug

```

**Comment by BenTheElder** [comment]
I _think_ the web preview feature interferes. https://cloud.google.com/shell/docs/features#web_preview

It should be possible to stick to lower ports for the API server etc. which _might_ fix that, but this will require changes to kind.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/426 was fixed, but there's still some funky networking blocking this.

**Comment by aojea** [comment]
@BenTheElder you can define the port range in the host, it's defined in the kernel in
`/proc/sys/net/ipv4/ip_local_port_range`

**Comment by BenTheElder** [comment]
In Google cloud shell?
Pretty sure https://cloud.google.com/shell/docs/features#web_preview is the
issue.

*From:*Antonio Ojea <notifications@github.com>
*Date:*Fri, May 3, 2019, 05:46
*To:*kubernetes-sigs/kind
*Cc:*Benjamin Elder, Mention

@BenTheElder <https://github.com/BenTheElder> you can define the port range

**Comment by aojea** [comment]
It's working for me running from https://console.cloud.google.com/cloudshell , but don't know if this is the same situation you are describing 😅 
```
antonio_ojea_garcia@cloudshell:~ (agile-sprite-239512)$ go get sigs.k8s.io/kind
antonio_ojea_garcia@cloudshell:~ (agile-sprite-239512)$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.14.1) 🖼
 ✓ Preparing nodes 📦
export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
kubectl cluster-info
antonio_ojea_garcia@cloudshell:~ (agile-sprite-239512)$ export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
antonio_ojea_garcia@cloudshell:~ (agile-sprite-239512)$ kubectl get nodes
NAME                 STATUS     ROLES    AGE   VERSION
kind-control-plane   NotReady   master   25s   v1.14.1
antonio_ojea_garcia@cloudshell:~ (agile-sprite-239512)$ kubectl get nodes -o wide
NAME                 STATUS     ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                  KERNEL-VERSION   CONTAINER-RUNTIME
kind-control-plane   NotReady   master   29s   v1.14.1   172.18.0.2    <none>        Ubuntu Disco Dingo (development branch)   4.14.104+        containerd://1.2.6-0ubuntu1
```
The port forwarded is within the allowed range (2000 to 65000) 
```
antonio_ojea_garcia@cloudshell:~ (agile-sprite-239512)$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS              PORTS                                  NAMES
c6d2f3edda33        kindest/node:v1.14.1   "/usr/local/bin/entr…"   About a minute ago   Up About a minute   38797/tcp, 127.0.0.1:38797->6443/tcp   kind-control-plane
```
And the port range defined is within the webshell range (2000 to 65000) too
```
antonio_ojea_garcia@cloudshell:~ (agile-sprite-239512)$ cat /proc/sys/net/ipv4/ip_local_port_range
32768   60999
```

**Comment by BenTheElder** [comment]
Did your node ever go to ready though? Testing this...

**Comment by BenTheElder** [comment]
I observe an issue dialing the CRI socket, only some of the static pods come up. not sure why, but overall this not working quite right is not surprising. `cat /proc/1/cgroup` :wink:

**Comment by aojea** [comment]
hehe, s/working/runs without errors/ 
definitively it needs more testing

**Comment by BenTheElder** [comment]
did a little more poking, something is killing containerd :thinking:

**Comment by BenTheElder** [comment]
it's not clear to me that this is clearly feasible or that any similar tool works there.

it would be neat, but I don't think we have the time.

if anyone is interested in the future feel free to try again and report back / file a new issue

**Comment by sirdarckcat** [comment]
fyi https://github.com/kubernetes/minikube/issues/6404 got it working

**Comment by aojea** [comment]
I think that this may fix it https://github.com/kubernetes-sigs/kind/pull/1995

**Comment by BenTheElder** [comment]
This is indeed fixed at HEAD, and will work in the next release (soon!), you can test it now by running the following from your cloudshell:

```console
GO111MODULE=on go get sigs.k8s.io/kind@master
export PATH="${HOME}/gopath/bin:${PATH}"
kind create cluster
```

**Comment by BenTheElder** [comment]
thanks @aojea @sirdarckcat :-)

**Comment by BenTheElder** [comment]
<img width="808" alt="Screen Shot 2021-01-19 at 9 04 02 PM" src="https://user-images.githubusercontent.com/917931/105129419-e1d10480-5a99-11eb-93ff-e6a61a45a903.png">
