### ISSUE TITLE
no_proxy should include the control-plane node ip and host name automatically when using with proxy.

### ISSUE THREAD

**Issue by cadmuxe** [kubernetes-sigs/kind#1821]
**What happened**:
When running bind of a proxy and configed the proxy with 
https_proxy=...
no_proxy=localhost,127.0.0.1

kind creation failed with control plan not reachable error
Retry failed:
I0826 22:25:43.038354     157 round_trippers.go:443] GET https://testing-control-plane:6443/healthz?timeout=10s  in 1 milliseconds

++
update the no_proxy to no_proxy=localhost,127.0.0.1,testing-control-plane
kind is able to create the cluster.
But the kubectl can't list log/exec into pods.
++
update the no_proxy to no_proxy=localhost,127.0.0.1,testing-control-plane,${testing-control-plane-NODE-IP}
Everything works again.
[Adding the Docker "kind" network subnet to no_proxy also works.]

**What you expected to happen**:
1) kind should automatically add the control-plane hostname and IP to the no_proxy list.

**How to reproduce it (as minimally and precisely as possible)**:
with kind 0.8.1 config as described above.

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):  kind v0.8.1 go1.14.4 linux/amd64
- Docker version: (use `docker info`):  Server Version: 19.03.12
- OS (e.g. from `/etc/os-release`): Red Hat Enterprise Linux 8.2

**Comment by cadmuxe** [comment]
@BenTheElder

**Comment by BenTheElder** [comment]
should already be fixed at HEAD, hoping to get a release out today but hitting some hiccups

can you test HEAD? just checkout the repo and `make install` if you have GOPATH/bin in $PATH, or use `make build` and copy `bin/kind` into path.

you can also just `go install .` if you have go but that misses a few nice things we do (like embed commit)

**Comment by BenTheElder** [comment]
https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64 as well

**Comment by cadmuxe** [comment]
Thank you Benjamin, I have tested the fix. Creation and logs are working well and it also automatically included .svc etc.

**Comment by cadmuxe** [comment]
Fixed at: https://github.com/kubernetes-sigs/kind/blob/63701f33ef2c64509c89be9b512a92b2e3a57294/pkg/cluster/internal/providers/docker/provision.go#L286
