### ISSUE TITLE
kindnet support for preserving source ip with externalTrafficPolicy: Local

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/kind#1830]
**What would you like to be added**:

kindnet support for preserving source ip with externalTrafficPolicy: Local
 
Currently when using a Service of type: LoadBalancer with externalTrafficPolicy: Local, the client requests are NAT'd, not preserving the source IP, it would be great if kindnet supported preserving the source IP in this case as it would prevent the need to deploy an alternative CNI for applications that require the sourceIP to be preserved to function.

I suspect what is needed is a way to bypass KIND-MASQ-AGENT, when adding a rule for a service of type: LoadBalancer with externalTrafficPolicy: Local. I suspect this would require changes to both the static rules added by kindnet in https://github.com/kubernetes-sigs/kind/blob/8d02d178ca95f58e169f0f5789b318831eab014f/images/kindnetd/cmd/kindnetd/masq.go as well as 
**Why is this needed**:

Testing applications that require the sourceIP to be preserved today require disabling kindnet and installing an alternative CNI solution, with support for this it would be possible to test these types of applications in kind without needing an alternative CNI.

**Comment by aojea** [comment]
/assign

I really want to check this carefully, there are several components playing with the masquerading here, kube-proxy too.

@detiber can we uniquely identify the source ip range from the request? i.e. it always come from a VM/container attached to the kind network

**Comment by detiber** [comment]
@aojea I think I've ruled out kindnet as the issue at play

/close
