### ISSUE TITLE
Changed behavior between releases - kubeconfig server returns DNS name instead of IP

### ISSUE THREAD

**Issue by pst** [kubernetes-sigs/kind#1835]
I'm seeing some changed behavior regarding the server attribute in the kubeconfig. Previously it was set to an IP but is now set to a DNS name. This DNS name however is not resolvable on my machine.

Please note, I'm not using KinD directly here, but instead through the terraform-provider-kind. Here's a link to the original issue: https://github.com/kyma-incubator/terraform-provider-kind/issues/20

The Terrraform provider uses [`provider.KubeConfig`](https://github.com/kubernetes-sigs/kind/blob/master/pkg/cluster/provider.go#L159) with internal set to true. Since there seems no change in either the provider's nor kind's code base regarding this feature I am looking for help where to look next or optimally how to restore the previous behavior.

I'd be grateful for any pointers.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.0#breaking-changes

this changed in v0.8+

using IP is not recommended, it's not stable across restarts.

accessing the cluster from the host should not use the internal kubeconfig, it should use the external kubeconfig

**Comment by BenTheElder** [comment]
Basically the internal IP happening to work on your host was a happy accident and not portable to not-linux to begin with.

You can still reach nodes on this IP unless they are rebooted. It can be accomplished with a shell one-liner getting the node IP from kubernetes and `sed`ing the server line. Restart / reboot will break it though.

The non-internal kubeconfig for use from the host machine will work across reboots as it uses a docker port forward, and works across operating systems. The internal kubeconfig is meant for use from within containers on the matching docker network.

**Comment by pst** [comment]
Thanks for the background Ben, so that means the second parameter for `provider.KubeConfig` should be `false` instead of `true` to get the external config, in which case it would produce the same as `provider.ExportKubeConfig` (the config written to the file works - although it uses an IP for me).

I was so sure I tried calling `provider.KubeConfig` with `false` before opening this ticket. But I suppose I must have made some mistake somehow. Will close for now. Thanks for your help.
