### ISSUE TITLE
Support for Jenkins

### ISSUE THREAD

**Issue by mjwilkerson-strateos** [kubernetes-sigs/kind#1837]
I was able to attend the Kind presentation at Kubecon. After looking at the repo I see that Jenkins is not listed as a supported CI system. Are there any plans to add Jenkins?

Thank you

**Comment by BenTheElder** [comment]
Hi, we don't "support" any particular CI in KIND at all, kind is supported wherever a reasonable docker environment exists (see the [known issues page](https://kind.sigs.k8s.io/docs/user/known-issues/) for known broken environments etc.)

We do however have a community supported set of examples for usage in various CI here https://github.com/kind-ci/examples

I don't think Jenkins would be particularly special here.
Hope that helps!

**Comment by mjwilkerson-strateos** [comment]
Thank you....
