### ISSUE TITLE
not able to create multiple cluster with kind

### ISSUE THREAD

**Issue by siddhant3030** [kubernetes-sigs/kind#1840]
System: Mac

I just started using kind for my local cluster. Minikube I was using earlier but I wanted which can spin-up fast and destroy. So I started using this.
But one of the main reasons is I wanted to create another cluster but somehow when I'm trying to install another cluster then It just deletes the previous cluster it has and installs the new one. I don't know how to debug this. 

Is there anything I'm doing wrong?

**Comment by BenTheElder** [comment]
kind absolutely supports multiple clusters. we use it extensively.

> But one of the main reasons is I wanted to create another cluster but somehow when I'm trying to install another cluster then It just deletes the previous cluster it has and installs the new one. I don't know how to debug this.

kind only deletes clusters when you ask it to. (`kind delete cluster`) and won't allow creating a cluster that already has resources.

`kind create cluster --name=foo` will create a `foo` cluster. the default is `kind`

to use a different cluster you can use `--context` with kubectl. the output of `kind create cluster` shows this:
```console
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.8) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋
```

this part:
> kubectl cluster-info --context kind-kind

the `kind-kind` context in kubeconfig is the kind cluster named kind
all kind contexts are `kind-`

you can `kubectl config set-context kind-foo` to switch to kind-foo by default, or use the `--context` flag everywhere.

**Comment by siddhant3030** [comment]
@BenTheElder Thanks for the comment. I have a couple of questions here

1. Shouldn't kubectl get nodes to list down all the nodes available because right now it's showing only one node which is running. 

I think it's confused me with this command - kind get clusters
 which is showing all the available cluster

**Comment by BenTheElder** [comment]
> Shouldn't kubectl get nodes to list down all the nodes available because right now it's showing only one node which is running.

`kubectl` talks to a single kubernetes cluster at a time via the cluster's API server. the default kind cluster configuration only has a single node (and I generally recommend that unless you have a good reason for using multiple nodes)

so `kubectl get nodes` is listing the node objects in the cluster's API.

`kind get nodes` does something similar, but without using the kubernetes API.

`kind get clusters` lists the clusters at the kind level. to talk to each of these you set `kubectl --context=kind-${cluster_name}`
so if kind get clusters gives you:
```
test1
test2
```

you can `kubectl --context=kind-test1 get nodes` and `kubectl --context=kind-test2 get nodes`

**Comment by BenTheElder** [comment]
https://kind.sigs.k8s.io/docs/user/quick-start/#creating-a-cluster
and more specifically:
https://kind.sigs.k8s.io/docs/user/quick-start/#interacting-with-your-cluster
cover this a bit.

**Comment by BenTheElder** [comment]
In addition I neglected to specify above: Whenever you create a cluster the default kubectl context points to that cluster (most / nearly all tools do this) but you other cluster is still there, and you can change the default context back with `kubectl config set-context` as mentioned before. The context name is in the sample command in the output of creating the cluster.

**Comment by BenTheElder** [comment]
You can also manage multiple clusters by using multiple kubeconfig files, by settting `KUBECONFIG` env or the `--kubeconfig` flag to most tools, we talk a bit about this in https://kind.sigs.k8s.io/docs/user/quick-start/#interacting-with-your-cluster

**Comment by siddhant3030** [comment]
Thanks. I will close this issue now.
