### ISSUE TITLE
coreDNS pods failing with CrashLoopBackOff when using kindest/node:v1.16.3

### ISSUE THREAD

**Issue by mszacillo** [kubernetes-sigs/kind#1845]
**What happened**:
I ran the following command to create a cluster:

```
kind create cluster --image kindest/node:v1.16.3@sha256:bced4bc71380b59873ea3917afe9fb35b00e174d22f50c7cab9188eac2b0fb88
```
But I'm noticing that both of the coredns pods are failing with a CrashLoopBackOff:
```
NAME                                         READY   STATUS             RESTARTS   AGE
coredns-5644d7b6d9-ct5kf                     0/1     CrashLoopBackOff   13         46m
coredns-5644d7b6d9-xxdr6                     0/1     CrashLoopBackOff   13         46m
etcd-kind-control-plane                      1/1     Running            0          45m
kindnet-8nt4z                                1/1     Running            0          46m
kube-apiserver-kind-control-plane            1/1     Running            0          46m
kube-controller-manager-kind-control-plane   1/1     Running            0          46m
kube-proxy-x8tc4                             1/1     Running            0          46m
kube-scheduler-kind-control-plane            1/1     Running            0          46m
```
Looking at the logs I see:
```
ACCEPTFLATHELP:etc michael.szacillo$ kubectl -n kube-system logs coredns-5644d7b6d9-ct5kf
.:53
2020-09-11T16:13:34.241Z [INFO] plugin/reload: Running configuration MD5 = f64cb9b977c7dfca58c4fab108535a76
2020-09-11T16:13:34.241Z [INFO] CoreDNS-1.6.2
2020-09-11T16:13:34.241Z [INFO] linux/amd64, go1.12.8, 795a3eb
CoreDNS-1.6.2
linux/amd64, go1.12.8, 795a3eb
2020-09-11T16:13:34.242Z [FATAL] plugin/loop: Loop (127.0.0.1:34451 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 1731097407885672313.5114597377825910527."
```
Here is the coredns configmap:
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-11T15:09:25Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "169"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: ea41513d-4c0a-41ae-9158-4afbb4bc9eb1
```

**What you expected to happen**:
I expect the coredns pods to pass their readiness checks without a CrashLoopBackOff.

**How to reproduce it (as minimally and precisely as possible)**:
I haven't been able to reproduce this precisely besides running `kind create cluster`.

**Anything else we need to know?**:
I've tried a couple methods of troubleshooting but haven't had any luck in resolving the problem.

1. Double checked that localhost wasn't being set as a nameserver in /etc/resolv.conf:
```
docker exec -it kind-control-plane cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
```
2. Tried manually removing `loop` from the configmap (which has resolved the issue for some people facing similar issues I found)

3. I'm tempted to say it's due to a network issue - which others have fixed using:
```
kubeadm reset
iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
kubeadm init --apiserver-advertise-address=<node-IP>
```
But I don't believe macOS is on the list of support platforms for kubeadm, so I haven't been able to test this out.

Any help would be appreciated!

**Environment:**

- kind version: (use `kind version`): `kind version 0.8.1`
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-16T01:01:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`): `Server Version: 19.03.12`
- OS (e.g. from `/etc/os-release`): Running on MacOS v10.14.5

**Comment by BenTheElder** [comment]
You can't use this image with 0.8+ due to a necessary breaking change to fix many networking problems. Sorry about that. This is in the Release notes https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.0#breaking-changes

The 0.8.X image was 1.16.9

If you need 1.16.3 specifically, see the user guide docs on how to build your own image.

**Comment by mszacillo** [comment]
Ah I see. Thanks Ben, that solved the problem.
