### ISSUE TITLE
Kind not added to PATH for MacOS

### ISSUE THREAD

**Issue by ivanayov** [kubernetes-sigs/kind#185]
Hi,

I follow the instructions to install with  `go get sigs.k8s.io/kind` and have `-bash: kind: command not found`, so have to manually run from source code.

**Comment by alejandrox1** [comment]
Hi @ivanayov could you provide us with more info?

Could you provide the output of `go env` and `go version` along with the specific steps you followed to run `kind`?

**Comment by BenTheElder** [comment]
The binary should be at `$(go env GOPATH)/bin/kind`
Most go developers have `PATH=${PATH}:$(go env GOPATH)/bin` or something similar. 

I think the upstream go docs used to cover this better, https://golang.org/doc/install#testing just touches on the fact that binaries go in your "workspace" at `./bin`, with the default workspace (GOPATH) being `$HOME/go` unless you've set `$GOPATH` to something else.

I'm not sure how much of this belongs in our docs, but we probably need to clarify this a bit to make it easier.

/kind documentation
/priority important-soon
