### ISSUE TITLE
export logs: add kind version

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kind#1850]
**What would you like to be added**:

`export logs` adds a `kubernetes-version.txt` with the Kubernetes version. It could be nice to add a `kind-version.txt` with the version of kind.

**Why is this needed**:

Can be useful to debug in some scenarios. This is not really a major issue at all though, very low priority.

**Comment by BenTheElder** [comment]
this actually already had a `// TODO` comment, +1, it's past time to get to that.
https://github.com/kubernetes-sigs/kind/blob/1b4b217cfd74fc2181ce0d9888a80ed1a4cd0161/pkg/cluster/internal/providers/docker/provider.go#L249
