### ISSUE TITLE
CoreDNS metrics vary in node version 1.19.1

### ISSUE THREAD

**Issue by sjmiller609** [kubernetes-sigs/kind#1852]
**What happened**:

something is different about kindest node 1.19.1: coredns is reporting different metrics compared to the other kind node versions. The issue is probably in between kind and coredns, but I expect it could effect other CI users' tests, like it did mine, so it might be useful to check on.

This metric is not showing up on port 9153 in the pod, but it is showing up in node versions 1.15.12, 1.16.15, 1.17.11, 1.18.8
```
coredns_dns_request_count_total
```

**What you expected to happen**:

I expected to find the same metrics between kubernetes versions on core dns in Kind.

**How to reproduce it (as minimally and precisely as possible)**:

kind create cluster

kubectl edit deployment -n kube-system coredns

Add this in the "containers" list:
```
- command:
  - sleep
  - infinity
  name: debug
  image: ubuntu:18.04
```
after the rollout, ensure some DNS requests have occurred:
```
 $ kubectl run -it --rm --command=true --image=ubuntu:18.04 ubuntu /bin/bash
root@ubuntu:/# apt-get update && apt-get install -y curl
# curl google.com
# curl amazon.com
# exit
```

 exec into one of the debug sidecars, for example:
```
$ k exec -it -n kube-system coredns-fbf964d94-srm2g  -c debug /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@coredns-fbf964d94-srm2g:/#
```

Then, install some things for troubleshooting:
```
# apt-get update && apt-get install -y nmap curl vim net-tools dnsutils
```

**Optional**: you will see the metrics endpoint is on 9153:
```
root@coredns-fbf964d94-srm2g:/# nmap -p- localhost

Starting Nmap 7.60 ( https://nmap.org ) at 2020-09-15 17:34 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000050s latency).
Other addresses for localhost (not scanned): ::1
Not shown: 65531 closed ports
PORT     STATE SERVICE
53/tcp   open  domain
8080/tcp open  http-proxy
8181/tcp open  intermapper
9153/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 13.02 seconds
```

We can see the metric ```coredns_dns_request_count_total``` is missing:
```
curl http://localhost:9153/metrics | grep count_total
```

If you repeat this procedure with the lower kubernetes versions, you will find it is not missing.

**Anything else we need to know?**:

I know this issue is somewhere between coredns and kind... I hope to let you know about this issue because it can effect others' CI pipelines similar to how it has mine. In my case, we are running some tests to check our metrics system is compatible in various kubernetes versions. A note of dns variance in change notes is also fine!

**Environment:**

- kind version: (use `kind version`):
```
 $ kind version
kind v0.9.0 go1.15.2 darwin/amd64
```
- Kubernetes version: (use `kubectl version`):
```
 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
```
Client:
 Debug Mode: false

Server:
 Containers: 66
  Running: 1
  Paused: 0
  Stopped: 65
 Images: 1901
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 9
 Total Memory: 22.75GiB
 Name: docker-desktop
 ID: PCK6:XGJD:O4SD:FXJD:2FSU:GAL7:I2N5:T2O3:RHML:QTN6:MPHR:MWID
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 43
  Goroutines: 57
  System Time: 2020-09-15T17:46:06.3059896Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine


```
- OS (e.g. from `/etc/os-release`):

Mac OS Mojave 10.14.6

**Comment by BenTheElder** [comment]
> I expected to find the same metrics between kubernetes versions on core dns in Kind.

kind doesn't do anything special to coreDNS metrics, however different kubernetes versions ship different versions of coreDNS in the kubeadm internal addon.

we should check if this changed in coreDNS

**Comment by sjmiller609** [comment]
Thanks for the tip, I'm sure I'll find the change in kubeadm.

**Comment by sjmiller609** [comment]
https://kubernetes.io/docs/setup/release/notes/#feature

**Comment by BenTheElder** [comment]
>A note of dns variance in change notes is also fine!

The first breaking change entry at the top of the release notes states:
> The default node image is a Kubernetes v1.19.1 image: kindest/node:v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600

https://github.com/kubernetes-sigs/kind/releases/tag/v0.9.0#breaking-changes

If we check the kubernetes 1.19 release notes:

https://kubernetes.io/docs/setup/release/notes/#feature

> ACTION REQUIRED : In CoreDNS v1.7.0, metrics names have been changed which will be backward incompatible with existing reporting formulas that use the old metrics' names. Adjust your formulas to the new names before upgrading.
>
> Kubeadm now includes CoreDNS version v1.7.0. Some of the major changes include:
>
> - Fixed a bug that could cause CoreDNS to stop updating service records.
> - Fixed a bug in the forward plugin where only the first upstream server is always selected no matter which policy is set.
> - Remove already deprecated options resyncperiod and upstream in the Kubernetes plugin.
> - Includes Prometheus metrics name changes (to bring them in line with standard Prometheus metrics naming convention). They will be backward incompatible with existing reporting formulas that use the old metrics' names.
> - The federation plugin (allows for v1 Kubernetes federation) has been removed. More details are available in https://coredns.io/2020/06/15/coredns-1.7.0-release/ (#92651, @rajansandeep) [SIG API Machinery, CLI, Cloud Provider, Cluster Lifecycle and Instrumentation]
