### ISSUE TITLE
Inline Create Cluster Config

### ISSUE THREAD

**Issue by Xtigyro** [kubernetes-sigs/kind#1858]
**What would you like to be added**:

Ability to use inline config upon cluster creation.

**Why is this needed**:

No files are needed on the file system. Easier to manage when KinD is used in automations. You'll be able to pass the config via just an environment variable.

**Comment by BenTheElder** [comment]
You can pass a config file via stdin already. `--config=-`, giving various options to make it inline.

**Comment by Xtigyro** [comment]
Agreed.
