### ISSUE TITLE
Proxy Configuration - Documentatio 

### ISSUE THREAD

**Issue by ganeshr2** [kubernetes-sigs/kind#1863]
**What would you like to be documented**: HTTPS and HTTP PROXY Configuration sample configuration is not mentioned in the quickstart.md document.

**Why is this needed**: This will help in configuring proxy for kind

**Comment by BenTheElder** [comment]
We can mention it breifly but there's not a lot to mention. These are a "standard".

**Comment by ganeshr2** [comment]
ok, yes simple snippet like other configuration will help.

**Comment by aojea** [comment]
/close
Proxy configuration is documented here
https://kind.sigs.k8s.io/docs/user/quick-start/#configure-kind-to-use-a-proxy
