### ISSUE TITLE
Kind binding to IPV6

### ISSUE THREAD

**Issue by ganeshr2** [kubernetes-sigs/kind#1864]
**What happened**: Trying to instantiate a cluster with ipv4, but the port binding happened to ipv6. This is a dual-stack eth0 interface.

**What you expected to happen**: Bind should only happen to ipv4 only or both ipv4 and ipv6.

**How to reproduce it (as minimally and precisely as possible)**:
- snippet of config

  ipFamily: ipv4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
    listenAddress: "0.0.0.0"
  - containerPort: 443
    hostPort: 443
    protocol: TCP
    listenAddress: "0.0.0.0"

output ip -c a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9138 qdisc fq_codel state UP group default qlen 1000
    link/ether fa:16:3e:63:fd:74 brd ff:ff:ff:ff:ff:ff
    inet 192.168.93.33/24 brd 192.168.93.255 scope global dynamic noprefixroute eth0
       valid_lft 74035sec preferred_lft 74035sec
    inet6 fe80::f816:3eff:fe63:fd74/64 scope link
       valid_lft forever preferred_lft forever

netstat -tunlp |grep 443
tcp6       0      0 :::443                  :::*                    LISTEN      1433252/dockerd

  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64"

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): kind v0.9.0 go1.15.2 linux/amd64
- Kubernetes version: (use `kubectl version`):
Major:"1", Minor:"18", GitVersion:"v1.18.5"
- Docker version: (use `docker info`):
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 30
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-147.3.1.el8_1.x86_64
 Operating System: CentOS Linux 8 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.25GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

- OS (e.g. from `/etc/os-release`):
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

**Comment by BenTheElder** [comment]
Why should it bind to both, exactly?
You can add a port binding to both of you want, but each binding is for one address, the same as docker.
The default address is loopback and depends on the cluster IP family, but you can configure it yourself.

**Comment by ganeshr2** [comment]
i was looking to bind to ipv4, having specified the listenAddress: "0.0.0.0", but it bound to ipv6.. hence my thought was either it should bind to ipv4 or bind to ipv6.  

Note: i changed to provide the eth0 ip on the listen address instead of all 0's and it correctly bound to ipv4.  So my next question is does KIND support Dual stack networks, like how  Kubernetes support?

Thanks
Ganesh

**Comment by BenTheElder** [comment]
How exactly did you specify the listen address?
KIND uses the listen address for a docker port forward.

Single stack or dual stack is complicated. Kubernetes is not yet really dualstack and KIND doesn't do dual stack in Kubernetes yet. KIND does Kubernetes level single stack on single or dualstack node networks (single if the host can't do IPv6, dual otherwise), but most of the cluster is only using v4 or v6 because kubernetes.

The behavior for the apiServer access from the host comes from docker's port forwarding mechanism.

**Comment by BenTheElder** [comment]
To be clear I see the value you say you specified, but not the actual config. That snippet is not valid config on its own.

**Comment by ganeshr2** [comment]
@BenTheElder  i will get backon this tomorrow - sorry missed the updates. thanks for responding back.

**Comment by aojea** [comment]
> i was looking to bind to ipv4, having specified the listenAddress: "0.0.0.0", but it bound to ipv6.. hence my thought was either it should bind to ipv4 or bind to ipv6.

golang 0.0.0.0 and :: are equivalent, you can read more here 
https://github.com/kubernetes/kubernetes/issues/88458

> Note: i changed to provide the eth0 ip on the listen address instead of all 0's and it correctly bound to ipv4. So my next question is does KIND support Dual stack networks, like how Kubernetes support?

If Dual stack you mean pods and services are dual stack, that  is alpha in kubernetes and these days is going by a major rewrite, if you want to play with that feature you can use my fork https://github.com/aojea/kind/releases/tag/dualstack

If by Dual stack you mean that you can deploy a cluster in a dual stack environment, but pods and service are only using one ipfamily, kind and kubernetes  does support that.

**Comment by aojea** [comment]
/close
lack of answer, feel free to reopen if needed
