### ISSUE TITLE
kind create cluster flaky with 0.9.0

### ISSUE THREAD

**Issue by FWiesner** [kubernetes-sigs/kind#1865]
**What happened**:
I'm setting up KinD running in a Gitlab CI runner on Kubernetes 1.17.1. With KinD 0.9.0 I'm facing the issue that the kind-control-plane's health check intermittently can throw an internal server error and then the cluster creation typically aborts immediately although the control plane would come up normally
```
I0922 19:31:04.270993     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 19:31:04.771062     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 19:31:05.271075     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 19:31:05.771086     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 19:31:06.270960     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 19:31:06.771088     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 19:31:07.271012     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 19:31:07.770980     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 19:31:08.271020     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 19:31:08.770939     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 19:31:09.271064     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 19:31:09.771196     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 19:31:14.140135     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s 500 Internal Server Error in 3869 milliseconds
I0922 19:31:14.272928     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s 500 Internal Server Error in 2 milliseconds
```
Sometimes it is visible that the error 500 occurred, but KinD didn't realize it right away. Then the `healthz` check suddently reports success and config map uploads, role creations, etc happen successfully. Thereafter the deployment still is reported as failed. Here's an example:
```
I0922 18:38:12.213685     179 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 18:38:12.713522     179 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 18:38:13.213745     179 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 18:38:13.713749     179 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 18:38:14.213942     179 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0922 18:38:18.590730     179 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s 500 Internal Server Error in 3877 milliseconds
I0922 18:38:18.714985     179 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s 500 Internal Server Error in 1 milliseconds
I0922 18:38:19.215036     179 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s 500 Internal Server Error in 1 milliseconds
I0922 18:38:19.715723     179 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s 500 Internal Server Error in 2 milliseconds
I0922 18:38:20.217024     179 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s 200 OK in 3 milliseconds
[apiclient] All control plane components are healthy after 27.505677 seconds
I0922 18:38:20.217991     179 uploadconfig.go:108] [upload-config] Uploading the kubeadm ClusterConfiguration to a ConfigMap
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
I0922 18:38:20.223363     179 round_trippers.go:443] POST https://kind-control-plane:6443/api/v1/namespaces/kube-system/configmaps?timeout=10s 201 Created in 3 milliseconds
I0922 18:38:20.227139     179 round_trippers.go:443] POST https://kind-control-plane:6443/apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles?timeout=10s 201 Created in 2 milliseconds
I0922 18:38:20.231047     179 round_trippers.go:443] POST https://kind-control-plane:6443/apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings?timeout=10s 201 Created in 2 milliseconds
I0922 18:38:20.231770     179 uploadconfig.go:122] [upload-config] Uploading the kubelet component config to a ConfigMap
[kubelet] Creating a ConfigMap "kubelet-config-1.19" in namespace kube-system with the configuration for the kubelets in the cluster
I0922 18:38:20.234693     179 round_trippers.go:443] POST https://kind-control-plane:6443/api/v1/namespaces/kube-system/configmaps?timeout=10s 201 Created in 2 milliseconds
I0922 18:38:20.237156     179 round_trippers.go:443] POST https://kind-control-plane:6443/apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles?timeout=10s 201 Created in 2 milliseconds
I0922 18:38:20.239767     179 round_trippers.go:443] POST https://kind-control-plane:6443/apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings?timeout=10s 201 Created in 2 milliseconds
I0922 18:38:20.239902     179 uploadconfig.go:127] [upload-config] Preserving the CRISocket information for the control-plane node
I0922 18:38:20.239958     179 patchnode.go:30] [patchnode] Uploading the CRI Socket information "unix:///run/containerd/containerd.sock" to the Node API object "kind-control-plane" as an annotation
```
(after this line the tool terminates)
**What you expected to happen**:
I'm providing a timeout of 5 minutes via `--wait 5m` and I would expect that kind create cluster allows the control plane to come up, even when there are intermittent issues

**How to reproduce it (as minimally and precisely as possible)**:
I cannot reproduce this on my laptop, but on our Gitlab-CI runner, installed via Helm 3 on Kubernetes v1.17.1 it fails 4 times out of 5

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.9.0
- Kubernetes version: (use `kubectl version`): v1.19.2 (kubectl), v1.17.1 server, v1.19.1 as planned KinD cluster version
- Docker version: (use `docker info`): 19.03.13
- OS (e.g. from `/etc/os-release`): Oracle Linux 7 (host), Alpine 3.12 as basis of DinD

**Comment by BenTheElder** [comment]
The wait 5m is for kind to wait for the cluster to be healthy later on in the process, the timeout you're seeing here is from `kubeadm` upstream and is not configurable.

**Comment by FWiesner** [comment]
ok - still I would assume that an intermittent issue like the `healthz` endpoint throwing an error 500 should not abort everything

**Comment by BenTheElder** [comment]
> ok - still I would assume that an intermittent issue like the healthz endpoint throwing an error 500 should not abort everything

Again this is from kubeadm upstream, it's not intermittent if it fails for ~30s as per your logs. 

Did this work before with 0.8.0? Is it flaky with other server versions? Can you tell me more about the CI host?

> I0922 19:31:09.271064     173 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds

These lines mean that kubeadm is detecting that the Kubernetes API server is not coming up healthily. Often this means for example that kubelet is not healthy, due to some environmental issue.

You can find more by running create cluster with `--retain` (no cleanup) and then `kind export logs` to export all of the component logs so we can inspect for what part of Kubernetes isn't working in your environment.

**Comment by BenTheElder** [comment]
> I cannot reproduce this on my laptop, but on our Gitlab-CI runner, installed via Helm 3 on Kubernetes v1.17.1 it fails 4 times out of 5


Ah, you're nesting Kubernetes inside Kubernetes? This comes with a whole slew of footguns. Please see #303 for ongoing discussion.

**Comment by FWiesner** [comment]
With 0.8.0 I got further down the provisioning reliably, but then the node joining never succeeded as we use an HTTP proxy and the worker nodes were unable to connect to the API server. I guess because they all tried using the HTTP proxy, which in turn cannot route back

**Comment by BenTheElder** [comment]
v0.8.X does indeed have some issues related to proxies :disappointed:, you can try manually adding addresses to `NO_PROXY` but I suspect this is actually an environment issue. There are a number of tricks that must be employed to run kind inside another cluster successfully, and they're not the sort of thing kind should be doing on it's own (e.g. adjusting the system inotify watch limits).

**Comment by FWiesner** [comment]
> > I cannot reproduce this on my laptop, but on our Gitlab-CI runner, installed via Helm 3 on Kubernetes v1.17.1 it fails 4 times out of 5
> 
> Ah, you're nesting Kubernetes inside Kubernetes? This comes with a whole slew of footguns. Please see #303 for ongoing discussion.

Well, it is Kubernetes (Oracle Kubernetes Engine), running GitLab CI worker pods, which then run DinD in which the KinD cluster would be created ;)

**Comment by FWiesner** [comment]
> v0.8.X does indeed have some issues related to proxies 😞, you can try manually adding addresses to `NO_PROXY` but I suspect this is actually an environment issue. There are a number of tricks that must be employed to run kind inside another cluster successfully, and they're not the sort of thing kind should be doing on it's own (e.g. adjusting the system inotify watch limits), or some things we can't (mount that must be present in the outer cluster pod).

the problem with NO_PROXY in this case is that you'd have to know the pod IPs upfront

**Comment by BenTheElder** [comment]
> Well, it is Kubernetes (Oracle Kubernetes Engine), running GitLab CI worker pods, which then run DinD in which the KinD cluster would be created ;)

Yeah, so in this case see the hacks in #303. You'll need to do things like pass through the host modules to the dind container.
KIND's own CI runs this way and we don't have flake issues, but we have to employ these various environmental tweaks. If you're not employing these fixes the inner cluster will be very flaky.

> the problem with NO_PROXY in this case is that you'd have to know the pod IPs upfront

yes, agreed. It's fixed in v0.9.0.

**Comment by FWiesner** [comment]
btw. I just had a successful run, but the 5mins timeout was hit I guess. Exit code seems to have been 0 as my CI job is marked as successful

**Comment by FWiesner** [comment]
<img width="659" alt="Bildschirmfoto 2020-09-22 um 22 16 06" src="https://user-images.githubusercontent.com/1433733/93932962-3b5e3800-fd21-11ea-83d3-bb4959b8e8fc.png">

**Comment by FWiesner** [comment]
#303 I was missing on the FAQs

**Comment by BenTheElder** [comment]
The `--wait` flag is just to help ensure that the cluster is ready for your tests, it's not considered a critical path and isn't exhaustive, it is not supposed to fail, the cluster is already relatively online before we get to this phase. It's something we needed for testing Kubernetes itself.

If you strongly depend on some particular flavor of readiness (there are many levels for a cluster, e.g. api server available, nodes are all "ready", ...), you should add a wait-loop in your test rig.

I should also clarify that we do NOT recommend running Kubernetes in Kubernetes if you can avoid it for the moment. I think in the future we may have better options but it's full of problems and fairly unsafe. We're intentionally not advertising this, we don't want to encourage it.

**Comment by FWiesner** [comment]
I still think some warning about Kubernetes on Kubernetes should be posted. I just brought up a new set of Gitlab runners that directly run on VMs, using Docker. All the flakiness is gone. If I had known about the problems of KinD in Kubernetes, I would have avoided it from the beginning.

**Comment by BenTheElder** [comment]
ACK. Glad it's working for you now!

**Comment by BenTheElder** [comment]
A warning about this would fit in well to the known issues page, with a link back to 303. I'll try to take a look tomorrow.

**Comment by Pradumn99** [comment]
> btw. I just had a successful run, but the 5mins timeout was hit I guess. Exit code seems to have been 0 as my CI job is marked as successful

Hi @FWiesner, can you let me know the fix you did for running your CI in runner.

**Comment by haapjari** [comment]
I had very similar issue, but on local environment - maybe this could be helpful: https://github.com/kubernetes-sigs/kind/issues/2436#issuecomment-1127395983
