### ISSUE TITLE
Version 0.9 Does the local registry works ?

### ISSUE THREAD

**Issue by Arnaud-Francois-Fausse** [kubernetes-sigs/kind#1866]
Hi,
On my Window10 Pro box I run kind-windows-amd64.exe version 0.9. 
The port 5000 is closed. I can't push images on localhost:5000
What shall I do to make the local image registry working ?
Thanks.

**Comment by BenTheElder** [comment]
You need to do something equivalent to https://kind.sigs.k8s.io/docs/user/local-registry/ for now. No registry exists out of the box.
You can instead also use https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
We're aiming to have a built-in version in v0.10

**Comment by Arnaud-Francois-Fausse** [comment]
Thank you @BenTheElder, So I have to adapt this script for Windows, it seems quite possible.
By the way, looking at this script gave me an idea. In fact I tried to connect a  remote private registry to Kind using SSL. But it is necessary to declare the SSL CA certificate in the CRI pluging definition. Doing a containerdConfigPatches to set the CA in the containerd config seems to be a good solution. Have you already done it ? Is there a simpler solution ?
Thanks again, Best regards

**Comment by BenTheElder** [comment]
Containerd config is one way to do this, if you search the issue tracker and check the docs there's more discussion of private registries. https://kind.sigs.k8s.io/docs/user/private-registries/

**Comment by Arnaud-Francois-Fausse** [comment]
As far as I understand, they don't really talk about the CA certificates trust necessary to connect to the registry. I use microk8s and I had also this problem that I solved adding the CA certificate uri in the containerd configuration file. But there are very few articles on this subject and any pointer and advice is welcome.
BR

**Comment by BenTheElder** [comment]
Sorry I don't use private registries myself. Whatever applies to containerd
config in general should apply here, just with the additional availability
of the patch mechanism.
You can find additional past discussion by others about certs and private
registries by searching the issue tracker.

**Comment by BenTheElder** [comment]
The approach taken with microk8s should work here, you can use the containerd config patching mechanism to do this natively in the kind config.
