### ISSUE TITLE
New command: kube stop cluster and kube start cluster

### ISSUE THREAD

**Issue by felipecrs** [kubernetes-sigs/kind#1867]
This command would simply run `docker stop` and `docker start` against all the nodes. Despite I can do it by myself, they seem to restart automatically when stopped. Perhaps `kind` is creating the containers with `--restart always` instead of `--restart unless-stopped`?

It would be better to exist in `kind` since multiple clusters can co-exist, and `kind` knows exactly what are the containers which belong to a given cluster.

I use `kind` in my development environment, which has limited resources. I have a testing cluster set up that I would not like to lose, but I don't use it always, so I could simply start the cluster as needed and keep my laptop cold otherwise. :)

**Comment by BenTheElder** [comment]
kind is not setting restart = always.

https://github.com/kubernetes-sigs/kind/blob/1b4b217cfd74fc2181ce0d9888a80ed1a4cd0161/pkg/cluster/internal/providers/docker/provision.go#L166-L185

You can trivially run start/stop against the node containers yourself (`kind get nodes | xargs docker stop`), but I think you'll find that doesn't behave as you'd expect because of the nested containers.

The podman backend also currently does not support restart.

**Comment by BenTheElder** [comment]
> I use kind in my development environment, which has limited resources. I have a testing cluster set up that I would not like to lose, but I don't use it always, so I could simply start the cluster as needed and keep my laptop could otherwise. :)

I would strongly prefer to improve the experience of creating new clusters anyhow though. We do not want users becoming highly attached to their kind clusters. Testing should be from a clean state and critical data should not be stored permanently in these clusters. They should start quickly and be disposable.

**Comment by felipecrs** [comment]
I wonder if it's possible to change the `restart` policy dynamically.

**Comment by BenTheElder** [comment]
Docker container configuration is not dynamically changeable.

**Comment by felipecrs** [comment]
Actually, it's doable:

```sh-session
docker update --restart=unless-stopped kind-control-plane
```

https://docs.docker.com/engine/reference/commandline/update/#update-a-containers-restart-policy

But for some reason it fails:

```sh-session
$ docker update --restart=unless-stopped kind-control-plane
Error response from daemon: Cannot update container 2912eb63c333ce9395d428452474e7d7109167aeffb47196a6484c741705cfcd: runc did not terminate sucessfully: failed to write "a *:* rwm" to "/sys/fs/cgroup/devices/docker/2912eb63c333ce9395d428452474e7d7109167aeffb47196a6484c741705cfcd/devices.allow": write /sys/fs/cgroup/devices/docker/2912eb63c333ce9395d428452474e7d7109167aeffb47196a6484c741705cfcd/devices.allow: invalid argument
: unknown
```

**Comment by BenTheElder** [comment]
In any case `on-failure` should only be restarting when the container exits uncleanly, and it should only start once. `unless-stopped` is not a desirable policy, see the code comment above.

It also starts on bootup. If it stops and you reboot it will start, but that's the case with *all* restart policies except none.

**Comment by felipecrs** [comment]
You're right. The `unless-stopped` does not help anyhow (the container is indeed restarted when the system starts).

So, for `kind stop cluster`, we need to first call `docker update --restart=no kind-control-plane` then `docker stop kind control plane`.

For `kind start cluster`:`docker update --restart=on-failure:1 kind-control-plane` and `docker start kind-control-plane`.

**Comment by felipecrs** [comment]
However, for some reason `docker update` does not work with the kind node containers (they work in other containers though):

```console
$ docker update --restart=no test
test
$ docker update --restart=no kind-control-plane
Error response from daemon: Cannot update container 2912eb63c333ce9395d428452474e7d7109167aeffb47196a6484c741705cfcd: runc did not terminate sucessfully: failed to write "a *:* rwm" to "/sys/fs/cgroup/devices/docker/2912eb63c333ce9395d428452474e7d7109167aeffb47196a6484c741705cfcd/devices.allow": write /sys/fs/cgroup/devices/docker/2912eb63c333ce9395d428452474e7d7109167aeffb47196a6484c741705cfcd/devices.allow: invalid argument
: unknown
```

**Comment by BenTheElder** [comment]
This is likely because of the cgroups changes in the entrypoint. KIND is
not a normal container (nor are each node actually one container).

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes-sigs/kind/issues/1913

**Comment by DylanBowden** [comment]
FYI Running things the other way around works for me
- docker stop kind control plane then
- docker update --restart=no kind-control-plane

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes-sigs/kind/issues/2715

there's been more work on restarts for docker (podman is lacking some functionality), there's more recent discussion in #2715
