### ISSUE TITLE
List number of Docker containers running inside kind

### ISSUE THREAD

**Issue by rmohta** [kubernetes-sigs/kind#1869]
How do I list number of docker containers running inside KIND? Today I get all pods, and then apply little bash script - but as we use containerd (or docker) - can it be a simple info to show to end user?

**Comment by BenTheElder** [comment]
The kubernetes native thing to do is to `kubectl get no -oyaml` or `kubectl describe no` and get the _pods_ and if you really need the containers to then lookup the containers for each pod..

The nodes _currently_ run containerd as the node runtime, with `ctr` and `crictl` tools available.
We do not recommend depending on the contents of the nodes other than functioning kubernetes nodes, but if you must bypass the kubernetes API you can use `docker exec <node-name> crictl ps`, or use `ctr` within the nodes similarly.
