### ISSUE TITLE
Add and remove new nodes dynamically

### ISSUE THREAD

**Issue by marcosnils** [kubernetes-sigs/kind#1871]
**What would you like to be added**:

The ability to add and remove new nodes automatically to an existing cluster

**Why is this needed**:

The most useful use-case for me is to experiment with different setup and disaster recovery scenarios. It's good to learn how to join members to a running cluster and how to recover from failures

**Comment by BenTheElder** [comment]
> The ability to add and remove new nodes automatically to an existing cluster

We've discussed this many times. While it might happen in the future, the details for this get very messy and it's not important to any scenarios we target testing right now. 

For testing Kubernetes itself it's not important _when_ the nodes are added. We can do that in initial config.
For testing applications, you can simulate node addition / removal with e.g. taints.
Other things we target don't use more than one node anyhow.
https://kind.sigs.k8s.io/docs/contributing/project-scope/

> The most useful use-case for me is to experiment with different setup and disaster recovery scenarios. It's good to learn how to join members to a running cluster and how to recover from failures

kind would not be exposing how nodes are joined to you, if your goal is to learn about how to bring up kubernetes itself I do not recommend using kind, this is not a use-case we target. You should look at the kubeadm / Kubernetes upstream documentation instead.

**Comment by marcosnils** [comment]
Fair enough.. thx for the detailed reasoning and apologies if this has been opened before. I'm closing since I don't thing there's anything left to add here.

**Comment by lobuhi** [comment]
Solved https://github.com/lobuhi/kindscaler

**Comment by aojea** [comment]
Thanks, there is always simple solutions that can build on top of kind, like this one per example
