### ISSUE TITLE
Pulling the image from registry.connect.redhat.com doesn't work

### ISSUE THREAD

**Issue by antonlisovenko** [kubernetes-sigs/kind#1873]
**What happened**:
Failing to pull image from registry.connect.redhat.com when running in Kind. Minikube/kops work fine with the same imagePullSecret.
The error message may look differently (depending on the machine it's run). It's either the 
```
failed to resolve reference "registry.connect.redhat.com/mongodb/enterprise-operator:1.7.1": failed to authorize: failed to fetch oauth token: unexpected status: 403 Forbidden
```
or
```
failed to resolve reference "registry.connect.redhat.com/mongodb/enterprise-operator:1.7.1": no scope specified for token auth challenge
```

**What you expected to happen**:
I expect the image to be pulled successfully

**How to reproduce it (as minimally and precisely as possible)**:
1. Login to redhat connect (you need to have the RedHat registry service account)

```
docker login -u='<user>' -p='<password>' registry.connect.redhat.com
```
(ensure auth is written to `~/.docker.config.json` in base64 format - ensure the `credsStore` element doesn't exit)

2. Create the image pull secret
```
kubectl create secret generic image-registries-secret \
  --from-file=.dockerconfigjson="${HOME}/.docker/config.json" --type=kubernetes.io/dockerconfigjson
```
3. Create the following pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: somepod
spec:
  containers:
    - name: web
      image: registry.connect.redhat.com/mongodb/enterprise-operator:1.7.1
  imagePullSecrets:
    - name: image-registries-secret
```
4. `kubectl describe pod somepod` gets to `ErrImagePull` state.

**Anything else we need to know?**:

I've checked and the above path works perfectly on kops (`1.18.1`, K8s `1.15.10`) and Minikube (`v1.13.1`, K8s `1.19.1`)
Also Kind works without any problems pulling images from AWS ECR, it's only redhat registry which is failing

**Environment:**

- kind version: (use `kind version`): 
`kind v0.9.0 go1.15.2 darwin/amd64`
- Kubernetes version: (use `kubectl version`): 
`Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
`
- Docker version: (use `docker info`): 
` Server Version: 19.03.12`

- OS (e.g. from `/etc/os-release`): Mac OS `10.15.6`

**Comment by BenTheElder** [comment]
KIND doesn't do anything special for registry pulling other than using containerd as the node runtime. I was going to ask if it was a proxy issue perhaps but you say another registry works.

It's possible this is a containerd bug, but I would guess it's a bug in the registry after looking around a little.

**Comment by BenTheElder** [comment]
> no scope specified for token auth challenge

https://github.com/containerd/containerd/issues/3556

Basically this is a bug in the registry most likely.

**Comment by antonlisovenko** [comment]
thanks @BenTheElder 

Yes, that was my guess as well. I've reproduced the same problem in minikube when ran it with `containerd` instead of default CRI (docker?):
```
minikube start \
    --network-plugin=cni \
    --enable-default-cni \
    --container-runtime=containerd \
    --bootstrapper=kubeadm
```
```
failed to resolve reference "registry.connect.redhat.com/mongodb/enterprise-operator:1.7.1": no scope specified for token auth challenge
```

I'll file the ticket on redhat.

Do you know if there is a way to run Kind cluster with another CRI implementation. I thought about specifying `kubeletExtraArgs:` in Kind config but don't have any examples.

**Comment by BenTheElder** [comment]
Currently we only support containerd as the node runtime, usually it doesn't matter much in the k8s usage level / end users but we have to integrate for some system management stuff to e.g. make kind node image work offline.

clearly it does here 😞

**Comment by BenTheElder** [comment]
A friend at redhat reports they've made contact with the PM 🤞 

I'm pretty sure this is the more or less the same oauth flow issue artifactory fixed a while back in https://github.com/containerd/containerd/issues/3556 / https://www.jfrog.com/jira/browse/RTFACT-20170, hopefully it's not too involved to fix on the registry side.

**Comment by jdef** [comment]
unclear if it's related to this or not, but I just tested with the latest kindest/node 1.19.x image (running containerd-v1.4.0/ubuntu 20.10) and experienced image pull failures in an airgapped cluster (x509: certificate signed by unknown authority).

we're properly updating CA certs w/ our in house root CAs (ala docker cp/docker exec), and falling back to the 1.18.x kindest/node image seems to fix the problem, even with the kind 0.9 binary

**Comment by BenTheElder** [comment]
@jdef that doesn't sound related. This is a bug in the oauth flow in redhat's registry. Artifactory used to have a similar bug but it's been patched for some time now. There's more on that in the links I posted above.

Your issue sounds like a change in containerd or the ubuntu base image related to TLS/certs.

**Comment by BenTheElder** [comment]
I've not heard back anything further here, but AFAICT this is an issue on redhat's end with spec compatibility and won't be something we can resolve ourselves.

I'm going to leave this open for now in the hope that anyone else running into this issue finds the discussion here.

**Comment by BenTheElder** [comment]
I'm not a redhat customer so I can't really look into this further on our end and still haven't heard anything back ... @aojea maybe you can take a look.

**Comment by aojea** [comment]
yeah, let me check it next week, the reporter did a nice description so it should be easy to verify
/assign

**Comment by aojea** [comment]
/close

Followed the steps in the description but different image in registry.redhat.io

Pulling without login
```
docker pull registry.redhat.io/openshift3/ose-pod
Using default tag: latest
Error response from daemon: Head https://registry.redhat.io/v2/openshift3/ose-pod/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication

```

adding credentials to the kind clusters works perfectly
```
  Type    Reason     Age        From                         Message
  ----    ------     ----       ----                         -------
  Normal  Scheduled  <unknown>                               Successfully assigned default/somepod to kind-control-plane
  Normal  Pulling    51s        kubelet, kind-control-plane  Pulling image "registry.redhat.io/openshift3/ose-pod"
  Normal  Pulled     32s        kubelet, kind-control-plane  Successfully pulled image "registry.redhat.io/openshift3/ose-pod" in 19.061400787s
  Normal  Created    32s        kubelet, kind-control-plane  Created container web
  Normal  Started    31s        kubelet, kind-control-plane  Started container web

```

**Comment by BenTheElder** [comment]
Thanks!
