### ISSUE TITLE
How to build Kind for windows 10 (kind-windows-amd64.exe) ?

### ISSUE THREAD

**Issue by arnoldfranz** [kubernetes-sigs/kind#1876]
Hi
I would like to build a custom Kind image. I use the distributed kind-windows-amd64.exe. How can I build such a custom .exe ?
Thanks a lot

**Comment by BenTheElder** [comment]
Do you want a custom binary or a custom image (what kind of image?)
You can build a custom binary with the go compiler. `go build .` from the repo.
We cross compile the release binaries using a script under hack.

**Comment by arnoldfranz** [comment]
Thanks @BenTheElder,
I want to add cri setup parameters in the CRI file and build the image (base), since it is applied to others images (as far as I understand).
Can I do that without recompiling kind-windows-amd64.exe ?
Sorry if my questions are stupid !!

**Comment by arnoldfranz** [comment]
I need a customer image to set specific CRI parameters. I don't need to recompile Kind.
However, I am curious to understand how you "cross compile the release binaries using a script"
I looked at hack folder scripts but it's still unclear to me how it is done. 
I did a make on Linux, which succeeded but in the bin folder the kind-windows-amd64.exe is missing.
Could you be more specific on how cross compile, may be to set parameters in the make to activate the cross compile?
Any clue is welcome
Thanks

**Comment by BenTheElder** [comment]
You don't need to cross compile, but it's https://github.com/kubernetes-sigs/kind/blob/master/hack/release/build/cross.sh used during a release, which just wraps `make build`.

You can build a custom base image by following here https://github.com/kubernetes-sigs/kind/tree/master/images/base
... but I don't think you need to do that. It's a lot more expensive to build a new base and then `kind build node-image` with that base versus just adding your customization on top with a standard docker build using an existing node image as the `FROM`, or contributing the changes into kind itself..

What do you mean by "CRI parameters" ?
If you mean containerd configuration, you don't need to compile anything to change those.
you can `kind create cluster --config=/path/to/config.yaml` with `config.yaml` containing containerd options:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".containerd]
  disable_snapshot_annotations = true
```

**Comment by arnoldfranz** [comment]
Thank you very much @BenTheElder. I use the Visual Studio Code plugin for Kind (it's very convenient), but I am not able to modify it so that the kind command accepts my extra parameters. That's why I try to bypass this problem making an image which embeds the custom values I need. Fore the CRI parameters, yes, you are absolutely right on what I need. The last solution you propose is clearly the most elegant and simple.

**Comment by BenTheElder** [comment]
I see, perhaps they'd be willing to support the config format :thinking:
