### ISSUE TITLE
Bash CDPATH interferes with hack scripts

### ISSUE THREAD

**Issue by jlucktay** [kubernetes-sigs/kind#1887]
**What happened**:
Running a variety of shell scripts under the `hack/` sub-directory threw errors with `cd` and directory names that are doubled up.

**What you expected to happen**:
Linting, shellchecking, code generation, various hacky things.

**How to reproduce it (as minimally and precisely as possible)**:

```shell
$ export CDPATH=.
$ hack/make-rules/verify/all.sh 
hack/make-rules/verify/all.sh: line 20: cd: $'/Users/jameslucktaylor/go/src/sigs.k8s.io/kind\n/Users/jameslucktaylor/go/src/sigs.k8s.io/kind': No such file or directory
```

**Anything else we need to know?**:

From <https://www.gnu.org/software/bash/manual/html_node/Bourne-Shell-Builtins.html>:

> If a non-empty directory name from CDPATH is used, or if ‘-’ is the first argument, and the directory change is successful, the absolute pathname of the new working directory is written to the standard output.

**Environment:**

- kind version: (use `kind version`): checked out at d7f948dd8c00084d6ee30eb953471ce3ce375455.
- Kubernetes version: (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:21Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}`
- Docker version: (use `docker info`):
```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 444
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.779GiB
 Name: docker-desktop
 ID: OSEZ:53JP:7UA5:VNF3:XBCD:JLU3:IKYN:5UZJ:MC4S:ZKAB:VHTR:VOU7
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 52
  System Time: 2020-10-08T14:54:51.912683Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```
- OS (e.g. from `/etc/os-release`): `uname -a` gives: `Darwin james-l-tyk-mbp.lan 18.7.0 Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64`

**Comment by jlucktay** [comment]
I'll have a PR shortly, to fix up the hack scripts.

**Comment by BenTheElder** [comment]
Oof :(
Thanks!

I think this bug is probably present in a lot of other places in github.com/kubernetes / github.com/kubernetes-sigs

**Comment by BenTheElder** [comment]
thanks! https://github.com/kubernetes-sigs/kind/pull/1888
