### ISSUE TITLE
fix or eliminate the spinner

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#189]
the "spinner" / status in our CLI does not work properly in some shells (eg very narrow ones) since it just uses `\r` to rewrite the line.

https://github.com/nsf/termbox-go looks like one promising option for TUI

/priority important-soon
/assign

**Comment by BenTheElder** [comment]
/lifecycle active
I'm hacking on this.

**Comment by BenTheElder** [comment]
debating which option to go with and continuing to intermittently look at options :-)

**Comment by neolit123** [comment]
termbox seems very good and it does things properly by tapping into OS APIs.
but seems like an overkill for a spinner, unless kind has plans for `curses` like UI.

some solutions i can think of:
1) always place the spinner alone on a line, this will (mostly) ensure that `\r` works, but will increase the number of lines.
2) break input strings into 80 characters lines and place a spinner on the last one.
3) just use `...` instead of the spinner.

**Comment by BenTheElder** [comment]
Yeah termbox is not the right solution here unless we want to reimplement a LOT more, it's meant to control the whole buffet always.

For spinning we can use some different escape sequences with trade-offs.

The general issue is around how terminals handle line wrapping, lines that are too long (which can be very short when someone is demoing and has their terminal enlarged 😉) will break to another line in a way that does not properly rewrite with a simple /r.

I've been testing the behavior in various shells when I'm not actually at work and so far have two main options with escape sequences:
- \b for every char in the line
- a sequence with \r \b and a VT100 escape to clear the line combined multiple times up to the number of wrapped lines we want to support.

\b repeated seems to be more correct, but writing more characters is slower and not ideal

All of these seem to be broken in xterm.js line wrapping (IE in VSCode) but that's another matter ...

**Comment by BenTheElder** [comment]
We do already do 1) but we can't prevent that single line from wrapping to more

2) assumes 80 chars and thin terminals can be less than that, plus character width is not constant

3) we do have a mode like this already when not on a TTY. That's the eliminate option.

**Comment by BenTheElder** [comment]
I was prepared to remove this today, but @Katharine made an excellent suggestion to simply move the spinner to the end of the line and rewrite _just_ the spinner with `\b` * `len(spinner_frame)`, after some quick experimentation I think this route is worth going.

NB: there's some fun VT100 behavior around when the output is exactly `terminalWidth + 1`, where it will eat one character. if we do: `msg + " "+ " " + spinnerFrame` then this is mostly a non-issue (IE pad with two spaces, it will eat one of the spaces).

so I think we can probably keep it with a small rework. will do that later this week :^)

**Comment by BenTheElder** [comment]
bumping out of active, I did investigate this, but I'm punting the actual changes for a bit.

**Comment by mitar** [comment]
I would vote for just removing the spinner. Spinners tend to make CI logs long and sometimes hard to read because CI tries to render logs in "smart" ways breaking terminal assumptions.

**Comment by BenTheElder** [comment]
FWIW In CI there should already be no spinner unless the CI allocates a fake TTY, in which case this it would probably be working as intended. We do tty detection for toggling the spinner and log formatting (though I dislike the current no-tty formatting especially, just haven't gotten to that yet).

Locally it's nice to have enough feedback from the CLI to know that the tool is not hung, the alternative with just writing at the end of the line with backspaces should be pretty unintrusive and mimics some other tools.

A quick prototype of this worked pretty well in every situation I could throw at it, but if we make things fast enough we might not have any use for one anyhow :^)

**Comment by mitar** [comment]
You can just output a dot every 30 seconds or so and it shows that it is not hung.

**Comment by BenTheElder** [comment]
So to summarize where we are now:
- the output has been reformatted a bit, a terminal of somewhat less than 50 characters wide should be plenty
- the spinner is a little more robust now
- since the beginning the spinner supports a non-spinning fallback in CI when no TTY is detected

I'm closing this for now as I haven't seen further issues with recent versions, and we've received some positive feedback about it.
