### ISSUE TITLE
Fancy output crashes terminal

### ISSUE THREAD

**Issue by bdomars** [kubernetes-sigs/kind#1892]
**What happened**:
Tried running `kind create cluster` and terminal just closes after a couple of lines of output.

**What you expected to happen**:
Get the normal output and terminal stays open.

**How to reproduce it (as minimally and precisely as possible)**:
Run `kind create cluster` in the `st` terminal emulator.

**Anything else we need to know?**:
Verified that this works fine using `gnome-terminal` also works in `st` if I run it with the -q flag so it seems to me that it's the fancy output that `st` does not like.

**Environment:**

- kind version: kind v0.9.0 go1.15.2 linux/amd64

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version: Server Version: 19.03.13

- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.1 LTS

**Comment by BenTheElder** [comment]
What `TERM` does `st` set? is there any way to identify running inside of `st`?

These "fancy" characters are unicode (utf8) + a few VT escape sequences, which should work fine in 2020, but we already automatically disable them in a few known-broken environments (e.g. travis-ci's tty emulation), if it's possible to detect `st` specifically we can add that.

**Comment by bdomars** [comment]
Yeah, this might also be a bug with `st`. They at least have some known issue with Xft causing it to crash with "colored emojis" whatever that means.

TERM is set to `st-256color`
