### ISSUE TITLE
can‘t use kubectl command without --context kind-xxxx after delete one kind cluster

### ISSUE THREAD

**Issue by yushanjin** [kubernetes-sigs/kind#1894]
**What happened**:
can‘t use kubectl command without --context kind-xxxx after delete one kind cluster

**What you expected to happen**:
kubectl get node                     OK

**How to reproduce it (as minimally and precisely as possible)**:
1、kind create cluster --name 1   OK
2、kubectl get node                     OK
3、kind create cluster --name 2   OK
4、kubectl get node                     OK
5、kind delete cluster --name 2   OK
6、kubectl get node  --context kind-1  OK
7、kubectl get node                     NOK

**Anything else we need to know?**:
the whole process:
![image](https://user-images.githubusercontent.com/12782056/96078190-3b96c100-0ee4-11eb-8a09-6bd1bac18253.png)

I don't konw why connect localhost:8080

in ～/.kube/config
![image](https://user-images.githubusercontent.com/12782056/96078275-6e40b980-0ee4-11eb-8e87-375fc32154b9.png)

I think it should connect 127.0.0.1:33253

**Environment:**

- kind version: (use `kind version`):
root@ubuntu:~/kind# kind version
kind v0.9.0 go1.15.2 linux/amd64

- Kubernetes version: (use `kubectl version`):
root@ubuntu:~/kind# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- Docker version: (use `docker info`):
root@ubuntu:~/kind# docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-29-generic
 Operating System: Ubuntu 18.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.852GiB
 Name: ubuntu
 ID: WWRH:IAXZ:4HUX:YWZT:URRK:TKJY:726I:X34A:HZVZ:TNFJ:555A:QTO3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

- OS (e.g. from `/etc/os-release`):
root@ubuntu:~/kind# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by BenTheElder** [comment]
This is expected? If you delete the cluster for which current context is set it unsets the context when it removes the cluster from kubeconfig.

have you experienced different behavior with another tool?

**Comment by BenTheElder** [comment]
>1、kind create cluster --name 1 OK

The current context in kubeconfig is now `kind-1`

> 2、kubectl get node OK
> 3、kind create cluster --name 2 OK

The current context in kubeconfig is now `kind-2`

> 4、kubectl get node OK
> 5、kind delete cluster --name 2 OK

The current context in kubeconfig was `kind-2` but we just deleted `kind-2`, so when we do that the current context becomes `""` (unset).

> 6、kubectl get node --context kind-1 OK

This works because the `kind-1` context still exists. Other contexts may also exist.

> 7、kubectl get node NOK

You can make this work by `kubectl config use-context kind-1`. It doesn't work without doing this because the current context is no longer set.

I'm not aware of any other cluster tools behaving differently, there's no defined behavior for setting another context as the current one outside of cluster creation or the user explicitly setting it (`kubectl config use-context`).

**Comment by yushanjin** [comment]
> > 1、kind create cluster --name 1 OK
> 
> The current context in kubeconfig is now `kind-1`
> 
> > 2、kubectl get node OK
> > 3、kind create cluster --name 2 OK
> 
> The current context in kubeconfig is now `kind-2`
> 
> > 4、kubectl get node OK
> > 5、kind delete cluster --name 2 OK
> 
> The current context in kubeconfig was `kind-2` but we just deleted `kind-2`, so when we do that the current context becomes `""` (unset).
> 
> > 6、kubectl get node --context kind-1 OK
> 
> This works because the `kind-1` context still exists. Other contexts may also exist.
> 
> > 7、kubectl get node NOK
> 
> You can make this work by `kubectl config use-context kind-1`. It doesn't work without doing this because the current context is no longer set.
> 
> I'm not aware of any other cluster tools behaving differently, there's no defined behavior for setting another context as the current one outside of cluster creation or the user explicitly setting it (`kubectl config use-context`).

Thanks, i understand it
