### ISSUE TITLE
DNS lookups fail with ISPs that do NXDOMAIN wildcarding

### ISSUE THREAD

**Issue by sverch** [kubernetes-sigs/kind#1901]
**What happened**:

User has an ISP that does "DNS Wildcarding", i.e. responds to domains that would otherwise be NXDOMAIN with webservers that serve ads.

See [Redirecting DNS for Ads and Profit](https://www.icsi.berkeley.edu/pubs/networking/redirectingdnsforads11.pdf) and [DNS Wildcarding](https://icannwiki.org/Wildcarding).

Kind fails to start with these errors, because it got IP addresses for ad servers instead of NXDOMAIN (which I assume would cause it to fall through the correct path to handle whatever nonexistent local domain it's using for this):

```
Events:
  Type     Reason     Age                   From                       Message
  ----     ------     ----                  ----                       -------
  Normal   Scheduled  13m                   default-scheduler          Successfully assigned cert-manager/cert-manager-cainjector-7976f978f-qtztr to local1-1-worker3
  Warning  Failed     13m                   kubelet, local1-1-worker3  Failed to pull image "quay.io/jetstack/cert-manager-cainjector:v0.14.2": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/jetstack/cert-manager-cainjector:v0.14.2": failed to resolve reference "quay.io/jetstack/cert-manager-cainjector:v0.14.2": failed to do request: Head https://quay.io/v2/jetstack/cert-manager-cainjector/manifests/v0.14.2: dial tcp: lookup quay.io on 23.217.138.110:53: read udp 172.18.0.5:52546->23.217.138.110:53: i/o timeout
  Warning  Failed     13m                   kubelet, local1-1-worker3  Failed to pull image "quay.io/jetstack/cert-manager-cainjector:v0.14.2": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/jetstack/cert-manager-cainjector:v0.14.2": failed to resolve reference "quay.io/jetstack/cert-manager-cainjector:v0.14.2": failed to do request: Head https://quay.io/v2/jetstack/cert-manager-cainjector/manifests/v0.14.2: dial tcp: lookup quay.io on 23.217.138.110:53: read udp 172.18.0.5:50590->23.217.138.110:53: i/o timeout
  Warning  Failed     12m                   kubelet, local1-1-worker3  Failed to pull image "quay.io/jetstack/cert-manager-cainjector:v0.14.2": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/jetstack/cert-manager-cainjector:v0.14.2": failed to resolve reference "quay.io/jetstack/cert-manager-cainjector:v0.14.2": failed to do request: Head https://quay.io/v2/jetstack/cert-manager-cainjector/manifests/v0.14.2: dial tcp: lookup quay.io on 23.217.138.110:53: read udp 172.18.0.5:42254->23.217.138.110:53: i/o timeout
  Normal   Pulling    11m (x4 over 13m)     kubelet, local1-1-worker3  Pulling image "quay.io/jetstack/cert-manager-cainjector:v0.14.2"
  Warning  Failed     11m (x4 over 13m)     kubelet, local1-1-worker3  Error: ErrImagePull
  Warning  Failed     11m                   kubelet, local1-1-worker3  Failed to pull image "quay.io/jetstack/cert-manager-cainjector:v0.14.2": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/jetstack/cert-manager-cainjector:v0.14.2": failed to resolve reference "quay.io/jetstack/cert-manager-cainjector:v0.14.2": failed to do request: Head https://quay.io/v2/jetstack/cert-manager-cainjector/manifests/v0.14.2: dial tcp: lookup quay.io on 23.217.138.110:53: read udp 172.18.0.5:45379->23.217.138.110:53: i/o timeout
  Warning  Failed     11m (x6 over 13m)     kubelet, local1-1-worker3  Error: ImagePullBackOff
  Normal   BackOff    3m50s (x38 over 13m)  kubelet, local1-1-worker3  Back-off pulling image "quay.io/jetstack/cert-manager-cainjector:v0.14.2"
```

CoreDNS pods reporting failures:

```
kubectl logs coredns-5644d7b6d9-d88qh -n kube-system
.:53
2020-09-28T20:21:48.016Z [INFO] plugin/reload: Running configuration MD5 = f64cb9b977c7dfca58c4fab108535a76
2020-09-28T20:21:48.016Z [INFO] CoreDNS-1.6.2
2020-09-28T20:21:48.016Z [INFO] linux/amd64, go1.12.8, 795a3eb
CoreDNS-1.6.2
linux/amd64, go1.12.8, 795a3eb
2020-09-28T20:21:54.022Z [ERROR] plugin/errors: 2 2524305934256981297.6425277095225785637. HINFO: read udp 10.0.0.4:34827->23.202.231.169:53: i/o timeout
2020-09-28T20:21:57.016Z [ERROR] plugin/errors: 2 2524305934256981297.6425277095225785637. HINFO: read udp 10.0.0.4:40448->23.202.231.169:53: i/o timeout
2020-09-28T20:21:58.016Z [ERROR] plugin/errors: 2 2524305934256981297.6425277095225785637. HINFO: read udp 10.0.0.4:47592->23.202.231.169:53: i/o timeout
2020-09-28T20:21:59.017Z [ERROR] plugin/errors: 2 2524305934256981297.6425277095225785637. HINFO: read udp 10.0.0.4:50607->23.202.231.169:53: i/o timeout
2020-09-28T20:22:02.020Z [ERROR] plugin/errors: 2 2524305934256981297.6425277095225785637. HINFO: read udp 10.0.0.4:57676->23.202.231.169:53: i/o timeout
2020-09-28T20:22:05.024Z [ERROR] plugin/errors: 2 2524305934256981297.6425277095225785637. HINFO: read udp 10.0.0.4:43239->23.202.231.169:53: i/o timeout
2020-09-28T20:22:08.025Z [ERROR] plugin/errors: 2 2524305934256981297.6425277095225785637. HINFO: read udp 10.0.0.4:52554->23.202.231.169:53: i/o timeout
2020-09-28T20:22:11.025Z [ERROR] plugin/errors: 2 2524305934256981297.6425277095225785637. HINFO: read udp 10.0.0.4:43889->23.202.231.169:53: i/o timeout
2020-09-28T20:22:14.025Z [ERROR] plugin/errors: 2 2524305934256981297.6425277095225785637. HINFO: read udp 10.0.0.4:57328->23.202.231.169:53: i/o timeout
2020-09-28T20:22:17.026Z [ERROR] plugin/errors: 2 2524305934256981297.6425277095225785637. HINFO: read udp 10.0.0.4:51641->23.202.231.169:53: i/o timeout
```

**What you expected to happen**:

Kind starts and DNS lookups work.

**How to reproduce it (as minimally and precisely as possible)**:

Either have a bad ISP that does this, or point to a DNS server that responds to all queries to nonexistent domains with a webserver ip.

**Anything else we need to know?**:

I don't know if this is the right place for this issue, but I was thinking that kind could check for this case (may be an easy check, look up a domain that shouldn't exist and see what comes back).

**Environment:**

(this wasn't on my machine, but I'll get this information.  We should all be on `v0.9.0` of kind)

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by BenTheElder** [comment]
It looks to me like kind started succesfully but you can't pull custom images?
the DNS resolution in the node's containerd is going to come from the embedded docker resolver https://docs.docker.com/config/containers/container-networking/#dns-services

*kind* does _zero_ DNS lookups.

**Comment by BenTheElder** [comment]
Is the user unable to change their host's DNS service to e.g. 8.8.8.8 or 1.1.1.1 or?

It is by design that kind respects the host's DNS resolution via the embedded DNS. If DNS is broken on the host it's broken for kind running on the host.

It seems like the host's DNS is more generally broken here.

I have tested on an ISP that does NXDOMAIN hijacking and kind works fine there, quay.io should not be NXDOMAIN.

**Comment by aojea** [comment]
>  quay.io should not be NXDOMAIN.

It seems that the problem is that is not able to resolve domains
```
2020-09-28T20:21:54.022Z [ERROR] plugin/errors: 2 2524305934256981297.6425277095225785637. HINFO: read udp 10.0.0.4:34827->23.202.231.169:53: i/o timeout
```

the connection to the dns server is timing out

**Comment by sverch** [comment]
Yup, sorry I should have been more specific.  It looks like somehow coredns gets a bad IP (the IP of these ad servers) for the DNS server that it thinks it can use for lookups, but these ad servers aren't listening on port 53.

```
$ host 23.202.231.169
169.231.202.23.in-addr.arpa domain name pointer a23-202-231-169.deploy.static.akamaitechnologies.com.
```

So somewhere in there, I think there's an unresolvable "local" domain (that's supposed to be unresolvable) used for the DNS server lookup, and the fact that the ISP is returning ad servers instead of just admitting that the domain doesn't exist is intercepting the normal process for how that should work.

I'm not sure where the issue is really coming from, so I'm sorry in advance if this was the wrong place.  It seemed like it could be at least a good user experience thing to test for "bad ISPs" here, so I figured it was worth surfacing.  The workaround is to use some other public DNS servers instead of the ones provided by DHCP.

**Comment by BenTheElder** [comment]
I don't really know where it would make sense for kind to do anything here ... As I said kind itself makes _zero_ DNS lookups today. This is kubernetes + docker + containerd.
I think the user needs to configure non-broken DNS and I don't think there's a logical way for kind to detect this.
KIND is actually designed to work airgapped very well (most users need to obtain a node image + the kind binary, then you can use a local registry or `kind load ...` any application images), where users may not have public DNS at all.

**Comment by sverch** [comment]
Thanks for your comments @BenTheElder.  This makes sense to me.  The root issue is that the user's DNS is misconfigured, even if the reason is unfortunately that their particular ISP misconfigured their DNS without their knowledge.  Since this is a common practice by some ISPs, I'm trying to think of where this defensive check would make sense.  By the time pods are running in the cluster, it seems too late.

Users can check this before running kind by running `nslookup nonexistent.domain` and verifying that we get back `NXDOMAIN` instead of these ad servers.

For anyone looking for this, the workaround is to set your DNS servers to `8.8.8.8` or something that doesn't misbehave.

I'm fine with closing this.  Hopefully now people looking for these errors will find something.  Thanks for maintaining kind, this is a great project!
