### ISSUE TITLE
"kind load docker-image" supports loading multiple images at once

### ISSUE THREAD

**Issue by SataQiu** [kubernetes-sigs/kind#1905]
**What would you like to be added**:
`kind load docker-image` supports loading multiple images at once.
Usage: `kind load docker-image [OPTIONS] IMAGE [IMAGE...]`

**Why is this needed**:
When I create the test cluster using `kind`, I have to import a lot of custom images. It will be much easier if batch operations can be supported.

**Comment by yashvardhan-kukreja** [comment]
I would like to pick this up

**Comment by yashvardhan-kukreja** [comment]
@BenTheElder @aojea should I proceed working on this? Seems like a nice issue to me

**Comment by yashvardhan-kukreja** [comment]
I am thinking something on the lines of this:

```sh
kind load docker-image image1,image2,image3
```
Keeping the multiple images separated by commas

**Comment by yashvardhan-kukreja** [comment]
@SataQiu ,  I am thinking something on the lines of this, let me know if this look good enough to you:

```sh
kind load docker-image image1,image2,image3
```
Keeping the multiple images separated by commas

**Comment by yashvardhan-kukreja** [comment]
@SataQiu That's how the above PR will add the functionality: 

**Usage:** 
Provide multiple images as comma-separated or just provide a single image without commas **(backwards compatibility)**

- Multiple image names provided (all images present locally):
```
kind load docker-image nginx,busybox --name master    

```
- Multiple image names provided (all images are not present locally):
```
kind load docker-image nginx,busybox,python --name master
ERROR: image: "python" not present locally
```
- One image name provided without commas (backwards compatibility):
```
kind load docker-image nginx --name master               

```

Let me know if this is fine

**Comment by BenTheElder** [comment]
As discussed in the PR, the original request usage is for multiple arguments, which seems the most obvious and idiomatic way to handle this. In general something like this should be preferred over in-band signaling cramming multiple things into one argument.

I don't see a compelling reason for the images to be contained in a single argument.
