### ISSUE TITLE
improve instructions for windows

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#191]
The CLI in particular should output valid instructions for setting KUBECONFIG on Windows ideally, this might be a bit tricky as technically you could also be in bash on windows, and this may open a whole can of worms to detect correctly :-)

/kind feature
/priority important-longterm
/help

xref #155 #190

**Comment by alejandrox1** [comment]
Can I take this? Need something cool to get back from the holiday slump :smiley:

**Comment by BenTheElder** [comment]
Sure.

I think we might need some tricky business for this one, depending on what shell the user is in. Can't just use POSIX :(

**Comment by alejandrox1** [comment]
So I've been looking up into this. I'll add some more documentation and will focus mostly on using kind in powershell. Git bash seems to more or less work as expected and the command prompt itself behaves very much like powershell.

Please tell me if there is some other type of environment that you think should be tested :-)

**Comment by BenTheElder** [comment]
I think cmd.exe and powershell are indeed the main targets, but I'm not really a windows developer, let's start there and look for feedback in the future :-)

**Comment by neolit123** [comment]
with this PR the CLI prints shell instructions for Windows:
https://github.com/kubernetes-sigs/kind/pull/326

should the docs include these Windows shell instructions here?
https://github.com/kubernetes-sigs/kind/blob/master/site/content/docs/user/quick-start.md#interacting-with-your-cluster

**Comment by BenTheElder** [comment]
yeah, at least they should link to another section with them, I'm not sure if we want to detail every shell inline there 🤔

**Comment by BenTheElder** [comment]
(note this issue is almost solve, but I want to track which issues would be good to see if we're having them at all. if we're not we should aim to write more well-scoped issues...)

**Comment by neolit123** [comment]
do we still need to track this?

**Comment by BenTheElder** [comment]
I think we're in pretty good shape now.
