### ISSUE TITLE
build node-image with Bazel fails when invoked outside of the Kubernetes source code

### ISSUE THREAD

**Issue by pohly** [kubernetes-sigs/kind#1910]
**What happened**:

A node image build fails when using Bazel and kind is invoked with a current directory that isn't the Kubernetes source code root:
```
$ pwd
/nvme/gopath.tmp/src/github.com/kubernetes-csi/external-provisioner

$ kind build node-image --image csiprow/node:latest --type=bazel --kube-root /home/prow/go/pkg/csiprow.uS36SJL93u/src/kubernetes
...
ERROR: error building node image: command "docker cp bazel-out/k8-fastbuild/bin/cmd/kubelet/kubelet kind-build-1603796560-4097252:/usr/bin/kubelet" failed with error: exit status 1
Command Output: lstat /nvme/gopath.tmp/src/github.com/kubernetes-csi/external-provisioner/bazel-out: no such file or directory
```

Note that `docker cp bazel-out` is using a relative path.

**What you expected to happen**:

It should use an absolute path when accessing `bazel-out`.

**How to reproduce it (as minimally and precisely as possible)**:

Check out Kubernetes master, build a node image while in some other directory.

**Environment:**

- kind version: (use `kind version`): 0.9.0

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1841
