### ISSUE TITLE
`kind get kubeconfig --internal` no longer produce a kubeconfig with internal server ipaddress

### ISSUE THREAD

**Issue by mikeshng** [kubernetes-sigs/kind#1916]
**What happened**:
In `kind v0.7.0`, I can create a cluster and get the kubeconfig with the `--internal` flag and produce a kubeconfig with a server field that is pingable. ie: `server: https://172.17.0.2:6443`
In later version `kind v0.8.0` and `kind v0.9.0`, the kubeconfig that `--internal` flag produces contains a hostname that is not pingable locally. ie: ` server: https://kind-control-plane:6443`

**What you expected to happen**:
I expect it behaves like the `v0.7.0` version where the server field contains a valid ip.

**How to reproduce it (as minimally and precisely as possible)**:
1. download and install the latest (v0.9.0) 
2. `kind create cluster`
3. 
```
$ kind get kubeconfig --internal | grep server
server: https://kind-control-plane:6443
```

**Environment:**

- kind version: (use `kind version`):
```
kind v0.9.0 go1.15.2 linux/amd64
```
- Kubernetes version: (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
```
Server:
 Containers: 85
  Running: 2
  Paused: 0
  Stopped: 83
 Images: 801
 Server Version: 19.03.6
```
- OS (e.g. from `/etc/os-release`):
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by BenTheElder** [comment]
Please search the tracker before filing bugs.

https://github.com/kubernetes-sigs/kind/issues/1558

As kind is alpha and the versions are prerelease, behavior can and will change between versions. In this case it was necessary to make major fixes to networking.

**Comment by BenTheElder** [comment]
Also: internal is for use internal to the docker network, in this context the hostname will work.

If you try to use it externally, it's not supported.
