### ISSUE TITLE
Add support for http for kind create cluster --config

### ISSUE THREAD

**Issue by csantanapr** [kubernetes-sigs/kind#1918]
**What would you like to be added**:
It would be awsome to support `http` for `kind create cluster --config`

**Why is this needed**:
There are many tutorials that require a config for the cluster, this would avoid the end user to download the git repository just to get one file locally to create the cluster, when the rest of the tutorial is using `kubectl` specifying files from the git using `http`

For example this [knative-kind](https://github.com/csantanapr/knative-kind/blob/master/kind/clusterconfig.yaml) tutorial
`kind create cluster --config https://raw.githubusercontent.com/csantanapr/knative-kind/master/kind/clusterconfig.yaml`

**Comment by BenTheElder** [comment]
/triage duplicate
/close
https://github.com/kubernetes-sigs/kind/issues/1300

**Comment by csantanapr** [comment]
Hi @BenTheElder I just found out that `--config` can take stdin 
It would be good to add this to the help, it only indicates a file path
```
kind create cluster -h
Creates a local Kubernetes cluster using Docker container 'nodes'

Usage:
  kind create cluster [flags]

Flags:
      --config string       path to a kind config file
```

**Comment by BenTheElder** [comment]
I haven't seen this explicitly mentioned in similar tools (e.g. kubectl
create -f) ... 🤷‍♂️
If there's a good pattern for this with examples, PRs welcome.
Otherwise expanding upon this in
https://kind.sigs.k8s.io/docs/user/configuration/ might be a good place.
