### ISSUE TITLE
Getting logs out of the kind cluster or on a node

### ISSUE THREAD

**Issue by shreyagr** [kubernetes-sigs/kind#1921]
Hi,

I have been using kind for some time now to be able to  create clusters locally. Now I have a ton of logs that multiple services i deploy to kind log. I want these Console logs to be streamed out of the cluster somehow. Is there any solution for this?

Some way to possibly create a dump of logs on the host machine or even the kind node possibly?

**Comment by BenTheElder** [comment]
`kind export logs` will dump the logs (check `kind help` for more commands, or see our docs...)

streaming log options are not going to be kind specific, there are loads of logging agents for kubernetes, most of them should work fine with kind if  you want to use one.
