### ISSUE TITLE
Random failures of `kind` command

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kind#1927]
This is a very, very rare problem, but I figured I would open anyways

**What happened**:

Ran this command
```
  if ! (kind create cluster --name="${NAME}" --config "${CONFIG}" -v9 --retain --image "${IMAGE}" --wait=60s); then
    echo "Could not setup KinD environment. Something wrong with KinD setup. Exporting logs."
    exit 1
  fi
```

It failed.

Build logs: https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-115_istio_postsubmit/1327320345169891328#1:build-log.txt%3A151

**What you expected to happen**:

Cluster creation succeeds. If does need to fail, it should emit some logging

**How to reproduce it (as minimally and precisely as possible)**:

Not sure. Run 1000s of jobs on kind every day and eventually it might happen. This happens extremely rarely. I would guess less than 1/1000 runs, but really this is an arbitrary guess.

**Anything else we need to know?**:

I believe this failure has happened on other commands than just `kind create cluster`, where the kind binary exits with non-zero status code without any output

**Environment:**

- kind version: (use `kind version`): v0.8.1
- Kubernetes version: (use `kubectl version`): Typically we are deploying 1.19. 
- Docker version: (use `docker info`): 19.03.8, running in Prow on GKE

**Comment by howardjohn** [comment]
> It's failing in less than half a second with no output?
```
2020-11-13T18:40:37.40695306Z + kind create cluster --name=istio-testing --config ./prow/config/trustworthy-jwt.yaml -v9 --retain --image gcr.io/istio-testing/kindest/node:v1.19.1 --wait=60s
2020-11-13T18:40:37.525828071Z + echo 'Could not setup KinD environment. Something wrong with KinD setup. Exporting logs.'
2020-11-13T18:40:37.525855731Z Could not setup KinD environment. Something wrong with KinD setup. Exporting logs.
2020-11-13T18:40:37.525866474Z + exit 1
2020-11-13T18:40:37.525873978Z
2020-11-13T18:40:37.525881264Z real     0m0.442s
2020-11-13T18:40:37.525888724Z user     0m0.380s
2020-11-13T18:40:37.525894729Z sys      0m0.087s
```

Looks like it dies in 100ms or so
> Did something kill it?

Its plausible, but I am not sure what would be doing this. Any idea to get more visibility here?

**Comment by BenTheElder** [comment]
> Its plausible, but I am not sure what would be doing this. Any idea to get more visibility here?

Possibly the init system in either your dind setup or the host, IIRC Kubernetes will only kill a pod not one process but those could kill a process. You could check the system logs (dmesg etc.) if you can get onto the machine.

----

I mean if you trace the binary at -v 9 it should not be possible to run without any output even if an error is encountered, a returned error would be logged, and a panic from some broken code would also produce output.

If an error isn't encountered early in validation one of the first things `kind create cluster does` is log that it's creating the cluster.

At risk of "our code has no bugs!" (0.8.1 certainly does, but I don't think like this), I'd definitely suspect the process is being killed. This reminds me of https://github.com/kubernetes-sigs/kind/issues/1614, which is on my TODO ...

**Comment by howardjohn** [comment]
Oh we are actually for what its worth this is on 0.9.0, I ran the command in the wrong env

**Comment by BenTheElder** [comment]
One thing that may improve this is #1614, in kind v0.10.0+ the remaining thing to do is tweak DIND setups to similarly handle the cgroups better (IIRC istio has it's own image implementing docker in docker, as does kubernetes, neither of which have the cgroups fixups).

**Comment by BenTheElder** [comment]
If you can re-open / re-file with more specifics, please do. As it stands I don't think we have much more actionable I can do here.
