### ISSUE TITLE
How to use local image when constructing .yaml file?

### ISSUE THREAD

**Issue by hazelnutsgz** [kubernetes-sigs/kind#1933]
The thing here is that I want to utilize the locally built image in my yaml file to create&deploy the pod. But I find that the kind master cannot read the docker images on my host machine.(ErrImagePull), I was wondering how to make ```kind``` be aware of the local image on the disk of host machine.

Thanks.

**Comment by BenTheElder** [comment]
Basically we can't share the host filesystem but you can either use a local registry or https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
