### ISSUE TITLE
How to bypass `kind-external-load-balancer` and send req directly to apiserver in HA mode?

### ISSUE THREAD

**Issue by marshtompsxd** [kubernetes-sigs/kind#1934]
Hello Kind developers!
I am using a HA kind cluster and I want to send create/get/list req to some **specific** control plane node (for some testing purpose) **bypassing the load-balancer**.
My cluster has 3 cp nodes and 2 worker nodes:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
- role: worker
```

and there is also a `kind-external-load-balancer` in my cluster:
```
$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                       NAMES
e42a12792e03        kindest/sr:latest              "/usr/local/bin/entr…"   9 minutes ago       Up 9 minutes        127.0.0.1:42221->6443/tcp   kind-control-plane
c3375662a681        kindest/sr:latest              "/usr/local/bin/entr…"   9 minutes ago       Up 9 minutes        127.0.0.1:41501->6443/tcp   kind-control-plane3
1ecbecf51200        kindest/sr:latest              "/usr/local/bin/entr…"   9 minutes ago       Up 9 minutes                                    kind-worker
45c2fc098e95        kindest/haproxy:2.1.1-alpine   "/docker-entrypoint.…"   9 minutes ago       Up 9 minutes        127.0.0.1:45787->6443/tcp   kind-external-load-balancer
b9e762bdfef8        kindest/sr:latest              "/usr/local/bin/entr…"   9 minutes ago       Up 9 minutes                                    kind-worker2
6f918e400ed1        kindest/sr:latest              "/usr/local/bin/entr…"   9 minutes ago       Up 9 minutes        127.0.0.1:43145->6443/tcp   kind-control-plane2
```
And here is what I get when using `kubectl get nodes`
```
$ kubectl get nodes -o wide
NAME                  STATUS   ROLES    AGE     VERSION                          INTERNAL-IP    EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION     CONTAINER-RUNTIME
kind-control-plane    Ready    master   7m52s   v1.18.9-4+9658168a6a638d-dirty   192.168.96.7   <none>        Ubuntu 20.04 LTS   5.3.0-26-generic   containerd://1.3.3-14-g449e9269
kind-control-plane2   Ready    master   7m24s   v1.18.9-4+9658168a6a638d-dirty   192.168.96.6   <none>        Ubuntu 20.04 LTS   5.3.0-26-generic   containerd://1.3.3-14-g449e9269
kind-control-plane3   Ready    master   6m27s   v1.18.9-4+9658168a6a638d-dirty   192.168.96.3   <none>        Ubuntu 20.04 LTS   5.3.0-26-generic   containerd://1.3.3-14-g449e9269
kind-worker           Ready    <none>   5m53s   v1.18.9-4+9658168a6a638d-dirty   192.168.96.5   <none>        Ubuntu 20.04 LTS   5.3.0-26-generic   containerd://1.3.3-14-g449e9269
kind-worker2          Ready    <none>   5m53s   v1.18.9-4+9658168a6a638d-dirty   192.168.96.4   <none>        Ubuntu 20.04 LTS   5.3.0-26-generic   containerd://1.3.3-14-g449e9269
```

I used `client-go` to create two clients specifying the masterURL I want to talk to like below:
```
config1, err := clientcmd.BuildConfigFromFlags("https://192.168.96.7:6443", kubeconfig)
config2, err := clientcmd.BuildConfigFromFlags("https://192.168.96.6:6443", kubeconfig)
clientset1, err := kubernetes.NewForConfig(config1)
clientset2, err := kubernetes.NewForConfig(config2)
```
and use the two clients to send different reqs to k8s cluster.
But later I find that my reqs are not forwarded to the cp nodes I specified in `BuildConfigFromFlags`. It seems to me that`kind-external-load-balancer` can still forward my reqs to different cp nodes even after I explicitly set them in `BuildConfigFromFlags`.

I was wondering how can I bypass the balancer and directly send reqs to cp nodes I want?
Or if it is not caused by balancer, how should I enforce the req sent to the cp nodes I want?

Thank you!

**Comment by BenTheElder** [comment]
#### A bit about kind api server networking:

If your test is running inside docker or the cluster you can access the nodes via `node-name:6443`

If you're on the host, you may need your own proxy process / container if you're on macOS / windows.
If you're on linux, the node IPs are reachable directly, and the api-server is on 6443 on each.

----

> But later I find that my reqs are not forwarded to the cp nodes I specified in BuildConfigFromFlags.

In what way ...? As in you can't reach these addresses? Or the client chooses to use the loadbalancer anyhow?

There's not enough detail here to comment much further.

**Comment by BenTheElder** [comment]
The loadbalancer is a totally seperate non-kubernetes process. It can't enforce anything.

It sounds like what you're saying is client-go is using the KUBECONFIG configured server endpoint anyhow, in which case this is really a client-go question and I don't know the answer, I always configure this via KUBECONFIG or in cluster credential, not like this.

If this is in fact a client-go question, you should probably ask in their issue tracker.

**Comment by marshtompsxd** [comment]
Hello @BenTheElder . Thank you for the reply.

I am running the client on MacOS.

> But later I find that my reqs are not forwarded to the cp nodes I specified in BuildConfigFromFlags.

This is what I did.
I print some logs in the `Create`, `Delete`, `Get` method in `k8s.io/apiserver/pkg/storage/cacher/cacher.go` liek below:
```
func (c *Cacher) Create(ctx context.Context, key string, obj, out runtime.Object, ttl uint64) error {
	if strings.Contains(key, "demo-pod") {
		klog.Infof("create demo-pod")
	}
	return c.storage.Create(ctx, key, obj, out, ttl)
}

func (c *Cacher) Delete(ctx context.Context, key string, out runtime.Object, preconditions *storage.Preconditions, validateDeletion storage.ValidateObjectFunc) error {
	if strings.Contains(key, "demo-pod") {
		klog.Infof("delete demo-pod")
	}
	return c.storage.Delete(ctx, key, out, preconditions, validateDeletion)
}
```
I assume that these methods are the real handlers for the create/delete/get requests.
Then I use the clients connected to cp1 to create/delete/get the `demo-pod` and I the logs from all the apiservers in different cp nodes by `kubectl get logs ...`.
Then I find that the `create demo-pod` and `delete demo-pod` sometimes appear in the logs from other cp nodes rather than cp1.

**Comment by marshtompsxd** [comment]
It seems to me that the client chooses to use the loadbalancer anyhow even if I specify the cp nodes.

**Comment by BenTheElder** [comment]
Your client must be getting that address from somewhere, you could edit the `server` field in a KUBECONFIG file / copy as an alternative.

https://github.com/kubernetes/client-go is the right issue tracker for client-go usage, kind isn't doing anything to your client.
