### ISSUE TITLE
Multiple kind cluster on one host

### ISSUE THREAD

**Issue by morozzArt** [kubernetes-sigs/kind#1941]
Hi! I'm trying an experiment. I want to run two kind on my laptop, but each kind must be in its own docker container. With this, I'm trying to simulate multiple hosts.

However, my clusters don't see each other (I can't ping from one to the control-plane other)

My steps:

1. create a Docker network 15.0.0.0/29
2. run two Docker containers on this network
3. attach to each container
4. Create a kind cluster in each container. One of them has an API address server 15.0.0.2 and the second 15.0.0.3(https://kind.sigs.k8s.io/docs/user/configuration/#api-server)

Am I on the right way? Does kind support what I need?

**Comment by BenTheElder** [comment]
>  but each kind must be in its own docker container.

Do you mean that each kind node is a container (that's accurate), or are you trying to run kind inside docker in docker

If the latter, may I ask why? kind can create multiple clusters against one docker runtime (`kind create cluster --name=cluster2`), and you'll avoid a lot of headaches.

**Comment by morozzArt** [comment]
Yes, docker in docker. For educational purposes only. My ultimate goal is to run two clusters under the control of istio.

Could you give me some tips on how to solve my problem, please?

**Comment by BenTheElder** [comment]
I highly highly recommend eliminating the docker in docker layer, it should be pretty superfluous but it's why they can't see each other. 

If you create two clusters on one host without this they can see each other and you can run istio, the istio project does this in CI.

If you absolutely must keep the docker in docker layers, you'll need to configure the networks all the way down to the node (but not pods / service VIP) to make routing possible. Right now you have multiple network namespaces with the same IP range in their bridges, I don't think that works.

The vastly simpler route is just to create two named clusters without docker in docker. Nesting container runtimes repeatedly has a whole suite of footguns.
