### ISSUE TITLE
secret not generated after creating service account

### ISSUE THREAD

**Issue by rentseen** [kubernetes-sigs/kind#1943]
when I create a service account, with:
`kubectl create serviceaccount test`
and check it with:
`kubectl get sa/test -o yaml`
I got:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "XXX"
  name: test
  namespace: default
  resourceVersion: "XXX"
  selfLink: /api/v1/namespaces/default/serviceaccounts/test
  uid: XXX
```
But it is expected to exist a secret, like described in [doc](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/):
```
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2015-06-16T00:12:59Z
  name: build-robot
  namespace: default
  resourceVersion: "272500"
  uid: 721ab723-13bc-11e5-aec2-42010af0021e
secrets:
- name: build-robot-token-bvbk5
```

Does any one know why? Maybe kind cluster won't start token controller by default?

**Comment by BenTheElder** [comment]
kind configures / bootstraps kubernetes with kubeadm, largely with defaults, it should generally exhibit default kubernetes behavior.

I'm not familiar with this controller.

**Comment by rentseen** [comment]
> kubeadm

It behaves normally after I recreating a new cluster

**Comment by rentseen** [comment]
> kind configures / bootstraps kubernetes with kubeadm, largely with defaults, it should generally exhibit default kubernetes behavior.
> 
> I'm not familiar with this controller.

> kubeadm

Thanks a log, Ben.

It behaves normally after I recreating a new cluster : )

Before recreating cluster, I checked the args of apiserver and controller manager related to service account, but nothing weird found. Further more, I checked the log of controller manger and found some network problems, like:
```
E1128 07:30:01.857030       1 leaderelection.go:321] error retrieving resource lock kube-system/kube-controller-manager: Get "https://172.18.0.4:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s": dial tcp 172.18.0.4:6443: connect: connection refused
```
Have no idea why, but problem is resolved anyway = =

**Comment by SiqingYu** [comment]
Same problem.
I followed the documentation:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

Kind version: `kindest/node:v1.20.2`

**Comment by rentseen** [comment]
> Same problem.
> I followed the documentation:
> https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
> Recreating the cluster fixes the problem.
> 
> Kind version: `kindest/node:v1.20.2`

I used default node image(v1.20.x) to create cluster before. I found the log of controller manger contained some network errors, just like I mentioned in previous comment, which related to leadership election.
I switched to node image(kindest/node:v1.18.15) for the needs of testing, then the problem gone by chance.
Maybe you should try kindest/node:v1.18.15

**Comment by BenTheElder** [comment]
note: images should not be used without the digests published in the release notes, both for security, and for maximally ensuring compatibility with the kind version.  e.g. listed here for v0.11.1 https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1#new-features


when we move registries we will probably change to a tagging scheme including kind version, but today we just try to make sure older kind binaries can continue to use the same tag, but we cannot guarantee this.

the same *digest* will never change, and will always refer to a specific image.

**Comment by cawizca** [comment]
@rentseen Did you figure out this issue?
