### ISSUE TITLE
import docker images from host machine first instead of downloading from internet every time

### ISSUE THREAD

**Issue by infa-ddeore** [kubernetes-sigs/kind#1946]
**What would you like to be added**:
it looks like kind's docker image downloads k8 related docker images whenever it starts, instead can it get the image from host machine, if not found then download from internet? it will save bandwidth and also will be useful with slower or no internet connection

**Why is this needed**:
save bandwidth 
useful with slower or no internet connection i.e. user will pre-download the images or kind will give an option to download all required images on host machine and then import them after creating a cluster

**Comment by BenTheElder** [comment]
You can do this manually. It's not super feasible to do automatically just yet. In the future we may be able to do some magic with containerd mirrors. If it were feasible we'd be doing it already.

See previously:
https://github.com/kubernetes-sigs/kind/issues/1933
https://github.com/kubernetes-sigs/kind/issues/1930#issuecomment-729274124

**Comment by BenTheElder** [comment]
https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

**Comment by infa-ddeore** [comment]
> https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

thx for the quick reply, I do it manually now but not that great experience, will do the same until kind has something :-)
