### ISSUE TITLE
Show Timestamp of created kind cluster

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/kind#1949]
**What would you like to be added**:
Would be helpful if `kind get clusters` can show the age of the created cluster. / Or we can add an option like `-o wide` to get more info.

For eg like,

```
Name                  Age
kind                  30m
capi-quickstart       15m
```

**Why is this needed**:
This can provide a better experience to the end user.

Note: Apologies if I might be missing something if this thing can be acheived through some other command.

**Comment by BenTheElder** [comment]
Please see the contributor guide https://kind.sigs.k8s.io/docs/contributing/getting-started/

In particular, we'd really appreciate a discussion of what this will look like and how it might be implemented etc. *before* sending a PR, so we can discuss what we'd like do here and how it will be supported before you spend a lot of time writing the code and we spend time trying to review it.

I think there's actually a lot to consider here in terms of what the formatting flags should be like, what the default should be like, etc.

For example, if you change the default output, you will break many user scripts.

**Comment by msscaroso** [comment]
@BenTheElder  I think it is safe to assume `kind get clusters` should keep returning the same output as it is today, cause it is a breaking change and the benefits doesn't seem to justify the trouble of doing it.

So, apparently, formatting flags are the way to go. 

Have you thought about it already? Any paths you'd like to explore?

@prankul88 idea `-o wide` is simple and makes sense to follow `kubectl`.

```
  # List all pods in ps output format with more information (such as node name).
  kubectl get pods -o wide  
```

+  We're adding more information (i. e. age)

- `-o wide` is not only adding more information, but also changing the format (i. e. adding a header)


I think we should have something to tell the format contains the column/field names

**Comment by msscaroso** [comment]
Maybe `kind get clusters -l`? 

The current behavior isn't changed:
```
$ kind get clusters
another-kind-cluster
kind
```

And then with the -l (long) flag:

```
$ kind get clusters -l
Name                  Age
kind                  30m
capi-quickstart       15m
```

(Still thinking about the flag design. I know you mentioned about discussing how it is going to be actually implemented, but I'm not there yet)

**Comment by BenTheElder** [comment]
Sorry I personally haven't had much time to put into this and I think the same is true of the other maintainers. 
I've just gotten that bot disable for this repo though, so hopefully this issue will continue to be tracked until it can get proper attention.

**Comment by BenTheElder** [comment]
I don't think there's much demand for this relative to the complexity and the portability issues this would bring so I'm going to close this for now.
