### ISSUE TITLE
Docker support is deprecated in k8s 1.20, how does this affect Kind?

### ISSUE THREAD

**Issue by s3rj1k** [kubernetes-sigs/kind#1951]
Docker support in the kubelet is now deprecated for k8s 1.20, how does this affect Kind?

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#deprecation

**Comment by BenTheElder** [comment]
It doesn't affect KIND at all, the nodes run containerd inside docker, if you're using KIND you've already tested not using dockershim.

**Comment by BenTheElder** [comment]
basically we can run kubernetes *in* docker without running kubernetes *on* docker, and we already do 🙃

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1952

**Comment by BenTheElder** [comment]
https://kind.sigs.k8s.io/ done

**Comment by s3rj1k** [comment]
@BenTheElder Great news. Thanks!
