### ISSUE TITLE
document loadbalancer

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#1961]
**What would you like to be documented**:

It's possible to use a loadbalancer rather effectively on linux by installing metallb.

On mac/windows we should explain the limitations (namely that you can't currently access it cleanly from the host due to docker containers not being routable, only via port forwards), and point to alternatives (like the ingress guide).

It may also be useful to have a high level guide just over how to deal with the network (and no @aojea I'm not talking about crazy hacks, just standard stuff like configuring port forwards, using nodePort, pointing to the ingress / loadbalancer guides, etc.)

/help

**Comment by BenTheElder** [comment]
We have a link in https://kind.sigs.k8s.io/docs/user/resources/#how-to-use-kind-with-metalllb currently, but we should get something upstream and vet that it works with current kind + metallb

cc @mauilion 

Also check this out https://www.thehumblelab.com/kind-and-metallb-on-mac/ ! 
This trick should probably be in there .. cc @ codyde

**Comment by micarlise** [comment]
I would be interested in working on this.  Having just recently figured out getting load balancers to work using metallb and exposing them on mac, 

I would be interested in adding these to the KinD doc site: 

- exposing nodeports to the host
- getting past pending-ip for loadbalancer services
- exposing services to the host on mac.

**Comment by aojea** [comment]
/assign @micarlise 
That sounds great to me

**Comment by micarlise** [comment]
PR #1996

**Comment by jordansissel** [comment]
First time `kind` user (hi!) today, checking in here to report success!

I followed the docs on https://kind.sigs.k8s.io/docs/user/loadbalancer/ (from #1996), and I was successfully able to get `kind` to use my docker network subnet:

```
% kubectl get services elasticsearch-sample-es-http
NAME                           TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
elasticsearch-sample-es-http   LoadBalancer   10.100.120.150   172.18.1.0    9200:30974/TCP   4m27s

% curl -k https://172.18.1.0:9200
{"error":{"root_cause":[{"type":"security_exception",... <remainder omitted>
```

I honestly don't know what metallb is, but the docs, as-is, helped me copy-paste my way to success (LoadBalancer having an address accessible from the docker host itself). 

Nice :)

**Comment by BenTheElder** [comment]
Thanks for the feedback! 🎉 

> I honestly don't know what metallb is, but the docs, as-is, helped me copy-paste my way to success (LoadBalancer having an address accessible from the docker host itself).

Heh, that's great ❤️ 

If you want to know what metallb is, check the first link in the description at the top of the new doc (links to: https://metallb.universe.tf/), I think that has the right details. Basically it's a baremetal loadbalancer project for kubernetes that amongst other things implements `type: LoadBalancer` without necessarily being in a hosted cloud.

I think we can close this now, thanks @micarlise !!

**Comment by BenTheElder** [comment]
and if you haven't seen, check the release notes https://github.com/kubernetes-sigs/kind/releases/tag/v0.10.0#user-content-contributors and https://github.com/kubernetes-sigs/kind/releases/tag/v0.10.0#user-content-new-features

**Comment by kiranchavala** [comment]
Metallab using kind doesn't work on Apple m1 macs

Even after following the guide 
https://www.thehumblelab.com/kind-and-metallb-on-mac/

**Comment by aojea** [comment]
Any clue why?

**Comment by BenTheElder** [comment]
maybe @munnerz knows. amwat and I only have AMD64 hardware still and I don't think aojea uses mac at all.

If you have a more specific pointer to it being a kind issue please file a bug regarding this.
Otherwise I will assume it is a metallb issue and either way not related to this issue.
