### ISSUE TITLE
nginx-controller "Pending": 1 node(s) didn't match node selector

### ISSUE THREAD

**Issue by msgNlswmr** [kubernetes-sigs/kind#1971]
**What happened**:
Hello,

currently I'm learning kubernetes via kind and fail to setup an ingress controller. I use this tutorial as reference:
https://kind.sigs.k8s.io/docs/user/ingress/#using-ingress

In the end, I can't access the pods from localhost.

I assume the kubernetes object
https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
doesnt create the ingress-nginx controller properly, I receive the following message (yes, twice):
 Warning  FailedScheduling  2m3s  default-scheduler  0/1 nodes are available: 1 node(s) didn't match node selector.
 Warning  FailedScheduling  2m3s  default-scheduler  0/1 nodes are available: 1 node(s) didn't match node selector.

**What you expected to happen**:

In the end, I expect to complete the above mentioned tutorial and accees my app via localhost:80/foo.

**How to reproduce it (as minimally and precisely as possible)**:

Just follow the tutorial.

**Anything else we need to know?**:

Nope.

**Environment:**

- kind version:  v0.9.0 go1.15.2 windows/amd64
- Kubernetes version: 1.19.1
- Docker version: 19.03.13
- OS: Windows 10 Build 1809

**Comment by tao12345666333** [comment]
nodeSelector:
        ingress-ready: 'true'
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Equal

It has node selector and toleration, you can change it.

**Comment by BenTheElder** [comment]
Did you create your cluster following the config in the docs? It must have the correct label which requires the kind config.

cc @amwat

**Comment by msgNlswmr** [comment]
@tao12345666333 thanks for pointing out
@BenTheElder You got me therem, thanks! I was scrolling to fast.

**Comment by BenTheElder** [comment]
great! 😅
