### ISSUE TITLE
Upgrading underlying kubernetes version

### ISSUE THREAD

**Issue by Sh4kE** [kubernetes-sigs/kind#1972]
Is there a way to update the kind cluster to a newer kubernetes version without losing all config?
I couldn't find anything in the docs concerning this.

I'm currently running the kindest/node:v1.19.1 and want to upgrade to kindest/node:v1.20.0

**Comment by BenTheElder** [comment]
Not natively, no. You can run a kubeadm upgrade across the nodes if you're connected to the internet and want to do some hacking, but this is not a supported feature.

The intention is for users to re-create the cluster and test software from a clean repeatable state, we optimize for cluster creation speed.
