### ISSUE TITLE
Documentation bug in "using-wsl2.md"

### ISSUE THREAD

**Issue by alandixon** [kubernetes-sigs/kind#1977]
Sorry, not really a bug, but the best label fit available.

Documentation bug in kind/site/content/docs/user/using-wsl2.md
(https://github.com/kubernetes-sigs/kind/blob/master/site/content/docs/user/using-wsl2.md)

At the bottom of the document in the paragraph "Helpful Tips for WSL2"
Your proposed approach "wsl distro --shutdown" throws an error: "/bin/bash: distro: command not found".

<strike>You shutdown a distro with 
`wsl --shutdown <distro>`</strike>
<strike>i.e. the parameter order needs to be reversed.</strike>
This is incorrect, see [my comment below](https://github.com/kubernetes-sigs/kind/issues/1977#issuecomment-752272341)

**Comment by BenTheElder** [comment]
Would you mind sending a PR? WSL2 support is fully community maintained, none of the maintainers are using it currently.

**Comment by aojea** [comment]
/good-first-issue
/help wanted
@alandixon should I assign it to you?

**Comment by alandixon** [comment]
Hi Benjamin,
Sorry, PR?
Alan

**Comment by alandixon** [comment]
Ah yes, good idea, assign it to me, I didn't think of that!

**Comment by BenTheElder** [comment]
Er sorry for the jargon / acronym! Pull request, a patch on GitHub 😅 
If not, we can get to it ourselves eventually as well, docs are important! Currently chasing #1969

**Comment by gunadhya** [comment]
Hi @aojea, I'd like to fix this documentaion bug.

**Comment by aojea** [comment]
@gunadhya go for it, worse case we have 2 PRS ...

**Comment by aojea** [comment]
is there any person using WSL that can confirm what is the right command?
This issue says that `--shutdown` doesn't accept any argument https://github.com/microsoft/WSL/issues/4539

**Comment by alandixon** [comment]
The fix is in my original comment.
This was assigned to me but I was completely unable to push the change back up - it kept giving me an error.
I followed the instructions about signing the CNCF CLA etc. but gave up when that didn't work - it all seemed a bit much for a tiny doc change.
Sorry, I should have unassigned myself earlier - @gunadhya feel free to take this.

**Comment by aojea** [comment]
Thanks Alan

**Comment by alandixon** [comment]
After all that, I got it wrong anyway :(
Running `wsl -?` to see the available commands gives
```
    --shutdown
        Immediately terminates all running distributions and the WSL 2 lightweight utility virtual machine.
    --terminate, -t <Distro>
        Terminates the specified distribution.
```
i.e. it's `--terminate` to shutdown a specific distro, not `--shutdown`

**Comment by aojea** [comment]
why does this work then?
https://github.com/kubernetes-sigs/kind/pull/1994#issuecomment-752096678
