### ISSUE TITLE
[Question] Clarify dependency between docker and kind on mac

### ISSUE THREAD

**Issue by justicezyx** [kubernetes-sigs/kind#1984]
Docker itself cannot launch a local image:
```
$ docker run localhost:5000/http_server:zyx
standard_init_linux.go:219: exec user process caused: exec format error
```

Which suggests the image is not built for linux VM (as part of the docker on mac underlying infrastructure).
But the local Kind cluster actually can execute the image:

```
kubectl run http-server --image=localhost:5000/http_server:zyx
```

I thought Kind uses the same underlying VM as the docker on mac?
Am I wrong?

**Comment by BenTheElder** [comment]
Can you tell us more about the environment and your image?

That docker error can also mean e.g. it was a shell script missing the shebang.

The kind cluster is in the same VM, though the image will run under containerd inside the kind node container inside the VM.

**Comment by BenTheElder** [comment]
Is it possible you updated the image in the registry to fix something? When you create a kind cluster and then run the image the node runtime (containerd) will have to pull the image and if you delete the cluster that storage is gone so when you create it again and create the pod again it will pull again.

When you docker run repeatedly it won't pull repeatedly.

**Comment by justicezyx** [comment]
I tried to reproduce the issue, but it seems gone.

I believe your assessment is likely the cause. Thanks!
