### ISSUE TITLE
Is there any work that try to integrate kind with a network emulator? 

### ISSUE THREAD

**Issue by violetbingzhe** [kubernetes-sigs/kind#1985]
Hello, I am trying to use kind to emulate a Kubernete cluster. But I also want to emulate the physical network between the cluster nodes. For example, using Mininet (http://mininet.org/) to connect the node containers and setup network topology, bandwidth, latency, queue size, etc. 

I am wondering if you've noticed any ongoing work. If not, I may want to work on a solution, and it would be helpful if you could give any hint about where to start. Thanks!

**Comment by aojea** [comment]
This is not a current goal of the project and is difficult to implmenet beause the network depends on the container provider, currently we support Docker that uses `libnetwork` model and podman that uses the `CNI` model.

However, it can be done, you have more details here
https://gist.github.com/aojea/00bca6390f5f67c0a30db6acacf3ea91#example-multiple-network-interfaces-and-multi-home-nodes
and example on how to setup latency, bandwidth, ... here
https://gist.github.com/aojea/603e88ba709aac874bd7611752261772

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/1780 <-- see some discussion here in addition to above comment.

I dont think we're currently prepared to host this, but please discuss in that issue.
