### ISSUE TITLE
failed to create cluster: unable to decode config: yaml: unmarshal errors:

### ISSUE THREAD

**Issue by YatinShah** [kubernetes-sigs/kind#1992]
I get following errors when running config file listed under
  line 4: field featureGates not found in type v1alpha4.Cluster
  line 6: field runtimeConfig not found in type v1alpha4.Cluster

config.yaml=>
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
#cluster wide featureGates, enable for all components ..
featureGates:
  "EphemeralContainers": true
runtimeConfig:
  "api/all": "true"
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "127.0.0.1"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "anyname=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443

------
running Docker Desktop for windows10, with WSL2 - Ubuntu setup.
$> kind version
kind v0.7.0 go1.13.6 linux/amd64
$> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by BenTheElder** [comment]
Your kind version is too old. The docs are for the current release.
