### ISSUE TITLE
pre-load CNI

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#200]
... IE weave, the images and the manifest, so that we can finally run clusters offline / air-gapped

I've started on this.
/assign
/priority important-soon

**Comment by BenTheElder** [comment]
explored options for this further, I think I know which is best but need to implement and verify first... thanks @justinsb !

**Comment by pablochacin** [comment]
@BenTheElder if you have already an idea about this issue. I can help implementing it.

**Comment by BenTheElder** [comment]
thanks @pablochacin, I'm finally putting the finishing touches on the PR, but in case I somehow don't get it in today due to more prow fires:

- add default CNI manifests and images list to pkg/build/node
- install these to well-known paths in the kind node images
- load them at cluster up if present, fallback to our current CNI isntall mechanism if not

**Comment by BenTheElder** [comment]
filed https://github.com/kubernetes-sigs/kind/pull/331
