### ISSUE TITLE
Simplification Wrapper

### ISSUE THREAD

**Issue by Xtigyro** [kubernetes-sigs/kind#2001]
**What would you like to be added**:

A soft wrapper that simplifies further the overall usage of kind - as a separate project.

E.g. - https://github.com/Xtigyro/kindadm.
If considered good enough - I'll be extremely happy to transfer the repo (for better visibility) to `kubernetes-sigs`.

**Why is this needed**:

Enabling easier adoption of kind for local testing by developers.

**Comment by BenTheElder** [comment]
while I believe projects like this are useful to users, there are multiple tools in this space and I don't think we're prepared to endorse any of them by moving them upstream or to participate in them ourselves.

I appreciate you reaching out though!
