### ISSUE TITLE
Kind ingress using Bitnami's nginx-ingress image

### ISSUE THREAD

**Issue by hatzhang** [kubernetes-sigs/kind#2003]
Hi

I am following [kind ingress](https://kind.sigs.k8s.io/docs/user/ingress/)'s instructions to set up ingress. For some reason, i need to install nginx-ingress using [bitnami's helm](https://bitnami.com/stack/nginx-ingress-controller/helm) . 
But when following the manual to the end, and trying the example ingress, it can't be accessed from host.
So how to resolve this? 

> kubectl get svc
NAME                                                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                 AGE
bar-service                                              ClusterIP      10.96.153.134   <none>        5678/TCP                                82m
foo-service                                              ClusterIP      10.96.239.237   <none>        5678/TCP                                82m
kubernetes                                               ClusterIP      10.96.0.1       <none>        443/TCP                                 125m
nginx-ingress-nginx-ingress-controller                   LoadBalancer   10.96.23.82     <pending>     80:31030/TCP,443:31260/TCP              38s
nginx-ingress-nginx-ingress-controller-default-backend   ClusterIP      10.96.155.83    <none>        80/TCP                                  38s
$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS
                      NAMES
127df09c1e1a        kindest/node:v1.19.1   "/usr/local/bin/…"   2 hours ago         Up 2 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 127.0.0.1:36871->6443/tcp   entrade-control-plane

**Comment by aledbf** [comment]
@hatzhang the ingress-nginx example you see in the kind docs is a static manifest yaml. Such manifest is generated with a script from the official chart. Not sure exactly what is done by the bitnami chart, but you can install the chart with the next values.yaml file:

```console
echo ' 
controller:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  hostPort:
    enabled: true
  terminationGracePeriodSeconds: 0
  service:
    type: NodePort
  nodeSelector:
    ingress-ready: "true"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      effect: "NoSchedule"
  publishService:
    enabled: false
  extraArgs:
    publish-status-address: localhost
' > values.yaml

```

**Comment by hatzhang** [comment]
@aledbf   So, if this applied correct, i should have Nodeport type service? Did the following, not working yet. My Kind is in wsl2. If use contor as the manual said, access localhost/bar from browser will work though.

> 
$ helm upgrade nginx-ingress -f values.yaml bitnami/nginx-ingress-controller --dry-run --debug
$ kubectl get svc
NAME                                                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                 AGE
bar-service                                              ClusterIP      10.96.153.134   <none>        5678/TCP                                115m
foo-service                                              ClusterIP      10.96.239.237   <none>        5678/TCP                                115m
kubernetes                                               ClusterIP      10.96.0.1       <none>        443/TCP                                 158m
nginx-ingress-nginx-ingress-controller                   LoadBalancer   10.96.23.82     <pending>     80:31030/TCP,443:31260/TCP              33m
nginx-ingress-nginx-ingress-controller-default-backend   ClusterIP      10.96.155.83    <none>        80/TCP                                  33m
$ curl localhost/bar
curl: (52) Empty reply from server

**Comment by aledbf** [comment]
> nginx-ingress-nginx-ingress-controller LoadBalancer 10.96.23.82 80:31030/TCP,443:31260/TCP 33m

That is not right. Can you uninstall the chart? Also, please test following the steps from the docs, to check it works.

**Comment by hatzhang** [comment]
@aledbf  After check helm show values bitnami/nginx-ingress-controller, i removed 'controller:' and indents of other lines, and i got a Nodeport, but still not working, wonder why

> 
$ kubectl get svc
NAME                                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                 AGE
bar-service                                              ClusterIP   10.96.153.134   <none>        5678/TCP                                3h4m
foo-service                                              ClusterIP   10.96.239.237   <none>        5678/TCP                                3h4m
kubernetes                                               ClusterIP   10.96.0.1       <none>        443/TCP                                 3h47m
nginx-ingress-nginx-ingress-controller                   NodePort    10.96.67.166    <none>        80:31308/TCP,443:30668/TCP              12m
nginx-ingress-nginx-ingress-controller-default-backend   ClusterIP   10.96.148.158   <none>        80/TCP                                  12m
$ kubectl describe  ing/example-ingress
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Name:             example-ingress
Namespace:        default
Address:          localhost
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
              /foo   foo-service:5678   10.244.0.28:5678)
              /bar   bar-service:5678   10.244.0.29:5678)
Annotations:  <none>
$ curl localhost/bar
curl: (52) Empty reply from server

**Comment by aledbf** [comment]
> After check helm show values bitnami/nginx-ingress-controller, i removed 'controller:' and indents of other lines from the values, and i got a Nodeport, but still not working, wonder why

Liek I mentioned, the values I posted are from the official helm chart. Did you test the static manifest to check it works as expected?

**Comment by hatzhang** [comment]
@aledbf  Thanks a lot. There are some differences about bitnami nginx ingress's values.  It went well with the following spec:

```yaml

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
hostNetwork: true
daemonset.useHostPort: true

terminationGracePeriodSeconds: 0
service:
  type: NodePort
nodeSelector:
  ingress-ready: "true"
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    effect: "NoSchedule"
publishService:
  enabled: false
extraArgs:
  publish-status-address: localhost
```

**Comment by BenTheElder** [comment]
Thanks @aledbf !
