### ISSUE TITLE
Support for Apple M1

### ISSUE THREAD

**Issue by venkatrayapudi** [kubernetes-sigs/kind#2005]
I tried installing kind on the new macbook M1 and got below error. I am able to run docker containers on this machine.
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.19.1) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 139
Command Output: SIGSEGV: segmentation violation
PC=0x0 m=0 sigcode=0

goroutine 1 [running]:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

**Comment by neolit123** [comment]
/kind duplicate
/close

https://github.com/kubernetes-sigs/kind/issues/2006
