### ISSUE TITLE
Support for Apple silicon M1

### ISSUE THREAD

**Issue by venkatrayapudi** [kubernetes-sigs/kind#2006]
I tried installing kind on the new macbook M1 and got below error. I am able to run docker containers on this machine.
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.19.1) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 139
Command Output: SIGSEGV: segmentation violation
PC=0x0 m=0 sigcode=0

goroutine 1 [running]:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

**Comment by neolit123** [comment]
if the node image is for AMD64 it will likely just crash on an architecture that is not supported - i.e. ARM64.

**Comment by venkatrayapudi** [comment]
Please note that I have the docker tech preview version installed and able to spin up docker instances on macbook M1. The problem is with kind only.

**Comment by BenTheElder** [comment]
the docker image you're running is AMD64, the pre-built kind images are not multi-arch yet and it will not be trivial to do so.

I'm working on ARM support this quarter, there's an existing bug tracking this #166

**Comment by BenTheElder** [comment]
if you see #166 you can see about obtaining or building an image in the meantime.

**Comment by BenTheElder** [comment]
m1 release is out https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.0#contributors
