### ISSUE TITLE
regression: entrypoint is broken on cgroup v2

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes-sigs/kind#2013]
**What happened**:

`fix_cgroup()` change in https://github.com/kubernetes-sigs/kind/pull/1995/files broke cgroup v2

**What you expected to happen**:
It should work

**How to reproduce it (as minimally and precisely as possible)**:

Minimal repro:
```bash
$ docker build -t kindest/base:latest ./images/base
$ docker run --rm --privileged kindest/base
stat: cannot read file system information for '/kind': No such file or directory
INFO: ensuring we can execute mount/umount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: fix cgroup mounts for all subsystems
$ echo $?
1
```

**Environment:**

- kind version: (use `kind version`): 26637e29987e1759f0bfb6025f335396960c8565 (Jan 19, 2021)
- Ubuntu 20.10, cgroup v2
- moby/moby@0456e058d2, containerd/containerd@092f9e607a0fe430d6daa4dd5d2be9231bf4966e, opencontainers/runc@1a9011689467283662592a54e1e544a310c03967

**Comment by BenTheElder** [comment]
perhaps we should check for v1/v2 and split the paths?
we don't have v2 in CI and this change fixed a number of v1 platforms.

**Comment by BenTheElder** [comment]
I'm also actually not sure if Kubernetes even has any cgroupsv2 CI at all yet, last I checked someone decided that meant we had to use fedora VMs ... which we didn't have a GCE VM image handy for. AFAIK SIG Node never sorted that out.

**Comment by AkihiroSuda** [comment]
PR: https://github.com/kubernetes-sigs/kind/pull/2014
