### ISSUE TITLE
kind and OIDC plugin

### ISSUE THREAD

**Issue by 2327** [kubernetes-sigs/kind#2015]
Hello.

Is kind support OIDC plugin? 
I tried gangway and dex. I receive 500 when gangway requests from kind token for user access.

**Comment by BenTheElder** [comment]
We don't _actively_ support OIDC in particular, but it should work fine similar to another kubeadm cluster, modulo the general networking quirks of running in docker on various platforms.

I'm pretty certain other users have enabled OIDC.

**Comment by BenTheElder** [comment]
See this thread in slack.k8s.io / kuberntes.slack.com: https://kubernetes.slack.com/archives/CEKK1KTN2/p1607097891225700

--- 

Also in general we have more community members with wide range of experience using extensions like this available in our slack, the #kind channel has ~2400 members, I don't think nearly as many people respond to github 🤔 

Perhaps we should update our contact guide ...

---

The general answer is you'll need to configure kubeadm for OIDC using https://kind.sigs.k8s.io/docs/user/configuration/#kubeadm-config-patches

For some idea of the specific OIDC parameters, see the link above, or general kubeadm guides.
For networking: https://kind.sigs.k8s.io/docs/user/ingress/ is a good starting point.

**Comment by BenTheElder** [comment]
note: closing this to manage the tracker as this has a response, but will respond to further comments
