### ISSUE TITLE
Unable to load image using Podman 

### ISSUE THREAD

**Issue by bostrt** [kubernetes-sigs/kind#2027]
**What happened**: Unable to load image using Podman provider:

```
[root@localhost kind]# podman images
REPOSITORY                         TAG      IMAGE ID      CREATED       SIZE
localhost/ovn-daemonset-f          dev      abb63014304d  15 hours ago  634 MB
[root@localhost kind]# kind load docker-image ovn-daemonset-f:dev --name ovn 
enabling experimental podman provider
ERROR: image: "ovn-daemonset-f:dev" not present locally
[root@localhost kind]# kind load docker-image localhost/ovn-daemonset-f:dev --name ovn 
enabling experimental podman provider
ERROR: image: "localhost/ovn-daemonset-f:dev" not present locally
```

**What you expected to happen**: Be able to load image without any workaround (mentioned below).

**How to reproduce it (as minimally and precisely as possible)**:

1. Fresh install Fedora 33
2. Install podman (no docker)
3. clone and build kind
4. build an image using `podman build`
5. check the image exists `podman images`
6. try loading image via kind

**Anything else we need to know?**:
Yes, If I create a symlink like below, I'm able to load image:
```
[root@localhost kind]# ln -s /usr/bin/podman /usr/local/bin/docker

[root@localhost contrib]# kind load docker-image ovn-daemonset-f:dev --name ovn -v 10
enabling experimental podman provider
Image: "ovn-daemonset-f:dev" with ID "abb63014304dfae15ab5c7282b409f8a1b677bf14c6601a04e229ac489f71b29" not yet present on node "ovn-worker", loading...
...
```

**Environment:**

- kind version:
```
[root@localhost kind]# git rev-parse --short HEAD
db37e6cf
[root@localhost kind]# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[root@localhost kind]# kind --version
kind version 0.10.0-alpha+db37e6cfe88729
```

- Podman version:
```
[root@localhost tcpdump-docker]# podman version
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 07:37:50 2020
OS/Arch:      linux/amd64
```

- OS:
```
[root@localhost kind]# cat /etc/redhat-release 
Fedora release 33 (Thirty Three)
```

**Comment by BenTheElder** [comment]
The docker command is docker specific and supposed to be replaced with a generic command but it's unimplemented. The docker-image command will always read from docker and changing that would be breaking behavior for those with both installed.

You can use `kind load image-archive` and `podman save` until the new command is implemented.

The podman driver is still considered experimental and unstable, we're still constantly patching over podman incompatibility.

**Comment by bostrt** [comment]
Many thanks! I'll give the manual podman step a try and fallback to using docker otherwise. 

I'm happy to close this since podman driver is still quite new if you wish.

**Comment by BenTheElder** [comment]
I think we don't actually have a tracking issue for the command, but let me file a new one for that and link back here and tag it for v0.11.0 (v0.10.0 cutting is in progress today). We have some existing discussion in a PR but it didn't wind up making it back into the issue tracker I think.

**Comment by BenTheElder** [comment]
I filed https://github.com/kubernetes-sigs/kind/issues/2038 to outline what I _think_ we should do next regarding this, let's track there for now.

I'd like to see something ship in the next release, the podman support seems to be stabilizing, but this is a missing spot still.

With #2038 I think we can solve this in a way that works well for scripts that are using docker or podman interchangeably (though ironically in kind itself we need special codepaths because some of the more advanced usage is just not interchangable).

**Comment by carrulop** [comment]
Hello. I have the same issue with podman desktop 5.2.2 and latest version kindle: when I create local image with podman build -t nameImage . , and then I do kubectl apply -f app.yaml, it does not find the image.

I checked the image exists in podman, but in app.yaml, where I defined the pod, I put the images name, but there is ErrImagePull error and the pod is not created successfully.

Can anyone help me? Thanks!

**Comment by stmcginnis** [comment]
It would be best to file a new issue rather than commenting on an old, closed one.

But you don't mention loading your image, only building it and then applying a manifest. If you just omitted that step from your description and are still having problems then please open a new issue and include all the details from the issue template and any additional logging output from the image load command.

**Comment by carrulop** [comment]
Thank you, stmcginnis. I have created a new issue here: https://github.com/kubernetes-sigs/kind/issues/3732

Thanks!
