### ISSUE TITLE
Add more options for export command

### ISSUE THREAD

**Issue by dragonly** [kubernetes-sigs/kind#2034]
**What would you like to be added**:
Add more options for `export` command, such as exporting config maps.

**Why is this needed**:
We are using kind as a e2e testing environment in developing TiDB Operator. What always makes us upset is that when something bad happens, we can only exports logs and stuck there. For example, the log says that some config file is missing, but without the configmap we can't see what's really going on.

So I propose that we should add more options for exporting, not just kubeconfig and logs for now, which is awesome though.

**Comment by BenTheElder** [comment]
Is there a reason not to dump your configmaps using tooling that just works using KUBECONFIG?

The logs kind exports are largely not something you can get from the Kubernetes API (node level files that depend on the provider) but your configmaps should be dumpable portably?

**Comment by BenTheElder** [comment]
Closing for now due to lack of response / clarification.
