### ISSUE TITLE
Drop requirement on docker client

### ISSUE THREAD

**Issue by mitar** [kubernetes-sigs/kind#2035]
**What would you like to be added**:

I would suggest that kind should not need a `docker` CLI tool but should embed one and be able to talk directly to `docker.sock`. I do not think there is really a reason to use `docker` CLI tool.

**Why is this needed**:

Just to have Docker images running `kind` smaller because they would not need `docker` CLI tool but just access to `docker.sock`.

**Comment by BenTheElder** [comment]
Kind also supports podman and the docker client library dependency chain will make kind significantly harder to embed in test applications.

Currently the user must supply a functioning podman or docker install, that's it.

The images containing docker cli + kind should not be substantially smaller than docker + kind importing the client as the docker cli is a relatively thin layer over the client logic.

**Comment by BenTheElder** [comment]
Our primary use case is also not running in a docker image, and the kind binarh is very tiny to deliver on its own by having minimal dependencies and binary bloat.

When you mount the docker socket to the container you can also mount the docker binary.

**Comment by BenTheElder** [comment]
see: https://github.com/moby/moby/issues/39302#issuecomment-702406292

While the tone of the comment is a bit much, this part is a major issue -- when using the docker CLI there is substantial compatibility across versions and we can sanely support them. Similarly we can do this for podman across small breaking changes. Currently there is not even a supported client tagging compatibility at all, the versions are purely based on the binary releases, there is no semver.

Pulling in the client-library forfeits this *and* brings that pain on our downstream embedders (tools like cluster-api bootstrapping, kinder, test harnesses, etc.).

**Comment by mitar** [comment]
Thanks for explaining the issues here. I thought docker lib is easier to use.

**Comment by BenTheElder** [comment]
Thanks for understanding!

I think it's pretty easy to use *if* you have full control over the version of docker you're targeting and don't mind fighting with the dependencies a bit (though docker also ships using an out of support version of go still ...). It doesn't support modules yet and has generally been a notoriously painful dependency for us in the kubernetes/kubernetes main project, we're working to eliminate it there.

**Comment by mitar** [comment]
> we're working to eliminate it there.

This is why I would also like to eliminate docker cli. :-)

**Comment by cmoulliard** [comment]
> This is why I would also like to eliminate docker cli. :-)

Should be great to have an universal lightweight client as currently the docker client is quite big `55Mb`
