### ISSUE TITLE
Cannot create cluster through puppet

### ISSUE THREAD

**Issue by chiyiliao** [kubernetes-sigs/kind#2039]
**What happened**:
When I execute "kind create cluster" to create cluster manual, it can be successful.
But when execute "kind create cluster" in puppet script, it occur error!

**What you expected to happen**:
kind should create cluster through puppet without error.

**How to reproduce it (as minimally and precisely as possible)**:

- Step1: create a file 'kind.pp':
-----------------------

class kind(
) {
  exec { 'kind create cluster':
    cwd  => '/tmp',
    path => ['/usr/bin', '/usr/sbin'],
  }
}

include kind

-----------------------

- Step2: execute puppet command
puppet apply kind.pp

**Anything else we need to know?**:
Error log show at below.

**Environment:**
- kind version: (use `kind version`):
kind v0.9.0 go1.15.2 linux/amd64

- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", 

- Docker version: (use `docker info`):
 app: Docker App (Docker Inc., v0.9.1-beta3)
 buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
 Server Version: 19.03.5
 Kernel Version: 4.4.0-177-generic

- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"

### error log 
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.19.1) 🖼  ...
DEBUG: docker/images.go:58] Image: kindest/node:v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600 present locally
 ✓ Ensuring node image (kindest/node:v1.19.1) 🖼
 • Preparing nodes 📦   ...
 ✓ Preparing nodes 📦 
 • Writing configuration 📜  ...
 ✗ Writing configuration 📜
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: file should only be one line, got 2 lines

Stack Trace: 
sigs.k8s.io/kind/pkg/errors.Errorf
	sigs.k8s.io/kind/pkg/errors/errors.go:33
sigs.k8s.io/kind/pkg/cluster/nodeutils.KubeVersion
	sigs.k8s.io/kind/pkg/cluster/nodeutils/util.go:40
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.getKubeadmConfig
	sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config/config.go:170
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.(*Action).Execute.func1.1
	sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config/config.go:82
sigs.k8s.io/kind/pkg/errors.UntilErrorConcurrent.func1
	sigs.k8s.io/kind/pkg/errors/concurrent.go:30
runtime.goexit
	runtime/asm_amd64.s:1374

**Comment by neolit123** [comment]
under puppet, if you pass --retain to "create" kind will keep the node containers running.
what are the contents of `/kind/version`?

you can get that using something like `docker exec kind-control-plane cat /kind/version`

**Comment by chiyiliao** [comment]
The contents of /kind/version is v1.19.1
The cluster only can be create by hand, it will failed when create by puppet.
puppet version is 5.3.2

**Comment by BenTheElder** [comment]
please upgrade to kind v0.10.0, this bug is already fixed.
FYI this means your docker CLI is throwing a warning.

https://github.com/kubernetes-sigs/kind/issues/1288

**Comment by BenTheElder** [comment]
(If I had to guess: the puppet user doesn't have permission to read the DOCKER_CONFIG)

**Comment by chiyiliao** [comment]
It works, puppet can create cluster after upgrade to kind v0.10.0
Thank you very much.

**Comment by chiyiliao** [comment]
> (If I had to guess: the puppet user doesn't have permission to read the DOCKER_CONFIG)

I'm not sure, I don't see relative message in system log.

**Comment by BenTheElder** [comment]
Docker is printing something to stderr when used by the puppet user, it's probably not important (which is why we fixed just ignoring it), but you might want to look. You could probably add and log some other docker call to your puppet setup (I don't use puppet, so I'm not sure exactly how).
