### ISSUE TITLE
Is it possible to access kind CLI inside docker

### ISSUE THREAD

**Issue by joesonw** [kubernetes-sigs/kind#2040]
I'm running kind cluster on a mac. 

And I have a gitlab-runner container running on the same mac. 

Is it possible to for me to load images into kind inside docker with Docker In Docker?

Or has it to be on the host machine?

**Comment by BenTheElder** [comment]
> Is it possible to for me to load images into kind inside docker with Docker In Docker?

I don't recommend running kind in docker in docker, however it is possible to do, including loading images.

However, you're going to want the image reading portion to talk to the docker with the images, and the writing portion must talk to the kind nodes and the docker running that.

If your images are in the docker-in-docker then proceed as normal, running the kind binary there against that socket.

If you have images on the *host* docker and you wish to sideload them to a nested setup, you can use `docker save` on the host piped to `kind load image-archive`, and you'll need to sort out how to have a shell in the nested environment + host environment.

The overhead of this setup is not great, and I don't recommend adding additional nesting. 

The phrase "docker in docker" is a little overloaded though, It's not clear from your post what the exact nesting and layout is. If you provide more detail I can also provide more about what you need.


For example typical kind nesting looks like this:
<img width="519" alt="Screen Shot 2021-01-27 at 7 13 56 PM" src="https://user-images.githubusercontent.com/917931/106084774-d2723c80-60d3-11eb-82b7-4677be343847.png">
(https://kind.sigs.k8s.io/docs/user/resources/#deep-dive-kind--benjamin-elder--antonio-ojea)

**Comment by joesonw** [comment]
@BenTheElder Thank you for the detailed explanation. My understanding is that `kind load image` solely talks to `docker.sock`, does it talk to the `kind nodes` (kind-control-plane, kind-worker)?

**Comment by BenTheElder** [comment]
`kind load docker-image` needs to talk to the docker daemon on which the nodes are running.
it then talks to the container runtime *inside* the nodes over this connection.
it also needs to check the image ID from the docker daemon for the desired image against the present images on the nodes, and then potentially save and stream in the image.

if your image is in one daemon and the nodes are in another, you can't just `kind load docker-image` because it needs to talk to _two_ dockerd. if your images are in the dockerd running the nodes, you can just `kind load docker-image`.

**Comment by BenTheElder** [comment]
so without docker in docker: if I `kind create cluster` and then I `docker build -t foo:bar ...` I can `kind load docker-image foo:bar`. 

but if I ran kind in docker-in-docker and built the image on the host / outer docker, I'd need to `docker save` against the host docker and then pass that along to `kind load image-archive` on the inner docker-in-docker.

**Comment by joesonw** [comment]
@BenTheElder I see. Thanks. I'll give it a shot.

**Comment by BenTheElder** [comment]
closing this for now, but will keep an eye out for further comments ...
