### ISSUE TITLE
[Docker Desktop - Mac] custom apiServerAddress doesn't work, goes to 127.0.0.1

### ISSUE THREAD

**Issue by lcostea** [kubernetes-sigs/kind#2046]
**What happened**:
Using a configuration like this:
```
  apiServerAddress: 192.168.1.231
  apiServerPort: 6443
```
where 192.168.1.231 is my local IP address, to start a cluster, in kubeconfig I get 127.0.0.1 and a dynamic port. When I try to `kubectl get pods` I get:
`The connection to the server 127.0.0.1:55001 was refused - did you specify the right host or port?`

**What you expected to happen**:
To have the api server working on my local IP, so I can access it from other local kind clusters.

This was working back in Aug/Sep 2020 (with kind 0.9.0), but probably after I upgraded to newer docker version it stopped working.

I tried it with kind 0.9.0 and it wasn't working, then I upgraded to 0.10.0 but the issue remained.

**How to reproduce it (as minimally and precisely as possible)**:

create a cluster with a custom api server, like the local ip and you will not be able to access it at all (with any kubectl command).

**Anything else we need to know?**:
This is similar to what is described in https://github.com/kubernetes-sigs/kind/issues/1732
and the workaround specified there it is working, if I run the below command I can access the kind-test-cluster:
`kubectl config set clusters.kind-test-cluster.server https://192.168.1.231:6443`

**Environment:**

- kind version: (use `kind version`): kind v0.10.0 go1.15.7 darwin/amd64
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 324
  Running: 4
  Paused: 0
  Stopped: 320
 Images: 300
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 2.925GiB
 Name: docker-desktop
 ID: HXK4:527I:KPMC:534P:QJNE:JLOS:HNJH:4A67:XGN5:P6S3:6KR4:OSDV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 73
  Goroutines: 70
  System Time: 2021-01-30T18:04:47.574258206Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`): macOS Catalina 10.15.7

**Comment by BenTheElder** [comment]
Is that your entire configuration? Because that snippet alone is invalid.
https://kind.sigs.k8s.io/docs/user/configuration/

**Comment by lcostea** [comment]
This is the configuration:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 192.168.1.231
  apiServerPort: 6443
```
The command to create the cluster:
```
kind create cluster --name dev-cluster --config kind-configs/dev-cluster.yaml
```

You can see it in this repo: https://github.com/lcostea/argocd-config/blob/master/docs/2-add-external-clusters.md (number 2)

**Comment by lcostea** [comment]
Created this gist with additional info: https://gist.github.com/lcostea/3a19e731a9f0e13f5e1a1541bfe6f9cb

It seems that the label `desktop.docker.io/ports/6443/tcp` is missing. I couldn't find anywhere any reference to the ip I used `192.168.1.231`.

I could dig more on how to workaround this, but I ran out of ideas. 

Good thing is that https://github.com/docker/for-mac/issues/4541 seems will get fixed in the next version of docker for mac.

**Comment by BenTheElder** [comment]
if it is indeed https://github.com/docker/for-mac/issues/4541 we already merged https://github.com/kubernetes-sigs/kind/pull/1785 so ... 🤔

**Comment by lcostea** [comment]
In https://github.com/docker/for-mac/issues/4541#issuecomment-748273314 they say the label is gone, so it looks like the fix from https://github.com/kubernetes-sigs/kind/pull/1785 stopped working for 20.10 version. At least that's my understanding and running docker inspect confirmed no such label `desktop.docker.io/ports/6443/tcp` is present

**Comment by BenTheElder** [comment]
Are you able to roll back or switch to the fixed version? From https://github.com/docker/for-mac/issues/4541#issuecomment-766694535 it seems this is being fixed upstream.

**Comment by BenTheElder** [comment]
The upstream fix should be out now https://github.com/docker/for-mac/issues/4541#issuecomment-791568088
