### ISSUE TITLE
kindnet: Ability to turn off the IP masquerade?

### ISSUE THREAD

**Issue by podusowski** [kubernetes-sigs/kind#2051]
Hi,
do you have any plans for adding an option for turning off the IP masquerading for specific subnets or be willing to accept such PR? Something like ip-masq-agent already does with `nonMasqueradeCIDRs` or by it's default configuration:

> By default, the agent is configured to treat the three private IP ranges specified by RFC 1918 as non-masquerade CIDR. These ranges are 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16.

Why I need it?
I'm setting up a testing environment for the telco solution were we use Multus to setup multiple NICs so we basically have multuple subnets in our cluster.

**Comment by BenTheElder** [comment]
Not currently, no.

> I'm setting up a testing environment for the telco solution were we use Multus to setup multiple NICs so we basically have multuple subnets in our cluster.

And you're not using multis-CNI?
You can disable kindnetd and use your own currently (though we don't actively support any of the alternatives).

You can also pick a different CIDR for the pod / service subnets if you want to use non-private ranges in kind.

**Comment by podusowski** [comment]
Ah yes, I can disable kindnet all together and use something else. I'll give it a shot, thank you!
