### ISSUE TITLE
Error creating cluster under WSL2

### ISSUE THREAD

**Issue by vipseixas** [kubernetes-sigs/kind#2053]
**What happened**:
The same symptoms of #1288, kindest/node container is exiting during "Writing configuration" stage.

**How to reproduce it (as minimally and precisely as possible)**:
Just tried to create the cluster:

> $ kind create cluster -v 1 --retain --name wslkind
Creating cluster "wslkind" ...
DEBUG: docker/images.go:58] Image: kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab present locally
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼
 ✓ Preparing nodes 📦
 ✗ Writing configuration 📜
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged wslkind-control-plane cat /kind/version" failed with error: exit status 1
Command Output: Error response from daemon: Container 763db2d5b1f0c065a9d48f2745b3f3157cf2980cc08d5e0eeab7c5ae96059c8c is not running
Stack Trace:
sigs.k8s.io/kind/pkg/errors.WithStack
        /home/suporte/go/pkg/mod/sigs.k8s.io/kind@v0.10.0/pkg/errors/errors.go:51
sigs.k8s.io/kind/pkg/exec.(*LocalCmd).Run
        /home/suporte/go/pkg/mod/sigs.k8s.io/kind@v0.10.0/pkg/exec/local.go:124
sigs.k8s.io/kind/pkg/cluster/internal/providers/docker.(*nodeCmd).Run
        /home/suporte/go/pkg/mod/sigs.k8s.io/kind@v0.10.0/pkg/cluster/internal/providers/docker/node.go:146
sigs.k8s.io/kind/pkg/exec.OutputLines
        /home/suporte/go/pkg/mod/sigs.k8s.io/kind@v0.10.0/pkg/exec/helpers.go:81
sigs.k8s.io/kind/pkg/cluster/nodeutils.KubeVersion
        /home/suporte/go/pkg/mod/sigs.k8s.io/kind@v0.10.0/pkg/cluster/nodeutils/util.go:35
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.getKubeadmConfig
        /home/suporte/go/pkg/mod/sigs.k8s.io/kind@v0.10.0/pkg/cluster/internal/create/actions/config/config.go:172
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.(*Action).Execute.func1.1
        /home/suporte/go/pkg/mod/sigs.k8s.io/kind@v0.10.0/pkg/cluster/internal/create/actions/config/config.go:84
sigs.k8s.io/kind/pkg/errors.UntilErrorConcurrent.func1
        /home/suporte/go/pkg/mod/sigs.k8s.io/kind@v0.10.0/pkg/errors/concurrent.go:30
runtime.goexit
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:1357

Docker logs:

> $ docker logs 763db2d5b1f0
INFO: ensuring we can execute mount/umount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: detected cgroup v1
INFO: fix cgroup mounts for all subsystems
INFO: ensuring we can execute mount/umount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: detected cgroup v1
INFO: fix cgroup mounts for all subsystems

Kind logs:

> $ kind export logs --name wslkind
ERROR: [command "docker exec --privileged wslkind-control-plane sh -c 'tar --hard-dereference -C /var/log/ -chf - . || (r=$?; [ $r -eq 1 ] || exit $r)'" failed with error: exit status 1, [command "docker exec --privileged wslkind-control-plane journalctl --no-pager -u kubelet.service" failed with error: exit status 1, command "docker exec --privileged wslkind-control-plane journalctl --no-pager -u containerd.service" failed with error: exit status 1, command "docker exec --privileged wslkind-control-plane journalctl --no-pager" failed with error: exit status 1, command "docker exec --privileged wslkind-control-plane cat /kind/version" failed with error: exit status 1]]

**Anything else we need to know?**:

I followed what was suggested here: https://github.com/kubernetes-sigs/kind/issues/1288#issuecomment-631673479
Used a earlier version of kindest/node and it worked:

> ~$ kind create cluster -v 1 --retain --image kindest/node:v1.18.2 --name wslkind2
Creating cluster "wslkind2" ...
DEBUG: docker/images.go:67] Pulling image: kindest/node:v1.18.2 ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-wslkind2"
You can now use your cluster with:
>
> kubectl cluster-info --context kind-wslkind2
>
> Thanks for using kind! 😊

**Environment:**
Running inside WSL2 with 
- Kind v0.10.0 go1.13.8
- Ubuntu 20.04.2
- Docker 20.10.3, build 48d30b5
- Kubectl client v1.20.2 / server v1.18.2

**Comment by BenTheElder** [comment]
The maintainers don't use / have WSL2 (and it seems we can't get it in CI easily) but we have a guide from the community here in the docs: https://kind.sigs.k8s.io/docs/user/using-wsl2/

Does your setup match the guide?

**Comment by vipseixas** [comment]
> 
> 
> The maintainers don't use / have WSL2 (and it seems we can't get it in CI easily) but we have a guide from the community here in the docs: https://kind.sigs.k8s.io/docs/user/using-wsl2/
> 
> Does your setup match the guide?

Yep, it matched the guide. But I played around with my installation and I can't reproduce the error anymore. I also installed minikube with some dependencies, maybe it solved the problem...

I'll close the issue since it is not reproducible anymore.

**Comment by BenTheElder** [comment]
Please let us know if you run into this again, thanks!

**Comment by pecigonzalo** [comment]
I'm facing the same issue and the same workaround (using `--image kindest/node:v1.18.2`) has worked for me. Anything I can add here?

Same config, same setup.
