### ISSUE TITLE
Add an example on how to run kind from another Go program for UT

### ISSUE THREAD

**Issue by krish7919** [kubernetes-sigs/kind#2054]
I am trying to spin up kind during my UT setup, and it is unclear so far how to set this up.

The options to create the cluster are in a an `internal` package and the other option is to pass an `io.Reader` interface. This is very unfriendly, esp when I was expecting this will be a few minutes worth of effort.

Are there any plans to provide a proper Go API?

**Comment by BenTheElder** [comment]
The ClI only uses the public APIs with the same "unfriendly" restrictions as any other user, there are public APIs to supply the public config API type, this is a standard Kubernetes pattern to split a versioned component API into the public versions and the internal intermediate version that converts between them and is passed to implementation as a singular type.

We have a real go API 🙃

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/tree/master/pkg/apis/config

https://github.com/kubernetes-sigs/kind/tree/master/pkg/cluster

https://pkg.go.dev/sigs.k8s.io/kind/pkg/cluster#CreateWithV1Alpha4Config

**Comment by BenTheElder** [comment]
You can see usage of the API (modulo this one option as the CLI must instead provide the text and let the internals handle multiple API versions using a different option) in the CLI packages (also importable) under cmd/, with directories structured to match the commands

**Comment by krish7919** [comment]
Yeah, I wanted to avoid the file creation and copy, but I guess there is on way around it.

**Comment by BenTheElder** [comment]
> Yeah, I wanted to avoid the file creation and copy, but I guess there is on way around it.

https://pkg.go.dev/sigs.k8s.io/kind/pkg/cluster#CreateWithV1Alpha4Config ?

You don't need a file, you can do this purely in memory with the actual data structure.

**Comment by krish7919** [comment]
Got it. Thanks!

I didn't go through the source properly before.

**Comment by krish7919** [comment]
To make life easier for anyone in the future, this is what I have done (still untested):

##### Initialize the logging infra for kind:

```
// KindLogger implements the Logger interface
type KindLogger struct {
	logger     logrus.FieldLogger // since I am using logrus
	infoLogger KindInfoLogger
}

// Warn meets the Logger interface but does nothing
func (k KindLogger) Warn(message string) {
	k.logger.Warn(message)
}

// Warnf meets the Logger interface but does nothing
func (k KindLogger) Warnf(format string, args ...interface{}) {
	k.logger.Warnf(format, args)
}

// Error meets the Logger interface but does nothing
func (k KindLogger) Error(message string) {
	k.logger.Error(message)
}

// Errorf meets the Logger interface but does nothing
func (k KindLogger) Errorf(format string, args ...interface{}) {
	k.logger.Errorf(format, args)
}

// V meets the Logger interface but does nothing
func (k KindLogger) V(level log.Level) (l log.InfoLogger) {
	l = k.infoLogger
	return
}

// KindInfoLogger implements the InfoLogger interface
type KindInfoLogger struct {
	logger logrus.FieldLogger
}

// Enabled meets the InfoLogger interface but always returns false
func (k KindInfoLogger) Enabled() bool { return true }

// Info meets the InfoLogger interface but does nothing
func (k KindInfoLogger) Info(message string) {
	k.logger.Info(message)
}

// Infof meets the InfoLogger interface but does nothing
func (k KindInfoLogger) Infof(format string, args ...interface{}) {
	k.logger.Infof(format, args)
}
```

##### Start the cluster:

```
func RunKindInstance(logger logrus.FieldLogger) {
	kindLogger := KindLogger{logger: logger}

	providerOptions := []cluster.ProviderOption{
		cluster.ProviderWithLogger(kindLogger),
	}

	provider := cluster.NewProvider(providerOptions...)

	err := provider.Create(clusterName,
		cluster.CreateWithV1Alpha4Config(&v1alpha4.Cluster{Name: clusterName}),
		cluster.CreateWithNodeImage("kindest/node:v1.15.12"),
		// Delete resources on failures
		cluster.CreateWithRetain(false),
		cluster.CreateWithWaitForReady(120*time.Second),
		cluster.CreateWithDisplayUsage(true),
		cluster.CreateWithDisplaySalutation(true),
	)
	if err != nil {
		logger.WithError(err).Fatal("failed to create kind cluster")
	}
	return
}
```

##### Stop the cluster:

```
func StopKindInstance(logger logrus.FieldLogger) {
	kindLogger := KindLogger{logger: logger}

	providerOptions := []cluster.ProviderOption{
		cluster.ProviderWithLogger(kindLogger),
	}

	provider := cluster.NewProvider(providerOptions...) // OR you can reuse the provider from above by returning it

	err := provider.Delete(clusterName, "~/.kube/config")
	if err != nil {
		logger.WithError(err).Fatal("failed to delete kind cluster")
	}
	return
}
```

**Comment by BenTheElder** [comment]
thanks for sharing! and sorry for the terse responses ... lot going on lately.

you can also provide a nil and we'll simply not log if you don't care about the logs, without the source-code verbosity of adapting it to your preferred logging solution.

We know some people want the logs, so we have the interface patterned after `klog` (kubernetes's log package based on `glog`) without actually pulling that in as a dependency as it has some not so great behavior wrt globals.
