### ISSUE TITLE
Can Kind on DockerDesktop support linux/windows mixed k8s cluster?

### ISSUE THREAD

**Issue by hatzhang** [kubernetes-sigs/kind#2056]
Though the manual said not. But if Kind is based on DockerDesktop, and DockerDesktop support linux/windows mixed containers to run simultaneously either with Swarm mode or with Windows container mode with some experimental feature turned on. So maybe this can work? Another question might be does Kind support create k8s cluster accross physical/virtual machines.

**Comment by BenTheElder** [comment]
Windows nodes that are containers are not possible, windows containers don't work like Linux containers and you can't run "docker in docker" style tricks in them. It is not possible for us to support KIND style windows nodes. 

kind is for local test clusters and does not support creating clusters across machines, for that there are many production cluster tools under SIG cluster lifecycle.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/410

https://kind.sigs.k8s.io/
https://kind.sigs.k8s.io/docs/contributing/project-scope/

**Comment by hatzhang** [comment]
@BenTheElder  So is that possible to configure a windows worker node, and join it with Kind's master node, using tools like [k0s](https://docs.k0sproject.io/v0.11.0/experimental-windows/)

**Comment by BenTheElder** [comment]
I don't work with downstream projects like this.

It is possible to join a node with `kubeadm join` but it's not something that fits into kind to support built in as it can't be a container node currently due to windows container limitations.
You will have to sort out synchronizing the credentials and the networking details.
