### ISSUE TITLE
How to build a node image with preloaded docker images 

### ISSUE THREAD

**Issue by hatzhang** [kubernetes-sigs/kind#2063]
Is there a way to build a node image with some preloaded docker images/tars, then when the cluster is created with ``` kind create cluster --image ```, those docker images will need not be pulled inside or loaded into kind.

**Comment by BenTheElder** [comment]
This is not supported currently. It's possible to reproduce what kind does internally, but you'd have to do it yourself, and it's going to be clunky and brittle (you can't do this in a normal `docker build` for example).

I recommend just using a local registry, or saving all the images you want to a tarball (e.g. `docker save`) so you can load them in one-shot with `kind load image-archive`.

**Comment by dkoshkin** [comment]
I have the same use-case, for air-gapped installations it would be great to be able to build a custom image with additional images pre-loaded.
I would be happy to work on this, please let me know.

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes-sigs/kind/issues/2160 for current discussion 😅

**Comment by nitishm** [comment]
I noticed this PR as well - https://github.com/kubernetes-sigs/kind/pull/2303. Wonder if this might be something that I could try? I essentially want to prime by kind node with some docker images to speed up my CI pipeline (since pulling images takes a lot of time at the moment leading to slow tests)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/2303 is the current in-review PR for issue #2160.

**Comment by BenTheElder** [comment]
You will still have to pull down the content of course, the total download size is not easily decreased, but it can be done at a different point in the process (arguably one that is less concurrent and not necessarily net improvement in performance, unless you are managing to cache images at the CI level, in which case it may be a big win)
