### ISSUE TITLE
Create Cluster fails on Apple M1 Mac with Segmentation fault

### ISSUE THREAD

**Issue by tonit** [kubernetes-sigs/kind#2078]
**What happened**:
Running `kind create cluster`` results in: 
```
❯ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 139
Command Output: qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```
**What you expected to happen**:
A cluster being created.

**How to reproduce it (as minimally and precisely as possible)**:
Install kind via Homebrew:
> Get M1 Mac with latest Mac OS 11.3
> brew install kind 

**Anything else we need to know?**:
Docker for Mac ARM preview

**Environment:**

- kind version: (use `kind version`): kind v0.10.0 go1.16beta1 darwin/arm64
- Kubernetes version: (use `kubectl version`): v1.19.3
- Docker version: (use `docker info`):  20.10.1
- OS (e.g. from `/etc/os-release`): Mac OS 11.3

**Comment by neolit123** [comment]
tracked here:
https://github.com/kubernetes-sigs/kind/issues/2078

/remove-kind bug
/kind feature

**Comment by BenTheElder** [comment]
kind supports x86 OOTB for now, multi-arch is coming but a little more involved than it sounds.
additionally upstream in Kubernetes vendors interested in non-x86 have not put effort into ensuring we have release qualification, so it will at best be best effort in kind, as kubernetes makes no guarantees about non-x86 before release.

SIG release is working on platform support tiering officially in Kubernetes to clarify this and motivate fixing this. https://github.com/kubernetes/sig-release/issues/1337

**Comment by BenTheElder** [comment]
The kubernetes client binaries etc also do not have official support on M1 yet, as go1.16 only just released the other day

**Comment by BenTheElder** [comment]
> tracked here:
> #2078

https://github.com/kubernetes-sigs/kind/issues/166 *

**Comment by tonit** [comment]
ok, thanks for clarification.

**Comment by BenTheElder** [comment]
It's possible to build your own images for other architectures (see the user guide to build an image for your current architecture) but we do not do this by default for the node images _yet_, it will take some more work to make that sustainable.

**Comment by cocoonkid** [comment]
+1

**Comment by BenTheElder** [comment]
#2176 is the main remaining piece. I've been out a bit but will be finishing it up. Then we'll cut v0.11.0

**Comment by egandro** [comment]
I can confirm and repicate this on an Alpine Linux (x86_64) image.

Alpine Linux lacks of a glibc.

Willing to test if there are updates.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.0#contributors

**Comment by cocoonkid** [comment]
wohoo! Thanks!
