### ISSUE TITLE
Kind reports success even when kube-scheduler never starts

### ISSUE THREAD

**Issue by vinayakankugoyal** [kubernetes-sigs/kind#2095]
**What happened**:
kind reports success for control-plane start even though kube-scheduler container is exited.

**What you expected to happen**:
kind to report failure to start control-plane

**How to reproduce it (as minimally and precisely as possible)**:
1. Forced kube-scheduler to run as non root, so it would fail with permissions denied error in kubeadm. 
2. Then I built this image using `kind build node-image --type docker` 
3. Then I created a cluster using kind create cluster --image kindest/node:latest
4.  I saw the following
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:latest) 🖼
 ✓ Preparing nodes 📦
✓ Writing configuration 📜 
✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
5. Upon execing into the control plane container using `docker exec -it kind-control-plane /bin/bash`
6. And running `crictl ps -a` I noticed
```
CONTAINER           IMAGE               CREATED              STATE               NAME                      ATTEMPT             POD ID
3fa084ccd0636       8a497144b9856       3 seconds ago        Exited              kube-scheduler            4                   2ab59e3b7b5bd
733493747108c       dfbe1d03412b4       About a minute ago   Running             kube-controller-manager   0                   ab902ad92b5ae
b6546011082a8       6c15fb5b6f2f9       About a minute ago   Running             kube-apiserver            0                   b5fda9c84f69d
53698f2bbaf3e       0369cf4303ffd       About a minute ago   Running             etcd                      0                   5922eda405a82
```
**Anything else we need to know?**:
Feel free to ping me if you need more details. Happy to help! 👍🏾 

**Environment:**

- kind version: (use `kind version`): kind v0.10.0 go1.16 linux/amd64
- Kubernetes version: (use `kubectl version`): choose not to disclose
- Docker version: (use `docker info`): choose not to disclose
- OS (e.g. from `/etc/os-release`): chose not to disclose

**Comment by BenTheElder** [comment]
You can use `--wait=1m` if you want to wait for control plane ready. KIND exiting before this otherwise is working as intended.

When testing in CI the tests will catch this.

When doing local development you can easily monitor this yourself. But when developing a Kubernetes app blocking on this is wasted time. Note that kubeadm underneath also does not block on this.
