### ISSUE TITLE
Kind onable to join worker nodes on RHEL 8.3 with podman

### ISSUE THREAD

**Issue by jagusztinl** [kubernetes-sigs/kind#2099]
**What happened**:
Kind create cluster failure

**What you expected to happen**:
create cluter
**How to reproduce it (as minimally and precisely as possible)**:
kind create cluster  --config kind-cluster.yaml

yaml:
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
- role: worker

**Anything else we need to know?**:

**Environment:**
RHEL 8.3

- kind version: (use `kind version`):
- kind v0.10.0 go1.15.7 linux/amd64

- Kubernetes version: (use `kubectl version`):
lient Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- Docker version: (use `docker info`):
[root@localhost kind]# podman info
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.22-3.module+el8.3.1+9857+68fb1526.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.22, commit: a40e3092dbe499ea1d85ab339caea023b74829b9'
  cpus: 6
  distribution:
    distribution: '"rhel"'
    version: "8.3"
  eventLogger: file
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-240.el8.x86_64
  linkmode: dynamic
  memFree: 2159112192
  memTotal: 5953191936
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rc92.module+el8.3.1+9857+68fb1526.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 6225129472
  swapTotal: 6289354752
  uptime: 1h 35m 11.39s (Approximately 0.04 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 2
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: "2"
  Built: 1612819146
  BuiltTime: Mon Feb  8 22:19:06 2021
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.2.1

- OS (e.g. from `/etc/os-release`):
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3"

Error:
enabling experimental podman provider
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼 
 ✓ Preparing nodes 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✗ Joining worker nodes 🚜 
ERROR: failed to create cluster: failed to join node with kubeadm: command "podman exec --privileged kind-worker kubeadm join --config /kind/kubeadm.conf --skip-phases=preflight --v=6" failed with error: exit status 1
Command Output: I0228 18:42:31.893356     384 join.go:395] [preflight] found NodeName empty; using OS hostname as NodeName
I0228 18:42:31.893455     384 joinconfiguration.go:74] loading configuration from "/kind/kubeadm.conf"
I0228 18:42:31.894668     384 controlplaneprepare.go:211] [download-certs] Skipping certs download
I0228 18:42:31.894698     384 join.go:465] [preflight] Discovering cluster-info
I0228 18:42:31.894710     384 token.go:78] [discovery] Created cluster-info discovery client, requesting info from "kind-control-plane:6443"
I0228 18:42:32.981353     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1085 milliseconds
I0228 18:42:32.981432     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:42:39.686345     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1067 milliseconds
I0228 18:42:39.686404     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:42:46.276411     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1086 milliseconds
I0228 18:42:46.276483     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:42:52.819797     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1065 milliseconds
I0228 18:42:52.819922     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:42:59.216482     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1068 milliseconds
I0228 18:42:59.216573     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:43:05.754760     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1095 milliseconds
I0228 18:43:05.755122     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:43:12.874667     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1073 milliseconds
I0228 18:43:12.874893     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:43:20.410372     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1072 milliseconds
I0228 18:43:20.410529     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:43:26.938442     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1074 milliseconds
I0228 18:43:26.938532     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:43:33.643588     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1069 milliseconds
I0228 18:43:33.643701     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:43:40.255994     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1069 milliseconds
I0228 18:43:40.256090     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:43:47.794604     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1071 milliseconds
I0228 18:43:47.794725     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:43:54.371815     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1109 milliseconds
I0228 18:43:54.371884     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:44:00.716679     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1068 milliseconds
I0228 18:44:00.716802     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:44:08.169634     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1068 milliseconds
I0228 18:44:08.169740     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:44:14.763707     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1071 milliseconds
I0228 18:44:14.763856     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:44:21.667119     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1070 milliseconds
I0228 18:44:21.667309     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:44:29.116451     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1103 milliseconds
I0228 18:44:29.116628     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:44:36.186790     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1065 milliseconds
I0228 18:44:36.186905     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:44:42.541466     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1073 milliseconds
I0228 18:44:42.541614     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:44:49.231962     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1073 milliseconds
I0228 18:44:49.232043     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:44:56.403510     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1076 milliseconds
I0228 18:44:56.403582     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:45:03.254869     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1103 milliseconds
I0228 18:45:03.254991     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:45:09.339833     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1079 milliseconds
I0228 18:45:09.339927     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:45:16.726102     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1067 milliseconds
I0228 18:45:16.726178     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:45:23.174634     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1072 milliseconds
I0228 18:45:23.174808     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:45:30.469887     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1072 milliseconds
I0228 18:45:30.470054     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:45:37.699861     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1102 milliseconds
I0228 18:45:37.699931     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:45:45.023457     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1074 milliseconds
I0228 18:45:45.023606     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:45:51.132275     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1069 milliseconds
I0228 18:45:51.132443     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:45:58.090536     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1074 milliseconds
I0228 18:45:58.090697     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:46:05.393945     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1106 milliseconds
I0228 18:46:05.394018     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:46:11.785277     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1105 milliseconds
I0228 18:46:11.785366     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:46:18.007292     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1072 milliseconds
I0228 18:46:18.007543     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:46:24.287677     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1072 milliseconds
I0228 18:46:24.287800     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:46:31.381218     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1066 milliseconds
I0228 18:46:31.381315     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:46:38.406669     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1069 milliseconds
I0228 18:46:38.406837     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:46:45.715627     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1068 milliseconds
I0228 18:46:45.715841     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:46:52.655771     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1106 milliseconds
I0228 18:46:52.655863     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:46:59.963295     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1064 milliseconds
I0228 18:46:59.963373     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:47:06.240319     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1108 milliseconds
I0228 18:47:06.240497     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:47:12.684606     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1067 milliseconds
I0228 18:47:12.684710     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:47:20.174825     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1071 milliseconds
I0228 18:47:20.174886     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
I0228 18:47:26.978468     384 round_trippers.go:445] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 1072 milliseconds
I0228 18:47:26.978594     384 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup kind-control-plane on 192.168.135.2:53: no such host
couldn't validate the identity of the API Server
k8s.io/kubernetes/cmd/kubeadm/app/discovery.For
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/discovery/discovery.go:44
k8s.io/kubernetes/cmd/kubeadm/app/cmd.(*joinData).TLSBootstrapCfg
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:466
k8s.io/kubernetes/cmd/kubeadm/app/cmd.(*joinData).InitCfg
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:476
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join.getKubeletStartJoinData
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join/kubelet.go:85
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join.runKubeletStartJoinPhase
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join/kubelet.go:100
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdJoin.func1
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:172
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
error execution phase kubelet-start
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdJoin.func1
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:172
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

**Comment by BenTheElder** [comment]
https://kind.sigs.k8s.io/docs/user/known-issues/#fedora32-firewalld
this is most likely a broken transition to iptables-nft on the host environment.

see: https://github.com/kubernetes-sigs/kind/issues/1939

**Comment by jagusztinl** [comment]
tried to stop firewalld, did not help:
systemctl stop firewalld

**Comment by BenTheElder** [comment]
I don't think stopping is expected to be sufficient as it won't cleanup existing rules?
https://github.com/kubernetes-sigs/kind/issues/1939#issuecomment-737425761

This is a podman issue https://github.com/kubernetes-sigs/kind/issues/1939#issuecomment-740499097

**Comment by BenTheElder** [comment]
The known issues page instructs reconfiguring rather than stopping.

**Comment by aojea** [comment]
> tried to stop firewalld, did not help:
> systemctl stop firewalld

let's check first that podman network works correctly:
1. Create a custom network:
`podman network create test`
2. Create a server container in the new network
```
podman run -d --net test --name test1 httpd
7fa7d1be9ef1577e7f22f5528c2a4a191cc9808c61b9e9cc3d77e69ee76faa05
```
3. Check that you can access the server from another containers in the same network using dns:
```
podman run -it --net test busybox sh
/ # wget test1
Connecting to test1 (10.89.0.2:80)
saving to 'index.html'
index.html           100% |******************************************************************************************|    45  0:00:00 ETA
'index.html' saved
```

**Comment by aojea** [comment]
and stopping only doesn't solve the problem, IIRC it needs to recreate the rules with the same iptables version

**Comment by BenTheElder** [comment]
I'm pretty confident this is just stopping vs restarting per the workaround guide. 
The underlying bug is in podman and already tracked in https://github.com/kubernetes-sigs/kind/issues/1939

Please reopen or file a new issue if that is not the case.
