### ISSUE TITLE
Adopt kubernetes API tooling

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#21]
`pkg/cluster/config/...` should adopt Kubernetes's API tooling to automatically generate deep copy and other API tooling.

To do this we need to vendor the generators and add them to `hack/update-generate.sh`

Marking this help wanted, if anyone wants to take this on feel free to contact me for help. I'll tackle this myself eventually.
/priority important-soon
/kind cleanup
/help

**Comment by Lion-Wei** [comment]
Hi, Benjamin. I think I can help. :smile:

**Comment by BenTheElder** [comment]
Awesome!

Yeah unfortunately you have to separately request membership in the other kubernetes orgs like this one, it's pretty easy though ref: https://github.com/kubernetes/org/issues/110

I'll consider this taken for now, thanks! :-)
/lifecycle active

**Comment by BenTheElder** [comment]
@Lion-Wei has this, we still can't assign but I can remove-help (oops! done now) :-)

**Comment by BenTheElder** [comment]
this is sorta done. cc @munnerz 
thanks again @Lion-Wei!

**Comment by Lion-Wei** [comment]
@BenTheElder Be my guest, and I'd like shoulder more works in this repo. : )

**Comment by BenTheElder** [comment]
/assign @Lion-Wei
😄

**Comment by BenTheElder** [comment]
Thanks again for the work on this, opened a new issue to track any remaining cleanup work.
