### ISSUE TITLE
no space left on device when trying to load image

### ISSUE THREAD

**Issue by lechowsky** [kubernetes-sigs/kind#2108]
**What happened**: 
when i execute this command:

kind load docker-image myimage

i get below error:

ERROR: failed to load image: command "docker exec --privileged -i kind-control-plane ctr --namespace=k8s.io images import -" failed with error: exit status 1
Command Output: ctr: failed to ingest "53c72d7c3aa6216ecdf7ae0c1b2341ff0bca496fcac3f948635e31c6cd1f6029/layer.tar": failed to copy: failed to send write: write /var/lib/containerd/io.containerd.content.v1.content/ingest/fb7edd84f30b6083e7bb0b4af3720ecd0d95a7fc1dfa86a73f43300a97c11f04/data: no space left on device: unknown

**What you expected to happen**:
success load of image

**How to reproduce it (as minimally and precisely as possible)**:
i guess that loading big image 

- kind version: kind v0.10.0 go1.15.7 darwin/amd64
- Kubernetes version: "v1.17.1"
- Docker version:   v0.9.1-beta3
- OS (e.g. from mac os 10.15.7

**Comment by BenTheElder** [comment]
Is your docker desktop environment out of disk space ..?

Docker desktop has a virtual disk of limited size.

**Comment by lechowsky** [comment]
> Is your docker desktop environment out of disk space ..?
> 
> Docker desktop has a virtual disk of limited size.

no, in fact using the private registry script that you guys provide in the documentation, it is working, the problem is only when i try to do the 'kind load', as far as i know, i guess this 'kind load' is pushing a given image inside de internal registry that Kind is using.

**Comment by BenTheElder** [comment]
ah, it's not a registry, it's the image storage in the container runtime in the node.

it sounds like your docker environment is out of disk space.

**Comment by BenTheElder** [comment]
on docker for mac the application runs a virtual disk, you can check the disk size and free space in the application preferences.

**Comment by lechowsky** [comment]
let me try it, i will update you with the result and better information if it doesn't work.
thx in advance

**Comment by surenyufuz** [comment]
Reset virtual disk limit in docker desktop environment really works for me.

**Comment by teatreeoilchocolate** [comment]
Subscribing.
I am currently unsure if this is related to kind or docker itself and if this could be tackled using namespaces.
I run into this on Linux.
I have `/tmp` as a different mount. When the image-size does not fit into the size that folder the import will fail with the exact same message.
Whenever you do a `kind load docker-image`  that process will write to `/tmp` first.
