### ISSUE TITLE
correctly check KUBECONFIG when deleting clusters

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#211]
This check is incomplete:
https://github.com/kubernetes-sigs/kind/blob/2b270a02556671be069c19c38a404a1eaf5951a9/pkg/cluster/context.go#L382-L385

Per [the official docs], `KUBECONFIG` may contain multiple paths. The current naive check is insufficient.

NOTE: this only affects wether we give help text or not, so it is not critical. But we should do the correct thing.

/priority backlog
/help

[the official docs]: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable

**Comment by manparvesh** [comment]
Hi, can I work on this issue?

**Comment by neolit123** [comment]
/unassign
sure @manparvesh

**Comment by manparvesh** [comment]
@neolit123 thanks, I will assign it to myself
/assign

**Comment by manparvesh** [comment]
Oh, I can't do that. Can you please assign me this issue?
I am not sure how this works

**Comment by neolit123** [comment]
you are not a member of the kubernetes-sigs organization so you cannot be assigned.
just sent a PR, thanks.

/lifecycle active

**Comment by manparvesh** [comment]
Oh I understand. I will send a PR.
Thanks

**Comment by BenTheElder** [comment]
Thanks for the PR :-) this check should be much better when the user uses multiple KUBECONFIG 🎉

For future reference there is an edgecase now around partial match where the file name later for some reason becomes a directory and is referenced in `KUBECONFIG`, but this case seems pretty unlikely...

We could get arbitrarily complex with this check  (what about if there's a different equivalent path strinf specifying the same file?) and it wouldn't really be worth it (I'm guessing, maybe we change our mind later based on usage) because it's just a helpful reminder and we can't check your other open terminals anyhow.

Hopefully it's good enough now 😄
