### ISSUE TITLE
How to access kubernetes dashboard from host's browser

### ISSUE THREAD

**Issue by hatzhang** [kubernetes-sigs/kind#2141]
I intalled a [kubernetes dashboard](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/) inside Kind cluster. It is ok to access it from inside docker container when ran ```kubectl proxy```.  But can't be accessed from host browser, even add extra porting mapping when create the cluster.  
_I think there should be similar question been asked, but can't filter it out. So i just might ask this again._

**Comment by raphaelauv** [comment]
Use post forwarding -> https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/
