### ISSUE TITLE
Download link for linux is broken by a newline

### ISSUE THREAD

**Issue by tokers** [kubernetes-sigs/kind#2150]
The download link is broken by a new line for installing Kind on Linux.
![image](https://user-images.githubusercontent.com/10428333/112092711-07ca7080-8bd3-11eb-8ef8-f9d02640ee63.png)
It may be confusing.

**Comment by BenTheElder** [comment]
Thanks for reporting this. I think this is a recent regression related to #2118. The docs are under site/ if you're up for taking a look. Otherwise I will get to this in the morning my time.

**Comment by BenTheElder** [comment]
For anyone interested in tackling this see our contributor guide which covers ~everything including the docs 
https://kind.sigs.k8s.io/docs/contributing/getting-started/
https://kind.sigs.k8s.io/docs/contributing/development/#documentation

**Comment by amwat** [comment]
Fixing this would involve trimming both the leading and trailing whitespaces from 

https://github.com/kubernetes-sigs/kind/blob/91ef7a3ef01126247be885f1178349dcedf5ef8d/site/layouts/shortcodes/stableVersion.html#L1

https://gohugo.io/templates/introduction/#whitespace

**Comment by tokers** [comment]
@amwat Let me try it :).

**Comment by BenTheElder** [comment]
thanks! https://github.com/kubernetes-sigs/kind/pull/2154
