### ISSUE TITLE
need to block ip 

### ISSUE THREAD

**Issue by gauravachatrath** [kubernetes-sigs/kind#2152]
Hi Team,

We need to block a specific IP from our alb but be open to the whole world.

This is the solution works from the console
https://aws.amazon.com/premiumsupport/knowledge-center/elb-route-requests-with-source-ip-alb/

May i know how to write this solution in yaml file for kind ingress ?

If we implement from console it is overwritten by k8 hence need the help to add it into yaml

**Comment by BenTheElder** [comment]
kind isn't really intended to be used serving public traffic: 
https://kind.sigs.k8s.io/docs/user/configuration/#api-server
we expect traffic to be local to the host normaly.

but if you are allowing traffic from the internet for some reason, presumably you can firewall this on the host side?

**Comment by gauravachatrath** [comment]
WAF need to be introduced later but if aws console provide same thing how can we do it from here ?

**Comment by BenTheElder** [comment]
> but if aws console provide same thing how can we do it from here ?

Kubernetes is not AWS. Blocking outbound traffic is not a a feature of Kubernetes.

And KIND should not be run open to the whole world.

**Comment by BenTheElder** [comment]
> May i know how to write this solution in yaml file for kind ingress ?

The Kubernetes Ingress API does not support any sort of firewalling. You'll have to do this some other way.

**Comment by gauravachatrath** [comment]
How will be manage ingress for aws alb then ?

I need to block inbound traffic

**Comment by BenTheElder** [comment]
> How will be manage ingress for aws alb then ?

From the beginning of [our README](https://github.com/kubernetes-sigs/kind/blob/main/README.md):
> kind is a tool for running local Kubernetes clusters using Docker container "nodes".
> kind was primarily designed for testing Kubernetes itself, but may be used for local development or CI.

kind is for _local_ test clusters.
kind does not involve anything AWS, or any other cloud.
kind does not support or manage anything AWS, or any other cloud.

I think you may be confused as to the purpose of this tool. If you're looking for a production ready cluster on AWS I recommend [kops](https://github.com/kubernetes/kops).
