### ISSUE TITLE
How to change the proxy setting of an existing cluster?

### ISSUE THREAD

**Issue by Ruminateer** [kubernetes-sigs/kind#2171]
By reading <https://kind.sigs.k8s.io/docs/user/quick-start/#configure-kind-to-use-a-proxy>, I was able to let the cluster use proxy by setting the environment variables before running `$ kind create cluster`. Is it possible to change the proxy setting (stop using the proxy or use a different proxy) without deleting and creating a new cluster? Cannot find an answer in the docs.

Also one more question. Do the environment variables affect both the container networks and imaging pulling? Is there a way to use the proxy only for imaging pulling but not for container networks?

**Comment by Ruminateer** [comment]
The situation is that I am in China where gcr.io is blocked. I do have a proxy through which I can pull gcr.io images, but with that proxy set, I cannot pull some images that I was able to pull without the proxy. I wonder if I can use the proxy only for pulling some image 😢

**Comment by BenTheElder** [comment]
> By reading https://kind.sigs.k8s.io/docs/user/quick-start/#configure-kind-to-use-a-proxy, I was able to let the cluster use proxy by setting the environment variables before running $ kind create cluster. Is it possible to change the proxy setting (stop using the proxy or use a different proxy) without deleting and creating a new cluster? Cannot find an answer in the docs.

As a general rule we don't support cluster mutation, we encourage testing from a clean state and some of these would be very non trivial to implement anyhow. A change in configuration requires recreating.

> Also one more question. Do the environment variables affect both the container networks and imaging pulling? Is there a way to use the proxy only for imaging pulling but not for container networks?

Yes. They affect processes running on the nodes.
Yes. You can configure a mirror or proxy for image pulling by configuring containerd.

This is not well documented yet but see https://kind.sigs.k8s.io/docs/user/private-registries/#use-a-certificate for some idea how to patch containerd config (`containerdConfigPatches`) and https://kind.sigs.k8s.io/docs/user/configuration/ for how to use config in general. See https://github.com/containerd/containerd/blob/master/docs/cri/config.md for documentation of the config. You could configure the mirrors there.

**Comment by BenTheElder** [comment]
hope that helps. if you have more questions we'll try to keep responding (or you can file a new issue), but closing this out now to keep the tracker organized.

I'm going to be out for a bit soon myself, but others will be around.

**Comment by Ruminateer** [comment]
> The situation is that I am in China where gcr.io is blocked. I do have a proxy through which I can pull gcr.io images, but with that proxy set, I cannot pull some images that I was able to pull without the proxy. I wonder if I can use the proxy only for pulling some image 😢

So is there a way to use the proxy only for pulling some images?

I am thinking about manually ensuring the image on the nodes and use `imagePullPolicy: IfNotPresent`, but how can I ensure the images on the nodes in the first place? I pulled the image onto the host machine, but it doesn't seem to work. It seems that I need to ensure the image on the kind node containers, which cannot directly use the images on the host machine. So is there a way to ensure the images on the kind nodes so that `imagePullPolicy: IfNotPresent` can take effect?

**Comment by BenTheElder** [comment]
> So is there a way to use the proxy only for pulling some images?

Yes, you can set hosts ("mirrors") per registry in containerd config using a containerd config patch.

I'm checking in on vacation and don't have time to elaborate but you can see more details in the docs I linked above. Containerd has this well documented

**Comment by BenTheElder** [comment]
>  I pulled the image onto the host machine, but it doesn't seem to work. It seems that I need to ensure the image on the kind node containers, which cannot directly use the images on the host machine.

For technical reasons it's not possible to share that storage / container runtime. Each node has it's own runtime. You can load images into the nodes with a command we provide.

https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

https://kind.sigs.k8s.io/docs/design/initial/#overview

**Comment by Ruminateer** [comment]
> You can load images into the nodes with a command we provide.
> 
> https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
> 
> https://kind.sigs.k8s.io/docs/design/initial/#overview

I tried this, but it doesn't seem to work 😥. The pod is still in `ImagePullBackOff` status.
```
$ docker pull hub.baidubce.com/paddlepaddle/serving@sha256:2e234858a85a16e18f736e7ce71720fb9ad6e86fc25610b4c11285e26ca07bbd
hub.baidubce.com/paddlepaddle/serving@sha256:2e234858a85a16e18f736e7ce71720fb9ad6e86fc25610b4c11285e26ca07bbd: Pulling from paddlepaddle/serving
Digest: sha256:2e234858a85a16e18f736e7ce71720fb9ad6e86fc25610b4c11285e26ca07bbd
Status: Image is up to date for hub.baidubce.com/paddlepaddle/serving@sha256:2e234858a85a16e18f736e7ce71720fb9ad6e86fc25610b4c11285e26ca07bbd
hub.baidubce.com/paddlepaddle/serving@sha256:2e234858a85a16e18f736e7ce71720fb9ad6e86fc25610b4c11285e26ca07bbd
$ kind load docker-image hub.baidubce.com/paddlepaddle/serving@sha256:2e234858a85a16e18f736e7ce71720fb9ad6e86fc25610b4c11285e26ca07bbd
Image: "hub.baidubce.com/paddlepaddle/serving@sha256:2e234858a85a16e18f736e7ce71720fb9ad6e86fc25610b4c11285e26ca07bbd" with ID "sha256:825a7fd941acb184a26fc9b0cefcd47bc7c9c3a5e4e2936d13d4725fa54962c3" not yet present on node "kind-control-plane", loading...
$ echo $?
0
$ docker exec  -it kind-control-plane crictl images
IMAGE                                                          TAG                  IMAGE ID            SIZE
docker.io/istio/pilot                                          1.8.2                64aeafbbdeba5       100MB
docker.io/istio/proxyv2                                        1.8.2                8542bc91edf01       105MB
docker.io/kindest/kindnetd                                     v20210119-d5ef916d   6b17089e24fdb       122MB
k8s.gcr.io/etcd                                                3.4.13-0             0369cf4303ffd       255MB
k8s.gcr.io/kube-apiserver                                      v1.20.2              3ad0575b6f104       69.7MB
k8s.gcr.io/kube-controller-manager                             v1.20.2              51dc9758caa7b       63.2MB
k8s.gcr.io/kube-proxy                                          v1.20.2              23b52beab6e55       120MB
k8s.gcr.io/pause                                               3.3                  0184c1613d929       686kB
gcr.io/knative-releases/knative.dev/net-istio/cmd/controller   <none>               763498c82aa11       17MB
gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook      <none>               7f416da9723df       15.5MB
gcr.io/knative-releases/knative.dev/serving/cmd/activator      <none>               730662e188705       16.4MB
gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler     <none>               a6f212e29da70       16.6MB
gcr.io/knative-releases/knative.dev/serving/cmd/controller     <none>               1461ed043b037       18MB
docker.io/rancher/local-path-provisioner                       v0.0.14              e422121c9c5f9       42MB
k8s.gcr.io/build-image/debian-base                             v2.1.0               c7c6c86897b63       53.9MB
k8s.gcr.io/coredns                                             1.7.0                bfe3a36ebd252       45.4MB
k8s.gcr.io/kube-scheduler                                      v1.20.2              cd40419687469       47.6MB
gcr.io/knative-releases/knative.dev/serving/cmd/queue          <none>               dd77461ab3b62       15.1MB
gcr.io/knative-releases/knative.dev/serving/cmd/webhook        <none>               fa0271df9ef36       16.3MB
$ kubectl get pods -n paddleservice-system
NAME                                                      READY   STATUS             RESTARTS   AGE
paddle-sample-service-00002-deployment-7dc5968b95-ghrll   0/2     ImagePullBackOff   1          14h
```

**Comment by BenTheElder** [comment]
IIRC this won't work with a digest of a manifest, I don't think there's anything we can do about that.

**Comment by BenTheElder** [comment]
The loaded image will not have that digest. It will have the platform specific image.
