### ISSUE TITLE
dualstack should automatically enable feature gate for < 1.21

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#2172]
see: https://kubernetes.slack.com/archives/CEKK1KTN2/p1617232113200400

note: we can be smart and enable this _precisely_ before it comes on by default 🙃, see e.g.  https://github.com/kubernetes-sigs/kind/commit/a4df15b6f77e65fa3598e87f139071f8697ec625#diff-1d8da887aaff57615ed7bc578730aff0c89074cb92ba7f5ef2bcb6536f9ae521R110

filing so we don't lose track, I can do this in the morning though, been working on #166.

cc @aojea

**Comment by BenTheElder** [comment]
also: we need to get a kind CI job. maybe just a small subset of tests on kubernetes master in kind presubmit for now (we need to avoid excessively expanding presubmit in this repo and we already subject ourselves to equivalents of all kubernetes/kubernetes presubmits using kind).

**Comment by aojea** [comment]
> also: we need to get a kind CI job. maybe just a small subset of tests on kubernetes master in kind presubmit for now (we need to avoid excessively expanding presubmit in this repo and we already subject ourselves to equivalents of all kubernetes/kubernetes presubmits using kind).

There are 2 periodic KIND dual-stack jobs (ipvs and iptables proxy) and 2 optional presubmits already
https://testgrid.k8s.io/sig-network-kind#sig-network-kind,%20dual,%20master&width=20
https://testgrid.k8s.io/sig-network-kind#pr-sig-network-kind,%20dual&width=20
