### ISSUE TITLE
No context found by `kubectl` when starting cluster with `kind create cluster`

### ISSUE THREAD

**Issue by hakrac** [kubernetes-sigs/kind#2174]
After starting the kind cluster wtih `kind create cluster` I tried connecting to the cluster with `kubectl cluster-info --context kind-kind`.
Unfortuntaly `kubectl` gave me the following error.

```
error: context "kind-kind" does not exist
```

Inspecting the contexts available to `kubectl` I only got my minikube instance.

```
CURRENT   NAME       CLUSTER    AUTHINFO   NAMESPACE
*         minikube   minikube   minikube   default

```

The error persisted even after removing minikube and clearing `$HOME/.kube/config`.

I am using

Ubuntu 20.04,
kind version 0.10.0,
kubectl client version 1.20.5,
kubectl server version 1.20.2

**Comment by hakrac** [comment]
I just found a workaround by appending the output of
```
sudo kind get kubeconfig
```
to `$HOME/.kube/config`.

**Comment by BenTheElder** [comment]
It should happen automatically. Is your kubeconfig not owned by the current user?

**Comment by BenTheElder** [comment]
Also `sudo kind export kubeconfig` is a less manual way to add it if not, but the fact that it worked with sudo suggests to me that the permissions are wrong on your kubeconfig file, you might need to `chown` it.

We should print an error / warning if this happens as well, if kind doesn't that's a bug in itself though we still need you to correct the permissions on the file or specify a different file to use.

**Comment by hakrac** [comment]
`$HOME/.kube/config` is owned by the currenty active user who has read as well as write permisson.

**Comment by BenTheElder** [comment]
What about the directory?

**Comment by BenTheElder** [comment]
Are there any stray lock files?

**Comment by hakrac** [comment]
My `.kube` directory is owned by the active user.

I am currently executing all docker related commands as root user so this should not be the problem.

**Comment by BenTheElder** [comment]
> I am currently executing all docker related commands as root user so this should not be the problem.

Ah, that explains it.

kubernetes has rules about where kubeconfig is written, it will default to under the current user.

if you run `kind` as root, it will likely write the kubeconfig under the root user's homedir then. we use the same lookup logic as kubectl. most likely there is a kubeconfig under the root's homedir with the kind configuration.

**Comment by BenTheElder** [comment]
you can do one of:
- add this kubeconfig to `KUBECONFIG` (which supports a list in all kubernetes tools following the spec)
- use `--kubeconfig` when calling `kind` or `kubectl` (and possibly chown after calling kind if you go that route)
- run kubectl as the same user as kind

**Comment by hakrac** [comment]
I solved the issue by adding my user to the docker group and running `kind create cluster`.
Thanks;

**Comment by SmadusankaB** [comment]
kubectl config set-context kind-kind
