### ISSUE TITLE
Multi host support

### ISSUE THREAD

**Issue by benjah1** [kubernetes-sigs/kind#2180]
**What would you like to be added**:
Being able to use kind to create a k8s cluster which is running on multi hosts.

**Why is this needed**:
1. Nowadays, there are more CPU cores on a local development machine. and most container solutions (other than on linux) are running base on virtual machine. In the VM, the more CPU being assigned, the more context switch, the slower it becomes. - Which I may have a 8-core macbook, but only 2 cores are could really being used for kind..
2. Why not using other like minikube? kind is much CI friendly, and I could like to use kind in CI and local development. Plus, I am not a big fan of, creating VM(minikube) in container(Jenkins), to run container(k8s)...

**What I think to implement this**:
1. kind, to create or use an `Overlay Networking` for Multi-Host Container Networking.
2. in the `Per-Node Options`, allow to specify which docker host to be used.

**Comment by BenTheElder** [comment]
Sorry this is completely out of [scope](https://kind.sigs.k8s.io/docs/contributing/project-scope/) for the project.

There are many projects in SIG cluster lifecycle for creating multi-node clusters across hosts. Checkout Cluster API, kops, kubespray, ...
We are not trying to overlap with these tools.

Also, the only reason we run "in a container" is for cheap local testing. This doesn't work perfectly (#1963 etc) and isn't intended for heavy compute / serious workloads, just for testing.
