### ISSUE TITLE
kind build node-image - won't work with master branch of kubernetes

### ISSUE THREAD

**Issue by egandro** [kubernetes-sigs/kind#2191]
**What would you like to be documented**:

This is not sufficient:

`
$GOPATH/src/k8s.io/kubernetes
`

You need to checkout a specific Version of kubernetes, e,.g.

`
 $ git checkout tags/v1.22.0-alpha.0 -b v1.22.0-alpha.0`

**Why is this needed**:

`
 $ hack/print-workspace-status.sh
`
Won't print a gitVersion. So either we fix the documentation or we just assume if gitVersion is empty that we do a <master> build.

**Comment by BenTheElder** [comment]
This is not true, we run kind build node-image in every Kubernetes PR, you must be encountering some sort of bug.

**Comment by egandro** [comment]
> This is not true, we run kind build node-image in every Kubernetes PR, you must be encountering some sort of bug.

Well it is a bug :) I just didn't make things up. This was empty yesterday. Can be closed here.

```
$ git clone https://github.com/kubernetes/kubernetes.git
Cloning into 'kubernetes'...
remote: Enumerating objects: 320, done.
remote: Counting objects: 100% (320/320), done.
remote: Compressing objects: 100% (222/222), done.
remote: Total 1216093 (delta 143), reused 117 (delta 91), pack-reused 1215773
Receiving objects: 100% (1216093/1216093), 733.72 MiB | 10.77 MiB/s, done.
Resolving deltas: 100% (875254/875254), done.
Checking out files: 100% (20472/20472), done.
$ cd kubernetes
$ hack/print-workspace-status.sh
STABLE_BUILD_GIT_COMMIT 3eac7972552bdf9948b99d687fdf1cd0aa20834a
STABLE_BUILD_SCM_STATUS clean
STABLE_BUILD_SCM_REVISION v1.22.0-alpha.0.293+3eac7972552bdf
STABLE_BUILD_MAJOR_VERSION 1
STABLE_BUILD_MINOR_VERSION 22+
STABLE_DOCKER_TAG v1.22.0-alpha.0.293_3eac7972552bdf
STABLE_DOCKER_REGISTRY k8s.gcr.io
STABLE_DOCKER_PUSH_REGISTRY staging-k8s.gcr.io
gitCommit 3eac7972552bdf9948b99d687fdf1cd0aa20834a
gitTreeState clean
gitVersion v1.22.0-alpha.0.293+3eac7972552bdf
gitMajor 1
gitMinor 22+
buildDate 2021-04-11T08:46:27Z
```

**Comment by BenTheElder** [comment]
Er right, this is probably a bug _in Kubernetes_, I also maintain the build tools there so I'd be interested in seeing a bug filed in Kubernetes with details if you can figure it out 😅 

Sorry my last comment was not clear.

In general this should work fine at arbitrary commits, we work pretty hard to make that work (though sometimes the latest Kubernetes sources require the latest kind sources to keep up with upstream breaking changes).
