### ISSUE TITLE
Not able to download kind 1.19.7 image; it's stuck in waiting

### ISSUE THREAD

**Issue by pjajootibco** [kubernetes-sigs/kind#2194]
v1.19.7: Pulling from kindest/node
d8b994c44286: Already exists
b0773f3f1417: Already exists
5b20aefff2dc: Already exists
6f44fb9b2033: Already exists
46f8fc57c0d0: Waiting

**Comment by BenTheElder** [comment]
We just call docker / podman pull so ... 🤔

**Comment by pjajootibco** [comment]
> We just call docker / podman pull so ... 🤔

Yes, works for me too, just checked, not sure how, but it was not pulling before.. Sorry for the trouble.

**Comment by BenTheElder** [comment]
No worries, thanks!
