### ISSUE TITLE
Ability to set static IP for containers

### ISSUE THREAD

**Issue by gagipro** [kubernetes-sigs/kind#2197]
**Ability to set static IP for containers**: if you reboot for example with WSL2 + docker desktop : IPs are not retained.

**K8s cluster simply doesn't work properly**: Especially SSL certificates in ETCD ha setup are valid for specific IP, if you reboot, try to check status for etcd cluster, you'll see that certificate aren't valid anymore.

**Comment by BenTheElder** [comment]
> Ability to set static IP for containers

lots of prior discussion: https://github.com/kubernetes-sigs/kind/issues?q=static+ip

> K8s cluster simply doesn't work properly: Especially SSL certificates in ETCD ha setup are valid for specific IP, if you reboot, try to check status for etcd cluster, you'll see that certificate aren't valid anymore.

Yes, this is a bug, but it is a duplicate of https://github.com/kubernetes-sigs/kind/issues/2045

**Comment by gagipro** [comment]
> > Ability to set static IP for containers
> 
> lots of prior discussion: https://github.com/kubernetes-sigs/kind/issues?q=static+ip
> 
> > K8s cluster simply doesn't work properly: Especially SSL certificates in ETCD ha setup are valid for specific IP, if you reboot, try to check status for etcd cluster, you'll see that certificate aren't valid anymore.
> 
> Yes, this is a bug, but it is a duplicate of #2045

Ho sorry I searched all bugs but didn’t found this.

thanks a lot 👍🏻

**Comment by gagipro** [comment]
duplicate of [https://github.com/kubernetes-sigs/kind/issues/2045](url)
