### ISSUE TITLE
Kind can't mount hostpath /run to kind cluster node because the duplicate mount point in docker run cmd

### ISSUE THREAD

**Issue by gxglls** [kubernetes-sigs/kind#2200]
**What happened**:
kind can't mount host /run path to kind cluster node, because the duplicate mount point in docker run cmd
kind config:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /run
    containerPath: /run
```
run create cluster  result
```bash
#kind create cluster --config ./kind.yaml
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼
 ✗ Preparing nodes 📦
ERROR: failed to create cluster: docker run error: command "docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --net kind --restart=on-failure:1 --volume=/run:/run --publish=127.0.0.1:38526:6443/TCP kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab" failed with error: exit status 125
Command Output: docker: Error response from daemon: Duplicate mount point: /run.
See 'docker run --help'.
```
**What you expected to happen**:
I want to use hostpath /run to get some information in kind cluster, so I expected kind can mount hostpath /run to kind cluster

**Environment:**
- kind version: (use `kind version`): kind v0.10.0
- Kubernetes version: (use `kubectl version`): v1.19.3
- Docker version: (use `docker info`): v19.03.11
- OS (e.g. from `/etc/os-release`): CentOS Linux 7

**Comment by BenTheElder** [comment]
I suppose we could allow overriding the built in mounts but there are good reasons for these and it may not work properly if you replace them. In this case /run is expected to be a tmpfs ...

What do you mean by "get some information in cluster"?

Also you really shouldn't bind mount system paths from the host to the node like this even if it was allowed, for example you may collide the host container runtime sockets.

**Comment by gxglls** [comment]
I found that I don’t need all the files in the /run directory, I only need /run/udev to do physical disk discovery, so I only need to mount /run/udev separately, thank you very much for your answer @BenTheElder
