### ISSUE TITLE
Write container logs in JSON format

### ISSUE THREAD

**Issue by regel** [kubernetes-sigs/kind#2202]
I'm running a kind cluster on macOS. Container logs are written in raw text format, instead of JSON. How can I force kind to write container logs in JSON format?

This issue is breaking my fluentd setup. It works in kubernetes AKS, but I'd like to test the same configuration locally with kind.

Version info:

$ kind --version
kind version 0.10.0
$ docker --version
Docker version 19.03.12, build 48a66213fe

**Comment by BenTheElder** [comment]
CRI mandates the CRI log format. fluentd should support this.
https://github.com/kubernetes/kubernetes/issues/70539
https://github.com/cri-o/cri-o/issues/3181
https://github.com/containerd/containerd/issues/4798
https://github.com/containerd/cri/issues/830#issuecomment-400453368

**Comment by BenTheElder** [comment]
(CRI = https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/, which is the way to interface with container runtimes going forward after https://kubernetes.io/blog/2020/12/02/dockershim-faq/, we ship containerd as our CRI implementation within the nodes)
