### ISSUE TITLE
No response for `kind create cluster --name wslkind`

### ISSUE THREAD

**Issue by smartnava** [kubernetes-sigs/kind#2206]
I was trying to setup the cluster in my WSL (Ubuntu - 20.04). But it is not showing any output.
![image](https://user-images.githubusercontent.com/34976735/115261355-2cbdef00-a151-11eb-874e-73ddc2ab651e.png)

**Comment by smartnava** [comment]
> That line means it's pulling the image, did docker fail to pull it?
> Does it behave the same with just `kind create cluster`?
> 
> What versions? The bug report template has questions like what docker version what OS what kind version, etc.

Yes. It is behaving the same for this `kind create cluster` . 

```
krish@DESKTOP-705RRMT:~$ kind version
kind v0.10.0 go1.15.7 linux/amd64
krish@DESKTOP-705RRMT:~$ docker -v
Docker version 20.10.5, build 55c4c88
```
It is running with WSL2. Ubuntu 20.04

**Comment by BenTheElder** [comment]
re: WSL2 see also https://github.com/kubernetes-sigs/kind/issues/1740#issuecomment-748355710

I and the other maintainers don't use WSL2 so I'm not sure how much we can help here.

Image pulling hanging is not a kind bug, something is wrong with docker. Perhaps out of disk space?

**Comment by BenTheElder** [comment]
for v0.10.0 it runs `docker pull kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab` (see release notes for the default)

if that can't work, kind can't work. docker has to pull the image.

**Comment by smartnava** [comment]
`docker pull kindest/node` This is not working. But `docker pull kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab` this actually working for me. I can pull the node image. Then i ran this `kind create cluster` again. Now the cluster got created

**Comment by BenTheElder** [comment]
There is no :latest tag as arbitrary images should not be used.

I think all you saw was pulling this image is slow as it's a large image. Which is why it will hang at ensuring the image for some time.

**Comment by BenTheElder** [comment]
We've done what we can to make it smaller but kubernetes + dependencies is large.

**Comment by smartnava** [comment]
Thanks for the update.
