### ISSUE TITLE
can use kind to build a CSI development environment ? 

### ISSUE THREAD

**Issue by allenhaozi** [kubernetes-sigs/kind#2211]
Recently developed CSI driver, and I want to use Kind to build a development environment on Mac

**Comment by BenTheElder** [comment]
yes, some CSI drivers are commonly tested with kind. For cloud drivers it may not make sense versus running a "real" cluster on that provider.

see e.g. https://github.com/kubernetes-csi/csi-driver-host-path/blob/97346865ff2d0e890db424bdbf165f46522dc6a1/release-tools/prow.sh

**Comment by allenhaozi** [comment]
> yes, some CSI drivers are commonly tested with kind. For cloud drivers it may not make sense versus running a "real" cluster on that provider.
> 
> see e.g. https://github.com/kubernetes-csi/csi-driver-host-path/blob/97346865ff2d0e890db424bdbf165f46522dc6a1/release-tools/prow.sh

got it, Thank you very much

**Comment by allenhaozi** [comment]
I tried a way, a little trick
[build kubernetes csi development env by kind on Mac](https://allenhaozi.medium.com/build-kubernetes-csi-development-env-by-kind-on-mac-d61947b71661)

If you have an easier method based on Kind, please leave a comment

**Comment by aojea** [comment]
nice blog @allenhaozi , thanks
This can be considered solved :)

/close
