### ISSUE TITLE
How can I export loadbalancer ip?

### ISSUE THREAD

**Issue by fmontaldo87** [kubernetes-sigs/kind#2212]
Hi

I deploy a k8s with kind using the terraform project. I made the following:

fmontaldo@fmontaldo-ThinkPad-L14-Gen-1:~$ kubectl --namespace=selenium get services
NAME           TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                         AGE
selenium-hub   LoadBalancer   10.96.165.222   172.19.255.201   4444:32048/TCP,5555:30298/TCP   42m
fmontaldo@fmontaldo-ThinkPad-L14-Gen-1:~$ 

I cannot access the external ip from my browser. There is an issue with kind cluster?.

**Comment by BenTheElder** [comment]
Please read https://kind.sigs.k8s.io/docs/user/loadbalancer/

**Comment by fmontaldo87** [comment]
So I got metalb up and running

fmontaldo@fmontaldo-ThinkPad-L14-Gen-1:~$ kubectl --namespace=metallb-system get all
NAME                              READY   STATUS    RESTARTS   AGE
pod/controller-64f86798cc-79dhv   1/1     Running   0          159m
pod/speaker-5vpzk                 1/1     Running   0          159m
pod/speaker-5zskj                 1/1     Running   0          159m
pod/speaker-wk297                 1/1     Running   0          159m

NAME                     DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/speaker   3         3         3       3            3           kubernetes.io/os=linux   159m

NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/controller   1/1     1            1           159m

NAME                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/controller-64f86798cc   1         1         1       159m
fmontaldo@fmontaldo-ThinkPad-L14-Gen-1:~$ 

I made the service class as per recomendations.

**Comment by aojea** [comment]
> So I got metalb up and running

can we close it then?
