### ISSUE TITLE
Nightly build for 0.11

### ISSUE THREAD

**Issue by matzew** [kubernetes-sigs/kind#2227]
Hello, I am wondering if there is a nightly build option, e.g. to get access to the 0.11 release :smile_cat: 

thanks :wave:

**Comment by BenTheElder** [comment]
0.11 isn't quite released yet but yes there are nightly binaries (use at your own risk / may have undocumented breaking changes), https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64

you can also build from source quite easily:
- ensure you have make, bash, git
- clone the repo and cd to it
- `make build`
- the binary is in `bin/kind`

it does not need a go install

**Comment by matzew** [comment]
thanks for the kind reply ;-) 

I am now building the `main` branch locally, and it works great w. `podman` (rootless) for me.

Thanks @BenTheElder
