### ISSUE TITLE
download docker repeatedly when installing from choco

### ISSUE THREAD

**Issue by Tarrowren** [kubernetes-sigs/kind#2232]
Docker version 20.10.5, build 55c4c88  

I have installed docker desktop, but it will download it again when I install kind
![image](https://user-images.githubusercontent.com/35626141/117392478-bda01300-af24-11eb-8e69-d042a838ce73.png)

**Comment by tao12345666333** [comment]
what's your Docker Desktop for Windows version ?

**Comment by BenTheElder** [comment]
We don't maintain the choco package currently.
See https://github.com/kubernetes-sigs/kind/issues/956 for the background on the package.

**Comment by Tarrowren** [comment]
> 您的Windows版Docker桌面是什么？

20.10.5, now it's updated to 20.10.6, maybe it's updating?

> 我们目前不维护choco软件包。
> 有关包装上的背景，请参见[＃956](https://github.com/kubernetes-sigs/kind/issues/956)。

ok, thank you

**Comment by tao12345666333** [comment]
> maybe it's updating?

I think it might be, but I don’t have a windows system to test.

**Comment by BenTheElder** [comment]
I have no idea what is the expecation with choco, maybe you can file this against the actual package sources?

**Comment by Tarrowren** [comment]
Maybe it's because I installed docker desktop with the installation package.
choco couldn't detect it so reinstall it.
![1](https://user-images.githubusercontent.com/35626141/117521721-cf93bb80-afe1-11eb-98e3-d5e7febc1adc.png)

**Comment by aojea** [comment]
/close

I don't think we can do more here, 

awesome work by the package maintainer by the way
https://community.chocolatey.org/packages/kind
thanks @digitalcoyote
