### ISSUE TITLE
Document sig-network results for kube proxy userspace + ipvs  + windows tests

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kind#2234]
**What would you like to be documented**:

This is a good first issue to learn about how to configure kube proxy on kind.
Its also a nice little iteration to do some investigation into test-coverage for kube-proxy in tree providers.

- test kube-proxy with sonobuoy and ginkgo.focus=sig-network, and ginkgo.focus=Conformance filters, iptable
- test kube-proxy with sonobuoy and  ginkgo.focus=sig-network, ginkgo.focus=Conformance filters, userspace
- tets kube-proxy with sonobuoy and  ginkgo.focus=sig-network, ginkgo.focus=Conformance filters, ipvs
- test kube-proxy with sonobuoy and  ginkgo.focus=sig-network, ginkgo.focus=Conformance filters, noproxy, (note you need to run kind from master for this b/c the kind current release doesnt support kube-proxy=none yet

**Why is this needed**:

As we evolve kind to support new dev environments would be cool if there was a doc page w/ expected results so we can a/b test our recipes like https://github.com/kubernetes-sigs/kpng/blob/master/hack/kpng-local-up.sh

IDEALLY for output we could have spreadsheet of results or a csv file , or just all the e2e.log files in ONE github repo (please no tar ball).... e2e.log :)

results
```
dougsland/
   kind-ipvs-conf/
       e2e.log
   kind-iptables-conf/
       e2e.log
    kind-iptables-sig-network/
       e2e.log
```

**Comment by jayunit100** [comment]
@dougsland is ramping up learning about kube proxy stuff and so we decided to make this as an experiment in testing and data collectino for him

**Comment by BenTheElder** [comment]
Configuring kube proxy is configuring kubeadmCondigPatches and using the kube proxy component config.

Maybe I've misunderstood this issue but ...

I think sig network should be responsible for some sort of test matrix like this. I don't think it should be here.

I don't think we can reasonably afford to maintain a page with expected results from a matrix like this ourselves. From the given examples ... We expect conformance to pass unless you something breaks, in which case it should be fixed, not documented as failing.

Windows is not supported and cannot be supported. Except as a host, which doesn't change the testing.

Also even the log files are huge. As for conformance log storage, we periodically submit results to the CNCF, in addition to live results from CI. I don't think we should have another repo of logs, the CI storage or official programs seem better suited to this.

**Comment by jayunit100** [comment]
For context we had some folks on boarding and using kind so I figured a first pass to ensure different kube proxy data planes work on all kube proxy kind config as was a good learning project :).

**Comment by BenTheElder** [comment]
Sounds like a good project! Please ping back whatever y'all do 😅 

I'm going to close this one out for now to keep the tracker neat 🙃
