### ISSUE TITLE
Errors running kind on windows

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes-sigs/kind#224]
Using Windows 10 Home on x86, I was able to successfully download and create a binary using `go get sigs.k8s.io/kind`. However, running `kind create cluster` in a normal command prompt or powershell session errors out:
```
C:\Users\user>kind create cluster
Creating cluster 'kind-1' ...
 ✓ Ensuring node image (kindest/node:v1.12.3) 🖼
[31mERRO[0m[20:18:48] docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/create?name=kind-1-control-plane: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
[31mERRO[0m[20:18:48] See 'docker run --help'.
[31mERRO[0m[20:18:48] docker run error: exit status 127
 ✗ [control-plane] Creating node container 📦
Error: failed to create cluster: docker run error: exit status 127
Usage:
  kind create cluster [flags]

Flags:
      --config string   path to a kind config file
  -h, --help            help for cluster
      --image string    node docker image to use for booting the cluster
      --name string     cluster context name (default "1")
      --retain          retain nodes for debugging when cluster creation fails
      --wait duration   Wait for control plane node to be ready (default 0s)

Global Flags:
      --loglevel string   logrus log level [panic, fatal, error, warning, info, debug] (default "warning")

failed to create cluster: docker run error: exit status 127
```

This error (The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect) seems to indicate that the command should be run as administrator (see https://github.com/docker/toolbox/issues/636 and https://github.com/docker/for-win/issues/1825 ).
However, running the same command in an admin shell doesn't seem to do anything - the command stalls:
```
C:\Windows\system32>kind create cluster
Creating cluster 'kind-1' ...
⢎⠁ Ensuring node image (kindest/node:v1.12.3) 🖼
```

This last step has been in the same step for over half an hour.

ref: #191 
/kind bug

**Comment by BenTheElder** [comment]
This sounds like docker for windows is misconfigured / installed. I do not run kind as an administrator on windows 10. Will check my setup later tonight.

**Comment by BenTheElder** [comment]
I've run into https://github.com/docker/toolbox/issues/636#issuecomment-322786800, IIRC I had to re-enable hyperV

**Comment by alejandrox1** [comment]
@BenTheElder do you have Docker desktop installed or are you using the Docker toolbox ?
If i remeber correctly,  Docker toolbox uses oracle's virtualbox instead of hyperV. Is there any chance this could be a problem?

**Comment by alejandrox1** [comment]
Also, Docker seems to work. All Docker commands work as expected.

**Comment by BenTheElder** [comment]
I have docker desktop. (https://docs.docker.com/docker-for-windows/install/), can you `docker run ..` ? that first output you pasted looks exactly like "docker is installed but the daemon is not running"

**Comment by BenTheElder** [comment]
can we get `kind export logs` for the stuck cluster? also what docker version etc? are you using docker toolbox or docker desktop yourself?

**Comment by neolit123** [comment]
cc

**Comment by BenTheElder** [comment]
Yeah sorry about that!

I am going to work more on making offline work viable, but it does require pre-pulling some things.

Small note: the node images are indeed quite large, but there's not much we can do here.

The bulk of the binary size is Kubernetes, docker. We can make the image """smaller""" by not pre-loading anything, but then _Every_ startup has to download all of it (eg etcd)

When building we get these via the host, which could save bandwidth, except k8s uses a ~2gb build image 😬 

The hope for the future is that node images will actually get _larger_, but they will be compressed and contain _everything_ necessary to start a cluster and work without internet once pulled. This also means even on poor bandwidth while the first pull will feel extra painful, it will be quicker to start clusters afterwords, and not continue to waste bandwidth re-pulling dependencies (eg weave).

**Comment by BenTheElder** [comment]
k8s on low bandwidth is somewhat brutal due to the binary / image size, I'm interested in ideas but short of fixing that upstream somehow (which also might be interesting!), I think our best route is to try to minimize re-downloading. I plan to fix that this week.
