### ISSUE TITLE
failed to list clusters

### ISSUE THREAD

**Issue by dv-sharma** [kubernetes-sigs/kind#2247]
I am facing issues creating my kubernetes cluster in ubuntu using kind .

###  kind create cluster --name wslkind1
ERROR: failed to list clusters: command "docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster=wslkind1 --format '{{.Names}}'" failed with error: exit status 1

can anyone help me with this ?

**Comment by BenTheElder** [comment]
Please include the rest of the information from the bug template. We need to know more about your docker installation etc. It appears to not be functional.

**Comment by tao12345666333** [comment]
Please check if docker is running? Do you have permission to execute `docker ps` directly?

**Comment by aojea** [comment]
I'm going to close due to lack of information, please reopen if you can provide the requested information
Thanks
/close
