### ISSUE TITLE
[Podman] ERROR: failed to create cluster: running kind with rootless provider requires setting systemd property "Delegate=yes", see https://kind.sigs.k8s.io/docs/user/rootless/

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes-sigs/kind#2254]
**What happened**:

kind + rootless podman fails, even when the systemd property "Delegate=yes" is set.

```console
$ KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
ERROR: failed to create cluster: running kind with rootless provider requires setting systemd property "Delegate=yes", see https://kind.sigs.k8s.io/docs/user/rootless/
```

The issue does not happen with Rootless Docker.

Podman itself can handle cgroup delegation as expected
```console
$ podman run  --rm --cpus=0.42 --memory=42m --pids-limit 42 -w /sys/fs/cgroup docker.io/library/alpine cat cpu.max memory.max pids.max
42000 100000
44040192
42
```

**What you expected to happen**:

It should work.

**How to reproduce it (as minimally and precisely as possible)**:

Set up a vagrant VM with the following Vagrantfile:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant box for testing kind with cgroup v2
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/33-cloud-base"
  memory = 2048
  cpus = 2
  config.vm.provider :virtualbox do |v|
    v.memory = memory
    v.cpus = cpus
  end
  config.vm.provider :libvirt do |v|
    v.memory = memory
    v.cpus = cpus
  end
  config.vm.provision "install-packages", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
    set -eux -o pipefail
    # Ensure network-related modules to be loaded
    modprobe tap iptables_nat ip6tables_nat

    # The moby-engine package included in Fedora lacks support for rootless,
    # So we need to install docker-ce and docker-ce-rootless-extras from the upstream.
    curl -fsSL https://get.docker.com | sh
    dnf install -y golang-go make kubernetes-client podman docker-ce-rootless-extras
    systemctl enable --now docker

    # Configuration for rootless: https://kind.sigs.k8s.io/docs/user/rootless/
    loginctl enable-linger vagrant
    mkdir -p "/etc/systemd/system/user@.service.d"
    cat <<EOF >"/etc/systemd/system/user@.service.d/delegate.conf"
    [Service]
    Delegate=yes
    EOF
    systemctl daemon-reload
    SHELL
  end
  config.vm.provision "install-kind", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
    set -eux -o pipefail
    make -C /vagrant install INSTALL_DIR=/usr/local/bin
    SHELL
  end
end
```

Enter into the VM via `vagrant ssh`, and run `KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster` there.

**Anything else we need to know?**:
No
**Environment:**

- kind version: (use `kind version`): kind v0.11.0-alpha+7b166ac2b6a94f go1.16.4 linux/amd64
- Kubernetes version: (use `kubectl version`): unrelated
- Podman version: 3.1.2
- OS (e.g. from `/etc/os-release`): Fedora 33

**Comment by AkihiroSuda** [comment]
Seems this path is not robust, as the current cgroup can be like `/sys/fs/cgroup/user.slice/user-1000.slice/session-11.scope`

https://github.com/kubernetes-sigs/kind/blob/b6bc112522651d98c81823df56b7afa511459a3b/pkg/cluster/internal/providers/podman/provider.go#L380

**Comment by jesperpedersen** [comment]
This may be related, so posting here - I can create a new issue if needed.

OS: Fedora 34
podman: 3.1.2
kind 0.11.0

with

```
$ cat /etc/systemd/system/user@.service.d/delegate.conf 
[Service]
Delegate=yes
```

for

```
KIND_EXPERIMENTAL_PROVIDER=podman ./kind-linux-amd64 -v 5 create cluster
```

Thanks to @aojea for the help to debug.

[664088025.tar.gz](https://github.com/kubernetes-sigs/kind/files/6532161/664088025.tar.gz)

**Comment by aojea** [comment]
> Thanks to @aojea for the help to debug.

for completeness, the kubelet is failing to create the pods with permission denied problems

> 
> May 21 15:31:51 kind-control-plane kubelet[218]: E0521 15:31:51.477866     218 kuberuntime_manager.go:790] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:57: preparing rootfs caused: permission denied: unknown" pod="kube-system/etcd-kind-control-plane"
> May 21 15:31:51 kind-control-plane kubelet[218]: E0521 15:31:51.477967     218 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"etcd-kind-control-plane_kube-system(00e212bd62ddcb302be3d7456c5d373c)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"etcd-kind-control-plane_kube-system(00e212bd62ddcb302be3d7456c5d373c)\\\": rpc error: code = Unknown desc = failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:57: preparing rootfs caused: permission denied: unknown\"" pod="kube-system/etcd-kind-control-plane" podUID=00e212bd62ddcb302be3d7456c5d373c

**Comment by AkihiroSuda** [comment]
SELinux has to be disabled to use rootless overlayfs.
We could use fuse-overlayfs instead, but didn't reach consensus https://github.com/kubernetes-sigs/kind/pull/2127

**Comment by jesperpedersen** [comment]
Thank you Akihiro-san for your feedback !

Is there a way to override this setting ? It is likely going to be difficult to disable SELinux on a lot of deployments.
