### ISSUE TITLE
race restarting containerd with config patches

### ISSUE THREAD

**Issue by igorcalabria** [kubernetes-sigs/kind#2262]
**What happened**:

Cluster is unable to pull images on `localhost:5000` after following the local registry guide https://kind.sigs.k8s.io/docs/user/local-registry/. It fails with dial tcp 127.0.0.1:5000: connect: connection refused

**What you expected to happen**:

Cluster is able to pull images on `localhost:5000` registry

**How to reproduce it (as minimally and precisely as possible)**:

On host machine 

```
./kind-with-registry.sh 
docker pull busybox:latest
docker tag busybox:latest localhost:5000/busybox:latest 
docker push  localhost:5000/busybox:latest
```
inside control pane(`docker exec -it kind-control-pane bash`):

```
root@kind-control-plane:/# crictl --debug pull localhost:5000/busybox:latest
```

It should fail with the error above(in my setup at least)

**Anything else we need to know?**:

From my limited investigation, it seems that containerd config patch was applied after the process started. The patch had no effect on the running process and this may explain why it tried to pull the image from 127.0.0.1 instead of the configured endpoint. To fix this I simply ran `service containerd restart` inside the control plane container and everything started working. Hope this helps

**Environment:**

- kind version: (use `kind version`): kind v0.11.0 go1.16 linux/amd64
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-18T01:10:20Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 547
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.4.0-73-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.28GiB
 Name: desk
 ID: JY6E:ECRV:UPVQ:FDBF:W7OR:EBOE:6AMT:I3GV:CGZ3:KITC:HMY4:CFAW
 Docker Root Dir: /home/igor/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by BenTheElder** [comment]
when we patch containerd config we do this:

https://github.com/kubernetes-sigs/kind/blob/b6bc112522651d98c81823df56b7afa511459a3b/pkg/cluster/internal/create/actions/config/config.go#L189

this probably has a race window in which we've not reached `is-system-running` but containerd is. we should update this step.

**Comment by BenTheElder** [comment]
I believe this is fixed at HEAD but I've not actually thoroughly confirmed (there's an obvious logical error in the previous logic and I'm low on time to do more) -- if you observe this after running with a build after https://github.com/kubernetes-sigs/kind/pull/2382 or after the next release please let us know and we'll follow up.
