### ISSUE TITLE
kind v0.11.0/arm64 kubectl times out

### ISSUE THREAD

**Issue by vnallamothu** [kubernetes-sigs/kind#2265]
**What happened**:

Tried to bring up a kind cluster with registry on arm64 (aws graviton instance). Kind reports success, but kubectl fails to connect.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

ubuntu@ip-172-31-24-234:~/k8s$ sudo ./kind-with-registry.sh
5652f3b8edd5946daf9f9f5e7863b1ef5556cfb4f82fb5709b960263fe4bf113
Registry Host: kind-registry
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦
✓ Writing configuration 📜
  Starting control-plane 🕹️
 ✓ Installing CNI 🔌
✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
configmap/local-registry-hosting created

ubuntu@ip-172-31-24-234:~/k8s$ sudo docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS         PORTS                                       NAMES
1ce1d14cc886   kindest/node:v1.21.1   "/usr/local/bin/entr…"   9 minutes ago   Up 9 minutes   127.0.0.1:42709->6443/tcp                   kind-control-plane
5652f3b8edd5   registry:2             "/entrypoint.sh /etc…"   9 minutes ago   Up 9 minutes   0.0.0.0:5000->5000/tcp, :::5000->5000/tcp   kind-registry

ubuntu@ip-172-31-24-234:~/k8s$ sudo kubectl get pods -A
Unable to connect to the server: net/http: TLS handshake timeout
ubuntu@ip-172-31-24-234:~/k8s$ sudo kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): kind v0.11.0 go1.16.4 linux/arm64
- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/arm64"}
Unable to connect to the server: net/http: TLS handshake timeout
- Docker version: (use `docker info`): 
Client:
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.2-0ubuntu1~20.04.2
 Built:             Tue Mar 30 21:33:43 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.2-0ubuntu1~20.04.2
  Built:            Mon Mar 29 19:10:09 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.4-0ubuntu1~20.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.2-dev
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        

- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by BenTheElder** [comment]
> Unable to connect to the server: net/http: TLS handshake timeout

this usually means you're not using the appropriate kubeconfig.

kind automatically exports kubeconfig to the standard location by default. this is roughly $HOME/.kube/config which is per user. if you switch users (e.g. using sudo) then it will not be detected by kubectl.

this is fixable by using a consistent user or by explicitly setting the kubeconfig path either with the environment variable or the flag on all commands (kind and kubectl).

**Comment by BenTheElder** [comment]
if this is not the case, it would be helpful to minimize the reproducer, e.g. does this reproduce without using the script? just using `kind create cluster`?

**Comment by vnallamothu** [comment]
> kind automatically exports kubeconfig to the standard location by default. this is roughly $HOME/.kube/config which is per user. if you switch users (e.g. using sudo) then it will not be detected by kubectl.
> 
> this is fixable by using a consistent user or by explicitly setting the kubeconfig path either with the environment variable or the flag on all commands (kind and kubectl).

Thanks this helped resolve the issue!

I added user to docker group, re-login and tried again and it came up fine.

usermod -aG docker $USER
