### ISSUE TITLE
multi-node cluster is failing to bootstrap in kind v0.11.0 docker rootless mode

### ISSUE THREAD

**Issue by calshankar** [kubernetes-sigs/kind#2267]
**What happened**:

Kind cluster is failing to bootstrap in manjaro kernel (5.11.18-1-MANJARO) & cgroupV2 setting .. API server seems to be timing out when started with kind config param with additional nodes, though a single master node without config does not report error & kind cluster comes up fine.. The issue seems to happen in both Docker in rootless mode

**What you expected to happen**:

Cluster should bootstrap  

**How to reproduce it (as minimally and precisely as possible)**:

Upon further investigation in to the kind logs i noticed this from the export logs which seem to suggest that node nw is broken for some reason.. The entire kind log is attached as zip file.. pasting snippet here. 

> May 20 15:18:04 local-k8s-worker2 containerd[156]: time="2021-05-20T15:18:04.904795402Z" level=info msg="Connect containerd service"
> May 20 15:18:04 local-k8s-worker2 containerd[156]: time="2021-05-20T15:18:04.904830611Z" level=info msg="Get image filesystem path \"/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs\""
> May 20 15:18:04 local-k8s-worker2 containerd[156]: time="2021-05-20T15:18:04.904842785Z" level=warning msg="Running containerd in a user namespace typically requires disable_cgroup, disable_apparmor, restrict_oom_score_adj set to be true"
> May 20 15:18:04 local-k8s-worker2 containerd[156]: time="2021-05-20T15:18:04.905187639Z" level=error msg="failed to load cni during init, please check CRI plugin status before setting up network for pods" error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config
> the containerd config that i see in my setup is having these config value

> **containerd config dump | egrep -i 'cgroup|systemd|apparmor|oom'**
> oom_score = 0
> [cgroup]
>     systemd_cgroup = false
>     disable_cgroup = false
>     disable_apparmor = false
>     restrict_oom_score_adj = false

**_docker info..._**

> Server Version: 20.10.6
> Storage Driver: overlay2
>   Backing Filesystem: xfs
>   Supports d_type: true
>   Native Overlay Diff: false
>  Logging Driver: [json-file](url)
>  Cgroup Driver: systemd
>  Cgroup Version: 2`

i'm running docker in rootles mode as per the instructions here.. https://docs.docker.com/engine/security/rootless/#exposing-privileged-ports https://kind.sigs.k8s.io/docs/user/rootless/

**Anything else we need to know?**:

Looks like issue with containerd config is causing cluster initialization to fail (based on the log)

**Environment:**

- kind version: (use `kind version`):  [v0.11.0](url)
- Kubernetes version: (use `kubectl version`): 1.21
- Docker version: (use `docker info`): attached
- OS (e.g. from `/etc/os-release`):  MANJARO 5.11.18-1

[export_logs.zip](https://github.com/kubernetes-sigs/kind/files/6518164/export_logs.zip)

**Comment by AkihiroSuda** [comment]
> The issue seems to happen in both Docker in root/rootless mode


If this issue is not specific to rootless, could you remove "rootless" from the issue title?

**Comment by BenTheElder** [comment]
sorry, there was a prior discussion in #kind slack and the title didn't reflect that. it's still not accurate since we bootstrap multi-node clusters continuously, but we don't have the real root cause yet. initially it appeared to bee rootless.

**Comment by calshankar** [comment]
@BenTheElder @AkihiroSuda 
I can confirm this is not an issue when docker is running as root with _kind version: v0.11.0_. I added additional kernel command-line parameter forcing kernel to Prevent cgroups-v1 from automatically mounting during the system boot, the cgroup hierarchy was already enabled as part of my rootless testing as in kind docs.. 

`GRUB_CMDLINE_LINUX="nouveau.modeset=0 systemd.unified_cgroup_hierarchy=1 **cgroup_no_v1=all**"` 

Ofcourse `sudo  update-grub` and reboot was required. Do you think it is better forced this way??

**Comment by BenTheElder** [comment]
From the api-server logs:

> 2021-05-20T18:46:53.874181911Z stderr F I0520 18:46:53.874150       1 flags.go:59] FLAG: --runtime-config="authorization-mode=RBAC,kubeProxyMode=ipvs"

> 2021-05-20T18:46:53.874445412Z stderr F Error: runtime-config invalid key authorization-mode


I don't think your issue is accurately describing your cluster bringup? ipvs is definitely not the default.

**Comment by BenTheElder** [comment]
api-server is not coming up due to invalid config, so none of the other components can come up, per logs in https://github.com/kubernetes-sigs/kind/files/6518164/export_logs.zip

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ has valid runtime-config values
