### ISSUE TITLE
Running kind with kubelet flags

### ISSUE THREAD

**Issue by jicowan** [kubernetes-sigs/kind#2268]
Is it possible to pass flags to the kubelet with kind? I'm trying to figure out the best way to test https://kubernetes.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/.

**Comment by BenTheElder** [comment]
yes, there's an example here: https://kind.sigs.k8s.io/docs/user/configuration/#kubeadm-config-patches yes,
