### ISSUE TITLE
submit conformance results for v1.21

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#2276]
We haven't submitted for a few releases and our conformant status is expiring.

We need to submit again, we should do v0.11.0 + kubernetes v1.21.1, with sonobuoy.

Our last submission can be a good starting point. I think we can do an even simpler version this time with just:
- briefly how to install kind + a link to our install guide
- the kind version used
- sonobuoy + the version. used
- create cluster using a minimal multi-node config (see past submissions)
- run tests
https://github.com/cncf/k8s-conformance/pull/939

**Comment by BenTheElder** [comment]
Conformance for kind expires on the 26th. 

While we're not actively using the logo etc., it would be best not to let that lapse. 

We know the project is conformant, but we need to continue to submit evidence + reproducing instructions.

**Comment by amwat** [comment]
https://github.com/cncf/k8s-conformance/pull/1469

**Comment by amwat** [comment]
/close 

https://github.com/cncf/k8s-conformance/pull/1469 has merged
