### ISSUE TITLE
invalid syntax when parsing  /kind/kubeadm.conf - "kind cluster create" fails in Kubernetes version v1.21.1

### ISSUE THREAD

**Issue by alexeadem** [kubernetes-sigs/kind#2277]
kubernertes version `v1.21.1` fails in  `kubeadm init ` when running `kind create cluster --image image/node:v1.21.1 -v3` with syntax error in kubelet logs.

Kubernetes versions "v1.18.19","v1.17.17","v1.19.11","v1.20.7", work just fine

`
err="invalid argument \"falseKUBELET_EXTRA_ARGS=--fail-swap-on=false\" for \"--fail-swap-on\" flag: strconv.ParseBool: parsing \"falseKUBELET_EXTRA_ARGS=--fail-swap-on=false\": invalid syntax
`

**What happened**:

**What you expected to happen**:

It should just complain but accept the config as in image kindest/node:v1.21.1
```
May 25 02:48:34 kind-control-plane kubelet[769]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 25 02:48:34 kind-control-plane kubelet[769]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 25 02:48:34 kind-control-plane kubelet[769]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 25 02:48:34 kind-control-plane kubelet[769]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 25 02:48:34 kind-control-plane kubelet[769]: I0525 02:48:34.262796     769 server.go:197] "Warning: For remote container runtime, --pod-infra-container-image is ignored in kubelet, which should be set in that remote runtime instead"
```

accept syntax as in kinder

**How to reproduce it (as minimally and precisely as possible)**:
I followed instructions on how to create customer images here:
https://github.com/kubernetes-sigs/kind/blob/main/site/content/docs/contributing/development.md

**Anything else we need to know?**:

`journalctl -xu kubelet`

```
May 25 02:31:34 kind-control-plane kubelet[479]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 25 02:31:34 kind-control-plane kubelet[479]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 25 02:31:34 kind-control-plane kubelet[479]: E0525 02:31:34.580270     479 server.go:156] "Failed to parse kubelet flag" err="invalid argument \"falseKUBELET_EXTRA_ARGS=--fail-swap-on=false\" for \"--fail-swap-on\" flag: strconv.ParseBool: parsing \"falseKUBELET_EXTRA_ARGS=--fail-swap-on=false\": invalid syntax
```

**Environment:**

- kind version: (use `kind version`):

- Kubernetes version: (use `kubectl version`):
- - v1.21.1
- Docker version: (use `docker info`):
- Version:           19.03.11
- OS (e.g. from `/etc/os-release`):
VERSION="32 (Workstation Edition)"

**Comment by BenTheElder** [comment]
Please include the kind version.

**Comment by BenTheElder** [comment]
This issue is currently not reproducible. 

kind v0.11.0 (current stable release) has a v1.21.1 image by default (`kindest/node:v1.21.1@sha256:fae9a58f17f18f06aeac9772ca8b5ac680ebbed985e266f711d936e91d113ba`), which works fine with `kind create cluster -v3`

> err="invalid argument \"falseKUBELET_EXTRA_ARGS=--fail-swap-on=false\" for \"--fail-swap-on\" flag: strconv.ParseBool: parsing \"falseKUBELET_EXTRA_ARGS=--fail-swap-on=false\": invalid syntax

This should not happen with any kind version, are you using kinder or some customized base image ..?

**Comment by alexeadem** [comment]
I checkout out kind v0.11.0 and recreated the image and the syntax error is gone but I'm getting:

`Kubelet: invalid configuration: cgroup-root ["kubelet"] doesn't exist`
which was fixed here:
`Fix entrypoint cgroups mounts #1995
images/base/files/usr/local/bin/entrypoint`

Yes I was using `kinder do kubeadm-init --loglevel trace -v=6` but I see ou added other files under.

I see you added new config under:
 `pkg/cluster/internal/kubeadm/config.go` such as `KubeletConfiguration` and `apiVersion: kubeadm.k8s.io/v1beta2` maybe I need to add those too...

Alex

**Comment by alexeadem** [comment]
ok i was missing that one line. issue fixed

`cgroupDriver: cgroupfs`

under

`apiVersion: kubelet.config.k8s.io/v1beta1`

```
---
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: cgroupfs
evictionHard:
  imagefs.available: 0%
  nodefs.available: 0%
  nodefs.inodesFree: 0%
imageGCHighThresholdPercent: 100
kind: KubeletConfiguration
```

**Comment by BenTheElder** [comment]
Yes, that's due to the kubeadm change in v1.21
kind v0.11 handles this, kinder will need to as well.

You should probably build images for kinder with kinder, kind images may not work across releases.

E.g. in the future we may actually switch to systemd which will necessitate changes to both kind and the images most likely.
