### ISSUE TITLE
Optimize --wait

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kind#2282]
**What would you like to be added**:

--wait seems to complete on 30 second increments, suggesting that we may have room to optimize it a bit. Code in https://github.com/kubernetes-sigs/kind/blob/b6bc112522651d98c81823df56b7afa511459a3b/pkg/cluster/internal/create/actions/waitforready/waitforready.go#L84

The hypothesis is that we are hitting a 30s kubectl timeout which could perhaps be improved by droppped the kubectl timeout

From Ben:

> I would not be surprised if that needed more attention, we added it initially to help deal with kubernetes e2e.test failing out hard if the cluster wasn't at least a certain level of ready, but now it's much better behaved and we've been hesitant to change the definition.
> I bet we can tune the kubectl timeout lower, and I wouldn't be surprised if something changed in kubernetes related to this..
> I do still think the tests or a seperate tool defining their own level of expected readiness is probably best anyhow though, like most users don't need all nodes to be full ready (just the api) but istio might want say istio pods to be ready.

**Why is this needed**:

So cluster creation is faster

Our test results:
```
$ gsutil ls gs://istio-prow/pr-logs/pull/istio_istio/33094/**/build-log.txt | xargs -n1 gsutil cat | rg 'Ready after'
 • Ready after 53s 💚
 • Ready after 1m3s 💚
 • Ready after 1m3s 💚
 • Ready after 33s 💚
 • Ready after 1m3s 💚
 • Ready after 1m3s 💚
 • Ready after 1m3s 💚
 • Ready after 53s 💚
 • Ready after 1m3s 💚
 • Ready after 1m3s 💚
 • Ready after 1m3s 💚
 • Ready after 1m30s 💚
 • Ready after 1m3s 💚
 • Ready after 1m3s 💚
 • Ready after 1m23s 💚
 • Ready after 1m24s 💚
 • Ready after 1m3s 💚
 • Ready after 1m3s 💚
 • Ready after 1m2s 💚
```

**Comment by BenTheElder** [comment]
incidentally: what are you setting `--wait` to?

Also do you know what version this is? I'm getting 23s pretty consistently in my local env with kind @ HEAD (kubernetes v1.21.1, more or less kind v0.11.1).

The obvious thing to try was setting `--request-timeout` but it's making no difference so far.

**Comment by howardjohn** [comment]
At the time - 60s on kind v0.10 v1.21.0 k8s

Now: 180s, kind v0.11, v1.21.1 k8s.

Actually seems a lot better now (test PR: 33319):
```
 • Ready after 34s 💚
 • Ready after 32s 💚
 • Ready after 21s 💚
 • Ready after 23s 💚
 • Ready after 23s 💚
 • Ready after 30s 💚
 • Ready after 33s 💚
 • Ready after 24s 💚
 • Ready after 24s 💚
 • Ready after 24s 💚
 • Ready after 24s 💚
 • Ready after 23s 💚
 • Ready after 33s 💚
 • Ready after 34s 💚
 • Ready after 23s 💚
 • Ready after 23s 💚
 • Ready after 24s 💚
 • Ready after 23s 💚
 • Ready after 23s 💚
 • Ready after 23s 💚
 • Ready after 23s 💚
 • Ready after 23s 💚
 • Ready after 34s 💚
 • Ready after 52s 💚
 • Ready after 1m2s 💚
 • Ready after 23s 💚
 • Ready after 23s 💚
 • Ready after 23s 💚
 • Ready after 23s 💚
 • Ready after 33s 💚
 • Ready after 33s 💚
 • Ready after 33s 💚
 • Ready after 23s 💚
 • Ready after 23s 💚
 • Ready after 33s 💚
 • Ready after 31s 💚
 • Ready after 32s 💚
 • Ready after 23s 💚
 • Ready after 24s 💚
 • Ready after 23s 💚
 • Ready after 24s 💚
 • Ready after 23s 💚
 • Ready after 33s 💚
 • Ready after 33s 💚
 • Ready after 24s 💚
 • Ready after 24s 💚
 • Ready after 24s 💚
 • Ready after 53s 💚
 • Ready after 50s 💚
 • Ready after 24s 💚
 • Ready after 34s 💚
 • Ready after 33s 💚
 • Ready after 45s 💚
 • Ready after 24s 💚
 • Ready after 24s 💚
 • Ready after 23s 💚
 • Ready after 24s 💚
 • Ready after 34s 💚
 • Ready after 33s 💚
```

I wonder if it was somehow related to our node problems

**Comment by BenTheElder** [comment]
That seems plausible, I'm seeing extremely regular times for bringup locally, some component(s) in the cluster probably have predictable retry timing. 

The wait loop basically does ask the API-server as fast as it can until ready, but I'm seeing ~0.25s / attempt, so I don't think it's impacting bringup much. ~4 QPS seems fairly reasonable for waiting until ready. I think we can probably leave this as-is and focus more on other aspects of startup.
