### ISSUE TITLE
kubectl can't connect to k8s cluster created by find. No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by chenjinkai** [kubernetes-sigs/kind#2283]
**os：**
windows7

**docker：**
DockerToolbox-18.03.0-ce.exe

**kind：**
kind v0.11.0 go1.16.4 windows/amd64

**k8s created by kind：**
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                       NAMES
6588e3f7b68f        kindest/node:v1.20.7   "/usr/local/bin/entr…"   4 hours ago         Up 4 hours          127.0.0.1:63087->6443/tcp   local-control-plane

**kubectrl config:**
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:63087
  name: kind-local
contexts:
- context:
    cluster: kind-local
    user: kind-local
  name: kind-local
current-context: kind-local
kind: Config
preferences: {}
users:
- name: kind-local
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED

**problem:**
`$ kubectl version --short`
`Client Version: v1.20.7
Unable to connect to the server: dial tcp 127.0.0.1:63087: connectex: No connection could be made because the target machine actively refused it.
`
`$ kubectl cluster-info`
`To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp 127.0.0.1:63087: connectex: No connection could be made because the target machine actively refused it.
`

**exported log**
[log file](https://github.com/chenjinkai/k8slogs/blob/main/k8slogs-bak.zip)

**Comment by BenTheElder** [comment]
Docker toolbox is deprecated and I highly recommend switching to docker desktop https://github.com/docker/toolbox

Due to the standing depreciation we've not invested resources in working with toolbox.

**Comment by chenjinkai** [comment]
> Docker toolbox is deprecated and I highly recommend switching to docker desktop https://github.com/docker/toolbox#warning-deprecation-notice-this-project-and-repository-is-now-deprecated-and-is-no-longer-in-active-development-please-use-docker-desktop-instead-where-possible-docker-desktop
> 
> Due to the standing depreciation we've not invested resources in working with toolbox.

Thank you. I will try it.

**Comment by chenjinkai** [comment]
it is ok, using kind with win10 and docker-desktop.

**Comment by BenTheElder** [comment]
great!

The networking is probably acting up with docker toolbox, but seeing as toolbox is deprecated and you've got it working with docker's supported replacement I will close this for now.
