### ISSUE TITLE
Can't find module `autofs4` on macOS

### ISSUE THREAD

**Issue by XAMPPRocky** [kubernetes-sigs/kind#2286]
**What happened**: When trying to run `kind create cluster` on a fresh installation of docker, and Kubernetes on macOS Big Sur (11.3.1), the server logs `Failed to find module 'autofs4'` along with failing to symlink `cpu`, `cpuacct`, `net_cls`, and `net_prio` files from cgroups.

**What you expected to happen**: No errors.

**How to reproduce it (as minimally and precisely as possible)**: `kind create cluster`

**Anything else we need to know?**:

```
INFO: ensuring we can execute mount/umount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: detected cgroup v1
INFO: fix cgroup mounts for all subsystems
INFO: clearing and regenerating /etc/machine-id
Initializing machine ID from random generator.
INFO: faking /sys/class/dmi/id/product_name to be "kind"
INFO: faking /sys/class/dmi/id/product_uuid to be random
INFO: faking /sys/devices/virtual/dmi/id/product_uuid as well
INFO: setting iptables to detected mode: legacy
INFO: Detected IPv4 address: 172.18.0.2
INFO: Detected IPv6 address: fc00:f853:ccd:e793::2
Failed to find module 'autofs4'
systemd 246.6-1ubuntu1.3 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid)
Detected virtualization docker.
Detected architecture x86-64.
Failed to create symlink /sys/fs/cgroup/cpu: File exists
Failed to create symlink /sys/fs/cgroup/cpuacct: File exists
Failed to create symlink /sys/fs/cgroup/net_cls: File exists
Failed to create symlink /sys/fs/cgroup/net_prio: File exists
Welcome to Ubuntu 20.10!
Set hostname to <kind-control-plane>.
Queued start job for default target Graphical Interface.
[ OK ] Started Dispatch Password …ts to Console Directory Watch.
[UNSUPP] Starting of Arbitrary Exec…Automount Point not supported.
[ OK ] Reached target Local Encrypted Volumes.
[ OK ] Reached target Paths.
[ OK ] Reached target Slices.
[ OK ] Reached target Swap.
[ OK ] Listening on Journal Audit Socket.
[ OK ] Listening on Journal Socket (/dev/log).
[ OK ] Listening on Journal Socket.
[ OK ] Reached target Sockets.
Mounting Huge Pages File System...
Mounting Kernel Debug File System...
Mounting Kernel Trace File System...
Starting Journal Service...
Starting Create list of st…odes for the current kernel...
Mounting FUSE Control File System...
Starting Remount Root and Kernel File Systems...
Starting Apply Kernel Variables...
[ OK ] Mounted Huge Pages File System.
[ OK ] Mounted Kernel Debug File System.
[ OK ] Mounted Kernel Trace File System.
[ OK ] Finished Create list of st… nodes for the current kernel.
[ OK ] Mounted FUSE Control File System.
[ OK ] Finished Remount Root and Kernel File Systems.
Starting Create System Users...
Starting Update UTMP about System Boot/Shutdown...
[ OK ] Finished Apply Kernel Variables.
[ OK ] Finished Update UTMP about System Boot/Shutdown.
[ OK ] Finished Create System Users.
[ OK ] Started Journal Service.
Starting Flush Journal to Persistent Storage...
Starting Create Static Device Nodes in /dev...
[ OK ] Finished Flush Journal to Persistent Storage.
[ OK ] Finished Create Static Device Nodes in /dev.
[ OK ] Reached target Local File Systems (Pre).
[ OK ] Reached target Local File Systems.
[ OK ] Reached target System Initialization.
[ OK ] Started Daily Cleanup of Temporary Directories.
[ OK ] Reached target Basic System.
[ OK ] Reached target Timers.
Starting containerd container runtime...
[ OK ] Started containerd container runtime.
[ OK ] Reached target Multi-User System.
[ OK ] Reached target Graphical Interface.
Starting Update UTMP about System Runlevel Changes...
[ OK ] Finished Update UTMP about System Runlevel Changes.
```

**Environment:**

- kind version: (use `kind version`): `kind v0.11.0 go1.16.3 darwin/amd64` (Homebrew)
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-18T01:10:20Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 36
  Running: 35
  Paused: 0
  Stopped: 1
 Images: 12
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.94GiB
 Name: docker-desktop
 ID: SU3V:6I2X:KPFB:TTEF:R4HS:GKWO:I7DC:QVMK:4PEO:AA6L:4FSG:J53Q
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`): macOS 11.3.1

**Comment by BenTheElder** [comment]
My personal machine on macOS 11.3.1:

```console
$ kind version
kind v0.11.0 go1.16.4 darwin/amd64

$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 5
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 9.732GiB
 Name: docker-desktop
 ID: GR3G:AS7H:BMXN:PS7M:GTFK:VBZI:PFS7:YUZA:IAX7:TE7R:RGQX:7RCY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂

```


I see the same errors if I do `docker logs kind-control-plane` but those errors in the node log are not a problem.
The autofs4 error is from systemd which we can't control and isn't causing anything to not work. The symlink errors we should know about but shouldn't be a problem for now.

**Comment by XAMPPRocky** [comment]
@BenTheElder While the errors might not be kind's problem, I do consider it a kind bug that it does not give the user any indication that these errors are in fact fine and ignorable. When I was running into other errors with running kind, seeing a bunch of errors with no kind of prefix of where it came from or its severity gives the impression that there is a critical error with the setup, and the problem is with the `autofs4` module. This kind of confusion can lead to users wasting time spending trying to debug a problem, when `kind` should have informed the user in the logs that it could be ignored.

**Comment by BenTheElder** [comment]
Also: it is idiomatic in kubernetes for transient errors to occur and be logged, reconciling towards a healthy state. The concern when debugging is if it does not reach a healthy state, to work backwards from there. For example the standard kubeadm package involves kubelet panic-ing and crashing in a loop until configured.

We've specifically put in effort to avoid that, but we're not going to modify systemd or the behavior of your host kernel.

**Comment by XAMPPRocky** [comment]
> The autofs4 thing is something between systemd and the kernel, it is not a kind bug and we cannot change it. I don't expect the average user to attempt to debug the kind container logs on their own and the kind tool will not display them.

Well I'm using this tool for the first time, and I ran into these errors very quickly (It's literally the first thing you see when you open the container in Docker Desktop), and this was my first impression with it, so I imagine my experience is at least somewhat more representative of the average than your assuming. I'm sure you did put a lot work into it, but that work is squandered when this is your reaction to first time users. The only thing you've convinced me of, is to go use another project.

<img width="1362" alt="Screenshot 2021-05-27 at 11 58 26" src="https://user-images.githubusercontent.com/4464295/119807982-f871e700-bee3-11eb-93d8-4ada031fd6ad.png">

**Comment by BenTheElder** [comment]
If you look through the other logs in Kubernetes you will find other errors you will find that we also cannot do anything about because they are normal and expected.

We cannot change systemd's output. It's not our bug. As far as I can tell it's already been resolved upstream, it should be fixed when docker gets a newer kernel.

> I'm sure you did put a lot work into it, but that work is squandered when this is your reaction to first time users. 

We have. I'm sorry if my tone has been poor. Or if you mean that we closed the issue, that is because
a) logging errors that are non fatal is expected throughout the ecosystem. If they were fatal the script / program would exit.
b) we cannot change the titular issue ourselves

I'm not sure what you expect here. Do you have a concrete proposal for changing the code in this project?

> The only thing you've convinced me of, is to go use another project.

I mean by all means do but you're going to find the same output in any similar project. The only close alternative for running upstream Kubernetes in a container is minikube which uses a fork of our same image because all of the "in docker" bits are derviative and will produce identical output to an older version of this image.

It's likely any other tool would as well because kubernetes more or less requires systemd and this is a systemd + kernel interaction.
