### ISSUE TITLE
create cluster fails with permission denied error on /dev/dma_heap

### ISSUE THREAD

**Issue by elmiko** [kubernetes-sigs/kind#2296]
**What happened**:

After updating my Fedora Linux to the latest kernel (`5.11.12-300.fc34.x86_64`) i tried to run `kind create cluster` and hit this error:

```
Creating cluster "mgmt" ...                                                                                                               
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼                                                                                           
 ✗ Preparing nodes 📦                                                                                                                     
ERROR: failed to create cluster: docker run error: command "docker run --hostname mgmt-control-plane --name mgmt-control-plane --label io.
x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run 
--volume /var --volume /lib/modules:/lib/modules:ro -e KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER --device /dev/fuse --detach --tty --label 
io.x-k8s.kind.cluster=mgmt --net kind --restart=on-failure:1 --init=false --volume=/var/run/docker.sock:/var/run/docker.sock --publish=127
.0.0.1:40963:6443/TCP -e KUBECONFIG=/etc/kubernetes/admin.conf kindest/node:v1.21.1@sha256:80773e2069dd4a80a4929fdef050c1e463e1d5578c2cd9a
f3962cfbc230e1500" failed with error: exit status 126                                                                                     
Command Output: 6a36fe59f40c4d4338b75c0b357d0ceb4f789319550fe61196c3f76dbdb8ec3b                                                          
docker: Error response from daemon: open /dev/dma_heap: permission denied.
```

**What you expected to happen**:

Cluster to be created as normal.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install Fedora 34
2. run `dnf --refresh upgrade -y` to update to latest kernel
3. run `kind create cluster`

**Anything else we need to know?**:

**Environment:**

- kind version: `kind v0.12.0-alpha+1188d9bd86afbf go1.16.4 linux/amd64`
- Kubernetes version: `1.21.1`
- Docker version: `20.10.6`
- OS (e.g. from `/etc/os-release`): Fedora 34

**Comment by BenTheElder** [comment]
Is this rootless docker by any chance?
https://kind.sigs.k8s.io/docs/user/rootless/

Can you share the rest of `docker info`?

**Comment by BenTheElder** [comment]
I think this is a fedora bug actually, mislabeling the device in selinux https://bugzilla.redhat.com/show_bug.cgi?id=1966158

**Comment by elmiko** [comment]
> I think this is a fedora bug actually, mislabeling the device in selinux https://bugzilla.redhat.com/show_bug.cgi?id=1966158

yeah, that seems correct. i suppose we can close this then as it looks like they are putting out a fix in fedora. thanks for finding that bugzilla!

**Comment by BenTheElder** [comment]
Thanks, Please let us know if anything changes!

**Comment by christianh814** [comment]
So I just ran into this and it looks like the policy was fixed. A relabel/restorecon is needed, however.

> All steps as root

Update the package

```shell
dnf -y update selinux-policy
```

Then before you relabel/restore; you need to set SELinux to permissive

```shell
setenforce 0
```

Now either relabel, or just restore from the updated policy

```shell
restorecon -vR /dev/dma_heap
```

Set SELinux to enforcing

```shell
setenforce 1
```

**Comment by BenTheElder** [comment]
thanks @christianh814! 🙏

**Comment by tao12345666333** [comment]
FYI https://github.com/fedora-selinux/selinux-policy/pull/763

**Comment by dlipovetsky** [comment]
For anyone on Fedora 33, there is no backport as of June 28, 2021, so putting SELinux in permissive mode (`setenforce 0`) is the only option I am aware of.

**Comment by BenTheElder** [comment]
@dlipovetsky thanks, that may need a known issues entry. @aojea at this point we might need to update the fedora-33 entry to just be more generally a sub-section on fedora known issues ...

**Comment by aojea** [comment]
> @dlipovetsky thanks, that may need a known issues entry. @aojea at this point we might need to update the fedora-33 entry to just be more generally a sub-section on fedora known issues ...

The problem I see is how to keep up with the fedora release schedule

> We say maintained for approximately 13 months because the supported period for releases is dependent on the date the release under development goes final. As a result, Release X is supported until one month (4 weeks) after the release of Release X+2.


Fedora Linux 33 EOL auto closure	is 11/2021

**Comment by dlipovetsky** [comment]
I PR'd the known issue. Once the Fedora 33 backport lands, it should be updated (to tell users to update their SELinux policy).

**Comment by BenTheElder** [comment]
@aojea fair point, but the other entry is proving to not be version specific and we've had a number of issues tracked that aren't on other common distros. we might still need a page for this or something, we know OOTB there are issues to be aware of.

**Comment by aojea** [comment]
> @aojea fair point, but the other entry is proving to not be version specific and we've had a number of issues tracked that aren't on other common distros. we might still need a page for this or something, we know OOTB there are issues to be aware of.

yep https://github.com/kubernetes-sigs/kind/pull/2341
