### ISSUE TITLE
Getting error in starting cluster using ipv6

### ISSUE THREAD

**Issue by yash97** [kubernetes-sigs/kind#2299]
`kind create cluster --config kind-config.yaml`
Error:
```  
Preparing nodes 📦
ERROR: failed to create cluster: failed to get random host port for port mapping: listen tcp [::1]:0: socket: address family not supported by protocol
```

kind-config.yaml:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv6
```
Activated ipv6 in docker from this link https://docs.docker.com/config/daemon/ipv6/

**Comment by BenTheElder** [comment]
Is your host capable of ipv6?
This error means docker was unable to listen with ipv6 on the host's loopback ("localhost") address.

**Comment by BenTheElder** [comment]
If you're doing rootless check https://github.com/kubernetes-sigs/kind/pull/2309

Happy to reopen and help more if you have follow-up, but there's not enough info here to help further at the moment.
