### ISSUE TITLE
kind docker container does not start with different docker data root

### ISSUE THREAD

**Issue by ghost** [kubernetes-sigs/kind#2300]
**What happened**:
when changing the data-root folder in /etc/docker/daemon.json the kind docker container does not start
**What you expected to happen**:
docker container start
**How to reproduce it (as minimally and precisely as possible)**:
create kind cluster
stop docker
create etc/docker/daemon.json with content:
`{ 
   "data-root": "/path/to/your/docker" 
}`
copy files from /var/lib/docker/ to the new folder
start docker
kind cluster does not start with error message:
`docker logs 
[  OK  ] Unmounted /var/lib/kubelet…et/kubernetes-dashboard-certs.
[  OK  ] Unmounted /var/lib/kubelet…ojected/kube-api-access-zdqbp.
[  OK  ] Stopped target Swap.
[  OK  ] Stopped Update UTMP about System Boot/Shutdown.
         Unmounting /var...
[  OK  ] Unmounted /var.
[  OK  ] Stopped target Local File Systems (Pre).
[  OK  ] Reached target Unmount All Filesystems.
[  OK  ] Stopped Create Static Device Nodes in /dev.
[  OK  ] Stopped Create System Users.
[  OK  ] Stopped Remount Root and Kernel File Systems.
[  OK  ] Reached target Shutdown.
[  OK  ] Reached target Final Step.
         Starting Halt...
INFO: ensuring we can execute mount/umount even with userns-remap
INFO: remounting /sys read-only
/usr/local/bin/entrypoint: line 147: /usr/bin/mount: cannot execute binary file: Exec format error
INFO: ensuring we can execute mount/umount even with userns-remap
INFO: remounting /sys read-only
/usr/local/bin/entrypoint: line 147: /usr/bin/mount: cannot execute binary file: Exec format error
`
``
**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): kind v0.11.0 go1.16.4 linux/amd64
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-04-09T16:47:30Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-18T01:10:20Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
- Docker version: (use `docker info`): 20.10.6
- OS (e.g. from `/etc/os-release`): Manjaro Linux

**Comment by BenTheElder** [comment]
Can you delete and recreate the cluster after moving the data root?

**Comment by BenTheElder** [comment]
I'm not sure it's valid with docker to copy the data root around with existing containers. E.g. It contains lots of symlinks. https://github.com/moby/moby/issues/3127#issuecomment-421264336
