### ISSUE TITLE
get name of the pod consuming highest cpu using kubectl command

### ISSUE THREAD

**Issue by HariHaraReddyD** [kubernetes-sigs/kind#2322]
I am trying to get the pod name with highest CPU utilization using kubectl command.
Able to retrieve list using following command but unable to write a jsonpath query to fetch the name of first pod from the output.
Appreciate any help in this regard. Thanks!

`kubectl top pod POD_NAME --sort-by=cpu `

**Comment by BenTheElder** [comment]
This question isn't really kind specific, you might get a quicker response asking in e.g. #kubernetes-users in the kubernetes slack, or in the kubernetes discuss instance https://discuss.kubernetes.io/, I will try to come back to this at some point.

**Comment by HariHaraReddyD** [comment]
Thanks for the response. Able to achieve this with following command -
`kubectl top pod -n qa --sort-by=cpu --no-headers | head -n 1 | cut -d " " -f 1`

**Comment by BenTheElder** [comment]
Thanks for sharing! :-)
