### ISSUE TITLE
sha256sums for kind binaries

### ISSUE THREAD

**Issue by cokegen** [kubernetes-sigs/kind#2331]
**What would you like to be added**: sha256sums / gpg signatures for kind binaries

**Why is this needed**: some basic form of verification at least for the kind binaries would be good to have, hashes, gpg signatures, etc.

**Comment by BenTheElder** [comment]
We can and should definitely add shasums to the binaries so download integrity can be checked. 

I don't think the Kubernetes project currently has a solution for signing, if/when it does we'll follow suit here.

kind binary builds should be reproducible at least though, so anyone can vet that the binary + sha reflects the sources fairly easily.

---

This should make a pretty good starter issue for anyone interested, basically update this script which we run as part of the release process to produce a `${file_name}.sha256sum` file containing the hash of `${file_name}` for each build output file after we build:

https://github.com/kubernetes-sigs/kind/blob/c64d7644516f7214c063b4cee5c324fd14e6dd1e/hack/release/build/cross.sh 

Then when we release these will be alongside the binary outputs and we'll upload them as well

/help
/good-first-issue
/sig testing

**Comment by asher-lab** [comment]
hello @viveksyngh is there a readme or some place where the sha256sum/sha512sum are published? like from kubernetes where the sha512 sum are in there readme file? https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md thanks

**Comment by BenTheElder** [comment]
They're alongside the release binaries. See "assets" at the bottom of e.g. https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0, which is standard for github hosted releases.
