### ISSUE TITLE
Kind Ingress not working with Knative: IngressNotConfigured

### ISSUE THREAD

**Issue by JCzz** [kubernetes-sigs/kind#2333]
Kind Ingress not working with Knative: It hangs in kubect get ksvc "IngressNotConfigured"

I have created the following cluster:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
      endpoint = ["http://${reg_name}:${reg_port}"]
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "127.0.0.1"
  # Portforward on macos <https://kind.sigs.k8s.io/docs/user/configuration/#ip-family>
  # ipFamily: ipv6
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  # apiServerPort: 6443
name: $NAME-cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
            node-labels: "my-label1=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "my-label2=true"
```

Looked at installing Ingress: https://kind.sigs.k8s.io/docs/user/ingress/#contour

Experimented with bout Conture and Kouier and bouth is not working with Kind Ingress setup - do you know why?

Installed using:
Loadbalencer: https://kind.sigs.k8s.io/docs/user/loadbalancer/
Kind Ingress: https://kind.sigs.k8s.io/docs/user/ingress/#contour
Knative network setup: https://knative.dev/docs/install/install-serving-with-yaml/

Note: I have adding same issue on Kind [repo](https://github.com/knative/serving/issues/11605)

**Environment:**

Kind

kind version     
kind v0.11.1 go1.16.4 darwin/amd64

kubectl version 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by BenTheElder** [comment]
was there a resolution? https://github.com/knative/serving/issues/11605 seems the same with no comment, is this actually a kind bug? (if not I will update the labels, it's useful for producing metrics on our issues)
