### ISSUE TITLE
`hostPath` in pods goes to the node container, not the kind host

### ISSUE THREAD

**Issue by ian-howell** [kubernetes-sigs/kind#2339]
**What happened**:

I've created a pod with a single container and a single `volumeMount`, which uses `hostPath`, as in the following:

```
apiVersion: v1
kind: Pod
metadata:
  name: host-path-test
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: alpine
    imagePullPolicy: Always
    name: alpine
    volumeMounts:
    - mountPath: /tmp/created
      name: tmp
  volumes:
  - hostPath:
      path: /tmp/created
    name: tmp
```

I then `exec` into the pod and create a file. This file appears within the container, but it does not appear on the host:

```
# kubectl exec -it host-path-test -c alpine -- ls -la /tmp/created
total 4
drwxr-xr-x    2 root     root            40 Jun 28 19:33 .
drwxrwxrwt    1 root     root          4096 Jun 23 18:32 ..

# kubectl exec -it host-path-test -c alpine -- touch /tmp/created/some-file

# kubectl exec -it host-path-test -c alpine -- ls -la /tmp/created
total 4
drwxr-xr-x    2 root     root            60 Jun 28 19:34 .
drwxrwxrwt    1 root     root          4096 Jun 23 18:32 ..
-rw-r--r--    1 root     root             0 Jun 28 19:34 some-file

# ls -la /tmp/created
ls: cannot access '/tmp/created': No such file or directory
```

**What you expected to happen**:
The directory and file should be created on the host.

**How to reproduce it (as minimally and precisely as possible)**:
Simply follow the above.

**Anything else we need to know?**:
I've attempted this with and without the `DirectoryOrCreate` option, as well as having pre-created the directory on the host.

Interestingly, upon deletion and recreation of the pod, the created files appear to remain:
```
# kubectl delete pod host-path-test
pod "host-path-test" deleted

# kubectl apply -f host-path-test.yaml
pod/host-path-test created

# kubectl exec -it host-path-test -c alpine -- ls -la /tmp/created
total 4
drwxr-xr-x    2 root     root            60 Jun 28 19:34 .
drwxrwxrwt    1 root     root          4096 Jun 28 19:39 ..
-rw-r--r--    1 root     root             0 Jun 28 19:34 some-file
```
This leads me to believe that the directory *is* being created on the host somewhere, it just isn't where I've specified in the Pod definition.

**Environment:**

- kind version: (use `kind version`):
**kind v0.10.0 go1.15.7 linux/amd64**

- Kubernetes version: (use `kubectl version`):
**'Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}**

- Docker version: (use `docker info`):
**20.10.4**

- OS (e.g. from `/etc/os-release`):
**Ubuntu 20.04.1 LTS**

**Comment by BenTheElder** [comment]
the "host" to Kubernetes is a kind node, which is itself another container 🙃

see diagram here https://kind.sigs.k8s.io/docs/design/initial/ which is still more or less accurate, more recent info is in the resources page

if you want to make it show up on your _actual_ host, see:
https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts
and add a hostPath for the node to your host, and then use the containerPath from that config as the hostPath in the pod.

if would be very problematic for multiple clusters / multi-node clusters if they ran directly in your host filesystem, so this is working-as-intended.

**Comment by BenTheElder** [comment]
That is, your hostPath writes are going to the node filesystem, so you'll find them under `docker exec $nodeName ls $hostPath`, not `ls $hostPath` on the host running docker. You can have it on the host running docker by configuring the nodes.

For a default cluster, that would be `docker exec kind-control-plane ls /tmp/created`

Also FWIW: In Kubernetes `hostPath` is generally not a great idea unless you're writing a system daemonset, you should probably use a persistent volume claim instead. hostpath is only writable from pods running as root by design and is considered highly privileged and is best used to manipulate the host (e.g. to install drivers). For writing some data a persistent volume is more appropriate. On kind you probably don't want to be running pods designed to manipulate the host, as the nodes share the host kernel.
