### ISSUE TITLE
Transition from fmt.Errorf() to pkg/errors

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/kind#234]
the codebase includes a number of fmt.Errorf() calls.
kubeadm and the cluster-api already have moved to using the [pkg/errors](https://godoc.org/github.com/pkg/errors/) package instead.
this package is already vendored in kind.

examples:
```
fmt.Errorf("some error: %v", err) -> errors.Wrap(err, "some message")
fmt.Errorf("object %s; error: %v", objStr, err) -> errors.Wrapf(err, "some object %s; error", objStr)
errors.New("some error") -> errors.New("some error")
//  ^ `errors` comes from pkg/errors now
fmt.Errorf("some message %s, objStr) -> errors.Errorf("some message %s", objStr)
```

note: splitting this into more than one PR might be easier to manage.
e.g at least one for /cmd and one for /pkg.

/kind cleanup
/priority important-longterm
/good-first-issue
/help

**Comment by munnerz** [comment]
🤔 `pkg/errors` in the golang stdlib (as linked) does not contain a `Wrap` function, only the `New` function (and the `New` functions docs recommend using `fmt.Errorf` for formatting of errors).

I'm assuming this should be `github.com/pkg/errors` instead?

**Comment by neolit123** [comment]
the link in OP includes:
https://godoc.org/github.com/pkg/errors#Wrap
https://godoc.org/github.com/pkg/errors#Wrapf
...

**Comment by idealhack** [comment]
The link has been edited, @munnerz you saw the link 14 hours ago? 😅

**Comment by BenTheElder** [comment]
The link was wrong and I fixed it and pinged Lubomir out of band to let him
know I'd edited it in an attempt to avoid cluttering the issue with
comments about the link 🤣

**Comment by idealhack** [comment]
With these three PRs merged, I don't think we have any `fmt.Errorf()` left in `/cmd` or `/pkg` now, except `/pkg/build/base/sources/images_sources.go` which was generated by go-bindata.
