### ISSUE TITLE
Consider not disabling CGO

### ISSUE THREAD

**Issue by lukehinds** [kubernetes-sigs/kind#2343]
I am not sure how much of chance there is of this happening, but hey worth a go (no pun intended)

https://github.com/kubernetes-sigs/kind/pull/1937 disabled CGO, at the time the comment was made "if someone really wants CGO (no real reason currently) they can build with make build CGO_ENABLED=1"

I am working on a project, where we are using the kind helm github action to test a k8s deployment. The problem is we have a popular pkcs11 library that requires CGO, so our k8s build fails when using kind.  Currently we cannot use `make build CGO_ENABLED=1` as the helm action is just curl'ing down the pre built binaries. Users also won't be able to use kind to run our app (app is [sigstore](https://github.com/sigstore/))

Is there any chance I could help fix the build failure, it would mean we won't have to write our own helm plugin (to do the a `make` instead) and folks using our project can use kind out of the box (fresh from the release page).

**Comment by BenTheElder** [comment]
Sorry but our builds are reproducible and cross compilable and I don't think we're willing to give this up. Kubernetes also compiles kubectl in this way.

**Comment by BenTheElder** [comment]
I'm not sure I understand how kind being built with cgo or not relates to your library? Can you elaborate a bit more?

**Comment by BenTheElder** [comment]
It actually really shouldn't matter for kind, since that binary makes no network calls or anything else that might be using CGO in the stdlib anyhow, I suspect there's something else going on but need more details about what the issue is.

**Comment by lukehinds** [comment]
> I'm not sure I understand how kind being built with cgo or not relates to your library? Can you elaborate a bit more?

We depend on https://github.com/miekg/pkcs11 for HSM interoperability which requires CGO. I did see other go projects that depend on the same  hit CGO issues as well. Notary always builds with CGO_ENABLED as an e.g. 

https://github.com/theupdateframework/notary/blob/25cc887695251bb49efdb8e70bc1d8293d36945f/buildscripts/cross.sh#L23

**Comment by BenTheElder** [comment]
> We depend on https://github.com/miekg/pkcs11 for HSM interoperability which requires CGO. I did see other go projects that depend on the same hit CGO issues as well. Notary always builds with CGO_ENABLED as an e.g.

OK but where is the kind binary interacting with an HSM ..? `kind` is essentially a bunch of `exec` calls to tools like docker, kubeadm etc., and then some in-memory stuff processing all the yaml and so on.

If you're using prebuilt binaries, they should not in any way be interacting with things like HSMs or any CGO codepaths?

**Comment by BenTheElder** [comment]
> where we are using the kind helm github action to test a k8s deployment.

A pointer to this action would also be helpful, we have no affiliation with any github actions currently, and I honestly have not been able to keep up with what all people have build 😅 

> so our k8s build fails when using kind.

Are you talking about `kind build node-image` against some kubernetes sources? what versions? are they patched?

`CGO_ENABLED` at build time for the `kind` binary does not impact `CGO_ENABLED` for the kubernetes build system we're wrapping in order to produce a bundled image, we build how upstream builds*

\* for kind pre-built images we may or may not enable some some functionality we helped ship upstream for "dockerless" and [cloud-]"providerless" builds, but otherwise it's just what you get when you build a release the same as normal kubernetes release, we then package the output.

**Comment by lukehinds** [comment]
Hey Ben, sorry I have been well and truly barking up the wrong tree here and narrowed the issue down to a ko configuration. Sorry for the noise, I will close this if ok with you, but if you want any follow up info let me know.

**Comment by BenTheElder** [comment]
No problem 😅
