### ISSUE TITLE
Unable to hostpath mount /sys/fs/cgroup

### ISSUE THREAD

**Issue by ajwock** [kubernetes-sigs/kind#2353]
**What happened**:
My kind-cluster-configuration.yaml:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: /sys/fs/cgroup
    containerPath: /sys/fs/cgroup

```
When I ran
`kind create cluster --name <name> --config /path/to/that/config/i/wrote/above.yaml`
I got this error output:
Creating cluster "<name>" ...
 • Ensuring node image (kindest/node:v1.20.2) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼
 • Preparing nodes 📦 📦 📦 📦   ...
 ✓ Preparing nodes 📦 📦 📦 📦
 • Writing configuration 📜  ...
 ✗ Writing configuration 📜
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged <name>-worker cat /kind/version" failed with error: exit status 1

**What you expected to happen**:
I expected to have the cgroups hierarchy mounted onto my kind node's container.  I'm able to do this with other docker containers.  Though, anyone who would have a reason to mount the cgroups hierarchy onto a docker container understands how doing this might be problematic for kubernetes and virtually anything related to kubernetes, so I understand if it isn't practical to fix this.

**How to reproduce it (as minimally and precisely as possible)**:
Simply use the yaml I wrote above, and then create a cluster using that yaml.  

**Anything else we need to know?**:
Mounting the cgroups hierarchy elsewhere works i.e.

```
  extraMounts:
  - hostPath: /sys/fs/cgroup
    containerPath: /whatever/path/
```

Mounting _anything_ over the /sys/, /sys/fs/, or /sys/fs/cgroup hierarhcy causes the same error i.e.

```
  extraMounts:
  - hostPath: /whatever/path
    containerPath: /sys
```

Mounting to children of /sys/fs/cgroup causes no error:

```
  extraMounts:
  - hostPath: /whatever/path # Also, /sys/fs/cgroup works here
    containerPath: /sys/fs/cgroup/someother/path
```

**Environment:**
Fedora 33, using cgroups v2.

- kind version: (use `kind version`):
kind v0.10.0 go1.15.7 linux/amd64
- Kubernetes version: (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Docker version: (use `docker info`):

Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 42
Server Version: 20.10.5
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
init version: de40ad0
Security Options:
 seccomp
  Profile: default
 cgroupns
Kernel Version: 5.8.15-301.fc33.x86_64
Operating System: Fedora 33 (Server Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.63GiB
Name: <Redacted>
ID: <Redacted>
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

- OS (e.g. from `/etc/os-release`):

NAME=Fedora
VERSION="33 (Server Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Server Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server

**Comment by BenTheElder** [comment]
What exactly is your end-goal here? 

KIND is already managing the cgroups heirarchy (see the node entryoint). They're mounted or else kind wouldn't work, but they're not bind mounted like this.

Your applications almost certainly should not be touching or depending on paths like this, not only is it not portable in Kubernetes but it's not safe in kind because you share one kernel with the host.

This is also not what extraMounts is intended for -- they're meant to bind mount some files for consumption via a test pod with hostPath. Overriding system locations is "you break it you bought it" 🙃

**Comment by BenTheElder** [comment]
That error is symptomatic of the node container exiting early (should stay running).

**Comment by ajwock** [comment]
I have already identified a workaround for my own purposes, but I meant to report this because it seemed like unexpected behavior.  This can be closed if you think it won't be relevant to anyone else.

**Comment by BenTheElder** [comment]
Understood, I don't think this is intended to be supported, or more generally mounting over critical system paths is likely to cause issues and not recommended.
