### ISSUE TITLE
Deprecation notice: Netlify builds using the Trusty build image will fail after September 19

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#2362]
Email from Netlify as below:

---

Deprecation notice: Netlify builds using the Trusty build image will fail after September 19

The Netlify build system maintains multiple build images, which set the environment in which your sites build. One or more of your sites is using the “Trusty” image, built on Ubuntu 14.04 (“Trusty Tahr”). The Trusty image moved into legacy support in 2019, after Ubuntu 14.04 reached end of life.

On September 19, 2021, we will end all support for the Netlify Trusty image. We have identified the following impacted sites belonging to your team, Kubernetes Docs:

k8s-kind
kubectl-docs

Select a site name above to access specific site settings in the Netlify UI where you can change the site’s build image. For more information about changes between images, how to run a test build, and how to troubleshoot issues with upgrading, please visit the Trusty build image migration guide in the Netlify Support Forums.

As always, we’re here to help! If you have any questions, feel free to reply to this email directly.

---

We should fix this with in-repo config if possible. If not we need to look at getting more of the maintainers onto the Netlify team via sig-docs. I'm only semi-available currently.

**Comment by BenTheElder** [comment]
I don't see a way to do this in-repo, asking in #sig-docs-tools.

https://docs.netlify.com/configure-builds/file-based-configuration/

**Comment by sftim** [comment]
SIG Docs can help with making the change in the Netlify configuration GUI. I don't think there's an API for making that update.

**Comment by BenTheElder** [comment]
Thanks @sftim. I believe I personally have access to the kind project (and only that one), but not @amwat @aojea @munnerz, should we look to SIG docs for this in the future as well or should we add the other @kubernetes-sigs/kind-maintainers?

I'm not sure what the pattern is, I'm pretty sure I only have access from the original ~"sorting out how we can doc-site things that aren't official enough for kubernetes.io", do you know what we've done with other repos or if they also have this problem coming up?

**Comment by stmcginnis** [comment]
Can this be closed now? It's past the deadline, and it looks like we still have docs, so I'm assuming this was fixed?

**Comment by BenTheElder** [comment]
we are on `Ubuntu Focal 20.04 (default)` (just checked)
