### ISSUE TITLE
kindest/node image for v1.22.x

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/kind#2369]
K8s 1.22 is removing support for various api versions. I wonder if it will be possible to release a version of 1.22 rc node image to test things. Thanks!

**Comment by BenTheElder** [comment]
The docs cover building one yourself, I don't really want to keep doing one-offs without a plan to automate or similar (which Kubernetes makes a pain for ourselves ... https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io) and a plan as to how to ensure users or the kind binary understand compatibility between versions.

Right now we tell people to use the images published in the release notes or build their own with the matching binary they plan to use.

We have a few other issues discussing this problem space.

**Comment by tamalsaha** [comment]
Understood. Thanks! May be at some point having kind images as part of k8s release will be really great for all of us trying/testing those releases ahead of time.

**Comment by BenTheElder** [comment]
I agree, but last time this came up I think SIG release was hesitant to have N cluster projects tacking onto the release system (e.g. also cluster-API etc.), these are mostly social problems I think, but those are the hardest 🙃

**Comment by tamalsaha** [comment]
Agree on social problems. I think k8s should have an official answer to how users can realistically try these rc releases. I think KIND and Minikube fits that role nicely. Especially Kind, since Kind is used to k8s itself ( or so I thought).
