### ISSUE TITLE
optimize the node name with multi workers deployed

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kind#2370]
**What would you like to be added**:
when I deployed multi workers, the No.1 woker should named `kind-worker1` be default, but now is `kind-worker`.

**Why is this needed**:
elegantly and clearly. 

If accepted, I will work on this. Thansk.

**Comment by kerthcet** [comment]
What's more, should I add `worker` role to the workers node?

**Comment by BenTheElder** [comment]
We are not going to change the node naming, external scripts depend on the existing naming pattern.

Node-role as a kubernetes level label is a kubeadm concept that is only used to pin the control plane components to those nodes.

**Comment by neolit123** [comment]
>> What's more, should I add worker role to the workers node?

> Node-role as a kubernetes level label is a kubeadm concept that is only used to pin the control plane components to those nodes.

this has come up in multiple discussions in the past. a node is a worker only if the user wants it to be a worker. it can be reserved for operators only and not for workloads. this makes it difficult to assume node-roles labels to anything but the control plane nodes. users can use their admin credentials to apply node-role labels after the cluster creation.

**Comment by kerthcet** [comment]
> > > What's more, should I add worker role to the workers node?
> 
> > Node-role as a kubernetes level label is a kubeadm concept that is only used to pin the control plane components to those nodes.
> 
> this has come up in multiple discussions in the past. a node is a worke,r only if the user wants it to be a worker. it can be reserved for operators only and not for workloads. this makes it difficult to assume node-roles labels for anything but the control plane nodes. users can use their admin credentials to apply node-role labels after the cluster creation.

Got it.

**Comment by BenTheElder** [comment]
you can use `labels` field in node config to set custom labels in kind

for it to be by default some new label we should consider https://github.com/kubernetes/kubeadm first, ideally we want kind to look like standard kubernetes and there's no standard for labeling registered dedicated control plane machines vs other nodes.

**Comment by kerthcet** [comment]
> We are not going to change the node naming, external scripts depend on the existing naming pattern.
> 
> Node-role as a kubernetes level label is a kubeadm concept that is only used to pin the control plane components to those nodes.

ok, just a pop-up idea. keep following the evoluation.
