### ISSUE TITLE
I was trying to create a pvc with RWX access mode in the kind cluster. I see an error that it is not supported.

### ISSUE THREAD

**Issue by HariHaraReddyD** [kubernetes-sigs/kind#2371]
I was using kind cluster to create resources. As part of that I was creating a pvc with RWX access mode. I see the kind cluster comes with standard storage class as below-
```
NAME                     PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
standard (default)   rancher.io/local-path   Delete                   WaitForFirstConsumer         false                                         12h
```

It looks like the default storage class not allow to create pvc with Read Write Many access mode. Whereas the default storage class in minikube cluster environment allow us to create pvc with RWX mode.
Below error seen in pvc - 
` rancher.io/local-path_local-path-provisioner-bd4bb6b75-sbf49_ccebea37-56a9-405c-b76b-3cd0e113fb23  failed to provision volume with StorageClass "standard": Only support ReadWriteOnce access mode`

Can someone please let me know if something is missing or is it a known issue?

- kind version: (use `kind version`): kind v0.8.1 go1.14.2 linux/amd64
- Kubernetes version: (use `kubectl version`): 1.19
- Docker version: (use `docker info`): 19.03.11
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4

**Comment by xinydev** [comment]
I think this is a limitation of  rancher.io/local-path ,https://github.com/rancher/local-path-provisioner/issues/70

**Comment by BenTheElder** [comment]
Unlike minikube we need to support multi-node clusters. We use the driver above.

*Most* clusters do not have readwritemany out of the box. If you're not doing a special cased single node cluster where you can just bind mount a folder to all the pods you need some synchronized network attached storage like NFS. See https://github.com/kubernetes-sigs/kind/issues/1487

/remove-kind bug
/kind feeature
/triage duplicate
https://github.com/kubernetes-sigs/kind/issues/1487
