### ISSUE TITLE
Failed to load two docker images into kind cluster at once

### ISSUE THREAD

**Issue by JimmyYang20** [kubernetes-sigs/kind#2377]
**What happened**:
When I want to load two docker images into kind cluster at once,  result is that only find the first in cluster.
![image](https://user-images.githubusercontent.com/25048074/126251915-e1f0d154-3fb7-4bbb-ad57-2b45c3473822.png)
![image](https://user-images.githubusercontent.com/25048074/126249358-b0dce845-26d6-4d3a-b416-35827d635f23.png)
![image](https://user-images.githubusercontent.com/25048074/126249029-124a052a-0d44-4ad9-a282-6abddf9f5151.png)
![image](https://user-images.githubusercontent.com/25048074/126249099-ec9e6049-45e1-4014-8e64-6f0e3aa9849a.png)

**Environment:**

![image](https://user-images.githubusercontent.com/25048074/126249599-3b1a5131-05c0-4e98-acde-0c54aae44aab.png)

- Docker version: (use `docker info`): 20.10.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.5

**Comment by BenTheElder** [comment]
what was the resolution to this? it looks like the same image was requested twice in the same command and it was successfully loaded?

**Comment by JimmyYang20** [comment]
@BenTheElder  the different docker images.   I find kind(v0.10) does not support, but kind(v0.12) can do it.

**Comment by BenTheElder** [comment]
this features is in v0.11.0+ https://github.com/kubernetes-sigs/kind/pull/1920/commits/d3327a3296cc9ec1b1d7799a0ad07c9c3834a6f5
