### ISSUE TITLE
Cluster is not getting deleted, how to fix that?

### ISSUE THREAD

**Issue by ukreddy-erwin** [kubernetes-sigs/kind#2381]
I am trying to delete kind cluster using.

`kind delete cluster --name samples`
And I got error after waiting for 15 min.

```
Deleting cluster "samples" ...
ERROR: failed to delete cluster "samples": failed to delete nodes: command "docker rm -f -v samples-control-plane" failed with error: exit status 1
Command Output: Error response from daemon: removal of container samples-control-plane is already in progress

```
But this is the only command I ran to delete, not before.

So tried to delete the container of kind cluster using.

`docker ps`

```
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS          PORTS
  NAMES
5d0fa7222662   postgres:latest        "docker-entrypoint.s…"   51 minutes ago   Up 51 minutes   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   postgres_database
e6acb3781680   kindest/node:v1.21.1   "/usr/local/bin/entr…"   33 hours ago     Up 2 hours      127.0.0.1:44151->6443/tcp
  samples-control-plane
```
And tried deleting stopping it first.

`docker stop e6`
But stuck there for almost an hour but no response till now.

So I pressed ctrl+c and ran the command with -t.

`docker stop e6 -t 2`
Same result, stuck there and kept for 3 hours and more, but still there only. How to delete this?

**Comment by BenTheElder** [comment]
This sounds like a docker bug?

`kind delete cluster --name=foo` does:
1. list nodes for cluster name foo
2. deletes them with `docker rm -f`
3. cleans up the KUBECONFIG entry or entries for the cluster.

If delete is hanging on docker's end, there's not much kind can do ...

**Comment by BenTheElder** [comment]
We're going to need to know more, this is not something I've seen. Please fill out the complete bug template in the future.

**Comment by BenTheElder** [comment]
Will reopen if we get more information.
