### ISSUE TITLE
Request for ability to control memory/cpu resource allocated to nodes

### ISSUE THREAD

**Issue by zephinzer** [kubernetes-sigs/kind#2395]
**What would you like to be added**: Ability to specify memory/cpu values for each node

**Why is this needed**: Having this would enable localised testing of workload behaviour mimicing a real cluster's resources (example question that can be answered: does OOM happen given we are using 120% memory based on limits but 80% based on requests?)

Haven't dug into how `kind` works so I'm not too sure how complex this will be but the Docker daemon [seems to allow for specifying of resources](https://docs.docker.com/config/containers/resource_constraints/) so it could be adding configuration during this step?

If it's in line with `kind`'s roadmap, I can help with this-

**Comment by zephinzer** [comment]
Just found https://github.com/kubernetes-sigs/kind/issues/877, which seems to be a duplicate, feel free to close-

**Comment by BenTheElder** [comment]
This is unfortunately trickier than you might hope to do correctly at the moment and not something I personally can justify focusing on at the moment. If someone proposes a workable plan in #877 I will do my best to help see it through. I think most/all? of the kind maintainers are currently burning all cycles maintaining the project and doing their "real" work on other projects 😅
