### ISSUE TITLE
A CLI command that generates a default kind.x-k8s.io/v1alpha4 Cluster configuration

### ISSUE THREAD

**Issue by Drumato** [kubernetes-sigs/kind#2396]
**What would you like to be added**:

I would like to add a CLI command that print [a default configuration](https://github.com/kubernetes-sigs/kind/blob/bd72cac34efc6e4c91a0ea989a5d490054c735d8/pkg/apis/config/v1alpha4/default.go#L24) to stdout or write it to a specified file.
An example usage is below.

```shell
$ kind create default-config -f <filename> # or kind print default-config
==> print out
```

**Why is this needed**:

kind configuration is so detailed and flexible but it's not easy to use for beginners.
I know the kind documentation is so "kind" and is good at start to use kind.
But when I create a kind cluster with `kind create cluster` I can't see what configuration is applied.
Beginners may need a CLI command that annotates a brief description about `--config` flag and each configuration field.

There is a verbose flag but the flag is so complicated and the output only describes about kubeadm/kubelet/kube-proxy configuration.

Please comment about the necessity of this feature.

**Comment by neolit123** [comment]
IIRC kubeadm added such a command (kubeadm config print...) since users
requested it. It can be a bit problematic since it only applies static
defaulting and the values that need dynamic defaulting can trip users e.g.
host name -> node name uses 'node' always. Kind can always fully default
thought.

Overall i think i am +1 on such a feature.

**Comment by BenTheElder** [comment]
The default config is an empty config upon which defaulting is applied. The defaulting is dynamic.

**Comment by BenTheElder** [comment]
Documentation is maintained at https://kind.sigs.k8s.io/docs/user/configuration/

**Comment by Drumato** [comment]
@BenTheElder 
[kubeadm supports](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/) such a command as `kubeadm config print`.
I think It's pretty useful interface.

I found a defaulting process [here](https://github.com/kubernetes-sigs/kind/blob/bd72cac34efc6e4c91a0ea989a5d490054c735d8/pkg/apis/config/v1alpha4/default.go#L24).
It appears a static defaulting and maybe I can print it to stdout.
Is the `SetsDefaultsCluster` func used yet?

**Comment by BenTheElder** [comment]
> I think It's pretty useful interface.

What is the usage though? Patching? We have interdependent fields so if you're doing that you should probably import the actual API types to generate your config or just set the fields you intended and allow the rest to be defaulted.

`import "sigs.k8s.io/kind/pkg/apis/config/v1alpha4"` 
https://github.com/kubernetes-sigs/kind/blob/main/pkg/apis/config/v1alpha4/types.go

> It appears a static defaulting 

No, the static default is literally an empty config: https://github.com/kubernetes-sigs/kind/blob/bd72cac34efc6e4c91a0ea989a5d490054c735d8/pkg/internal/apis/config/encoding/load.go#L39

Upon which the dynamic defaulting is applied (which would also be applied to any partial config and depend on the fields that are set).

> Is the SetsDefaultsCluster func used yet?

Yes.

https://github.com/kubernetes-sigs/kind/blob/bd72cac34efc6e4c91a0ea989a5d490054c735d8/pkg/internal/apis/config/encoding/load.go#L40

https://github.com/kubernetes-sigs/kind/blob/31d33511ae0a86f04e5bd475acc422407349122c/pkg/cluster/internal/create/create.go#L238

https://github.com/kubernetes-sigs/kind/search?q=SetDefaultsCluster

**Comment by BenTheElder** [comment]
The default is equivalent to the following on-disk config:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
```
\+ `SetDefaultsCluster` (which will be applied to any input config, has logic that depends on what partial config settings are input)

**Comment by Drumato** [comment]
Thanks for supplying these information.
I've understood the defaulting mechanism right now.

I prefered we can configure by using printer If a user already understands how to use each configuration field by reading the docs.

Is it possible to generate a YAML template such as below?

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# the cluster name
# name: ExampleCluster

# you can enabe kube-apiserver feature gates by using FeatureGates.
# featureGates:
#   "CSIMigration": true
```

**Comment by Drumato** [comment]
It's my first time for contributing to kind so please comment to me if I was wrong.

**Comment by BenTheElder** [comment]
> I think we can configure by using printer If a user already understands how to use each configuration field by reading the docs.

If the user knows how to use configuration fields they probably read the docs? 🤔 

> Is it possible to generate a YAML template such as below?

The sample given here appears to be attempting to document all possible fields via yaml comments?

I would prefer not to duplicate the effort at https://kind.sigs.k8s.io/docs/user/configuration/ into the sources regarding documenting all fields, we have better formatted and more detailed guides in a structured order there. 

Alternatively the types themselves can be read for any we've not yet written up (see in the docs: "The structure of the Cluster type is defined by a Go struct, which is described here."), but if we're going to write them up I'd prefer it be in the docs than in a CLI printed comment. This also gives us room to give real examples of using fields and discuss them.

This is in line with most Kubernetes components / tools.

**Comment by Drumato** [comment]
> I would prefer not to duplicate the effort at https://kind.sigs.k8s.io/docs/user/configuration/ into the sources regarding documenting all fields, we have better formatted and more detailed guides in a structured order there.

I perfectly understood the idea what you thought, thanks!
I agree the whole idea.

How do you think the way to generate a template by Go generate or something?
It enables us to generate from the latest definition of Go struct and no update cost of the template.

**Comment by Drumato** [comment]
If the above idea is mismatch on this feature, I confirmed the difficulty of this features feasibility.
so feel free to close! thank you for conversation!
