### ISSUE TITLE
Need to access services on mac localhost 

### ISSUE THREAD

**Issue by andycwk** [kubernetes-sigs/kind#2405]
Hi!

Not sure if this is possible or not but I would like to spin up some services locally on my mac that can be reached by pods within a Kind cluster.

Is this possible? How would I go about it?

At the moment, the only way I can think of doing it is via something like ngrok but that feels like overkill and not a scalable solution to allow other devs to develop on their local devices within the project team.

Cheers!

**Comment by BenTheElder** [comment]
`host.docker.internal` is provided by docker in the mac app.

see also: https://github.com/kubernetes-sigs/kind/issues/1200

**Comment by andycwk** [comment]
Nice one, thanks @BenTheElder I'll experiment with that and see how it goes - but sounds like it's just what the doctor ordered :)

**Comment by andycwk** [comment]
Hay, just reporting back.. that worked like a charm thanks :)
