### ISSUE TITLE
regression in performance of kind load docker-image if all images are already present

### ISSUE THREAD

**Issue by Alfa-Alex** [kubernetes-sigs/kind#2413]
**What would you like to be added**:
Currently, when you run `kind load docker-image` and all images are already present on all nodes, `kind` takes 2.5 secs on my machine to return after printing `Image: ... with ID "..." found to be already present on all nodes.`

Looking into the code, I found that the reason for this is simple: 
The code in ll. 144-155 in [docker-image.go](https://github.com/kubernetes-sigs/kind/blob/c78bd3f581a1da72f514c3c6f8ef59f530d13b7d/pkg/cmd/kind/load/docker-image/docker-image.go#L144) is run even if `len(selectedNodes)` is zero.

**Why is this needed**:
In my use case, I load a lot of images via a script by individual `kind load docker-image` invocations (each with exactly one image). Some of these images are already available on the desired node. But currently loading those images slows down the whole process because the above-mentioned part of code (that doesn't have any notable effect for the already-present images) takes 2.5 secs on my machine per `kind load` (I benchmarked this).

My suggestion is to add a simple:
```go
	if len(selectedNodes) == 0 {
		return nil
	}
```
after the loop ending at Line 142. I tested this locally and it allowed me to save the 2.5 seconds.

**Comment by BenTheElder** [comment]
Thanks, this is probably a regression from when support for multiple images was addes, please do send a PR.

**Comment by Alfa-Alex** [comment]
Thanks for the fast response! Closing this because #2414 is merged.
