### ISSUE TITLE
Cannot load docker image into kind when images are pulled by podman

### ISSUE THREAD

**Issue by morningspace** [kubernetes-sigs/kind#2417]
**What happened**:
I am using podman on a RHEL system where I can use podman to pull images to the local machine. e.g.:
```console
# podman images
REPOSITORY                                    TAG     IMAGE ID      CREATED        SIZE
docker.io/library/kong                        2.4     b022e820b9b2  3 months ago   148 MB
docker.io/kong/kong-operator                  v0.8.0  bdeba0cd3d02  3 months ago   216 MB
docker.io/kong/kubernetes-ingress-controller  1.2     a2f5ee07c4ac  4 months ago   80.6 MB
docker.io/kindest/node                        <none>  37ddbc9063d2  11 months ago  1.33 GB
```

However, when I run `kind load docker-image` to load local images to kind, it is always failed, e.g.:
```console
# kind load docker-image library/kong --name=test
enabling experimental podman provider
ERROR: image: "library/kong" not present locally
# kind load docker-image docker.io/library/kong --name=test
enabling experimental podman provider
ERROR: image: "docker.io/library/kong" not present locally
# kind load docker-image docker.io/library/kong:latest --name=test
enabling experimental podman provider
ERROR: image: "docker.io/library/kong:latest" not present locally
# kind load docker-image library/kong:latest --name=test
enabling experimental podman provider
ERROR: image: "library/kong:latest" not present locally
```

**What you expected to happen**:
Images pulled by podman should be able to be loaded into kind

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:
N/A

**Environment:**

- kind version: (use `kind version`): kind-v0.9.0
- Kubernetes version: (use `kubectl version`): 1.19.1
- Docker version: (use `docker info`): N/A
- OS (e.g. from `/etc/os-release`): RHEL 8.4

**Comment by BenTheElder** [comment]
kind load docker-image is docker specific on the image loading side by design (consider images built for kubernetes with buildx because it is required but otherwise testing podman) and predates podman. There's open issues discussing introducing an alternative command or altering this behavior.

Currently you can use `podman save | kind load image-archive`

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/2038
