### ISSUE TITLE
Completely insecure mode

### ISSUE THREAD

**Issue by julienlau** [kubernetes-sigs/kind#2420]
**What would you like to be added**:
It would be nice to have a completely insecure setup in order to be able to more easily perform :
- curl http request to APISERVER
- etcdctl browsing 

**Why is this needed**:
Help understanding kubernetes internal architecture.
I was looking for a list of lease and watch used in etcd for a basic worker control and for a pod control

Thanks to all people helping to provide this tool.

**Comment by BenTheElder** [comment]
I don't think kubeadm is likely to support this and I suspect would be painful to do without that. The whole stack is built around certs.

You can curl APIserver without an insecure mode, kubectl proxy is a pretty easy option https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#using-kubectl-proxy, there are also more options documented there.

ecdctl is also rather doable without a special more insecure mode, basically you just need to assume the kubeadm cert paths on the control plane node https://mauilion.dev/posts/etcdclient/

**Comment by julienlau** [comment]
Thanks for the tips, yes I understood afterwards that Kubernetes itself is difficult to install in insecure mode.
