### ISSUE TITLE
NGINX ingress controller v1.0.0 breaks Kind's ingress documentation

### ISSUE THREAD

**Issue by andreasjansson** [kubernetes-sigs/kind#2433]
**What happened**:

* I followed the ingress guide on https://kind.sigs.k8s.io/docs/user/ingress, using the NGINX ingress
* `curl localhost/foo` returned HTTP 404

**What you expected to happen**:

`curl localhost/foo` should output "foo"

**How to reproduce it (as minimally and precisely as possible)**:

Follow the instructions on https://kind.sigs.k8s.io/docs/user/ingress, using the NGINX ingress.

**Anything else we need to know?**:

Downgrading ingress-nginx to 0.49.0 fixes the issue, i.e. replace
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
```
with
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.49.0/deploy/static/provider/kind/deploy.yaml
```

**Environment:**

- kind version: (use `kind version`): kind v0.11.0 go1.16.2 darwin/arm64
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-18T01:15:06Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
```
- Docker version: (use `docker info`): 20.10.8
- OS (e.g. from `/etc/os-release`): OSX 11.1 (Apple M1)

**Comment by rikatz** [comment]
/assign
I'm on it, will look today

**Comment by mattj-io** [comment]
Downgrading fixed for me

**Comment by alfonsomunozpomer** [comment]
I can confirm that this issue exists also on Linux (Pop!_OS 21.04) with Kind v0.11.1 and Docker v20.10.7. As others have noted, downgrading to ingress-nginx v0.49.0 fixed it.

**Comment by wfxr** [comment]
Confirm downgrading to 0.49.0 works.

**Comment by rikatz** [comment]
Will try to verify what's going on

**Comment by rikatz** [comment]
OK, found the issue. Let me explain here what happens for future users:

Ingress NGINX now needs Ingress Class to run. This was a definition of the new ingress/v1 api specification. A good explanation is right [here](https://kubernetes.github.io/ingress-nginx/#what-is-an-ingressclass-and-why-is-it-important-for-users-of-ingress-nginx-controller-now) but tl;dr, you need to tell ingress controller either to parse ingress objects without class (passing a flag --watch-ingress-without-class) or adding the field `ingressClassName: nginx` in case of KinD example.

As the example is more generic than ingress-nginx, I will propose to other contribs in Ingress NGINX to change the kind deployment manifest to add --watch-ingress-without-class

In you all specific case, if you want to test ingress nginx v1.0.0 (and we thank you for that!) without waiting the release of the new manifest file, please be sure to follow the following steps:

* kubectl edit deploy -n ingress-nginx ingress-nginx-controller
* In .container.args configs, add `- --watch-ingress-without-class`

Thanks!

**Comment by rikatz** [comment]
Please try again with the new manifests :)

Thanks!

**Comment by wfxr** [comment]
@rikatz Now it works fine. Thank you!
