### ISSUE TITLE
How do I mount the TMP directory of the host to the K8S cluster

### ISSUE THREAD

**Issue by anban-wuxi** [kubernetes-sigs/kind#2437]
root@anban-virtual-machine:~# kind create cluster --config kind-conf.yaml --name kind
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✗ Preparing nodes 📦 📦  
ERROR: failed to create cluster: docker run error: command "docker run --hostname kind-worker --name kind-worker --label io.x-k8s.kind.role=worker --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --net kind --restart=on-failure:1 --init=false --volume=/tmp:/tmp kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6" failed with error: exit status 125
Command Output: docker: Error response from daemon: Duplicate mount point: /tmp.

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "192.168.50.102"
  apiServerPort: 6443
nodes:
- role: control-plane
- role: worker
  extraMounts:   #共享主机文件系统
  - hostPath: /tmp 
    containerPath: /tmp

**Comment by BenTheElder** [comment]
I'm not sure what you're trying to accomplish here but you'll have to mount it somewhere else. In general mounting over system paths is a bound to cause problems.
