### ISSUE TITLE
KIND: no such host when lookup ovn-control-plane

### ISSUE THREAD

**Issue by lxin** [kubernetes-sigs/kind#2454]
When I was deploying ovn-k8s by kind.sh, it showed that, ovn-worker and ovn-worker2 couldn't get the IP of 'ovn-control-plane' from DNS servers (DNS servers seem copied from hosts), see the details below:

"""

./kind.sh -ep podman
WARNING: Running pip install with root privileges is generally not a good idea. Try pip install --user instead.
Requirement already satisfied: wheel in /root/.local/lib/python2.7/site-packages
j2cli==0.3.10
Using these parameters to install KIND

KIND_INSTALL_INGRESS = false
OVN_HA = false
KIND_CONFIG_FILE = ./kind.yaml.j2
KIND_REMOVE_TAINT = true
KIND_IPV4_SUPPORT = true
KIND_IPV6_SUPPORT = false
KIND_NUM_WORKER = 2
KIND_ALLOW_SYSTEM_WRITES = false
KIND_EXPERIMENTAL_PROVIDER = podman
OVN_GATEWAY_MODE = shared
OVN_HYBRID_OVERLAY_ENABLE = false
OVN_DISABLE_SNAT_MULTIPLE_GWS = false
OVN_DISABLE_PKT_MTU_CHECK = false
OVN_NETFLOW_TARGETS =
OVN_SFLOW_TARGETS =
OVN_IPFIX_TARGETS =
OVN_EMPTY_LB_EVENTS = false
OVN_MULTICAST_ENABLE = false
OVN_IMAGE = local
MASTER_LOG_LEVEL = 5
NODE_LOG_LEVEL = 5
DBCHECKER_LOG_LEVEL = 5
OVN_LOG_LEVEL_NORTHD = -vconsole:info -vfile:info
OVN_LOG_LEVEL_NB = -vconsole:info -vfile:info
OVN_LOG_LEVEL_SB = -vconsole:info -vfile:info
OVN_LOG_LEVEL_CONTROLLER = -vconsole:info
OVN_LOG_LEVEL_NBCTLD = -vconsole:info
OVN_HOST_NETWORK_NAMESPACE = ovn-host-network
OVN_ENABLE_EX_GW_NETWORK_BRIDGE = false
OVN_EX_GW_NETWORK_INTERFACE =

detect_apiserver_ip
++ ip -4 addr
++ grep -oP '(?<=inet\s)\d+(.\d+){3}'
++ grep -v 127.0.0.1
++ head -n 1
API_IP=10.19.188.5
'[' -z 10.19.188.5 ']'
check_ipv6
'[' false == true ']'
set_cluster_cidr_ip_families
'[' true == true ']'
'[' false == false ']'
IP_FAMILY=
NET_CIDR=10.244.0.0/16
SVC_CIDR=10.96.0.0/16
echo 'IPv4 Only Support: API_IP=10.19.188.5 --net-cidr=10.244.0.0/16 --svc-cidr=10.96.0.0/16'
IPv4 Only Support: API_IP=10.19.188.5 --net-cidr=10.244.0.0/16 --svc-cidr=10.96.0.0/16
create_kind_cluster
KIND_CONFIG_LCL=./kind.yaml
ovn_apiServerAddress=10.19.188.5
ovn_ip_family=
ovn_ha=false
net_cidr=10.244.0.0/16
svc_cidr=10.96.0.0/16
ovn_num_master=1
ovn_num_worker=2
cluster_log_level=4
j2 ./kind.yaml.j2 -o ./kind.yaml
kind get clusters
grep ovn
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
No kind clusters found.
kind create cluster --name ovn --kubeconfig /root/admin.conf --image kindest/node:v1.20.0 --config=./kind.yaml
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Creating cluster "ovn" ...
✓ Ensuring node image (kindest/node:v1.20.0) ð��¼
✓ Preparing nodes ð��¦ ð��¦ ð��¦
✓ Writing configuration ð���
✓ Starting control-plane ð��¹️
✓ Installing StorageClass ð��¾
✗ Joining worker nodes ð���
ERROR: failed to create cluster: failed to join node with kubeadm: command "podman exec --privileged ovn-worker kubeadm join --config /kind/kubeadm.conf --skip-phases=preflight --v=6" failed with error: exit status 1
Command Output: I0823 06:07:49.169400 1348 join.go:395] [preflight] found NodeName empty; using OS hostname as NodeName
I0823 06:07:49.169421 1348 joinconfiguration.go:74] loading configuration from "/kind/kubeadm.conf"
I0823 06:07:49.170653 1348 controlplaneprepare.go:211] [download-certs] Skipping certs download
I0823 06:07:49.170664 1348 join.go:465] [preflight] Discovering cluster-info
I0823 06:07:49.170674 1348 token.go:78] [discovery] Created cluster-info discovery client, requesting info from "ovn-control-plane:6443"
I0823 06:07:49.193225 1348 round_trippers.go:445] GET https://ovn-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s in 22 milliseconds
I0823 06:07:49.193275 1348 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://ovn-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup ovn-control-plane on 10.19.42.41:53: no such host
I0823 06:07:55.092489 1348 round_trippers.go:445] GET https://ovn-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s in 261 milliseconds
I0823 06:07:55.092540 1348 token.go:215] [discovery] Failed to request cluster-info, will try again: Get "https://ovn-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp: lookup ovn-control-plane on 10.19.42.41:53: no such host
...
(10.19.42.41:53 is the DNS server configured on the host by default)
"""

I had to make it work by adding one line below into /etc/hosts on the host before running "./kind.sh -ep podman", as /etc/hosts on the host will be copied into each node:

10.89.0.32 ovn-control-plane

The problem is I didn't really know these nodes' IPs before running the command, as the IPs are generated or assigned during these nodes' starting (at least when running ./kind.sh). So I had to put some address that I guessed according to the rules how the IPs are assigned, and it's not always right.

So I think the right thing to happen should be: In ./kind.sh, after getting the IP for one node, it should add one record with the IP address into a DNS server that all nodes will use or add it into the /etc/hosts on all nodes, not sure why this didn't happen?

Thanks!

**Comment by BenTheElder** [comment]
> So I think the right thing to happen should be: In ./kind.sh, after getting the IP for one node, it should add one record with the IP address into a DNS server that all nodes will use or add it into the /etc/hosts on all nodes, not sure why this didn't happen?

podman is responsible for doing exactly this. this sounds like a podman bug.

**Comment by BenTheElder** [comment]
re-reading, it sounds like you added your _own_ hosts to /etc/hosts with the container names.

> n ./kind.sh, after getting the IP for one node, it should add one record with the IP address into a DNS server that all nodes will use or add it into the /etc/hosts on all nodes, not sure why this didn't happen?

kind.sh is not part of the kind project, this is not a kind bug.

I don't think you should take this approach at all. this should be handled by podman as docker does or not at all. You can instead access services within kubernetes using standard in-cluster networking.

**Comment by lxin** [comment]
> re-reading, it sounds like you added your _own_ hosts to /etc/hosts with the container names.
> 
> > n ./kind.sh, after getting the IP for one node, it should add one record with the IP address into a DNS server that all nodes will use or add it into the /etc/hosts on all nodes, not sure why this didn't happen?
> 
> kind.sh is not part of the kind project, this is not a kind bug.
> 
> I don't think you should take this approach at all. this should be handled by podman as docker does or not at all. You can instead access services within kubernetes using standard in-cluster networking.
Right. It should be handled by podman.

After changing From RHEL-8 to Fedora-34, it works now. I think there must be some differences between.

Thanks.

**Comment by aojea** [comment]
this is something to report on the corresponding project

https://github.com/ovn-org/ovn-kubernetes
