### ISSUE TITLE
Mounting volumes

### ISSUE THREAD

**Issue by andy9775** [kubernetes-sigs/kind#246]
Hey All, I was trying to figure out a way to mount a volume to a pod running in a kind cluster for local development and I was curious if kind allows this? I don't see anything in the documentation or any issues raised.

**Comment by BenTheElder** [comment]
this will be a hostpath mount + #62 

we should be in good shape to add #62 now.

#118 is also semi related

**Comment by lukasheinrich** [comment]
hi @BenTheElder I haven't seen many updated on #62 but happy to hear it's close. Is there a roadmap what needs to happen for #62?

**Comment by BenTheElder** [comment]
We were just discussing in slack 🙃, this should be pretty straightforward now, I intend to open a PR for this.

**Comment by lukasheinrich** [comment]
can't wide, will this automatically enable #28 or does this need a separate PR?

**Comment by andy9775** [comment]
Is there a plan to support different types of volumes as well? e.g. NFS

Also, as soon as it's ready I'd be happy to test

**Comment by neolit123** [comment]
seems like a duplicate of #62 
we should probably fold the tickets.

**Comment by BenTheElder** [comment]
deduping with #62, even if it is _slightly_ different since #62 is originally just hostPath focused. I have a  something to PR ~tomorrow that isn't exactly targeting this specifically but will enable this.

**Comment by BenTheElder** [comment]
will update #62 to cover this
