### ISSUE TITLE
Validation: ipv6 only with ipv4 pod subnet

### ISSUE THREAD

**Issue by fedepaol** [kubernetes-sigs/kind#2468]
**What should be cleaned up or changed**:

It is currently possible to create an ipv6 only cluster specifying an ipv4 pod subnet.
I am not sure if this combination should be blocked during the validation phase, in case I can try to provide a PR. 

**Why is this needed**:

With this combination, pods won't be able to access the api server which is under a v6 address, making the cluster unusable.
I.e: 
```
kubectl -n local-path-storage logs local-path-provisioner-547f784dff-lvmss
time="2021-09-21T07:07:33Z" level=fatal msg="Error starting daemon: Cannot start Provisioner: failed to get Kubernetes server version: Get https://[fd00:10:96::1]:443/version?timeout=32s: dial tcp [fd00:10:96::1]:443: connect: network is unreachable" 
```

**Comment by fedepaol** [comment]
cc @aojea

**Comment by aojea** [comment]
I was surprised when Fede reported this but is true, I can't remember why I've added validation for dual but not for ip families :thinking:  , @BenTheElder do you remember something about this topci?


If you want to contribute to this, it should be done here

https://github.com/kubernetes-sigs/kind/blob/4910c3e221a858e68e29f9494170a38e1c4e8b80/pkg/internal/apis/config/validate.go#L54-L63

**Comment by fedepaol** [comment]
> If you want to contribute to this, it should be done here
> 
> https://github.com/kubernetes-sigs/kind/blob/4910c3e221a858e68e29f9494170a38e1c4e8b80/pkg/internal/apis/config/validate.go#L54-L63

This is removing half of the fun :P

**Comment by BenTheElder** [comment]
this makes sense to me, thanks for catching this!

**Comment by fedepaol** [comment]
> this makes sense to me, thanks for catching this!

It's really the least I can do! Without kind my life would be way more complex :-)
