### ISSUE TITLE
Installing additional provisioner supporting volume expansion

### ISSUE THREAD

**Issue by alex-arica** [kubernetes-sigs/kind#2469]
The provisioner ```rancher.io/local-path``` does not support volume expansion. 

But I need to test features locally requiring volume expansion. 

I did some research and I could not find any provisioners supporting volume expansion on the local hard disk.

I found [open-local](https://github.com/alibaba/open-local/blob/main/docs/user-guide.md) which supports volume expansion but I had to raise an issue with them as it does not seem to work with Kind nor Minikube.

Do you have any suggestion about a provisioner that I could use?

**Comment by BenTheElder** [comment]
given that it depends on LVM I don't think it's likely to work well in docker nodes.

I don't think there is currently a particularly advanced local provisioner, most clusters are depending on a cloud API or cloud-ish API provided by some other software

**Comment by alex-arica** [comment]
@BenTheElder thank you for your comment. 

I am sad that I won't be able to test features about volume expansion on my development computer. Thank you anyway.
