### ISSUE TITLE
kubectl cannot communicate with the cluster 

### ISSUE THREAD

**Issue by jasondavindev** [kubernetes-sigs/kind#2470]
**What happened**:

I'm trying to run Kind as docker-in-docker deploying kind as a docker container. The create command returns success, but when I call `kubectl cluster-info --context kind-my-cluster` returns an error.
The error message
```
Unable to connect to the server: dial tcp 172.21.0.2:6443: i/o timeout
```

**What you expected to happen**:
Calls kubectl and returns success.

**How to reproduce it (as minimally and precisely as possible)**:
Use the follow setup:
https://github.com/jasondavindev/kubernetes-in-docker
Build the docker image and runs

```bash
docker run --rm -ti --name k8s-cluster -v /var/run/docker.sock:/var/run/docker.sock k8s-in-docker bash -c "kubectl cluster-info --context kind-my-cluster"
```

**Anything else we need to know?**:
I have sufficient disk and memory.
Using version >0.7.0 I have the above error. When I use version 0.7.0 my master cluster node remains in NotReady state.

**Environment:**

- kind version: v0.11.1
- Kubernetes version: 1.20.0
- Docker version: 20.10.8
- OS: Ubuntu 20.04.3 LTS

Logs files
[kubelet.log](https://github.com/kubernetes-sigs/kind/files/7207084/kubelet.log)
[journal.log](https://github.com/kubernetes-sigs/kind/files/7207087/journal.log)
[containerd.log](https://github.com/kubernetes-sigs/kind/files/7207090/containerd.log)
[alternatives.log](https://github.com/kubernetes-sigs/kind/files/7207091/alternatives.log)

**Comment by jasondavindev** [comment]
I solved the problem setting network to `kind` -> `docker run --network=kind`. By default, kind creates the container using `kind` network.

**Comment by BenTheElder** [comment]
FWIW there are some details about the networking changes in the release notes. v0.8.0 had major breaking changes in this regard.
