### ISSUE TITLE
kubectl - Unable to ssh -L tunnelling into KinD cluster

### ISSUE THREAD

**Issue by JCzz** [kubernetes-sigs/kind#2472]
I have a KinD cluster running and I can kubectl to it from local network ip address: 

Client ~/.kube/config - a copy from server running K8s KinD cluster:
`server: https://<local ip address>:40475`

Everything works fine.

## Now I wanted to kubectl ssh tunnelling to the server over Internet.

Note: domain >> external ip address >> proxy port mapping >> local ip address

kind create cluster --config=:
```
apiServerAddress: "<local ip address>"
```

1. Client:  ~/.kube/config - a copy from server running K8s KinD cluster:
`server: https://kubernetes:40475`

2. Client: vi /etc/hosts:
`127.0.0.1 kubernetes`

3. ssh
`ssh -i ~/.ssh/ubuntu_server -L 40475:<domain.com>:40475 <user>@<domain.com>`
 

But it hangs and no connection or error?

**Comment by JCzz** [comment]
> -y is not a valid flag 🤔

Ahh right, thanks changed the question to `kind create cluster --config=:` - don't know what I was thinking :-) Hope you got the point that it is a configuration.

I will try to tunnel into the container instead of the server running KinD.

**Comment by JCzz** [comment]
Hmm, not sure still how to do this. I can see docker exposes the port, so it should work thunneling to the host righ ?
```

docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED      STATUS          PORTS                                                                          NAMES
2b3201fd8aab   kindest/node:v1.21.1   "/usr/local/bin/entr…"   7 days ago   Up 17 minutes   <local ip address>:40475->6443/tcp, 0.0.0.0:80->31080/tcp, 0.0.0.0:443->31443/tcp   kind-control-plane
```

**Comment by BenTheElder** [comment]
> Hmm, not sure still how to do this. I can see docker exposes the port, so it should work thunneling to the host righ ?

yes, just run an SSH port forward to the host running kind, you can use the same port on both ends and use the host config from when you ran `kind create cluster` copied from the remote host to your local host.

or run kubectl remotely over an ssh terminal, kind is optimized for local clusters.

**Comment by BenTheElder** [comment]
1. kind create cluster (no config necessary)
2. get the port (from the kubeconfig `server` field, or from docker ...)
3. copy KUBECONFIG from the remote host to the local host (default ~/.kube/config if you didn't specify)
4. run ssh tunnel on the port for 127.0.0.1
5. use kubectl normally. it will talk to the ssh tunnel on the same IP and port (127.0.0.1:port)

**Comment by JCzz** [comment]
Thanks

Exactly, that is was also what I did, the thing is I am not using 127.0.0.1 - don't know if that that is causing the issue. 

> Client ~/.kube/config - a copy from server running K8s KinD cluster:
`server: https://<local ip address>:40475`

**Comment by BenTheElder** [comment]
> Exactly, that is was also what I did, the thing is I am not using 127.0.0.1 - don't know if that that is causing the issue.

Yes, the issue is the certs for the cluster are only signed for known addresses by kubeadm, so the api server needs to see traffic intended for one of them. It is easiest to align 127.0.0.1, your cluster will be available locally, and you can remotely access it by setting up an ssh tunnel on the same "local" address.

**Comment by JCzz** [comment]
Thanks @BenTheElder 

Hmm but I need the cluster to be set to <local ip adderss> for it to map to the host - for it to work with domain names.

Do you know if it is just as safe to create users manually sing [openss]?(https://docs.bitnami.com/tutorials/configure-rbac-in-your-kubernetes-cluster/)l: 
`openssl req -new -key employee.key -out employee.csr -subj "/CN=employee/O=bitnami"`

Thanks in advance

**Comment by JCzz** [comment]
Thanks @BenTheElder 

hmm, I have to use the internal ip address in "Knative" for external domain and not 127.0.0.1.

Do you know if manually creating config files, using [X509 Client Certs](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#x509-client-certs), is just as safe as https tunnelling?

Thanks in advance

**Comment by BenTheElder** [comment]
> Do you know if manually creating config files, using X509 Client Certs, is just as safe as https tunnelling?

Safety aside, that won't work, because the issue is the server cert.

**Comment by aojea** [comment]
/close
this is now more a problem of tunneling and authentication through tunnels
