### ISSUE TITLE
unable to pull docker images from my local repository

### ISSUE THREAD

**Issue by jasondavindev** [kubernetes-sigs/kind#2474]
**What happened**:
I'm unable to pull docker images from my local repository.

I received the error

```
Failed to pull image "open-dataplatform-hadoop-hdfs": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/open-dataplatform-hadoop-hdfs:latest": failed to resolve reference "docker.io/library/open-dataplatform-hadoop-hdfs:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**What you expected to happen**:
Able to pull images

**How to reproduce it (as minimally and precisely as possible)**:
Use my setup to run the cluster https://github.com/jasondavindev/kubernetes-in-docker
Run

```bash
kind load docker-image open-dataplatform-hadoop-hdfs --name my-cluster
```
Running `crictl images` inside control-plane node container, the output

```
root@my-cluster-control-plane:/# crictl images
IMAGE                                             TAG                  IMAGE ID            SIZE
docker.io/kindest/kindnetd                        v20210729-e8b68380   3105b3ff910ef       39.8MB
docker.io/library/open-dataplatform-hadoop-hdfs   latest               68320dfa41168       1.42GB
docker.io/rancher/local-path-provisioner          v0.0.14              e422121c9c5f9       13.4MB
k8s.gcr.io/build-image/debian-base                buster-v1.7.2        19bad6b08adae       21.1MB
k8s.gcr.io/coredns/coredns                        v1.8.4               8d147537fb7d1       13.7MB
k8s.gcr.io/etcd                                   3.5.0-0              0048118155842       99.9MB
k8s.gcr.io/kube-apiserver                         v1.22.0              1852f207c5fd1       74.8MB
k8s.gcr.io/kube-controller-manager                v1.22.0              fb0e867e63326       67.5MB
k8s.gcr.io/kube-proxy                             v1.22.0              d34e62e43dded       105MB
k8s.gcr.io/kube-scheduler                         v1.22.0              282192a9c3fbb       53.9MB
k8s.gcr.io/pause                                  3.5                  ed210e3e4a5ba       301kB
```

**Environment:**

- kind version: 0.11.1
- Kubernetes version: 1.20.0
- Docker version: 20.10.8
- OS Ubuntu 20.04.3 LTS

**Comment by BenTheElder** [comment]
Judging by the content of the issue this is not actually a local registry, just an image in Docker's local storage? 

The host's docker storage is not and cannot be shared with the node runtimes. You need to use `kind load ...` or an actual local or remote registry. We have docs for this in the quick start.

**Comment by BenTheElder** [comment]
Er and see the doc notes about imagePullPolicy and the "latest" tag, which is a core Kubernetes API behavior we cannot alter.

**Comment by jasondavindev** [comment]
> Judging by the content of the issue this is not actually a local registry, just an image in Docker's local storage?
> 
> The host's docker storage is not and cannot be shared with the node runtimes. You need to use `kind load ...` or an actual local or remote registry. We have docs for this in the quick start.

Yes. Is a image from my local docker and I used `kind load` to expose to k8s cluster`s registry.

I follow the step of documentation

```
This allows a workflow like:

docker build -t my-custom-image:unique-tag ./my-image-dir
kind load docker-image my-custom-image:unique-tag
kubectl apply -f my-manifest-using-my-image:unique-tag
```

**Comment by BenTheElder** [comment]
> docker.io/library/open-dataplatform-hadoop-hdfs   latest               68320dfa41168       1.42GB

Your image is tagged (implicitly or otherwise) `:latest`, please see the docs mentioned above.

**Comment by stephanwesten** [comment]
i ran into the same problem, for those struggling:

see https://github.com/stephanwesten/ksak with documented instructions in the readme

(yes, there is room for improvements)
