### ISSUE TITLE
How to configure timezone in a kind cluster?

### ISSUE THREAD

**Issue by teone** [kubernetes-sigs/kind#2476]
**What would you like to be documented**:
How to configure the timezone when deploying a kind cluster

**Why is this needed**:
When locally deploying kind the timezone is set to UTC:
```
$ docker exec -it kind-control-plane /bin/bash
root@kind-control-plane:/# date
Fri Sep 24 19:32:24 UTC 2021
```
but the host system has a different timezone
```
$ date
Fri 24 Sep 2021 12:32:26 PM PDT
```
this makes it very difficult to compare logs from apps running on top of kind and clients running on the hosts (eg for testing).

Is it possible to set such configuration?

**Comment by aojea** [comment]
hmm , maybe we can pass an environment variable from the host?

```
$ docker exec -it kind-control-plane date
Thu Oct  7 19:03:11 UTC 2021

$ docker exec -e TZ=America/Los_Angeles -it kind-control-plane date
Thu Oct  7 19:02:15 America 2021
```

**Comment by aojea** [comment]
I'm going to close it since it doesn't seem we can do much more here
