### ISSUE TITLE
Unable to create kind cluster in Macos via Bash ,error is failed to create cluster ,read only file system.

### ISSUE THREAD

**Issue by suneethavk** [kubernetes-sigs/kind#2483]
I have tried below command:

On Macos via Bash:
curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-darwin-amd64.

Regards ,
Suneetha Konduru

**Comment by aojea** [comment]
/close
there is no answer for 23 days and it doesn't look like a kind bug,
