### ISSUE TITLE
Pop!_OS 21.04 Fails to create cluster in rootless docker with ecryptfs

### ISSUE THREAD

**Issue by AGhost-7** [kubernetes-sigs/kind#2486]
**What happened**:
`kind create cluster` fails with the following error:
```
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✗ Preparing nodes 📦
ERROR: failed to create cluster: docker run error: command "docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --net kind --restart=on-failure:1 --init=false --publish=127.0.0.1:40441:6443/TCP -e KUBECONFIG=/etc/kubernetes/admin.conf kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6" failed with error: exit status 125
Command Output: docker: Error response from daemon: failed to copy files: copy file range failed: invalid argument.
See 'docker run --help'.
```

**What you expected to happen**:
I expect it to successfully create the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Run `kind create cluster`.

**Anything else we need to know?**:
The `--volume /var` option seems to be causing the error. Removing it seems to make the `docker run` command succeed.

**Environment:**

- kind version: (use `kind version`): kind v0.11.1 go1.16.4 linux/amd64

- Kubernetes version: (use `kubectl version`): N/A
- Docker version: (use `docker info`):
```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 160
 Server Version: 20.10.9
 Storage Driver: fuse-overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.13.0-7614-generic
 Operating System: Pop!_OS 21.04
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.35GiB
 Name: pop-os
 ID: J6ED:DK4O:HONC:SRO5:VGLA:7I2J:LDHC:MIJF:WSJJ:BKFP:TYVE:OI5T
 Docker Root Dir: /home/jboudreau/.local/share/docker
 Debug Mode: false
 Username: aghost7
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```
- OS (e.g. from `/etc/os-release`):

```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**Comment by AGhost-7** [comment]
It works on Ubuntu, but for some reason is failing on Pop. As you can see, I have cgroups v2 enabled, have overlayfs working, and I did check that the modules were loaded correctly. Perhaps its something specific with Pop.

**Comment by AGhost-7** [comment]
I am getting the same error message after running the `modprobe` command. As you can see above, I am on kernel version 5.13.

**Comment by AGhost-7** [comment]
Could the issue be related to ecryptfs?

**Comment by AkihiroSuda** [comment]
Likely to be so.

**Comment by AGhost-7** [comment]
I was able to get it working with overlay2 and a bind mount to `~/.local/share/docker`. Unfortunately the image layers may contain intellectual property that my employer is going to want to protect. Would it be possible to make kind work with fuse-overlay?

**Comment by BenTheElder** [comment]
fuse overlayfs is supported within the nodes and already used in some situations.
 
I've never heard of docker on ecryptfs, and I'm not sure this is a priority for us. 
https://kind.sigs.k8s.io/docs/contributing/project-scope/

> Unfortunately the image layers may contain intellectual property that my employer is going to want to protect. 

presumably the post above has the answer to that already?

> I guess you can try creating a loopback image (ext4 or XFS) on your crypt filesystem and mount it on ~/.local/share/docker

**Comment by BenTheElder** [comment]
I think the loopback image is probably the best approach for now to run on ecryptfs.
