### ISSUE TITLE
Kind cluster seems to be unreachable after restart docker 

### ISSUE THREAD

**Issue by brolinuk** [kubernetes-sigs/kind#2507]
After restarting the docker, I still can see the cluster from command "kind get clusters"
I can use kubectl to switch to the kind cluster, but seems unable to interact to any k8s objects in it. 

This is a message I have got when I try to "kubectl get pod" after switched to kind cluster
"The connection to the server 127.0.0.1:38121 was refused - did you specify the right host or port?"

The following screenshot is the setting of the cluster with Lens, which was working before but now can not connect to the cluser and showing 502 error. 

![image](https://user-images.githubusercontent.com/13369932/137880092-35967f49-f785-4b54-8d14-778c2021cb9d.png)

Not sure what I am missing here. please advise. thanks

kind version: kind v0.11.1 go1.16.4 linux/amd64
BTW, it seems I can't delete the cluster created by kind. I still can see it using kind get clusters after kind delete cluster command

**Comment by aojea** [comment]
is a multi node cluster?
Restarting is not supported on those because of how docker network works
