### ISSUE TITLE
Trying to use kind in windows with "remote" docker in WSL2

### ISSUE THREAD

**Issue by qoricode** [kubernetes-sigs/kind#2508]
Running Ubuntu LTS 20 in WSL2 and docker works fine e.g. for `docker build` executed from WIndows.

docker version is 20.10.9 in WSL2 and 19.03.3 on the windows client.
kind version is kind v0.11.1 go1.16.4 windows/amd64 installed via choco.

The error I get when I try to start kind in windows (from cmd, ps or bash its the same):
```
$ kind create cluster --image kindest/node:v1.19.11 --verbosity 9
Creating cluster "kind" ...
DEBUG: docker/images.go:58] Image: kindest/node:v1.19.11 present locally
 ←[32m✓←[0m Ensuring node image (kindest/node:v1.19.11) 🖼
 ←[32m✓←[0m Preparing nodes 📦
 ←[31m✗←[0m Writing configuration 📜
←[31mERROR←[0m: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: file should only be one line, got 0 lines
←[31mStack Trace←[0m:
sigs.k8s.io/kind/pkg/errors.Errorf
        sigs.k8s.io/kind/pkg/errors/errors.go:41
sigs.k8s.io/kind/pkg/cluster/nodeutils.KubeVersion
        sigs.k8s.io/kind/pkg/cluster/nodeutils/util.go:40
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.getKubeadmConfig
        sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config/config.go:208
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.(*Action).Execute.func1.1
        sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config/config.go:90
sigs.k8s.io/kind/pkg/errors.UntilErrorConcurrent.func1
        sigs.k8s.io/kind/pkg/errors/concurrent.go:30
runtime.goexit
        runtime/asm_amd64.s:1371
```
I want k8s v1.19 but have tried some others with the same outcome. Don't want to use Docker Desktop because of new license terms for v4. Is there anything I can do to get more information about what is wrong?

Many thanks,

Dave

**Comment by aojea** [comment]
have you checked your system matches the requirements explained on https://kind.sigs.k8s.io/docs/user/using-wsl2/ ?

**Comment by BenTheElder** [comment]
> Thanks - as explained kind was installed to Windows using choco. I'm not running kind on WSL2. Only Docker Engine is on WSL2. Or maybe I'm missing a nuance in your suggestion.

The rest of the doc besides installing kind is still relevant and covers what is required to run kubernetes in docker on WSL2.
