### ISSUE TITLE
creating second kind cluster fails

### ISSUE THREAD

**Issue by shivchelwa** [kubernetes-sigs/kind#2509]
**What happened**:
A kind cluster is already running on my Mac. I am trying to start another kind cluster using config flile(golang packages). The below error is thrown, where I see the port 6443 is being published twice.

```
✗ Preparing nodes 📦 

2021-10-21T11:15:36.938+0530	ERROR	[MyApp service] -	docker run error: command "docker run --hostname global-1-control-plane --name global-1-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=global-1 --net kind --restart=on-failure:1 --init=false --publish=0.0.0.0:30000:30000/TCP --publish=0.0.0.0:6444:6443/TCP --publish=0.0.0.0:9080:80/TCP --publish=0.0.0.0:9443:443/TCP --publish=127.0.0.1:6444:6443/TCP -e KUBECONFIG=/etc/kubernetes/admin.conf kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6" failed with error: exit status 125
```

If I run this docker command removing the second port mapping `--publish=127.0.0.1:6444:6443/TCP`, the container comes up fine.

I am using below cluster file to provider port information.

```kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: global-1

networking:
  apiServerPort: 6444

nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
      - containerPort: 6443
        hostPort: 6444
        protocol: TCP
      - containerPort: 80
        hostPort: 9080
        protocol: TCP
      - containerPort: 443
        hostPort: 9443
        protocol: TCP
```

**What you expected to happen**:
The second cluster should have come up using apiServerPort 6444.

**How to reproduce it (as minimally and precisely as possible)**:
Create the first kind cluster using defaults and the use the second kind cluster using the config file.

**Environment:**

- kind version: (use `kind version`): kind v0.11.1 go1.16.4 darwin/amd64
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-27T23:27:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
- Docker version: (use `docker info`): Docker Desktop 4.1.1 (Engine: 20.10.8)
- OS (e.g. from `/etc/os-release`): macOS Big Sur

**Comment by aojea** [comment]
The portsmapping are unique, you can't map the same port in the host twice.
You have to different hostPorts for different clusters
