### ISSUE TITLE
Accessing Pod using root user

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [kubernetes-sigs/kind#2528]
Is it possible to access a pod using root user?

I tried using plugins, but it didn't work:  
`kubectl ssh triple-rabbit-server-0 -- bash`  
> error during connect: Get "http://docker:2375/v1.24/containers/dcf6237bfea0c1266f558dea5bd0818e130e7a548e3c524e7a7810d5e934b57b/json": dial tcp: lookup docker on 10.96.0.10:53: server misbehaving

Is there another way to access a kind cluster and get root privileges into a pod's container?

**Comment by aojea** [comment]
what is `kubectl ssh` ?

**Comment by danilobatistaqueiroz** [comment]
> what is `kubectl ssh` ?

it is a plugin for kubectl: git@github.com:luksa/kubectl-plugins.git

**Comment by aojea** [comment]
you can use kubectl exec
Or exec into a kind node, with docker exec -it kind-control-planr bash and use crictl to operate on the pods
