### ISSUE TITLE
Consider using external addons

### ISSUE THREAD

**Issue by wolfedale** [kubernetes-sigs/kind#253]
I noticed that k8s cluster created by `kind` don't have any additional addons, for example there is no ingress, nginx or default backend. Somehow I need to test my ingress (nginx/traefik) and I'm wondering if it make sense to add this kind of option to the `kind`. Of course we can leave it as it is, but then I would need to execute my `ingress` configuration files each time I will create new cluster.

Does it make sense?

**Comment by neolit123** [comment]
by allowing commands on nodes we can achieve that.
i have a proposal for that in this ticket:
https://github.com/kubernetes-sigs/kind/issues/252

**Comment by BenTheElder** [comment]
Today in SIG-cluster-lifecycle there is discussion of a potential shared addon management solution https://github.com/kubernetes/enhancements/pull/746 (currently ongoing)

I think in the meantime we can try to document and make it easier to install these things without necessarily committing to shipping one built-in yet.

I'm thinking about ways we can make this faster and easier without bundling a particular version / implementation just to avoid the project having scope explosion.

**Comment by BenTheElder** [comment]
Still keeping a close eye on the SIG Cluster Lifecycle addons work. there are regular meetings and a slack channel for this now, continuing to keep tabs on how that effort is going. I'd like to not duplicate effort there if possible.

**Comment by BenTheElder** [comment]
No major updates on this just yet, still monitoring the cluster lifecycle work.
Freezing the issue for now as we're watching how this goes in the broader project while tackling other work for now.

**Comment by dholbach** [comment]
With https://github.com/kubernetes/kubernetes/pull/85224 getting closer to the finish line, the work could potentially be exposed and used in `kind` too?

**Comment by BenTheElder** [comment]
Likely yes, also note that all kubeadm config options are available to power users via config patches, so without even properly exposing it this will be possible to experiment with 😅

**Comment by cmoulliard** [comment]
So, the feature requested by this ticket will be in fact managed by some kubernetes cluster addons = operators (https://github.com/kubernetes-sigs/cluster-addons) - correct ?

**Comment by BenTheElder** [comment]
Undecided. I'm not sure where the project is at currently, this is on our backlog along with many things.

**Comment by BenTheElder** [comment]
BTW Ingress is a trickier case (due to docker networking), documented at https://kind.sigs.k8s.io/docs/user/ingress/

**Comment by BenTheElder** [comment]
Ingress: https://kind.sigs.k8s.io/docs/user/ingress/ (pick your own, need to align some cluster configuration for networking unfortunately due to docker)
Loadbalancer: https://kind.sigs.k8s.io/docs/user/loadbalancer/ (note: perhaps not very useful on mac and windows)

I think iff https://github.com/kubernetes-sigs/cluster-addons or similar gets traction they can be used against kind without any work here. Currently cluster-addons seems rather inactive. Last commit ~6 months ago.
