### ISSUE TITLE
Cluster creation failing with error code 125 process_linux.go:402: getting the final child's pid from pipe caused: EOF: unknown

### ISSUE THREAD

**Issue by ukpbz** [kubernetes-sigs/kind#2530]
kubectl version - Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"c
lean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

docker version = 20.10.7

Kind Version = kind v0.11.1 go1.16.4 linux/amd64

I am trying to run this on a QNAP NAS Container running Ubuntu 20.04 with 6GB of memory

Any help greatly appreciated

Full Error -
 ✗ Preparing nodes 📦  
ERROR: failed to create cluster: docker run error: command "docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s
.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /
var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --net kind --restart=on-failure:1 --init=false --pu
blish=127.0.0.1:42753:6443/TCP -e KUBECONFIG=/etc/kubernetes/admin.conf kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec
3a346306239bba8cfa1a6" failed with error: exit status 125
Command Output: 740ac34ef8a208f95a1ddcc626af3c7a28ae15fd6690478bfb0567e8305a4f3e
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused
: process_linux.go:402: getting the final child's pid from pipe caused: EOF: unknown.

**Comment by BenTheElder** [comment]
> Command Output: 740ac34ef8a208f95a1ddcc626af3c7a28ae15fd6690478bfb0567e8305a4f3e
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused
: process_linux.go:402: getting the final child's pid from pipe caused: EOF: unknown.

The docker install on your host is broken such that you can't start the node container. See https://github.com/moby/moby/issues/40835 for an upstream docker issue discussing this error.

**Comment by BenTheElder** [comment]
This is a docker issue and the docker folks can hopefully help, there's nothing kind can do about this.

**Comment by jayunit100** [comment]
i find this to be intermittent, FWIW

**Comment by BenTheElder** [comment]
If you can currently reproduce and get logs, please file a current issue (instructions to get container logs in the issue template), we don't closely monitor clsoed issues and this one is pretty old and never had anything actionable.

Limactl w/ dockerd is a recommended alternative to docker desktop FWIW as a more immediate workaround.

**Comment by jayunit100** [comment]
Ya I agree should stay closed. Plenty of workarounds (lima or retry or...)
