### ISSUE TITLE
"go get" in QuickStart instructions appears to be deprecated.

### ISSUE THREAD

**Issue by eak13** [kubernetes-sigs/kind#2533]
Using the following quick start instructions located here: https://kind.sigs.k8s.io/docs/user/quick-start/

When running the "go get" command, you now get the following:
```
$ go get sigs.k8s.io/kind@v0.11.1
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

```
Realize there's other methods documented on the page but should probably updated at some point. This is running go version go1.17.3 linux/amd64.

**Comment by BenTheElder** [comment]
thanks for raising this! guide should be updated now.
