### ISSUE TITLE
Could not load docker image in ubuntu in latest kind version

### ISSUE THREAD

**Issue by rpiotrow** [kubernetes-sigs/kind#2535]
**What happened**:
```
$ kind load docker-image 'postgres:13.4' 'postgres:13.4'
Image: "postgres:13.4" with ID "sha256:113197da0347a82925486217beece0386a4de3b4aa3a34e53a20c988606ffa96" not yet present on node "kind-control-plane", loading...
Image: "postgres:13.4" with ID "sha256:113197da0347a82925486217beece0386a4de3b4aa3a34e53a20c988606ffa96" not yet present on node "kind-control-plane", loading...
ERROR: command "docker save -o /tmp/images-tar389269045/images.tar postgres:13.4 postgres:13.4" failed with error: exit status 1
Command Output: failed to save image: invalid output path: directory "/tmp/images-tar389269045" does not exist
```

**What you expected to happen**:
Kind loads docker image without any error.

**How to reproduce it (as minimally and precisely as possible)**:
```
kind create cluster
docker pull postgres:13.4
kind load docker-image 'postgres:13.4' 'postgres:13.4'
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
```
kind v0.11.1 go1.16.4 linux/amd64
```
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-29T02:41:56Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 41
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-40-generic
 Operating System: Ubuntu Core 18
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.18GiB
 Name: rpiotrow
 ID: QSFY:72B4:NSGD:MS3P:JNDC:HBSG:VLTX:OCBG:Y4MF:BALT:EMRE:UCLY
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Username: rpiotrow
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by aojea** [comment]
> kind load docker-image 'postgres:13.4' 'postgres:13.4'

why do you set the same image twice?
does `kind load docker-image 'postgres:13.4' ` fails too?

**Comment by aojea** [comment]
the problem is that the command fails if the image name are duplicated, there is a bug there, but you should pass the image name only once

**Comment by rpiotrow** [comment]
> > kind load docker-image 'postgres:13.4' 'postgres:13.4'
> 
> why do you set the same image twice? does `kind load docker-image 'postgres:13.4' ` fails too?

I was following example from the doc (https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster) thinking that the first argument is a "local" tag and the second is a "remote" tag :facepalm: (I did not read carefully docs, sorry).

Nevertheless, I see the same problem with one image:
```
$ kind load docker-image 'postgres:13.4'
Image: "postgres:13.4" with ID "sha256:113197da0347a82925486217beece0386a4de3b4aa3a34e53a20c988606ffa96" not yet present on node "kind-control-plane", loading...
ERROR: command "docker save -o /tmp/images-tar528868466/images.tar postgres:13.4" failed with error: exit status 1
Command Output: failed to save image: invalid output path: directory "/tmp/images-tar528868466" does not exist
```
Looks like temporary directory was not created before invoking `docker save`. Adding `--name` or `--nodes` options does not change the output.

**Comment by aojea** [comment]
hmm, I ack the problem with duplicate names https://github.com/kubernetes-sigs/kind/pull/2536
but I can't reproduce the issue with only one name, is there something that can be blocking kind to write in the tmp folder?
can you try with another image `kind load docker-image busybox` ?

**Comment by rpiotrow** [comment]
Looks the same
```
$ kind load docker-image busybox
Image: "busybox" with ID "sha256:7138284460ffa3bb6ee087344f5b051468b3f8697e2d1427bac1a20c8d168b14" not yet present on node "kind-control-plane", loading...
ERROR: command "docker save -o /tmp/images-tar098729653/images.tar busybox" failed with error: exit status 1
Command Output: failed to save image: invalid output path: directory "/tmp/images-tar098729653" does not exist
```
Hmm, maybe it's specific to my environment (somehow). Later today I can try to make some VM and try it there. Maybe my OS is somehow "broken" :man_shrugging:

**Comment by BenTheElder** [comment]
The problem is using docker from snap.

Snap doesn't allow docker access to TMPDIR, you can use something like `TMPDIR=$HOME/tmp/ kind ...`, use `docker save my-image` + `kind load image-archive`, or don't use snap to install docker.


https://kind.sigs.k8s.io/docs/user/known-issues/#docker-installed-with-snap

IMO docker snap's restriction here is not reasonable.

**Comment by BenTheElder** [comment]
unrelated: there is a typo in the docs there TEMPDIR should be TMPDIR

**Comment by rpiotrow** [comment]
That helped! Thanks! (I should read "known Issues" earlier :blush:) And yes, there is a typo there, should be `TMPDIR`. Closing this one.
