### ISSUE TITLE
Need to create users in the cluster

### ISSUE THREAD

**Issue by rsmoorthy** [kubernetes-sigs/kind#2538]
I need to create users in the cluster created by kind. In minikube, I would create a RSA key and CSR, and create a certificate using ca.crt and ca.key available at /home/user/.minikube/ca.crt and ca.key. In clusters created by kubeadm, the same keys are available at /etc/kubernetes/pki

However, with kind, I can get ca.crt from kubeconfig (`certficate-authority-data`), but I am not sure, where would I get the ca.key from.

Can you please guide me towards this?

**Comment by aojea** [comment]
kind deploys a kubernetes cluster using kubeadm emulating nodes with docker containers.

You are requesting something that is kubernetes and kubeadm specific, you can log into a node `docker exec -it kind-control-plane` per example, and get the certificates 

```
root@kind-control-plane:/# ls /etc/kubernetes/pki/
apiserver-etcd-client.crt  apiserver-etcd-client.key
```
