### ISSUE TITLE
`kind load` fails with "failed to extract layer" on debian bookworm with rootless docker

### ISSUE THREAD

**Issue by SanjayVas** [kubernetes-sigs/kind#2543]
Split off from #2541. Has some similarity to #2402.

**What happened**: `kind load` fails with error. See trace below. Image still shows up in internal containerd despite error (`docker exec -it kind-control-plane crictl images`)

**What you expected to happen**: Image loaded into Kind successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create default cluster with `kind create cluster`.
2. Attempt to load image archive using `kind load image-archive` OR load image into Docker and use `kind load docker-image`

**Anything else we need to know?**:

* Sample run with trace:
```
$ kind load image-archive bazel-container-bin/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/async_computation_control_server_image.tar -v 1
ERROR: failed to load image: command "docker exec --privileged -i kind-control-plane ctr --namespace=k8s.io images import -" failed with error: exit status 1

Command Output: unpacking docker.io/bazel/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server:async_computation_control_server_image (sha256:72adfdb270f0a3a69b425fe725c3028ec72b1d6227046ce31f2ff3baf0f2e443)...time="2021-11-17T19:11:25Z" level=info msg="apply failure, attempting cleanup" error="failed to extract layer sha256:e3d24823466584f8fcc6fe0d7d5bb09d2360b86ef9b655e21e8002ee04dd386b: failed to mount /var/lib/containerd/tmpmounts/containerd-mount562134243: operation not permitted: unknown" key="extract-583305635-lKcw sha256:5c30f10f05a6636f4b4a9fe393b48215dd35657cf972784e74027e488f9cbd0f"
ctr: failed to extract layer sha256:e3d24823466584f8fcc6fe0d7d5bb09d2360b86ef9b655e21e8002ee04dd386b: failed to mount /var/lib/containerd/tmpmounts/containerd-mount562134243: operation not permitted: unknown

Stack Trace: 
sigs.k8s.io/kind/pkg/errors.WithStack
	/usr/local/google/home/sanjayvas/go/pkg/mod/sigs.k8s.io/kind@v0.11.2-0.20211115230152-60143cb4e28c/pkg/errors/errors.go:59
sigs.k8s.io/kind/pkg/exec.(*LocalCmd).Run
	/usr/local/google/home/sanjayvas/go/pkg/mod/sigs.k8s.io/kind@v0.11.2-0.20211115230152-60143cb4e28c/pkg/exec/local.go:124
sigs.k8s.io/kind/pkg/cluster/internal/providers/docker.(*nodeCmd).Run
	/usr/local/google/home/sanjayvas/go/pkg/mod/sigs.k8s.io/kind@v0.11.2-0.20211115230152-60143cb4e28c/pkg/cluster/internal/providers/docker/node.go:146
sigs.k8s.io/kind/pkg/cluster/nodeutils.LoadImageArchive
	/usr/local/google/home/sanjayvas/go/pkg/mod/sigs.k8s.io/kind@v0.11.2-0.20211115230152-60143cb4e28c/pkg/cluster/nodeutils/util.go:80
sigs.k8s.io/kind/pkg/cmd/kind/load/image-archive.loadImage
	/usr/local/google/home/sanjayvas/go/pkg/mod/sigs.k8s.io/kind@v0.11.2-0.20211115230152-60143cb4e28c/pkg/cmd/kind/load/image-archive/image-archive.go:136
sigs.k8s.io/kind/pkg/cmd/kind/load/image-archive.runE.func1
	/usr/local/google/home/sanjayvas/go/pkg/mod/sigs.k8s.io/kind@v0.11.2-0.20211115230152-60143cb4e28c/pkg/cmd/kind/load/image-archive/image-archive.go:123
sigs.k8s.io/kind/pkg/errors.UntilErrorConcurrent.func1
	/usr/local/google/home/sanjayvas/go/pkg/mod/sigs.k8s.io/kind@v0.11.2-0.20211115230152-60143cb4e28c/pkg/errors/concurrent.go:30
runtime.goexit
	/usr/lib/google-golang/src/runtime/asm_amd64.s:1581
```

* containerd log: [containerd.log](https://github.com/kubernetes-sigs/kind/files/7557357/containerd.log)

**Environment:**

- kind version: (use `kind version`): v0.12.0-alpha devel +b7a85e0003 linux/amd64
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-11-04T09:36:56Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`): [edited to remove some unnecessary/potentially sensitive info]
```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.10
 Storage Driver: fuse-overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.10 amd64
 Operating System: Debian GNU/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.41GiB
 Debug Mode: false
 Username: sanjayvas
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```
- OS (e.g. from `/etc/os-release`): Debian Bookworm

**Comment by BenTheElder** [comment]
sadly containerd.log was not more insightful 😞 

something is wrong with fuse-overlayfs and containerd-in-docker trying to setup mounts for unpacking the image layers to the snapshotter.

I'm not sure if there's a workaround in kind, we depend on priv nodes being able to do `mount` on their volumes ... maybe forcing the "native" snapshotter if we can detect this broken environment similar to when run on zfs: 
https://github.com/kubernetes-sigs/kind/blob/fa7d86470f4c0e924fc4c2e767ec8491c45f4304/images/base/files/usr/local/bin/entrypoint#L100-L117

**Comment by BenTheElder** [comment]
Can you try `KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER=native kind create cluster` ?

**Comment by SanjayVas** [comment]
Same failure. Output of `docker logs kind-control-plane`: [kind-control-plane.log](https://github.com/kubernetes-sigs/kind/files/7557611/kind-control-plane.log)

Let me know if there's any other logs that could be helpful.

**Comment by BenTheElder** [comment]
I spoke to @SanjayVas some more after they reached out internally -- it's worth noting that we're observing this on gLinux/rodete which is not quite identical to upstream debian bookworm.

My own gLinux machine is running rootfull, not rootless docker, and I won't be switching right away as I need to run the Kubernetes debian/RPM releases shortly (which involves docker), but I may be able to dig in and repro this further in the future.

There's something funky going on with unpacking to the snapshotter such that the core K8s components are running fine while newly imported images fail ...

**Comment by AkihiroSuda** [comment]
`ctr` needs to be executed with `--snapshotter`  (`$CONTAINERD_SNAPSHOTTER`), as ctr does not read CRI config.

Maybe we should modify /etc/environment in the entrypoint script?

**Comment by SanjayVas** [comment]
Confirmed that `docker exec -i kind-control-plane ctr --namespace=k8s.io images import --snapshotter=fuse-overlayfs - < path/to/image.tar` successfully loaded the image.

**Comment by BenTheElder** [comment]
Thanks @AkihiroSuda @SanjayVas, that explains 🙃 , of course it makes sense that ctr is not reading CRI config 🤦‍♂️ 

https://github.com/kubernetes-sigs/kind/pull/2546 will fix, by detecting / parsing the currently configured CRI snapshotter and passing it to `ctr images import` at runtime.
