### ISSUE TITLE
Naming of workers nodes

### ISSUE THREAD

**Issue by sbng** [kubernetes-sigs/kind#2545]
NAME               STATUS   ROLES                  AGE     VERSION
k1-control-plane   Ready    control-plane,master   8h      v1.21.1
k1-worker          Ready    <none>                 7h59m   v1.21.1
k1-worker2         Ready    <none>                 7h59m   v1.21.1

Is there a way to rename and postfix the nodes to worker1, worker2, worker3? I look through the documentation and couldn't find an option to do that. Any help would be appreciated. Thanks in advance.

**Comment by BenTheElder** [comment]
No, there is not, sorry. Our node names are auto-generated, like kops, GKE, etc.

If you need to pin workloads to nodes you can add `labels:` to the node config (we need to document this! it will work properly in the next release), or use a https://kind.sigs.k8s.io/docs/user/configuration/#kubeadm-config-patches, then you can also taint the node based on label if you need with kubectl. this approach is portable across kubernetes implementations.

For other use cases, hopefully the node name should not be important.
