### ISSUE TITLE
How can I install application services in one cluster

### ISSUE THREAD

**Issue by yxz312** [kubernetes-sigs/kind#2548]
I have created multiple clusters. How can I install application services in one cluster? For example, install services in the form of helm chart package

**Comment by aojea** [comment]
as with any other kubernetes cluster, is there something in particular you feel blocked?
There are a lot of tutorials like this per example https://docs.gitlab.com/charts/development/kind/

**Comment by BenTheElder** [comment]
Regarding KIND and multiple clusters:

KIND defines users and contexts, you can access each cluster with `--context=kind-$name` with `kubectl` and many other tools or you can change the current default context in the KUBECONFIG with `kubectl config use-context kind-$name`. So for example with the default cluster from `kind create cluster` with no options you would say `kubectl config use-context kind-kind`.

You can also instead create a config file per cluster by setting `KUBECONFIG` environment variable or `--kubeconfig` flag to point to a different path when calling `kind create cluster` and then set `KUBECONFIG` or `--kubeconfig` when calling other tools like kubectl or helm.

Regarding installing with helm charts:


This question is probably better suited for https://discuss.kubernetes.io/, we don't use / support helm here, or any other competing tool. KIND provides fully upstream, conformant, standard Kubernetes with which you can use tools like helm the same as any other Kubernetes cluster.
