### ISSUE TITLE
Please remove specific tag check?

### ISSUE THREAD

**Issue by SamYuan1990** [kubernetes-sigs/kind#2557]
**What happened**:
kind use an image with specific tag with hash but not the tag itself.

```
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.21.1) 🖼  ...
DEBUG: docker/images.go:67] Pulling image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6 ...
```

**What you expected to happen**:
it running with tag but not tag+hash
```
 docker images | grep kindest/node
kindest/node                                                                                                                                                             v1.21.1                                                 65d38077cb24   5 months ago     931MB
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by aojea** [comment]
if you don't use the hash you can not differentiate between images with the same tag

**Comment by SamYuan1990** [comment]
> if you don't use the hash you can not differentiate between images with the same tag

for my understanding, the tag as some kind of interface for a release package right?
ex in tag a.b.c we released feature x
and with latest a.b.c we fixed a bug y of feature x.

but it should works for `kind` cli as the command line require for feature x.
if use no meet the bug y, the old image should no impacts with user.
if need to use version with bug free, user need to update the image as docker pull image:a.b.c ...

if we hard code image with hash, yes, we can't differentiate between images with same tag.
also the image tag lost.

which means, 
- user need bug fix version should update image and?
- as the image with same tag with 2 hash, the old image will be removed by `docker image prune` as the `docker` housekeeping targeting on image tag.
it sharing image tag, but only one image with tag is the correct/latest. the older image will be pruned.

**Comment by SamYuan1990** [comment]
btw, this there any benefit to hard code hash in specific command binary release?

**Comment by aojea** [comment]
each kind version releases kind node images associated to a kubernets version
https://github.com/kubernetes-sigs/kind/releases

These images doesn't have to be backwards compatible, so:
- kind v0.11.1 has kindest/node:v1.21.1@hash1
- kind v0.9.0 has kindest/node:v1.21.1@hash2

**Comment by BenTheElder** [comment]
> Please remove specific tag check?

What check?

> btw, this there any benefit to hard code hash in specific command binary release?

yes, this means you can never be surprised by a new image being changed, you opt into changes.
as long as the host registry infrastructure itself is not compromised or as long as docker verifies the hashes, you cannot be surprised by a new image. this is more secure and reproducible.

if they user wants to use an image by tag, they can just set `--image` or the config file, though we still recommend pinning the hash.

**Comment by BenTheElder** [comment]
> as the image with same tag with 2 hash, the old image will be removed by docker image prune as the docker housekeeping targeting on image tag.

when you tell docker to use a hash, it doesn't read the tag at all, it is discarded. the tag in `foo:bar@sha256:abcd` is just for the purposes of documenting to the user what intention is `foo@sha256:abcd`, `bar` is ignored.

so this shouldn't be a problem.

**Comment by BenTheElder** [comment]
> user need bug fix version should update image and?

Any bug fix that happens will be in a new release. We make our best effort to ensure that images remain compatible across kind versions but cannot guarantee it, this is why there's a listing of prebuilt images in the release notes.

You can also build your own images: https://kind.sigs.k8s.io/docs/user/quick-start/#building-images if you need a different Kubernetes version.

> if we hard code image with hash, yes, we can't differentiate between images with same tag.

for images identified by hash, the tag is irrelevant. You're actually consuming them by hash, the tag is just documentation / intent to the person reading your `--image` flag setting or `docker run` command.

----

The trivial opt-out for this is just not providing the hash when setting `--image` or the config file equivilant. You're free to do that, but we make less guarantees about this, currently. There are multiple other tracking issues related to how the images are published.

We will continue to specify and encourage the hashes, and the one *default* image will continue to pin it.
