### ISSUE TITLE
How does a Docker that creates a cluster own a network

### ISSUE THREAD

**Issue by yanlingsishao** [kubernetes-sigs/kind#2560]
When I created a cluster through KIND, the image could not be downloaded. Finally, I found the docker running the cluster and found that there was no network. How does the docker own a network

**Comment by aojea** [comment]
can you elaborate more?
kind creates a docker network , you can see it with `docker network ls` , is that what you are asking?

**Comment by aojea** [comment]
/close
it's been more than 10 days without an answer, we can always reopen though
