### ISSUE TITLE
Having trouble getting started

### ISSUE THREAD

**Issue by virtualdogbert** [kubernetes-sigs/kind#2563]
So I wanted to migrate from minikube to kind and started with the instructions on the website to download kind, then moved on to setting up and ingress controller but I see that it won't pull the image for the controller:
```
curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
chmod +x ./kind
mv ./kind ~/bin/kind
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
EOF
kind get clusters
kubectl cluster-info --context kind-kind
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
kubens ingress-nginx
kubectl get pods
NAME                                       READY   STATUS              RESTARTS   AGE
ingress-nginx-admission-create-5kn2z       0/1     ImagePullBackOff    0          6m28s
ingress-nginx-admission-patch-hj86g        0/1     ImagePullBackOff    0          6m28s
ingress-nginx-controller-b7b74c7b7-4754p   0/1     ContainerCreating   0          6m28s
```

Is there something more I need to be doing before trying to install the ingress controller?

**Comment by BenTheElder** [comment]
Do you have unfiltered public internet access? Are you using any sort of proxy?

kind can pass along `HTTP_PROXY` / `NO_PROXY` / `HTTPS_PROXY` (or their lowercase friends) when creating the cluster if you have these set in your shell.

The images in that manifest are hosted at k8s.gcr.io (the Kubernetes project's official registry). Typically failure to pull the image is a connectivity issue.

If you run `kind export logs` and upload the results here we can look at the cluster system logs.

**Comment by virtualdogbert** [comment]
Here are the logs, I'm not behind a proxy and I can ping k8s.gcr.io  with no issue...

[kindlogs.zip](https://github.com/kubernetes-sigs/kind/files/7671469/kindlogs.zip)

**Comment by virtualdogbert** [comment]
So I looked deeper at the logs and it did look like something weird, with my network connection. So I disconnected from the vpn and it seems to work. Although I'm also going to want to set this up on a system that's on that network, and I guessing that will require devOps which could be a PITA. Thanks.
