### ISSUE TITLE
pin Docker to 18.09

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/kind#257]
kubeadm moved to recommending 18.09:
https://github.com/kubernetes/kubernetes/pull/73457/files

logging an issue to see if there are objections:
https://github.com/kubernetes-sigs/kind/blob/master/images/base/Dockerfile#L75

**Comment by BenTheElder** [comment]
Doesn't this break CRI detection for older kubernetes?

**Comment by neolit123** [comment]
on the kubeadm side, not if we`--ignore-preflight-errors=all`, which is pretty much the case, still.
technically kubeadm has a support matrix for Docker.

but yes, older kubeadm binaries will not recognize 18.09 or even 18.06. problem here is that the Docker file needs to be "templated" the same way we handle different kubeadm config versions.

**Comment by BenTheElder** [comment]
And that won't cause any other issues? I hadn't had a chance to dig into this yet.

> but yes, older kubeadm binaries will not recognize 18.09 or even 18.06. problem here is that the Docker file for the base image needs to be "templated" the same way we handle different kubeadm config versions.

I'd like to avoid that, kind should support the 3 current kubernetes versions + master branch at minimum and not be dependent on image features to work.

Another option might be dropping down to containerd so we aren't yet another CI task depending on dockershim, but I think having docker available is probably most user-friendly.

**Comment by neolit123** [comment]
> And that won't cause any other issues? I hadn't had a chance to dig into this yet.

i'm not even using 18.x on my VMs yet.

**Comment by neolit123** [comment]
so we had a chat about this today at the kubeadm office hours.
we decided to enable support for 18.09 in 1.14 but still keep 18.06 as the default in docs and everywere.

**Comment by tao12345666333** [comment]
> And that won't cause any other issues? I hadn't had a chance to dig into this yet.

For the time being, there will be no big problem.
The following is the version of the software I am using.

```
[root@master ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:21:46Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
[root@master ~]# docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

If there is a very abnormal situation, I will feedback. :laughing:

**Comment by BenTheElder** [comment]
Thanks. I do remember we at least saw some dind issues with 18.09 ref #136

**Comment by neolit123** [comment]
let's close the docker related tickets and decide to upgrade once upstream moves as well.
/close
