### ISSUE TITLE
kubectl config set-context does not persist

### ISSUE THREAD

**Issue by EdmundsEcho** [kubernetes-sigs/kind#2572]
**What happened**:
Set the current context to one of the clusters created using `kind`:
```fish
k config set-context this-cluster
```

Echo the current cluster
```fish
k config current-context
```

Reports the "default" cluster.  i.e., the  `current-context` entry in the `~/.kube/config`.  The important thing being the entry is not what I set it to.

**What you expected to happen**:

Run the `config set-context` command and be able to echo the change; i.e., the command should update the config file.  

**Environment:**

All in all, there seems to be a difference in the versions between `kind` and `kubectl`.   

- kind version: (use `kind version`):  `0.11.1`

- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:06:30Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

- Docker version: (use `docker info`):
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 5.8GiB
 Name: docker-desktop
 ID: TCLP:TOR4:CKYQ:DTOC:XOAD:GKFE:XCLE:LMOF:2GIA:QIO5:PJLP:BZBG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- OS (e.g. from `/etc/os-release`):  `macos 12.0.1`

**Comment by BenTheElder** [comment]
Taking a guess based on what you have above:

> k config set-context this-cluster


The context name for a cluster with `--name=this-cluster` would be `kind-this-cluster`, rather than `this-cluster`. (It is prefixed with `kind-`).

`kind create cluster --name=foo` will print an example kubectl command with the correct context `--context=kind-foo` upon creating the cluster. It also sets the current context to that cluster upon creating it.

If this isn't persisting otherwise due to e.g. some bug in `kubectl `then:
1. kubectl is another project upstream
2. kind doesn't install kubectl

So in that case please file a bug with kubectl 😅

**Comment by EdmundsEcho** [comment]
To your point, this may be something to address with `kubectl`.  

Just a quick follow-up if I might.  I can create multiple clusters with `kind`.  The kubectl config is generated for me by kind with a complete list of the clusters.  Is there a way to work with a single cluster by using the `kubectl config` command in such a way that I don't have to keep specifying which cluster's api I wish to hit?
