### ISSUE TITLE
Starting control - plane fails with ubuntu 

### ISSUE THREAD

**Issue by keanryan** [kubernetes-sigs/kind#2585]
**What happened**:

When i try to start a cluster, the control plane fails.

**What you expected to happen**:

The control plane starts to create a cluster. 

**Environment:**

- kind version: v0.8.1
- Kubernetes version: v1.23.1
- Docker version: v0.9.1
- OS (e.g. from `/etc/os-release`):
<img width="866" alt="Schermata 2022-01-11 alle 09 19 16" src="https://user-images.githubusercontent.com/97507103/148910391-6cff46c3-5907-46de-af90-e1f8dae32e1a.png">

**Comment by aojea** [comment]
you are using an old version of kind, please use the latest one

**Comment by BenTheElder** [comment]
+1, I suggest upgrading to a current release of both docker and kind, though I suspect 0.9.1 is not the accurate docker version.

I don't think there's anything further for us to do here, even if there is a bug in v0.8.1 we've likely already fixed it by now.
