### ISSUE TITLE
Several pods do not start, encounter "too many open files" error

### ISSUE THREAD

**Issue by skhamkar-tibco** [kubernetes-sigs/kind#2586]
I am using macOS Monterey 12.1 and I am setting up a cluster on kind version v0.11.1 but several pods encounter "**too many open files**" error.

The cluster has been torn down and rebuilt several times. Each time the pods encounter "**too many open files**" error. All other pods successfully attain Running status.

Since this is run on macOS, configured launchctl to increase the maxfiles but still faced the same issue.

We added the following configuration to docker, But it didn’t solve the problem.
`Preferences -> Docker Engine` and the following are added to config:

```
  "default-ulimits": {
    "nofile": {
      "Soft": 640000,
      "Hard": 640000,
      "Name": "nofile"
    }
  },
```
On the host machine terminal we can see the below values:

```
launchctl limit maxfiles
	maxfiles    524288         5242880
```

Below are the running containers of KIND:
docker ps -a
```
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES

85754ed34564   kindest/node:v1.20.7                   "/usr/local/bin/entr…"   32 minutes ago   Up 32 minutes                                                                        worker
f072d9bc99b1   kindest/node:v1.20.7                   "/usr/local/bin/entr…"   32 minutes ago   Up 32 minutes   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 127.0.0.1:6443->6443/tcp   control-plane
5800621e01fd   rpardini/docker-registry-proxy:0.6.3   "/entrypoint.sh"         32 minutes ago   Up 32 minutes   80/tcp, 3128/tcp, 8081-8082/tcp                                      registry-proxy
```
ulimit values inside worker node:

```
docker exec -it 85754ed34564 bash
root@tibco-cic-worker:/# ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 95734
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 640000
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) unlimited
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

**### Software Versions:**

```
skhamkar@skhamkar ~ % sudo kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-27T23:27:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
skhamkar@skhamkar ~ % docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.10
 Git commit:        dea9396
 Built:             Thu Nov 18 00:36:09 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:39 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by aojea** [comment]
it sounds you are hitting this known issue

https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files

**Comment by skhamkar-tibco** [comment]
> it sounds you are hitting this known issue
> We tried the above solution but we are facing the same issue
> https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files

**Comment by sechkova** [comment]
@skhamkar-tibco I had exactly the same issue as you, setting up a cluster with kind 0.11.1 on MacOS 11.6.2 by running `kind create cluster`. I had to apply the fix from https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files but to the worker node running Linux. That fixed it. 

@aojea Since the issue was in the Linux limits of the worker node created by kind, is there a way to apply this config permanently to all newly created nodes/clusters?

**Comment by BenTheElder** [comment]
> Since this is run on macOS, configured launchctl to increase the maxfiles but still faced the same issue.

note that the out of files errors are coming from within the linux VM docker runs. changing the limits on macOS is unlikely to matter, this is a limit inside the docker desktop linux VM.

**Comment by BenTheElder** [comment]
(and as noted by the known issues entry, it's probably not actually a general file handles limit, but rather inotify watch limits, the errors printed by go programs using common code for this tend to be misleading)

**Comment by BenTheElder** [comment]
> @aojea Since the issue was in the Linux limits of the worker node created by kind, is there a way to apply this config permanently to all newly created nodes/clusters?

you could customize `/etc/sysctl.conf` in the docker desktop VM. An important detail currently missing from the docs is that inotify limits are *not* namespaced, it is global to everything running under that linux kernel, at least last I investigated this.

so you should change it on the linux host (docker desktop VM) rather than it being a per-cluster property

**Comment by skhamkar-tibco** [comment]
Thanks, @BenTheElder @sechkova, It fixed the issue.
In the script for creating a kind cluster, we added the following lines to apply config and it worked.

`  docker exec -t <id> bash -c "echo 'fs.inotify.max_user_watches=1048576' >> /etc/sysctl.conf"
    docker exec -t <id> bash -c "echo 'fs.inotify.max_user_instances=512' >> /etc/sysctl.conf"
    docker exec -i <id> bash -c "sysctl -p /etc/sysctl.conf"
`
Closing the issue.
