### ISSUE TITLE
Links to filepermissions.com are broken in Dockerfiles

### ISSUE THREAD

**Issue by gotzmann** [kubernetes-sigs/kind#2587]
Dockerfiles have a links to 404 pages, like this:

https://github.com/kubernetes-sigs/kind/blob/main/images/base/Dockerfile#L71

**What should be cleaned up or changed**:

Links to http://www.filepermissions.com/file-permission/0755 and similar pages should be changed for something meaningful

**Why is this needed**:

It have no sense to have broken links for documentation purposes.

**Comment by aojea** [comment]
nice catch, do you want to submit a PR to fix it?

**Comment by gotzmann** [comment]
> nice catch, do you want to submit a PR to fix it?

https://github.com/kubernetes-sigs/kind/pull/2590

**Comment by BenTheElder** [comment]
thanks! https://github.com/kubernetes-sigs/kind/pull/2591
