### ISSUE TITLE
figure out how to handle --name flag for clusters

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/kind#259]
currently for cluster `delete` and `create` the `--name` flag defaults to `1`.
while the cluster name ends up being as `1` in the cluster list, the nodes are prefixed with `kind-1-`.

figure out a plan how to handle the name on the user side. some options.
- default cluster names to `kind-1` for `delete` and `create`
for kind the UX must be as simple as possible so defaulting to a cluster name makes sense.
- allow custom cluster names without the implicit `kind` prefix which will allow users to prefix nodes in a custom way as well.

optionally / possibly separate PRs:
- add methods to list nodes per cluster on the CLI.
- `delete cluster` without y/n is a bit scary.
for kubeadm we have a stdin prompt unless `--force` is passed.

/assign 
/priority important-soon
/kind design

**Comment by mauilion** [comment]
However this works out it would be awesome to expose it as an env var. I frequently use tooling like direnv.net to set the configuration of the kubeadm-dind stuff and would very much like to persist this to the kind project.

**Comment by BenTheElder** [comment]
can you use `kind create cluster --name=$KIND_NAME` ? 

the "name" is just use to differentiate creating multiple instances from a config (or the default config) we've kept almost everything else in config files for now.

we're leaning towards not using many unversioned flags.

**Comment by neolit123** [comment]
i will possibly send a PR for the initial changes tomorrow.

**Comment by BenTheElder** [comment]
fixed in #260, thanks!
