### ISSUE TITLE
Perhaps `-n` for `--name`?

### ISSUE THREAD

**Issue by rwxrob** [kubernetes-sigs/kind#2592]
**What would you like to be added**:

Just a `-n` alternative to `--name` since we are so used to using that
with `kubectl`.

**Why is this needed**:

Because we are lazy and use `kubectl` a lot. ;)

**Comment by BenTheElder** [comment]
this is probably OK but I really want to see v0.12.0 out the door before we add anything further to it, there's one remaining regression to resolve we just haven't had it fixed yet. I may aim for it later today #2540

**Comment by BenTheElder** [comment]
I can't recall any reason we intentionally *didn't* do this, i think the main thing was we were looking at if name should be an argument instead of a flag but I think that boat has sailed.

FWIW, there's also the environment variable in the meantime.

**Comment by amarsgithub** [comment]
@BenTheElder  any chance I can implement this and we can run it into v0.12.0?

**Comment by amarsgithub** [comment]
@BenTheElder is this the same as -n for kind create cluster?

**Comment by BenTheElder** [comment]
presumably the request is for all commands with `--name`?

but as I said, we should NOT merge any more feature work until we're cut another release, it's been far too long.

**Comment by arielmorelli** [comment]
@rwxrob this is done with this https://github.com/kubernetes-sigs/kind/pull/2818, right?

**Comment by aojea** [comment]
> @rwxrob this is done with this #2818, right?

Indeed
Thanks
/Close
