### ISSUE TITLE
Add v1.19.17 to docker hub. The current latest is v1.19.11 which is not up-to-date

### ISSUE THREAD

**Issue by iamtodor** [kubernetes-sigs/kind#2593]
**What would you like to be added**:
Please add the latest v.1.19.16 k8s public version to your docker hub. Currently, the latest minor version for v1.19 is 11: https://hub.docker.com/layers/kindest/node/v1.19.11/images/sha256-cbecc517bfad65e368cd7975d1e8a4f558d91160c051d0b1d10ff81488f5fb06?context=explore

**Why is this needed**:
Here is CHANGELOG for 1.19 from the official repo https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md

**Comment by BenTheElder** [comment]
Sorry, this is not how image publishing works. Please see existing issues discussing the topic.

We publish pre-built images at the latest kubernetes version intermittently during development of the project, and then a full suite of the latest of each patch to go with kind releases. These images are vetted and published to the best of our efforts.

Inbetween that time, we do not have the automation yet or the time, and instead https://kind.sigs.k8s.io/docs/user/quick-start/#building-images is availble.

The primary purpose of this project as it was originally created and supported is to test Kubernetes itself, and currently it is largely being volunteer maintained

more:
https://kind.sigs.k8s.io/docs/contributing/project-scope/

and:
https://kind.sigs.k8s.io/
> kind was primarily designed for testing Kubernetes itself, but may be used for local development or CI.


see also: [#pushautom](https://github.com/kubernetes-sigs/kind/issues/197), https://github.com/kubernetes-sigs/kind/issues/1895, https://github.com/kubernetes-sigs/kind/issues/2376, etc.
