### ISSUE TITLE
Is KIND local registry documentation wrong about localhost?

### ISSUE THREAD

**Issue by simonjcarr** [kubernetes-sigs/kind#2599]
The documentation at https://kind.sigs.k8s.io/docs/user/local-registry/

Provides a tutorial on how to create a local repository and then pull an image from that repository.

```
kubectl create deployment hello-server --image=localhost:5000/hello-app:1.0
```

The above command gives a POD with a ImagePull error. I don't think this is surprising as localhost in the context of the POD is not localhost on the host system.

Can someone confirm if this is me reading this wrong, or if the documentation needs updating?

**Comment by aojea** [comment]
containerd is patched to redirect localhost to the right url
```
# create a cluster with the local registry enabled in containerd
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
    endpoint = ["http://${reg_name}:5000"]
EOF
```

**Comment by BenTheElder** [comment]
As Antonio said, containerd is configured to pull from the registry at kind-registry:5000 for images that are at localhost:5000, this is so you can tag/push/pull at a consistent image name on the host and inside the cluster without any special hostnames on the host.

You are correct that localhost in the context of the pod is not localhost on the host system. Further actually localhost in your pod is not localhost of the node container is not localhost of the host.

But the pod image is being pulled at the node level by containerd, where the docs specify supplying the config patch that tells containerd to use a different address when pulling from localhost.

I would guess the image pull error is either a cluster that is missing the patch from the sample script, or the image actually doesn't exist in the registry.

**Comment by simonjcarr** [comment]
@BenTheElder Thank you for the explanation. I expect I was doing something wrong.
