### ISSUE TITLE
Node image for v1.23.3

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/kind#2605]
Could you please release the node image for v1.23.3?

Why?
https://groups.google.com/a/kubernetes.io/g/dev/c/Xl1sm-CItaY/m/gmotd1VEBAAJ

Thanks!

**Comment by aojea** [comment]
here you go

https://hub.docker.com/layers/kindest/node/v1.23.3/images/sha256-0df8215895129c0d3221cda19847d1296c4f29ec93487339149333bd9d899e5a?context=explore
