### ISSUE TITLE
can't visit pod

### ISSUE THREAD

**Issue by zhoumingcheng** [kubernetes-sigs/kind#2606]
After I created the cluster through kind, I deployed nginx pod. However, the pod cannot be accessed from the host
![image](https://user-images.githubusercontent.com/52434045/151107131-cb3c7f4b-dfd1-4d7e-a0dc-25455ec8bbab.png)

kind v0.11.1 go1.16.4 linux/amd64

**Comment by aojea** [comment]
The pod is accessible Within the cluster, the kubernetes networking explains it better
https://kubernetes.io/docs/concepts/services-networking/
