### ISSUE TITLE
control plane fails for second cluster

### ISSUE THREAD

**Issue by sandcuck** [kubernetes-sigs/kind#2610]
At creation of the second cluster, initialization of control plane fails consistently.

environment:
- freshly installed Ubuntu 20.04 on kvm, updated and upgraded
- Docker version 20.10.12, build e91ed57
- kind v0.11.1 go1.16.4 linux/amd64
- no kubectl installed yet, but error is independent from presence of kubectl

[kind-history.txt](https://github.com/kubernetes-sigs/kind/files/7950904/kind-history.txt)
[kind-error.txt](https://github.com/kubernetes-sigs/kind/files/7950896/kind-error.txt)

**Comment by aojea** [comment]
```   51  kind create cluster --name test
   52  kind get clusters
   53  kind delete cluster
   54  kind create cluster --name test

**Comment by sandcuck** [comment]
I am not familiar with user interface yet, but I don't see a possibility how this can be causal for the issue (I reproduced the issue several times and sometimes broke the kind create command before the timeout, so there was no cluster with the same name in the list).

**Comment by sandcuck** [comment]
Issue is solved. Root cause was overprovisioning in the virtualization infrastructure.
