### ISSUE TITLE
Kubernetes Job not creating pod

### ISSUE THREAD

**Issue by EGNSIUR** [kubernetes-sigs/kind#2611]
![image](https://user-images.githubusercontent.com/73429040/151651496-145300fd-451a-4502-8420-94565ed9caa0.png)
I  created a job but with jobs.yml file but it is not creating any pod and its status is also not getting changed (completion 1/1), am i missing anything?
please help!!

**Comment by fhke** [comment]
Try checking for events related to the job:

```shell
kubectl describe job batch-job
```

If there are no events for the job, check the kube-controller-manager pod(s) status & logs in the kube-system namespace.

**Comment by EGNSIUR** [comment]
I checked, it is working now

Created pod: kubia-bt46b"
I0130 16:29:58.906370       1 event.go:291] "Event occurred" object="default/batch-job" kind="Job" apiVersion="batch/v1" type="Normal" reason="SuccessfulCreate" message="Created pod: batch-job-n2nfl"
I0130 16:32:11.489371       1 event.go:291] "Event occurred" object="default/batch-job" kind="Job" apiVersion="batch/v1" type="Normal" reason="Completed" message="Job completed"

I recreated my kind cluster and it resolves the issue.
