### ISSUE TITLE
Can we use kind go sdk instead of binary?

### ISSUE THREAD

**Issue by WinterSoilder** [kubernetes-sigs/kind#2613]
I know that We can download kind binary and execute, but if i wanted to create kubernetes cluster programatically is that possible?
i have seen this [documatentation](https://pkg.go.dev/github.com/kubernetes-sigs/kind) where there is cluster pkg but i am not sure how we can import and use it. Can i get a code snippet if this possible?

**Comment by BenTheElder** [comment]
You can see usage of the cluster package in the commands, which are also importable.

https://github.com/kubernetes-sigs/kind/tree/main/pkg/cmd

Or via a few other open source projects https://grep.app/search?q=%22sigs.k8s.io/kind/pkg/cluster%22

We do our best to keep the API stable, but it's not our primary use case for the project.
https://kind.sigs.k8s.io/docs/contributing/project-scope/

**Comment by aojea** [comment]
I have some code that shows how to use the kind API in this repo

https://github.com/aojea/kind-networking-plugins/blob/main/multizone/cmd/create.go

**Comment by WinterSoilder** [comment]
Thanks @aojea and @BenTheElder. I'll check these files and try to get it done.
