### ISSUE TITLE
Local proxy with docker desktop

### ISSUE THREAD

**Issue by blacksails** [kubernetes-sigs/kind#2614]
**What would you like to be added**: 

I would like to be able to configure the proxy without changing the proxy environment variables on the host OS.

I would assume that in most cases we should use what is set in `~/.docker/config.json`. Wether a specific kind setting would be needed is a bit unclear to me.

**Why is this needed**:

At our company we are running a CNTLM proxy locally on the host OS, we set our proxy environment variables to point to this proxy to properly reach the internet. When using docker desktop a vm is created, and when launching a kind cluster a container is started on the vm. When the kind cluster is started it inherits the proxy environment variables, but these need to be changed from `localhost` to `host.docker.internal` inside the vm in order to point to the proxy on the host OS.

Docker Desktop has a setting for setting this up correctly, but when we have another docker inside docker this doesn't work for that. Instead this container will use the proxy settings from the environment variables. https://docs.docker.com/desktop/mac/#proxies

The docker cli client also has an explicit setting for how the proxy should be setup inside containers. https://docs.docker.com/network/proxy/#configure-the-docker-client

**Comment by BenTheElder** [comment]
> I would assume that in most cases we should use what is set in ~/.docker/config.json.

This appears to be a duplicate of https://github.com/kubernetes-sigs/kind/issues/1175

**Comment by blacksails** [comment]
Yes it is indeed a duplicate sorry about that. I will close the issue.
