### ISSUE TITLE
Could not resolve host: kind.sigs.k8s.io

### ISSUE THREAD

**Issue by catfish1225** [kubernetes-sigs/kind#2615]
root@PLYD2B756:/mnt/c/Users/Administrator# curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: kind.sigs.k8s.io

I'm Trying to install Kind I'm getting this Error. Can anyone help me on this isssue?

**Comment by BenTheElder** [comment]
I can't replicate this, https://kind.sigs.k8s.io/ loads for me.

You can use https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1 instead though:
https://github.com/kubernetes-sigs/kind/releases/download/v0.11.1/kind-linux-amd64

**Comment by catfish1225** [comment]
root@PLYD2B756:/usr/local/bin# curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1/kind-linux-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: github.com
root@PLYD2B756:/usr/local/bin# curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: kind.sigs.k8s.io

Seems like Domain got registered somewhere in the local. Is there any chance that i can delete & run kind comamnd?

**Comment by aojea** [comment]
if your host is not able to resolve domains is not likely you can progress more, because it will fail later trying to download the docker images needed.
You should try to fix that, maybe you are using an internal proxy?

**Comment by catfish1225** [comment]
Yep, It is a internal proxy. However https://kind.sigs.k8s.io/ & https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1 it got worked for the first time. If I wanted to re-run the same command the it is showing the above Error.

What would be fix?

**Comment by BenTheElder** [comment]
I really couldn't say, it sounds like a bug in the proxy implementation (maybe it can't handle 3XX redirects?), but we're not really doing anything unusual here. 

This domain is managed in https://github.com/kubernetes/k8s.io/ `dns/` and is just pointing to the netlify instance hosting our docs. It serves a redirect for the downloads so we can move the hosting for those later if we want.

**Comment by stmcginnis** [comment]
> Could not resolve host: github.com

This is clearly a local environment issue, unrelated to kind.

You may be able to flush your local DNS cache with `sudo /etc/init. d/dns-clean restart`. This appears to be WSL, so not sure how WSL/Windows name resolution interacts, but it may also be worth running `ipconfig /flushdns` from the Windows side of things. Doing a `ping www.github.com` could be a quick test to see if the name resolution is working for you. If that doesn't work after flushing you DNS cache, you may need to speak to whoever supports your proxy and/or networking to get some help.
