### ISSUE TITLE
Connect to the cluster from another machine

### ISSUE THREAD

**Issue by Sporesirius** [kubernetes-sigs/kind#2616]
Hello,
I'm trying to connect with a laptop (test client) to the cluster.
I have 9 deployments and each has a service, then I used metalb to get an external IP (docker kind network).
Is there a simple method to forward the ports to the WAN IP of the host but at the same time be able to use the services and not access the nodes directly or is that not the scope of the project?

Thx :)

**Comment by BenTheElder** [comment]
You can perhaps try extraPortMappings on the node + matching nodePorts for the services, similar to https://kind.sigs.k8s.io/docs/user/ingress/, but overall I think this is out of scope of the project. Alternately you can run a container alongside the cluster to do the forwarding (e.g. socat).

**Comment by BenTheElder** [comment]
Generally we discourage exposing kind to WAN 🙃  https://kind.sigs.k8s.io/docs/user/configuration/#api-server

**Comment by Sporesirius** [comment]
Oh ok, I thought that maybe that would be a legit support case to test from cluster to external.
