### ISSUE TITLE
versions should be fully sortable

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#2618]
Right now versions are either just plain semver, or semver like `v0.12.0-alpha+666b3368ea5659` for versions between releases

We should make versions between releases be like `v0.12.0-alpha+278-g666b3368` or similar, IE include the number of commits since the last tag (similar to `git describe --always --dirty --tags`). Right now versions between releases cannot be sorted, which makes compatibility trickier to understand.

We should enhance the versioning scheme for non-release versions. We can detect and inject the commit count in the same way we detect and inject the commit currently.

**Comment by zaunist** [comment]
Hi, @BenTheElder 

As I understand it, we need to add commit information to the non-release version, right? In addition to that, there needs to be a number to sort by, like the number of commits.

As you have described:  `v0.12.0-alpha+278-g666b3368`

If that's all, I could come and try.

**Comment by zaunist** [comment]
Maybe `git rev-list count HEAD` could solve this issue. This command will count commit number.

eg.

```
code/kind/bin  main ✔                                                                                            1d8h
▶ git rev-list --count HEAD
3584
```

**Comment by BenTheElder** [comment]
I think we should mimic versions from kubernetes etc, so we should use the commits since the tag, but I think we can do that.

**Comment by zaunist** [comment]
> I think we should mimic versions from kubernetes etc, so we should use the commits since the tag, but I think we can do that.

What I mean by this is to add a commit number for statistics, for example:

```
v0.12.0-alpha+{commit-number}-g666b3368
```

**Comment by BenTheElder** [comment]
Yes, my point is the approach listed above gives total commits as opposed to commits since last version tag (git describe style$

**Comment by zaunist** [comment]
Got it.

**Comment by BenTheElder** [comment]
for what it's worth I think total commits is a useful value but I don't want to confuse people investing our own version format

we can parse back from the last `-` and get the commit count since the tag with `git describe --tags`. hacky approach: `git describe --tags | rev | cut -d- -f2 | rev`

**Comment by zaunist** [comment]
> for what it's worth I think total commits is a useful value but I don't want to confuse people investing our own version format
> 
> we can parse back from the last `-` and get the commit count since the tag with `git describe --tags`. hacky approach: `git describe --tags | rev | cut -d- -f2 | rev`

I'm sorry, I've been busy with other things recently, and I'm a little negligent.

**Comment by BenTheElder** [comment]
No worries! Appreciate the help 🙂
