### ISSUE TITLE
document kubetest integration

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#262]
https://github.com/kubernetes-sigs/kind/issues/161#issuecomment-460105113

We have integration now, but it's not really documented. Possibly pointers could live in the upstream developer e2e test docs as hack/local-up-cluster.sh does currently and/or some docs could live in test-infra. 

We should also at least point to those docs from kind's own docs once they exist, but the full contents may not belong here.

**Comment by neolit123** [comment]
i cannot find any docs about `hack/local-up-cluster.sh` in k/k and k/test-infra. but if there is an exact location e.g. file/folder i guess can help.

**Comment by BenTheElder** [comment]
The main docs I know of for k/k devel are actually in k/community, in particular I think this is the canonical e2e doc: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md

**Comment by neolit123** [comment]
ok, i forgot about those.

i think we might want to start on the docs only after we have jobs using the deployer.
my work on `kubeadm-kind-<branch-name>` is starting next week.

**Comment by neolit123** [comment]
might as well wait for kubetest2 TBH.

**Comment by BenTheElder** [comment]
SGTM

**Comment by BenTheElder** [comment]
we do have jobs using the deployer, maybe we should go ahead and document how to use this with kubetest, kubetest2 might be a bit... (it looks like a teammate will ramp up on this and get to it ... soonish ??)

**Comment by neolit123** [comment]
i have a TODO to document how to test the e2e framework for new contributors:
https://github.com/kubernetes/kubernetes/issues/76833
these tickets seem to overlap, although there were concern from the testing-commons group that they  don't want these docs in k/community because they find these docs confusing /shrug.

when i get time, i might as well send to:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md
and see how that goes.

**Comment by BenTheElder** [comment]
SGTM, if not we can put docs in the kind docs, either way we should at
least link out to those from the kind site.

Thanks :-)

**Comment by BenTheElder** [comment]
we have other issue tracking improving the docs, and kubetest / kubetest2 hasn't really shaken out.

**Comment by BenTheElder** [comment]
`kubetest` is fully deprecated since then, in maintenance only mode, and but obviously kubetest2 is still not quite there.

there's a related currently open issue https://github.com/kubernetes-sigs/kind/issues/1181 tracking this more generally.
