### ISSUE TITLE
kind could not start v1.17 or v1.16 cluster on macOS docker desktop

### ISSUE THREAD

**Issue by mstrYoda** [kubernetes-sigs/kind#2629]
**What happened**:

When I try to create kind cluster with image v1.16.9 or v1.17.0 it gives the following error.
But I can create a cluster with version v1.23.3.

**What you expected to happen**:

Create cluster successfully.

**How to reproduce it (as minimally and precisely as possible)**:

`kind create cluster --image=kindest/node:v1.16.9`
`kind create cluster --image=kindest/node:v1.17.0`

**Anything else we need to know?**:

Logs:

> ❯ kind create cluster --image=kindest/node:v1.17.0
> Creating cluster "kind" ...
>  ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
>  ✓ Preparing nodes 📦
>  ✓ Writing configuration 📜
>  ✗ Starting control-plane 🕹️
> ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
> Command Output: I0212 21:40:20.297423     136 initconfiguration.go:207] loading configuration from "/kind/kubeadm.conf"
> [config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta2, Kind=JoinConfiguration
> W0212 21:40:20.304114     136 validation.go:28] Cannot validate kube-proxy config - no validator is available
> W0212 21:40:20.304162     136 validation.go:28] Cannot validate kubelet config - no validator is available
> [init] Using Kubernetes version: v1.17.0
> I0212 21:40:20.304257     136 kubelet.go:63] Stopping the kubelet
> [kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
> [kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
> [kubelet-start] Starting the kubelet
> [certs] Using certificateDir folder "/etc/kubernetes/pki"
> I0212 21:40:20.377651     136 certs.go:104] creating a new certificate authority for ca
> [certs] Generating "ca" certificate and key
> [certs] Generating "apiserver" certificate and key
> [certs] apiserver serving cert is signed for DNS names [kind-control-plane kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local kind-control-plane localhost] and IPs [10.96.0.1 172.18.0.2 127.0.0.1]
> [certs] Generating "apiserver-kubelet-client" certificate and key
> I0212 21:40:21.383793     136 certs.go:104] creating a new certificate authority for front-proxy-ca
> [certs] Generating "front-proxy-ca" certificate and key
> [certs] Generating "front-proxy-client" certificate and key
> I0212 21:40:21.552722     136 certs.go:104] creating a new certificate authority for etcd-ca
> [certs] Generating "etcd/ca" certificate and key
> [certs] Generating "etcd/server" certificate and key
> [certs] etcd/server serving cert is signed for DNS names [kind-control-plane localhost] and IPs [172.18.0.2 127.0.0.1 ::1]
> [certs] Generating "etcd/peer" certificate and key
> [certs] etcd/peer serving cert is signed for DNS names [kind-control-plane localhost] and IPs [172.18.0.2 127.0.0.1 ::1]
> [certs] Generating "etcd/healthcheck-client" certificate and key
> [certs] Generating "apiserver-etcd-client" certificate and key
> I0212 21:40:22.528452     136 certs.go:70] creating a new public/private key files for signing service account users
> [certs] Generating "sa" key and public key
> I0212 21:40:22.626618     136 kubeconfig.go:79] creating kubeconfig file for admin.conf
> [kubeconfig] Using kubeconfig folder "/etc/kubernetes"
> [kubeconfig] Writing "admin.conf" kubeconfig file
> I0212 21:40:22.854643     136 kubeconfig.go:79] creating kubeconfig file for kubelet.conf
> [kubeconfig] Writing "kubelet.conf" kubeconfig file
> I0212 21:40:23.011853     136 kubeconfig.go:79] creating kubeconfig file for controller-manager.conf
> [kubeconfig] Writing "controller-manager.conf" kubeconfig file
> I0212 21:40:23.162030     136 kubeconfig.go:79] creating kubeconfig file for scheduler.conf
> [kubeconfig] Writing "scheduler.conf" kubeconfig file
> [control-plane] Using manifest folder "/etc/kubernetes/manifests"
> [control-plane] Creating static Pod manifest for "kube-apiserver"
> I0212 21:40:23.383821     136 manifests.go:90] [control-plane] getting StaticPodSpecs
> I0212 21:40:23.394100     136 manifests.go:115] [control-plane] wrote static Pod manifest for component "kube-apiserver" to "/etc/kubernetes/manifests/kube-apiserver.yaml"
> I0212 21:40:23.394150     136 manifests.go:90] [control-plane] getting StaticPodSpecs
> W0212 21:40:23.394453     136 manifests.go:214] the default kube-apiserver authorization-mode is "Node,RBAC"; using "Node,RBAC"
> [control-plane] Creating static Pod manifest for "kube-controller-manager"
> I0212 21:40:23.395565     136 manifests.go:115] [control-plane] wrote static Pod manifest for component "kube-controller-manager" to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
> I0212 21:40:23.395646     136 manifests.go:90] [control-plane] getting StaticPodSpecs
> W0212 21:40:23.395707     136 manifests.go:214] the default kube-apiserver authorization-mode is "Node,RBAC"; using "Node,RBAC"
> [control-plane] Creating static Pod manifest for "kube-scheduler"
> I0212 21:40:23.396490     136 manifests.go:115] [control-plane] wrote static Pod manifest for component "kube-scheduler" to "/etc/kubernetes/manifests/kube-scheduler.yaml"
> [etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
> I0212 21:40:23.397164     136 local.go:69] [etcd] wrote Static Pod manifest for a local etcd member to "/etc/kubernetes/manifests/etcd.yaml"
> I0212 21:40:23.397236     136 waitcontrolplane.go:80] [wait-control-plane] Waiting for the API server to be healthy
> I0212 21:40:23.398433     136 loader.go:375] Config loaded from file:  /etc/kubernetes/admin.conf
> [wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
> I0212 21:40:23.407054     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 2 milliseconds
> I0212 21:40:23.909119     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
> I0212 21:40:24.408866     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
> I0212 21:40:57.390523     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:00.887852     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
> I0212 21:41:02.892965     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> [kubelet-check] Initial timeout of 40s passed.
> [kubelet-check] It seems like the kubelet isn't running or healthy.
> [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
> I0212 21:41:03.387930     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
> I0212 21:41:03.890276     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:04.388515     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:07.389283     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
> I0212 21:41:07.890854     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> [kubelet-check] It seems like the kubelet isn't running or healthy.
> [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
> I0212 21:41:08.387757     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
> I0212 21:41:08.888714     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:16.866702     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:17.366584     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:17.867318     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> [kubelet-check] It seems like the kubelet isn't running or healthy.
> [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
> I0212 21:41:18.365705     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
> I0212 21:41:18.869895     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:30.865911     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
> I0212 21:41:31.371117     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:31.870887     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:32.372091     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:32.867475     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:33.366085     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
> I0212 21:41:33.868114     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> [kubelet-check] It seems like the kubelet isn't running or healthy.
> [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
> I0212 21:41:38.366651     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:51.844061     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
> I0212 21:41:52.345783     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:41:52.845141     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:42:05.344044     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
> I0212 21:42:17.825460     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
> I0212 21:42:18.322138     136 round_trippers.go:443] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
> [kubelet-check] It seems like the kubelet isn't running or healthy.
> [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
> 
> Unfortunately, an error has occurred:
> 	timed out waiting for the condition
> 
> This error is likely caused by:
> 	- The kubelet is not running
> 	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
> 
> If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
> 	- 'systemctl status kubelet'
> 	- 'journalctl -xeu kubelet'
> 
> Additionally, a control plane component may have crashed or exited when started by the container runtime.
> To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
> Here is one example how you may list all Kubernetes containers running in docker:
> 	- 'docker ps -a | grep kube | grep -v pause'
> 	Once you have found the failing container, you can inspect its logs with:
> 	- 'docker logs CONTAINERID'
> couldn't initialize a Kubernetes cluster
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runWaitControlPlanePhase
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:100
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
> k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:147
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
> k8s.io/kubernetes/cmd/kubeadm/app.Run
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
> main.main
> 	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
> runtime.main
> 	/usr/local/go/src/runtime/proc.go:203
> runtime.goexit
> 	/usr/local/go/src/runtime/asm_amd64.s:1357
> error execution phase wait-control-plane
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
> k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:147
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
> k8s.io/kubernetes/cmd/kubeadm/app.Run
> 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
> main.main
> 	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
> runtime.main
> 	/usr/local/go/src/runtime/proc.go:203
> runtime.goexit
> 	/usr/local/go/src/runtime/asm_amd64.s:1357

**Environment:**

- kind version: (use `kind version`): kind v0.11.1 go1.16.4 darwin/amd64
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`): 

> 
> Client:
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   buildx: Docker Buildx (Docker Inc., v0.7.1)
>   compose: Docker Compose (Docker Inc., v2.2.1)
>   scan: Docker Scan (Docker Inc., v0.14.0)
> 
> Server:
>  Containers: 11
>   Running: 2
>   Paused: 0
>   Stopped: 9
>  Images: 346
>  Server Version: 20.10.11
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Cgroup Version: 2
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
>  runc version: v1.0.2-0-g52b36a2
>  init version: de40ad0
>  Security Options:
>   seccomp
>    Profile: default
>   cgroupns
>  Kernel Version: 5.10.76-linuxkit
>  Operating System: Docker Desktop
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 6
>  Total Memory: 7.773GiB
>  Name: docker-desktop
>  ID: 635J:KFLN:CJPL:VAFF:LQ27:N3TR:HOFS:QGMI:7RFK:I7SB:Y3RM:D2QI
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: true
>   File Descriptors: 53
>   Goroutines: 51
>   System Time: 2022-02-12T21:50:55.934806008Z
>   EventsListeners: 3
>  HTTP Proxy: http.docker.internal:3128
>  HTTPS Proxy: http.docker.internal:3128
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false

- OS (e.g. from `/etc/os-release`): macOS Big Sur 11.5.2

**Comment by BenTheElder** [comment]
This is an instance of https://kind.sigs.k8s.io/docs/user/known-issues/#failure-to-create-cluster-with-cgroups-v2

Docker Desktop 4.3.0+ uses cgroupsv2 and cannot run Kubernetes < v1.19.0.

**Comment by BenTheElder** [comment]
This would probably be helpful to document more prominently for the specific case of docker desktop (which is also the case on windows typically) v4.3.0+, people will probably be running into this more frequently in the future. We can't change that Kubernetes < 1.19 lacks the cgroupsv2 changes but we can add a clearer note to the known issues page at least.

**Comment by mstrYoda** [comment]
Thank you @BenTheElder

**Comment by chenmeng1996** [comment]
> 

Is there another way around this if I want to run K8S less than version 1.19?

**Comment by BenTheElder** [comment]
You need an environment that is not cgroups V2. Kubernetes itself does not support cgroupsv2 before 1.19.

You could try creating your own VM with docker.

**Comment by BenTheElder** [comment]
we should add a note about that settings.json option to the known issues entry, thanks @stmcginnis

**Comment by stmcginnis** [comment]
> we should add a note about that settings.json option to the known issues entry

Just submitted https://github.com/kubernetes-sigs/kind/pull/2690 to address this - thanks!
