### ISSUE TITLE
How to configure kind cluster to not start automatically after reboots?

### ISSUE THREAD

**Issue by xjvs** [kubernetes-sigs/kind#2631]
By default, the kind cluster will start automatically after reboots, but I only want to start the cluster by manual when needed, delete-and-create cluster is not an ideal solution because creating a new cluster with other customized setup takes some efforts, I've searched the docs and issues but didn't find such an option, is it possible to change the default behavior or any workaround for this?

I'm also curious about how the cluster get auto started after reboots, I see the `kind-control-plane` container is started when system boost up, but have no idea how it works, seems it's not achieved by docker's `RestartPolicy`, right? 
```
$ docker inspect -f '{{json .HostConfig.RestartPolicy}}' kind-control-plane | jq
{
  "Name": "on-failure",
  "MaximumRetryCount": 1
}
```
Additional info:
Kernel Version: 5.16.8-200.fc35.x86_64
Operating System: Fedora Linux 35 (Workstation Edition)
docker/moby-engine: 20.10.12 (moby-engine-20.10.12-1.fc35.x86_64)
kind: kind v0.11.1 go1.16.8 linux/amd64

**Comment by BenTheElder** [comment]
> but I only want to start the cluster by manual when needed

Sorry, this is not supported.

> I'm also curious about how the cluster get auto started after reboots, I see the kind-control-plane container is started when system boost up, but have no idea how it works, seems it's not achieved by docker's RestartPolicy, right?

It is achieved by docker's restart policy.

Here's a detailed comment explaining why the current policy is used:
https://github.com/kubernetes-sigs/kind/blob/c117f59cb4ec7479f5693e770523c89b3fd59459/pkg/cluster/internal/providers/docker/provision.go#L142-L166

**Comment by xjvs** [comment]
@BenTheElder thank you for your reply.

> It is achieved by docker's restart policy.

Good to know, then it should be easy to hack my environment to make it not auto-start :)
I'm closing this issue.

**Comment by lapwat** [comment]
```
docker update --restart=no container-id
```
