### ISSUE TITLE
Ingress not getting created

### ISSUE THREAD

**Issue by EGNSIUR** [kubernetes-sigs/kind#2635]
Docker version 20.10.11, build dea9396

os: windows

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T
15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T
23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
-------------------------------------------------------------------------------------------------------------------------------

**usage.yml file
highlighted part is not getting created**
kind: Pod
apiVersion: v1
metadata:
  name: foo-app
  labels:
    app: foo
spec:
  containers:
  - name: foo-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=foo"
---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  selector:
    app: foo
  ports:
  # Default port used by the image
  - port: 5678
---
kind: Pod
apiVersion: v1
metadata:
  name: bar-app
  labels:
    app: bar
spec:
  containers:
  - name: bar-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=bar"
---
kind: Service
apiVersion: v1
metadata:
  name: bar-service
spec:
  selector:
    app: bar
  ports:
  # Default port used by the image
  - port: 5678
---
**apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: foo-service
            port:
              number: 5678
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: bar-service
            port:
              number: 5678**
---

---------------------------------------------------------------------------------------------------------------------------
**error when applying ingress file which is part of usage.yml **
$ kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml
pod/foo-app created
service/foo-service created
pod/bar-app created
service/bar-service created
Error from server (InternalError): error when creating "https://kind.sigs.k8s.io/examples/ingress/usage.yaml": Internal error occurred: failed calling webhook "validate.ngi
nx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": dial tcp 10.96.50.193:443: connect:
connection refused

---------------------
_**ingress controller**_

$ kubectl get po -n ingress-nginx
NAME                                        READY   STATUS      RESTARTS   AGE
ingress-nginx-admission-create-bgb6z        0/1     Completed   0          42m
ingress-nginx-admission-patch-458hs         0/1     Completed   1          42m
ingress-nginx-controller-674cb6ff57-9r9mw   0/1     Pending     0          42m
----------------------
_** timeout error from ingress controller**_

$ kubectl wait --namespace ingress-nginx \
  --for=condition=ready pod \
  --selector=app.kubernetes.io/component=controller \
  --timeout=90s
error: timed out waiting for the condition on pods/ingress-nginx-controller-674cb6ff57-9r9mw
-----------------------
**description of one pod of ingress controller which is in pending state**
$ kubectl describe po -n ingress-nginx ingress-nginx-controller-674cb6ff57-9r9mw
Name:           ingress-nginx-controller-674cb6ff57-9r9mw
Namespace:      ingress-nginx
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/component=controller
                app.kubernetes.io/instance=ingress-nginx
                app.kubernetes.io/name=ingress-nginx
                pod-template-hash=674cb6ff57
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/ingress-nginx-controller-674cb6ff57
Containers:
  controller:
    Image:       k8s.gcr.io/ingress-nginx/controller:v1.1.1@sha256:0bc88eb15f9e7f84e8e56c14fa5735aaa488b840983f87bd79b1054190e660de
    Ports:       80/TCP, 443/TCP, 8443/TCP
    Host Ports:  80/TCP, 443/TCP, 0/TCP
    Args:
      /nginx-ingress-controller
      --election-id=ingress-controller-leader
      --controller-class=k8s.io/ingress-nginx
      --configmap=$(POD_NAMESPACE)/ingress-nginx-controller
      --validating-webhook=:8443
      --validating-webhook-certificate=/usr/local/certificates/cert
      --validating-webhook-key=/usr/local/certificates/key
      --watch-ingress-without-class=true
      --publish-status-address=localhost
    Requests:
      cpu:      100m
      memory:   90Mi
    Liveness:   http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=5
    Readiness:  http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:       ingress-nginx-controller-674cb6ff57-9r9mw (v1:metadata.name)
      POD_NAMESPACE:  ingress-nginx (v1:metadata.namespace)
      LD_PRELOAD:     /usr/local/lib/libmimalloc.so
    Mounts:
      /usr/local/certificates/ from webhook-cert (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w5kph (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  webhook-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-nginx-admission
    Optional:    false
  kube-api-access-w5kph:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              ingress-ready=true
                             kubernetes.io/os=linux
Tolerations:                 node-role.kubernetes.io/master:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  7s (x49 over 45m)  default-scheduler  0/3 nodes are available: 3 node(s) didn't match Pod's node affinity/selector.
------------------------------------

----------------------------

**Comment by aojea** [comment]
please format correctly the description, is not really easy to read it :smile:

**Comment by BenTheElder** [comment]
This is pretty difficult to read, there's a little `< >` icon at the top of github comment editor that allows inserting a code block for formatting literal text / code snippets.

How did you install the ingress? Did you follow https://kind.sigs.k8s.io/docs/user/ingress/ ?

**Comment by EGNSIUR** [comment]
![image](https://user-images.githubusercontent.com/73429040/155387105-4d424b43-7bfa-44c4-be5c-1f655ecc7a39.png)

![image](https://user-images.githubusercontent.com/73429040/155387284-62be9b8e-511e-4bfa-b87f-2e32235c9fe2.png)
 ingress_deploy.yml is taken from here except host port is changed w.r.t cluster file
 
 
![image](https://user-images.githubusercontent.com/73429040/155387492-7066475a-3121-4da0-a8b2-a935bc088871.png)

![image](https://user-images.githubusercontent.com/73429040/155387605-65ee40ee-2596-4187-9f61-0db1424053b0.png)

ISSUE:
$ curl localhost:82/foo
curl: (52) Empty reply from server

**Comment by BenTheElder** [comment]
you have mapped 82 on the host to 80 in the kind container, but then you have 82 to 80 also for the pod.

that won't work, they are different "hosts", the host machine, and the kind node container. as far as kubernetes is concerned the network inside the node container is the "host", and that port should match the containerPort on the extraPortMappings

**Comment by BenTheElder** [comment]
if you follow the instructions from the guide exactly the ports will align
if you want a different port on your host, you can change only the hostPort fields in the kind config, and nothing else.

**Comment by EGNSIUR** [comment]
okay, understood,
it should be like this right?
port1-------->port2
port2--------->port3
thanks for support!!

**Comment by BenTheElder** [comment]
Yes, that's it. 👍 

HostPort in kind config --> mapped to containerPort in kind config

container port in Kind config should match nodePort in ingress installation

then the nodePort should be pointed to an ingress implementation, the ingress object should be configured to point to the application deployment/port, which are unrelated to the above ports.

**Comment by EGNSIUR** [comment]
I updated my controller config and using directly from the link which is having below ports defined.
![image](https://user-images.githubusercontent.com/73429040/158443446-5a42cb18-597e-41b5-b646-3fd715770149.png)

ports in my kind config: 
      - containerPort: 80
        hostPort: 81
        protocol: TCP
      - containerPort: 443
        hostPort: 82
        protocol: TCP 

I am still getting empty reply,
$ curl localhost:81/foo
curl: (52) Empty reply from server


Additional details:

![image](https://user-images.githubusercontent.com/73429040/158443952-8f0ef1cc-0103-4545-987a-cebdab6e058d.png)


![image](https://user-images.githubusercontent.com/73429040/158444038-9a016234-51a0-4e6c-a193-82f8d87280ef.png)

**Comment by BenTheElder** [comment]
You may have more luck with an interactive thread with our user community in #kind in https://slack.k8s.io

Sorry I haven't had the bandwidth to follow up on this further.

I *highly* suggest starting with getting *Exactly* the ingress guide working first, and _then_ altering towards your desired config from there. The ingress guide contents should work.
