### ISSUE TITLE
Volume does not mount on KiND

### ISSUE THREAD

**Issue by kconde2** [kubernetes-sigs/kind#2636]
Hello everyone, 

I would like to know if anyone has used longHorn storage on kind (https://kind.sigs.k8s.io/).

When I create a volume it constantly switches between "attached" and "detached" and the volume never goes up.

I have same problem as described here :
https://longhorn.io/kb/troubleshooting-volume-pvc-xxx-not-scheduled/

Do you know if there are specific things to do with it to make it work?

Thanks in advance

**Comment by aojea** [comment]
should be better to ask on the longhorn project?

**Comment by BenTheElder** [comment]
I think the discussion there seems more helpful, we're not familiar with longhorn and can't really comment on requirements for that project. I've commented on https://github.com/longhorn/longhorn/issues/3643 regarding kind limitations however.
