### ISSUE TITLE
Can support user-defined kind images?

### ISSUE THREAD

**Issue by MinvenX** [kubernetes-sigs/kind#2639]
**What would you like to be added**:
- Let user install some components in kind cluster and repack as a new image. Then, we can launch it by kind anywhere

**Why is this needed**:
   Kind is a convenient tool when we want to run app or install component in k8s cluster. But sometimes we need to customize the kind image and start the kind cluster on different machines, instead of starting the kind cluster on each machine and installing custom components one by one

**Comment by aojea** [comment]
You can already build your images inheriting the kind node image and using docker build
Per example
https://gist.github.com/aojea/bd1fb766302779b77b8f68fa0a81c0f2#file-dockerfile

**Comment by BenTheElder** [comment]
/triage duplicate
https://github.com/kubernetes-sigs/kind/issues/2160
