### ISSUE TITLE
Got security vulnerabilities alert from github when import sigs.k8s.io/kind v0.11.1 

### ISSUE THREAD

**Issue by XudongLiuHarold** [kubernetes-sigs/kind#2643]
**What happened**:

I got `We found potential security vulnerabilities in your dependencies` alert when I import `sigs.k8s.io/kind v0.11.1` in my go project.

![Imgur](https://i.imgur.com/JQitr7Q.png)

**What you expected to happen**:

No security vulnerabilities after run `go get sigs.k8s.io/kind`

**How to reproduce it (as minimally and precisely as possible)**:

run `go get sigs.k8s.io/kind` in your repo.

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by BenTheElder** [comment]
I don't think you got this importing kind, github.com/docker/docker is not a dependency of kind @ v0.11.1, not even transitively.

https://github.com/kubernetes-sigs/kind/blob/6a69d867676798bf9d9de0b39a2ac6d33f9935ee/go.sum

**Comment by XudongLiuHarold** [comment]
I think it should because this one: https://github.com/kubernetes-sigs/kind/blob/6a69d867676798bf9d9de0b39a2ac6d33f9935ee/go.sum#L47 ?

I don't have any docker dependencies in my `go.mod` file except this one.

**Comment by BenTheElder** [comment]
github.com/docker/spdystream does not import docker/docker, it would be in the go.sum if it did.

**Comment by BenTheElder** [comment]
Are you able to link to your project? You can also check `go mod why github.com/docker/docker`.

**Comment by XudongLiuHarold** [comment]
O, sorry, false alarm, that's another package I am importing, thanks @BenTheElder ! Close this one.

/close
