### ISSUE TITLE
warn or fail for unknown configuration fields

### ISSUE THREAD

**Issue by pohly** [kubernetes-sigs/kind#2644]
**What would you like to be added**:

The default is to silently ignore unknown fields in the configuration file given with `kind create --config`. Also, patches inside the configuration that don't match any resource are silently ignored. This behavior is consistent with Kubernetes practices and cannot be changed.

What I'd like to see is that:
- there is a warning in the output when parts of the configuration are ignored; this should be on by default, with a command line flag to turn it off: `--warn-unused-configuration` (default true)
- users can opt into a hard failure when this happens: `--error-unused-configuration` (default false)

**Why is this needed**:

As it stands right now, it is very easy to make mistakes when writing a configuration file (simple typo, not knowing the exact version of kubeadm resources, etc.) which then make it very hard to debug why things are not working as expected.

**Comment by pohly** [comment]
I can try to come up with a patch if there is consensus that this would be useful.

**Comment by BenTheElder** [comment]
> The default is to silently ignore unknown fields in the configuration file given with kind create --config. 

Hmm, that shouldn't be the case? I specifically made an effort to ensure we UnmarshalStrict, it was actually one of the reasons we migrated off of api-machinery tooling (strict parsing was stuck there for some time...)

https://github.com/kubernetes-sigs/kind/blob/ee6c4187e1a749ef60093ca1ffe51005b5a20c2b/pkg/internal/apis/config/encoding/load.go#L72

Do you have a reproducer?

> Also, patches inside the configuration that don't match any resource are silently ignored. This behavior is consistent with Kubernetes practices and cannot be changed.

Yeah, If we don't allow patches to resources that don't match it will be hard to write e.g. patches simply applied at the cluster level instead of per-node.

**Comment by pohly** [comment]
> Hmm, that shouldn't be the case?

You are right of course. I hadn't actually tested it and was expecting it because of your comment about patches intentionally be ignored silently. I thought the rationale for that was consistency with config parsing but ...

> If we don't allow patches to resources that don't match it will be hard to write e.g. patches simply applied at the cluster level instead of per-node.

... this makes more sense.

So would a `--unused-patches=ignore|warn|error` flag make sense, with `ignore` as default? Or perhaps `notify` (or `log` or `info`) for normal info message? That could become the default.

**Comment by BenTheElder** [comment]
I think increasing the verbosity shows enough detail to tell this, in that it prints the generated kubeadm config used, and you get kubeadm output including warnings from kubeadm about unused config.

I would prefer to keep kind relatively independent of kubernetes/kubernetes changes where possible (we don't import even staging repos in to the main binary, only in `kindnetd`), and without bringing in the kubeadm + kubelet types I don't see how we can know if a field will be used (and we have chicken and egg issue with type changes in k/k).

**Comment by pohly** [comment]
Okay, let's keep this as-is.

/close

**Comment by neolit123** [comment]
> As it stands right now, it is very easy to make mistakes when writing a configuration file (simple typo, not knowing the exact version of kubeadm resources, etc.) which then make it very hard to debug why things are not working as expected.

Kubernetes inherited some Golang structured format parsing problems such as the lack of sophisticated error reporting in encoding/json and other libraries.

This results in sparse support tickets from private users and customers. The saner option has always been to enable strict parsing of user data, if possible.
