### ISSUE TITLE
Cannot access registry.docker.io from worker nodes on WSL2 Debian 11

### ISSUE THREAD

**Issue by arundeep78** [kubernetes-sigs/kind#2645]
**What happened**:
 registry.docker.io and registry-1.docker.io are not reachable from worker nodes. Due to this deployments does not work. e.g. helm install airflow fails with below error

"Failed to pull image "redis:6-buster": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/redis:6-buster": failed to resolve reference "docker.io/library/redis:6-buster": failed to do request: Head "https://registry-1.docker.io/v2/library/redis/manifests/6-buster": dial tcp: lookup registry-1.docker.io on 172.19.0.1:53: no such host"

Please let me know, if you need any further information. 
I must say, this is a new environment for me and I found this issue while trying to learn [how to setup airflow on Kubernetes using Kind](https://airflow.apache.org/docs/helm-chart/stable/quick-start.html).

**What you expected to happen**:
Would expect that docker registry is reachable from worker node and deployments works.

**How to reproduce it (as minimally and precisely as possible)**:
kind create cluster --image kindest/node:v1.20.7
helm repo add apache-airflow https://airflow.apache.org
helm repo update
kubectl create namespace test
helm install test-airflow apache-airflow/airflow --namespace test

**Anything else we need to know?**:
Node has access to internet and reach google, yahoo and other sites. problem seems to be very specific trying to resolve registry.docker.io and registry-1.docker.io
`ping registry.docker.io
ping: registry.docker.io: Temporary failure in name resolution`

`ping registry-1.docker.io
PING registry-1.docker.io (34.200.175.181) 56(84) bytes of data.`

`traceroute registry.docker.io
registry.docker.io: Name or service not known
Cannot handle "host" cmdline arg registry.docker.io on position 1 (argc 1)`

`traceroute registry-1.docker.io
registry-1.docker.io: No address associated with hostname
Cannot handle "host" cmdline arg `registry-1.docker.io' on position 1 (argc 1)`

I have document various network information on the [github repo](https://github.com/arundeep78/wsl_debian_dev/blob/master/Kind_k8s_Readme.md#check-internet-access-from-nodes).
I have kept it logged in case it is needed and helpful, even though I do not understand all of it.

**Environment:**

- kind version: (use `kind version`): kind v0.11.1 go1.16.4 linux/amd64
- Kubernetes version: (use `kubectl version`): client 1.23, server 1.20
- Docker version: (use `docker info`):  Server Version: 20.10.12. running inside WSL and not as Docker desktop on Windows.
- OS (e.g. from `/etc/os-release`): "Debian GNU/Linux 11 (bullseye)" running on WSL2 on WIndows 11

**Comment by BenTheElder** [comment]
Does your environment have a proxy?

This is difficult to debug non-intetactively. I can tell you many other users pull images in WSL2, it is most likely something specific to your environment.

**Comment by arundeep78** [comment]
Well, I have not configured any proxy by myself. Also that I can reach these addresses from Windows, WSL2 Debian, an alpine or Ubuntu image running in docker (which runs in WSL2). 

Even from this Kind cluster the worker node (docker container) can access google, yahoo and k8s.gcr.io. In the [link I gave above](https://github.com/arundeep78/wsl_debian_dev/blob/master/Kind_k8s_Readme.md#wsl-host-information), I have tried to capture all networking information and traces that I could think of. 

As I mentioned earlier, I get errors when reaching to registry.docker.io and registry-1.docker.io. 
However, when I use `dig` to get DNS info, I do get IP addresses.

Also that ping to registry-1.docker.io gives and IP address. traceroute to that IP works, but traceroute to registry-1.docker.io does not work!

The only proxy I can think of is the kube-proxy that is running in kind cluster.

Any hint or ideas to investigate further would also help

**Comment by aojea** [comment]
https://github.com/docker/for-win/issues/6837 seems similar

**Comment by arundeep78** [comment]
Thanks. I will look into those threads. However, initial read points 2 differences.

1. I can pull images from WSL2 (with native docker engine installed). There is no Docker desktop install.
```
docker images
REPOSITORY     TAG       IMAGE ID       CREATED        SIZE
kindest/node   <none>    b3dd68fe0a8c   2 months ago   1.46GB
hello-world    latest    feb5d9fea6a5   5 months ago   13.3kB
kindest/node   <none>    14c4b042989b   9 months ago   1.08GB

docker pull nginx
Using default tag: latest
latest: Pulling from library/nginx
5eb5b503b376: Pull complete
1ae07ab881bd: Pull complete
78091884b7be: Pull complete
091c283c6a66: Pull complete
55de5851019b: Pull complete
b559bad762be: Pull complete
Digest: sha256:2834dc507516af02784808c5f48b7cbe38b8ed5d0f4837f16e78d00deb7e7767
Status: Downloaded newer image for nginx:latest
docker.io/library/nginx:latest
```

2. No sudo is required in WSL2. it just works with default user.
3. traceroute from this sample nginx also works to registry.docker.io and registry-1.docker.io. 
```
root@68e52645ba53:/# traceroute registry.docker.io
traceroute to registry.docker.io (52.200.78.26), 30 hops max, 60 byte packets
 1  172.17.0.1 (172.17.0.1)  0.043 ms  0.010 ms  0.003 ms
 2  arunpc.mshome.net (172.25.112.1)  0.236 ms  0.222 ms  0.216 ms

root@68e52645ba53:/# traceroute registry-1.docker.io
traceroute to registry-1.docker.io (52.72.186.182), 30 hops max, 60 byte packets
 1  172.17.0.1 (172.17.0.1)  0.034 ms  0.004 ms  0.003 ms
 2  arunpc.mshome.net (172.25.112.1)  0.555 ms  0.539 ms  0.535 ms
```
3. Atleast that seems to suggest that in a normal way images can be pulled from
   1. Windows
   2. WSL2 with docker engine installed inside WSL without Docker desktop
4. Also that registry.docker.com and registry-1.docker.com are reachable from containers running using this setup.

This networking issue comes up when I create a cluster using Kind. The docker container started with `kind create cluster` somehow has this networking issue. 

If it was with router/ISP configuration (as suggested in the suggested link), should it not have same problem from windows and WSL and other non-Kind containers?

The difference I see is that the container image created directly with docker like nginx above points directly to WSL2 IP as DNS

```
root@68e52645ba53:/# cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.25.112.1 # WSL IP on windows
```
However, the one created by Kind has one extra step

```
root@kind-test-worker:/# cat /etc/resolv.conf
nameserver 172.19.0.1 # IP of WSL2 machine which in turn routes to WSL2 Ip on windows
options ndots:0
```
But this extra step of routing seem to work fine for other hosts in Kind container, but just not registry.docker.io

```
root@kind-test-worker:/# traceroute k8s.gcr.io
traceroute to k8s.gcr.io (142.251.18.82), 30 hops max, 60 byte packets
 1  172.19.0.1 (172.19.0.1)  0.193 ms  0.014 ms  0.005 ms               # IP created on WSL2 by Kind which is in /etc/resolv.conf for kind container
 2  arunpc.mshome.net (172.25.112.1)  0.234 ms  0.214 ms  0.207 ms # WSL2 IP on windows
 3  speedport.ip (192.168.1.1)  2.635 ms  2.583 ms  2.585 ms   # My router
```

Investigation continues...

**Comment by BenTheElder** [comment]
> nameserver 172.19.0.1 # IP of WSL2 machine which in turn routes to WSL2 Ip on windows

This IP we're just redirecting to the docker DNS server with iptables in the node network namespace.

The actual resolver behind the iptables rules is the standard resolver docker injects into the container when the container is on any docker network other than the default bridge.

We need the IP to appear different because normally it's a loopback address that would not be reachable by pods.

**Comment by arundeep78** [comment]
@BenTheElder pardon my ignorance of all the network terminology. 

I understand that you are just pointing out that extra IP provided in Kind is needed and it should not create a problem as DNS resolution is happening at the end by whatever DNS docker is using on the "Kind host" .

If that is the case, I am aligned with that. What I was trying to point above is that in comparison to starting a normal Docker linux container, this is the difference that I could see at network level.

However, as far as DNS is concerned it seems to work fine for pretty much all of the primary internet addresses e.g. `yahoo.com`, `google.com`. I added above a traceroute to `k8s.gcr.io`. They all seems to get resolved and find their path to the actual servers. Problem happens only in the case of docker registry ( well did not try all the possible internet addresses).

When I do a `dig` on the node, it does list IP addresses. But somehow traceroute or ping or other application do not get those IPs. 

## Dig on kind node 
```zsh
root@kind-test-worker:/# dig registry.docker.io

; DiG 9.16.8-Ubuntu  registry.docker.io
;; global options: +cmd
;; Got answer:
;; -HEADER- opcode: QUERY, status: NOERROR, id: 40316
;; flags: qr rd ad; QUERY: 1, ANSWER: 16, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;registry.docker.io.            IN      A

;; ANSWER SECTION:
registry.docker.io.     0       IN      CNAME   registry-1.docker.io.
ReGiSTry-1.docker.io.   0       IN      A       34.196.250.152
ReGiSTry-1.docker.io.   0       IN      A       52.0.218.102
ReGiSTry-1.docker.io.   0       IN      A       54.197.112.205
ReGiSTry-1.docker.io.   0       IN      A       52.202.132.224
ReGiSTry-1.docker.io.   0       IN      A       52.205.127.201
ReGiSTry-1.docker.io.   0       IN      A       52.72.186.182
ReGiSTry-1.docker.io.   0       IN      A       44.196.236.180
ReGiSTry-1.docker.io.   0       IN      A       52.72.252.48
ns-1168.awsdns-18.org.  0       IN      A       205.251.196.144
ns-1827.awsdns-36.co.uk. 0      IN      A       205.251.199.35
ns-421.awsdns-52.com.   0       IN      A       205.251.193.165
ns-513.awsdns-00.net.   0       IN      A       205.251.194.1
ns-1168.awsdns-18.org.  0       IN      AAAA    2600:9000:5304:9000::1
ns-1827.awsdns-36.co.uk. 0      IN      AAAA    2600:9000:5307:2300::1
ns-421.awsdns-52.com.   0       IN      AAAA    2600:9000:5301:a500::1

;; Query time: 29 msec
;; SERVER: 172.19.0.1#53(172.19.0.1)
;; WHEN: Wed Feb 23 11:20:52 UTC 2022
;; MSG SIZE  rcvd: 432
```
## Dig on docker host
```zsh
$dig registry.docker.io

 DiG 9.16.22-Debian  registry.docker.io
;; global options: +cmd
;; Got answer:
;; -HEADER- opcode: QUERY, status: NOERROR, id: 57336
;; flags: qr rd ad; QUERY: 1, ANSWER: 16, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;registry.docker.io.            IN      A

;; ANSWER SECTION:
registry.docker.io.     0       IN      CNAME   registry-1.docker.io.
registry-1.docker.io.   0       IN      A       54.86.228.181
registry-1.docker.io.   0       IN      A       54.210.12.153
registry-1.docker.io.   0       IN      A       52.72.186.182
registry-1.docker.io.   0       IN      A       34.203.135.183
registry-1.docker.io.   0       IN      A       52.0.218.102
registry-1.docker.io.   0       IN      A       52.200.37.142
registry-1.docker.io.   0       IN      A       34.200.175.181
registry-1.docker.io.   0       IN      A       52.202.132.224
ns-1168.awsdns-18.org.  0       IN      A       205.251.196.144
ns-1827.awsdns-36.co.uk. 0      IN      A       205.251.199.35
ns-421.awsdns-52.com.   0       IN      A       205.251.193.165
ns-513.awsdns-00.net.   0       IN      A       205.251.194.1
ns-1168.awsdns-18.org.  0       IN      AAAA    2600:9000:5304:9000::1
ns-1827.awsdns-36.co.uk. 0      IN      AAAA    2600:9000:5307:2300::1
ns-421.awsdns-52.com.   0       IN      AAAA    2600:9000:5301:a500::1

;; Query time: 50 msec
;; SERVER: 172.25.112.1#53(172.25.112.1)
;; WHEN: Tue Feb 22 23:53:44 CET 2022
;; MSG SIZE  rcvd: 532
```

Any thing that can help further investigate to find the root cause of it?

**Comment by aojea** [comment]
> I have no idea what solved it, but at the moment I cannot reproduce this issue.

lol 

![image](https://user-images.githubusercontent.com/6450081/157431510-fb13b076-f178-4f1e-b1b1-c123ac39b480.png)

**Comment by arundeep78** [comment]
it would have been different, if it worked after a restart. I tried all layers of restart
1. restart of cluster
2. different node image version
3. restart of docker service
4. restart of wsl image
5. restart of whole wsl engine
6. restart of windows!!!

Anyways, I like this perspective more :grin:

![download](https://user-images.githubusercontent.com/24549972/157757959-43c7d071-6270-44d2-b77f-5139e111af9f.jpg)

Time to 🧘 ....

**Comment by arundeep78** [comment]
Marking this issue as closed as for now kind cluster and further software installations can connect with docker now. Thanks for all who spent some time to share their inputs and perspectives.

**Comment by owos** [comment]
Hi, Please I think you need to reopen this issue again. I have been struggling with the same problem but I haven't found any solution yet. 
When I try to describe my pods hosted on Kind, this is what I get:
`Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  104s               default-scheduler  Successfully assigned demo/webstuff-7d9f8f59b8-4bcxh to kind-control-plane
  Normal   BackOff    17s (x5 over 96s)  kubelet            Back-off pulling image "nginx"
  Warning  Failed     17s (x5 over 96s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    3s (x4 over 96s)   kubelet            Pulling image "nginx"
  Warning  Failed     3s (x4 over 96s)   kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to resolve reference "docker.io/library/nginx:latest": failed to do request: Head "https://registry-1.docker.io/v2/library/nginx/manifests/latest": dial tcp: lookup registry-1.docker.io: No address associated with hostname`

I'm really stranded right now.

**Comment by SpockCoding** [comment]
have someone have success to solve that issue ?

**Comment by BenTheElder** [comment]
@owos your appears to be a DNS issue, we'd need more information about the host environment to begin debugging

@SpockCoding the author did, which is why it's closed. Please file a new issue following the bug template if you'd like us to help try to figure out your problem.

**Comment by omichels** [comment]
I find that i have found the correct workaround for this bug: Switching IPTables to legacy mode has fixed this for me.

https://github.com/docker/for-linux/issues/1406#issuecomment-1183487816

**Comment by BenTheElder** [comment]
@omichels this might be a variant on the recently discovered #3054 was the host using iptables 1.8.8+?
