### ISSUE TITLE
[wsl2] [nfs] MountVolume.SetUp failed for volume "pvc-759e2292-6938-4b8e-b6e3-67bbf9b7b904" : mount failed: exit status 32

### ISSUE THREAD

**Issue by uneabh** [kubernetes-sigs/kind#2648]
Hi Team,

I am facing the issue of attaching the volume. to the pod I am getting the following error
**Warning FailedMount 110s kubelet MountVolume.SetUp failed for volume "pvc-759e2292-6938-4b8e-b6e3-67bbf9b7b904" : mount failed: exit status 32**

Basically, we are using wsl2 on windows 10 to make it local development environment where you could deploy our own dev k8 cluster with multiple node with the help of helm,kind,docker amd kubectl..

we have created script files through which we run the commands to pull the images and also to create the cluster using kind.

In our case the cluster is getting created on kind. The pod for nfs is in running state ,but the other pod is not running and its in container creating state. we also able to get the information from po,pv an pvc of this particular namespace in which pods are running. but when I am describing the pod(the one in containercreating) it gives me the mount failed error which I have mentioned above.

For this issue I also installed the nfs-common inside the kind containers, but I am getting the same issue. Attaching the describe pod command output below

[describe_podoutput.txt](https://github.com/kubernetes-sigs/kind/files/8175930/describe_podoutput.txt)

**Comment by BenTheElder** [comment]
can you share more details like:
- how did you configure NFS
- what kind version and exact kind command / node image are you using?

> For this issue I also installed the nfs-common inside the kind containers, but I am getting the same issue. Attaching the describe pod command output below

nfs-common is already installed in current kind versions 🤔

**Comment by uneabh** [comment]
1) Configuring NFS: In the script file we are providing the command to install nfs server by adding it to repo and installing with helm which looks like this:

Command:
helm install nfs-provisioner stable/nfs-server-provisioner --namespace $NAMESPACE \
--set=persistence.size=500Mi,  

after this command we have command to create PV using the .pvc file which is:
kubectl create -f pvc.yaml in whichwe are creating pvc and the storage class name in here is "NFS"

2) Kind version we are using is : kind v0.8.1
   We are creating kind cluster using create kind cluster by providing config.yaml file. In there we are using "apiVersion: kind.x-k8s.io/v1alpha4"


3) Other environment details:
Windows version: 
               64 bit windows 10
WSL: 
           version:2
           Distro name: Ubuntu
           Distributor ID: Ubuntu
           Description:    Ubuntu 20.04.4 LTS
          Release:        20.04
         Codename:       focal

**Comment by BenTheElder** [comment]
> Kind version we are using is : kind v0.8.1


Please upgrade, this is your problem.

**Comment by uneabh** [comment]
Hi,  I updated the kind  version to your latest version that is [v0.12.0]. because, firstly I updated it with v0.11.1 which is current recommended stable version and it gave me the error . So , my question is , if its okay to use v0.12.0 , because this is the version which solved my issue

**Comment by BenTheElder** [comment]
v0.12.0 is just as stable as v0.11.1 we just neglected to update the docs 🙃

**Comment by zaunist** [comment]
> 

Hi, @BenTheElder. I will to update the docs if needed.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/2676 thanks!
