### ISSUE TITLE
Be able to load local image based on sha

### ISSUE THREAD

**Issue by mitar** [kubernetes-sigs/kind#2659]
**What would you like to be added**:

It seems it is not possible to reference an image with `@sha` suffix from the local machine to make sure exactly wanted image is loaded. So if you do `kind load docker-image …@sha…` it currently says "not found".

**Why is this needed**:

While debugging issues with your app inside a Docker image, it is useful to exactly know you are loading what you intended. Moreover, this assures that the image is loaded locally and not from a remote repository.

**Comment by BenTheElder** [comment]
Please see also https://github.com/kubernetes-sigs/kind/issues/2394

**Comment by mitar** [comment]
This seems to be duplicate of https://github.com/kubernetes-sigs/kind/issues/2394.
