### ISSUE TITLE
document how to use HA

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/kind#266]
mostly document how to to use the config for HA at this point.
/assign
/kind documentation
/priority important-soon

**Comment by neolit123** [comment]
will add a small config example for HA somewhere under here, once alpha3 is done:
https://kind.sigs.k8s.io/docs/user/quick-start/#configuring-your-kind-cluster

**Comment by tao12345666333** [comment]
#373 has been merged. :+1:  
Maybe we can add config example for HA.

**Comment by neolit123** [comment]
will do tomorrow. :+1:

**Comment by tao12345666333** [comment]
> EDIT: i suggest we add this to the 0.2.0 milestone?

+1
