### ISSUE TITLE
kind load docker-image should add a tag instead of loading the image when possible

### ISSUE THREAD

**Issue by jorsol** [kubernetes-sigs/kind#2663]
**What happened**:
Loading the same image with different tag loads the image again to kind:

```bash
$ kind load docker-image demo/demo1:v1
Image: "demo/demo1:v1" with ID "sha256:e9d87b36eeece1dac52c002a35d75205bdc4ea142e091f6b45861a78afbfb839" not yet present on node "kind-control-plane", loading...
$ kind load docker-image demo/demo1:latest
Image: "demo/demo1" with ID "sha256:e9d87b36eeece1dac52c002a35d75205bdc4ea142e091f6b45861a78afbfb839" not yet present on node "kind-control-plane", loading...
```

**What you expected to happen**:
An image with the same hash (`sha256:e9d87b36eeece1dac52c002a35d75205bdc4ea142e091f6b45861a78afbfb839` in the previous example) should only need to add a "tag" instead of loading the image again.

Something like this should be expected:
Image: ID "sha256:e9d87b36eeece1dac52c002a35d75205bdc4ea142e091f6b45861a78afbfb839" found to be already present on all nodes, creating tag for "demo/demo1" .

**How to reproduce it (as minimally and precisely as possible)**:
```bash
$ kind load docker-image demo/demo1:v1
Image: "demo/demo1:v1" with ID "sha256:e9d87b36eeece1dac52c002a35d75205bdc4ea142e091f6b45861a78afbfb839" not yet present on node "kind-control-plane", loading...
$ kind load docker-image demo/demo1:latest
Image: "demo/demo1" with ID "sha256:e9d87b36eeece1dac52c002a35d75205bdc4ea142e091f6b45861a78afbfb839" not yet present on node "kind-control-plane", loading...
```

**Environment:**

- kind version: (use `kind version`): 0.12.0
- Kubernetes version: (use `kubectl version`): v1.23.4
- Docker version: (use `docker info`): 20.10.7
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.4 LTS

**Comment by jorsol** [comment]
Yes, it happens with other tags.

**Comment by aojea** [comment]
I can reproduce it, 

The image hash on the nodes is obtained 

https://github.com/kubernetes-sigs/kind/blob/91cc28782d7343dc1547c3d40e7136fd24ed5ddc/pkg/cluster/nodeutils/util.go#L112-L117

the image id on kind is

https://github.com/kubernetes-sigs/kind/blob/91cc28782d7343dc1547c3d40e7136fd24ed5ddc/pkg/cmd/kind/load/docker-image/docker-image.go#L190-L194

and this is the loop that checks

https://github.com/kubernetes-sigs/kind/blob/91cc28782d7343dc1547c3d40e7136fd24ed5ddc/pkg/cmd/kind/load/docker-image/docker-image.go#L132-L137

is it possible that is erroring?

/help wanted

**Comment by BenTheElder** [comment]
> is it possible that is erroring?

No @aojea, we need to load the image again to load the tag. FWIW container will skip actually importing existing layers, but we do still have to export them from docker.

At the time `kind load` was implemented, containerd ctr lacked any command to add a tag.

> An image with the same hash (sha256:e9d87b36eeece1dac52c002a35d75205bdc4ea142e091f6b45861a78afbfb839 in the previous example) should only need to add a "tag" instead of loading the image again.

There is a command for tagging in CTR now but you'd have to feature detect it because older kind images will lack it.

Enhancing image loading is a feature.

**Comment by BenTheElder** [comment]
thanks @harshanarayana !!
