### ISSUE TITLE
unable to resolve node name most of the time

### ISSUE THREAD

**Issue by prashant-shahi** [kubernetes-sigs/kind#2667]
**What happened**:

DNS resolver for _kind_ node name often does not work.

**What you expected to happen**:

Expected to resolve the node name always*.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
$ k get node -o wide
NAME                 STATUS   ROLES                  AGE   `VERSION`   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
kind-control-plane   Ready    control-plane,master   23h   v1.21.1   192.168.192.2   <none>        Ubuntu 21.04   5.13.0-30-generic   containerd://1.5.2
```

Here I have a simple webserver that returns `foo` or `bar` that is exposed as a `NodePort` service (which is exposed with the `31898` port).

```bash
kubectl apply -f https://gist.github.com/raw/49d01f0091c0e7db08c810ca09828283
```

From a pod, we can run the command below:

```bash
wget -qO- http://kind-control-plane:31898
# OR alternatively, use curl
curl -s http://kind-control-plane:31898
```

**Anything else we need to know?**:

Most of the time, it results in `bad address` or `can't connect to remote host: Network is unreachable`.

To keep the counter to success, I brought up a `busybox` container and ran the `sh` commands below:

```bash
kubectl run kindler --image=busybox --tty -i --rm --command -- sh
```

```sh
/ # i=0; until wget --spider -q http://kind-control-plane:31898/; do i=$((i=i+1)); sleep 1; done; echo "resolved after $i times"
wget: bad address 'kind-control-plane:31898'
wget: bad address 'kind-control-plane:31898'
wget: bad address 'kind-control-plane:31898'
wget: bad address 'kind-control-plane:31898'
wget: bad address 'kind-control-plane:31898'
wget: can't connect to remote host: Network is unreachable
wget: bad address 'kind-control-plane:31898'
resolved after 7 times
```

**Environment:**

- kind version: (use `kind version`): `kind v0.11.1 go1.16.3 linux/amd64`
- Kubernetes version: (use `kubectl version`): `1.21`
- Docker version: (use `docker info`): `20.10.12`
- OS (e.g. from `/etc/os-release`): `Ubuntu 20.04.4 LTS`

**Comment by BenTheElder** [comment]
The DNS resolver in kind is kubernetes (coreDNS) + docker (embedded docker network DNS as the upstream resolver for coreDNS).

DNS in kubernetes can be flaky, there are known mitigation options but they're end-user specific:  see e.g. 

https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html

https://docs.docker.com/config/containers/container-networking/#dns-services
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

**Comment by BenTheElder** [comment]
The node name resolution in particular is provided by docker, via the DNS resolver running in dockerd that it injects into the node containers.

**Comment by BenTheElder** [comment]
closing for now due to lack of activity. feel free to `/reopen` or file a new issue with more details.

**Comment by prashant-shahi** [comment]
@BenTheElder  yeah, I suppose we can close the issue if it's not managed by **_kind_**.
