### ISSUE TITLE
Documentation | Kind Custom node image

### ISSUE THREAD

**Issue by backtrackshubham** [kubernetes-sigs/kind#2675]
**What would you like to be documented**:
- Probable wrong sample of using a custom node image, [this](https://kind.sigs.k8s.io/docs/user/configuration/#nodes) section defines a way to use a custom image in kind config file to create the cluster, however it seems it is being defined as a per node option like
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  image: kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55
```
Which I feel should be like
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
image: kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55
```

**Why is this needed**:
To get the anonymity removed 🥇

**Comment by BenTheElder** [comment]
No this is properly documented. It is a per node option with defaulting or else you can use --image flag to override for all nodes.

**Comment by backtrackshubham** [comment]
Ohh thanks for the clarification @BenTheElder but if you have a look at the link above this option is depicted above `per nodes options` section and just like you said it is properly documented but IMHO it could be moved to per node options section

**Comment by BenTheElder** [comment]
makes sense to me 👍
