### ISSUE TITLE
failed to create cluster with `kind create cluster --image kindest/node:latest`

### ISSUE THREAD

**Issue by shenxianpeng** [kubernetes-sigs/kind#2683]
**What happened**:

Follow https://kind.sigs.k8s.io/ or README.md to create cluster with `kind create cluster --image kindest/node:latest` failed.

Because docker image `kindest/node:latest`  not exist on https://hub.docker.com/r/kindest/node

Here is the output of creating cluster failed and successful.

```bash
sh-4.2$ kind create cluster --image kindest/node:latest
Creating cluster "kind" ...
 ✗ Ensuring node image (kindest/node:latest) 🖼 
ERROR: failed to create cluster: failed to pull image "kindest/node:latest": command "docker pull kindest/node:latest" failed with error: exit status 1
Command Output: Error response from daemon: manifest for kindest/node:latest not found: manifest unknown: manifest unknown

sh-4.2$ kind create cluster --image kindest/node:v1.18.20
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.20) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋
```

**What you expected to happen**:

If possible, the user should follow the document and get the expected result smoothly

**How to reproduce it (as minimally and precisely as possible)**:

Run command `kind create cluster --image kindest/node:latest`

**Anything else we need to know?**:

N/A

**Environment:**

- kind version: (use `kind version`): kind v0.12.0 go1.17.5 linux/amd64

**Comment by aojea** [comment]
The readme specify that latest is when you want to build the image from source, so you have to do `kind build node-image` first

https://github.com/kubernetes-sigs/kind/blob/08a6597255ad1852798c2c6c10b4382cce74c5bc/README.md?plain=1#L85-L105

otherwise you do `kind create cluster` only

**Comment by stmcginnis** [comment]
+1 - that command was taken out of context. It is only given as an example under the "To create a cluster from Kubernetes source" section.

@shenxianpeng does that make sense now? Can we close this issue?

**Comment by shenxianpeng** [comment]
Very make sense. thank you @stmcginnis
