### ISSUE TITLE
Enable WebAssembly Images

### ISSUE THREAD

**Issue by 0xE282B0** [kubernetes-sigs/kind#2686]
**What would you like to be added**:
I'd love to add native WebAssembly support, like described [here](https://wasmedge.org/book/en/kubernetes.html). There is already a custom node-image that can execute WebAssembly natively ([Liquid-Reply/kind-crun-wasm](https://github.com/Liquid-Reply/kind-crun-wasm)). Since `runc` does not support WASM right now, I replaced it by `crun`.

To keep the changes minimal I'd suggest to add crun (compiled with wasm support) to containerd config, but keep runc the default runtime. So for most of the users nothing will change, but with the right `runtimeClassName` this feature can be used.

**Why is this needed**:
With native WebAssembly support kind can execute runtimeless images, which only contain `*.wasm` files. Those  images are tiny in size, multi-arch by nature and come with the security features of the WASM sandbox.

Would that be interesting for the kind project or is that something out of focus for you?

**Comment by aojea** [comment]
We should get feedback from https://github.com/Liquid-Reply/kind-crun-wasm and check if it gets traction and adoption ...

**Comment by BenTheElder** [comment]
Tentatively I'd suggest this is out of focus. https://kind.sigs.k8s.io/docs/contributing/project-scope/

Also https://github.com/Liquid-Reply/kind-crun-wasm/blob/9f9d37cf2fd7622aa58b345ff358587fc92d1f63/images/node/Dockerfile#L19

That line is not something we can accept doing in our image.

**Comment by 0xE282B0** [comment]
@BenTheElder Sure, that line is only there because I override runc and havent found the time to figure out what problem crun has with that configuration. It's nothing I would recommend 😅

**Comment by BenTheElder** [comment]
ACK.

I'm still not particularly keen on shipping by default features that cannot reasonably be expected to be available in other conformant Kubernetes clusters + another binary we need to test and verify. The runc we have today is tightly controlled to match what containerd tests and even then we still have to vet updates carefully. But mostly I don't think kind should be enabling non-portable features by default. I think the customized node images should be sufficient for now ...

**Comment by BenTheElder** [comment]
For now we're going to stick to standard, conformant Kubernetes.

If there is a wider expectation that clusters can run special wasm images, we'll reconsider, but until then, we don't want to make kind more incompatible and make images larger for a niche feature.
