### ISSUE TITLE
Shipped local path provisioner is not usable for some cases

### ISSUE THREAD

**Issue by EBCEEB** [kubernetes-sigs/kind#2697]
**What happened**:

Trying to deploy redis-cluster using Bitnami's helm chart faced an issue with lost nodes.conf. 

After some investigation found a solution - remove shipped storage class and re-create it:

```
kubectl delete storageclasses.storage.k8s.io standard
kubectl delete ns local-path-storage
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.21/deploy/local-path-storage.yaml
kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```

**How to reproduce it (as minimally and precisely as possible)**:

Deploy redis-cluster using bitnami/redis-cluster helm chart:

```
helm install redis bitnami/redis-cluster  --values - <<-EOF
image:
  debug: true
usePassword: false
cluster:
  nodes: 3
  replicas: 0
EOF
```

**Environment:**

- kind version: kind v0.12.0 go1.17.8 darwin/arm64
- Kubernetes version: Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-03-06T21:39:59Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/arm64"}
- Docker version: Docker Desktop 4.6.1 (engine 20.10.13)
- OS: macOS Monterey 12.3 @ Apple Silicon (M1)

**Comment by EBCEEB** [comment]
FYI

Looks like shipped provisioner has incomplete configmap:

```
data:
  config.json: |-
    {
            "nodePathMap":[
            {
                    "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                    "paths":["/var/local-path-provisioner"]
            }
            ]
    }
```

Redeployed:

```
data:
  config.json: |-
    {
            "nodePathMap":[
            {
                    "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                    "paths":["/opt/local-path-provisioner"]
            }
            ]
    }
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent
  setup: |-
    #!/bin/sh
    while getopts "m:s:p:" opt
    do
        case $opt in
            p)
            absolutePath=$OPTARG
            ;;
            s)
            sizeInBytes=$OPTARG
            ;;
            m)
            volMode=$OPTARG
            ;;
        esac
    done

    mkdir -m 0777 -p ${absolutePath}
  teardown: |-
    #!/bin/sh
    while getopts "m:s:p:" opt
    do
        case $opt in
            p)
            absolutePath=$OPTARG
            ;;
            s)
            sizeInBytes=$OPTARG
            ;;
            m)
            volMode=$OPTARG
            ;;
        esac
    done

    rm -rf ${absolutePath}
```

**Comment by BenTheElder** [comment]
the configmaps are different because the versions are different, https://github.com/kubernetes-sigs/kind/blob/bf63502ed1dfdee6c898ee5cc4318b89f0e09980/pkg/build/nodeimage/const_storage.go#L28

**Comment by BenTheElder** [comment]
updating to latest v0.0.22 in https://github.com/kubernetes-sigs/kind/pull/2762
