### ISSUE TITLE
Configure nodes to use a proxy server

### ISSUE THREAD

**Issue by pablochacin** [kubernetes-sigs/kind#270]
In order to solve #136 the `HTTP_PROXY` and `HTTPS_PROXY` environment variables should be passed from the host machine to the node container as suggested [here](https://github.com/kubernetes-sigs/kind/issues/136#issuecomment-459248404).

**Comment by BenTheElder** [comment]
I think initially we can just pass through the values of this from the host to each container at container create time.

Eventually I think I'd like to refactor that out into the context and make it possible to override (for the library case), but I'll do that as part of a larger cleanup of create options I've been hacking on that will land later...

**Comment by pablochacin** [comment]
Agree on both ideas. 

I was also thinking that eventually the environment could also be part of the config file, but I cannot think about specific use case that justifies it.
