### ISSUE TITLE
Kind cluster fails with extraMounts propagation: HostToContainer option on Debian in WSL

### ISSUE THREAD

**Issue by arundeep78** [kubernetes-sigs/kind#2700]
**What happened**:
Stated Kind cluster with extraMounts options as described on [kind documentation](https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts). 

It fails with errors

for HostToContainer
```
ERROR: failed to create cluster: docker run error: command "docker run --hostname kind-airflow-worker --name kind-airflow-worker --label io.x-k8s.kind.role=worker --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind-airflow --net kind --restart=on-failure:1 --init=false --volume=/home/arundeep/projects/airflow/pv_data:/data:ro,rslave kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac" failed with error: exit status 125
Command Output: 7c6963bbce1291dbc1b121194a164a4817943b818b12ae99ab338219688389a6
docker: Error response from daemon: path /home/arundeep/projects/airflow/pv_data is mounted on / but it is not a shared or slave mount.
```

For Bidirectional
```
failed to create cluster: docker run error: command "docker run --hostname kind-airflow-worker --name kind-airflow-worker --label io.x-k8s.kind.role=worker --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind-airflow --net kind --restart=on-failure:1 --init=false --volume=/home/arundeep/projects/airflow/pv_data:/data:ro,rshared kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac" failed with error: exit status 125
Command Output: 5947723c1fcdcd4ee71c744b371a0b82958174c0f285bc6474f5f6c0a5328704
docker: Error response from daemon: path /home/arundeep/projects/airflow/pv_data is mounted on / but it is not a shared mount.
```

Difference is check between shared and slave mount vs only shared mount.

**What you expected to happen**:
Expected to start the cluster as per the documentation
**How to reproduce it (as minimally and precisely as possible)**:
In my environment I have below config.yaml
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-airflow
nodes: 
- role: control-plane
  #image: kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9
  image: kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
- role: worker
  #image: kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9
  image: kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
  extraMounts:
  - hostPath: ./pv_data/
    containerPath: /data
    propagation: HostToContainer
```

**Anything else we need to know?**:
After a day of trying to find solution. I found that if I removed the propagation flag, then it worked. 

As per the reference to [k8s documentation](https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation) given, it suggests to configure `MountFlags`. But I am running on WSL2 and there is no systemd in it. 

Also based on [github issue](https://github.com/coreos/bugs/issues/2579#issuecomment-486744151) and [docker documentation](https://docs.docker.com/engine/release-notes/18.09/#18091), it seems Docker does not recommend that setting anymore as suggested on kubernetes documentation. 

**Environment:**

Debian in WSL2. Docker engine is configured inside Debian. There is no Docker Desktop installed.

- kind version: (use `kind version`): `kind v0.11.1 go1.16.4 linux/amd64`
- Kubernetes version: (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}`
- Docker version: (use `docker info`):
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 4
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.31GiB
 Name: arunpc
 ID: VVOW:KNWT:CQ6Q:AAXC:V2HT:AJK3:UK3K:EHKB:UDSN:WSAP:Y6ET:NQP5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`):
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by BenTheElder** [comment]
You do not have to set the mountPropogation field and we cannot guarantee that it will be suitable for your host environment. 

I'm not understanding how this is a kind bug.

**Comment by BenTheElder** [comment]
> Also based on https://github.com/coreos/bugs/issues/2579#issuecomment-486744151 and [docker documentation](https://docs.docker.com/engine/release-notes/18.09/#18091), it seems Docker does not recommend that setting anymore as suggested on kubernetes documentation.

Those are about the dockerd service and not a volume mount of a running container.

**Comment by arundeep78** [comment]
> 

Well maybe things are very clear to you. I can only give you perspective of a user who is just trying to learn something new. 
The [kind documentation](https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts) that I mentioned above, has below configuration. 

I took it as such assuming that this works, before trying anything new. If a configuration provided in documentation does not work, shall we not call it a bug? or maybe we need to update documentation to reflect the actual status?

I am fine as I finally thought to remove that parameter  and it works. If not a bug then I hope we have some way to avoid anyone else taking a wrong turn.

```zsh
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /path/to/my/files/
    containerPath: /files
    # optional: if set, the mount is read-only.
    # default false
    readOnly: true
    # optional: if set, the mount needs SELinux relabeling.
    # default false
    selinuxRelabel: false
    # optional: set propagation mode (None, HostToContainer or Bidirectional)
    # see https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
    # default None
    propagation: HostToContainer
```

**Comment by BenTheElder** [comment]
`kind create cluster` also may not work without any bugs in kind due to problems in the host environment, with that config it's similar, it's a valid config that generally should work, but if it will or not depends on the host environment.

We should add a note about this being a host dependent, advanced field, that most users probably should not set.

/kind documentation
/remove-kind bug

**Comment by arundeep78** [comment]
That's fine. But I hope I was able to explain, why I or any new user would see it as a bug.

Next point, which maybe related to that dockerd service point. Assume, I want to learn more about this feature. As mentioned in Kind documentation of extraMounts, it gives a link to read on [K8s documentation](https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation).  That section in turn states below

> Before mount propagation can work properly on some deployments (CoreOS, RedHat/Centos, Ubuntu) mount share must be configured correctly in Docker as shown below.
> 
> Edit your Docker's systemd service file. Set MountFlags as follows:
> MountFlags=shared

> Or, remove MountFlags=slave if present. Then restart the Docker daemon:

> 
> sudo systemctl daemon-reload
> sudo systemctl restart docker

And that lead to the [docker documentation](https://docs.docker.com/engine/release-notes/18.09/#18091), which says not to configure that in docker. 

So from my perspective as I read it, Kind says propagation parameters work read K8s
K8s says that if your setup has Docker on Ubuntu and others then configure dockerd to make it work. and Kind is based on docker.
But then Docker says don't do it. as it will not work!

Actually, that docker documentation was the reason, that I then realized that this propagation parameter does not work in this case.

Once again, I am happy that my little setup is working now. But, those who are not experts as the ones developing all these complex systems can be simply derailed.

I will leave it to the team decide how and what to update and thanks you a lot @BenTheElder  for your time. 

I can now move on to setup PostgreSQL with persistence setup in this incredibly layered setup of components 😄

**Comment by giupb** [comment]
> As per the reference to [k8s documentation](https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation) given, it suggests to configure `MountFlags`. But I am running on WSL2 and there is no systemd in it.

Im running docker on WSL2 with Windows 11, and technically systemd is now available as mentioned [here](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/).

But I didn't find docker.service at WSL systemd.

So i found [this](https://legacy-docs.portworx.com/knowledgebase/shared-mount-propagation.html) solution that suggest to set `$ sudo mount --make-shared /` and it works.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/2974 covered this but I only closed https://github.com/kubernetes-sigs/kind/issues/2576 and missed this one.
