### ISSUE TITLE
ppc64le support to kindest/node image

### ISSUE THREAD

**Issue by mayurwaghmode** [kubernetes-sigs/kind#2707]
**What would you like to be added**:
 As of now looks like, the ppc64le specific binary is available but its [image](https://hub.docker.com/r/kindest/node/tags)(kindest/node:v1.23.5) does not have ppc64le support.

**Why is this needed**:
We want to try "Kind" functionality on ppc64le architecture.

**Comment by stmcginnis** [comment]
You will likely need to [build your own images](https://kind.sigs.k8s.io/docs/design/node-image/) for this. There would need to be more of a demand for ppc64le to make it a standard part of the build artifacts. And I don't think the current build systems are set up to be able to create ppc64le images right now, so it would likely be a larger effort to get everything in place before this would be possible.

**Comment by aojea** [comment]
> @stmcginnis can you elaborate more on this point? what is the build system are we talking about?

right now is Ben's and my laptop :smile: 

Kind uses a mix of github actions and prow (kubernetes infra) for CI

Maintaining a new architecture is very expensive , in terms of physical resources and people resources, there was a previous attempt of adding arm CI, but when it started to fail the people that add it went silent ... for new architecture we encourage the people to build their own CIs and maintain them, we are happy to accept patches, but not to maintain more things that doesn't have a clear adoption

**Comment by mkumatag** [comment]
> > @stmcginnis can you elaborate more on this point? what is the build system are we talking about?
> 
> right now the image build system is Ben's and my laptop 😄

ah! this is really a pain especially for cross builds.
> 
> Kind uses a mix of github actions and prow (kubernetes infra) for CI
> 
> Maintaining a new architecture is very expensive , in terms of physical resources and people resources, there was a previous attempt of adding arm CI, but when it started to fail the people that added it went silent ... for new architecture we encourage the people to build their own CIs and maintain them, we are happy to accept patches, but not to maintain more things that doesn't have a clear adoption

valid concern, lately cross-building(buildx) via GH actions improved a lot. I think we can get started with build/push some experimental images for multi-arch and see how it goes(we can drop the plan if it is not really working as expected), wdys?

**Comment by aojea** [comment]
I'm doing that in my own fork https://github.com/aojea/kind-images/actions

There is no need to start here, once you have it working and stable for some time (multiple kubernetes releases) we can revisit this issue

**Comment by BenTheElder** [comment]
We dropped support for flaky architectures we can't actually test on in v0.18.0, please see the release notes.

Sorry, but this just isn't in high demand and we have a lot to support already.
