### ISSUE TITLE
remove the reference about k8s.gcr.io/debian-base

### ISSUE THREAD

**Issue by aad** [kubernetes-sigs/kind#271]
the base has been switched to ubuntu (https://github.com/kubernetes-sigs/kind/commit/4d9a99fef477712bd293c2a1aae5a0f953de4b57) but there are still reference of debian-base in 
- https://github.com/kubernetes-sigs/kind/blob/master/docs/design/base-image.md and 
- https://github.com/kubernetes-sigs/kind/blob/master/images/base/Dockerfile#L15-L19

**Comment by BenTheElder** [comment]
thanks for reporting! will definitely get this cleaned up, those docs could also do with a general update. will probably follow up after finishing #268
