### ISSUE TITLE
Failure for building base image on ppc64le architecture

### ISSUE THREAD

**Issue by mayurwaghmode** [kubernetes-sigs/kind#2710]
**What happened**:
While building the base image using instructions mentioned [here](https://github.com/kubernetes-sigs/kind/tree/main/images/base) facing the below issue at installing packages step. Have attached the complete logs- 
[base-image-issue.txt](https://github.com/kubernetes-sigs/kind/files/8441608/base-image-issue.txt)

``` 
error: failed to solve: process "/bin/sh -c echo \"Installing Packages ...\"     && DEBIAN_FRONTEND=noninteractive clean-install       systemd       conntrack iptables iproute2 ethtool socat util-linux mount ebtables kmod       libseccomp2 pigz       bash ca-certificates curl rsync       nfs-common fuse-overlayfs       jq     && find /lib/systemd/system/sysinit.target.wants/ -name \"systemd-tmpfiles-setup.service\" -delete     && rm -f /lib/systemd/system/multi-user.target.wants/*     && rm -f /etc/systemd/system/*.wants/*     && rm -f /lib/systemd/system/local-fs.target.wants/*     && rm -f /lib/systemd/system/sockets.target.wants/*udev*     && rm -f /lib/systemd/system/sockets.target.wants/*initctl*     && rm -f /lib/systemd/system/basic.target.wants/*     && echo \"ReadKMsg=no\" >> /etc/systemd/journald.conf     && ln -s \"$(which systemd)\" /sbin/init" did not complete successfully: exit code: 100
make: *** [/root/kind/images/base/../Makefile.common.in:20: build] Error 1
```

**What you expected to happen**:
The base image should get build for ppc64le architecture

**How to reproduce it (as minimally and precisely as possible)**:
 git clone https://github.com/kubernetes-sigs/kind.git
    cd kind/images/base
    make quick 

**Anything else we need to know?**:

**Environment**:
```
- kind version: (use `kind version`): kind v0.12.0 go1.17.8 linux/ppc64le
- Kubernetes version: (use `kubectl version`): - Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/ppc64le"}
- Docker version: (use `docker info`):  Version: v20.10.14
- OS (e.g. from `/etc/os-release`): Red Hat Enterprise Linux-8.5
```

**Comment by aojea** [comment]
```
#0 365.0 System has not been booted with systemd as init system (PID 1). Can't operate.
#0 365.0 Failed to connect to bus: Host is down
#0 369.5 Created symlink /etc/systemd/system/multi-user.target.wants/nfs-client.target → /lib/systemd/system/nfs-client.target.
#0 369.5 Created symlink /etc/systemd/system/remote-fs.target.wants/nfs-client.target → /lib/systemd/system/nfs-client.target.
#0 370.6 invoke-rc.d: could not determine current runlevel
#0 371.0 invoke-rc.d: policy-rc.d denied execution of start.
#0 371.0 Setting up systemd-timesyncd (245.4-4ubuntu3.15) ...
#0 373.9 qemu:handle_cpu_signal received signal outside vCPU context @ pc=0x10213a8e
#0 374.5 adduser: `/bin/chfn -f systemd Time Synchronization systemd-timesync' exited from signal 134. Exiting.
#0 374.6 dpkg: error processing package systemd-timesyncd (--configure):
#0 374.6  installed systemd-timesyncd package post-installation script subprocess returned error exit status 1
#0 374.6 dpkg: dependency problems prevent configuration of systemd:
#0 374.6  systemd depends on systemd-timesyncd | time-daemon; however:
#0 374.6   Package systemd-timesyncd is not configured yet.
#0 374.6   Package time-daemon is not installed.
#0 374.6   Package systemd-timesyncd which provides time-daemon is not configured yet.
#0 374.6
#0 374.6 dpkg: error processing package systemd (--configure):
#0 374.6  dependency problems - leaving unconfigured
#0 374.6 Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
#0 375.2 Processing triggers for ca-certificates (20210119~20.04.2) ...
#0 375.8 Updating certificates in /etc/ssl/certs...
#0 431.4 0 added, 0 removed; done.
#0 431.4 Running hooks in /etc/ca-certificates/update.d...
#0 431.5 done.
#0 431.9 Errors were encountered while processing:
#0 431.9  systemd-timesyncd
#0 431.9  systemd
#0 432.1 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
```

it doesn't seems a problem in `kind` , it seems a problem building the dockerfile, I will try to build a dockerfile with only `systemd-timesyncd` in ppc64le and see if it works ...

**Comment by mkumatag** [comment]
Added support to makefile to build for ppc64le platform here - https://github.com/kubernetes-sigs/kind/pull/2711

**Comment by aojea** [comment]
thanks

**Comment by mkumatag** [comment]
> it doesn't seems a problem in `kind` , it seems a problem building the dockerfile, I will try to build a dockerfile with only `systemd-timesyncd` in ppc64le and see if it works ...

I tried building with all the platforms(+ppc64le) from my Mac and it just works fine

```shell
$ REGISTRY=docker.io/mkumatag make push
./../../hack/build/init-buildx.sh
docker buildx build --platform=linux/amd64,linux/arm64,linux/s390x,linux/ppc64le --push --progress=auto -t docker.io/mkumatag/base:v20220407-8cc0c0b5-dirty --pull .
[+] Building 254.0s (77/77) FINISHED
```

**Comment by mayurwaghmode** [comment]
> ```
> #0 365.0 System has not been booted with systemd as init system (PID 1). Can't operate.
> #0 365.0 Failed to connect to bus: Host is down
> #0 369.5 Created symlink /etc/systemd/system/multi-user.target.wants/nfs-client.target → /lib/systemd/system/nfs-client.target.
> #0 369.5 Created symlink /etc/systemd/system/remote-fs.target.wants/nfs-client.target → /lib/systemd/system/nfs-client.target.
> #0 370.6 invoke-rc.d: could not determine current runlevel
> #0 371.0 invoke-rc.d: policy-rc.d denied execution of start.
> #0 371.0 Setting up systemd-timesyncd (245.4-4ubuntu3.15) ...
> #0 373.9 qemu:handle_cpu_signal received signal outside vCPU context @ pc=0x10213a8e
> #0 374.5 adduser: `/bin/chfn -f systemd Time Synchronization systemd-timesync' exited from signal 134. Exiting.
> #0 374.6 dpkg: error processing package systemd-timesyncd (--configure):
> #0 374.6  installed systemd-timesyncd package post-installation script subprocess returned error exit status 1
> #0 374.6 dpkg: dependency problems prevent configuration of systemd:
> #0 374.6  systemd depends on systemd-timesyncd | time-daemon; however:
> #0 374.6   Package systemd-timesyncd is not configured yet.
> #0 374.6   Package time-daemon is not installed.
> #0 374.6   Package systemd-timesyncd which provides time-daemon is not configured yet.
> #0 374.6
> #0 374.6 dpkg: error processing package systemd (--configure):
> #0 374.6  dependency problems - leaving unconfigured
> #0 374.6 Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
> #0 375.2 Processing triggers for ca-certificates (20210119~20.04.2) ...
> #0 375.8 Updating certificates in /etc/ssl/certs...
> #0 431.4 0 added, 0 removed; done.
> #0 431.4 Running hooks in /etc/ca-certificates/update.d...
> #0 431.5 done.
> #0 431.9 Errors were encountered while processing:
> #0 431.9  systemd-timesyncd
> #0 431.9  systemd
> #0 432.1 E: Sub-process /usr/bin/dpkg returned an error code (1)
> ------
> ```
> 
> it doesn't seems a problem in `kind` , it seems a problem building the dockerfile, I will try to build a dockerfile with only `systemd-timesyncd` in ppc64le and see if it works ...

Created this PR for fixing the issue, - https://github.com/kubernetes-sigs/kind/pull/2712.
Using this change, able to build ppc64le specific base image in my local docker environment

**Comment by aojea** [comment]
/close

Fixed by https://github.com/kubernetes-sigs/kind/pull/2711
