### ISSUE TITLE
Kind should note when Docker is out of disk space

### ISSUE THREAD

**Issue by bentito** [kubernetes-sigs/kind#2717]
**What would you like to be added**:
Kind should note when Docker is out of disk space on startup and refuse to start.

**Why is this needed**:
Spent a lot of time trying to figure out why a deployment was failing to be able to create a directory. Finally found the problem when I went to install Minikube and it refused to start due to Docker being out of disk space. `docker prune` fixed the problem and allowed the deployment to function properly.

**Comment by BenTheElder** [comment]
A problem is that we support (nominally, though not encouraged) remote docker daemons, so checking the local disk space is potentially wrong. I'm not sure if minikube supports this assumption or what. If checking on a remote daemon, this may be very slow.

Additionally, the kind binary process may not have permission to read this information, and requiring access would be a breaking change.

I think running out of disk space is a pretty regular docker issue, it's not immediately clear to me that kind should be responsible for this, though if we can do so cheaply and efficiently that may be OK. kind prioritizes being relatively quick and minimal.

I think a warning may be reasonable, if we can think about how to resolve the points above. I do not think refusing to start is reasonable, especially as the check may be incorrect.

**Comment by bentito** [comment]
Yeah Idk if minikube supports remote docker daemons, searching it didn't yield a definitive answer for me. Even if they do, they may not be aware of the limitations that doing the disk space check involves.

Still, I think a warning or hint is warranted because the view at the container level is hard to debug. Something worked,then time passed, and it doesn't work anymore. You look at all your versions and base images to see if something changed out from under you. Later, maybe, you finally think, ah, all the space assigned to Docker is full.

**Comment by IoannisMatzaris** [comment]
what about checking the local disk, only if it is a local docker daemon?

**Comment by aojea** [comment]
that is something the user should do, or docker ... but I don't think `kind` be doing system management ... I think that is a bit of the unix philosophy of "do one thing and do it well"

**Comment by stmcginnis** [comment]
I have to agree with @aojea - this doesn't seem like something kind should do.

**Comment by bentito** [comment]
Okay but I have to say I only noticed my Docker instance was out of space because I went to install minikube and it pointed it out. And I went to install minikube because I was giving up on kind because of the mystery problem...

**Comment by BenTheElder** [comment]
It might be interesting to consider this if kind attempted to explain cluster creation failure, which could be best effort and not add complexity and cost to the happy path.

I’d be interested in a broader design introducing hinting to the user why a failure likely occurred and what can be done when we hit predictable failure modes like this, but doing so well will be tricky and might not be the best focus still vs focusing on trying to ensure kind “just works”

The issue of remote daemons remains.

**Comment by BenTheElder** [comment]
I don't think there's a reliable, efficient, portable answer for this. 

We do at least provide the output from failed commands with any info docker may show.
