### ISSUE TITLE
How to add a extraPortMapping without recreating the cluster

### ISSUE THREAD

**Issue by Charlie17Li** [kubernetes-sigs/kind#2720]
1. I have created a cluster with the script:
```shell
#!/bin/bash
cluster_name=${cluster_name:-"test"}

cat > kind-cluster.yaml <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
EOF

kind create cluster --config=kind-cluster.yaml --name=test
```

2. but I find I have another port need to expose(31116), But I don't want to recreate the cluster, what should I do, thx :)
```shell
[root@localhost lql]# k get svc -A --context=kind-test
NAMESPACE     NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                       AGE
...
default       spark-demo-master-svc            NodePort    10.96.209.188   <none>        7077:31025/TCP,80:31116/TCP   3h12m
kubeapps      kubeapps-svc                     NodePort    10.96.96.211    <none>        8080:30080/TCP                3h58m
```

**Comment by aojea** [comment]
AFAIK is not possible to do dynamically portmapping in docker, but you can define the nodeport to your deployment to use the same port that you are exposing

There are other options like in https://kind.sigs.k8s.io/docs/user/ingress/

**Comment by BenTheElder** [comment]
you can start a new `socat` container alongside the cluster for TCP connections (search this repo for past discussions) but there's no super great way to do this at runtime on an existing container, docker and podman just don't support mutating the container spec like this.
