### ISSUE TITLE
node can't use apt-get to install

### ISSUE THREAD

**Issue by luojieio** [kubernetes-sigs/kind#2725]
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker

**Comment by aojea** [comment]
??

Can you expand?

**Comment by tao12345666333** [comment]
If you want to install package using apt-get, you should run `apt-get update` first.

**Comment by BenTheElder** [comment]
You generally shouldn't be installing things on the node / we only guarantee the node image can be used to create a conformant kubernetes cluster.
