### ISSUE TITLE
Kong Ingress documentation is not updated

### ISSUE THREAD

**Issue by andrea-mucci** [kubernetes-sigs/kind#2727]
**What would you like to be documented**:
The documentation kind - Ingress on the Kong Section is not updated and return an error:

```
kubectl patch service -n kong ingress-kong -p '{"spec":{"type":"NodePort"}}'

```

this command return the following error:

Error from server (NotFound): services "ingress-kong" not found

**Comment by AppalaKarthik** [comment]
I will work on this and submit PR later
