### ISSUE TITLE
load: `kind load docker-image ..` is non-functional for provider `podman`

### ISSUE THREAD

**Issue by flouthoc** [kubernetes-sigs/kind#2729]
As of now kind hardcodes looking and loading images from docker
as a result kind load docker-image <image>:<tag> does not works well when
Provider is configured as podman instead of docker.

Following PR makes sure that kind supports loading images irrespective of
the providers configured and works for both podman and docker

**What happened**:
`kind load docker-image <image-name>:<image-tag>` is not functional when provider is configured as `podman`.

**What you expected to happen**:
To get image uploaded into control-plane

**How to reproduce it (as minimally and precisely as possible)**:
```console
[root@fedora ~]# kind load docker-image localhost/test:latest
enabling experimental podman provider
ERROR: image: "localhost/test:latest" not present locally
```

**Anything else we need to know?**:
I think this can be fixed by: https://github.com/kubernetes-sigs/kind/pull/2728

**Comment by BenTheElder** [comment]
it is expected that `kind load docker-image` only supports ... docker, docker is in the name

https://github.com/kubernetes-sigs/kind/issues/2038 for the tracking issue re: we should have a multi-provider option.

in the meantime: `podman save image | kind load image-archive -`

**Comment by flouthoc** [comment]
@BenTheElder Thanks for promptly replying. Ah i see if there is already a plan for unification of `image` command then that would be better. Podman still supports `docker-image` format but command is a `no-op` when `docker` is not present on the `host` hence I thought it would be better to use whatever provider is present.

I can use my patch or a workaround till this is fixed upstream. This issue is not a blocker for my use-case so its perfectly fine to wait for unification of `image` command.

Please feel free to close this issue if this is already being tracked somewhere to avoid redundancy.

Cheers :smile:
