### ISSUE TITLE
Cluster startup cgroups v2-related failure

### ISSUE THREAD

**Issue by tooSadman** [kubernetes-sigs/kind#2731]
**What happened**:
When running `kind create cluster` it fails with the following log message:
``` $ kind create cluster --retain --image kindest/node:v1.20.2; kind export logs; kind delete cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✗ Starting control-plane 🕹️ 
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
```

**Anything else we need to know?**:
Here are the logs: [kind-logs.zip](https://github.com/kubernetes-sigs/kind/files/8578024/kind-logs.zip)
As we can see from the kubelet logs here's the issue:
```
Apr 27 21:12:20 kind-control-plane kubelet[186]: E0427 21:12:20.582136     186 remote_runtime.go:116] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create containerd task: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: openat2 /sys/fs/cgroup/kubelet/kubepods/burstable/podb46ac09f2c06fb2fcca38023cab48148/e1f761d70617d03c9d612d783a744a86adc16e38ca7e70cec31a77b23bd28c3a/cpu.weight: no such file or directory: unknown
Apr 27 21:12:20 kind-control-plane kubelet[186]: E0427 21:12:20.582183     186 kuberuntime_sandbox.go:70] CreatePodSandbox for pod "kube-scheduler-kind-control-plane_kube-system(b46ac09f2c06fb2fcca38023cab48148)" failed: rpc error: code = Unknown desc = failed to create containerd task: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: openat2 /sys/fs/cgroup/kubelet/kubepods/burstable/podb46ac09f2c06fb2fcca38023cab48148/e1f761d70617d03c9d612d783a744a86adc16e38ca7e70cec31a77b23bd28c3a/cpu.weight: no such file or directory: unknown
Apr 27 21:12:20 kind-control-plane kubelet[186]: E0427 21:12:20.582193     186 kuberuntime_manager.go:755] createPodSandbox for pod "kube-scheduler-kind-control-plane_kube-system(b46ac09f2c06fb2fcca38023cab48148)" failed: rpc error: code = Unknown desc = failed to create containerd task: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: openat2 /sys/fs/cgroup/kubelet/kubepods/burstable/podb46ac09f2c06fb2fcca38023cab48148/e1f761d70617d03c9d612d783a744a86adc16e38ca7e70cec31a77b23bd28c3a/cpu.weight: no such file or directory: unknown
Apr 27 21:12:20 kind-control-plane kubelet[186]: E0427 21:12:20.582234     186 pod_workers.go:191] Error syncing pod b46ac09f2c06fb2fcca38023cab48148 ("kube-scheduler-kind-control-plane_kube-system(b46ac09f2c06fb2fcca38023cab48148)"), skipping: failed to "CreatePodSandbox" for "kube-scheduler-kind-control-plane_kube-system(b46ac09f2c06fb2fcca38023cab48148)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-scheduler-kind-control-plane_kube-system(b46ac09f2c06fb2fcca38023cab48148)\" failed: rpc error: code = Unknown desc = failed to create containerd task: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: openat2 /sys/fs/cgroup/kubelet/kubepods/burstable/podb46ac09f2c06fb2fcca38023cab48148/e1f761d70617d03c9d612d783a744a86adc16e38ca7e70cec31a77b23bd28c3a/cpu.weight: no such file or directory: unknown"
```

**Environment:**

- kind version: (use `kind version`): `kind v0.12.0 go1.17.8 linux/amd64`
- Kubernetes version: (use `kubectl version`): 
``` 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"archive", BuildDate:"2022-03-17T21:14:47Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):  
```$ docker info  
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  compose: Docker Compose (Docker Inc., 2.4.1)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.14
 Storage Driver: btrfs
  Build Version: Btrfs v5.16.2 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: de8046a5501db9e0e478e1c10cbcfb21af4c6b2d.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.17.5-lqx1-1-lqx
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.34GiB
 Docker Root Dir: /home/<user>/.local/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`): 
```
OS: Manjaro Linux x86_64 
Kernel: 5.17.5-lqx1-1-lqx 
DE: GNOME 41.5 
WM: Mutter 
```

**Comment by aojea** [comment]
that seems a kubelet bug , it seems there is also some work on kubelet  to improve that

https://github.com/kubernetes/kubernetes/pull/109217

I'd try with the more modern version, please use the official images released for each version 1.20.2 is very old

https://github.com/kubernetes-sigs/kind/releases/tag/v0.12.0

**Comment by tooSadman** [comment]
Hi @aojea, thanks for reply.
I've already tried versions 1.23.5 and  1.23.3 and the result was the same. Will try with future version after that PR is merged.

**Comment by aojea** [comment]
> Hi @aojea, thanks for reply. I've already tried versions 1.23.5 and 1.23.3 and the result was the same. Will try with future version after that PR is merged.

then upload logs for the failure with the latest version of kubernetes , we'll check if there is a bug in kubelet and report it there or if kind needs to workaround something, these distros like Manajaro with new kernels and new features are always tricky

**Comment by tooSadman** [comment]
ok, so with image version `kindest/node:v1.23.5` here are the logs: [kind-logs.zip](https://github.com/kubernetes-sigs/kind/files/8581004/kind-logs.zip)

**Comment by aojea** [comment]
> Apr 27 21:12:20 kind-control-plane kubelet[186]: E0427 21:12:20.582234     186 pod_workers.go:191] Error syncing pod b46ac09f2c06fb2fcca38023cab48148 ("kube-scheduler-kind-control-plane_kube-system(b46ac09f2c06fb2fcca38023cab48148)"), skipping: failed to "CreatePodSandbox" for "kube-scheduler-kind-control-plane_kube-system(b46ac09f2c06fb2fcca38023cab48148)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-scheduler-kind-control-plane_kube-system(b46ac09f2c06fb2fcca38023cab48148)\" failed: rpc error: code = Unknown desc = failed to create containerd task: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: openat2 /sys/fs/cgroup/kubelet/kubepods/burstable/podb46ac09f2c06fb2fcca38023cab48148/e1f761d70617d03c9d612d783a744a86adc16e38ca7e70cec31a77b23bd28c3a/cpu.weight: no such file or directory: unknown"


@kolyshkin can this error `cpu.weight: no such file or directory: unknown`  be related to your recent fix https://github.com/kubernetes-sigs/kind/commit/db40a9b58aefcb44abffcab638acb5e44e05f31d?

or is this about this hooks?

https://github.com/kubernetes-sigs/kind/blob/dbcc39c6b8fb395863dc124fe74aca902ea7fef5/images/base/Dockerfile#L152-L154

**Comment by burmanm** [comment]
I don't think that's it. There was a similar issue earlier which caused the kind 0.11.1 to fail also and it all happened after a Manjaro update that somehow messed up cgroupsv2 and it behaved in a similar way to the WSL v2 systemd-issues. That log entry of missing cgroup is found in the journalctl, not in the kind logs. 

For the record, on my Manjaro installation (although running kernel 5.16), kind 0.12.0 works fine (with multiple images, incl. kindest/node 1.23.5)

**Comment by tooSadman** [comment]
Can also confirm that it works on `5.15.32` kernel, thus the problem is really with 5.17+ kernels.

**Comment by tooSadman** [comment]
yeah, looks like kind can do nothing about it, so this could be closed. 
Thank you all for help!
