### ISSUE TITLE
kind delete non-exist clusters return true

### ISSUE THREAD

**Issue by laith-leo** [kubernetes-sigs/kind#2733]
**What happened**:
Delete a nonexisting cluster in Kind returns a "TRUE" message

**What you expected to happen**:
Delete a nonexisting cluster in Kind should return a FALSE message, e.g. "The Kind cluster $CLUSTER does not exist"
**How to reproduce it (as minimally and precisely as possible)**:
kind delete clusters $ANY-NON-EXIST-CLUSTER 
Deleted clusters: ["ANY-NON-EXIST-CLUSTER "]
**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): kind v0.12.0 go1.17.8 darwin/arm64
- Kubernetes version: (use `kubectl version`): v1.23.6
- Docker version: (use `docker info`): 20.10.13
- OS (e.g. from `/etc/os-release`): macOS 12.3.1

**Comment by stmcginnis** [comment]
This is expected, and wanted behavior.

See https://github.com/kubernetes-sigs/kind/pull/2646 for more background.

/close
