### ISSUE TITLE
Being able to override the platform in the underlying docker command

### ISSUE THREAD

**Issue by subnetmarco** [kubernetes-sigs/kind#2735]
I would like to override the `--platform` argument in the underlying `docker run ..` command that is being invoked by `kind create cluster`, is there a way to do this?

**Comment by BenTheElder** [comment]
No, and even if you could, kind nodes will not work under qemu / binfmt_misc hijinks 🙃 

If you want to run on an architecture other than the host, you need docker in a VM.

**Comment by BenTheElder** [comment]
I think this is, amusingly, https://github.com/kubernetes-sigs/kind/issues/2718#issuecomment-1115874242 `DOCKER_DEFAULT_PLATFORM`, which kind may need to disable actually ...

**Comment by BenTheElder** [comment]
Let's follow up in https://github.com/kubernetes-sigs/kind/issues/2718 👍
