### ISSUE TITLE
kind create cluster fails with iptables error - m1 mac

### ISSUE THREAD

**Issue by miguelvr** [kubernetes-sigs/kind#2739]
**What happened**:

Kind control plane fails with error:
```
INFO: ensuring we can execute mount/umount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: detected cgroup v2
INFO: clearing and regenerating /etc/machine-id
Initializing machine ID from random generator.
INFO: setting iptables to detected mode: legacy
iptables-save v1.8.7 (legacy): Cannot initialize: iptables who? (do you need to insmod?)

INFO: ensuring we can execute mount/umount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: detected cgroup v2
INFO: clearing and regenerating /etc/machine-id
Initializing machine ID from random generator.
INFO: setting iptables to detected mode: legacy
iptables-save v1.8.7 (legacy): Cannot initialize: iptables who? (do you need to insmod?)
```

**What you expected to happen**: cluster to be created successfully

**How to reproduce it (as minimally and precisely as possible)**: I'm on a Macbook Pro 16'' (M1 Pro)

**Anything else we need to know?**: 
 - minikube is failing for the same reason
 - kind v0.12.0 fails at an earlier stage

**Environment:**

- kind version: (use `kind version`): 0.11.1
- Kubernetes version: (use `kubectl version`): 1.24.0

<details>
  <summary>Docker version (expand for details):</summary>

```
  Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.1)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.765GiB
 Name: docker-desktop
 ID: UDDO:NFIC:55AU:OWZV:3EQ7:IF53:HTNF:GF7T:K5KT:D24B:25MW:3YD3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```
</details>

- OS: macOS Monterey 12.3.1

**Comment by miguelvr** [comment]
Once I opened this ticket, I had an epiphany, so I'll leave it here as it might be useful for someone else:

!!! Please make sure the `DOCKER_DEFAULT_PLATFORM` environment variable is unset → mine was set to `linux/amd64` to build & export images, and this was creating the problem !!!

**Comment by BenTheElder** [comment]
We're discussing what kind should do about this env in https://github.com/kubernetes-sigs/kind/issues/2718 😅, it took a while to track some previous issues down to this.

**Comment by GZack2000** [comment]
One of my buddies was facing this issue while creating kind cluster. 
```bash
 ✗ Starting control-plane 🕹️
Deleted nodes: ["kind-control-plane"]
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 137
Command Output: I1122 19:36:26.910676     169 initconfiguration.go:255] loading configuration from "/kind/kubeadm.conf"
W1122 19:36:26.930880     169 initconfiguration.go:332] [config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta3, Kind=JoinConfiguration
```
@BenTheElder Like you said it took so long to narrow this down as the root cause as the above error is so generic and doesn't really help much.

He was hitting this issue on M1 Mac with Rancher Desktop 1.9.1 as runtime. 
Since latest kind version doesn't work with Rancher, we had to downgrade `go install sigs.k8s.io/kind@v0.19.0`

Debugging path was like
1. Attempt creating kind cluster using --retain option
```bash
kind create cluster --retain -v 1
```
2. Checking the `docker container logs` of the failed control-plane container showed this error
```bash
INFO: setting iptables to detected mode: legacy
iptables-save v1.8.7 (legacy): Cannot initialize: iptables who? (do you need to insmod?)
```
A quick search on this phrase brought me to this Issue and voila, unsetting the env variable fixed it.
Thanks a bunch @miguelvr 

This would be worth mentioning somewhere in the Kind documentation.

**Comment by BenTheElder** [comment]
#2718 please use the main open tracking issue for discussing so we can more easily keep track of feedback, thanks!

note: #3277, I'd recommend switching to some other local docker tool (eg the underlying lima project)

**Comment by ipartner** [comment]
I have the exact same problem but DOCKER_DEFAULT_PLATFORM is not set

**Comment by neoyagami** [comment]
I have the exact same problem. DOCKER_DEFAULT_PLATFORM is unset the sad part is I need o test x86 images with helm but minikube do not supoort x86 on m1 :\
