### ISSUE TITLE
Support docker restart for clusters with multiple nodes (single controlplane node)

### ISSUE THREAD

**Issue by tnqn** [kubernetes-sigs/kind#2759]
**What would you like to be added**:

For clusters with multiple nodes like below, once the machine or docker restarts, the cluster cannot recover like clusters with single node.
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
```

The cluster is still reachable but kube-controller-manager and kube-scheduler are not working properly because of the IP address they use to connect kube-apiserver is stale. 
```
1 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: Get "https://172.18.0.6:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=5s": dial tcp 172.18.0.6:6443: connect: connection refused
1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://172.18.0.6:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.18.0.6:6443: connect: connection refused
```

This is because the IP allocation is not persistent, and there is a great chance the IP of the controlplane node will change after docker restarts. To recover the cluster, two things need to be fixed:
* The IP address in kubeconfigs of kube-controller-manager and kube-scheduler needs to be updated
* The new IP address must be a valid alternative name of kube-apiserver's certificate

There are two possible approaches that can achieve it:

#### 1. Use loopback address to connect kube-apiserver
This leverages the fact that loopback address is a valid alternative name of kube-apiserver's certificate: https://github.com/kubernetes-sigs/kind/blob/b4ab02cffbc8aca096ee7e2bc0f105654f1572c6/pkg/cluster/internal/kubeadm/config.go#L167-L171
However, setting loopback address to kubeconfig of kube-controller-manager and kube-scheduler is not simple. kubeadm uses `localAPIEndpoint.advertiseAddress` parameter to configure that address, but it's also used to determine which address kube-apiserver will listen to. So we cannot just set the parameter (and current kubeadm doesn't accept advertiseAddress set to loopback address).  @BenTheElder suggested the following options at https://github.com/kubernetes-sigs/kind/pull/2671#issuecomment-1116475575:

>  * kubeadm makes it possible to specify this directly
>  * kind uses phases to work around kubeadm
 
I haven't found a proper parameter to specify it in kubeadm directly, and currently kubeadm "patches" don't support patching kubeconfig files. I tried to extend "patches" to kubeconfig via https://github.com/kubernetes/kubernetes/pull/109886 and added patch files to kind via https://github.com/kubernetes-sigs/kind/pull/2671, it could resolve the problem. However, it would require a new Kubernetes release and the certificate of kube-apiserver would still not match the IP address it advertises, though the defect is worked around by making clients use loopback address.

#### 2. Regenerate certificate with new IP

Inspired by the comment in https://github.com/kubernetes-sigs/kind/pull/2671#discussion_r868563989, the entrypoint could regenerate a certificate for kube-apiserver with the new IP and replace the IP address used in kubeconfig files, given that CA cert and key are available on controlplane node.

I have verified it could resolve the problem, and it doesn't require a new Kubernetes release and the certificate matches the new IP. Required change can be found at https://github.com/tnqn/kind/commit/cf95727a5d35360c219604fb0a832395f775c3fb.

Personally I think the second approach is better, I would like hear your opinions before updating the PR. @BenTheElder @aojea @neolit123

**Comment by BenTheElder** [comment]
I think we should do the cert part of 2) regardless, we don't want the cert signed for the wrong IP.
I think if we only do 1) then we're probably leaving other broken clients (e.g. peer containers on the `kind` network)

I think it might *also* make sense to be picking loopback for control plane traffic, but that does have the downside of deviating from kubeadm defaults, which we sometimes do but generally avoid. With kubeadm/kinder in CI as well now it's perhaps less of a concern.

1) also seems to be a lot more work, we could revisit in the future.

Thank you so much for patiently working through this with us 🙏

**Comment by BenTheElder** [comment]
cc @aojea

**Comment by tnqn** [comment]
@BenTheElder @neolit123 Thanks for your comments. I have created #2775 to implement 2) via kubeadm phase.
