### ISSUE TITLE
Discuss Extended Provisioning use cases

### ISSUE THREAD

**Issue by pablochacin** [kubernetes-sigs/kind#276]
The objective of this issue is to discuss the requirements from use cases beyond the current "one shot" create/delete cluster which is the main focus of the `kind`. These use cases include, for example, the provisioning of additional nodes to an existing cluster, as well as a fine grained control on the node bootstrap process. 

Such use cases are therefore likely to be addressed as part of the creation of a kind library, which could be used by other tools. 

The use cases are described in the [Kind Extended Provisioning use Cases](https://docs.google.com/document/d/1NlZZtzqBTticKWgwxFHK72HMgBexkyQhRHM7gnt2m-I/edit?usp=sharing) document, open for comments.

**Comment by BenTheElder** [comment]
[this has been discussed a bitin meetings and on slack so far, for anyone interested]

**Comment by rohansingh** [comment]
I think the "local clusters on developer machines" fits into extended provisioning. While `kind create` itself is pretty lightweight, a developer might load a large number of objects and images into the cluster.

Restoring such a cluster can be expensive, so it would be ideal to leave it running indefinitely and have it potentially survive restarts, upgrades, etc.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-docker/ is now a thing :eyes:

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubeadm/tree/master/kinder is also using some bits along these lines.

I think we're far enough away from this original issue now though to follow up in future issues.
