### ISSUE TITLE
Ingress NGINX Pod in 'Pending' State

### ISSUE THREAD

**Issue by thepaulmacca** [kubernetes-sigs/kind#2763]
**What happened**:

When deploying the Ingress NGINX controller to a new cluster, the pod is in a `Pending` state

**What you expected to happen**:

Pod to be in a `Running` state

**How to reproduce it (as minimally and precisely as possible)**:

```bash
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
```

**Anything else we need to know?**:

This only happens with the `v0.13.0` release, it works fine in `v0.12.0` so have just reverted to that for now

**Environment:**

- kind version: (use `kind version`): v0.13.0
- Kubernetes version: (use `kubectl version`): v1.24.0
- Docker version: (use `docker info`): 20.10.14
- OS (e.g. from `/etc/os-release`): WSL2 (Windows 10)

**Comment by BenTheElder** [comment]
I'm pretty sure this is ingress-nginx not being ready for Kubernetes 1.24 https://github.com/kubernetes/ingress-nginx/issues/8091

**Comment by BenTheElder** [comment]
If you use `kind create cluster --image=kindest/node:v1.23.6@sha256:1af0f1bee4c3c0fe9b07de5e5d3fafeb2eec7b4e1b268ae89fcab96ec67e8355` to switch to Kubernetes 1.23.6 I suspect it will work with kind v0.13.0

**Comment by thepaulmacca** [comment]
Ah right ok, I'll try that and report back if any issues. Thanks for the quick reply

**Comment by BenTheElder** [comment]
we may need to add a note to our docs in the meantime, if that is the case. https://kind.sigs.k8s.io/docs/user/ingress/
testing this is also on my TODO now ...

**Comment by BenTheElder** [comment]
Perhaps you just needed to wait longer for the pod to become ready?

I went back through https://kind.sigs.k8s.io/docs/user/ingress/ with kind v0.13.0 (default image) and successfully curled the foo and bar test services by the end.

One of the steps after installing the ingress is:
```bash
kubectl wait --namespace ingress-nginx \
  --for=condition=ready pod \
  --selector=app.kubernetes.io/component=controller \
  --timeout=90s
 ```
The pods can take a bit to settle.

**Comment by Alainx277** [comment]
I've experienced this same error on version `0.13.0`.

I think it's caused by the new kubernetes version renaming the taint from `node-role.kubernetes.io/master` to `node-role.kubernetes.io/control-plane`. In the `deploy.yaml` file linked in the docs, it only tolerates the old taint name: https://github.com/kubernetes/ingress-nginx/blob/main/deploy/static/provider/kind/deploy.yaml#L479-L481

@BenTheElder  Can we reopen this issue?

**Comment by BenTheElder** [comment]
We can, but this may not be the same issue, for single node clusters we already remove the taint.
I suspect your case is different than OP and the actual change needs to happen in ingress-nginx repo.

**Comment by BenTheElder** [comment]
Since no issues were reported back, I would prefer a new bug with the bug template filled out with your reproducer etc.

**Comment by BenTheElder** [comment]
Upstream: https://github.com/kubernetes/ingress-nginx/issues/8605

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/ingress-nginx/pull/8609 is merged upstream
