### ISSUE TITLE
Document installing linux docker (not docker desktop) on WSL 2

### ISSUE THREAD

**Issue by jankoprowski** [kubernetes-sigs/kind#2770]
**What would you like to be documented**:
WSL 2 is not nesesery need Docker Desktop, which is not free.
You could document setup with https://docs.docker.com/engine/install/ubuntu/
After installing docker you just need add your user to `docker` group, restart wsl and run command `service docker start` 

**Why is this needed**:
Docker Desktop is not free - it would be nice to know you have an free alternative under WSL 2

**Comment by BenTheElder** [comment]
PRs welcome, the WSL2 docs are maintained through community contributions, we don't develop on windows and don't have CI #1529 
/help
/good-first-issue

**Comment by Aryan-Deshpande** [comment]
Hey, I would like to work on this issue. Just to clear up, documentation needs to be made to install docker/ setup docker on wsl2 right?.

**Comment by BenTheElder** [comment]
Yes, the request is to document using kind without using docker desktop, on WSL2.

I think we should keep this relatively short / lightweight, "how to install docker" is not really in scope for this project, but we should document that this is an option with WSL2.

**Comment by rakshitgondwal** [comment]
Hey @BenTheElder !!
I would like to work on this issue.

**Comment by hrittikhere** [comment]
Do we need to expand this section? CC: @BenTheElder 
I can touch on that! 

 <img width="1346" alt="image" src="https://user-images.githubusercontent.com/67012359/193919146-de413cd7-1051-438d-98a2-f01781649404.png">

**Comment by BenTheElder** [comment]
Yes, please do!

**Comment by hrittikhere** [comment]
Hey @BenTheElder 
Found this article: https://dev.solita.fi/2021/12/21/docker-on-wsl2-without-docker-desktop.html and I think it will be a good reference point. Do you feel going with Debian & apt will be okay for the first PR? Please advice

**Comment by BenTheElder** [comment]
I think we should prefer to document only that it is an option and link to external documentation.

We should not personally maintain "how to install docker on WSL2" ourselves, this is duplicated effort and Kubernetes SIG Docs prohibits this sort of thing for https://kubernetes.io

**Comment by hrittikhere** [comment]
Thanks @BenTheElder for the information! 

Something like:

## Setting up Docker in WSL2 without Docker Desktop 

- 2/3 Links for external blogs


Does this look good with a few more lines of information?
