### ISSUE TITLE
Control-Plane IP May Dismatch in Multi Kind Cluster Situation

### ISSUE THREAD

**Issue by bamboo12366** [kubernetes-sigs/kind#2784]
**What happened**:
I have two kind cluster in my local env. One control-plane(Cluster-A) ip is 172.19.0.2, the other one(Cluster-B) is 172.19.0.3
Once restart the docker, the control-plane ip may mismatched since the start flow maybe different: Cluster-A become 172.19.0.3, Cluster-B become 172.19.0.2.

The Controller-manager reporting following error msg since the cert unmatched:
`E0522 13:57:39.715038       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.PodDisruptionBudget: failed to list *v1beta1.PodDisruptionBudget: Get "https://172.19.0.2:6443/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0": x509: certificate is valid for 10.96.0.1, 172.19.0.3, 127.0.0.1, not 172.19.0.2`

**What you expected to happen**:
The ip should be consistent, or update the cert correspondingly

**How to reproduce it (as minimally and precisely as possible)**:
Restart the docker

**Anything else we need to know?**:
I am not that familiar with kind, maybe there are some configuration to help me solve that?

**Environment:**
MacOS
- kind version: (use `kind version`):
 0.10.0
- Kubernetes version: (use `kubectl version`):
 1.20
- Docker version: (use `docker info`):
 20.10.6
- OS (e.g. from `/etc/os-release`):
MacOS

**Comment by BenTheElder** [comment]
/triage duplicate
Follow current developments at https://github.com/kubernetes-sigs/kind/issues/2759

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/2045

**Comment by BenTheElder** [comment]
a fix for #2045 just landed
