### ISSUE TITLE
Hairpin not working with k8s v1.24 on minikube using HyperKit driver

### ISSUE THREAD

**Issue by spowelljr** [kubernetes-sigs/kind#2791]
Hi, I'm a minikube maintainer trying to get get the kindnet CNI working with k8s v1.24 for our next release.

## Expected Behavior
Hairpinning works with kindnet CNI with k8s v1.24 on minikube using the HyperKit driver

## Current Behavior
Hairpinning does not work with kindnet CNI with k8s v1.24 on minikube using the HyperKit driver

## Steps to Reproduce (for bugs)

```
# in minikube repo
$ gh pr checkout 14197

$ make

$ minikube start --driver hyperkit --memory 2048 --wait=true --wait-timeout=5m --cni=kindnet
...
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

$ minikube kubectl -- replace --force -f test/integration/testdata/netcat-deployment.yaml
deployment.apps/netcat replaced
service/netcat replaced

$ minikube kubectl -- exec deployment/netcat -- /bin/sh -c "nc -w 5 -i 5 -v -z localhost 8080"
Connection to localhost 8080 port [tcp/http-alt] succeeded!

$ minikube kubectl -- exec deployment/netcat -- /bin/sh -c "nc -w 5 -i 5 -v -z netcat 8080"
nc: connect to netcat port 8080 (tcp) timed out: Operation in progress
command terminated with exit code 1
```

## Context

All other drivers work with kindnet, so this seems to be specific to HyperKit

This also works fine with k8s version prior to v1.24

kindnet YAML: https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cni/kindnet.go#L30

## Your Environment

- kind version: (use `kind version`): `kindnetd:v20220510-4929dd75`
- Kubernetes version: (use `kubectl version`): `v1.24.0`
- Docker version: (use `docker info`): `20.10.16`
- OS (e.g. from `/etc/os-release`): minikube's custom Linux distro running on HyperKit

**Comment by aojea** [comment]
any logs you can share?

**Comment by aojea** [comment]
oh, but it doesn't work in calico too https://github.com/projectcalico/calico/issues/6186

Then it is not CNI specific, what means `specific to HyperKit` then

**Comment by BenTheElder** [comment]
I wonder if there's an issue with iptables-legacy/iptables-nft in this environment, did kube-proxy change the scripts in 1.24?

Locally I get:
```
$ kubectl exec deployment/netcat -- /bin/sh -c "nc -w 5 -i 5 -v -z localhost 8080"
nc: connect to localhost port 8080 (tcp) failed: Connection refused
Connection to localhost 8080 port [tcp/http-alt] succeeded!

[bentheelder@bentheelder:~·2022-06-06T13:26:17-0700]
$ kubectl exec deployment/netcat -- /bin/sh -c "nc -w 5 -i 5 -v -z 127.0.0.1 8080"
Connection to 127.0.0.1 8080 port [tcp/http-alt] succeeded!
```

(happy eyeballs?)

With kind v0.14.0 (default v1.24.0 node image) on Linux, I don't have hyperkit handy (no VMs permitted on work machine, have focused on Linux of late).

Also FWIW: While I'd like to get to the bottom of this and I appreciate the report: Disclaiming now that we do not test kindnetd outside of kind / in any other environments and don't advertise how to use it outside of kind.

**Comment by spowelljr** [comment]
> Then it is not CNI specific, what means `specific to HyperKit` then

@aojea 
It all runs inside a VM or container environment which we coin the `driver`, and in this case it's specifically failing when using HyperKit.

Here's a table of the tests
| OS | Arch | Driver | Container Runtime | Hairpinning Status |
| - | - | - | - | - |
| Linux | x86_64 | Docker | cri-docker | Passed |
| Linux | arm64 | Docker | cri-docker | Passed |
| Linux | x86_64 | Docker | containerd | Passed |
| Linux | arm64 | Docker | containerd | Passed |
| Linux | x86_64 | Docker | cri-o | Passed |
| Linux | arm64 | Docker | cri-o | Passed |
| Linux | x86_64 | KVM | cri-docker | Passed |
| Linux | x86_64 | KVM | containerd | Passed |
| Linux | x86_64 | KVM | cri-o | Passed |
| Window | x86_64 | Docker | cri-docker | Passed |
| Window | x86_64 | Hyper-V | cri-docker | Passed |
| macOS | x86_64 | Docker | cri-docker | Passed |
| macOS | x86_64 | HyperKit | cri-docker | Failed |
| macOS | x86_64 | HyperKit | containerd | Passed |
| macOS | x86_64 | HyperKit | cri-o | Passed |

I discovered this morning that it's specific also to just the cri-docker container runtime, so that's likely part of the puzzle.

**Comment by aojea** [comment]
Without logs or being able to reproduce is hard to know, is this running in some ci? Can you give us a link if it is running in a CI?

**Comment by BenTheElder** [comment]
Thanks for the table!

My suspicion at this point would be a cri-dockerd bug, affecting both kindnetd and calico.
I'm guessing this only showed up in 1.24 due to the switch after dockershim removal?

cri-dockerd could use more documentation 😬 

Are there any other differences between the KVM and hyperkit environments than the virtualization driver (e.g. different VM images with different contents, how different?)?

**Comment by WoodyWoodsta** [comment]
Have been following this issue, as well as a couple others opened in `flannel` and `calico`. I'm experiencing the same behaviour but with `cri-docker` on my own self-managed cluster (linux). That would support the fact that the two highlighted, common components are kubernetes itself, and `cri-docker`.

**Comment by spowelljr** [comment]
I found that this issue is caused by `cri-docker` hardcoding `HairpinMode` to `none`.
https://github.com/Mirantis/cri-dockerd/blob/60a25a1586890870cfdb9c160cb9d1dfc45a27d9/cmd/server.go#L154

I changed it to `promiscuous-bridge` and it succeeded. Thank you for your responses and sorry for the noise, feel free to close this issue at your discretion.
