### ISSUE TITLE
Kind timeout when preparing new node

### ISSUE THREAD

**Issue by vanhtuan0409** [kubernetes-sigs/kind#2793]
**What happened**:

Kind timeout when tail docker logs for node ready. Which in turn panicking as follow. Current VPN in used is Cloudflare WARP

```
Creating cluster "blackwood" ...
 ✓ Ensuring node image (kindest/node:v1.24.0) 🖼
 ✗ Preparing nodes 📦
panic: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"
```

I suspect this slowness is due to some corp VPN that is enforced on my machine

**What you expected to happen**:

Able to create a cluster

**How to reproduce it (as minimally and precisely as possible)**:

Turn on Cloudflare WARP with `warp-cli connect`
Try to create a cluster with `kind create cluster`

**Anything else we need to know?**:

30s timeout on docker tail logs might be too low. I tried to build a custom binary with increased timeout and is able to create a cluster without problems
https://github.com/kubernetes-sigs/kind/blob/main/pkg/cluster/internal/providers/docker/provision.go#L404
https://github.com/kubernetes-sigs/kind/blob/main/pkg/cluster/internal/providers/podman/provision.go#L375

If you guys are ok with the increased timeout to 90s, I can happily create a PR for this

**Environment:**

- kind version: `kind v0.14.0 go1.18.2 linux/amd64`
- Kubernetes version: 
```
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.24.1
```
- Docker version: (use `docker info`):
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., 2.6.0)

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 29
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 96df0994faabc1944fc614e52b0b3c6feb609a57.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.18.1-arch1-1
 Operating System: EndeavourOS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.44GiB
 Name: thinkpad
 ID: RATP:UU65:P33E:RWG4:7JDQ:FE7L:DOXS:SMB5:2Q43:QUJE:OYKS:QLYU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`):
```
NAME=EndeavourOS
PRETTY_NAME=EndeavourOS
ID=endeavouros
ID_LIKE=arch
BUILD_ID=2021.12.17
ANSI_COLOR="38;2;23;147;209"
HOME_URL='https://endeavouros.com'
DOCUMENTATION_URL='https://discovery.endeavouros.com'
SUPPORT_URL='https://forum.endeavouros.com'
BUG_REPORT_URL='https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports'
LOGO=endeavouros
```

**Comment by aojea** [comment]
> 30s timeout on docker tail logs might be too low. I tried to build a custom binary with increased timeout and is able to create a cluster without problems https://github.com/kubernetes-sigs/kind/blob/main/pkg/cluster/internal/providers/docker/provision.go#L404 https://github.com/kubernetes-sigs/kind/blob/main/pkg/cluster/internal/providers/podman/provision.go#L375
> 
> If you guys are ok with the increased timeout to 90s, I can happily create a PR for this

is this time taking into account the time to download the image? @BenTheElder do you remember?
if that is the case we can download the image and try to run it in 2 different steps and have better granularity on the timeouts

**Comment by vanhtuan0409** [comment]
@aojea based on the code, the 30s timeout does not include the time to download the image I think

Not sure what is taking too long for systemd to reach the Multi-User target

**Comment by BenTheElder** [comment]
I would like to see some more debugging on what is taking soong before tripling this limit, 30s is already meant to be very much in excess of the time needed to perform this step.

**Comment by vanhtuan0409** [comment]
found out why the node provision took so much time. The `entrypoint` script tries to resolve `host.docker.internal`, which unfortunately unhandled by the network VPN and becomes hang. It took 44s to finally timeout the `getent` command
https://github.com/kubernetes-sigs/kind/blob/main/images/base/files/usr/local/bin/entrypoint#L408
this is probably an issue of our VPN and not related to Kind. Just curious if you guys see any harm in increasing the timeout?
Otherwise can just go ahead and close this ticket

**Comment by BenTheElder** [comment]
> found out why the node provision took so much time. The entrypoint script tries to resolve host.docker.internal, which unfortunately unhandled by the network VPN and becomes hang. It took 44s to finally timeout the getent command

IMO _this_ is the kind bug we should fix, we should probably not let attempting to detect host.docker.internal take this long.

We should also probably inject NO_PROXY for this name.

**Comment by aojea** [comment]
hmm, I can't follow this

`host.docker.internal` is a local entry, and getent does a dns lookup checking the follow `strace`

```
futex(0x7f9bf56bd32c, FUTEX_WAKE_PRIVATE, 2147483647) = 0                                                                                                                                                                                                                    
openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 3                                                                                                                                                                                                                 
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=49, ...}, AT_EMPTY_PATH) = 0                                                                                                                                                                                                
read(3, "search lan\nnameserver 172.18.0.1"..., 4096) = 49                                                                                                                                                                                                                   
read(3, "", 4096)                       = 0
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=49, ...}, AT_EMPTY_PATH) = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/hosts", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=221, ...}, AT_EMPTY_PATH) = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "127.0.0.1\tlocalhost\n::1\tlocalhos"..., 4096) = 221
read(3, "", 4096)                       = 0
close(3)                                = 0
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 3
setsockopt(3, SOL_IP, IP_RECVERR, [1], 4) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.18.0.1")}, 16) = 0
poll([{fd=3, events=POLLOUT}], 1, 0)    = 1 ([{fd=3, revents=POLLOUT}])
sendto(3, "r\r\1\0\0\1\0\0\0\0\0\0\4host\6docker\10interna"..., 38, MSG_NOSIGNAL, NULL, 0) = 38
poll([{fd=3, events=POLLIN}], 1, 5000)  = 1 ([{fd=3, revents=POLLIN}])
ioctl(3, FIONREAD, [113])               = 0
recvfrom(3, "r\r\201\203\0\1\0\0\0\1\0\0\4host\6docker\10interna"..., 1024, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.18.0.1")}, [28 => 16]) = 113

```

to the local dns , that we are redirecting to the embedded docker dns

NO_PROXY is not influencing this part of the bootstrap

**Comment by vanhtuan0409** [comment]
yeah, I dont think NO_PROXY will take effect in DNS resolution. If we can set timeout on the `getent` command it would be great, but to my knowledge, there is no such option

**Comment by aojea** [comment]
> found out why the node provision took so much time. The `entrypoint` script tries to resolve `host.docker.internal`, which unfortunately unhandled by the network VPN and becomes hang. It took 44s to finally timeout the `getent` command

ah, just was going to ask that means "undhandled" :smile: 

we can add a timeout in the script

`timeout 5 getent ahostsv4 'host.docker.internal'`

**Comment by aojea** [comment]
nevermind we have fallback, @vanhtuan0409 do you want to submit a PR to add a timeout to the getent command?

```
TIMEOUT(1)                                                                                                                   User Commands                                                                                                                  TIMEOUT(1)

NAME
       timeout - run a command with a time limit

SYNOPSIS
       timeout [OPTION] DURATION COMMAND [ARG]...
       timeout [OPTION]

```

**Comment by vanhtuan0409** [comment]
Unhandle mean the nameserver just stuck there without giving the response back

**Comment by BenTheElder** [comment]
> we can add a timeout in the script

yes, that's what I meant, with `timeout`

and yes, because getent can fallback to a real lookup.

> NO_PROXY is not influencing this part of the bootstrap

right, proxy is not used for DNS lookup, but while thinking about this problem it also made me realize that this name should probably be in the list of NO_PROXY as well, which is unrelated but something else we're probably doing wrong with this domain.

**Comment by vanhtuan0409** [comment]
may I know with the PR is now merged, will all current node images be rebuilt?
if not, is there any way we can swap the base image for a specific node version?
cc @aojea @BenTheElder
