### ISSUE TITLE
First class image side-loading support

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#28]
This will be very useful for CI tasks. Currently this is achievable by adding image archives to a node image in `/kind/images/` but we should support this first-class.

cc @munnerz @sebastienvas

/kind feature
/priority important-longterm

/assign

**Comment by neolit123** [comment]
the pause image has a bit of a special case in terms of the kubelet:
https://github.com/kubernetes/kubeadm/issues/1186#issuecomment-433383514

**Comment by BenTheElder** [comment]
/lifecycle active
FYI @liztio

**Comment by BenTheElder** [comment]
Rough design I didn't finish implementing:
```
kind load docker-image [--name=clustername] [--nodes=] image...
kind load image-archive [--name=clustername] [--nodes=] /path/to/image.tar
```
- implicitly load to all nodes if `--nodes` is unset
- load to specific nodes if `--nodes` is a comma separated list of node of names

`kind load docker-image` should pipe `docker save image/name` on the host to loading on each of the nodes, IE essentially be `kind load image-archive <(docker save image)`.

**Comment by rohansingh** [comment]
@BenTheElder That seems very reasonable to me. I'm happy to do a first-pass on the implementation if nobody else is; being able to load images is a blocker for my use case.

**Comment by stevesloka** [comment]
I should have posted here @rohansingh but I just about have a PR ready to solve this.

**Comment by BenTheElder** [comment]
#309
https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

**Comment by rohansingh** [comment]
Thanks again @BenTheElder and @stevesloka. This is invaluable for the "local clusters on developer machines" use case.

**Comment by BenTheElder** [comment]
I hope it will make CI better as well!

kind uses a similar technique internally to load Kubernetes and avoid needing to push images when testing from Kubernetes source, so far that has been great 😄
