### ISSUE TITLE
Please update containerd to 1.6.6

### ISSUE THREAD

**Issue by skitt** [kubernetes-sigs/kind#2803]
**What would you like to be added**:

I would like containerd to be bumped to 1.6.6.

**Why is this needed**:

1.6.4 broke Weave support (see https://github.com/weaveworks/weave/issues/3942); this was fixed in containerd 1.6.5 (https://github.com/containerd/containerd/issues/6921, included in https://github.com/containerd/containerd/releases/tag/v1.6.5).

Additionally, 1.6.6 fixes [a memory exhaustion issue](https://github.com/containerd/containerd/security/advisories/GHSA-5ffw-gxpp-mxpf).

**Comment by BenTheElder** [comment]
/lifecycle active
fixing up the containerd-nightlies build first, then we can ship this.

**Comment by BenTheElder** [comment]
done in https://github.com/kubernetes-sigs/kind/pull/2811
