### ISSUE TITLE
Does KIND node share the host cpu and memory

### ISSUE THREAD

**Issue by morningspace** [kubernetes-sigs/kind#2805]
I just notice it looks the KIND nodes share the allocatable cpu and memory resource at the host level because when I describe the nodes, I can see each node has the allocatable cpu and memory equal to the host level allocatable cpu and memory, e.g.: say I have a machine w/ 16c 64G, all KIND nodes will have 16c 64G resource allocatable.

Because of this, the cpu and memory usage reported by metrics-server (installed after KIND is launched) seems to be misleading. The overall capacity is the actual host capacity multiplied by the node number. The more number of nodes I have, the larger value it is.

Wonder if this is the default behavior that is configurable or due to the nature of KIND mechanism, node simulated based on docker container?

**Comment by BenTheElder** [comment]
The latter, it may be possible to fix someday but it's more or less due to how kind works.

Multi node is really only suitable for testing some Kubernetes internals around rolling update behavior. It may rarely also be necessary for application testing for similar reasons.
But it is not for resource isolation, and using a single node is otherwise better.

**Comment by morningspace** [comment]
Thanks @BenTheElder for your prompt reply, it looks https://github.com/kubernetes-sigs/kind/issues/1524 also mentioned a similar use case where it has the workaround by modifying `kubeadmConfigPatches`. Wonder if that could be part of FAQ in KIND docs.

**Comment by BenTheElder** [comment]
That approach is a bit of a hack and I haven't yet been able to vouch for its effectiveness.

In general I think if you're trying to limit resources like this, you probably need VM or physical nodes at the moment.

**Comment by morningspace** [comment]
Thanks @BenTheElder and @aojea , with that, I'm going to close this issue as my initial question has been answered.
