### ISSUE TITLE
Silver Sparrow MacOS M1 virus detected by google antivirus in kind-darwin-amd64

### ISSUE THREAD

**Issue by mcooknu** [kubernetes-sigs/kind#2807]
I have found I can't download this file (or a zip file containing it) via Google Drive unless I am the owner of that file.
I found the virus tool google uses (https://www.virustotal.com/gui/home/url) and it mentions the file has a virus.

Furthermore, when I download it I get a different sha256 than that posted in the Kind release notes.

I have tried this on several different computers.  I'm not sure if the posted SHA is wrong, the file is being altered as I download it, or this is a false-positive on the KinD executable.

Any guidance welcome here as I did not experience this problem in earlier Kind releases.

**Comment by jpmcb** [comment]
@mcooknu - did you contact the maintainers per the security contact markdown file before opening this public issue?

```
# Defined below are the security contacts for this repo.
#
# They are the contact point for the Product Security Team to reach out
# to for triaging and handling of incoming issues.
#
# The below names agree to abide by the
# [Embargo Policy](https://github.com/kubernetes/sig-release/blob/master/security-release-process-documentation/security-release-process.md#embargo-policy)
# and will be removed and replaced if they violate that agreement.
#
# DO NOT REPORT SECURITY VULNERABILITIES DIRECTLY TO THESE NAMES, FOLLOW THE
# INSTRUCTIONS AT https://kubernetes.io/security/

BenTheElder
munnerz
```

I move we delete this issue and follow up with @BenTheElder

**Comment by BenTheElder** [comment]
To be clear: no official releases are hosted in Google Drive.

We should perhaps double check that the official releases unmodified aren't misflagged as a virus when re-hosting, I am reasonably confident that they're not compromised.

Official release binaries are hosted on GitHub.com at this time.

If the hash is different, something is wrong with your copy 👀 We should have fully reproducible builds, if you clone the repo and build from source with the makefile the hash should match what we published on the release page.

**Comment by jpmcb** [comment]
I am seeing something similar from google drive with kind:
![Screen Shot 2022-06-21 at 9 46 22 AM](https://user-images.githubusercontent.com/23109390/174842589-a027679a-eb86-473c-9913-3a947ca7f624.png)

_However_, I also am seeing it with other binaries (like this one I just built locally):
![Screen Shot 2022-06-21 at 9 47 33 AM](https://user-images.githubusercontent.com/23109390/174842679-2dd822ce-6fd8-4f32-8eca-43799e05a4b5.png)

Could be that whatever google drive is using is a bit over zealous for binary formats?

**Comment by BenTheElder** [comment]
I think we can safely say that kind releases aren't actually infected, and I would tentatively recommend against using google drive to distribute binaries.
