### ISSUE TITLE
Docker Image Caching

### ISSUE THREAD

**Issue by dvpatel** [kubernetes-sigs/kind#2808]
Hi There,

As a newbie, I'm pretty impressed with Kind.  Great work.  I do have a basic caching question.

I know kind/node image is cached in Docker Desktop.  But what about additional images that are installed after the cluster is created?  For instance, I'm installing Calico, Hashicorp Consul, BusyBox, etc..  but I do not see them in Docker Desktop.  Does this mean every time I reinstall said images, they'll be pulled from Docker image registry?

Reason I'm asking this is because there is a [docker pull rate limit ](https://www.docker.com/increase-rate-limit) that could get exhausted very quickly if Kind is not using image caching.  Also, where are images cached by Kind if not in Docker Desktop?

Thanks!
-Dipesh

**Comment by BenTheElder** [comment]
I think you also brought this to #kind in Kubernetes slack and we had a conversation there 

https://kubernetes.slack.com/archives/CEKK1KTN2/p1655931204838789
https://kubernetes.slack.com/archives/CEKK1KTN2/p1655931242103629

But basically for anyone else:
- they're pulled to the node's container runtime, which cannot be the host docker, it's a nested containerd within the node containers
- there are some options to avoid exhausting the limit, like authenticating the node runtimes, pulling the images to the host and using `kind load ...`

**Comment by dvpatel** [comment]
Hi Ben,

We did chat yesterday on Slack.

Thanks for the guidance.  I added docker [credentials to the nodes](https://kind.sigs.k8s.io/docs/user/private-registries/#add-credentials-to-the-nodes) and this worked fine as you suggested.

-Dipesh

**Comment by stmcginnis** [comment]
Any further action needed here? Or can this be closed out?

**Comment by dvpatel** [comment]
Please go ahead and close out the item.  Thanks for your support.

**Comment by stmcginnis** [comment]
Thanks Dipesh!
/close
