### ISSUE TITLE
Hello, how can I add port mapping to my kind to cope with my increasing container ports, and how can I add data volume mount to the cluster container started by kind?

### ISSUE THREAD

**Issue by new-coder-fei** [kubernetes-sigs/kind#2812]
您好，请问我该如何给我的kind增加端口映射来应对我不断增加的容器端口呢以及我该如何对kind启动的集群容器增加数据卷挂载呢？

Hello, how can I add port mapping to my kind to cope with my increasing container ports, and how can I add data volume mount to the cluster container started by kind?

**Comment by BenTheElder** [comment]
> Hello, how can I add port mapping to my kind to cope with my increasing container ports

https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings

> and how can I add data volume mount to the cluster container started by kind?

https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts

If you mean at runtime on a running cluster node / container, docker doesn't really support either of these. It's easiest to configure them before starting a cluster.
