### ISSUE TITLE
support KIND_CONFIG_FILE

### ISSUE THREAD

**Issue by pgmillon** [kubernetes-sigs/kind#2813]
**What would you like to be added**:
kind should support a KIND_CONFIG_FILE-like env variable as a CLI UX improvement.

**Why is this needed**:
While working with tools like direnv within a team, dev clusters creation could be limited to running `kind create cluster` with a side config file that kind would read rather than `kind create cluster --config /path/to/file.yml`

**Comment by BenTheElder** [comment]
Isn't `kind create cluster --config $KIND_CONFIG_FILE` already doable without needing to write out the path?

I don't love the implications adding this has for reproducibility with simple test workflows that aren't passing a config today. If the user has accidentally left a KIND_CONFIG_FILE set then the results won't match running elsewhere and it may be difficult to identify that this is what happened. Config files have a *major* effect. I'm concerned this has the potential to waste a lot of time for folks receiving bug reports etc.

The existing env kind reads map to options that would need to be passed to most / all commands (--name) and are unlikely to affect reproducibility, or a few experimental options for power users that we're not committed to yet, or actual local environment like system proxy settings.

**Comment by BenTheElder** [comment]
Doesn't seem to be demand for this and we want to keep complexity down when there's alternatives and low demand as the existing bits are already rather tricky to maintain. Closing for now.
