### ISSUE TITLE
Can't pull an image from a local registry

### ISSUE THREAD

**Issue by oatmealb** [kubernetes-sigs/kind#2814]
**What steps did you take and what happened:**
When following the [Local Registry > Create A Cluster And Registry](https://kind.sigs.k8s.io/docs/user/local-registry/#create-a-cluster-and-registry) guide section, I ran the provided `.sh` script and got
```
Error response from daemon: network kind not found
```

If I "manually" `docker network create kind`, this guide section (seemingly) works. But then the next section, [Using The Registry](https://kind.sigs.k8s.io/docs/user/local-registry/#using-the-registry) fails as the pod can't pull the `hello-app` image:
```sh
kubectl logs hello-server-<someID>
Error from server (BadRequest): container "hello-app" in pod "hello-server-<someID>" is waiting to start: trying and failing to pull image
```

**What did you expect to happen:**
The `google-samples/hello-app` runs successfully, with the locally pulled image.

**Anything else you would like to add:**

```sh
> kubectl cluster-info --context kind-kind
Kubernetes control plane is running at https://127.0.0.1:43831
KubeDNS is running at https://127.0.0.1:43831/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```
I've attached 'kubectl cluster-info dump' output.

**Environment:**

- minikube/kind version: 0.6.1 (installed via [asdf](https://asdf-vm.com/))
- Kubernetes version: (use `kubectl version`): v1.16.3
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.2 LTS
- Docker version 20.10.7, build f0df350
 
[cluster-info_dump.log](https://github.com/kubernetes-sigs/cluster-api/files/8990539/cluster-info_dump.log)

**Comment by BenTheElder** [comment]
v0.6.1 is from December 2019, 2.5 years old.
