### ISSUE TITLE
kind load with podman provider fails 

### ISSUE THREAD

**Issue by thatsbrandon** [kubernetes-sigs/kind#2816]
**What happened**: `kind` fails to load an image built by podman. Since I'm using podman I don't need to have a docker daemon running

**What you expected to happen**: Have an image loaded from podman into `kind`'s image archive

**How to reproduce it (as minimally and precisely as possible)**:
1.  KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster
2. Once the container in running, load an image into `kind` using the following command `kind load image-archive ./image-tars/backend-0.1.tar`
3. I even tried running the previous command with 'KIND_EXPERIMENTAL_PROVIDER=podman' and I still get the following error.

Running the following commands will throw the following error:
```bash
ERROR: failed to list nodes: command "docker ps -a --filter label=io.x-k8s.kind.cluster=kind --format '{{.Names}}'" failed with error: exit status 1
Command Output: Cannot connect to the Docker daemon at unix:///home/node001/.docker/desktop/docker.sock. Is the docker daemon running?
```

**Environment:**

- kind version: (use `kind version`): 0.14.0
- Kubernetes version: (use `kubectl version`): v1.24.2
- Docker version: (use `docker info`): not using docker; podman version: 4.1.1
- OS (e.g. from `/etc/os-release`): Fedora Linux 36

**Comment by BenTheElder** [comment]
this command doesn't support podman, it's for docker and predates limited podman support.
see previous discussion in the tracker.

**Comment by BenTheElder** [comment]
You do need to continue to set the environment variable if docker I'd also installed.

Kind should detect podman vs docker though. I suspect podman changed on us again.

**Comment by BenTheElder** [comment]
Is the docker cli installed?

**Comment by thatsbrandon** [comment]
After doing some digging, having docker running on the background was throwing off the `kind load image-archive ./image-tars/backend-0.1.tar` command. Killing the docker process & then restarting podman fixed the issue I had. I was able to load a tar image into a kind container podman was managing.

**Comment by thatsbrandon** [comment]
Hmm that is strange! Luckily I got it to work, next time I'll remember not to have Docker running in the background since that causes the conflict even when I explicitly added "KIND_EXPERIMENTAL_PROVIDER"
