### ISSUE TITLE
Please document need for add. RPMs with CNI plugins when using podman in Fedora Silverblue 36

### ISSUE THREAD

**Issue by Unveraenderbar** [kubernetes-sigs/kind#2821]
**Under Fedora 36 Silverblue, additional RPMs containing CNI plugins have to be installed in order to get a kind cluster up**:
For release 36, the Fedora Silverblue team decided to remove the RPMs "containernetworking-plugins" and "podman-plugins" from the default OS image base layer (they were included in earlier Silverblue releases).  
As a consequence, before adding these packages e.g. by
```
rpm-ostree install containernetworking-plugins podman-plugins
```
and rebooting into the extended image, ```kind install``` will fail as the internal network is not functional.
I'd like to suggest to add a note on this to the documentation on using podman as runtime for kind.

**Comment by Unveraenderbar** [comment]
Yes, I think that's true... I also thought already about opening an issue against the Sivlerblue 36 OS base layer set.
But as the Fedora toolbox works w/o problems, stripping the CNI plugins from the base layer might have been done deliberately so I thought adding a note to the kind documentation could be useful.

**Comment by BenTheElder** [comment]
This doesn't really sound in-scope, this sounds like the Linux distro botched upgrades and should document it ... We're not even telling podman we want any particular networking implementation just that we want a network.

**Comment by BenTheElder** [comment]
I think "existing containers are not broken by OS / package upgrade" is very much something the OS / package should be handling ...

**Comment by aojea** [comment]
it seems we have to add a new additional check on the podman provider based on the linked issue https://github.com/kubernetes-sigs/kind/issues/2821#issuecomment-1172192044

> Please run and check podman info (shortcut: podman info | grep -i -A3 net) to see what networking mode you use. If it still says CNI, you should likely switch.

**Comment by BenTheElder** [comment]
We could add another "known issues" entry, as we already have a section dedicated to Fedora breakages, but I think this is something that should be fixed in the upstream packaging. If podman is still defaulting to CNI as https://discussion.fedoraproject.org/t/how-to-get-podman-dns-plugin-container-name-resolution-to-work-in-fedora-coreos-36-podman-plugins-podman-dnsname/39493/6#why-does-not-it-switch-by-default-4 says, then it really ought to keep shipping the required binaries??

**Comment by BenTheElder** [comment]
I think we're leaving this to podman x Fedora. This isn't a kind issue.
