### ISSUE TITLE
Why cluster failed on Ubuntu 20.04? ERROR: failed to create cluster: failed to init node with kubeadm

### ISSUE THREAD

**Issue by MilenkoMarkovic** [kubernetes-sigs/kind#2842]
My yaml file
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
```

**What happened**:

Tried with
`sudo kind create cluster --name multi-node --config=kind-example-config.yaml`

got 
```
Creating cluster "multi-node" ...
 ✓ Ensuring node image (kindest/node:v1.24.0) 🖼
 ✓ Preparing nodes 📦 📦 📦  
 ✓ Writing configuration 📜 
 ✗ Starting control-plane 🕹️ 
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged multi-node-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 137
Command Output: I0727 08:27:25.051883      53 initconfiguration.go:255] loading configuration from "/kind/kubeadm.conf"
W0727 08:27:25.054684      53 initconfiguration.go:332] [config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta3, Kind=JoinConfiguration
[init] Using Kubernetes version: v1.24.0
[certs] Using certificateDir folder "/etc/kubernetes/pki"
I0727 08:27:25.057020      53 certs.go:112] creating a new certificate authority for ca
[certs] Generating "ca" certificate and key
I0727 08:27:25.234167      53 certs.go:522] validating certificate period for ca certificate
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local localhost multi-node-control-plane] and IPs [10.96.0.1 172.27.0.8 127.0.0.1]
[certs] Generating "apiserver-kubelet-client" certificate and key
I0727 08:27:25.485067      53 certs.go:112] creating a new certificate authority for front-proxy-ca
[certs] Generating "front-proxy-ca" certificate and key
I0727 08:27:25.566516      53 certs.go:522] validating certificate period for front-proxy-ca certificate
[certs] Generating "front-proxy-client" certificate and key
I0727 08:27:25.611657      53 certs.go:112] creating a new certificate authority for etcd-ca
[certs] Generating "etcd/ca" certificate and key
I0727 08:27:25.705885      53 certs.go:522] validating certificate period for etcd/ca certificate
```

**What you expected to happen**:

I expected multinode cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**
5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

- kind version: (use `kind version`):
- kind v0.14.0 go1.18.2 linux/amd64
- Kubernetes version: (use `kubectl version`):
```
-Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version: (use `docker info`):
- 20.10.17
- OS (e.g. from `/etc/os-release`):
- Ubuntu 20.04

**Comment by aojea** [comment]
do you have enough cpu and memory?

**Comment by MilenkoMarkovic** [comment]
Yes,that was isssue,I deleted some old clusters.

**Comment by MilenkoMarkovic** [comment]
No,actually it did not solve anything.
```
free -m
              total        used        free      shared  buff/cache   available
Mem:          15329        8694        2567         133        4067        6181
Swap:          2047        1531         516

Again
```
ERROR: failed to create cluster: failed to join node with kubeadm: command "docker exec --privileged mmulti-node-worker2 kubeadm join --config /kind/kubeadm.conf --skip-phases=preflight --v=6" failed with error: exit status 1
Command Output: I0727 08:59:26.209753     255 join.go:413] [preflight] found NodeName empty; using OS hostname as NodeName
I0727 08:59:26.209781     255 joinconfiguration.go:76] loading configuration from "/kind/kubeadm.conf"
I0727 08:59:26.210609     255 controlplaneprepare.go:220] [download-certs] Skipping certs download
I0727 08:59:26.210623     255 join.go:530] [preflight] Discovering cluster-info
I0727 08:59:26.210640     255 token.go:80] [discovery] Created cluster-info discovery client, requesting info from "mmulti-node-control-plane:6443"
I0727 08:59:26.238027     255 round_trippers.go:553] GET https://mmulti-node-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 26 milliseconds
I0727 08:59:26.238540     255 token.go:

Then it shows
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.

Unfortunately, an error has occurred:
```
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
It seems that kubelet is issue
systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-07-27 11:04:21 CEST; 8s ago
       Docs: https://kubernetes.io/docs/home/
    Process: 165906 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, st>
   Main PID: 165906 (code=exited, status=1/FAILURE)

```


```
```

**Comment by zaunist** [comment]
Hi, @MilenkoMarkovic. I have follow your step, but can't reproduce your issue.

kind version: kind v0.14.0 go1.18.3 linux/amd64

os: ubuntu 20.04 WSL2



![image](https://user-images.githubusercontent.com/38528079/181212010-3707d924-ce21-421e-9c57-531c47a0fdea.png)

**Comment by MilenkoMarkovic** [comment]
Hi @zaunist 

which kubectl version is yours?

**Comment by zaunist** [comment]
> 

IMO, this is not related to the version of kubectl.

kubectl: 
![image](https://user-images.githubusercontent.com/38528079/181219839-a54ea72e-5a6e-4383-87cf-60909ccec32b.png)

**Comment by BenTheElder** [comment]
can you please try to find the minimum reproducer (e.g. does this fail with only one node?) and use `kind create cluster --retain; kind export logs; kind delete cluster` to capture the node logs so we can investigate why kubelet isn't healthy?

**Comment by MilenkoMarkovic** [comment]
Works now after 
`kind delete clusters multi-node`
and with --retain.

**Comment by BenTheElder** [comment]
`--retain` only prevents cleanup on failure, so it seems likely that the issue is something with multi-node cluster(s), possibly resource exhaustion. resource exhaustion has dimensions other than CPU / RAM, e.g. inotify watch limits.

does, for example, a single two node cluster work?

**Comment by BenTheElder** [comment]
Also: FWIW: without a niche, specific use case, I highly recommend single node clusters. KIND nodes do not have proper resource isolation, multi-node is typically only needed to test complex multi-node rolling behavior for distributed apps.

**Comment by MilenkoMarkovic** [comment]
@BenTheElder Thanks,I will go for single node clusters.

**Comment by BenTheElder** [comment]
I suspect this was a resource exhaustion issue, happy to follow up further in the future if we have more logs / info to debug.
