### ISSUE TITLE
How to Add fully qualified domain to kind k8s nodes

### ISSUE THREAD

**Issue by darint00** [kubernetes-sigs/kind#2843]
I've tried creating my cluster using the following kind config.yaml

apiVersion: kind.x-k8s.io/v1alpha4

kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  networking:
    dnsDomain: "mydomain.helm-testing.svc.cluster.local"

networking:
  ipFamily: ivp6
nodes:
- role: control-plane
- role: worker

hostname --fqdn  Still shows only kind-worker and no full domain

Please HELP!!!  I figure I'm close, just something is off a bit.

**Comment by BenTheElder** [comment]
dnsDomain relates to the in-cluster DNS resolver in Kubernetes -- in this case the coreDNS instance(s) that pods will typically route requests to.

`hostname` is going to report the node's hostname as configured locally, which will be the name of the node. this is not configurable, and typically isn't in other kubernetes tools either. 

applications typically run in pods though, not directly on the node, and will have their own networking configuration.

what's your use case?

**Comment by darint00** [comment]
I am using kind and installing a product that uses a license manager that
uses a fully qualified host name.  My nodes don't show the domain so I'm
trying to configure the nodes so that they have the domain set.

**Comment by BenTheElder** [comment]
Ouch 😞 

Does the product run within a pod or on the node directly? If the latter, can you run it as a pod?

Pods have pretty flexible hostname control:
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-sethostnameasfqdn-field

**Comment by darint00** [comment]
It runs in a pod and the pod does reflect the domain name. But the way the
license manager works, im told, is that it checks the domain of the node it.

Which is why I'm trying find out how to configure the domain at the node
level.

So if there is any way to configure this, this would be extremely helpful.

**Comment by aojea** [comment]
> Pods have pretty flexible hostname control:
> https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-sethostnameasfqdn-field

this feature Ben is indicating was added to solve this problem you are mentioning, 

https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/1797-configure-fqdn-as-hostname-for-pods/README.md#motivation

the process in the pod can not escape the network namespace of the pod, I can't see how it can check the node domain

Anyway, if you still want to configure the domain at node level , you have to change this kubelet parameter

> --cluster-domain string
> Domain for this cluster. If set, kubelet will configure all containers to search this domain in addition to the host's search domains (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See kubelet-config-file for more information.)

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by BenTheElder** [comment]
To be more clear: The node hostname is not configurable in kind.

It will not be configurable, Kubernetes applications should **not** be using this, production clusters typically will not have FQDN either.

> It runs in a pod and the pod does reflect the domain name. But the way the
license manager works, im told, is that it checks the domain of the node it.

If it's running in a pod, it should not be able to see the node name 🤔  

The pod has it's own network namespace, unless for some reason it is a hostNetwork pod, which is a very privileged thing that should be restricted to system networking daemons only.

In the same sense, the kind nodes are themselves also containers, and should not reveal the actual host name for the underlying host.

More details about how the app runs or is installed may let us help.
