### ISSUE TITLE
Stop shipping EOL Ubuntu releases in kindest:node

### ISSUE THREAD

**Issue by smst329** [kubernetes-sigs/kind#2845]
What would you like to be added**: Please stop shipping end-of-life os releases for kindest:node.

**Why is this needed**: Pulling the most recent image kindest:node image listed on this repos page releases page and the most recent release listed at docker hub as of today, downloads a container where the OS release is EOL. Being EOL, anything that needed to be patched could not be easily patched by the OSes package manager. I get that in closed issue 1978 it is stated that images are not meant to be mutated. While the argument against LTS releases is sound, if one did need to say apply a security patch, the consequence of an EOL release means that using the OSes package manager to apply an update may not work. There is no need to go LTS, but please stop shipping containers built on EOL distro releases as the most current release. Please just use any OS of your choosing with any version as long as that version is not considered EOL.

**Comment by BenTheElder** [comment]
We’ve already updated the base image and all future node images will be built with a newer Ubuntu distro.

you can build new ones yourself now if you wish, there’s a guide in the docs

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/2837

**Comment by BenTheElder** [comment]
[agree we should not be shipping EOL]

**Comment by smst329** [comment]
Thanks! Sorry I didn't see 2837, searched on EOL instead of EOL spelled out.

**Comment by BenTheElder** [comment]
No worries, someday GitHub search will be smarter :-)
