### ISSUE TITLE
apisix-ingress-controller support

### ISSUE THREAD

**Issue by caniko** [kubernetes-sigs/kind#2860]
**What would you like to be added**:
Support for apisix, I made an [issue](https://github.com/apache/apisix-ingress-controller/issues/1209) on their end

**Comment by BenTheElder** [comment]
We allow contributions to our docs for documenting ingresses but recent experience has suggested that adding more of these in our own docs is not helpful and leads to stale, broken docs https://github.com/kubernetes-sigs/kind/issues/2856

We do not have the time to maintain docs for every ingress controller out there, unfortunately.

The general ingress install guide should outline how ingresses are installed and the same techniques can be applied to additional ingresses.

In this case, apisix already maintains multiple guides for installing in various tools in their repo, if they wish to support kind i'm happy to provide some guidance but I'd prefer not to host and maintain it.

**Comment by BenTheElder** [comment]
it is documented in the apisix repo 🙏

**Comment by tao12345666333** [comment]
https://github.com/apache/apisix-ingress-controller/issues/1209#issuecomment-1205567095

@BenTheElder Would you be happy to accept the PR if I could actively maintain documentation about the deployment of the APISIX Ingress controller on KIND ?
