### ISSUE TITLE
Node images built on depracted Ubuntu version can't have new packages installed

### ISSUE THREAD

**Issue by raesene** [kubernetes-sigs/kind#2863]
**What happened**:

I have some images based on KinD node images, where I add python3 (to ease use in ansible playbooks). My standad workflow is to start an image with a `FROM` line of the node image then `apt update && apt install -y python3`.

Using the newest node images this generates an error as `apt update` fails. This appears to be due to the deprecation of Ubuntu 21.10 .

Sample Error message :-
```
E: The repository 'http://security.ubuntu.com/ubuntu impish-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**What you expected to happen**:

Adding packages to a KinD node image using apt works

**How to reproduce it (as minimally and precisely as possible)**:

```
docker run -it --entrypoint=/bin/bash kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e
```
```
apt update
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): kind v0.14.0 go1.18.2 linux/amd64
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
- Docker version: (use `docker info`): 20.10.17
- OS (e.g. from `/etc/os-release`): "20.04.4 LTS (Focal Fossa)"

**Comment by BenTheElder** [comment]
We’ve already upgraded the base image going forward (see past issues) but also FWIW the node image is only advertised as being able to run Kubernetes and we reserve the right to alter it in the future, installing packages to Kubernetes nodes is not portable and we’ve switched distros before.

**Comment by BenTheElder** [comment]
There's a new v1.24.3 image coming built with the new base image as part of https://github.com/kubernetes-sigs/kind/pull/2869 ahead of v0.15.0.

**Comment by raesene** [comment]
cool thanks!
