### ISSUE TITLE
kind load docker-image error

### ISSUE THREAD

**Issue by NUAAMETEOR** [kubernetes-sigs/kind#2864]
When I use kind to load an image into cluster,the console reports errors below:

# kind load docker-image hashicorp/http-echo:0.2.3 --name ak47                                                                                    
Image: "hashicorp/http-echo:0.2.3" with ID "sha256:a6838e9a6ff6ab3624720a7bd36152dda540ce3987714398003e14780e61478a" not yet present on node "ak47-worker2", loading...
Image: "hashicorp/http-echo:0.2.3" with ID "sha256:a6838e9a6ff6ab3624720a7bd36152dda540ce3987714398003e14780e61478a" not yet present on node "ak47-worker", loading...
Image: "hashicorp/http-echo:0.2.3" with ID "sha256:a6838e9a6ff6ab3624720a7bd36152dda540ce3987714398003e14780e61478a" not yet present on node "ak47-control-plane", loading...
ERROR: failed to load image: command "docker exec --privileged -i ak47-worker ctr --namespace=k8s.io images import --digests --snapshotter=overlayfs -" failed with error: exit status 1
Command Output: ctr: image might be filtered out

environment:
OS: Ubuntu 22.04 ARM
Memory: 4G
Mother board: raspberry 4B

**Comment by BenTheElder** [comment]
This is because hashicrop/http-echo:0.2.3 is only built for linux/amd64 but you're on linux/arm64

the error could be less obtuse "ctr: image might be filtered out" is a symptom of the non-matching architecture being ignored on the containerd side.

**Comment by NUAAMETEOR** [comment]
Thanks a lot~
After I added --platform=linux/arm64 parameter and used image httpd ,it works

**Comment by NUAAMETEOR** [comment]
> This is because hashicrop/http-echo:0.2.3 is only built for linux/amd64 but raspberry pi is linux/arm64
> 
> https://hub.docker.com/r/hashicorp/http-echo/tags
> 
> the error could be less obtuse "ctr: image might be filtered out" is a symptom of the non-matching architecture being ignored on the containerd side.
Thanks a lot~
After I added --platform=linux/arm64 parameter and used image httpd ,it works
