### ISSUE TITLE
Documentation: display installation instructions for arm64 linux machines

### ISSUE THREAD

**Issue by jpmcb** [kubernetes-sigs/kind#2866]
**What would you like to be documented**:

Currently, only x86 installation instructions are present. It'd be nice if the arm install instructions were next to the x86 ones (similar to how the mac m1 vs intel instructions are next to eachother)

Something like:

---

_On Linux:_
```bash
# For x86 architecture:
curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64
# For arm architecture:
curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-arm64
chmod +x ./kind
sudo mv ./kind /usr/local/bin/kind
```

**Why is this needed**:

When I installed kind on a new-ish arm dev machine, I used the instructions (without reading them super hard) for x86 which resulted in error when attempting to run that binary.

I'd be happy to submit a patch for this if it sounds good! 🚀

**Comment by BenTheElder** [comment]
I worry about making this documentation 10 pages of confusing instructions 😞 

Let's at least use uname as well to make it possible to continue pasting the whole code block

**Comment by jpmcb** [comment]
> I worry about making this documentation 10 pages of confusing instructions

Yeah, seems to be the world we live in these days 😭

`uname` is a good idea since the names of kind's releases differ from the name returned by uname for arm:

```
❯ uname --machine
aarch64
```

**Comment by BenTheElder** [comment]
I was just taking a peek at this again and the kind docs actually do this already for macOS with `[ $(uname -m) = x86_64] && ...` etc., we should be able to adapt that.

**Comment by jpmcb** [comment]
Sounds good! /assign

**Comment by afbjorklund** [comment]
As long as we are copy/paste-ing instructions instead of letting the computer do it, we used JavaScript in minikube to make the selection less cluttered...

**Comment by BenTheElder** [comment]
> As long as we are copy/paste-ing instructions instead of letting the computer do it, we used JavaScript in minikube to make the selection less cluttered...

The macOS docs have the computer do it ...

```shell
# for Intel Macs
[ $(uname -m) = x86_64 ]&& curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.18.0/kind-darwin-amd64
# for M1 / ARM Macs
[ $(uname -m) = arm64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.18.0/kind-darwin-arm64
chmod +x ./kind
mv ./kind /some-dir-in-your-PATH/kind
```

**Comment by BenTheElder** [comment]
NOTE: `uname -m` values for arm64  are not the same on mac and Linux! https://unix.stackexchange.com/questions/683360/why-does-hostnamectl-return-arm64-but-uname-returns-aarch64-ubuntu-20-04-2-on

**Comment by BenTheElder** [comment]
This is done.

**Comment by jpmcb** [comment]
Thanks Ben! ❤️
