### ISSUE TITLE
feat:  add 'help' info to Makefile 

### ISSUE THREAD

**Issue by zaunist** [kubernetes-sigs/kind#2871]
**What would you like to be added**:

Add help prompt in Makefile, just like this

![image](https://user-images.githubusercontent.com/38528079/183546254-ca783a9e-4a9f-4787-9f53-dc6fd1419737.png)

**Why is this needed**:

After I clone the repository, I want to build or run the test first, but I don't know which make command to use, so I need to check in the makefile, if we can add help information to the makefile, this can be used in the development project more convenient.

kubernetes makefile

https://github.com/kubernetes/kubernetes/blob/25a3274a4f62be0d37937c069007cedb3116e467/build/root/Makefile#L537

**Comment by BenTheElder** [comment]
FWIW in the meantime: 

https://github.com/kubernetes-sigs/kind#community and https://github.com/kubernetes-sigs/kind/blob/main/CONTRIBUTING.md

link to https://kind.sigs.k8s.io/docs/contributing/getting-started/

which covers kind development in detail

**Comment by zaunist** [comment]
Yes, this is a great guide.

**Comment by zaunist** [comment]
Yes, this is a great guide.
