### ISSUE TITLE
kind load image-archive xx1.tar xx2.tar , cannot find xx2.tar's image in container of kind-node

### ISSUE THREAD

**Issue by YunShiHang** [kubernetes-sigs/kind#2881]
**What happened**:
docker pull ghcr.io/kubean-io/kubean/spray-job:v0.1.0
docker pull ghcr.io/kubean-io/kubean/kubean-operator:v0.1.0
docker save ghcr.io/kubean-io/kubean/spray-job:v0.1.0       > kubean-job-v0.1.0.tar
docker save ghcr.io/kubean-io/kubean/kubean-operator:v0.1.0 > kubean-operator-v0.1.0.tar

cat /tmp/kind_config.yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80

kind create cluster --name my-mgmt-cluster-installer --image kindest/node:v1.21.1 --config /tmp/kind_config.yaml

kind load image-archive offline/kubean/kubean-job-v0.1.0.tar offline/kubean/kubean-operator-v0.1.0.tar --name=my-mgmt-cluster-installer

####it's happened:####
docker exec -it my-mgmt-cluster-installer-control-plane bash
crictl images|grep kubean
![企业微信截图_16607079917370](https://user-images.githubusercontent.com/85267027/185032205-571ca000-a81e-418c-b00b-d00b0ba7dce1.png)

####I'll import it offline/kubean/kubean-operator-v0.1.0.tar####

kind load image-archive offline/kubean/kubean-operator-v0.1.0.tar --name=my-mgmt-cluster-installer

####it's happened:####
docker exec -it my-mgmt-cluster-installer-control-plane bash
crictl images|grep kubean
![企业微信截图_16607080606723](https://user-images.githubusercontent.com/85267027/185032115-da1032f2-0e59-48e7-8521-99f51434e07c.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
kind v0.14.0 go1.18.2 linux/amd64

- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

- Docker version: (use `docker info`):
Client: Docker Engine - Community
 Version:           20.10.17
Server: Docker Engine - Community
 Engine:
  Version:          20.10.17

- OS (e.g. from `/etc/os-release`):
[root@shihang-operation ~/dce5-installer/offline]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by harshanarayana** [comment]
@YunShiHang  That is because the code only seem to support loading one archive at a time. 

https://github.com/kubernetes-sigs/kind/blob/74a8ae82b36e815bff02a7d839c1d518532c922d/pkg/cmd/kind/load/image-archive/image-archive.go#L82-L86

https://github.com/kubernetes-sigs/kind/blob/74a8ae82b36e815bff02a7d839c1d518532c922d/pkg/cmd/kind/load/image-archive/image-archive.go#L120-L126

This can be fixed.

/assign

**Comment by BenTheElder** [comment]
FYI you can docker save two images to one tarball which is also more efficient as it deduplicates shared layers

**Comment by YunShiHang** [comment]
> FYI you can docker save two images to one tarball which is also more efficient as it deduplicates shared layers

Thanks，It has been very helpful to me

**Comment by YunShiHang** [comment]
> @YunShiHang That is because the code only seem to support loading one archive at a time.
> 
> https://github.com/kubernetes-sigs/kind/blob/74a8ae82b36e815bff02a7d839c1d518532c922d/pkg/cmd/kind/load/image-archive/image-archive.go#L82-L86
> 
> https://github.com/kubernetes-sigs/kind/blob/74a8ae82b36e815bff02a7d839c1d518532c922d/pkg/cmd/kind/load/image-archive/image-archive.go#L120-L126
> 
> This can be fixed.
> 
> /assign

Thanks
