### ISSUE TITLE
Kind create cluster fails with 3 worker nodes

### ISSUE THREAD

**Issue by webmutation** [kubernetes-sigs/kind#2886]
**What happened**:
Kind works well with one node
Kind fails to start with 3 nodes

```
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
```

ERROR: failed to create cluster: failed to join node with kubeadm: command "docker exec --privileged kind-worker kubeadm join --config /kind/kubeadm.conf --skip-phases=preflight --v=6" failed with error: exit status 1
Command Output: I0817 20:43:55.327526     140 join.go:413] [preflight] found NodeName empty; using OS hostname as NodeName
I0817 20:43:55.327545     140 joinconfiguration.go:76] loading configuration from "/kind/kubeadm.conf"
I0817 20:43:55.328132     140 controlplaneprepare.go:220] [download-certs] Skipping certs download
I0817 20:43:55.328139     140 join.go:530] [preflight] Discovering cluster-info
I0817 20:43:55.328147     140 token.go:80] [discovery] Created cluster-info discovery client, requesting info from "kind-control-plane:6443"
I0817 20:44:05.330815     140 round_trippers.go:553] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s  in 10002 milliseconds
I0817 20:44:05.330924     140 token.go:217] [discovery] Failed to request cluster-info, will try again: Get "https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**What you expected to happen**:
The worker nodes to join the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Ubuntu 22.04 LTS 
sudo kind create cluster --config kind3node.yaml 

**Environment:**

- kind version: (use `kind version`):
kind v0.14.0 go1.18.2 linux/amd64

- Kubernetes version: (use `kubectl version`):
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

- Docker version: (use `docker info`):
Client:
Context:    default
Debug Mode: false
Plugins:
 app: Docker App (Docker Inc., v0.9.1-beta3)
 buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
 compose: Docker Compose (Docker Inc., v2.6.0)
 scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 16
  Running: 1
  Paused: 0
  Stopped: 15
 Images: 8
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-46-generic
 Operating System: Ubuntu Core 18
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 46.87GiB
 Name: lw202047160
 ID: AC7O:PJ7Y:QQCI:Y2FY:V362:ZHCW:MQNQ:EMGI:GYVN:DPIM:ZQKJ:LNRO
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

- OS (e.g. from `/etc/os-release`):

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

OS: Ubuntu 22.04.1 LTS x86_64 
Kernel: 5.15.0-46-generic 
Packages: 2562 (dpkg), 27 (flatpak), 23 (snap) 
Shell: bash 5.1.16 
CPU: Intel Xeon E-2286M (16) @ 5.000GHz 
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
Memory: 4907MiB / 47991MiB  (46.8GiB)

**NOTE**
VPN is off

I have seen similar issues, but I was not able to find the solution, since I am not using firewalld. 
I can connect from a docker container to the internet, and to other containers. 
I am able to ping them and connect for example to nginx example container.

Here is as well the Docker network for Kind

```
{
    "Name": "kind",
    "Id": "9c2a657b3c1c27aaae8402fb4b97171e768c057f5360b53d01236894bbc15ae6",
    "Created": "2022-08-17T20:35:26.507999804+02:00",
    "Scope": "local",
    "Driver": "bridge",
    "EnableIPv6": true,
    "IPAM": {
        "Driver": "default",
        "Options": {},
        "Config": [
            {
                "Subnet": "172.18.0.0/16",
                "Gateway": "172.18.0.1"
            },
            {
                "Subnet": "fc00:f853:ccd:e793::/64",
                "Gateway": "fc00:f853:ccd:e793::1"
            }
        ]
    },
    "Internal": false,
    "Attachable": false,
    "Ingress": false,
    "ConfigFrom": {
        "Network": ""
    },
    "ConfigOnly": false,
    "Containers": {},
    "Options": {
        "com.docker.network.bridge.enable_ip_masquerade": "true",
        "com.docker.network.driver.mtu": "1500"
    },
    "Labels": {},
    "CreatedTime": 1660761326507
}
```

**Comment by webmutation** [comment]
The only strange thing that I notice is inside the nodes the DNS config does not seem to be the same I have in my host

cat /etc/resolv.conf
search home
nameserver 172.18.0.1
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
options edns0 trust-ad ndots:0

in host I have

nameserver 127.0.0.53
options edns0 trust-ad
search home

so it seems to me there is something wrong with the DNS config of the kind network. Its not able to reach the internet or resolve the DNS name kind-control-plane

**Comment by BenTheElder** [comment]
The DNS resolver comes from docker.

https://docs.docker.com/config/containers/container-networking/#dns-services

However, we manipulate the networking very slightly so the IPv4 address can be reached by in cluster coreDNS pods which is the DNS services most pods will have.

**Comment by webmutation** [comment]
Thanks @BenTheElder I entered the nodes and I am not able to reach the internet from inside Kind... from docker docs

> whereas containers that use a [custom network](https://docs.docker.com/network/network-tutorial-standalone/#use-user-defined-bridge-networks) use Docker’s embedded DNS server, which forwards external DNS lookups to the DNS servers configured on the host. 

this appears to be broken on my installation of Docker, since the requests do not appear to be forwarded or resolved... should I revert to an older version od Docker any tip to have this working...

I am able on other containers that use the bridge network, but those get the injected resolv.conf from the host... I also tried to replace the resolv.conf of the kind container nodes and it does not work

**Comment by aojea** [comment]
check  those sysctl are set to 0
```
sysctl net.bridge.bridge-nf-call-iptables=0
sysctl net.bridge.bridge-nf-call-arptables=0
sysctl net.bridge.bridge-nf-call-ip6tables=0
```

**Comment by webmutation** [comment]
Hi @aojea they are all set to 1 in my host and inside the kind containers as well

**Comment by aojea** [comment]
> Hi @aojea they are all set to 1 in my host and inside the kind containers as well

set them to 0 on the host then :smile: , and report back, it should work after that

**Comment by webmutation** [comment]
Thanks that worked.

**Comment by webmutation** [comment]
I am closing this now. Problem was related to corporate vpn. Thanks once more @aojea for your instructions

**Comment by JMLX42** [comment]
> I am closing this now. Problem was related to corporate vpn. Thanks once more @aojea for your instructions

@webmutation please elaborate. I am using Wireguard, and I have the same problem on *some* machines. But nothing in my Wireguard configuration(s) interacts with those settings (or `iptables`).

I am on Ubuntu 22.04. @aojea Could [those values](https://github.com/kubernetes-sigs/kind/issues/2886#issuecomment-1219158523) be set to `1`by default?

**Comment by JMLX42** [comment]
> I am on Ubuntu 22.04. @aojea Could [those values](https://github.com/kubernetes-sigs/kind/issues/2886#issuecomment-1219158523) be set to `1`by default?

Here is what ChatGPT has to say:

> In many modern Linux distributions, including Ubuntu 22.04, these parameters are indeed set to 1 by default.
> This is done to provide a more secure default configuration. By allowing iptables, arptables, and ip6tables to see and manipulate bridged traffic, system administrators have the ability to apply firewall rules to this traffic if needed.
> However, if you find that you don't need to apply firewall rules to your bridged traffic, and you want to increase network performance, you could consider setting these parameters to 0. But remember, this should be done with a clear understanding of the potential security implications.

My understanding is that I have to chose between running `kind` or running an iptables/arptables/ip6tables based firewall. I'm surprised this is an actual requirement.

**Comment by BenTheElder** [comment]
> My understanding is that I have to chose between running kind or running an iptables/arptables/ip6tables based firewall. I'm surprised this is an actual requirement.

No that's not true, chatGPT is missing context :-)

We set this sysctl within the nodes, on my local linux host these are set to 1 and my multi-node kind cluster works fine. 
The Kubernetes networking needs to be able to NAT traffic on the pod network for the pod VIPs.

It's possible however that the wireguard network/firewall is interfering with traffic for the node network (the pod network is ~underneath this).

**Comment by BenTheElder** [comment]
It's hard to say specifically how your wireguard setup is interfering or not, seeing as iptables is quite powerful

**Comment by bulmust** [comment]
Delete created kind network `docker network rm kind` , and create the cluster.
