### ISSUE TITLE
Starting kind using rootfull podman

### ISSUE THREAD

**Issue by masterkidan** [kubernetes-sigs/kind#2888]
Hello folks, 
I've been trying to use kind with podman for a few days. One issue I seem to be hitting is that the variable KIND_EXPERIMENTAL_PROVIDER=podman seems to also be used to run podman in rootless mode. Is there some way I can pass an option to kind to use rootful podman ? 
I need it as I want to assign some lower port numbers etc like port 80 , which is not possible in rootless.

**Comment by BenTheElder** [comment]
It the same behavior as using podman directly so on most systems:

`sudo EXPERIMENTAL_PROVIDER kind ...`

**Comment by masterkidan** [comment]
Thanks it looks like my issue is something else then ... I am trying to publish to port 80 , but I get an access denied exception. I am thinking this may be related to podman itself and not really related to kind.

**Comment by BenTheElder** [comment]
I would think so, kind isn't doing anything particularly unusual with port forwards, if you mean the extraPortForwards config option. We're just plumbing that to `-p`
