### ISSUE TITLE
kind 0.14.0 startup slower than 0.12.0

### ISSUE THREAD

**Issue by raphaelauv** [kubernetes-sigs/kind#2893]
Linux XXXX 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

(ubuntu 22.04.1)

the command `kind create cluster` 

with 0.14.0 ->

```
real	0m17,099s
user	0m1,455s
sys	0m0,686s
```

with 0.12.0 ->

```
real	0m12,462s
user	0m1,409s
sys	0m0,843s
```

is this "normal" ? Thanks

**Comment by BenTheElder** [comment]
Unfortunately a few second skew is normal, Kubernetes doesn't regression test for "toy single node cluster startup time" and upstream changes can cause startup to take longer.

I would guess if you tested with the same Kubernetes minor version you will find roughly the same timings (within variance).

In the past we've worked to keep a lid on this, but I don't think @aojea or I have had time lately.

It's also worth noting that what kind considers "done" is somewhat arbitrary, based on when we no longer need to actively interact with the cluster and we have a healthy API server, but for some other tool it might be say, readiness of all nodes ...

Last time we noticed a change like this it was tracked down to https://github.com/kubernetes/kubeadm/issues/2395#issuecomment-782784169, you can see some of the upstream discussions linked from there.

**Comment by raphaelauv** [comment]
Thanks for the explanation, I'm going to close the issue 

👍
