### ISSUE TITLE
Do you have plans to do a release?

### ISSUE THREAD

**Issue by JorTurFer** [kubernetes-sigs/kind#2899]
Kubernetes v1.25 has been released and I'd like to use kind with it on my repositories' CIs but atm there isn't any node image for it.
Do you have any date for next release? I have checked but I can't find this information anywhere (Maybe I didn't see it but it's there)

**Comment by aojea** [comment]
We don't use to follow  kubernetes release, user should be able to build their own images , but this time we'll do a release soon , stay tuned

**Comment by JorTurFer** [comment]
Thanks for the clarification! 🙇

**Comment by BenTheElder** [comment]
We're roughly releasing at the cadence of Kubernetes this year, but mostly releases have been as-needed when major changes are well tested and ready for release, Kubernetes KIND node images can be built at any version following the guide in our docs.

KIND @ HEAD supports kubernetes @ HEAD, but stable kind supports _at least_ the default version it ships with. It may or may not yet support newer versions depending on breaking changes in Kubernetes. However the latest kind sources will always support the latest Kubernetes sources, it's just both are not stable released yet 😅 

I am in fact cutting a release tonight, which is nearly done.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/releases/tag/v0.15.0
