### ISSUE TITLE
Broken link: kind is a CNCF certified conformant Kubernetes installer

### ISSUE THREAD

**Issue by bjethwan** [kubernetes-sigs/kind#2900]
https://github.com/kubernetes-sigs/kind

<img width="747" alt="image" src="https://user-images.githubusercontent.com/5045325/187688133-141645b8-df06-4df6-a280-8876986dc3bc.png">

<img width="913" alt="image" src="https://user-images.githubusercontent.com/5045325/187688597-c585ba7b-c177-4ac6-acb2-67b08882499b.png">

Question: How can I prove to people that KIND is used in kubernetes release testing?
Question: Why's KIND removed from landscape.cncf.io

**Comment by aojea** [comment]
> Question: How can I prove to people that KIND is used in kubernetes release testing?

https://testgrid.k8s.io/sig-release-master-blocking

is there any special reason you have to prove people this?

**Comment by BenTheElder** [comment]
> Question: How can I prove to people that KIND is used in kubernetes release testing?

Uh, besides the link Antonio provided, I am a Chair + Technical Lead of the Kubernetes [Testing Special Interest Group](https://github.com/kubernetes/community/tree/master/sig-testing) and KIND was explicitly created for this purpose.

If you open any recent Kubernetes Pull Request you will see multiple test results from KIND on each PR, as well as the release-blocking dashboard running continuous testing.

This is the primary reason the project exists:
https://kind.sigs.k8s.io/docs/contributing/project-scope/

> Question: Why's KIND removed from landscape.cncf.io

It's possible we fell behind on submitting results, though I don't recall receiving the usual warning that we were at risk of becoming removed ...

For what it's worth: I can assure you that we continuously run conformance tests and KIND is certainly passing them.
We may need to submit current results to the CNCF again.

**Comment by bjethwan** [comment]
> https://kind.sigs.k8s.io/docs/contributing/project-scope/

DevOps team was completely dependent on AKS and EKS for testing. This was impacting the cost $.
I was suggesting mgmt to push for using KIND.
Mgmt folks came back with the conclusion that KIND is new and not fit for widespread use ... their reasoning was based looking at your [1.0 Roadmap 🗺](https://kind.sigs.k8s.io/docs/contributing/1.0-roadmap/).

Personally, I am a big fan of Kind. I was introduced to it in TGIK by Duffie Cooley

**Comment by aojea** [comment]
> Mgmt folks came back with the conclusion that KIND is new and not fit for widespread use ... their reasoning was based looking at your [1.0 Roadmap world_map](https://kind.sigs.k8s.io/docs/contributing/1.0-roadmap/).

kind gates Kubernetes development, that means that if everything that works in Kubernetes has to work with kind first ;)

**Comment by BenTheElder** [comment]
> their reasoning was based looking at your [1.0 Roadmap 🗺](https://kind.sigs.k8s.io/docs/contributing/1.0-roadmap/).

IMHO: This mostly means we have a high bar to considering something GA, similar to Kubernetes. KIND is stable enough to develop and run CI on, but we do not consider it 1.0 yet.

KIND is roughly beta-grade by the guidelines at https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages

> Personally, I am a big fan of Kind. I was introduced to it in TGIK by Duffie Cooley

Love Duffie! <3 @mauilion

**Comment by aojea** [comment]
We have to resubmit the results to the CNCF

https://github.com/cncf/k8s-conformance/pull/939

I'll do it
/assign

**Comment by BenTheElder** [comment]
https://github.com/cncf/k8s-conformance/pull/2146 we're re-certified now, the link should go live again soon.

**Comment by aojea** [comment]
also 1.24 https://github.com/cncf/k8s-conformance/pull/2149

/close
