### ISSUE TITLE
Kind nodeimage versioning

### ISSUE THREAD

**Issue by ricosega** [kubernetes-sigs/kind#2904]
How is the nodeimage being built?
There is a nodeimage version for each Kubernetes released version?
In that case why image 1.23.10 exists?

**Comment by BenTheElder** [comment]
> How is the nodeimage being built?
There is a nodeimage version for each Kubernetes released version?

For the kind current release we built one for each of the latest patch versions for the past 6+ minor versions of kubernetes

There's details in the docs on how to build one.

> In that case why image 1.23.10 exists?

https://github.com/kubernetes/kubernetes/releases/tag/v1.23.10

**Comment by ricosega** [comment]
@BenTheElder thank you for your reply!
Just checked https://kubernetes.io/releases/_print/ and seems not to be up to date right now.
