### ISSUE TITLE
Can I use docker different network mode?

### ISSUE THREAD

**Issue by noahge** [kubernetes-sigs/kind#2915]
My environment is Mac -> parallels -> ubuntu -> docker -> kind.

I want my mac connect to docker network, because kind use docker bridge mode, I can't do this.

is any solution?

**Comment by aojea** [comment]
those are a lot of hopes, @mauilion use to know creative solutions for these things

**Comment by BenTheElder** [comment]
bridge mode is the only thing we actively support, however depending on what specifically you are trying to accomplish there are options, for example configuring extraPortForwards on the nodes.

I'm not sure about the mac -> parallels part.
