### ISSUE TITLE
Kind v0.15.0 can't start cluster when using documented 1.18 node image

### ISSUE THREAD

**Issue by cfryanr** [kubernetes-sigs/kind#2925]
**What happened**:

 After upgrading to latest Kind using `brew upgrade kind`...

```bash
% kind version
kind v0.15.0 go1.19 darwin/amd64

# This is the image for 1.18.x copy/pasted from the v0.15.0 release notes.
% kind create cluster --image 'kindest/node:v1.18.20@sha256:61c9e1698c1cb19c3b1d8151a9135b379657aee23c59bde4a8d87923fcb43a91'
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.20) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
Command Output: I0913 22:10:13.303155     136 initconfiguration.go:200] loading configuration from "/kind/kubeadm.conf"

[... lots of debugging output trimmed here for brevity]

I0913 22:12:11.297574     136 round_trippers.go:444] GET https://kind-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.

	Unfortunately, an error has occurred:
		timed out waiting for the condition

[... more output trimmed here for brevity]
```

**What you expected to happen**:

I expected the cluster to start successfully.

Clusters do start successfully when other node images are copy/pasted from the v0.15.0 release notes (e.g. `kindest/node:v1.19.16@sha256:707469aac7e6805e52c3bde2a8a8050ce2b15decff60db6c5077ba9975d28b98`, etc.). This problem only happens with the 1.18 node image.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): `kind v0.15.0 go1.19 darwin/amd64`
- Kubernetes version: (use `kubectl version`): `Client Version: v1.24.3`
- Docker version: (use `docker info`):
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.7.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.8)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 47
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.773GiB
 Name: docker-desktop
 ID: 74KX:I4GW:S4RJ:ICSI:6BZX:HCZA:BFPG:HZKB:ZXYH:QUAX:W67E:I3TU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 56
  Goroutines: 53
  System Time: 2022-09-13T22:29:20.544923392Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

```
- OS (e.g. from `/etc/os-release`): `macOS Monterey`

**Comment by BenTheElder** [comment]
You're on a cgroups v2 host, cgroups v2 requires Kubernetes v1.19 unfortunately https://kind.sigs.k8s.io/docs/user/known-issues/#failure-to-create-cluster-with-cgroups-v2

**Comment by BenTheElder** [comment]
You should see the same issue with any other image with Kubernetes < 1.19 on this host, including with older kind versions.

**Comment by cfryanr** [comment]
Ah, thank you for the quick response. I had searched the existing issues, but I should have searched the docs more thoroughly before creating this issue. Sorry about that. Hopefully this issue will help others find the cause of this problem in the future.

**Comment by BenTheElder** [comment]
No worries, this one is awkward and non-obvious, but probably next we will just shift to 1.19+ anyhow 😅 

The main Kubernetes project only supports back to 1.23 currently https://kubernetes.io/releases/

**Comment by cfryanr** [comment]
@BenTheElder, Kind's support for old Kubernetes versions has been very valuable for testing our project for compatibility against old Kubernetes versions in our CI. It would be great if all users would ensure that all their Kubernetes clusters are always running the officially supported Kubernetes versions, but alas, some seem to always lag behind.

In this case, I had not tried to run an old Kube version on my Mac laptop for a long time, since the old versions are handled by CI (using linux hosts). So I was not aware of this particular limitation.

Thanks for supporting old Kube versions in Kind! That's a great feature.

**Comment by BenTheElder** [comment]
Yes, I agree, it's unfortunately pretty expensive to keep up with though, and Kubernetes and systemd are looking at dropping cgroups v1 support in the near future so 1.18 back is going to become rather problematic. 

As an upstream project we can't go back and patch Kubernetes branches that are no longer accepting patches and ship major changes like cgroup v2 support so eventually we're forced to drop versions due to lack of updates.

Until recently we still had limited support for v1.13 back, only a few versions newer than when we started the project (currently 1.16+ in the next release).

We're heading towards soft-targeting 3 additional minor releases in addition to what upstream k8s supports, plus also the latest Kubernetes sources at HEAD if you have kind at HEAD, with best-effort support for older versions. 

Need to write a policy down somewhere, but want to be really sure before we formally commit to something.

**Comment by cfryanr** [comment]
Makes sense! Thanks!

**Comment by tamalsaha** [comment]
In case anyone comes across the issue that suddenly you can't create 1.18.x clusters on GitHub Actions, please make sure you are using `runs-on: ubuntu-20.04`. On `ubuntu-latest` Docker uses cgroups v2 and KIND can't create 1.18.20 cluster anymore.
