### ISSUE TITLE
Issue : Not Able to enter to load balancer. 

### ISSUE THREAD

**Issue by rabindragogoi** [kubernetes-sigs/kind#2926]
**Scenario**
I created a cluater of 2 master node and 1 worker node and after that ran the below command pointing to my config.yaml file.

kind create cluster --config=config.yaml

It created :

○ → docker ps -a
CONTAINER ID   IMAGE                                COMMAND                  CREATED         STATUS         PORTS                       NAMES
385844d247c5   kindest/haproxy:v20220510-a42b3ea0   "haproxy -sf 7 -W -d…"   4 minutes ago   Up 4 minutes   127.0.0.1:50846->6443/tcp   kind-external-load-balancer
c2a684220281   kindest/node:v1.24.0                 "/usr/local/bin/entr…"   4 minutes ago   Up 4 minutes                               kind-worker
ed8aca5c835d   kindest/node:v1.24.0                 "/usr/local/bin/entr…"   4 minutes ago   Up 4 minutes   127.0.0.1:50844->6443/tcp   kind-control-plane
21b13a7b44f5   kindest/node:v1.24.0                 "/usr/local/bin/entr…"   4 minutes ago   Up 4 minutes   127.0.0.1:50845->6443/tcp   kind-control-plane2

**Issue**:
When I tried to enter the loadbalancer with the command it is returning the below error:
○ → docker exec -it kind-external-load-balancer sh
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown

I even tried with "/bin/sh" , "/bin/bash", "bash"

but returned the same error.

**Comment by BenTheElder** [comment]
Yes, there's no shell in the loadbalancer, it's minimal.

What's the use case? In general users are meant to be using the Kubernetes API.

**Comment by rabindragogoi** [comment]
Okay.. I was going through tutorials of Kind where I have seen the instructor entering the load balancer and checking ping to all the other master/worker node. 
https://www.youtube.com/watch?v=kkW7LNCsK74

id the functionality got changed now?

**Comment by BenTheElder** [comment]
yes, this is an internal detail, I was not aware of this tutorial. we have minimized this image further since earlier versions.

ping is also not really a reliable way to check connectivity in kubernetes, overlay networks may not support ICMP

**Comment by rabindragogoi** [comment]
Okay thanks.. closing the issue chain.
