### ISSUE TITLE
kind tries to remove non-existent taint while deploying a custom node-image

### ISSUE THREAD

**Issue by 100mik** [kubernetes-sigs/kind#2931]
**What happened**:
I built a node image from the develop branch of k/k (`kind build node-image --image kindest/node:local .` while in the project dir)
I then tried to create a cluster using this image by running:
`kind create cluster --name k8s-local --image kindest/node:local`

It failed with the message: 
```bash
ERROR: failed to create cluster: failed to remove control plane taint: command "docker exec --privileged k8s-local-control-plane kubectl --kubeconfig=/etc/kubernetes/admin.conf taint nodes --all node-role.kubernetes.io/master-" failed with error: exit status 1
Command Output: error: taint "node-role.kubernetes.io/master" not found
Stack Trace: 
sigs.k8s.io/kind/pkg/errors.WithStack
	sigs.k8s.io/kind/pkg/errors/errors.go:59
sigs.k8s.io/kind/pkg/exec.(*LocalCmd).Run
	sigs.k8s.io/kind/pkg/exec/local.go:124
sigs.k8s.io/kind/pkg/cluster/internal/providers/docker.(*nodeCmd).Run
	sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/node.go:146
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/kubeadminit.(*action).Execute
	sigs.k8s.io/kind/pkg/cluster/internal/create/actions/kubeadminit/init.go:140
sigs.k8s.io/kind/pkg/cluster/internal/create.Cluster
	sigs.k8s.io/kind/pkg/cluster/internal/create/create.go:135
sigs.k8s.io/kind/pkg/cluster.(*Provider).Create
	sigs.k8s.io/kind/pkg/cluster/provider.go:182
sigs.k8s.io/kind/pkg/cmd/kind/create/cluster.runE
	sigs.k8s.io/kind/pkg/cmd/kind/create/cluster/createcluster.go:111
sigs.k8s.io/kind/pkg/cmd/kind/create/cluster.NewCommand.func1
	sigs.k8s.io/kind/pkg/cmd/kind/create/cluster/createcluster.go:55
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.4.0/command.go:902
sigs.k8s.io/kind/cmd/kind/app.Run
	sigs.k8s.io/kind/cmd/kind/app/main.go:53
sigs.k8s.io/kind/cmd/kind/app.Main
	sigs.k8s.io/kind/cmd/kind/app/main.go:35
main.main
	sigs.k8s.io/kind/main.go:25
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1594
```

**What you expected to happen**:
I expected kind to create a cluster which uses the node image I just built

**How to reproduce it (as minimally and precisely as possible)**:
I could reproduce this consistently by repeating the steps I mentioned ^

**Anything else we need to know?**:
I can however create a cluster without a custom node image without any issues.

Since it was erroring out after creating the control plane, to take a closer look at what's up I used the `--retain` flag and examined the node.
The node seems to have taints:
```
taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
    - effect: NoSchedule
      key: node.kubernetes.io/not-ready
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      timeAdded: "2022-09-16T20:36:30Z"
```
My best guess is `kind` should be trying to remove the taint `node-role.kubernetes.io/control-plane` instead of `node-role.kubernetes.io/master`. Probably something that was missed during moving away from using "master" to describe the control plane. (completely a guess I am not sure if kind used different terminology initially)

**Environment:**

- kind version: (use `kind version`): v0.15.0
- Kubernetes version: (use `kubectl version`): (I built an image from develop)
- Docker version: (use `docker info`): macOS Monterey version 12.4
- OS (e.g. from `/etc/os-release`): macOS Monterey version 12.4

**Comment by 100mik** [comment]
I tried to dig into what happens differently while creating a node without a custom image, but according to what I see when I run this with `-v 9`. `kind` does not try to remove any taints at all.

Not sure if this happens but is not logged 🤔

**Comment by 100mik** [comment]
Looks like there is some logic [here](https://github.com/kubernetes-sigs/kind/blob/main/pkg/cluster/internal/create/actions/kubeadminit/init.go#L124-L134) which uses version constraints to decide which taint to remove. We grab this version by running `cat /kind/version` on the node. And that value for me is `v1.25.0` in which case it should try to remove the taint `node-role.kubernetes.io/control-plane`

**Comment by BenTheElder** [comment]
To be clear: which Kubernetes version are you running? Is it forked?

a common problem is shallow clones of kubernetes without full git history which creates a bad git describe in the upstream k8s build tools and therefore false info for kind to operate from.

otherwise we may have a bug in the version comparison, but our default image currently is v1.25.0 IIRC so ... 🤔

**Comment by 100mik** [comment]
>  but our default image currently is v1.25.0 IIRC

This seems to be true ^ I was just gonna try and log what `KubeVersion` returns in my case. When I ran `cat /kind/version`, I did get the value `v1.25.0 `

>  which Kubernetes version are you running? Is it forked?

I was trying to play around with some changes. So I built my image from the develop branch.

**Comment by 100mik** [comment]
I do not think it is the version comparison because I tried to test out that block by doing something like [this](https://gist.github.com/100mik/89f75ac6e1f1de6e14686adb74665ba4).

(Here the package `"sigs.k8s.io/kind/pkg/foo/version"` is a copy of `"sigs.k8s.io/kind/pkg/internal/version"` vendor)

**Comment by 100mik** [comment]
So I built `kind` from source while logging the version being grabbed, something like this:
```
kubeVersion, err := version.ParseSemantic(rawVersion)
if err != nil {
	return errors.Wrap(err, "could not parse Kubernetes version")
}

fmt.Println("Debug: %s", rawVersion)
```

And the version seems to be `v1.22.0-beta.2.8018+0f37b312064358`. 

Looks like in my case, `nodeutils.KubeVersion()` is not returning `v1.25.0`, even though that is what I see when I run `cat /kind/version` in the container created.

**Comment by 100mik** [comment]
PS: Kudos for having `--retain` in place. Ran into it while trying to debug

**Comment by 100mik** [comment]
Apologies! Correction from my side,

Looks like when I ran `cat /kind/version` the first time it was in a cluster created without a custom node image. I edited the comment above to call this out.

The issue seems to be, if I build an image from the `develop` branch of `k/k`, the version seems to be something like `v1.22.0-beta.2.8018+0f37b312064358` which results in `kind` trying to remove the taint `node-role.kubernetes.io/master` while the actual taint on the node is `node-role.kubernetes.io/control-plane`

**Comment by BenTheElder** [comment]
Are you sure the version reported by the kubernetes build is correct? Did you check if you have a full clone?

**Comment by BenTheElder** [comment]
I'm pretty sure we were precise about which Kubeadm versions changed the taint, but it is a common issue that the k8s build version is wrong due to say missing tags or commit history. I don't think there's much we can do in that case.

I'm on mobile and don't have handy the references but we worked with kubeadm maintainers on the taint transition 😅

**Comment by 100mik** [comment]
It is my first time trying to put together a dev environment of sorts, so it is totally possible that I am missing something!

I did pull the latest changes before building. Just to be sure I am gonna clone `k/k` again and try to reproduce this 🤔

**Comment by 100mik** [comment]
That seemed to work! I realised I have been calling `master` => `develop` out of habit.

I am not sure what changed because I had not made any changes yet and had the latest changes. Thanks a lot for the pointer!

**Comment by 100mik** [comment]
I cloned the repo quite some time back (around v1.22.0) and have been running `git pull upstream master` to grab the latest changes. 

My best bet is that the tags affect the version that is put in and what I have been doing did not fetch the tags (have not verified this). 😢

**Comment by BenTheElder** [comment]
yes, the tags affect the versions git produces with `git describe` and missing tags will cause Kubernetes's builds to have inaccurate version information, which then breaks tools like kind 😅

**Comment by 100mik** [comment]
Gotcha! Note to self: remember to fetch tags.
Thanks <3
