### ISSUE TITLE
Kind node images for k8s 1.25.2

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/kind#2933]
**What would you like to be added**:
It will be great if you could publish node image for k8s 1.25.1

**Why is this needed**:
https://github.com/kubernetes/kubernetes/pull/112204

**Comment by tamalsaha** [comment]
May be wait for 1.25.2 

https://groups.google.com/g/kubernetes-sig-release/c/UTwQ1qg8aN8/m/6PFlhKsaAgAJ

**Comment by BenTheElder** [comment]
came here to follow up and post "maybe wait for 1.25.2" 😅

**Comment by BenTheElder** [comment]
1.25.1 has `kindest/node:v1.25.1@sha256:d20e58f5a5e89678dbedc6748cad0fba01b0f2df386cb16594bcba39be53b447` FWIW, but I think we should wait to 1.25.2 to add to the 0.15.0 release notes (and maybe consider a small 0.16.0 to ship this to default given the bug)

**Comment by tamalsaha** [comment]
> maybe consider a small 0.16.0 to ship this to default given the bug

👍

**Comment by BenTheElder** [comment]
pushing 1.25.2 now after base image updates.

we can do v0.16 tomorrow.

**Comment by BenTheElder** [comment]
`kindest/node:v1.25.2@sha256:9be91e9e9cdf116809841fc77ebdb8845443c4c72fe5218f3ae9eb57fdb4bace`

**Comment by BenTheElder** [comment]
`kindest/node:v1.24.6@sha256:97e8d00bc37a7598a0b32d1fabd155a96355c49fa0d4d4790aab0f161bf31be1`
`kindest/node:v1.23.12@sha256:9402cf1330bbd3a0d097d2033fa489b2abe40d479cc5ef47d0b6a6960613148a` 
`kindest/node:v1.22.15@sha256:bfd5eaae36849bfb3c1e3b9442f3da17d730718248939d9d547e86bbac5da586`

(will publish these with v0.16.0)

**Comment by BenTheElder** [comment]
Annnnd done. https://github.com/kubernetes-sigs/kind/releases/tag/v0.16.0
