### ISSUE TITLE
Kind creates a kind Docker network by default. Does it support specifying multiple Docker networks

### ISSUE THREAD

**Issue by xiaofan-linux** [kubernetes-sigs/kind#2939]
##### Kind creates a kind Docker network by default. Does it support specifying multiple Docker networks

**Comment by aojea** [comment]
nope, but you can do it manually https://gist.github.com/aojea/00bca6390f5f67c0a30db6acacf3ea91#example-multiple-network-interfaces-and-multi-home-nodes

/close
