### ISSUE TITLE
Node stuck in NotReady state

### ISSUE THREAD

**Issue by vinycoolguy2015** [kubernetes-sigs/kind#2951]
While creating cluster with kind on Ubuntu 20.04 LTS machine, nodes are stuck in NotReady state with following message

KubeletNotReady runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized

**Comment by BenTheElder** [comment]
We're going to need a lot more information than that. For starters can you share docker info and the cluster config / commands used as well as the kind version.

In the meantime please check:
https://kind.sigs.k8s.io/docs/user/known-issues/

Given you said nodes plural:
https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files
is a common one. (There are many resource dimensions on the host that can be insufficient for multi node clusters)

**Comment by vinycoolguy2015** [comment]
Was going through Linux Foundation's LFS 269 course repo installation instructions

git clone https://github.com/lfs269/setup.git
cd setup/kind/
kind create cluster --config kind-three-node-cluster.yaml

docker info output:

root@kind:~/setup/kind# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.0-1018-gcp
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.829GiB
 Name: kind
 ID: Z2Z2:ICDS:2UFJ:IGM3:6H7Q:BYQW:XFDA:YEBV:X7WP:JX7D:Q2O4:3TPC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

root@kind:~/setup/kind# kubectl get nodes
NAME                 STATUS     ROLES                  AGE     VERSION
kind-control-plane   NotReady   control-plane,master   3m10s   v1.20.2
kind-worker          NotReady   <none>                 2m36s   v1.20.2
kind-worker2         NotReady   <none>                 2m35s   v1.20.2

Apologies for the confusion, I am running kind on a single Ubuntu machine

**Comment by vinycoolguy2015** [comment]
kube-proxy pod was crashing because of 
server.go:495] open /proc/sys/net/netfilter/nf_conntrack_max: permission denied

Issue resolved after upgrading kid to v0.11.1

**Comment by BenTheElder** [comment]
Oh yes, there's been some important fixes 😅. On some hosts kubernetes 1.19+ and the kind version that first shipped it are not required. KIND v0.16.0 is the current release.
