### ISSUE TITLE
fails to use port-forward with kind in githubaction

### ISSUE THREAD

**Issue by SamYuan1990** [kubernetes-sigs/kind#2953]
Hi,
I wanna to use kind as k8s cluster and deploy my service on it.
then I am moving forward with port-forward and try to use localhost port to test it.
but I received error as `failed to connect to localhost:9102 inside namespace`
```
Handling connection for 9102
E1004 08:02:47.046060    7990 portforward.go:406] an error occurred forwarding 9102 -> 9102: error forwarding port 9102 to pod 2b02221f9f4b01c499fabccd3d35d62e5591d6b1303d9[18](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:19)294587bd80d23e38f, uid : failed to execute portforward in network namespace "host": failed to connect to localhost:9102 inside namespace "2b022[21](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:22)f9f4b01c499fabccd3d35d62e5591d6b1303d918294587bd80d[23](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:24)e38f", IPv4: dial tcp4 1[27](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:28).0.0.1:9102: connect: connection refused IPv6 dial tcp6 [::1]:9102: connect: connection refused 
E1004 08:02:47.047407    7990 portforward.go:2[34](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:35)] lost connection to pod
```

ref https://github.com/sustainable-computing-io/kepler/pull/275
full log:
```
I1004 08:02:09.044762    7990 loader.go:374] Config loaded from file:  /home/runner/.kube/config
I1004 0[8](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:9):02:09.054192    7990 round_trippers.go:463] GET https://127.0.0.1:37749/api/v1/namespaces/kepler/services/kepler-exporter
I1004 08:02:0[9](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:10).054211    7990 round_trippers.go:469] Request Headers:
I[10](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:11)04 08:02:09.054220    7990 round_trippers.go:473]     Accept: application/json, */*
I1004 08:02:09.054227    7990 round_trippers.go:473]     User-Agent: kubectl/v1.25.2 (linux/amd64) kubernetes/5835544
I1004 08:02:09.062814    7990 round_trippers.go:574] Response Status: 200 OK in 8 milliseconds
I1004 08:02:09.179931    7990 round_trippers.go:463] GET https://127.0.0.1:37749/api/v1/namespaces/kepler/pods?labelSelector=app.kubernetes.io%2Fcomponent%3Dexporter%2Capp.kubernetes.io%2Fname%3Dkepler-exporter
I1004 08:02:09.179956    7990 round_trippers.go:469] Request Headers:
I1004 08:02:09.179965    7990 round_trippers.go:473]     Accept: application/json, */*
I1004 08:02:09.179972    7990 round_trippers.go:473]     User-Agent: kubectl/v1.25.2 (linux/amd64) kubernetes/5835544
I1004 08:02:09.182492    7990 round_trippers.go:574] Response Status: 200 OK in 2 milliseconds
I1004 08:02:09.85[11](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:12)24    7990 round_trippers.go:463] GET https://[12](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:13)7.0.0.1:37749/api/v1/namespaces/kepler/pods/kepler-exporter-9xmzm
I1004 08:02:09.85[13](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:14)83    7990 round_trippers.go:469] Request Headers:
I1004 08:02:09.85[16](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:17)10    7990 round_trippers.go:473]     Accept: application/json, */*
I1004 08:02:09.851625    7990 round_trippers.go:473]     User-Agent: kubectl/v1.25.2 (linux/amd64) kubernetes/5835544
I1004 08:02:09.853849    7990 round_trippers.go:574] Response Status: 200 OK in 2 milliseconds
I1004 08:02:09.855082    7990 round_trippers.go:463] POST https://127.0.0.1:37749/api/v1/namespaces/kepler/pods/kepler-exporter-9xmzm/portforward
I1004 08:02:09.855098    7990 round_trippers.go:469] Request Headers:
I1004 08:02:09.855106    7990 round_trippers.go:473]     X-Stream-Protocol-Version: portforward.k8s.io
I1004 08:02:09.855113    7990 round_trippers.go:473]     User-Agent: kubectl/v1.25.2 (linux/amd64) kubernetes/5835544
I1004 08:02:09.924785    7990 round_trippers.go:574] Response Status: 101 Switching Protocols in 69 milliseconds
Forwarding from 127.0.0.1:9102 -> 9102
Forwarding from [::1]:9102 -> 9102
Running Suite: E2eTest Suite
============================
Random Seed: 1664870545
Will run 1 of 1 specs

Handling connection for 9102
E1004 08:02:47.046060    7990 portforward.go:406] an error occurred forwarding 9102 -> 9102: error forwarding port 9102 to pod 2b02221f9f4b01c499fabccd3d35d62e5591d6b1303d9[18](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:19)294587bd80d23e38f, uid : failed to execute portforward in network namespace "host": failed to connect to localhost:9102 inside namespace "2b022[21](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:22)f9f4b01c499fabccd3d35d62e5591d6b1303d918294587bd80d[23](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:24)e38f", IPv4: dial tcp4 1[27](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:28).0.0.1:9102: connect: connection refused IPv6 dial tcp6 [::1]:9102: connect: connection refused 
E1004 08:02:47.047407    7990 portforward.go:2[34](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:35)] lost connection to pod
```

**Comment by aojea** [comment]
this doesn't look like a kind problem

**Comment by SamYuan1990** [comment]
> this doesn't look like a kind problem

any suggestions for troubleshooting ?

**Comment by SamYuan1990** [comment]
> this doesn't look like a kind problem

I tried some thing today, and the error seems happened at from ipv4 address to ipv6 address transform. 
```
E1005 05:43:29.795651    8202 portforward.go:406] an error occurred forwarding 9102 -> 9102: error forwarding port 9102 to pod 658bdf588989bd980c3970[33](https://github.com/sustainable-computing-io/kepler/actions/runs/3187539021/jobs/5199208247#step:7:34)76e86655fc77e9e881d1796ce9982956d7a3fc32, uid : failed to execute portforward in network namespace "/var/run/netns/cni-831e470d-5e3a-1cfe-3011-80db69ffec71": failed to connect to localhost:9102 inside namespace "658bdf588989bd980c39703376e86655fc77e9e881d1796ce9982956d7a3fc32", IPv4: dial tcp4 127.0.0.1:9102: connect: connection refused IPv6 dial tcp6 [::1]:9102: connect: connection refused
```

**Comment by SamYuan1990** [comment]
@aojea , may I know how to avoid https://github.com/kubernetes-sigs/kind/issues/1326
as it seems we have issue when port-forward with ipv6? https://kind.sigs.k8s.io/docs/user/known-issues/#ipv6-port-forwarding

**Comment by SamYuan1990** [comment]
```
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  #disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.245.0.0/16"
```
I am confused, as I given ip v4 address loop, the port forwarding still give me an ipv6 address.

**Comment by BenTheElder** [comment]
> I tried some thing today, and the error seems happened at from ipv4 address to ipv6 address transform.

not quite, see if we split up the error:
> E1005 05:43:29.795651    8202 portforward.go:406] an error occurred forwarding 9102 -> 9102: error forwarding port 9102 to pod 658bdf588989bd980c3970[33](https://github.com/sustainable-computing-io/kepler/actions/runs/3187539021/jobs/5199208247#step:7:34)76e86655fc77e9e881d1796ce9982956d7a3fc32, uid : failed to execute portforward in network namespace "/var/run/netns/cni-831e470d-5e3a-1cfe-3011-80db69ffec71": failed to connect to localhost:9102 inside namespace "658bdf588989bd980c39703376e86655fc77e9e881d1796ce9982956d7a3fc32", IPv4: dial tcp4 127.0.0.1:9102: connect: connection refused IPv6 dial tcp6 [::1]:9102: connect: connection refused

`IPv4: dial tcp4 127.0.0.1:9102: connect: connection refused IPv6 dial tcp6 [::1]:9102: connect: connection refused`

_both_ IPv4 and IPv6 were attempted for `localhost` and both refused connection

> as it seems we have issue when port-forward with ipv6? https://kind.sigs.k8s.io/docs/user/known-issues/#ipv6-port-forwarding

That issue could do with some clarification, the known issue is about https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings not the kubernetes port forward API, that is, it's about forwarding ports to the KIND node when using docker, because docker has limitations there.

Kubernetes within kind is using containerd.

**Comment by BenTheElder** [comment]
Are you sure the application is listening on that port? The error says containerd attempted to run the port forward within the container's network namespace but got connection refused.

**Comment by SamYuan1990** [comment]
> Are you sure the application is listening on that port? The error says containerd attempted to run the port forward within the container's network namespace but got connection refused.

for this, I suppose it works. as what I am doing is try to test health check(or say livenessProbe).
and we have `kubectl rollout status daemonset ...` passed.
cc: @rootfs

**Comment by SamYuan1990** [comment]
> > I tried some thing today, and the error seems happened at from ipv4 address to ipv6 address transform.
> 
> not quite, see if we split up the error:
> 
> > E1005 05:43:29.795651    8202 portforward.go:406] an error occurred forwarding 9102 -> 9102: error forwarding port 9102 to pod 658bdf588989bd980c3970[33](https://github.com/sustainable-computing-io/kepler/actions/runs/3187539021/jobs/5199208247#step:7:34)76e86655fc77e9e881d1796ce9982956d7a3fc32, uid : failed to execute portforward in network namespace "/var/run/netns/cni-831e470d-5e3a-1cfe-3011-80db69ffec71": failed to connect to localhost:9102 inside namespace "658bdf588989bd980c39703376e86655fc77e9e881d1796ce9982956d7a3fc32", IPv4: dial tcp4 127.0.0.1:9102: connect: connection refused IPv6 dial tcp6 [::1]:9102: connect: connection refused
> 
> `IPv4: dial tcp4 127.0.0.1:9102: connect: connection refused IPv6 dial tcp6 [::1]:9102: connect: connection refused`
> 
> _both_ IPv4 and IPv6 were attempted for `localhost` and both refused connection
> 
> > as it seems we have issue when port-forward with ipv6? https://kind.sigs.k8s.io/docs/user/known-issues/#ipv6-port-forwarding
> 
> That issue could do with some clarification, the known issue is about https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings not the kubernetes port forward API, that is, it's about forwarding ports to the KIND node when using docker, because docker has limitations there.
> 
> Kubernetes within kind is using containerd.

is there any way to start kind with podman? when both docker and podman been installed? 
as far as I know it seems podman use containerd?

**Comment by aojea** [comment]
let's try to find out first what happens and discard things.

Can you log into the pod and check how the app is bound? something like
```
kubectl exec -it ... bash
ss -apn
```

**Comment by SamYuan1990** [comment]
> let's try to find out first what happens and discard things.
> 
> Can you log into the pod and check how the app is bound? something like
> 
> ```
> kubectl exec -it ... bash
> ss -apn
> ```

I just wondering, shall we deploy a nginx and use port forward in kind CI?

**Comment by BenTheElder** [comment]
> is there any way to start kind with podman? when both docker and podman been installed?

Yes. `KIND_EXPERIMENTAL_PROVIDER =podman`, but that's not necessary here. the issue is happening *inside* the cluster, not with node level forwards.

> as far as I know it seems podman use containerd?

no. podman doesn't use containerd. KIND uses containerd *inside* podman or docker.

So either way, your application should run ~the same, the issue is not with the node provider.

> Can you log into the pod and check how the app is bound? something like

This, please. Let's ensure the app is indeed listening in the pod on that port.

> for this, I suppose it works. as what I am doing is try to test health check(or say livenessProbe).

Hmm, I'm not sure I understand, why not use an actual health check or liveness probe?

`kubectl port-forward` will not work if the application is not up and listening.

> and we have kubectl rollout status daemonset ... passed.

That doesn't guarantee that it is listening in the pod on *this* port on localhost.

**Comment by BenTheElder** [comment]
> E1004 08:02:47.046060    7990 portforward.go:406] an error occurred forwarding 9102 -> 9102: error forwarding port 9102 to pod 2b02221f9f4b01c499fabccd3d35d62e5591d6b1303d9[18](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:19)294587bd80d23e38f, uid : failed to execute portforward in network namespace "host": failed to connect to localhost:9102 inside namespace "2b022[21](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:22)f9f4b01c499fabccd3d35d62e5591d6b1303d918294587bd80d[23](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:24)e38f", IPv4: dial tcp4 1[27](https://github.com/sustainable-computing-io/kepler/actions/runs/3180383090/jobs/5183888088#step:7:28).0.0.1:9102: connect: connection refused IPv6 dial tcp6 [::1]:9102: connect: connection refused 


note that "host" in this message is the kind node, not the underlying host. The node container is the "host" as far as kubernetes is concerned.

**Comment by SamYuan1990** [comment]
So far @aojea is right, we found a panic in our code logic and we are WIP for fix.

**Comment by BenTheElder** [comment]
Looks like this was resolved back in https://github.com/sustainable-computing-io/kepler/pull/275

**Comment by SamYuan1990** [comment]
we have a good discuss in detail at https://github.com/sustainable-computing-io/kepler/pull/275
as a summary
> nodePort can only be set on a service of type [NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport). shouldn't be related to the node level port mappings.
> The command kubectl rollout status daemonset xxx --timeout 180s verifies if the container has been started, but will not check if the container failed shortly after starting....

> port-forward forwards to pods (not services), it will attempt to open a connection from within the pod's namespace, the tunnel looks roughly like:
```
kubectl <=> API server <=> kubelet <=> CRI <=> socket opened within target pod. IIRC kubernetes will always do this on localhost. The specific implementation in this case will be containerd's.
```

> kubectl port forward is more of a debugging tool and is not the most robust...

the tips to debug this kind of case maybe:
1. check your pod log, if you pod works well and in stable.(don't just relay or rollout status or pod liveness....)
2. check your vm and host instance, with the tunnel logic, for example, some times ipv6 may cause issue. as https://github.com/actions/runner-images/issues/668 
3. remember kubectl is not robust, for example https://github.com/kubernetes/kubectl/issues/1169
4. if needed, try LB, or ingress or other network solutions.

@BenTheElder, @aojea thanks for your support on this ticket, may I know if things above make sense and we may better put those tips in document for others to learn form this lesson?

**Comment by BenTheElder** [comment]
maybe something in the kubernetes.io docs for port forwarding, but i'm not sure where

I don't think kind should host general kubernetes docs vs contributing to the actual general kubernetes docs 😅
