### ISSUE TITLE
Back-off pulling image

### ISSUE THREAD

**Issue by mark8s** [kubernetes-sigs/kind#2961]
Hi everyone, I have a question.

I used kind to deploy a multi-node k8s cluster, but I encountered the problem of image pull failure. Is the log like this?

![image](https://user-images.githubusercontent.com/47961301/194817551-9f5202c2-bd68-4264-ba0b-27743cc6ddae.png)

I found a phenomenon that every time I started to use kind to create a new cluster every day, I could pull the docker related images. But when I pull a few more times, the mirror will show that the pull failed. Also, I can use docker pull to pull this image on the host, but I can't pull it from the kind container. Is there any way to pull the image, I don't want to use kind load.

**Comment by BenTheElder** [comment]
I'm sorry I don't know anything about this mirror. Is it possible that it rate limits you?

If you don't want to use kind load you will need to do an actual pull of some sort then. The image contents have to get into the cluster somehow.

**Comment by aojea** [comment]
the screenshot shows dns request timing out and tcp healthz probes faling

**Comment by mark8s** [comment]
@aojea @BenTheElder  tks，I need to do more research
