### ISSUE TITLE
Config file should validate if the image is suitable for arm or amd architecture

### ISSUE THREAD

**Issue by aliabbasjaffri** [kubernetes-sigs/kind#2963]
**What would you like to be added**:
It would be nice to have a validator in the config file if the image for node is being installed for amd or arm architecture.
I recently ran in the same issue and had to do some back and forth with the maintainer to figure out i was running in such a [basic issue](https://github.com/kubernetes-sigs/kind/issues/2959).

**Why is this needed**:
Such validations should be natively a part of applications, and no one should have to waste time in such a mindless issue. Rather than having someone else to figure this out, a simple validator can verify whether the node version and the chipset architecture version are in agreement with each other. It is not a big enhancement requirement, but because it happened with me, i do not want anyone else to waste any of their time figuring out that they landed in such a lame issue.

https://github.com/kubernetes-sigs/kind/issues/2963#tasklist-block-ed0fee24-9004-4fa6-953c-1dd570b3d312

**Comment by BenTheElder** [comment]
FWIW: All published and documented images are multi-arch. So this is only an issue with custom images.

> The node version and the chipset architecture version are in agreement with each other

You could be using a remote docker or podman daemon, so we have to be careful with this assumption.

**Comment by aliabbasjaffri** [comment]
Hmm, I'm no expert in that. I thought of an issue that i recently ran in. and thought if i could contribute back by making kind a bit more refined around the edges! It does seem like this request might have a bigger maintenance overhead than the good aspects.

**Comment by aojea** [comment]
> Hmm, I'm no expert in that. I thought of an issue that i recently ran in. and thought if i could contribute back by making kind a bit more refined around the edges!

Thanks for thinking that way, that is a great mindset, unfortunately the approach has some problems, so I'm going to close it if you don't mind

/close
