### ISSUE TITLE
Are users able to configure how the kind docker network is created on cluster creation?

### ISSUE THREAD

**Issue by aburgos-hv** [kubernetes-sigs/kind#2970]
We're hitting an issue where the kind docker network bridge is being deployed with an ip addr/CIDR that is overlapping with services outside of the host which prevents the host from establishing a connection to those services. When this happens, removing the kind docker network resolves the issue and the host is able to establish connection to the service again. Are there any supported ways of dictating how the kind docker network is created so we can avoid this overlap in the future?

**Comment by BenTheElder** [comment]
Docker has configurable IPAM, you can configure dockerd with the pool of CIDRs

**Comment by BenTheElder** [comment]
https://docs.docker.com/engine/reference/commandline/dockerd/

https://straz.to/2021-09-08-docker-address-pools/

https://forums.docker.com/t/docker-default-address-pool-customization-question/112969

**Comment by aburgos-hv** [comment]
Thank you for the suggestion and providing the documentation! I will look into leveraging this solution
