### ISSUE TITLE
validate that hostports are not configured twice with the same protocol

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#2975]
cc @aojea (thinking of that kubernetes issue)

**Comment by aojea** [comment]
👁️

**Comment by BenTheElder** [comment]
The issue doesn't really add more context than this title, it just brought the topic to attention: hostports should not be configured twice with the same protocol. 

You can't listen to say port 80 on the host on TCP twice to different container Ports. It's not possible, both port forwards have to create a listener on the host on the (port, protocol) and if there's duplicate entries covering the same (hostPort, protocol) that should be an error.

Sorry I've been drowning in notifications :-)

**Comment by daman1807** [comment]
@BenTheElder It is possible to bind a socket to the same port and protocol on different interfaces (**listenAddress**). 
Should we also consider this then? Would need to handle **0.0.0.0** separately.

**Comment by daman1807** [comment]
@BenTheElder @aojea  While going through the code I found that we don't check if the user-provided port is free/available, is this intentional or should I create an issue for this?
 
https://github.com/kubernetes-sigs/kind/blob/49c88451b3ac87c3d7b4155e43452d5880a8cf81/pkg/cluster/internal/providers/common/getport.go#L25

**Comment by BenTheElder** [comment]
Yes we should consider listenAddress.

No we should not attempt to check if the port is free. 
1. That can change between checking and actually creating the cluster
2. The cluster nodes may be created on a remote machine via DOCKER_HOST or similar

The linked utility is used for obtaining a semi-randomized port, because if we don't explicitly set one it will be re-randomized when the container is recreated on restart. In the case of a remote host -1 may be configured to avoid the local check at the cost of the reboot behavior.
