### ISSUE TITLE
debian11 GPG error leads to inability to update and install packages and thus an infinite loop

### ISSUE THREAD

**Issue by lusains** [kubernetes-sigs/kind#2979]
**What happened**:
root@c1-worker:/# apt-key adv --keyserver mirrors.ustc.edu.cn --recv-keys 3B4FE6ACC0B21F32
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
root@c1-worker:/# apt-get update
Get:1 http://mirrors.ustc.edu.cn/ubuntu xenial InRelease [247 kB]
Err:1 http://mirrors.ustc.edu.cn/ubuntu xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
Get:2 http://mirrors.ustc.edu.cn/ubuntu xenial-security InRelease [99.8 kB]
Err:2 http://mirrors.ustc.edu.cn/ubuntu xenial-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
Get:3 http://mirrors.ustc.edu.cn/ubuntu xenial-updates InRelease [99.8 kB]
Err:3 http://mirrors.ustc.edu.cn/ubuntu xenial-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
Get:4 http://mirrors.ustc.edu.cn/ubuntu xenial-proposed InRelease [251 kB]
Err:4 http://mirrors.ustc.edu.cn/ubuntu xenial-proposed InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
Get:5 http://mirrors.ustc.edu.cn/ubuntu xenial-backports InRelease [97.4 kB]
Err:5 http://mirrors.ustc.edu.cn/ubuntu xenial-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
Reading package lists... Done
W: GPG error: http://mirrors.ustc.edu.cn/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
E: The repository 'http://mirrors.ustc.edu.cn/ubuntu xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://mirrors.ustc.edu.cn/ubuntu xenial-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
E: The repository 'http://mirrors.ustc.edu.cn/ubuntu xenial-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://mirrors.ustc.edu.cn/ubuntu xenial-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
E: The repository 'http://mirrors.ustc.edu.cn/ubuntu xenial-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://mirrors.ustc.edu.cn/ubuntu xenial-proposed InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
E: The repository 'http://mirrors.ustc.edu.cn/ubuntu xenial-proposed InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://mirrors.ustc.edu.cn/ubuntu xenial-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
E: The repository 'http://mirrors.ustc.edu.cn/ubuntu xenial-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@c1-worker:/# apt-get install -y gnupg2 gnupg gnupg1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package gnupg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package gnupg2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gpgv

Package gnupg1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gnupg2' has no installation candidate
E: Package 'gnupg' has no installation candidate
E: Package 'gnupg1' has no installation candidate

**What you expected to happen**:
the baseImage kindest/node help install  gnupg2 gnupg gnupg1 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish

**Environment:**
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
       certSANs:
       - 49.234.62.179
       - 127.0.0.1
  extraPortMappings:
  - containerPort: 6443
    hostPort: 36443
    listenAddress: "0.0.0.0"
- role: worker
  extraPortMappings:
  - containerPort: 30000
    hostPort: 20000
  - containerPort: 30001
    hostPort: 20001
  - containerPort: 30002
    hostPort: 20002
  - containerPort: 30003
    hostPort: 20003
  - containerPort: 30004
    hostPort: 20004

**Comment by BenTheElder** [comment]
So first up: We don't support using the contents of the node like this, it's not documented and it is only guaranteed to provide what kind needs to create the respective kubernetes version.

We're not equipped to provide support for debian key management, sorry. I don't know anything about this mirror.

**Comment by BenTheElder** [comment]
Also: we're not using debian 11 for the nodes

**Comment by BenTheElder** [comment]
I will however try to come back to this later anyhow, in the meantime can you please share the kind version and the precise image you are using? It's also unclear what the desired end goal is.

**Comment by lusains** [comment]
> I will however try to come back to this later anyhow, in the meantime can you please share the kind version and the precise image you are using? It's also unclear what the desired end goal is.
Kind version：kind v0.14.0 go1.18.2 linux/amd64
image version：kindest/node:v1.24.0
my goal is I can exec apt-get update after change the mirror source, but the new mirror may notice  NO_PUBKEY
now I change the source to mirrors.aliyun.com, and it work well

**Comment by aojea** [comment]
> my goal is I can exec apt-get update after change the mirror source, but the new mirror may notice NO_PUBKEY
> now I change the source to mirrors.aliyun.com, and it work well

/close

it seems it is a configuration issue, but we don't support tweaking or modifying the images

**Comment by BenTheElder** [comment]
you may need to update to a newer image to do something like this, v0.14.0 is a bit old now.

but also, this isn't really something we're trying to support. kind provides [conformant](https://www.cncf.io/certification/software-conformance/) kubernetes, it is not providing a particular linux distro etc.

**Comment by gabriel-stefanescu** [comment]
> you may need to update to a newer image to do something like this, v0.14.0 is a bit old now.
> 
> but also, this isn't really something we're trying to support. kind provides [conformant](https://www.cncf.io/certification/software-conformance/) kubernetes, it is not providing a particular linux distro etc.
