### ISSUE TITLE
inside worker, why ping can resolve registry from dns, but ctr images pull is failed got no such host?

### ISSUE THREAD

**Issue by eveforest** [kubernetes-sigs/kind#2994]
After install kind cluster in my docker, i run exec -it into worker container, 
and try to use ctr pull image in registry like registry.cn-hangzhou.aliyuncs.com/ns/xxx:latest , it's failed.
`ctr images pull   --user user:pass registry.cn-hangzhou.aliyuncs.com/ns/hello:latest`
```
ctr: failed to copy: httpReadSeeker: failed open: failed to do request: 
Get "https://registry.cn-hangzhou.aliyuncs.com/v2/ns/hello/manifests/sha256:...": 
dial tcp: lookup registry.cn-hangzhou.aliyuncs.com on 192.168.65.2:53: no such host
```
but when i ping to registry.cn-hangzhou.aliyuncs.com ，i can get the ip.
`ping registry.cn-hangzhou.aliyuncs.com`
```
PING registry.cn-hangzhou.aliyuncs.com (120.55.105.209): 56 data bytes
64 bytes from 120.55.105.209: icmp_seq=0 ttl=37 time=38.588 ms
64 bytes from 120.55.105.209: icmp_seq=1 ttl=37 time=37.160 ms
```
so, why ctr can't resolve the registry , but ping is work, happen?

my environment:
docker desktop for window  4.13.0 (89412). + WSL2（Ubuntu22.04.1 LTS）

docker desktop Network CICR config:
192.168.65.0/24

WSL2 （Ubuntu2）:
IP addr: inet 192.168.60.2/24 brd 192.168.60.255 scope global eth0
/etc/resolv.conf -> nameserver 192.168.60.1 

container (kind Worker)
/etc/resolv.conf -> nameserver 192.168.65.2 options ndots:0

https://github.com/kubernetes-sigs/kind/issues/2994#tasklist-block-9859166c-2dba-4316-be51-9704791527b2

**Comment by eveforest** [comment]
then i add host to /etc/hosts file, it work. why dns 192.168.65.2 does'nt work?
`echo "120.55.105.209 registry.cn-hangzhou.aliyuncs.com" >> /etc/hosts`

**Comment by BenTheElder** [comment]
The kind worker is resolving via docker's embedded DNS socket, which then goes out to dockerd on the "host" (which here is the WSL2 VM), where are you running ping?

**Comment by BenTheElder** [comment]
KIND does some tricks to make the embedded socket routable from the coreDNS pod, but the behavior of the socket in resolving things is still docker's responsibility, and is configured by dockerd/the host.

**Comment by eveforest** [comment]
> The kind worker is resolving via docker's embedded DNS socket, which then goes out to dockerd on the "host" (which here is the WSL2 VM), where are you running ping?

@BenTheElder thx for reply. i run ping in worker node.

**Comment by BenTheElder** [comment]
containerd might have slightly different behavior if it's using go's built in DNS resolver client instead of the libc resolver, I think containerd is not build that way though.

I guess ping does not report how it is looking up the name

**Comment by BenTheElder** [comment]
> en... do you mean ping does'nt looking up the name in the way by 192.168.65.2:53, but containerd use that way, and that way is something wrong , right?

possibly? can we try something like `curl -V https://registry.cn-hangzhou.aliyuncs.com/v2/` in the worker?

**Comment by eveforest** [comment]
```
# curl -v https://registry.cn-hangzhou.aliyuncs.com/v2/
*   Trying 120.55.105.209:443...
* Connected to registry.cn-hangzhou.aliyuncs.com (120.55.105.209) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
```

**Comment by eveforest** [comment]
> > en... do you mean ping does'nt looking up the name in the way by 192.168.65.2:53, but containerd use that way, and that way is something wrong , right?
> 
> possibly? can we try something like `curl -v https://registry.cn-hangzhou.aliyuncs.com/v2/` in the worker?

still can resolve

**Comment by BenTheElder** [comment]
I was hoping we could see what DNS lookup was performed by curl or some tool other than containerd that works, so we can see the difference in how the name is resolved. It's weird that it would work in another tool in the same container, maybe using a different DNS server or using a hosts file

**Comment by BenTheElder** [comment]
maybe `apt update && apt install dnsutils && dig registry.cn-hangzhou.aliyuncs.com` in the node.

**Comment by BenTheElder** [comment]
So, we got the correct answer with dig, on 192.168.65.2:53, which is also what ctr or containerd are using, because it's the node-level DNS from the docker embedded DNS (or at least appears to be) and should be working .... 😕 

is there anything else at play here, like a proxy? cc @aojea

**Comment by eveforest** [comment]
@BenTheElder i change the dns server to 8.8.8.8, and ctr images pull worked! so it's docker dns problem.

**Comment by eveforest** [comment]
8.8.8.8 both ping and ctr pull worked
192.168.65.2 just ping worked, ctr pull failed.

**Comment by BenTheElder** [comment]
So in theory docker's DNS server should do this:
- if the hostname matches a container name on the network(s) the container is attached to, return the container IP
- otherwise resolve the host in dockerd (the daemon running on the "host", which would be WSL2 here) and reply back

**Comment by eveforest** [comment]
> So in theory docker's DNS server should do this:
> 
> * if the hostname matches a container name on the network(s) the container is attached to, return the container IP
> * otherwise resolve the host in dockerd (the daemon running on the "host", which would be WSL2 here) and reply back

hi @BenTheElder, thanks for your answer again. And yes，i change the deamon dns config to 8.8.8.8 which would be added to the emdeded dns, and the image pull success. Because it didn't use the external docker  DNS(192.168.65.5)  in the outside of container.
```
conntrack -L | grep udp

udp      17 28 src=172.18.0.4 dst=172.18.0.1 sport=59826 dport=53 src=127.0.0.11 dst=172.18.0.4 sport=55146 dport=59826 mark=0 use=1
udp      17 28 src=172.18.0.4 dst=8.8.8.8 sport=36256 dport=53 src=8.8.8.8 dst=172.18.0.4 sport=53 dport=36256 mark=0 use=1
```
 So the point is ctr images pull can't get the resolve from the external docker DNS. All image pull failed like below:
```
ctr: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://registry-1.docker.io/v2/library/nginx/manifests/sha256:943c25b4b66b332184d5ba6bb18234273551593016c0e0ae906bab111548239f": dial tcp: lookup registry-1.docker.io on 192.168.65.2:53: no such host
```
```
conntrack -L | grep udp

udp      17 7 src=172.18.0.2 dst=192.168.65.2 sport=57705 dport=53 src=127.0.0.11 dst=172.18.0.2 sport=45121 dport=57705 mark=0 use=1
udp      17 7 src=172.18.0.2 dst=192.168.65.2 sport=59556 dport=53 [UNREPLIED] src=127.0.0.11 dst=172.18.0.2 sport=45121 dport=59556 mark=0 use=1
udp      17 7 src=172.18.0.2 dst=192.168.65.5 sport=33858 dport=53 src=192.168.65.5 dst=172.18.0.2 sport=53 dport=33858 mark=0 use=1
```
But the ping can resolve the name
``` 
ping registry-1.docker.io

PING registry-1.docker.io (44.205.64.79): 56 data bytes
```
```
conntrack -L | grep udp

udp      17 24 src=172.18.0.2 dst=192.168.65.2 sport=54833 dport=53 src=127.0.0.11 dst=172.18.0.2 sport=45121 dport=54833 mark=0 use=1
udp      17 24 src=172.18.0.2 dst=192.168.65.5 sport=55008 dport=53 src=192.168.65.5 dst=172.18.0.2 sport=53 dport=55008 mark=0 use=1
```
So What caused the external docker DNS do not resolve registry from ctr images pull command? 
Is there any reason like the wsl2  environment used in docker desktop is special? By the way, my docker desktop use vpnkit-bridge to support the network.

**Comment by BenTheElder** [comment]
>  And yes，i change the deamon dns config to 8.8.8.8 which would be added to the emdeded dns, and the image pull success. Because it didn't use the external docker DNS(192.168.65.5) in the outside of container.

192.168.65.5 is probably the docker network gateway and shouldn't be usable outside of containers, it's just kind mapping the embedded docker listener that _should_ work inside the container, but the actual resolution of domains happens in `docker` running in WSL2.

> So What caused the external docker DNS do not resolve registry from ctr images pull command?
Is there any reason like the wsl2 environment used in docker desktop is special? By the way, my docker desktop use vpnkit-bridge to support the network.

I'm sorry I'm not a WSL2 user, I've only used it long enough to get kind working there initially a few years ago. I don't know of a reason this would happen.

You can try a more minimal case by creating a custom bridge network (any name, just any docker bridge network) and then running a container on that network, without any of the kind specific details, it should then still have the WSL2 docker embedded DNS resolution to debug.
