### ISSUE TITLE
pre-pull images that are not part of the build

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#30]
When we build Kubernetes we are able to preload built images into the `kind` node image, a typical kubernetes build does not actually build important relatively fixed images like `etcd` though, we should look at querying kubeadm for these at build time and pre-pulling them. 

Possibly we can use https://github.com/google/containerregistry to pull these directly into the built image without docker. These tools have worked pretty well for us underneath `rules_docker` in test-infra.

/priority important-soon
/kind enhancement
/assign

**Comment by BenTheElder** [comment]
running in the default image:
```
root@b0816c5f4071:/# kubeadm config images list
k8s.gcr.io/kube-apiserver-amd64:v1.11.3
k8s.gcr.io/kube-controller-manager-amd64:v1.11.3
k8s.gcr.io/kube-scheduler-amd64:v1.11.3
k8s.gcr.io/kube-proxy-amd64:v1.11.3
k8s.gcr.io/pause:3.1
k8s.gcr.io/etcd-amd64:3.2.18
k8s.gcr.io/coredns:1.1.3
```
Checking upstream, these are ~ mapped by kubernetes version, not config, so we should be able to pre-pull them at build time easily, we probably want to pull `.*etcd.*` and `.*pause.*`

ref: https://github.com/kubernetes/kubernetes/blob/69da1f83995f0fa1e555dfacef9e97abc63b9333/cmd/kubeadm/app/constants/constants.go#L376

**Comment by neolit123** [comment]
etcd, pause and coredns versions are hardcoded in a constants file. their version is bumped on each release. the control plane version in 1.11 was mapped to the `stable-1.11` endpoint, in 1.12 we moved to `stable-1` (this needs a cherry pick enhancement).

**Comment by BenTheElder** [comment]
Excellent, thanks! For the control plane in `docker` and `bazel` builds we have locally built images, but not in `apt`. For all of them we don't have pause, DNS, etcd since those aren't built in k8s.

**Comment by BenTheElder** [comment]
Fixed in https://github.com/kubernetes-sigs/kind/pull/89, will push new images.
