### ISSUE TITLE
pulling images are too slow

### ISSUE THREAD

**Issue by zffocussss** [kubernetes-sigs/kind#3002]
**What happened**:
it is too slow when pulling images in kind cluster

**What you expected to happen**:
as far as how docker pull images

**How to reproduce it (as minimally and precisely as possible)**:
run a pod with public image from docker hub
**Anything else we need to know?**:
kind v0.11.1 go1.17.2 darwin/amd64

**Environment:**

- kind version: (use `kind version`):
kind v0.11.1 go1.17.2 darwin/amd64
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:56:35Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:06:30Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
- Docker version: (use `docker info`):
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.12.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.3)
  extension: Manages Docker extensions (Docker Inc., v0.2.13)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 6
  Running: 2
  Paused: 0
  Stopped: 4
 Images: 96
 Server Version: 20.10.20
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.764GiB
 Name: docker-desktop
 ID: FCST:BAHR:T6OD:6DZH:4RFT:5YBO:TPJE:HTSZ:C7TH:PN3I:5HPX:RETV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 75
  Goroutines: 80
  System Time: 2022-11-15T08:48:31.750559552Z
  EventsListeners: 6
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
- OS (e.g. from `/etc/os-release`):
macos Apple M1 pro

**Comment by BenTheElder** [comment]
> kind v0.11.1 go1.17.2 darwin/amd64

this is very old, v0.17 is current

> it is too slow when pulling images in kind cluster

This isn't exactly actionable. We've done what we can. You could move container storage onto a tmpfs (i.e. /tmp) if you don't care about durability through reboots but that would be quite a breaking change.

You can also instead use `kind load ...` to avoid pulling.


I noticed your host appears to be an M1 mac but you're using the amd64 version of kind.

You should use the arm64 version.

**Comment by zaunist** [comment]
I have a idea to provide an environment variable for replacing the docker image source addr, and explain how to use in the documentation. Because access to docker.io may be slow in some areas, and we can provide a way to support access to docker's image mirror source addr. If this idea works, I'm happy to do it.

**Comment by BenTheElder** [comment]
> I have an idea to provide an environment variable for replacing the docker image source addr, and explain how to use in the documentation. Because access to docker.io may be slow in some areas, and we can provide a way to support access to docker's image mirror source addr. If this idea works, I'm happy to do it.

If you pull on the host it shouldn't be kind.
If it's on the nodes and we're configuring mirrors we really need to figure out a more general approach in config see #2875

**Comment by zffocussss** [comment]
why not kind run with the host docker images?I mean it is not required to load images into kind from host images storage.

**Comment by zffocussss** [comment]
> 

okay, I can try it . but can you tell me how to choose arm64?

**Comment by BenTheElder** [comment]
> why not kind run with the host docker images?I mean it is not required to load images into kind from host images storage.

Because docker's host storage is not something you can share with another container runtime, not even a second instance of docker, and we need kubelet to have a consistent "host" environment for the containers it manages, which is inside the kind node.

> okay, I can try it . but can you tell me how to choose arm64?

Install kind https://kind.sigs.k8s.io/docs/user/quick-start/#installation and use the arm64 instead of amd64.
I'm not sure how you installed it previously, since it hasn't been mentioned here.

**Comment by BenTheElder** [comment]
Also FYI docker does support configuring a mirror for docker.io specifically already, which is one of the reasons we haven't migrated to Kubernetes's project-wide registry.k8s.io system.
