### ISSUE TITLE
Kind v0.17 Image name is blank when doing a load

### ISSUE THREAD

**Issue by sbkpilot1** [kubernetes-sigs/kind#3006]
**What happened:**
Just upgraded to 0.17 and noticed that the image name is blank when doing a `kind load docker-image`, attached is a screen shot

**What you expected to happen:**
Image tag name should appear in the Image Loading message, this used to happen in earlier Kind versions

**How to reproduce it (as minimally and precisely as possible):**
Create a kind cluster
`kind create cluster --name test`

Load  a local docker image into the cluster
`kind load docker-image busybox:latest --name test`

Note Image is blank in the message should actually read `Image: "busybox:latest with ID...` instead it says `Image: ""`

**Anything else we need to know?:**
On WSL2 with Windows 11

**Environment:**
kind version: (use kind version): 0.17.0
Kubernetes version: (use kubectl version): v1.25.3
Docker version: (use docker info): 20.10.17
OS (e.g. from /etc/os-release): Debian 11 (bullseye) on WSL2

![kind_017_docker_load](https://user-images.githubusercontent.com/20803783/203151977-eb20fc01-e6c5-4374-ac8f-2ddb0ade7731.png)

**Comment by BenTheElder** [comment]
Can you please fill out the rest of the bug template with the environment details (docker or podman info command output, os and kind version output, etc) annd include a minimal example to reproduce this?

**Comment by sbkpilot1** [comment]
`❯ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.1)
  extension: Manages Docker extensions (Docker Inc., v0.2.7)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 86
  Running: 2
  Paused: 0
  Stopped: 84
 Images: 37
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.49GiB
 Name: docker-desktop
 ID: OR77:FN4L:FQJN:A4JU:D7NM:J47M:67AI:BL4B:EMBT:37FM:MCD2:PH3Q
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support`

`❯ kind --version
kind version 0.17.0`

**Comment by rmfitzpatrick** [comment]
I believe this was introduced in https://github.com/kubernetes-sigs/kind/commit/d44bdc8831d357fb835163fa308fab2e9dd690e3 where `sanitizedImage` is the empty string.

**Comment by aojea** [comment]
/triage-accept
/help wanted

I can reproduce it

```
kind load docker-image busybox:latest
Image: "" with ID "sha256:9d5226e6ce3fb6aee2822206a5ef85f38c303d2b37bfc894b419fca2c0501269" not yet present on node "kind-worker", loading...
Image: "" with ID "sha256:9d5226e6ce3fb6aee2822206a5ef85f38c303d2b37bfc894b419fca2c0501269" not yet present on node "kind-worker2", loading...
Image: "" with ID "sha256:9d5226e6ce3fb6aee2822206a5ef85f38c303d2b37bfc894b419fca2c0501269" not yet present on node "kind-control-plane", loading...
$ kind load docker-image busybox:latest
Image: "busybox:latest" with ID "sha256:9d5226e6ce3fb6aee2822206a5ef85f38c303d2b37bfc894b419fca2c0501269" found to be already present on all nodes.
```

**Comment by aojea** [comment]
> I believe this was introduced in [d44bdc8](https://github.com/kubernetes-sigs/kind/commit/d44bdc8831d357fb835163fa308fab2e9dd690e3) where `sanitizedImage` is the empty string.

yeah, it has to be there

**Comment by tao12345666333** [comment]
let me fix it

/assign

**Comment by rmfitzpatrick** [comment]
@tao12345666333 fwiw I've opened https://github.com/kubernetes-sigs/kind/pull/3013 but I'm not sure if that's the best way to go about the fix.

**Comment by tao12345666333** [comment]
reviewed. 
/unassign
