### ISSUE TITLE
How to upgrade NGINX ingress to 2.4.x ?

### ISSUE THREAD

**Issue by sbkpilot1** [kubernetes-sigs/kind#3007]
I need to use path rewriting but the old api spec is under version v1beta which isn't supported anymore with the latest Kubernetes.  The new spec is not supported by NGINX Controller version `1.5.1`.  Could you document how to upgrade NGINX Ingress Controller to `2.4.x`? 

I know it was mentioned that there are some `KIND` specific patches so not exactly sure what those are and how it differs with the general release.

**Comment by BenTheElder** [comment]
Upgrading ingress nginx installs is rather out of scope for this project. kind clusters are meant to be disposable. The version of ingress-nginx in the sample comes from the ingress-nginx project and is maintained there.

the patches are the same as the other examples:
 - use a label selector to pin it to the labeled node
 - use a nodePort service to expose the ports

**Comment by tao12345666333** [comment]
As an extra, the latest version of ingress-nginx is 1.5.1.  No v2 version yet
