### ISSUE TITLE
Docs: How to stop a cluster?

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/kind#3008]
I would like to know how to stop/pause a kind cluster.

The control-plane (and other processes) use CPU constantly and the fan of
my laptop starts and the sound is not nice.

That's why I think it would be great to have some docs on how to stop a cluster.

**Comment by afbjorklund** [comment]
The words "stop" and "pause" have distinct meanings in Docker....

https://docs.docker.com/engine/reference/commandline/stop/

https://docs.docker.com/engine/reference/commandline/pause/

Both would help with fan noise (CPU use) , but in different ways

----

I think what you want here is pause, similar to what minikube has ?

* https://github.com/kubernetes/minikube/issues/14773

I guess delete/remove would also help with fan noise, but even more brutal :-)

But that's also a nice feature, to archive the cluster setup and archive it for later.

**Comment by BenTheElder** [comment]
It's not a feature we've invested in yet, we worked on reboots first which should work fine now under docker. There are open feature issues, discussion should continue there.
