### ISSUE TITLE
Add the suffix  1 to the first worker node name for a multi-node cluster

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes-sigs/kind#3014]
**What would you like to be added**:

Add the suffix  `1` to the first worker node name for a multi-node cluster.

For a multi-node kind cluster, the default worker node names are 
```
<clusterName>-worker
<clusterName>-worker2
```
How about changing the node names to
```
<clusterName>-worker1
<clusterName>-worker2
...
```

For a single-node cluster, the name is still
```
<clusterName>-worker
```

A possible implementation is to add the suffix `1` to the first node name string if there are more than 1 worker node in [provision.go](https://github.com/kubernetes-sigs/kind/blob/7d26b50a129faf1a7024ce1337d516aada1db118/pkg/cluster/internal/providers/docker/provision.go#L41).  

```
    nodeNamer := common.MakeNodeNamer(cfg.Name)
    names := make([]string, len(cfg.Nodes))
    for i, node := range cfg.Nodes {
        name := nodeNamer(string(node.Role)) // name the node
        names[i] = name
    }
    if len(cfg.Nodes) > 1 {
        names[0] = fmt.Sprintf("%s1", names[0])
    }
```

**Why is this needed**:

Improve the readability and usability with well-numbered node names.

**Comment by BenTheElder** [comment]
This would be a high-fuss breaking change for users that depend on the naming scheme which has been predictable for years.

I agree that this would be better, but at this point we'd break so many things if we changed it.
