### ISSUE TITLE
Kindnet fails during create cluster on RHEL8 when ipv6.disable=1

### ISSUE THREAD

**Issue by mmoore0011** [kubernetes-sigs/kind#3016]
**What happened**:
Create cluster fails with:

```
ERROR: failed to create cluster: command "podman run --name kind-control-plane --hostname kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --tmpfs /tmp --tmpfs /run --volume df992b4a85f944c329890d2eccff715d0d79d7c16217b1f2e7cd81365f823f76:/var:suid,exec,dev --volume /lib/modules:/lib/modules:ro -e KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER --detach --tty --net kind --label io.x-k8s.kind.cluster=kind -e container=podman --volume /dev/mapper:/dev/mapper --publish=127.0.0.1:36055:6443/tcp -e KUBECONFIG=/etc/kubernetes/admin.conf docker.io/kindest/node:v1.22.15" failed with error: exit status 127

Command Output: time="2022-12-01T18:23:45-05:00" level=warning msg="Failed to load cached network config: network kind not found in CNI cache, falling back to loading network kind from disk"

Error: plugin type="bridge" failed (add): cni plugin bridge failed: open /proc/sys/net/ipv6/conf/eth0/accept_dad: no such file or directory
```

The server is booted with `ipv6.disable=1` so `/proc/sys/net/ipv6` doesn't exist

**What you expected to happen**:
Cluster starts

**How to reproduce it (as minimally and precisely as possible)**:
Not sure if this is specific to RHEL8 with podman but, boot a RHEL8 server with `ipv6.disable=1` and run `kind create cluster`

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
`kind version 0.17.0`

- Kubernetes version: (use `kubectl version`):
```
Client Version: v1.25.4
Kustomize Version: v4.5.7
```

- Docker version: (use `docker info`):
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue Apr 19 06:16:32 2022
OS/Arch:    linux/amd64
```

- OS (e.g. from `/etc/os-release`):
```
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
```

**Comment by aojea** [comment]
seems related to https://github.com/containers/netavark/issues/439

but that doesn't look like a kindnet error

can you create a simple container with podman using ipv6?

https://developers.redhat.com/articles/2022/08/10/how-conifgure-podman-40-ipv6#attach_a_pod_to_the_podman_network_interface

**Comment by mmoore0011** [comment]
Thanks @aojea 

no, it produces the same error if I try to create any network using ipv6 as you'd expect. 

So I guess what I'm really asking is for a way to run kindnet with ipv6 disabled.  
Or, alternatively, is there another CNI I should be using instead?

**Comment by aojea** [comment]
but kindnet doesn't use the bridge plugin

>  Error: plugin type="bridge" failed (add): cni plugin bridge failed: open /proc/sys/net/ipv6/conf/eth0/accept_dad: no such file or directory

which kindnet are you using?

**Comment by mmoore0011** [comment]
I'm not sure what version I'm using, its just whatever came with kind.  How do I tell?
```
# podman network inspect kind
[
     {
          "name": "kind",
          "id": "0b27c158feb36a87909ec730ece6280581dd407e2672359be7725dd",
          "driver": "bridge",
          "network_interface": "cni-podman1",
          "created": "2022-12-01T17:15:42.053602247-05:00",
          "subnets": [
               {
                    "subnet": "fc00:f833:ccd:e793::/64",
                    "gateway": "fc00:f833:ccd:e793::1"
               },
               {
                    "subnet": "10.89.0.0/24",
                    "gateway": "10.89.0.1"
               }
          ],
          "ipv6_enabled": true,
          "internal": false,
          "dns_enabled": false,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
```

**Comment by mmoore0011** [comment]
I was able to get around this by manually creating a kind network.

```
podman network rm -f kind
podman network create kind
kind create cluster
```

Not sure what the implications of that are...

**Comment by aojea** [comment]
ok, clarified, that bridge plugin error is from podman not from kindnet ...

that workaround is ok, it just creates the kind network without ipv6 , so kind doesn't try to create it (and fail) ... you just don't have IPv6 ... but you already knew this ;)

**Comment by mmoore0011** [comment]
Thanks for your guidance!
