### ISSUE TITLE
Failed to pull docker images timeout

### ISSUE THREAD

**Issue by husseinsa** [kubernetes-sigs/kind#3017]
Running docker-engine on WSL2 with Kind
 
**Environment** 

Kind version: `kind v0.17.0 go1.19.2 linux/amd64`
docker version: ` 20.10.21`
OS version: ` Ubuntu 20.10.2 LTS`
kubectl version: `v1.25`
k8 control plane version:  v1.25.3

Not able to pull docker images on the cluster.

` Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to resolve reference "docker.io/library/nginx:latest": failed to do request: Head "https://registry-1.docker.io/v2/library/nginx/manifests/latest": dial tcp: lookup registry-1.docker.io on 172.18.0.1:53: read udp 172.18.0.2:36585->172.18.0.1:53: i/o timeout`

Its working fine on docker

![image](https://user-images.githubusercontent.com/22456321/205377197-371c8eea-3f0a-4e3c-8cd2-e9f94e80fccd.png)

**Comment by stmcginnis** [comment]
Can you fill in the rest of the details from the issue template?

**Environment:**

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by massenz** [comment]
Don't know if this was ever resolved, but it could be something related to the `HTTPS_PROXY` setting on the shell, when the cluster was created.
I am seeing that Kind passes that into the created container:
```
└─( deti proxy-control-plane env
'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=proxy-control-plane
TERM=xterm
NO_PROXY=172.18.0.0/16,fc00:f853:ccd:e793::/64,10.96.0.0/16,10.244.0.0/16,proxy-control-plane,.svc,.svc.cluster,.svc.cluster.local
KUBECONFIG=/etc/kubernetes/admin.conf
no_proxy=172.18.0.0/16,fc00:f853:ccd:e793::/64,10.96.0.0/16,10.244.0.0/16,proxy-control-plane,.svc,.svc.cluster,.svc.cluster.local
HTTPS_PROXY=http://127.0.0.1:9995
https_proxy=http://127.0.0.1:9995
container=docker
HOME=/root
```
(which in this case leads to a bug, as `localhost` on the container is not what it thinks it to be)
Re-creating the cluster with `HTTPS_PROXY` unset fixes the issue.

I have not found this documented, but I presume it is "intended behavior", although it may lead to issues (such as in my case, where the proxy is running locally, for SSH auth purposes, but is not required for pulling containers).

**Comment by BenTheElder** [comment]
The proxy env are something of an undocumented informal standard themselves, which kind respects. 

They are documented in kind however, at https://kind.sigs.k8s.io/docs/user/quick-start/#configure-kind-to-use-a-proxy

If your proxy is local-only, unfortunately it will not work properly within a container, and you'll want to avoid passing those env to `kind`.

**Comment by massenz** [comment]
LoL I did look at all the reference docs, assuming it was some sort of "advanced" feature and didn't think to check out the Getting Started section.
Thanks for quick follow up.
I don't need the proxy for that (it is used to enable internal SSH) but the setting was passed in "silently" which caused surprising results -- maybe having a little warning log during `cluster create` may be useful to avoid getting caught unawares.

**Comment by BenTheElder** [comment]
Maybe ... I've never seen another tool warn for proxies though, it is "standard" to respect these environment variables and it's normal that environment variables are "silently" inherited by subprocesses. 

Proxies have been a constant headache throughout the Kubernetes project though (e.g. with registry.k8s.io users) >.>
