### ISSUE TITLE
Wrong kind node image digest

### ISSUE THREAD

**Issue by kevinbin** [kubernetes-sigs/kind#3019]
**What happened**:

The pull image label does not match the digest when the cluster is created. After manual pull, the cluster is created successfully.

 kind create cluster -v 10                                                                                                                                 
enabling experimental podman provider
Creating cluster "kind" ...
DEBUG: podman/images.go:67] Pulling image: docker.io/kindest/node@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1 ...
Ensuring node image (kindest/node:v1.25.3)
...

------------------

 podman images --digests                                                                                                                                         
REPOSITORY              TAG         DIGEST                                                                   IMAGE ID      CREATED        SIZE
docker.io/kindest/node  v1.25.3     sha256:cd248d1438192f7814fbca8fede13cfe5b9918746dfa12583976158a834fd5c5  aa7084fa36af

----------
 kind create cluster --image kindest/node:v1.25.3                                                                                                         
enabling experimental podman provider
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.25.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾

**Environment:**

podman version 4.3.1
kind version 0.17.0
Darwin MBA 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 20:57:23 PDT 2022; root:xnu-8020.121.3~2/RELEASE_ARM64_T8110 arm64

**Comment by BenTheElder** [comment]
That's expected, the digest is of a multi-arch image and will be resolved to an architecture specific image with that digest. That behavior is in podman not kind.
