### ISSUE TITLE
CI: should we need switch ubuntu-22.04 for cgroup v2 test env?

### ISSUE THREAD

**Issue by tao12345666333** [kubernetes-sigs/kind#3020]
**What should be cleaned up or changed**:

GitHub Action has provided ubuntu-22.04 as the default operating environment.

ubuntu-22.04 already uses cgroups v2 by default, do we want to switch the current cgroup v2 test to use ubuntu-22.04?

xref: 
* https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
* https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Why is this needed**:

No longer depends on Vagrant's nesting, maybe faster (but need to verify)

**Comment by tao12345666333** [comment]
cc @AkihiroSuda

**Comment by AkihiroSuda** [comment]
The vagrant test uses Fedora to cover several SELinux-related quirks, such as 
https://github.com/kubernetes-sigs/kind/commit/e601f2f3439332d626c1c1e2e1fc5ef922651fff#diff-462bea45380eb8ea42a17c2f68e96ff867b6301ef87ea1e885c94728de72f889R45
https://github.com/kubernetes-sigs/kind/commit/b1a6869f9dbb19826245b88f321f7ad52f2e9a23

So I'd prefer to retain the vagrant tests.

**Comment by AkihiroSuda** [comment]
(Off-topic: Cirrus CI might be faster than GHA for running Vagrant)

**Comment by aojea** [comment]
+1 to keep Fedora on the CI, it has been a good signal for podman, selinux, btrfs, cgroupsv2, ... any thing that is more bleeding edge that more stable distros

**Comment by tao12345666333** [comment]
make sense. 

Let's keep it. Thanks!

/close

**Comment by BenTheElder** [comment]
We'll want to keep testing cgroups v1 for now unfortunately, the migration to v2 only is going to be challenging for this project. Even if we switch, I agree that we still want to test the fedora environment, where we've encountered many quirks we're likely to run into with end users in the same or similar environments.
