### ISSUE TITLE
adding drives to nodes

### ISSUE THREAD

**Issue by Abdullah-alfadhel** [kubernetes-sigs/kind#3021]
I'm trying to test rook-ceph, and one of it needs is to have an unformatted drive in the node. How can I emulate that using kind?

**Comment by BenTheElder** [comment]
I don't know ceph's requirements. In some cases a /dev/loop device is sufficient, there are somepitfalls that can be found in other issues here, but it's workable.

If you have an actual hardware unformatted drive or otherwise device for testing, you can pass it through to a kind node with https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts

**Comment by Abdullah-alfadhel** [comment]
Actually it worked, but it didn't :) it did recognize the drives but still it shows that they are in the same host, is there a way to prevent that?

```bash
2022-12-15 07:21:41.085590 W | cephclient: all OSDs are running on the same host. not performing upgrade check. running in best-effort
```

and 
```bash
022-12-15 07:33:34.624774 E | op-osd: failed to update cluster "rook-ceph" Storage. failed to update object "rook-ceph/rook-ceph" status: Operation cannot be fulfilled on cephclusters.ceph.rook.io "rook-ceph": the object has been modified; please apply your changes to the latest version and try again
```

I'm using rook-ceph for the deployment, it worked on separated machines, and I thought it would be best to do it in Kind, but for some reason it doesn't work.


if you don't think kind can support this kind of testing, that's fine. And thank you for your time.

**Comment by BenTheElder** [comment]
Sorry, there's been a lot ...

I'm not familiar enough with ceph and I don't see that changing anytime soon, there's too many other things to do and I don't work with it and I don't think we have any projects in the organization that do.

I can't comment on what makes sense here, but generally speaking if you're going to manage host devices directly it's best to treat that host as a real cluster node e.g. by installing with kubeadm.

**Comment by aojea** [comment]
https://github.com/kubernetes-sigs/kind/issues/745#issuecomment-516920036

you have to use cephfs, the other modes depend on the kernel and I think that are not able to be used namespaced
