### ISSUE TITLE
kindest/node 1.25.4 missing

### ISSUE THREAD

**Issue by yellowhat** [kubernetes-sigs/kind#3022]
**What happened**:
Currently the following tags are available for the container image `kindest/node`:

* `v1.25.1`
* `v1.25.2`
* `v1.25.3`
* `v1.26.0`

But it is missing [v1.25.4](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#v1254)

**What you expected to happen**:

Build `kindest/node` container image for `v1.25.4`.

**How to reproduce it (as minimally and precisely as possible)**:

Go to: https://hub.docker.com/r/kindest/node/tags?page=1&name=1.25

Thanks

**Comment by aojea** [comment]
kind images doesn't follow the kubernetes cadence, users may build your images https://github.com/kubernetes-sigs/kind/issues/197
