### ISSUE TITLE
How to add "Kind" settings to "/.kube/config" file?

### ISSUE THREAD

**Issue by bestofman** [kubernetes-sigs/kind#3035]
I have installed `kubeadm` previously and configured it using `kubeadm --init` and the configs are inside `/.kube/config` file by now. I recently installed `kind` and want to know how should I configure it? 

My goal is to using `kind` to work with `kubernetes` locally alongside `skaffold`. It seems images can't be pulled directly from a local storage to `kubeadm` using `skaffold` and we need something like `kind` in between.

**Comment by BenTheElder** [comment]
1) Have you `kubeadm reset` first? Trying to run tools like kind on a host that is already a kubernetes cluster node is fraught with issues.

2) `$KUBECONFIG` and `--kubeconfig` flags are the standard way to tell Kubernetes tools what config file to use. https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/

**Comment by BenTheElder** [comment]
https://kind.sigs.k8s.io/docs/user/quick-start/#interacting-with-your-cluster

**Comment by bestofman** [comment]
> 1. Have you `kubeadm reset` first? Trying to run tools like kind on a host that is already a kubernetes cluster node is fraught with issues.
> 
>     2. `$KUBECONFIG` and `--kubeconfig` flags are the standard way to tell Kubernetes tools what config file to use. See `kind create cluster --help` or `kind export kubeconfig --help`, and https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/

No I didn't! So you say it's necessary to `kubeadm reset` before configuring the `kind`? If I want only the simplest default basic configuration, should I only do `kubeadm reset` and then `kubeadm --init` or it's necessary to create a separate config file for the `kind` and add it at the end of the init command like `kubeadm --init --config kindconfig.yaml`?

**Comment by BenTheElder** [comment]
> No I didn't! So you say it's necessary to kubeadm reset before configuring the kind?

No, it's not strictly necessary, but I would not advise mixing `kubeadm init` on a machine and also trying to run non-kubernetes containers on it, especially something like KIND or minikube. This will cause all sorts of headaches. Kubernetes is designed to solely manage the container runtime and the machine.

>  If I want only the simplest default basic configuration, should I only do kubeadm reset and then kubeadm --init or it's necessary to create a separate config file for the kind and add it at the end of the init command like kubeadm --init --config kindconfig.yaml?

You don't need to use kubeadm directly at all to use kind, or vice versa. If you're not using the kubeadm cluster then `kubeadm reset` shoudl clean it up.

I'm not sure what you mean by kindconfig.yaml, but kind doesn't support managing host kubeadm, it runs kubeadm inside of a """node""" container.

**Comment by bestofman** [comment]
> > No I didn't! So you say it's necessary to kubeadm reset before configuring the kind?
> 
> No, it's not strictly necessary, but I would not advise mixing `kubeadm init` on a machine and also trying to run non-kubernetes containers on it, especially something like KIND or minikube. This will cause all sorts of headaches. Kubernetes is designed to solely manage the container runtime and the machine.
> 
> > If I want only the simplest default basic configuration, should I only do kubeadm reset and then kubeadm --init or it's necessary to create a separate config file for the kind and add it at the end of the init command like kubeadm --init --config kindconfig.yaml?
> 
> You don't need to use kubeadm directly at all to use kind, or vice versa. If you're not using the kubeadm cluster then `kubeadm reset` shoudl clean it up.
> 
> I'm not sure what you mean by kindconfig.yaml, but kind doesn't support managing host kubeadm, it runs kubeadm inside of a """node""" container.

I think you say after installing `kind` it will automatically generate a config file within `./kube/config` and there is no need to execute another command like `kubeadm --init` like what we do after installing `kubeadm`?

**Comment by BenTheElder** [comment]
> I think you say after installing kind it will automatically generate a config file within ./kube/config and there is no need to execute another command like kubeadm --init like what we do after installing kubeadm?

Not exactly. 

After running `kind create cluster` it will place the cluster details in the standard kubeconfig location (unless you request otherwise with KUBECONFIG or --kubeconfig).

The default location, normally, is `$HOME/.kube/config`, and `$HOME` is typically not `/`.

`/.kube/config` is a kubeadm thing.

There is no need to run `kubeadm init` when using kind.

**Comment by BenTheElder** [comment]
https://kind.sigs.k8s.io/docs/user/quick-start/ covers this in more detail, including  https://kind.sigs.k8s.io/docs/user/quick-start/#interacting-with-your-cluster
