### ISSUE TITLE
Unclear release version text in documentation

### ISSUE THREAD

**Issue by jglogan** [kubernetes-sigs/kind#3038]
**What would you like to be documented**:

From the docs:

```
The default node image is a Kubernetes v1.25.3 image: kindest/node:v1.25.2@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1
```

The versions here are inconsistent.  Is this intended?  Can this be fixed if necessary?

**Why is this needed**:

The wording is confusing at present.

**Comment by BenTheElder** [comment]
Sorry that's a typo, if you inspect `sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1` or a running default cluster you'll find 1.25.3, it's consistent in the rest of the release text but not the first mention.

**Comment by BenTheElder** [comment]
I've fixed this.
