### ISSUE TITLE
What is the equivalent command of "minikube start --memory 5120 --cpus=4" for "Kind"?

### ISSUE THREAD

**Issue by bestofman** [kubernetes-sigs/kind#3047]
Here in [Cassandra deployment instruction][1], it says:

> Caution:
> 
> Minikube defaults to 2048MB of memory and 2 CPU. Running Minikube with
> the default resource configuration results in insufficient resource
> errors during this tutorial. To avoid these errors, start Minikube
> with the following settings:
> 
> minikube start --memory 5120 --cpus=4

But I don't know what is the equivalent command if I use `Kind` instead of `minikube`? 

I also like to know if I want to set these settings permanently for my `Kind` cluster, how can I do that?
  [1]: https://kubernetes.io/docs/tutorials/stateful-application/cassandra/

**Comment by aojea** [comment]
There is no equivalent, the resources depends on the machine or VM where you are running kind
