### ISSUE TITLE
Networking somewhat broken with iptables nf_tables mode 1.8.8 on the host

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#3054]
Quick placeholder issue for https://github.com/kubernetes/minikube/issues/15573#issuecomment-1374286267

We're going to have to get creative to deal with this properly. cc @aojea

**Comment by aojea** [comment]
@danwinship these is the second weird report about iptables, the first was this one https://github.com/kubernetes/kubernetes/issues/114537

Is there something new going on with the iptables binaries?

**Comment by aojea** [comment]
Oh, I see, it seems to be related to https://bugzilla.netfilter.org/show_bug.cgi?id=1632

**Comment by BenTheElder** [comment]
I actually think we should just do the minimum viable thing and unblock this. I think it's less fragile than parsing the rules and reconstructing the entire rule and hopefully iptables nftables is working on compatibility improvements now.

https://github.com/kubernetes-sigs/kind/pull/3121

**Comment by BenTheElder** [comment]
mitigated in https://github.com/kubernetes-sigs/kind/pull/3121, should be released soon (maybe next week, lot going on atm http://k8s.io/image-registry-redirect)
