### ISSUE TITLE
RFE: listing supported providers and currently configured provider

### ISSUE THREAD

**Issue by yibozhuang** [kubernetes-sigs/kind#3056]
**What would you like to be added**:

It would be great if the `kind` cli can support listing supported providers as well as an option/flag to show the currently configured provider.

e.g.

`kind provider` lists all supported provider (docker, podman, etc.)
`kind provider --current` would show the currently configured provider (docker)

**Why is this needed**:

We have use cases where having this would benefit our internal tooling for determining what the current provider configured for kind is. And in the case of forks of kind that are setting the default provider to be not docker, then we cannot assume that if `KIND_EXPERIMENTAL_PROVIDER` env is missing, that the configured provider would be docker. So having this subcommand making the configured provider explicit is very useful.

Very much open to UX suggestions and other feedback around this.

**Comment by BenTheElder** [comment]
> kind provider lists all supported provider (docker, podman, etc.)

There are only two right now, and one of them is considered experimental / not fully stable.

Whenever podman is used, a log message is printed.
If this message isn't printed then it is docker.

> kind provider --current would show the currently configured provider (docker)

This seems misleading. Provider is not a stateful thing, it can be different per-invocation and isn't stored anywhere.

> We have use cases where having this would benefit our internal tooling for determining what the current provider configured for kind is.

Can you please elaborate on this use case?

For example, if you're attempting to locate the nodes, you can just check `kind get nodes` for the cluster --name and then cross check those against podman/docker containers by the node names (`ps`).

Regardless, this proposed command does not follow the pattern of the other commands.

**Comment by yibozhuang** [comment]
> Whenever podman is used, a log message is printed.
If this message isn't printed then it is docker.

But consider forks of kind that may set the default provider to something else that's not docker (say podman), then we cannot just use the env `KIND_EXPERIMENTAL_PROVIDER` to determine what the runtime provider is.

> This seems misleading. Provider is not a stateful thing, it can be different per-invocation and isn't stored anywhere.
Sure but you can argue that `kind get clusters` is also not stateful as you are invoking docker/podman commands underneath. Here we just want to have a way to figure out the current provider based on whether env `KIND_EXPERIMENTAL_PROVIDER` is set and/or if for forked kind binaries that default to something that's not docker.

> Can you please elaborate on this use case?
Use case: for some internal tooling that wraps around kind (and forks of kind that set the default provider in code to not docker), we need to mechanism to be able to figure out the kind configuration to use based on the configured provider. We can't just rely on `KIND_EXPERIMENTAL_PROVIDER` env due to the forked cases where default is not docker. And for the purpose of the wrapper, ideally it would rely on `kind` cli to provide that information (as with all other kind operations like create cluster, get cluster, etc.)

> Regardless, this proposed command does not follow the pattern of the other commands.
I'm very much open to UX suggestions and/or ways to expose this information. Basically we need a consistent mechanism to determine what are the list of supported providers and the current configured provider is. Also open to other ideas if you think getting it from the kind cli is not preferable.

**Comment by BenTheElder** [comment]
cc @aojea 

I don't think this makes sense currently, and we're still not near podman being fully stable / supported, leaving only one fully supported provider. Even if we had a fully supported provider, I think it would make more sense for external tooling to detect the clusters (e.g. call list / get clusters with each provider, or inspect for the well-known container naming scheme directly with docker/podman) than to add this command even if we had a second supported provider.

**Comment by BenTheElder** [comment]
I think the supported answer for now is:

```shell
KIND_EXPERIMENTAL_PROVIDER=podman kind get clusters
KIND_EXPERIMENTAL_PROVIDER=docker kind get clusters
```

Docker is still the only non-experimental provider, and the wrapping code is either using the default provider or explicitly setting it anyhow.

Forked kind implementations are not something we're going to add more supported surface for. For non-forked implementations either calling into the exported kind methods or using the existing commands should be sufficient.

We've seen no further demand for this feature, so I'm going to close it for now.
