### ISSUE TITLE
kind create cluster fails to create cluster on default install

### ISSUE THREAD

**Issue by bart0sh** [kubernetes-sigs/kind#306]
Running ```kind create cluster``` just after  ```go get sigs.k8s.io/kind``` install produces this error:

```
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.13.3) 🖼 
 ✓ [control-plane] Creating node container 📦 
 ✓ [control-plane] Fixing mounts 🗻 
 ✓ [control-plane] Starting systemd 🖥
 ✓ [control-plane] Waiting for docker to be ready 🐋 
 ✓ [control-plane] Pre-loading images 🐋 
 ✓ [control-plane] Creating the kubeadm config file ⛵
ERRO[14:34:06] failed to init node with kubeadm: exit status 1  ☸ 
 ✗ [control-plane] Starting Kubernetes (this may take a minute) ☸
ERRO[14:34:06] failed to init node with kubeadm: exit status 1 
Error: failed to create cluster: failed to init node with kubeadm: exit status 1
```

System info:
* openSUSE 42.3 (x86_64)
* go1.11.2 linux/amd64
* Docker 17.09.1-ce

Debug output:
```
$ kind create cluster --loglevel debug
DEBU[14:38:01] Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\t{{.Label "io.k8s.sigs.kind.cluster"}}] 
Creating cluster "kind" ...
DEBU[14:38:01] Running: /usr/bin/docker [docker inspect --type=image kindest/node:v1.13.3@sha256:d1af504f20f3450ccb7aed63b67ec61c156f9ed3e8b0d973b3dee3c95991753c] 
INFO[14:38:01] Image: kindest/node:v1.13.3@sha256:d1af504f20f3450ccb7aed63b67ec61c156f9ed3e8b0d973b3dee3c95991753c present locally 
 ✓ Ensuring node image (kindest/node:v1.13.3) 🖼
DEBU[14:38:01] Running: /usr/bin/docker [docker info --format '{{json .SecurityOptions}}'] 
DEBU[14:38:01] Running: /usr/bin/docker [docker run -d --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname kind-control-plane --name kind-control-plane --label io.k8s.sigs.kind.cluster=kind --label io.k8s.sigs.kind.role=control-plane --entrypoint=/usr/local/bin/entrypoint --expose 45760 -p 45760:6443 kindest/node:v1.13.3@sha256:d1af504f20f3450ccb7aed63b67ec61c156f9ed3e8b0d973b3dee3c95991753c /sbin/init] 
DEBU[14:38:01] Running: /usr/bin/docker [docker exec --privileged kind-control-plane rm -f /etc/machine-id] 
DEBU[14:38:01] Running: /usr/bin/docker [docker exec --privileged kind-control-plane systemd-machine-id-setup] 
 ✓ [control-plane] Creating node container 📦
DEBU[14:38:01] Running: /usr/bin/docker [docker info --format '{{json .SecurityOptions}}'] 
DEBU[14:38:01] Running: /usr/bin/docker [docker exec --privileged kind-control-plane mount -o remount,ro /sys] 
DEBU[14:38:01] Running: /usr/bin/docker [docker exec --privileged kind-control-plane mount --make-shared /] 
DEBU[14:38:01] Running: /usr/bin/docker [docker exec --privileged kind-control-plane mount --make-shared /run] 
DEBU[14:38:01] Running: /usr/bin/docker [docker exec --privileged kind-control-plane mount --make-shared /var/lib/docker] 
 ✓ [control-plane] Fixing mounts 🗻
DEBU[14:38:01] Running: /usr/bin/docker [docker kill -s SIGUSR1 kind-control-plane] 
 ✓ [control-plane] Starting systemd 🖥 
DEBU[14:38:01] Running: /usr/bin/docker [docker exec --privileged -t kind-control-plane systemctl is-active docker] 
DEBU[14:38:01] Running: /usr/bin/docker [docker exec --privileged -t kind-control-plane systemctl is-active docker] 
DEBU[14:38:01] Running: /usr/bin/docker [docker exec --privileged -t kind-control-plane systemctl is-active docker] 
DEBU[14:38:01] Running: /usr/bin/docker [docker exec --privileged -t kind-control-plane systemctl is-active docker] 
DEBU[14:38:01] Running: /usr/bin/docker [docker exec --privileged -t kind-control-plane systemctl is-active docker] 
DEBU[14:38:02] Running: /usr/bin/docker [docker exec --privileged -t kind-control-plane systemctl is-active docker] 
 ✓ [control-plane] Waiting for docker to be ready 🐋
DEBU[14:38:02] Running: /usr/bin/docker [docker exec --privileged kind-control-plane find /kind/images -name *.tar -exec docker load -i {} ;] 
DEBU[14:38:05] Running: /usr/bin/docker [docker exec --privileged -t kind-control-plane cat /kind/version] 
 ✓ [control-plane] Pre-loading images 🐋
INFO[14:38:05] Using KubeadmConfig:

apiServer:
  certSANs:
  - localhost
apiVersion: kubeadm.k8s.io/v1beta1
clusterName: kind
kind: ClusterConfiguration
kubernetesVersion: v1.13.3
---
apiVersion: kubeadm.k8s.io/v1beta1
bootstrapTokens:
- token: abcdef.0123456789abcdef
kind: InitConfiguration
localAPIEndpoint:
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
---
apiVersion: kubelet.config.k8s.io/v1beta1
evictionHard:
  imagefs.available: 0%
  nodefs.available: 0%
  nodefs.inodesFree: 0%
imageGCHighThresholdPercent: 100
kind: KubeletConfiguration
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration

 
DEBU[14:38:05] Running: /usr/bin/docker [docker cp /tmp/043838321 kind-control-plane:/kind/kubeadm.conf] 
 ✓ [control-plane] Creating the kubeadm config file ⛵
DEBU[14:38:05] Running: /usr/bin/docker [docker exec --privileged kind-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf] 
ERRO[14:42:30] failed to init node with kubeadm: exit status 1  ☸ 
 ✗ [control-plane] Starting Kubernetes (this may take a minute) ☸
ERRO[14:42:30] failed to init node with kubeadm: exit status 1 
DEBU[14:42:30] Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\t{{.Label "io.k8s.sigs.kind.cluster"}} --filter label=io.k8s.sigs.kind.cluster=kind] 
DEBU[14:42:30] Running: /usr/bin/docker [docker rm -f -v kind-control-plane] 
Error: failed to create cluster: failed to init node with kubeadm: exit status 1
```

**Comment by neolit123** [comment]
can you try fetching a kubelet log before it does the `rm`?

**Comment by bart0sh** [comment]
the log is quite big. 2 errors I've noticed that may help to investigate this:
```
Feb 15 14:06:45 kind-control-plane kubelet[781]: W0215 14:06:45.141247     781 cni.go:203] Unable to update cni config: No networks found in /etc/cni/net.d
Feb 15 14:06:45 kind-control-plane kubelet[781]: E0215 14:06:45.141317     781 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Feb 15 14:06:45 kind-control-plane kubelet[781]: E0215 14:06:45.196034     781 summary_sys_containers.go:47] Failed to get system container stats for "/docker/c8021afbdc3a74d5862262d583276a65bb4d6fa4bb0161f09251fc8068489aff/docker/c8021afbdc3a74d5862262d583276a65bb4d6fa4bb0161f09251fc8068489aff/system.slice/kubelet.service": failed to get cgroup stats for "/docker/c8021afbdc3a74d5862262d583276a65bb4d6fa4bb0161f09251fc8068489aff/docker/c8021afbdc3a74d5862262d583276a65bb4d6fa4bb0161f09251fc8068489aff/system.slice/kubelet.service": failed to get container info for "/docker/c8021afbdc3a74d5862262d583276a65bb4d6fa4bb0161f09251fc8068489aff/docker/c8021afbdc3a74d5862262d583276a65bb4d6fa4bb0161f09251fc8068489aff/system.slice/kubelet.service": unknown container "/docker/c8021afbdc3a74d5862262d583276a65bb4d6fa4bb0161f09251fc8068489aff/docker/c8021afbdc3a74d5862262d583276a65bb4d6fa4bb0161f09251fc8068489aff/system.slice/kubelet.service"
```

They're continuously repeated at the end of the log.

**Comment by neolit123** [comment]
not sure what might be causing that.

**Comment by bart0sh** [comment]
It also complains about absent certificates:
```
Feb 15 14:15:46 kind-control-plane kubelet[753]: F0215 14:15:46.518455     753 server.go:244] unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
...
Feb 15 14:15:56 kind-control-plane kubelet[773]: E0215 14:15:56.830121     773 certificate_manager.go:348] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post https://172.17.0.2:6443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: dial tcp 172.17.0.2:6443: connect: connection refused
```

**Comment by bart0sh** [comment]
I'm running it on a real hardware if it matters, no VM involved.

**Comment by pablochacin** [comment]
@bart0sh are you by any chance using a `btrfs` partition? I had some weird issues because the volumes that `kind`mounts are not updated properly in the docker-in-docker.

**Comment by padiazg** [comment]
Same here
* RedHat EL 7
* Docker version 18.09.0, build 4d60db4
* go version go1.11.5 linux/amd64

I'm in a restricted network, and need to specify proxy to reach the internet, can that be the problem?

How can I get some logs to figure out what's wrong, besides --loglevel?

**Comment by neolit123** [comment]
latest master branch contains a patch by @pablochacin that passes HTTP*_PROXY env variables to nodes:
https://github.com/kubernetes-sigs/kind/pull/275/files

**Comment by bart0sh** [comment]
I'm also behind the proxy. all proxy variables are set correctly, but kind refuses to create a cluster.

**Comment by bart0sh** [comment]
ah, the fix is not released yet.

**Comment by neolit123** [comment]
well if you build the binary from master it should be there.
`go get...` does that, no?

**Comment by BenTheElder** [comment]
`go get -u sigs.k8s.io/kind` will get the latest (note the u for update). The latest should have support for proxies.

**Comment by bart0sh** [comment]
just to be sure I've rebuilt it from master. It didn't help.

**Comment by bart0sh** [comment]
any suggestions how to debug it?

**Comment by BenTheElder** [comment]
`kind create cluster --retain` // don't delete the broken nodes
`kind export logs` // dump various debug logs

**Comment by BenTheElder** [comment]
> just to be sure I've rebuilt it from master. It didn't help

I'm pretty sure there are two different issues here. One is the proxy, which should be fixed at head (supports HTTP_PROXY and HTTPS_PROXY).

The other is not known yet. Have you checked https://kind.sigs.k8s.io/docs/user/known-issues/ ?

**Comment by bart0sh** [comment]
just checked it, thanks. Neither of those issues seem to be my case. ext4 partitions, plenty of disk space and memory,  no "failed to apply overlay network" message on the console, no "failed to build images" message either. See debug output above.

**Comment by BenTheElder** [comment]
The stats bit is expected and ignorable for now.
The certs bit is odd, I don't think I've seen that before. Sounds like kubeadm isn't populating a cert signed for the "node ip"... That shouldn't happen. It should be signed for that by default and we additionally add localhost 🤔

**Comment by BenTheElder** [comment]
I think we need to additionally set which addresses to NOT proxy

**Comment by BenTheElder** [comment]
Can you share `docker info` and your proxy envs?

**Comment by bart0sh** [comment]
sure:
```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.06.1-ce
Storage Driver: devicemapper
 Pool Name: docker-8:2-2098125-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 107.4GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 3.246GB
 Data Space Total: 107.4GB
 Data Space Available: 10.36GB
 Metadata Space Used: 2.617MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.145GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.03.01 (2015-05-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: oci runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: v0.1.3_catatonit (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.140-62-default
Operating System: openSUSE Leap 42.3
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.3GiB
Name: ed
ID: BT22:6TU5:LPMW:REOE:ALIL:3H4O:FU4E:6QWM:PNEY:KHW6:NNWL:COU5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://<internal proxy host>:<port>/
Username: bart0sh
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

$ set |grep -i proxy | cut -f1 -d=
GIT_PROXY_COMMAND
HTTPS_PROXY
HTTP_PROXY
NO_PROXY
SOCKS_PROXY
ftp_proxy
gopher_proxy
http_proxy
https_proxy
no_proxy
socks_proxy
```

I can't show internal IP and host names here, sorry. However, I'm pretty sure proxy settings are ok as I'm running kubeadm on this host almost on daily basis and it works just fine, e.g. I'm able to create master with it and debug kubeadm issues.

btw, I've upgraded docker. It didn't help to solve the issue.

**Comment by bart0sh** [comment]
Can cgroup driver cgroupfs be the reason of the issue?

**Comment by neolit123** [comment]
try setting `systemd` as the driver on the host.
but for the docker in the nodes this might need a patch in kind.

**Comment by bart0sh** [comment]
I've changed cgroup driver to system. It didn't help. I still see this in the kubelet log:
```
Feb 15 16:38:10 kind-control-plane kubelet[774]: E0215 16:38:10.367505     774 certificate_manager.go:348] Failed while requesting a signed certificate from the master: cannot cr
eate certificate signing request: Post https://172.17.0.2:6443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: dial tcp 172.17.0.2:6443: connect: connection refused
```

I'll try to add NO_PROXY to pkg/cluster/nodes/create.go the same way as HTTP_PROXY and HTTPS_PROXY.

**Comment by bart0sh** [comment]
that helped. I've patched kind as I explained above and added 172.17.0.0/16 to NO_PROXY:
```
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
kubectl cluster-info
[ed@ed kubernetes (master)]$ export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
[ed@ed kubernetes (master)]$ kubectl cluster-info
Kubernetes master is running at https://localhost:41576
KubeDNS is running at https://localhost:41576/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Comment by bart0sh** [comment]
let me know if you want me to send a patch. It's pretty trivial:
```
--- a/pkg/cluster/nodes/create.go
+++ b/pkg/cluster/nodes/create.go
@@ -141,6 +141,11 @@ func createNode(name, image, clusterLabel string, role config.NodeRole, extraArg
                runArgs = append(runArgs, "-e", "HTTPS_PROXY="+httpsProxy)
        }
 
+       noProxy := os.Getenv("NO_PROXY")
+       if noProxy != "" {
+               runArgs = append(runArgs, "-e", "NO_PROXY="+noProxy)
+       }
+
        // adds node specific args
        runArgs = append(runArgs, extraArgs...)
```

**Comment by BenTheElder** [comment]
Please do! 😀

**Comment by bart0sh** [comment]
@BenTheElder done. please, merge

**Comment by padiazg** [comment]
Just downloaded the last version as suggested, and now it works. Thanks a lot!!

```bash
[root@test-1nodo-custom ~]# kind create cluster --retain
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.13.3) 🖼
 ✓ [control-plane] Creating node container 📦
 ✓ [control-plane] Fixing mounts 🗻
 ✓ [control-plane] Starting systemd 🖥
 ✓ [control-plane] Waiting for docker to be ready 🐋
 ✓ [control-plane] Pre-loading images 🐋
 ✓ [control-plane] Creating the kubeadm config file ⛵
 ✓ [control-plane] Starting Kubernetes (this may take a minute) ☸
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
kubectl cluster-info
```

**Comment by bart0sh** [comment]
It's should probably be explained somewhere how to find the address/network to put into NO_PROXY. Is there better way then what I did?
```
docker exec -it kind-control-plane /bin/bash -c "journalctl -ukubelet |grep 'connection refused'"
```

**Comment by BenTheElder** [comment]
@bart0sh the docker network IPs should not be proxied, we can document a command to obtain these.

**Comment by BenTheElder** [comment]
Thanks all! Will update the docs and make sure this is highlighted in the next release.. (soon!)

**Comment by BenTheElder** [comment]
@bart0sh `docker network inspect bridge` will print out the subnet range, unfortunately it looks like no_proxy doesn't support subnets or wildcards for IPs...
all IPs in the subnet could be placed in no_proxy, but that's a bit unwieldy.

**Comment by bart0sh** [comment]
@BenTheElder I believe Docker supports ranges in NO_PROXY. see my [above comment](
https://github.com/kubernetes-sigs/kind/issues/306#issuecomment-464121144) for details.

**Comment by bart0sh** [comment]
@BenTheElder Another place where we need to configure proxy is a docker daemon. Otherwise it refuses to pull images. It couldn't pull weave-net image and weave-net pods were stuck in LoopBackOff state.

I briefly looked at the code yesterday and I think the way to do it is to generate systemd drop-in with proxy settings for docker service before docker starts on the node, somewhere in pkg/cluster/internal/create/createcontext.go I guess. Does this make sense?

**Comment by bart0sh** [comment]
@BenTheElder Here I how Docker docs suggest to configure proxy for docker daemon: https://docs.docker.com/config/daemon/systemd/#http-proxy

We should also consider setting both lower and upper case variables as some programs don't respect upper case *_PROXY vars.

**Comment by bart0sh** [comment]
@BenTheElder please, reopen this issue as we're still not done yet. See my comments above for further details.

**Comment by BenTheElder** [comment]
@bart0sh FYI with prow you can re-open with
/reopen
sorry, I just found this in my notification backlog...

**Comment by BenTheElder** [comment]
but actually the issue in this original issue should be fixed by everything necessary to boot a cluster now being in the image, I opened a new issue to track the lowercase envs

**Comment by lizrice** [comment]
I'm seeing this same error with an older node image kindest/node:v1.11.3. From exec'ing into the node I can see that Docker never started up (but I have not established why). The same kind code is working great with an up-to-date node image kindest/node:v1.14.1.

I know kind is a work in progress but it would be marvellous if it could aim to support the same previous 3 minor releases as Kubernetes itself. (We're using kind to test kube-bench, and it is super-useful!)

**Comment by BenTheElder** [comment]
Sorry about that, the code at kind HEAD changed image format to make some major improvements, we're releasing 0.3 this week with notes about that. We left any existing images in kindest/ untouched but published new images for the changes.

kind does support those Kubernetes versions but will require building new node images for them.

We have less support for 1.11 now though, as Kubernetes's CI doesn't support it, and we can't patch bugs in the 1.11 tests now that the Kubernetes 1.11 branch is closed after the last patch release.

**Comment by BenTheElder** [comment]
When 0.3 is out (soon!) I'll make sure we have up to date node images listed somewhere for the latest Kubernetes 1.11.10, 1.12.8, 1.13.6, 1.14.2, none of which are currently published kind images, along with some better docs about these 😅 

Just trying to finish landing podSubnet cleanup and NO_PROXY fixes.

**Comment by BenTheElder** [comment]
podsubnet fixes & general CNI updates are in, I think we may punt NO_PROXY depending on the timing of v1.14.2 which is apparently delayed from today to at least one more day to soak the go 1.12.5 upgrade.

tracking image upgrades here: https://github.com/kubernetes-sigs/kind/issues/531

**Comment by BenTheElder** [comment]
kind v0.3.0 is out with images for 1.11, 1.12, 1.13, and 1.14 at their latest patch versions
