### ISSUE TITLE
Kwok support for faster cluster setup?

### ISSUE THREAD

**Issue by mstrYoda** [kubernetes-sigs/kind#3060]
**What would you like to be added**: WDYT about using `kwok` in kind to improve provision time?

https://github.com/kubernetes-sigs/kwok

**Why is this needed**: Performance optimization.

**Comment by stmcginnis** [comment]
This seems counter to kinds goals. Can you explain a little more what you are trying to do?

**Comment by aojea** [comment]
Kwow simulates nodew, it looks similar to kubemark ...kind emulates kubernetes cluster, I can't understand the relationships

Anyway, thanks for your interest

/Close
