### ISSUE TITLE
kube-controller-manager and kube-scheduler can not connect to kube-apiserver

### ISSUE THREAD

**Issue by fm2022aa** [kubernetes-sigs/kind#3062]
<img width="1829" alt="image" src="https://user-images.githubusercontent.com/53565339/211964980-4df91cd8-33b9-4b66-afec-d082859f0203.png">

hi, I want know how can i debug this error?
Thanks

**Comment by fm2022aa** [comment]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/53565339/211965100-c7d5bad2-b89b-463a-90f7-28bab7323e49.png">

**Comment by devenes** [comment]
Can you fill in the information from issue template?

Environment:

- kind version: (use `kind version`):
- Runtime info: (use `docker info` or `podman info`):
- OS (e.g. from `/etc/os-release`):
- Kubernetes version: (use `kubectl version`):
- Any proxies or other special environment settings?:

This error can occur for a variety of reasons, such as network connectivity issues, misconfigured DNS settings, or incorrect Kubernetes configuration.

**Comment by BenTheElder** [comment]
We can't debug this without the rest of the info asked above. Closing due to lack of information and activity.
