### ISSUE TITLE
Using "kind load docker-image img1 img2 ..." results in the image being loaded onto the node multiple times

### ISSUE THREAD

**Issue by artnaseef** [kubernetes-sigs/kind#3063]
Running on a single-node Kind cluster.

Using "kind load docker-image img1 img2 ..." (where img1 and img2 are valid docker image names), the large, aggregate image created by "docker save" is uploaded to the single node multiple times - once per source image.

I tracked this down in the code and would offer a fix, but lack golang experience.  Google searching how to make a set in golang yielded no simple solution, so I decided to defer to more experienced hands here.

**What you expected to happen**:

The large image created by the "docker save" command should be loaded to the node only once, since it already contains ALL of the original docker images.

**How to reproduce it (as _minimally_ and precisely as possible)**:

"kind load docker-image img1 img2 img3"

**Anything else we need to know?**:

With almost no golang experience, managed to track this down to the following:

    Source File: pkg/cmd/kind/load/docker-image/docker-image.go

The following array is populated:

       selectedNodes := []nodes.Node{}
        fns := []func() error{}
        for i, imageName := range imageNames {
                imageID := imageIDs[i]
                for _, node := range candidateNodes {
                        id, err := nodeutils.ImageID(node, imageName)
                        if err != nil || id != imageID {
                                selectedNodes = append(selectedNodes, node)
                                logger.V(0).Infof("Image: %q with ID %q not yet present on node %q, loading...", imageName, imageID, node.String())
                        }
                }
                if len(selectedNodes) == 0 {
                        logger.V(0).Infof("Image: %q with ID %q found to be already present on all nodes.", imageName, imageID)
                        continue
                }
        }

Then iterated:

        // Load the images on the selected nodes
        for _, selectedNode := range selectedNodes {
                selectedNode := selectedNode // capture loop variable
                fns = append(fns, func() error {
                        return loadImage(imagesTarPath, selectedNode)
                })
        }

Notice there is no attempt to dedup the nodes, so the same selectedNode is processed once per image.

This can also be observed via the command "docker exec kind-control-plane ps axu | grep ctr" while the load is ongoing.

**Environment:**

- kind version: (use `kind version`):
kind v0.12.0 go1.13.8 linux/amd64

- Runtime info: (use `docker info` or `podman info`):
Docker Version 20.10.14
 
- OS (e.g. from `/etc/os-release`):
Ubuntu

- Kubernetes version: (use `kubectl version`):
1.23.4

- Any proxies or other special environment settings?:
no

**Comment by aojea** [comment]
what `docker save`image are you referring too?

kind gets the images passed as arguments and loads each of them one by one

**Comment by afbjorklund** [comment]
It seems like all images are save into a single tarball, so it only needs to be transferred (and loaded) once ?

https://github.com/kubernetes-sigs/kind/blob/main/pkg/cmd/kind/load/docker-image/docker-image.go#L209

**Comment by artnaseef** [comment]
Loading all the images at once is a huge win when there are common layers - as we often have with many 100's of MBs each.

Loading images one-at-a-time in our use-case gets about 700mb per image.  We've got a dozen images.  Loading them all at once, the tar file is about 1.2gb.  So loading them all at once is notably faster - when done manually via docker save and docker load.

**Comment by aojea** [comment]
> It seems like all images are saved into a single tarball, so it only needs to be transferred (and loaded) once ?

I stand corrected 😄  Thanks

**Comment by aojea** [comment]
@artnaseef it should be something like this
```diff
diff --git a/pkg/cmd/kind/load/docker-image/docker-image.go b/pkg/cmd/kind/load/docker-image/docker-image.go
index cfb94b97..173135d8 100644
--- a/pkg/cmd/kind/load/docker-image/docker-image.go
+++ b/pkg/cmd/kind/load/docker-image/docker-image.go
@@ -130,7 +130,7 @@ func runE(logger log.Logger, flags *flagpole, args []string) error {
        }
 
        // pick only the nodes that don't have the image
-       selectedNodes := []nodes.Node{}
+       selectedNodes := map[string]nodes.Node{}
        fns := []func() error{}
        for i, imageName := range imageNames {
                imageID := imageIDs[i]
@@ -147,7 +147,9 @@ func runE(logger log.Logger, flags *flagpole, args []string) error {
                                logger.V(0).Infof("Image with ID: %s already present on the node %s but is missing the tag %s. re-tagging...", imageID, node.String(), sanitizedImageName)
                                if err := nodeutils.ReTagImage(node, imageID, sanitizedImageName); err != nil {
                                        logger.Errorf("failed to re-tag image on the node %s due to an error %s. Will load it in
stead...", node.String(), err)
-                                       selectedNodes = append(selectedNodes, node)
+                                       if _, ok := selectedNodes[node.String()]; !ok {
+                                               selectedNodes[node.String()] = node
+                                       }
                                } else {
                                        processed = true
                                }
@@ -155,7 +157,9 @@ func runE(logger log.Logger, flags *flagpole, args []string) error {
                        }
                        id, err := nodeutils.ImageID(node, imageName)
                        if err != nil || id != imageID {
-                               selectedNodes = append(selectedNodes, node)
+                               if _, ok := selectedNodes[node.String()]; !ok {
+                                       selectedNodes[node.String()] = node
+                               }
                                logger.V(0).Infof("Image: %q with ID %q not yet present on node %q, loading...", imageName, imageID, node.String())
                        }
                        continue
```

why don't you try it ? 🥇

**Comment by artnaseef** [comment]
That works.   Note that removing the `if _...` statement and just running the `selectedNodes[node.String()] = node` works as well - probably better not to check-then-add, but it's minor.

**Comment by aojea** [comment]
I leave that to the person that sends the PR to fix it ;)

**Comment by artnaseef** [comment]
Interesting.  Not a response I expected.

Do you have someone in mind?

**Comment by aojea** [comment]
It is an open source project, anyone interested in contributing is welcome

**Comment by AnjaliMishra1st** [comment]
Hi! I’m interested in working on this issue as part of GSSoC. May I please be assigned?

**Comment by aojea** [comment]
you don't need to be assigned to send a PR :)

**Comment by AnjaliMishra1st** [comment]
Hi! I’d love to work on this as part of GSSoC. I’ll submit a PR soon :)
