### ISSUE TITLE
Add option to ignore existing cluster?

### ISSUE THREAD

**Issue by embano1** [kubernetes-sigs/kind#3077]
My current local workflow is:

```console
export KIND_CLUSTER_NAME=e2e
kind create cluster
<load images>
<do tests>
```

When writing (e2e) tests I often iterate over an existing cluster instead of delete/recreate.
If `KIND_CLUSTER_NAME` already exists, then any script calling `kind create cluster` again would fail.

Would it make sense to add a `create` option in the lines of `IgnoreAlreadyExists`?

https://github.com/kubernetes-sigs/kind/blob/f552543622786b863c586d734548d26dcbbe6761/pkg/cluster/internal/create/create.go#L174-L184

**Comment by BenTheElder** [comment]
`kind delete cluster` is idempotent for this sort of workflow / cleanup, so one answer is:
```console
export KIND_CLUSTER_NAME=e2e
kind delete cluster && kind create cluster
<load images>
<do tests>
```

**Comment by embano1** [comment]
Fine with me :) At least it's doc-ed now...
