### ISSUE TITLE
`kindest/node` container image for v1.26.1

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/kind#3080]
Hey folks, I'm waiting for the container image of v1.26.1 to unblock our CI in https://github.com/kubernetes-sigs/security-profiles-operator/pull/1414, because this version fixes a CRD generation bug (https://github.com/kubernetes/kubernetes/pull/114585). If you have a couple of cycles, do you mind pushing it to docker hub?

I assume this refers to https://github.com/kubernetes-sigs/kind/issues/197

**Comment by aojea** [comment]
@BenTheElder do we plan to cut some release soon or we can make this ad-hoc?

**Comment by tmc** [comment]
ping

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/3116#issuecomment-1456926416

**Comment by BenTheElder** [comment]
There's a 1.26.2 image from HEAD development now, we're going to wind up cutting a bug-fix release pretty soon, been a bit hands tied with https://kubernetes.io/blog/2023/03/10/image-registry-redirect/ / pushing hard with others in SIG k8s infra to get the Kubernetes project back within our budget of donated cloud resources before we have problems with that.
