### ISSUE TITLE
Review/Edit Wikipedia page

### ISSUE THREAD

**Issue by bryanSME** [kubernetes-sigs/kind#3082]
**What would you like to be documented**:
https://en.wikipedia.org/wiki/Draft:KinD

**Why is this needed**:
I created the initial page, but I'm not a community supporter.  Ideally, someone more familiar with KinD should check that the information on Wikipedia is correct.

**Comment by BenTheElder** [comment]
Thanks -- Looks like wikipedia declined the page. Understandable.

**Comment by bryanSME** [comment]
It's was declined because it's not complete which is why this ticket was opened in the first place.
