### ISSUE TITLE
Warning due to deprecated actions

### ISSUE THREAD

**Issue by devenes** [kubernetes-sigs/kind#3084]
**What happened**:

While I was testing kind with GitHub Actions I got warning that broke my pipeline. 

The GitHub Actions workflow gives the following deprecation warning while running the action:

> Docker (ipv6, singleNode) Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 

>  Docker (ipv4, singleNode) Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 

>  Docker (ipv6, multiNode) Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 

>  Docker (ipv4, multiNode) Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**What you expected to happen**:

When you update the actions to use Node.js 16 environments, you don't get any errors or warnings.

**How to reproduce it (as _minimally_ and precisely as possible)**:

To run the GitHub Actions workflow. 

**Anything else we need to know?**:

You can assign me to open a PR to fix the issue.

**Comment by BenTheElder** [comment]
thanks for the issue and fix! https://github.com/kubernetes-sigs/kind/pull/3085
