### ISSUE TITLE
Add a kind cloud-provider

### ISSUE THREAD

**Issue by danwinship** [kubernetes-sigs/kind#3086]
In [a thread in the discussion of KEP-3705](https://github.com/kubernetes/enhancements/pull/3706#discussion_r1064846292), the idea came up that kind could provide a dummy cloud provider, which could be used to test certain cloud-related behaviors in kind clusters.

In [an update to the KEP](https://github.com/kubernetes/enhancements/pull/3798/files#diff-d14f8e17caa4cec27696e2ff5eeb00802582ecbf73e9b70684049a733700b44eR418) I added:

```
@aojea suggests we _could_ use `kind` with an external cloud provider.
This would presumably have to be a bespoke dummy cloud provider, but
since we are only doing this to test the new `k/cloud-provider` code,
having a mostly-dummied-out cloud provider should not be a problem? It
could perhaps have a default `NodeAddresses` return value of
"<intentionally-wrong-IPv4-IP>, <correct-IPv6-IP>,
<intentionally-wrong-IPv6-IP>, <correct-IPv4-IP>", and then we could
pass `--node-ip <correct-IPv4-IP>,IPv6` to kubelet. If the cloud
provider did not receive and interpret the `--node-ip` value
correctly, then we would end up with node IPs that didn't work and the
test job should fail.
```

I am not certain how much work this would be, or how useful it would be for anything other than testing this one specific case...

cc @aojea @elmiko

**Comment by aojea** [comment]
heh, not as "implementing it in Kind", more as in "Antonio's hacks with kind"

https://gist.github.com/search?q=user%3Aaojea+kind

I would write it down and most probably hack a bash script, then we can use it in the CI as we did with multizone 

https://github.com/kubernetes/test-infra/blob/master/experiment/kind-multizone-e2e.sh

Let's keep this issue to track this, but just to be clear, this will not be a kind core feature

**Comment by elmiko** [comment]
i had also been curious about a proper ccm for docker, although the lightweight version sounds intriguing.

**Comment by aojea** [comment]
prototype working for LoadBalancers, Clusters and Instances

https://github.com/aojea/cloud-provider-kind/

**Comment by BenTheElder** [comment]
@aojea and I met about this today and we're going to request a new SIG Testing repo to do this in.

That way we can continue to keep the core kind module dependency set low for things like embedding in other test, CAPI tooling, but re-use packages from core KIND in the cloud provider implementation and import heavy packages like k8s.io/cloud-provider etc.

Request is here https://github.com/kubernetes/org/issues/4052

**Comment by BenTheElder** [comment]
We have a repo and an approach sketched out, but with Kubernetes code freeze and some other fun it'll probably be a little bit longer before we have this fully moving forward.

Sources will be developed at https://github.com/kubernetes-sigs/cloud-provider-kind/

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/cloud-provider-kind/
