### ISSUE TITLE
Add support for custom DNS resolver in Kind nodes

### ISSUE THREAD

**Issue by ChinmayaSharma-hue** [kubernetes-sigs/kind#3088]
**What would you like to be added**:
Support for custom DNS resolver in Kind nodes, allowing users to pass their own resolv.conf file to the Kind cluster, which will then override the default /etc/resolv.conf file in each node.

**Why is this needed**:
In some cases, the default DNS resolver provided by the host can cause issues. By adding support for custom DNS resolvers, users will have more flexibility and control in addressing these issues by using the DNS resolver of their choice.

**Comment by BenTheElder** [comment]
What situation is not addressed by updating DNS resolution on your host?

Which backend is this for? Docker or podman?

For docker, kind uses a docker custom network, docker networks other than the default bridge receive docker's embedded DNS feature, which causes dockerd to add a dns listener inside the "node" container which is then resolved in dockerd on the host, using the host's DNS settings.

Not using this feature would break kind, as this resolver also handles resolving container / node names.
