### ISSUE TITLE
Document using rootfull podman machine for Kind

### ISSUE THREAD

**Issue by jspaleta** [kubernetes-sigs/kind#3092]
**What would you like to be documented**:
I would like to see documentation specifically for using podman machine on Linux systems to implement rootful Kind using podman.

**Why is this needed**:
Using Kind with Cilium enabled cluster for local development/testing is much easier/safer using a podman machine VM then using rootful podman on the host linux system. 

There's a small gotcha with podman machine running on linux.  Currently Kind will use the `podman` executable not the `podman-remote` executable when the podman experimental plugin is enabled and as a result will not use the podman VM machine.  The `podman` executable isn't remote connection aware. 

This is a divergence with behavior as seem on macOS installs of `podman` where `podman` executable is actually provided a symlink to `podman-remote` as the host is not a linux kernel and cannot use the `podman` executable.

The documentation solution is to provide a note for Linux podman users indicating they need to symlink `podman-remote` as `podman` into their executable path so Kind will actually use `podman-remote` for its internal operations, similar to what you would experience on macOS.

**Comment by BenTheElder** [comment]
> I would like to see documentation specifically for using podman machine on Linux systems to implement rootful Kind using podman.

This works currently without doing anything special but it's experimental, podman has not been a stable enough target.

> Using Kind with Cilium enabled cluster for local development/testing is much easier/safer using a podman machine VM then using rootful podman on the host linux system.

Remote podman is #2233, and won't be documented before it is supported.

**Comment by BenTheElder** [comment]
I think remote podman tracking should fully fall under https://github.com/kubernetes-sigs/kind/issues/2233, but the information about the two binaries is helpful.
