### ISSUE TITLE
Elastic Cloud in Kubernetes (ECK) in Kind

### ISSUE THREAD

**Issue by jeffreywstevens** [kubernetes-sigs/kind#3095]
I have this running in an on premise Kubernetes cluster. This same configuration works there.  I wanted to explore other things in Kind without disrupting the on premises cluster.

In Kind, the Elasticsearch cluster works great. The Kibana runs fine. However, it wont connect to the Elastic cluster in the same namespace.

The log entry is below. It seems to be a DNS or network-addressing problem for this particular pod.  Is there an easy fix for this?

[ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. socket hang up - Local: 10.244.3.11:36082, Remote: 10.96.21.199:9200

**Comment by BenTheElder** [comment]
I don't think we have enough to go on here and ECK is a bit out of scope for us.

Those look like application specific endpoints.

**Comment by jeffreywstevens** [comment]
Can you help me understand the real scope of Kind, so I don't have any unreasonable expectations? 

So far, It has been so much better than the other local options IMHO. Especially building a multi-node cluster.

I have had success proving apps within Kind to prove out specific ones for use in our K8s cluster. Helm has been great too.
For instance:
- Prometheus and Grafana.  
  - Grafana worked great out of the box
  - However, the default data source, pre-configured for Prometheus, didn't work. I added another one with a different DNS address, and it worked.
- RabbitMQ
  -  It has an excellent operator that works well.  This one was solid.
- Redis Cluster - I don't recall any problem here.

With some, I had tweaks for the real cluster, which are usually storage related.

So for Elastic, I had high hopes. Elasticsearch itself works great in KinD.  It was still a great learning experience.

**Comment by aojea** [comment]
> So for Elastic, I had high hopes. Elasticsearch itself works great in KinD. It was still a great learning experience.

This seems an environment problem and not a kind problem, we don't have bandwidth to troubleshoot all these setups, if you find the problem and turns out it is a Kind issue, we are happy to review patches ... but with the little information provided is impossible to help more

**Comment by jeffreywstevens** [comment]
Understood.
