### ISSUE TITLE
Add DNS search configuration

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kind#3097]
**What would you like to be added**:

Configuration to override the dns search in /etc/resolv.conf of nodes

**Why is this needed**:

Docker inherits resolv.conf of the host, which may have absurd number of search rules due to corporate policies, etc. These end up in all pods, making DNS latency quite high.

On my machine, a curl request takes 100ms because of this. Without search, its 10ms. This makes our tests nearly 10x slower.

https://kubernetes.slack.com/archives/CEKK1KTN2/p1676407003927219 has a bit more details and implementation ideas.

**Comment by aojea** [comment]
for ref https://docs.docker.com/config/containers/container-networking/#dns-services

```
--dns-search
```
