### ISSUE TITLE
Setting memory limit causes OOM

### ISSUE THREAD

**Issue by lujiajing1126** [kubernetes-sigs/kind#3100]
**What happened**:

When `resources.limits.memory` is set, the pod cannot start with OOM(s)

![image](https://user-images.githubusercontent.com/2568208/219324441-c7d42d7e-5db1-4726-bf4a-ae92e682ab07.png)

![image](https://user-images.githubusercontent.com/2568208/219325643-2777f526-9b61-4577-b650-b07d68f19f22.png)

But if I removed memory limit, everything is fine.

**What you expected to happen**:

No OOM.

**How to reproduce it (as _minimally_ and precisely as possible)**:

**Anything else we need to know?**:

Run `dmesg` on work-node,

![image](https://user-images.githubusercontent.com/2568208/219325145-8bfd5013-86c8-4f93-8a83-8d7df4f626af.png)

**Environment:**

- kind version: (use `kind version`): `kind v0.17.0 go1.19.3 darwin/arm64`
- Runtime info: (use `docker info` or `podman info`):

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 15.61GiB
 Name: docker-desktop
 ID: 4HIG:W5AM:PXCS:XYZF:WWKS:KHVK:Q5O5:NHOR:3X2E:SGSE:PUOE:ON7K
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

- OS (e.g. from `/etc/os-release`): macOS Ventura 13.2.1 (22D68)
- Kubernetes version: (use `kubectl version`): `kindest/node:v1.20.15@sha256:a32bf55309294120616886b5338f95dd98a2f7231519c7dedcec32ba29699394`
- Any proxies or other special environment settings?:

**Comment by aojea** [comment]
that is the expected behavior , isn't it?

https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/

**Comment by lujiajing1126** [comment]
> that is the expected behavior , isn't it?
> 
> https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/

Oh. I made a mistake between `m` and `Mi`.

**Comment by BenTheElder** [comment]
hopefully the next person will find your example, I've made this mistake before :-)
