### ISSUE TITLE
Mac M1 kind 0.17.0 cannot start control plane on Colima 0.5.2 using  kindest/node:v1.25.3 or v.1.26.0 - 

### ISSUE THREAD

**Issue by jmjava** [kubernetes-sigs/kind#3104]
Updated **Environment**: 

**kind version:**  kind v0.17.0 go1.19.2 darwin/arm64
**Runtime info:** 
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.1)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)
**OS**
ProductName:    macOS
ProductVersion: 12.3.1
BuildVersion:   21E258
**Kubernetes version:**
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.25.3 

**Any proxies or other special environment settings?:**
we are using Zscaler and I had to load the kind image locally into docker

**Colima Info**

colima version 0.5.2
git commit: 6b5b6fe0540e708f0c9d6e8919fab292c671fc72

runtime: docker
arch: x86_64
client: v20.10.14
server: v20.10.18

I get the following stack trace:

[certs] etcd/peer serving cert is signed for DNS names [kind-control-plane localhost] and IPs [172.20.0.2 127.0.0.1 ::1]
Stack Trace: 
sigs.k8s.io/kind/pkg/errors.WithStack
        sigs.k8s.io/kind/pkg/errors/errors.go:59
sigs.k8s.io/kind/pkg/exec.(*LocalCmd).Run
        sigs.k8s.io/kind/pkg/exec/local.go:124
sigs.k8s.io/kind/pkg/cluster/internal/providers/docker.(*nodeCmd).Run
        sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/node.go:146
sigs.k8s.io/kind/pkg/exec.CombinedOutputLines
        sigs.k8s.io/kind/pkg/exec/helpers.go:67
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/kubeadminit.(*action).Execute
        sigs.k8s.io/kind/pkg/cluster/internal/create/actions/kubeadminit/init.go:81
sigs.k8s.io/kind/pkg/cluster/internal/create.Cluster
        sigs.k8s.io/kind/pkg/cluster/internal/create/create.go:135
sigs.k8s.io/kind/pkg/cluster.(*Provider).Create
        sigs.k8s.io/kind/pkg/cluster/provider.go:182
sigs.k8s.io/kind/pkg/cmd/kind/create/cluster.runE
        sigs.k8s.io/kind/pkg/cmd/kind/create/cluster/createcluster.go:111
sigs.k8s.io/kind/pkg/cmd/kind/create/cluster.NewCommand.func1
        sigs.k8s.io/kind/pkg/cmd/kind/create/cluster/createcluster.go:55
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.4.0/command.go:902
sigs.k8s.io/kind/cmd/kind/app.Run
        sigs.k8s.io/kind/cmd/kind/app/main.go:53
sigs.k8s.io/kind/cmd/kind/app.Main
        sigs.k8s.io/kind/cmd/kind/app/main.go:35
main.main
        sigs.k8s.io/kind/main.go:25
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_arm64.s:1172

**Comment by stmcginnis** [comment]
Can you fill in the information from issue template?

**Environment:**

- kind version: (use `kind version`):
- Runtime info: (use `docker info` or `podman info`):
- OS (e.g. from `/etc/os-release`):
- Kubernetes version: (use `kubectl version`):
- Any proxies or other special environment settings?:

Some of that you have included, but the actual output from the requested commands can contain a lot of useful information.

**Comment by BenTheElder** [comment]
This does not have enough information to diagnose the root cause.

**Comment by jmjava** [comment]
This was determined to be a Zcaler issue on our end
