### ISSUE TITLE
🚨 Docker is sunsetting Free Team Organizations 🚨

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#3124]
Just got the notice, we have Until April 14th to resolve this. Currently we depend on the `kindest/` organization.

https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf

AIUI the Kubernetes project previously decline to join the OSS program and it wasn't clear that KIND could agree to it on our own.

However other CNCF projects are members ref: https://twitter.com/justincormack/status/1635704358355468307

While we could move off of dockerhub, that has additional implications:
- Users are already depending on these images in pipelines all over the place, if we just mirror / migrate they won't have much time to switch
- dockerd still only supports mirroring dockerhub (https://github.com/moby/moby/issues/18818), so it will be somewhat harder for users without access to our upstream (e.g. china https://github.com/kubernetes/registry.k8s.io/issues/137) to switch to a mirror as we've previously discussed with @tao12345666333 ref: #1895 

- We do have a staging k8s infra GCR project available and could begin copying images over and promoting to registry.k8s.io, **however registry.k8s.io does not support mutable tags and we'd have to finally fix our tagging scheme** to not be based on Kubernetes versions only, which we'd still been discussing https://github.com/kubernetes-sigs/kind/issues/197, #2618 ...

**Comment by BenTheElder** [comment]
I think we need to revisit https://github.com/kubernetes-sigs/kind/issues/1895#issuecomment-833111925 / https://www.docker.com/community/open-source/application/

**Comment by BenTheElder** [comment]
Per above tweet:
> We won't be deleting projects applying to this

[the open source application]

The current terms of agreement are _very_ simple https://web.docker.com/rs/790-SSB-375/images/DockerOpenSourceProgramTermsofAgreement.pdf

> • Program benefits are provided only to project leads and core project committers.
> • Program status and benefits are valid for one year and can be renewed if your project
> still meets the program requirements.
> • You may use the program benefits solely for developing non-commercial open-source
> projects.
> • You may not share free licenses with any third parties.

None of that seems like a problem. I think we should apply now and consider migrating to registry.k8s.io with a new tagging scheme as a next step for later this year when we have less on our plate and less immediate need to prevent user breakage.

**Comment by BenTheElder** [comment]
<img width="321" alt="Screenshot 2023-03-14 at 2 14 46 PM" src="https://user-images.githubusercontent.com/917931/225137913-ca534fcd-5997-4014-959e-6e4db6b270f5.png">

I think these are reasonably accurate. We obviously already agree to the docker TOS so only the additional conditions above.

**Comment by BenTheElder** [comment]
OK, I've submitted the form so we have a start on mitigating this anyhow, but we'll need to discuss more soon.

Back to Kubernetes Code Freeze / working on the k8s.gcr.io redirect planning for Kubernetes' own registry cost concerns :-)
(https://kubernetes.io/blog/2023/03/10/image-registry-redirect/))

**Comment by BenTheElder** [comment]
Using https://github.com/kubernetes-sigs/kind/issues/1895#issuecomment-1468991168 to track how we might start shipping images on another registry

**Comment by Vad1mo** [comment]
Hi, run a CNCF Harbor based [container registry service](https://container-registry.com/), happy to help the project and offer a registry free of charge. Harbor has the valuable option that allows you to replicate images to other registries. so you could have it centrally but backup and replicate automatically to ghcr, hcr Docker Hub and so on.

**Comment by BenTheElder** [comment]
Thanks @Vad1mo. Kubernetes has a registry too and we're discussing moving to it in https://github.com/kubernetes-sigs/kind/issues/1895#issuecomment-1468991168 but also tracking the dockerhub issue here as I'm concerned about users pulling existing images.

-----
Update re: dockerhub OSS program
![D2BF46E6-1DEC-4C12-8C7A-4376D23CEBDA](https://user-images.githubusercontent.com/917931/225344220-abf384d3-81aa-4f93-b710-970db331b9bd.png)

**Comment by boeboe** [comment]
https://github.com/kubernetes/minikube/issues/16053

Metallb addon for minikube is broken due to this sudden move from docker.io.

**Comment by medyagh** [comment]
> * dockerd still only supports mirroring dockerhub ([Enable engine to mirror private registry moby/moby#18818](https://github.com/moby/moby/issues/18818)), so it will be somewhat harder for users without access to our upstream (e.g. china [china can not pull from registry.k8s.io kubernetes/registry.k8s.io#137](https://github.com/kubernetes/registry.k8s.io/issues/137)) to switch to a mirror as we've previously discussed with @tao12345666333 ref: [Move dockerhub kindest/node to a non rate limited registry #1895](https://github.com/kubernetes-sigs/kind/issues/1895)

@BenTheElder  thats a really good point minikube uses GCR images by default and uses docker hub images as fail over,, large part of minikube users in china rely on docker hub as a fail over but we also have a alibaba sync job that pushes the images to alibaba
https://github.com/kubernetes/minikube/blob/master/.github/workflows/sync-minikube.yml

**Comment by BenTheElder** [comment]
@medyagh thanks! see also https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/ phew.

I think we still want to look at migrating to project controlled hosting finally, but it may be less urgent. Still need to reread this new announcement in depth.

**Comment by BenTheElder** [comment]
Leaving this open until I get to ensuring we have the descriptions / links up to date as requested.

We'll use another issue to track any further changes we want to make e.g. migrating to Kubernetes's registry long-term.

**Comment by BenTheElder** [comment]
We had most of this already from previously preparing for the OSS program.

I've gone back through every image in `kindest/` and added more details, links to the contributor guide, and updated any existing details. I think we have everything requested now and we appear to already have the "Sponsored OSS" badge.
