### ISSUE TITLE
Not able to acess the application running inside kind cluster

### ISSUE THREAD

**Issue by rabindragogoi** [kubernetes-sigs/kind#3127]
I have an applcation with the below deployment file:
`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-deployment
  template:
    metadata:
      labels:
        app: flask-app-deployment
    spec:
      containers:
      - name: test-app
        image: localhost:5001/learn:01
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8399
`

2. Created a service .
 `
  kubectl expose deployment flask-app-deployment --type=NodePort --name=my-service
`
But I am not able to access my application. While I do kubectl get deployments and get services, it shows everything is fine.

The only way I am able to run the application i when I run separately port forwarding. command.
`
kubectl port-forward flask-app-deployment-74b5c95c56-rj5mf 8399:8399
`
How can I run the application without port forwarding and put whatever needed in service.yaml file?
Please help.

**Comment by BenTheElder** [comment]
what platform are you on?

on mac/windows you'll have to use _some_ form of port forwarding. you can do https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings + a node port, see e.g. https://kind.sigs.k8s.io/docs/user/ingress/

on linux you can typically use the node container IPs and access the nodeports at $container_ip:$port

is there a reason kubectl port-forward is insufficient? it's a pretty simple and portable option.

**Comment by rabindragogoi** [comment]
Hey @BenTheElder : Thanks for the suggestion. I am able to access my application without port forwarding separately in a command.

Would like to know that the same process will work for load balancer as well?

**Comment by rabindragogoi** [comment]
closing the issue Thanks

**Comment by BenTheElder** [comment]
LoadBalancer API doesn't really map well to pre-defined forwards of specific ports https://kind.sigs.k8s.io/docs/user/loadbalancer/

We're working on something else in #3086 

In the meantime this approach does work https://kind.sigs.k8s.io/docs/user/ingress/
