### ISSUE TITLE
Node image - Docker archives... or not?

### ISSUE THREAD

**Issue by vx-github** [kubernetes-sigs/kind#3130]
I noticed a kind cluster can be run without internet access (at least if you pulled the node images before going offline). I found this page describes why this works: https://kind.sigs.k8s.io/docs/design/node-image, but the info seems old (as noted on the page). 

Can anyone explain (or document :wink: ) what the current implementation  is?

**Comment by BenTheElder** [comment]
Regarding offline specifically: https://kind.sigs.k8s.io/docs/user/working-offline/, which covers why a bit.
