### ISSUE TITLE
Can i start a kind cluster with ssh node

### ISSUE THREAD

**Issue by Kyofin** [kubernetes-sigs/kind#3133]
I start a kind cluster with 3 nodes on macbook. How to use ssh  client tool  to  conncet the node of cluster.

**Comment by stmcginnis** [comment]
The kind nodes are not virtual machines running a full OS stack, so there isn't an SSH server running for you to connect to.

Typically if you wanted to connect and interact with the node directly you would use `docker exec` to get a bash prompt in the running container. So something like:

```
$ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS          PORTS                       NAMES
d87fbc47be0e   kindest/node:v1.25.3   "/usr/local/bin/entr…"   31 seconds ago   Up 27 seconds   127.0.0.1:36197->6443/tcp   kind-control-plane

$ docker exec -it d87fbc47be0e bash
root@kind-control-plane:/#
```

**Comment by kanva001** [comment]
You can use kubectl exec command to ssh into the pod and run your commands inside your pod

$ kubectl get pods -o wide

NAME     READY   STATUS    RESTARTS   AGE     IP           NODE          NOMINATED NODE   READINESS GATES
my-pod   1/1     Running   0          8m41s   <**IP**>   kind-worker   <none>           <none>

$ k exec -it my-pod bash

kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@my-pod:/# curl <**IP**>
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

Hope this helps.
If you find issues, please comment and will check.
