### ISSUE TITLE
node service restarts

### ISSUE THREAD

**Issue by mythi** [kubernetes-sigs/kind#3135]
In confidential containers project we use an operator / pods to configure custom `RuntimeClass`es and we'd like to use `kind` for testing some of this. The problem is we need to issue `systemctl restart containerd` from pods to get the new runtime handler configs in effect. 

`kind` node images do not run `dbus` so this won't currently work and `systemctl` is failing.Any suggestions how this could work or any changes to get `dbus` added to the node images?

**Comment by aojea** [comment]
we try to avoid hard to get dependencies on the images, so we install the minimum necessary to have kind running.

There are other projects, per example Crio, that like to use kind and require to modify the images too..

We keep the building image workflow simple so people can create and maintain their own images, see the CRIO example here https://gist.github.com/aojea/bd1fb766302779b77b8f68fa0a81c0f2

**Comment by mythi** [comment]
@aojea thanks for the tip, following the idea, I came up with:

```
ARG IMAGE=kindest/node
ARG VERSION=1.26
ARG MINOR=0

FROM ${IMAGE}:v${VERSION}.${MINOR}

RUN echo "Installing Packages ..." \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends dbus \
    && systemctl enable dbus
```

which works for me. The unfortunate part is that I will have to maintain this little modification myself :/

**Comment by aojea** [comment]
> which works for me. The unfortunate part is that I will have to maintain this little modification myself :/

there has to be always someone to maintain things ... if you add it here you make me and Ben to have to maintain it for just only one user 🙃

**Comment by mythi** [comment]
> > which works for me. The unfortunate part is that I will have to maintain this little modification myself :/
> 
> there has to be always someone to maintain things ... if you add it here you make me and Ben to have to maintain it for just only one user upside_down_face

I understand. I'm OK with this custom image for know. If others are looking to have `systemctl` support we know what to do here. :-)

**Comment by aojea** [comment]
> If others are looking to have `systemctl` support we know what to do here. :-)

thanks, appreciate it

**Comment by BenTheElder** [comment]
I would try the [hostExec pod approach](https://github.com/kubernetes/kubernetes/blob/c3e7eca7fd38454200819b60e58144d5727f1bbc/test/e2e/storage/utils/host_exec.go#L49) or else just use `docker exec` from a test running out on the host. docker exec systemctl restart definitely works as we use it internally

but this is also an *internal* detail and nothing stops kind from switching distros or any other node level tool in the future*


*some of these would be very painful and we would not take the decision lightly

**Comment by BenTheElder** [comment]
> The problem is we need to issue systemctl restart containerd from pods to get the new runtime handler configs in effect.

Can you pre-configure the runtime handlers instead? I would expect something like this to be installed by the cluster "distro" and you can set containerd config in kind w/o having to do any of these hacks, it's just not well documented yet, see the kind config here https://kind.sigs.k8s.io/docs/user/local-registry/#create-a-cluster-and-registry

**Comment by mythi** [comment]
@BenTheElder thanks a lot for the follow-up! 

> I would try the [hostExec pod approach](https://github.com/kubernetes/kubernetes/blob/c3e7eca7fd38454200819b60e58144d5727f1bbc/test/e2e/storage/utils/host_exec.go#L49)

This looks a bit extreme :-) I was able to find an alternative which helps with dbus-less setup: using `hostPID: true` I can run `SYSTEMD_IGNORE_CHROOT=1 systemctl` that seems to work.

> Can you pre-configure the runtime handlers instead? 

Currently no, but this is something I need to think about for the future. Currently we have an operator that deploys a pod that installs a custom runtimehandler and it's components to the host.

**Comment by BenTheElder** [comment]
> This looks a bit extreme :-) I was able to find an alternative which helps with dbus-less setup: using hostPID: true I can run SYSTEMD_IGNORE_CHROOT=1 systemctl that seems to work.

this is a subset of the same idea as the linked testing approach -- it's possible to use a pod to effect executing on the host. that tooling is more generally replacing tests that needed to ssh.

> Currently no, but this is something I need to think about for the future. Currently we have an operator that deploys a pod that installs a custom runtimehandler and it's components to the host.


FWIW I think this is a good option to have for distros to smoothly preconfigure the runtime without the operator.
