### ISSUE TITLE
Need help in understanding the flow : Container is accessible through localhost instead of the Nodeport

### ISSUE THREAD

**Issue by rabindragogoi** [kubernetes-sigs/kind#3140]
Hi @BenTheElder and Team,

I am stuck in a usecase here where I need some help. Below is the scenario: 

   I set up a two worker kubernetes cluster where I deployed an application running on port 8399 and it just output a message as "Checking in kubernetes"

Here the issue I am facing is:
 I am able to access the url as http://localhost:8399 but not able to access the application with nodeIP as http://172.18.3.2:30950
where 30950 is the port that has been configured in service.

**_Can you please let me know what do I need to add as a part of settings_**

**Below is the terminal output.**

 2023-03-28 12:24:05 ⌚  Rabindras-MacBook-Pro in ~/Documents/Kubernetes/python_application/k8config
○ → kubectl get nodes -o wide
NAME                      STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION     CONTAINER-RUNTIME
k8cluster-control-plane   Ready    control-plane   35m   v1.24.0   172.18.0.4    <none>        Ubuntu 21.10   5.15.49-linuxkit   containerd://1.6.4
k8cluster-worker          Ready    <none>          35m   v1.24.0   172.18.0.3    <none>        Ubuntu 21.10   5.15.49-linuxkit   containerd://1.6.4
k8cluster-worker2         Ready    <none>          35m   v1.24.0   172.18.0.2    <none>        Ubuntu 21.10   5.15.49-linuxkit   containerd://1.6.4

 2023-03-28 12:24:11 ⌚  Rabindras-MacBook-Pro in ~/Documents/Kubernetes/python_application/k8config
○ → curl http://172.18.0.4:30950
^C

 2023-03-28 12:25:16 ⌚  Rabindras-MacBook-Pro in ~/Documents/Kubernetes/python_application/k8config
○ → curl http://localhost:8399
Checking in kubernetes
 2023-03-28 12:25:31 ⌚  Rabindras-MacBook-Pro in ~/Documents/Kubernetes/python_application/k8config
○ →

**My Deployment file:**

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app-deployment
  template:
    metadata:
      labels:
        app: flask-app-deployment
    spec:
      containers:
      - name: test-app
        image: localhost:5001/learn:01
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8399
          hostPort: 8399

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app-deployment
  ports:
  - name: 'http'
    targetPort: 8399
    port: 8399
    nodePort: 30950
  type: NodePort

**My Cluster File:**

#!/bin/sh
set -o errexit

# create registry container unless it already exists
reg_name='kind-registry'
reg_port='5001'
if [ "$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)" != 'true' ]; then
  docker run \
    -d --restart=always -p "127.0.0.1:${reg_port}:5000" --name "${reg_name}" \
    registry:2
fi

# create a cluster with the local registry enabled in containerd
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30950
    hostPort: 8399
- role: worker
- role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
    endpoint = ["http://${reg_name}:5000"]
EOF

# connect the registry to the cluster network if not already connected
if [ "$(docker inspect -f='{{json .NetworkSettings.Networks.kind}}' "${reg_name}")" = 'null' ]; then
  docker network connect "kind" "${reg_name}"
fi

# Document the local registry
# https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/generic/1755-communicating-a-local-registry
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    host: "localhost:${reg_port}"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
EOF

**Comment by BenTheElder** [comment]
> I am able to access the url as http://localhost:8399/ but not able to access the application with nodeIP as http://172.18.3.2:30950/

It appears you're on macOS, likely using docker desktop.

This is a limitation of docker desktop, only port forwards are available from the host, not container IPs.

https://kind.sigs.k8s.io/docs/user/loadbalancer/ has a note about this and https://kind.sigs.k8s.io/docs/user/ingress/ has a portable approach similar to what the local registry does
