### ISSUE TITLE
kubctl can't conncet to kind cluster with wsl2

### ISSUE THREAD

**Issue by misaya98** [kubernetes-sigs/kind#3165]
```misaya@LAPTOP-HENQBOIG:~$ kind create cluster 
Creating cluster "kind" ... 
 ✓ Ensuring node image (kindest/node:v1.26.3) 🖼 
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Thanks for using kind! 😊
misaya@LAPTOP-HENQBOIG:~$ kubectl cluster-info --context kind-kind
E0412 21:33:51.727333    3504 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:42909/api?timeout=32s": dial tcp 127.0.0.1:42909: connect: connection refused
```

**Environment:**
wsl2 ubuntu20.04
wsl version 1.2.0.0

- kind version: (use `kind version`):   kind version 0.18.0

- Runtime info: (use `docker info` or `podman info`): Docker version 20.10.24, build 297e128
  
- OS (e.g. from `/etc/os-release`): ubuntu20.04.4 LTS
- Kubernetes version: (use `kubectl version`): Client Version: v1.26.3  Kustomize Version: v4.5.7
- Any proxies or other special environment settings?: no

**Comment by aojea** [comment]
> dial tcp 127.0.0.1:42909: connect: connection refused

the forwarding is not working there

**Comment by igordcard** [comment]
Starting to look like WSL2 v1.2.0.0 brought the issue back - facing the same here after the update.

**Comment by misaya98** [comment]
> 
yes , it was caused by wsl part

**Comment by misaya98** [comment]
> @misaya98 can you check if this is the same known issue with WSL reported here ? [#3094 (comment)](https://github.com/kubernetes-sigs/kind/issues/3094#issuecomment-1430229097)

yes , it was caused by wsl part

**Comment by aojea** [comment]
> > @misaya98 can you check if this is the same known issue with WSL reported here ? [#3094 (comment)](https://github.com/kubernetes-sigs/kind/issues/3094#issuecomment-1430229097)
> 
> yes , it was caused by wsl part

/close

Thanks

**Comment by asheeshv** [comment]
I'm facing the same issue with wsl version 1.2 and the latest kind version. I know folks have mentioned that reverting to v1.0.3 of wsl fixes the issue for them. Are there clearly defined steps in order to revert to the wsl version?

**Comment by BenTheElder** [comment]
Sorry, Currently we only have WSL2 documented by user contribution: https://kind.sigs.k8s.io/docs/user/using-wsl2/
We don't use this and there's no windows CI #1529

**Comment by asheeshv** [comment]
Thanks for the response Ben. I'll take a look and determine the way to lower the wsl2 version. I know for sure KIND has worked fine for me on my windows setup using docker-desktop.

**Comment by igordcard** [comment]
For those who come across this issue as of today, run the following on an admin shell:
`wsl --update --pre-release`

WSL2 v1.2.3/1.2.4 (pre-release) have the issue above fixed.

**Comment by zapho** [comment]
@BenTheElder thanks for looking into this.

Unfortunately I cannot run `wsl --update --pre-release` as it leads to an error (To install this application you need either a Windows developer license or a sideloading-enabled system. Error code: Wsl/UpdatePackage/0x80073cff).

I will try to fix this and, if I can't, I'll wait for the next WSL release version.

I'll update the issue as soon as I can.
