### ISSUE TITLE
Explicitly call out avoiding use Gateway IP of the docker network when deal with the MetalLB

### ISSUE THREAD

**Issue by MengjiaLiang** [kubernetes-sigs/kind#3167]
Hi,
When I was setting up our CI system using Kind and configuring our Ingress with the LB support by MetalLB, I followed the instruction in https://kind.sigs.k8s.io/docs/user/loadbalancer/, but the LB type of service for the ingress controller is not connectable.

I spend plenty of time on figure out issue as I am not an expert in networking :(
I find other engineers also have such an issue in my organization, so I think this could be called out in the Kind documents for people(who is not network expert) to avoid it.

**What would you like to be documented**:
In https://kind.sigs.k8s.io/docs/user/loadbalancer/#setup-address-pool-used-by-loadbalancers, it mentiones
```
The output will contain a cidr such as 172.19.0.0/16. We want our loadbalancer IP range to come from this subclass. We can configure MetalLB, for instance, to use 172.19.255.200 to 172.19.255.250 by creating the IPAddressPool and the related L2Advertisement.
```
Actually this is not 100% accurate, because if the network is like
```
"IPAM": {
      "Driver": "default",
      "Options": {},
      "Config": [
        {
          "Subnet": "172.18.0.0/16",
          "Gateway": "172.18.0.1"
        },
        {
          "Subnet": "fc00:f853:ccd:e793::/64"
        }
      ]
}
```
We need to configure the IPAddressPool to avoid using the Gateway IP  `172.18.0.1`.
If the LB type of service takes `172.18.0.1`, that service will not be connected with.

**Why is this needed**:
This can save plenty of time to root cause and figure out the issue.

Thank you! I hope this tiny suggestion makes sense to you!

**Comment by aojea** [comment]
we'll have a better integration with loadbalancer soon with https://github.com/kubernetes-sigs/cloud-provider-kind

**Comment by MengjiaLiang** [comment]
Thank you @aojea for sharing this news!
Closing it now.
