### ISSUE TITLE
WSL2 1.2.0.0 and 1.2.5.0 do not work, 1.2.4.0 does

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#3180]
This issue is transient enough that I'm not sure if it warrants a permanent https://kind.sigs.k8s.io/docs/user/known-issues/ entry.

In the meantime I think pinning an issue will have better visibility.

TLDR: ~If you're using WSL2 and having issues, try updating to the latest pre-release `wsl --update --pre-release` as described here: https://github.com/kubernetes-sigs/kind/issues/3165#issuecomment-1513665114~

**EDIT**: See below for a better procedure to switch to 1.2.4.0 which is known-good https://github.com/kubernetes-sigs/kind/issues/3180#issuecomment-1551906924

There's an issue with the WSL2 `1.2.0.0` Kernel that is fixed in `1.2.4.0`. You can check `wsl --version`.

Past context: 
- https://github.com/kubernetes-sigs/kind/issues/3165
- https://github.com/kubernetes-sigs/kind/issues/3174

**Comment by gbg-sany** [comment]
Want to add that _1.2.5.0_ (the latest at the time of writing) not working.
command `wsl.exe --update --pre-release` will likely get you to version _1.2.5.0_ at the moment.
instead this worked for me: https://github.com/microsoft/WSL/issues/9508#issuecomment-1396866615
Basically run three commands on powershell, first two commands remove current wsl. The third command install the specific wsl (the post using _1.0.3.0_ but we can use _1.2.4.0_) version from current directory.
To get the _1.2.4.0_ version wsl go to: https://github.com/microsoft/WSL/releases/tag/1.2.4 or [download](https://github.com/microsoft/WSL/releases/download/1.2.4/Microsoft.WSL_1.2.4.0_x64_ARM64.msixbundle)

**Comment by BenTheElder** [comment]
Thanks! I've added a note to the original comment above to point to yours for how to update to 1.2.4.0 😅

**Comment by y1rn** [comment]
I'm using wsl2 1.3.11 pre still fail to start up kind, Is there any temporary solution?

**Comment by BenTheElder** [comment]
I think this particular issue has been resolved for a while now, so I'm going to close it.

If your'e still seeing issues, please file a new bug type issue and include the cluster logs etc (instructions in the issue template).
