### ISSUE TITLE
[Feature Request] Create KIND node with --pid=host docker or podman options

### ISSUE THREAD

**Issue by sigsegv1989** [kubernetes-sigs/kind#3182]
I am testing my eBPF program in the kind cluster using containerized eBPF program. To get the access to host pid from the container, I need to create a kind cluster node using --pid=host docker or podman command-line argument. 

I am able to achieve it with the following path on the kind master repo.

```
diff --git a/pkg/build/nodeimage/internal/container/docker/run.go b/pkg/build/nodeimage/internal/container/docker/run.go
index 54e8a42b..cd83b3f6 100644
--- a/pkg/build/nodeimage/internal/container/docker/run.go
+++ b/pkg/build/nodeimage/internal/container/docker/run.go
@@ -25,6 +25,7 @@ func Run(image string, runArgs []string, containerArgs []string) error {
        // construct the actual docker run argv
        args := []string{"run"}
        args = append(args, runArgs...)
**+       args = append(args, "--pid=host")**
        args = append(args, image)
        args = append(args, containerArgs...)
        cmd := exec.Command("docker", args...)
```

It will be really good to support this feature where we need to create a kind cluster node with host pid namespace.

**Comment by aojea** [comment]
> To get the access to host pid from the container

what is the motivation? why do you need this access?

**Comment by BenTheElder** [comment]
If you're going to run things on the host process tree why not just use "kubeadm init"?

As for eBPF: cilium has tests on KIND without patching AFAIK.

**Comment by sigsegv1989** [comment]
> What is the motivation? why do you need this access?

eBPF tool is fetching the init process id(1 in container pid namespace) of the container with respect to the host pid namespace which will be used in the user space programme to get the process details using `/proc` filesystem.

I am using the KIND cluster to run the e2e/FV test. Containerized eBPF programs run in the KIND cluster node container which gets the process ID(host pid namespace) of the process which triggers exeve() syscalls but the user space program can only access the kind cluster node container pid.

The process id is different in the kind cluster node container than the pid in the host pid namespace so userspace programs fail to find the process data-structure in `/proc `filesystem as the pid is different in the host pid namespace and kind node containers.

Please let me know if it is not clear or I need to explain it further.

**Comment by BenTheElder** [comment]
You can mount /proc from the host under some other location using https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts and then do whatever you want from there.

but I don't think it's reasonable to actually run the cluster node processes in the host PID namespace.

I would take a look at how https://docs.cilium.io/en/v1.13/installation/kind/ does it.

**Comment by sigsegv1989** [comment]
> You can mount /proc from the host under some other location using https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts and then do whatever you want from there.

It will be difficult to test the binary by mounting the host /proc file to some other location in the node container as it needs to change the code (only for testing) that will look mounted location for getting the file data-structure. 

> but I don't think it's reasonable to actually run the cluster node processes in the host PID namespace.
We could do it by following the configuration,
`apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /etc/os-release
        containerPath: /etc/os-release
  - role: worker
    hostPid: true
    extraMounts:
      - hostPath: /etc/os-release
        containerPath: /etc/os-release`
        
 In the above configuration, we are enabling the hostPid for the worker node only.
 If the hostPid is true for the given node then `docker run` command execute with the `"--pid=host"`

**Comment by BenTheElder** [comment]
We're going the opposite direction and requiring greater isolation to minimize complexity and bugs, e.g. #3241.

If you want to run kubernetes in the host namespace(s), I suggest using `kubeadm init` https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
