### ISSUE TITLE
kind Nginx Ingress controller image pull issue

### ISSUE THREAD

**Issue by tppalani** [kubernetes-sigs/kind#3204]
**What would you like to be documented**:

As per the https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx following document, I have applied yaml file to deploy the nginx ingress controller.

After applying yaml foo and bar app's are failed with image pull error.

```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  3m43s                 default-scheduler  Successfully assigned default/foo-app to kind-control-plane
  Normal   Pulling    2m7s (x4 over 3m42s)  kubelet            Pulling image "registry.k8s.io/e2e-test-images/agnhost:2.39"
  Warning  Failed     2m6s (x4 over 3m42s)  kubelet            Failed to pull image "registry.k8s.io/e2e-test-images/agnhost:2.39": rpc error: code = Unknown desc = failed to pull and unpack image "registry.k8s.io/e2e-test-images/agnhost:2.39": failed to resolve reference "registry.k8s.io/e2e-test-images/agnhost:2.39": failed to do request: Head "https://registry.k8s.io/v2/e2e-test-images/agnhost/manifests/2.39": x509: certificate signed by unknown authority
  Warning  Failed     2m6s (x4 over 3m42s)  kubelet            Error: ErrImagePull
  Warning  Failed     113s (x6 over 3m42s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    98s (x7 over 3m42s)   kubelet            Back-off pulling image "registry.k8s.io/e2e-test-images/agnhost:2.39"
```

**Why is this needed**:
Do we need add any certificate to pull the image if yes please let me know where we can add and what are the certificate do we need add.

**Comment by BenTheElder** [comment]
No you shouldn't need to add a certificate under normal circumstances. registry.k8s.io is signed with a public CA and the node images have standard root CA cert bundle from Ubuntu.

Is it possible you have a proxy in your local environment?

**Comment by tppalani** [comment]
Yes we connected in VPN network

**Comment by BenTheElder** [comment]
You have two options for this:
1. pull the images needed to the host and then `kind load docker-image ...`
2. add the cert manually for now, see https://github.com/kubernetes-sigs/kind/issues/2826

https://github.com/kubernetes-sigs/kind/issues/2826 tracks, we will add a feature at some point to make 2) simpler, but we've been a bit full with bug fixes and issue traige etc.

Sorry this is a bit painful still.

You should also see https://kind.sigs.k8s.io/docs/user/quick-start/#configure-kind-to-use-a-proxy

and #3173

**Comment by tppalani** [comment]
Hi @BenTheElder I have noticed few thing we have internal private registry Quay and kind cluster able to download the images but we are getting error 

```
 x509: certificate signed by unknown authority
```

**Comment by BenTheElder** [comment]
For private registries see: https://kind.sigs.k8s.io/docs/user/private-registries/

**Comment by tppalani** [comment]
Even though I'm not able to deploy nginx image from the internet as well (image name: nginx:1.14.2)

**Comment by BenTheElder** [comment]
For public internet see the prior comment about your VPN/proxy and certs https://github.com/kubernetes-sigs/kind/issues/3204#issuecomment-1542540411

**Comment by tppalani** [comment]
Hi @BenTheElder  I have resolved above issue. Just created extra mount configuration while creating kind cluster as like below.

But one thing mentioned below not creating automatically while creating cluster, i need login to the cluster then execute the below command.

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.27.1@sha256:c44686bf1f422942a21434e5b4070fc47f3c190305be2974f91444cd34909f1b
  extraMounts:
   - hostPath: /Users/viswa/corporate.crt
     containerPath: /usr/local/share/ca-certificates/corporate.crt
```

```
podman exec -it kind-control-plane /bin/bash
cd /usr/local/share/ca-certificates/
vi corporate.crt   (added .crt file data manually)
root@kind-control-plane:/# update-ca-certificates

``` 

Do i need add any command inside the config file create file if not exist to avoid the manual work (ls /usr/local/share/ca-certificates/corporate.crt) ?

**Comment by BenTheElder** [comment]
> Do i need add any command inside the config file create file if not exist to avoid the manual work (ls /usr/local/share/ca-certificates/corporate.crt) ?

You'll have to add a script or something for now, the config is declarative and doesn't have any way to run commands (and we have no plans to add that, though I've linked a tracking issue above for having a feature to handle adding certs specifically).

**Comment by bitemarcz** [comment]
I have a follow up question on this. If mounting, where does the mount file get applied to? i.e. kubectl apply -f <filename>. 

Does this have to be applied to the kube-system namespace where the control plan lives? Docs are a little vague after creating this.
