### ISSUE TITLE
Support github submission templates

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/kind#323]
See - https://github.com/kubernetes-sigs/cluster-api/tree/master/.github/ISSUE_TEMPLATE 

as Example

**Comment by BenTheElder** [comment]
/help

Would love if someone took this up, here are examples in other projects, see EG: 
https://github.com/kubernetes/test-infra/tree/master/.github/ISSUE_TEMPLATE
https://github.com/kubernetes/kubernetes/tree/master/.github/ISSUE_TEMPLATE
https://github.com/kubernetes-sigs/cluster-api/tree/master/.github/ISSUE_TEMPLATE

This shouldn't be very hard to setup, I just keep losing it between other things.
