### ISSUE TITLE
Adding delve as sidecar containers in Kubernetes core components via --debug-mode flag

### ISSUE THREAD

**Issue by ardaguclu** [kubernetes-sigs/kind#3239]
**What would you like to be added**:
Would it make sense to introduce a new flag such as `--debug-mode` to `kind build node-image` command. 
When this flag is passed, Kind will add delve as sidecar container into all k8s core components automatically. 
Thanks to that developers can easily port-forward those pods and easily debug core components via delve.

**Why is this needed**:
Debugging via delve would make Kubernetes maintainers' life much easier in addition to adding logs and re-deploying
these core components.
If this feature request only appeals to a very narrow audience or not applicable, etc., feel free to close it.
I just wanted to get the opinions of Kind maintainers before starting implementation of my own script. Thanks.

**Comment by BenTheElder** [comment]
node image build time isn't really the right place to insert sidecars, it doesn't have control over component bootstrap unless we applied some patch to kubeadm.

I think we should be able to do this with https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/ instead and just need to document how somewhere.

In general we need a guide for developing Kubernetes itself using KIND, but it would have overlap with other Kubernetes devel guides so it's a little tricky to say where we should put this and how to structure it.

cc @aojea @pohly

**Comment by aojea** [comment]
> I think we should be able to do this with https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/ instead and just need to document how somewhere.

:/

> Note: Ephemeral containers are not supported by [static pods](https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/).


I don't think that kind is different that others cluster in this regards, so all the same techniques for debugging a kubernetes cluster apply here ... pprof, metrics, compile and instrumented version and `kind load` it , ...
I also don't know if delve is widely used , I personally never used it, ...

**Comment by ardaguclu** [comment]
Thanks @BenTheElder @aojea for your comments. I haven't checked yet what degree the solution would be hacky and actually as Antonio said this is no different than the debugging other clusters. 

I'm closing this issue;

/close
