### ISSUE TITLE
RFE: Support for a phased breakdown of different operations, specifically create

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/kind#324]
Currently today kind executes a series of implicit steps as part of operations such as `create`.  The purpose of this issue is to make those steps explicit and well-defined ~= `kubeadm phases` such that both developers and consumers can execute different steps as needed for their testing.  

/cc @kubernetes/sig-cluster-lifecycle

**Comment by BenTheElder** [comment]
Making them well defined is the tricky part, as we've added features like HA or proxy support the required steps have changed.

An immediate alternative with even more control to iterate on kubeadm phases was suggested at the kind meeting with @fabriziopandini @neolit123 to support creating nodes but stopping short of any kubeadm provisioning etc.

**Comment by timothysc** [comment]
FWIW not all phases need to be at the same level and can go through promotion, so supportability is also explicit.

**Comment by BenTheElder** [comment]
Right. Thinking more in terms of how to actually break it down internally at this point. 

We will need some more refactor to clean up interdependencies between the creation steps (which we absolutely should do).

We should start by identifying what steps would be helpful.

As far as I could tell the most helpful thing would be to have control over the kubeadm steps, for which a way to provision but stop before `kubeadm init` / `kubeadm join` would probably be a quicker win in the short term.

**Comment by fabriziopandini** [comment]
@BenTheElder I agree? Stopping before init/join is already a well defined use case and having a short term solution in please will be great
I'm going to send a PR for this

**Comment by BenTheElder** [comment]
0.3 is overdue, punting to 0.4, but I've spent some time experimenting with options for this and what the phases should be (we need to make a few more granular).

**Comment by BenTheElder** [comment]
We wound up doing https://github.com/kubernetes-sigs/kind/issues/324#issuecomment-465731832 and it has worked pretty well, as the projects have matured kinder has needed different opinionated phases (e.g. for some time using different CNI installation) anyhow, and these are not the hard party of the project generally, the tricky part is all the "in docker" "in podman" bits, which are re-usable via this mechanism (and other APIs we've exposed).
