### ISSUE TITLE
Why kind doesn't support creating multi-node cluster in command line flags way?

### ISSUE THREAD

**Issue by LronDC** [kubernetes-sigs/kind#3268]
It should be a common scene that users want to create a local cluster with multi-node, without using a config file.
Like: `kind create cluster -n one --control-plane 1 --worker 2`
Does kind not support this for some specific reason?

**Comment by LronDC** [comment]
If this is an acceptable proposal, I can try to work on it.

**Comment by LronDC** [comment]
> we try to not overload flags, also this will be incompatible with the configuration, since each node has independent capabilities like patches or image versions, ...

Yes, makes sense, I understand.

> are you sure this request will be common?

Just my own thoughts 😆  In my case I often use kind to set up a temporary cluster to do some research, and it often requires multi nodes. In this case create a cluster easily and fast is my concern rather than the differences between nodes.

I understand your concern, thank you. I will close this question.

**Comment by aojea** [comment]
thanks for understanding, there are more places to contribute,  looking forward for more ideas to improve kind
