### ISSUE TITLE
document kubernetes behavior with image side loading and :latest tag

### ISSUE THREAD

**Issue by figo** [kubernetes-sigs/kind#328]
steps to reproduce:
1) build a container with tag: `latest`,
2) then load into kind, no error reported:
`kind load docker-image ###:latest`
3) then deploy pod to kind, check pod status, it getting image Pull Error.

it works well with other numeric tag as i tested.
thanks to @BenTheElder to point it out.

**Comment by BenTheElder** [comment]
This is a Kubernetes feature, and we should document it and how to work around:

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#container-v1-core


> `imagePullPolicy` string | Image pull policy. 
> One of Always, Never, IfNotPresent. **Defaults to Always if :latest tag is specified**, or IfNotPresent otherwise. Cannot be updated.  More info: 
> https://kubernetes.io/docs/concepts/containers/images#updating-images

(emphasis mine on `Defaults to Always if :latest tag is specified`)

**Comment by BenTheElder** [comment]
/kind documentation
/priority important-soon

work arounds are:
- don't use a `:latest` tag
- specify `imagePullPolicy: IfNotPresent` or `imagePullPolicy: Never` on your container(s)

**Comment by BenTheElder** [comment]
@tao12345666333 documented this 🙏 
https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
