### ISSUE TITLE
Hardcoded images might cause cross-cloud traffic

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kind#3289]
**What happened**:

`kindest/node` contains manifests to the following images:

```
docker.io/kindest/kindnetd                 v20230330-48f316cd   a329ae3c2c52f       27.7MB
docker.io/kindest/local-path-helper        v20230330-48f316cd   37af659db0ba1       3.05MB
docker.io/kindest/local-path-provisioner   v0.0.23-kind.0       c408b2276bb76       18.7MB
```

As far as I can tell, these images are hardcoded:

https://github.com/kubernetes-sigs/kind/blob/3610f606516ccaa88aa098465d8c13af70937050/pkg/build/nodeimage/const_cni.go#L23

This might be causing problems when running on bots on certain clouds.

**What you expected to happen**:

I can see two options:

- Provide a way to parameterize the registry, so we can point to a particular mirror.
- Use `imagePullPolicy: IfNotPresent` in the manifest, if the image is already part of the `kindest/node` image (I couldn't confirm this).

**How to reproduce it (as _minimally_ and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): `kind v0.16.0 go1.20.5 linux/amd64`; `kindest/node:v1.27.1`
- Runtime info: (use `docker info` or `podman info`):
- OS (e.g. from `/etc/os-release`):
- Kubernetes version: (use `kubectl version`):
- Any proxies or other special environment settings?:

**Comment by BenTheElder** [comment]
already present _and_ imageGC is disabled (at least until we can pin images in containerd, then we'll reconsider though image GC has other problems)
