### ISSUE TITLE
Please add support for RISCV64

### ISSUE THREAD

**Issue by pascal71** [kubernetes-sigs/kind#3300]
**What would you like to be added**:

Support for running/deploying KIND on RISCV64 architecture.

**Why is this needed**:

RISCV64 is currently getting more and more common. The Vision5-2 RISCV64 board supporting 4 cores and 8GiB of memory are ideal for running K8S/KIND.

**Comment by stmcginnis** [comment]
The published images are done manually by the `kind` maintainers, so it is a convenience that is limited to what they are able to support. Though I'm sure they wouldn't mind getting free RISV64 hardware to help. :D

For anything other than the main use case of testing k8s in upstream CI, it is recommended you [build your own images](https://kind.sigs.k8s.io/docs/user/quick-start/#building-images).

**Comment by aojea** [comment]
is not only about the published images, is about kubernetes support, kind can not guarantee that something that kubernetes does not support will work ... first step is to have some sort of support in Kubernetes, next one is to provide some CI for the platform and people commiting to maintain it

**Comment by BenTheElder** [comment]
Right, currently Kubernetes doesn't support RISCV so you'll have to overcome that first and then we can evaluate if there's sufficient reason for kind to follow suit.

To get support in upstream Kubernetes you will have to talk to SIG Release, and CI infrastructure (or rather lack of options readily available to the project) will be a major topic.
