### ISSUE TITLE
[user application] KIND: version > 0.20.0 causes panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by skumarya-tibco** [kubernetes-sigs/kind#3305]
**What happened**:

when trying to deploy application on kind version 0.20.0 the deployments are failing with the error 

Release "artifact-management" does not exist. Installing it now.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1398670]

**What you expected to happen**:
The tekton pipeline should run the deployment artifact-management

**How to reproduce it (as _minimally_ and precisely as possible)**:
Create kind cluster with version 0.20.0 and Kubernetes version 1.27.3, and run a deployment it fails

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.20.0
- Runtime info: (use `docker info` or `podman info`):
- OS (e.g. from `/etc/os-release`): Mac 0s intel
- Kubernetes version: (use `kubectl version`): 1.27.3
- Any proxies or other special environment settings?:

**Comment by aojea** [comment]
where is the panic? in kind? you need to provide more information or is not possible to understand the problem

**Comment by skumarya-tibco** [comment]
When running an application on kind version 0.20.0 with k8s version 1.27.3 the application is failing with the error "panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1398670]" 
whereas when we are trying with kind version 0.18.0 and k8s version 1.27.3 the application is working smoothly.
Also, we tried explicitly passing kind node image version 1.26.6 then it works smoothly but it fails when the default kind node image version is 1.27.3 it shows the above error.
So this seems to be a version compatibility issue 
kindly address.

**Comment by aojea** [comment]
> So this seems to be a version compatibility issue

it seems a compatibility issue with your application then, you should debug your application to understand what is making it panicing

**Comment by BenTheElder** [comment]
That is: it seems to be a compatibility issue with your application and Kubernetes versions. KIND is not responsible for that and it's well documented in the release notes that we switched to a new kubernetes version.

you'll need to fix the compatibility issue in your application or if you can find a bug in kubernetes then you'll need to report it to the kubernetes repo.

/remove-kind bug
/kind support
