### ISSUE TITLE
brew install kind version didn't match the latest version

### ISSUE THREAD

**Issue by charles-chenzz** [kubernetes-sigs/kind#3307]
<img width="968" alt="image" src="https://github.com/kubernetes-sigs/kind/assets/73322208/308158c6-f9fd-4b50-9ba0-fa4f882a1ece">

I've previous install kind with brew. to verify it, I run brew upgrade kind and it didn't fetch the latest version 0.20. and I uninstall it to reinstall again, running brew install kind. it still install 0.15

**Comment by liangyuanpeng** [comment]
Seems like the package for brew is not publish with kind community, you can create the issue on the repo of brew.

And the PR for the 0.20 kind is merged. check:
- https://github.com/Homebrew/homebrew-core/pull/133771

**Comment by tao12345666333** [comment]
As  [Lan](https://github.com/liangyuanpeng) mentioned, the `kind` package in the brew is not part of the release process for the kind project so it may lag behind. 

If you want to use the latest version, download the latest binary from the release page.

 The corresponding [PR](https://github.com/Homebrew/homebrew-core/pull/133771) has been merged and this issue can be closed now.

Thanks
/close
