### ISSUE TITLE
node disk full

### ISSUE THREAD

**Issue by zffocussss** [kubernetes-sigs/kind#3313]
**What happened**:
node disk is almost full 

**What you expected to happen**:
disk space is available.

**How to reproduce it (as _minimally_ and precisely as possible)**:
everytime I created a cluster,after some hours,it get full

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): kind v0.11.1 go1.17.2 darwin/amd64
- Runtime info: (use `docker info` or `podman info`): 20.10.20
- OS (e.g. from `/etc/os-release`): Macos Ventura
- Kubernetes version: (use `kubectl version`): 
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:31Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:06:30Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.24) and server (1.21) exceeds the supported minor version skew of +/-1
```
- Any proxies or other special environment settings?:

![image](https://github.com/kubernetes-sigs/kind/assets/46145695/25015a91-49c1-48da-9ea0-9f0e2532b736)

**Comment by zffocussss** [comment]
there are only some docker containers and pvcs.why does the node take up too much disk space?

**Comment by liangyuanpeng** [comment]
kind and the cluster created by kind itself will not take up much resources.

**Comment by BenTheElder** [comment]
This is #735

**Comment by zffocussss** [comment]
> 

I am using MacBook Pro which free disk storage is more than 512G

**Comment by BenTheElder** [comment]
Please see #735
/remove-kind bug
/kind support

It's possible to exhaust disk space for many reasons, and there's limited options for kind to mitigate this.
You'll have to allocated more disk space or recreate the clusters to free up space.

> I am using MacBook Pro which free disk storage is more than 512G

Docker on mac runs in a VM which has it's own virtual disk which only goes up to some configured subset of the free space. There's some references to those settings here https://kind.sigs.k8s.io/docs/user/quick-start/#settings-for-docker-desktop

**Comment by stmcginnis** [comment]
/close

Cleaning this up. Fairly certain this is a matter of allocating more space for the Docker VM.
