### ISSUE TITLE
Failed with exit 0: `kind delete cluster`

### ISSUE THREAD

**Issue by domust** [kubernetes-sigs/kind#3322]
**What happened**:

`kind delete cluster` is not working, but `kind delete cluster --name` is.

**What you expected to happen**:

Since I have a single cluster, I've expected `kind delete cluster` to delete it OR exit with an error if the cluster does not exist.
What it does instead is assume that my cluster is named `kind` and just prints to the terminal:
```sh
Deleting cluster "kind" ...
```
and exits with 0.

**How to reproduce it (as _minimally_ and precisely as possible)**:

Have a cluster with any name except kind.

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.20.0
- Runtime info: (use `docker info` or `podman info`): Docker Desktop 4.21.1 with Docker Engine 24.0.2
- OS (e.g. from `/etc/os-release`): macOS Ventura 13.5
- Kubernetes version: (use `kubectl version`): v1.27.3
- Any proxies or other special environment settings?: No

**Comment by stmcginnis** [comment]
> Have a cluster with any name except kind.

This is the root (or part of the root) of your issue.

`kind delete cluster` is a convenient shorthand for deleting the default "kind" cluster created with a plain `kind create cluster`. `kind delete` itself is an idempotent operation, so you can call `kind delete cluster` in an endless loop, and it is always going to return success. Basically, you are saying `kind delete cluster --name kind` by calling that, and `kind` is kindly telling you "ok, the 'kind' cluster has been deleted".

Now if you are using a different name for your cluster, this shorthand way of saying `kind delete cluster --name kind` is going to make sure there is no cluster named "kind" and return success, and of course leave alone any other cluster you have on the system.

You would definitely not want to make any decisions along the lines of "well, there is no cluster named kind, so I'm just going to delete this other cluster I see out there". That would be Very Bad.

**Comment by BenTheElder** [comment]
you can use `kind delete clusters -A` to delete all clusters regardless of name

otherwise *all* commands require `--name` if you want to work with clusters other than the default.

`kind delete cluster` is re-entrant and only exists non-zero if some action fails (think `rm -rf`)
