### ISSUE TITLE
Custom Node Image with Preinstalled Deployments

### ISSUE THREAD

**Issue by tommazzo89** [kubernetes-sigs/kind#3329]
Hi everyone,

I would like to prepare a local Kubernetes cluster with Prometheus preinstalled that can be easily shared with others. I will hold a workshop, where the attendees will need this to code along. I thought that a kind node image that already contains a Prometheus installation would be the ideal way to go. Is this possible and, if yes, how could I achieve that?

Thanks a lot in advance!

**Comment by lewisxin** [comment]
I have modified the containerd CRI code and built a version of containerd locally. May I know if there's a way tell KIND to use my local containerd when I run `kind build node-image`? Thanks in advance!
