### ISSUE TITLE
How to Stop a cluster , like ' kind stop '

### ISSUE THREAD

**Issue by felix0080** [kubernetes-sigs/kind#3336]
I think running it all the time wastes resources, but I don't want to delete it. Is there any way to stop it

**Comment by stmcginnis** [comment]
You can use `docker stop` to stop the container. Otherwise, it is best to treat the kind cluster as ephemeral and just delete and create again as needed.

**Comment by felix0080** [comment]
ok, thank you

**Comment by BenTheElder** [comment]
In addition to @stmcginnis There's a tracking issue about start/stop commands, but until then (if ever) +1, this is the answer
