### ISSUE TITLE
jobs are broken on kubernetes master (build)

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#336]
https://github.com/kubernetes/kubernetes/pull/73930 added cross build support, which shuffled some things around. WIP fix in #335 

/kind bug
/priority critical-urgent
/assign

**Comment by alejandrox1** [comment]
Seems to have worked: tested it on #320 and #337 
/close

**Comment by BenTheElder** [comment]
Thanks!

**Comment by ixdy** [comment]
follow-up PR https://github.com/kubernetes/kubernetes/pull/74467 is going to restore the old filenames.
