### ISSUE TITLE
GitHub Actions: use "larger" runners for nested virt

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes-sigs/kind#3364]
https://github.com/kubernetes-sigs/kind/blob/ac28d7fb19b4f353369d889b3900a7a9dd46f4c1/.github/workflows/cgroup2.yaml#L16-L18

The current CI uses very slow `macos-12` instances for nested virtualization, but the CI can get better performance and stability by switching it to "larger" Linux runners such as `ubuntu-latest-4-cores`: https://github.blog/changelog/2022-10-20-github-actions-larger-hosted-runners-are-now-automatically-created-for-customers/

CNCF projects have accesses to larger instances, but it has to be explicitly enabled by an admin of https://github.com/kubernetes-sigs :
- Open https://github.com/organizations/kubernetes-sigs/settings/actions/runner-groups
- Click `Default Larger Runners`
- Click `Allow public repositories`
- Click `Selected repositories`, and choose the `kind` repo

**Comment by AkihiroSuda** [comment]
(For cgroup v2, we can just consider switching from the Fedora VM to the free `ubuntu-22.04` instances, but having a test with Fedora VM still makes sense, as its LSM and root filesystem is different from Ubuntu)

**Comment by BenTheElder** [comment]
Thanks!
We'll have to make a request with https://github.com/kubernetes/org

**Comment by AkihiroSuda** [comment]
> Thanks! We'll have to make a request with https://github.com/kubernetes/org

Thanks, made a request:
- https://github.com/kubernetes/org/issues/4490

**Comment by AkihiroSuda** [comment]
Standard runners now support nested virt:
- https://github.com/kubernetes-sigs/kind/pull/3484
