### ISSUE TITLE
not able to deploy docker image in a single node kind cluster

### ISSUE THREAD

**Issue by wamik25apr** [kubernetes-sigs/kind#3367]
**What happened**:

I have followed the below steps.

Delete the kind cluster:delete the cluster using the following command:
kind delete cluster --name kind-control-plane
Recreate the kind cluster: After deleting the cluster, recreate it using the following command:
kind create cluster --name kind-control-plane
Load the Docker image to kind: Load the Docker image to kind using the following command:
kind load docker-image my-flask-app:latest
Create a deployment: You can create a deployment using the following command:
kubectl create deployment my-flask-app --image=my-flask-app:latest
Expose the deployment: Finally, expose the deployment using the following command:
kubectl expose deployment my-flask-app --type=LoadBalancer --port 80
Below are the outputs
C:\docker\python\test2>kind delete cluster --name kind-control-plane
Deleting cluster "kind-control-plane" ...

C:\docker\python\test2>kind create cluster --name kind-control-plane
Creating cluster "kind-control-plane" ...
• Ensuring node image (kindest/node:v1.27.3) 🖼 ...
✓ Ensuring node image (kindest/node:v1.27.3) 🖼
• Preparing nodes 📦 ...
✓ Preparing nodes 📦
• Writing configuration 📜 ...
✓ Writing configuration 📜
• Starting control-plane 🕹️ ...
✓ Starting control-plane 🕹️
• Installing CNI 🔌 ...
✓ Installing CNI 🔌
• Installing StorageClass 💾 ...
✓ Installing StorageClass 💾
Set kubectl context to "kind-kind-control-plane"
You can now use your cluster with:

kubectl cluster-info --context kind-kind-control-plane

Have a nice day! 👋

C:\docker\python\test2>kind load docker-image my-flask-app:latest
Image: "my-flask-app:latest" with ID "sha256:9b1a50c69caeb05665cdc93477cdc02a8a2a00ba24cffa1e817286694a9c1f26" found to be already present on all nodes.

C:\docker\python\test2>kubectl create deployment my-flask-app --image=my-flask-app:latest
deployment.apps/my-flask-app created

C:\docker\python\test2>kubectl expose deployment my-flask-app --type=LoadBalancer --port 80
service/my-flask-app exposed

C:\docker\python\test2>kubectl get pods
NAME READY STATUS RESTARTS AGE
my-flask-app-76c7dcc464-g2cbb 0/1 ErrImagePull 0 15s

C:\docker\python\test2>kubectl describe pod my-flask-app-76c7dcc464-g2cbb
Name: my-flask-app-76c7dcc464-g2cbb
Namespace: default
Priority: 0
Service Account: default
Node: kind-control-plane-control-plane/172.19.0.3
Start Time: Mon, 25 Sep 2023 12:03:01 +0530
Labels: app=my-flask-app
pod-template-hash=76c7dcc464
Annotations:
Status: Pending
IP: 10.244.0.5
IPs:
IP: 10.244.0.5
Controlled By: ReplicaSet/my-flask-app-76c7dcc464
Containers:
my-flask-app:
Container ID:
Image: my-flask-app:latest
Image ID:
Port:
Host Port:
State: Waiting
Reason: ErrImagePull
Ready: False
Restart Count: 0
Environment:
Mounts:
/var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-f5prb (ro)
Conditions:
Type Status
Initialized True
Ready False
ContainersReady False
PodScheduled True
Volumes:
kube-api-access-f5prb:
Type: Projected (a volume that contains injected data from multiple sources)
TokenExpirationSeconds: 3607
ConfigMapName: kube-root-ca.crt
ConfigMapOptional:
DownwardAPI: true
QoS Class: BestEffort
Node-Selectors:
Tolerations: node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
Type Reason Age From Message

Normal Scheduled 35s default-scheduler Successfully assigned default/my-flask-app-76c7dcc464-g2cbb to kind-control-plane-control-plane
Normal Pulling 17s (x2 over 34s) kubelet Pulling image "my-flask-app:latest"
Warning Failed 15s (x2 over 32s) kubelet Failed to pull image "my-flask-app:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/my-flask-app:latest": failed to resolve reference "docker.io/library/my-flask-app:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Warning Failed 15s (x2 over 32s) kubelet Error: ErrImagePull
Normal BackOff 4s (x2 over 32s) kubelet Back-off pul

**What you expected to happen**:
successful deployment
**How to reproduce it (as _minimally_ and precisely as possible)**:
please follow the step docker file and app.py attached
**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):kind v0.20.0 go1.20.4 windows/amd64
- Runtime info: (use `docker info` or `podman info`):
- Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 9
  Running: 2
  Paused: 0
  Stopped: 7
 Images: 17
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.684GiB
 Name: docker-desktop
 ID: a071f45b-ee64-4c6e-883a-ea0f1dbe8ce5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
- OS (e.g. from `/etc/os-release`):
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
#C:\docker\python\test2>wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                   OSArchitecture  Version
22621        Microsoft Windows 11 Pro  64-bit          10.0.22621
- Kubernetes version: (use `kubectl version`):
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.27) exceeds the supported minor version skew of +/-1
- Any proxies or other special environment settings?:no
[Dockerfile.zip](https://github.com/kubernetes-sigs/kind/files/12712079/Dockerfile.zip)

**Comment by wamik25apr** [comment]
@aojea can you please help to resolve this issue. How to to do this authentication
image registry exsists
C:\docker\python\test2>docker exec -it kind-control-plane crictl images
IMAGE                                            TAG                  IMAGE ID            SIZE
docker.io/kindest/kindnetd                       v20230511-dc714da8   b0b1fa0f58c6e       27.7MB
docker.io/kindest/local-path-helper              v20230510-486859a6   be300acfc8622       3.05MB
docker.io/kindest/local-path-provisioner         v20230511-dc714da8   ce18e076e9d4b       19.4MB
docker.io/library/flaskapp                       latest               626fcd94ad53c       142MB
docker.io/library/hello-world1                   latest               1c08857c33b92       123MB
docker.io/library/hello-world                    latest               ed624fcf31ba1       134MB
docker.io/library/my-flask-app                   latest               9b1a50c69caeb       134MB
docker.io/library/my-flask-app                   v1                   9b1a50c69caeb       134MB
docker.io/otel/opentelemetry-collector-contrib   0.85.0               8051649435451       60.1MB
registry.k8s.io/coredns/coredns                  v1.10.1              ead0a4a53df89       16.2MB
registry.k8s.io/etcd                             3.5.7-0              86b6af7dd652c       102MB
registry.k8s.io/kube-apiserver                   v1.27.3              c604ff157f0cf       83.5MB
registry.k8s.io/kube-controller-manager          v1.27.3              9f8f3a9f3e8a9       74.4MB
registry.k8s.io/kube-proxy                       v1.27.3              9d5429f6d7697       72.7MB
registry.k8s.io/kube-scheduler                   v1.27.3              205a4d549b94d       59.8MB
registry.k8s.io/pause                            3.7                  221177c6082a8       311kB

**Comment by wamik25apr** [comment]
my-flask-app:latest is already available in the kind-control-plane still facing this issue
I am using the below deployment config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: my-flask-app:latest
        ports:
        - containerPort: 5000

**Comment by BenTheElder** [comment]
The problem is using a `:latest` tag, please see the docs:

https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

/remove-kind bug
/kind support
