### ISSUE TITLE
Is it possible to run 5000 pods in Kind cluster?

### ISSUE THREAD

**Issue by chenweiyj** [kubernetes-sigs/kind#3373]
I tried to scale pods in Kind cluster. When I deploy a deployment.yaml with 500 replicas, the kube-apiserver exits unexpectedly. So I wonder whether it is possible to run 5000 pods in Kind cluster.

My environment:
OS: Linux 
Memory: 512GB
Kind cluster: 1 control-plane, 16 workers

**Comment by aojea** [comment]
you are hitting kubernetes components limits, kind virtualizes the environments in containers, nothing else, for the rest you should expect debugging kube-apiserver as in any other cluster
