### ISSUE TITLE
Is it possible to expose LoadBalancer ExternalIP to localhost?

### ISSUE THREAD

**Issue by AnhQuanTrl** [kubernetes-sigs/kind#3374]
I'm currently following the doc at https://kind.sigs.k8s.io/docs/user/loadbalancer/ to set up a LoadBalancer Service using Metallb. I can `curl` to the external IP as I am using WSL2 Ubuntu. Is it possible also to map the `<externalIP>:<port>` to a port on WSL  `localhost`? This is because sometimes I do want to access it through the window machine (e.g to open the URL in browser).

**Comment by BenTheElder** [comment]
Sorry but metallb is out of scope for us.

Please see the note at the top about the limitations of WSL2 networking.

**Comment by Dheerajreddy9999** [comment]
U can install a browser inside WSL2. It supports gui applications

**Comment by zsparal** [comment]
I ran into the same problem setting up an Istio ingress gateway and wanting to open the exposed services in a browser on the host Windows machine. What I ended up doing is installing nginx and then in `/etc/nginx/nginx.conf`:

```
stream {
  server {
    listen     <wslPort>;
    proxy_pass <externalIP>:<port>;
  }
}
```

**Comment by AnhQuanTrl** [comment]
Thank you guys for support.
