### ISSUE TITLE
Allow customizing defautl value for --name option

### ISSUE THREAD

**Issue by MaGaroo** [kubernetes-sigs/kind#3375]
**What would you like to be added**:
When `--name` flag is not specified, the kind command falls back to the default cluster name `kind`. However, it may be more convenient to let the users customize this value. I can think of two methods to achieve this:
1. Through the use of an environment variable: The default value may be set by an environment variable, e.g. `KIND_DEFAULT_CLUSTER`
2. Use a subcommand like `kubectl config use-context` which changes the current context of kubectl. In case of kind, it can be something like `kind use-cluster somecluster`.

**Why is this needed**:
It makes a better user experience when working with a kind cluster that's not the default (kind-kind) one.

**Comment by BenTheElder** [comment]
That shared state in kubectl has caused a _lot_ of problems with kubeconfig management and I think is generally considered an anti pattern at this point. 1) is available if you'd like to avoid including the flag explicitly repeatedly, and you can use a tool like direnv to manage this.

**Comment by MaGaroo** [comment]
Oh, nice. I'm sorry for my ignorance about the environment variable.
I'll close this issue.
