### ISSUE TITLE
kindnet container fails to start

### ISSUE THREAD

**Issue by arogic** [kubernetes-sigs/kind#3386]
**What happened**:
I am able to create a cluster but the `kindnet container` does not start. Getting the following Error when running `kubectl describe pod kindnet-pshk8 -n kube-system`:

```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  57s               default-scheduler  Successfully assigned kube-system/kindnet-pshk8 to demo-control-plane
  Normal   Pulled     5s (x4 over 56s)  kubelet            Container image "docker.io/kindest/kindnetd:v20230511-dc714da8" already present on machine
  Normal   Created    5s (x4 over 52s)  kubelet            Created container kindnet-cni
  Warning  Failed     4s (x4 over 47s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: openat2 /sys/fs/cgroup/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-podd4baa013_3583_46b6_9aea_9f45d5f1a3a0.slice/cri-containerd-kindnet-cni.scope/memory.max: no such file or directory: unknown
  Warning  BackOff    3s (x5 over 45s)  kubelet            Back-off restarting failed container kindnet-cni in pod kindnet-pshk8_kube-system(d4baa013-3583-46b6-9aea-9f45d5f1a3a0)
```

**What you expected to happen**:

**How to reproduce it (as _minimally_ and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): kind v0.20.0 go1.20.4 linux/arm64
- Runtime info: (use `docker info` or `podman info`):
```

Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.21-v8+
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
Total Memory: 3.705GiB
 Name: mypi
 ID: 0e73c0f0-feb3-470a-ac53-089244947d6f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`):
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kubernetes version: (use `kubectl version`):
```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
- Any proxies or other special environment settings?: no

**Comment by aojea** [comment]
>  Architecture: aarch64

see the open issues if you are hitting some problem already reported caused by the multiplatform

**Comment by arogic** [comment]
Hi @aojea, I checked reported issues and tried `kind v0.19.0 go1.20.4 linux/arm64 `, but same error for `kindnet` container.

**Comment by BenTheElder** [comment]
@aojea AFAICT in this case they're on an arm64 linux host running arm64 kind + kind image.

>   Warning  Failed     4s (x4 over 47s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: openat2 /sys/fs/cgroup/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-podd4baa013_3583_46b6_9aea_9f45d5f1a3a0.slice/cri-containerd-kindnet-cni.scope/memory.max: no such file or directory: unknown


Looks like a problem with cgroups on the host. Appears to be using systemd + v2 on debian which should be fine but ...

**Comment by arogic** [comment]
Thanks @BenTheElder. That’s that case. I already tried to revert to cgroups v1 and reinstalled docker to use cgroups v1, but then kind fails on creating the cluster. I guess I am out of luck and already spend way too much time to troubleshoot the issue. I am going to switch to ubuntu rather than debian. Going to close the issue.

**Comment by BenTheElder** [comment]
cgroups v2 is supported, FWIW, as long as it's kubernetes 1.19+

https://kind.sigs.k8s.io/docs/user/known-issues/#failure-to-create-cluster-with-cgroups-v2
