### ISSUE TITLE
Example ingress-nginx solution in user guide fails if it's not the first cluster created

### ISSUE THREAD

**Issue by hughpv** [kubernetes-sigs/kind#3405]
**What happened**:

I was following the example from https://kind.sigs.k8s.io/docs/user/ingress#ingress-nginx and the "Wait until is ready to process requests" step timed out and never succeeded. The "admission" pods kept restarting with errors like this in their logs:

```
W1030 20:28:27.115874       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"err":"Get \"https://10.96.0.1:443/api/v1/namespaces/ingress-nginx/secrets/ingress-nginx-admission\": dial tcp 10.96.0.1:443: i/o timeout","level":"fatal","msg":"error getting secret","source":"k8s/k8s.go:232","time":"2023-10-30T20:28:57Z"}
failed to create fsnotify watcher: too many open files
```

On further investigation, if I deleted all kind clusters and started over with _just_ the ingress example linked above, it worked fine.

I conclude that something goes wrong when the cluster being targeted isn't the first cluster created.

**What you expected to happen**:

I expected it to work just fine whether there was another cluster set up or not.

**How to reproduce it (as _minimally_ and precisely as possible)**:

1. Create a kind cluster (I ran `kind create cluster --config=kind.yml` against this file: https://github.com/nigelpoulton/TheK8sBook/blob/main/installation/kind.yml)
2. Create another kind cluster as directed at the top of https://kind.sigs.k8s.io/docs/user/ingress
3. Follow the instructions at https://kind.sigs.k8s.io/docs/user/ingress#ingress-nginx to "wait until is ready to process requests"
4. Expected: comes up working fine
5. Observed: times out

If you skip step 1, steps 2-5 work fine.

**Anything else we need to know?**:

See also https://github.com/kubernetes/ingress-nginx/issues/10524 -- not sure if this is a kind issue or an ingress issue.

**Environment:**

Ubuntu 22.04 (Server)

- kind version: (use `kind version`): `kind v0.20.0 go1.20.4 linux/amd64`
- Runtime info: (use `docker info` or `podman info`): 
```
docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-87-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.88GiB
 Name: lab2
 ID: P73G:6EIM:FRQK:7RCP:BZS7:ZE2Y:C5M2:MQ5A:7PPV:XWIV:4ZLI:OQBK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- OS (e.g. from `/etc/os-release`): 
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

- Kubernetes version: (use `kubectl version`):
```
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

- Any proxies or other special environment settings?:

Don't think it should matter, but the server I'm testing on is a virtual machine that's running inside a Proxmox host.

**Comment by eth7** [comment]
The specific error message from the logs `Failed to create fsnotify watcher: too many open files` is indicative of running out of inotify resources.

Check the following page ([pod-errors-due-to-too-many-open-files](https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files)) from the kind documentation and increase the limit for `fs.inotify.max_user_watches` and `fs.inotify.max_user_instances`.

**Comment by hughpv** [comment]
Thank you @eth7! That was the issue. Closing.
