### ISSUE TITLE
Once I create a `kind`- cluster, the previous `kubernetes`-cluster made up of 5 other nodes (Cloud VPS) is no longer visible using `kubectl get nodes` 

### ISSUE THREAD

**Issue by raphael10-collab** [kubernetes-sigs/kind#3406]
**What happened**:

I've discovered something strange which might be related to the issue I've described here:

https://serverfault.com/questions/1146920/failed-to-create-cluster-failed-to-join-node-with-kubeadm

https://stackoverflow.com/questions/77394947/failed-to-create-cluster-failed-to-join-node-with-kubeadm

https://kubernetes.slack.com/archives/C09NXKJKA/p1698744506943559

Once I create a `kind`- cluster, the previous `kubernetes`-cluster made up of 5 other nodes (Cloud VPS) is no longer visible using `kubectl get nodes`  : 

    oot@k8s-eu-1-master:~# kubectl get nodes
    NAME                STATUS   ROLES           AGE   VERSION
    k8s-eu-1-master     Ready    control-plane   25m   v1.28.2
    k8s-eu-1-worker-1   Ready    <none>          22m   v1.28.2
    k8s-eu-1-worker-2   Ready    <none>          21m   v1.28.2
    k8s-eu-1-worker-3   Ready    <none>          19m   v1.28.2
    k8s-eu-1-worker-4   Ready    <none>          17m   v1.28.2
    k8s-eu-1-worker-5   Ready    <none>          16m   v1.28.2
    root@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# kind get clusters
    No kind clusters found.
    root@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# kind create cluster
    Creating cluster "kind" ...
     ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
     ✓ Preparing nodes 📦  
     ✓ Writing configuration 📜 
     ✓ Starting control-plane 🕹️ 
     ✓ Installing CNI 🔌 
     ✓ Installing StorageClass 💾 
    Set kubectl context to "kind-kind"
    You can now use your cluster with:
    
    kubectl cluster-info --context kind-kind
    
    Thanks for using kind! 😊
    root@k8s-eu-1-master:~# kubectl cluster-info --context kind-kind
    Kubernetes control plane is running at https://127.0.0.1:32835
    CoreDNS is running at https://127.0.0.1:32835/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
    
    To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
    root@k8s-eu-1-master:~# kubectl get ndoes
    error: the server doesn't have a resource type "ndoes"
    root@k8s-eu-1-master:~# kubectl get nodes
    NAME                 STATUS   ROLES           AGE     VERSION
    kind-control-plane   Ready    control-plane   3m20s   v1.27.3

And...
once I delete the `kind` cluster I get `connection` issues:

    root@k8s-eu-1-master:~# kind delete clusters kind
    Deleted nodes: ["kind-control-plane"]
    Deleted clusters: ["kind"]
    root@k8s-eu-1-master:~# kind get clusters
    No kind clusters found.
    root@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# kubectl get nodes
    E1031 13:02:42.466619   11011 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
    E1031 13:02:42.467156   11011 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
    E1031 13:02:42.468328   11011 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
    E1031 13:02:42.469816   11011 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
    E1031 13:02:42.471332   11011 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
    The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Environment:**

- kind version: (use `kind version`):

    root@k8s-eu-1-master:~# kind version
    kind v0.20.0 go1.21.3 linux/amd64

- Runtime info: (use `docker info` or `podman info`):

root@k8s-eu-1-master:~# docker info
    Client: Docker Engine - Community
     Version:    24.0.7
     Context:    default
     Debug Mode: false
     Plugins:
      buildx: Docker Buildx (Docker Inc.)
        Version:  v0.11.2
        Path:     /usr/libexec/docker/cli-plugins/docker-buildx
      compose: Docker Compose (Docker Inc.)
        Version:  v2.21.0
        Path:     /usr/libexec/docker/cli-plugins/docker-compose
    
    Server:
     Containers: 3
      Running: 2
      Paused: 0
      Stopped: 1
     Images: 4
     Server Version: 24.0.7
     Storage Driver: overlay2
      Backing Filesystem: extfs
      Supports d_type: true
      Using metacopy: false
      Native Overlay Diff: true
      userxattr: false
     Logging Driver: json-file
     Cgroup Driver: systemd
     Cgroup Version: 2
     Plugins:
      Volume: local
      Network: bridge host ipvlan macvlan null overlay
      Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
     Swarm: inactive
     Runtimes: io.containerd.runc.v2 runc
     Default Runtime: runc
     Init Binary: docker-init
     containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
     runc version: v1.1.9-0-gccaecfc
     init version: de40ad0
     Security Options:
      apparmor
      seccomp
       Profile: builtin
      cgroupns
     Kernel Version: 5.15.0-87-generic
     Operating System: Ubuntu 22.04.3 LTS
     OSType: linux
     Architecture: x86_64
     CPUs: 10
     Total Memory: 58.86GiB
     Name: k8s-eu-1-master
     ID: 3f4609c8-f022-4b90-bc97-1da8a2f5eaf3
     Docker Root Dir: /var/lib/docker
     Debug Mode: false
     Experimental: false
     Insecure Registries:
      127.0.0.0/8
     Live Restore Enabled: false

- OS (e.g. from `/etc/os-release`): Ubuntu 22.04
- Kubernetes version: (use `kubectl version`):

    root@k8s-eu-1-master:~# kubectl version
    Client Version: v1.28.2
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.27.3

- Any proxies or other special environment settings?:

**Comment by aojea** [comment]
oh, this is on how kubectl works, it uses a configuration to select on or other cluster, there are a lot of articles about it

https://loft.sh/blog/kubectl-get-context-its-uses-and-how-to-get-started/
