### ISSUE TITLE
flaky test: boot fedora with vagrant in macos-12 with `gurumeditation` state

### ISSUE THREAD

**Issue by yankay** [kubernetes-sigs/kind#3411]
**What happened**:

The test in  boot fedora with vagrant in macos-12 is failed with `gurumeditation` state. The error logs:

```
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'gurumeditation' state. Please verify everything is configured
properly and try again.
```

The CI link: https://github.com/kubernetes-sigs/kind/actions/runs/6718255767/job/18257638805?pr=3409

It seems the same as:  https://github.com/kubernetes-sigs/security-profiles-operator/issues/1936
It seems releate to https://github.com/actions/runner-images/pull/8653

**What you expected to happen**:

The CI can run successfully

**How to reproduce it (as _minimally_ and precisely as possible)**:

every CI recently

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
- Runtime info: (use `docker info` or `podman info`):
- OS (e.g. from `/etc/os-release`):
- Kubernetes version: (use `kubectl version`):
- Any proxies or other special environment settings?:

**Comment by saschagrunert** [comment]
Opened https://github.com/actions/runner-images/issues/8730 for this

**Comment by stmcginnis** [comment]
Looks like the issue Sascha linked is closed. Can this one be as well?

**Comment by saschagrunert** [comment]
Yep, this one is gone now.

/close
