### ISSUE TITLE
Access port forward for pods from other containers -- any ideas on linux?

### ISSUE THREAD

**Issue by adamdavis40208** [kubernetes-sigs/kind#3422]
what we're doing: 

- kind runs our pods
- we're reusing old docker-compose setups to spin up dependencies, and using the `kind` docker network in our docker-compose (external: true) to make communication a little easier

On mac:
1. Pods can talk to containers via container name (pod --> http://dependency:5432 works)
2. Containers can talk to pods via the host (container --> http://host.docker.internal:8080 works)

On linux: 
1. Pods can still talk to containers via container name.
2. Containers can't talk to pods. host.docker.internal doesn't exist, and I can't get containers on the kind network to work with the `host.docker.internal:host-gateway` extra-hosts hack. (https://stackoverflow.com/a/43541732)

Any ideas? thanks in advance!

**Comment by aojea** [comment]
what is a container here? the docker container as in the kind node?

> Containers can talk to pods via the host

do you use NodePort or hostPort?

**Comment by adamdavis40208** [comment]
>what is a container here? the docker container as in the kind node?

Yeah, that's a good example (but I'm running a bunch of containers on the `kind` docker network, some of them need to call pods)

>do you use NodePort or hostPort?

ClusterIP on a service, with a port forward to the host for access

**Comment by aojea** [comment]
you can use https://github.com/kubernetes-sigs/cloud-provider-kind and create Services Type loadbalancer, those will create a new container that will forward to the specific pod

**Comment by adamdavis40208** [comment]
Oh dang, that's neat. Will check it out. 

I've been on a total hack train just trying to get this work, so far running this container https://github.com/qoomon/docker-host

plus a port forward bound to 0.0.0.0 is working, but is very hacky
`kubectl port-forward svc/mysvc -n svc 10010:8080 --address='0.0.0.0'`

Will give the loadbalancer a shot!

**Comment by adamdavis40208** [comment]
What finally unblocked me: 

* kubectl port forwards allow you to add the host it binds to. Default is localhost/127.0.0.1 but 0.0.0.0 will allow network traffic from other interfaces
`kubectl port-forward svc/mysvc -n mysvc 8080:8080 --address='0.0.0.0'`
* Because we're using tilt to manage these, tilt also lets you set a `--host` flag that achieves the same effect 
`tilt ci --host 0.0.0.0`

Hopefully this helps someone in the future. Thanks @aojea  !
