### ISSUE TITLE
ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"

### ISSUE THREAD

**Issue by raphael10-collab** [kubernetes-sigs/kind#3423]
**What happened**:

I'm getting this error when trying to create a cluster with kind :

    root@k8s-eu-1-master:~# kind create cluster
    Creating cluster "kind" ...
     ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
     ✗ Preparing nodes 📦  
    Deleted nodes: ["kind-control-plane"]
    ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"

**What you expected to happen**: No errors

**How to reproduce it (as _minimally_ and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):

    root@k8s-eu-1-master:~# kind version
    kind v0.20.0 go1.21.4 linux/amd64

- Runtime info: (use `docker info` or `podman info`):

    root@k8s-eu-1-master:~# docker info
    Client: Docker Engine - Community
     Version:    24.0.7
     Context:    default
     Debug Mode: false
     Plugins:
      buildx: Docker Buildx (Docker Inc.)
        Version:  v0.11.2
        Path:     /usr/libexec/docker/cli-plugins/docker-buildx
      compose: Docker Compose (Docker Inc.)
        Version:  v2.21.0
        Path:     /usr/libexec/docker/cli-plugins/docker-compose
    
    Server:
     Containers: 6
      Running: 5
      Paused: 0
      Stopped: 1
     Images: 4
     Server Version: 24.0.7
     Storage Driver: overlay2
      Backing Filesystem: extfs
      Supports d_type: true
      Using metacopy: false
      Native Overlay Diff: true
      userxattr: false
     Logging Driver: json-file
     Cgroup Driver: systemd
     Cgroup Version: 2
     Plugins:
      Volume: local
      Network: bridge host ipvlan macvlan null overlay
      Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
     Swarm: inactive
     Runtimes: io.containerd.runc.v2 runc
     Default Runtime: runc
     Init Binary: docker-init
     containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
     runc version: v1.1.9-0-gccaecfc
     init version: de40ad0
     Security Options:
      apparmor
      seccomp
       Profile: builtin
      cgroupns
     Kernel Version: 5.15.0-88-generic
     Operating System: Ubuntu 22.04.3 LTS
     OSType: linux
     Architecture: x86_64
     CPUs: 10
     Total Memory: 58.86GiB
     Name: k8s-eu-1-master
     ID: bcb09cdd-7ee1-45e3-8d9e-1bab1620f01b
     Docker Root Dir: /var/lib/docker
     Debug Mode: false
     Experimental: false
     Insecure Registries:
      127.0.0.0/8
     Live Restore Enabled: false

- OS (e.g. from `/etc/os-release`): 

    PRETTY_NAME="Ubuntu 22.04.3 LTS"
    NAME="Ubuntu"
    VERSION_ID="22.04"
    VERSION="22.04.3 LTS (Jammy Jellyfish)"
    VERSION_CODENAME=jammy
    ID=ubuntu
    ID_LIKE=debian
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    UBUNTU_CODENAME=jammy

- Kubernetes version: (use `kubectl version`):
    
    root@k8s-eu-1-master:~# kubectl version
    Client Version: v1.28.2
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.25.3
    WARNING: version difference between client (1.28) and server (1.25) exceeds the supported minor version skew of +/-1

- Any proxies or other special environment settings?:

**Comment by BenTheElder** [comment]
we will need `kind export logs` after running create with `--retain`, then you can delete (there were/are instructions in the bug template text)

**Comment by enel1221** [comment]
Encountered this same issue when running Docker version 24.0.7, no issue when running version 24.0.6 or older.

**Comment by kishor7007** [comment]
I am getting this issue while creating multiple containers.
kind create cluster --config kind_config.yaml -n c1 -v 10 ==> c1 cluster created
kind create cluster --config kind_config.yaml -n c2 -v 10 ==> some times created
kind create cluster --config kind_config.yaml -n c3 -v 10 ==> always failing with this issue.


Creating cluster "c3" ...DEBUG: docker/images.go:58] Image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72 present locally ✓ Ensuring node image (kindest/node:v1.27.3) 🖼 ✗ Preparing nodes 📦 📦ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*\|detected cgroup v1" | docker logs c3-control-plane

docker logs c3-control-plane

observed following logs
----------------------
Set hostname to <c3-control-plane>.
Failed to create control group inotify object: Too many open files
Failed to allocate manager object: Too many open files
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...

**Comment by kishor7007** [comment]
Solved the problem with https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files

sudo sysctl fs.inotify.max_user_watches=524288
sudo sysctl fs.inotify.max_user_instances=512

**Comment by spit4520** [comment]
Hi all,

I am just writing to confirm this fixed my issue on Ubuntu 24.04.3 and I am running kind version 0.30.0

Love the project, thank you all for your tireless efforts :) hope this helps someone looking for the same issue
