### ISSUE TITLE
 certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by WeihanLi** [kubernetes-sigs/kind#3425]
Got `Unable to connect to the server: x509: certificate has expired or is not yet valid` error when execute `kubectl` commands, it seemed the kubernetes certificate had expired.

There's one issue similar to this, but I think it may not a docker issue, the docker commands work fine.

Is there any way to renew the certificate without recreating the cluster? Thanks very much

![image](https://github.com/kubernetes-sigs/kind/assets/7604648/278e250d-e1dc-49f4-821d-d994b1f38e47)

**Comment by BenTheElder** [comment]
Your `docker ps` output does not show a running kind cluster?

It would take a long time for the kind cluster certs to expire, IIRC the CA-roots have 10y and the other certs have 1y, I suspect that's not what happened here.

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/

**Comment by WeihanLi** [comment]
> Your docker ps output does not show a running kind cluster?

I hide some contains including the `kind-control-plane`

> It would take a long time for the kind cluster certs to expire, IIRC the CA-roots have 10y and the other certs have 1y, I suspect that's not what happened here.

Let me check deeply, thanks very much

**Comment by WeihanLi** [comment]
![image](https://github.com/kubernetes-sigs/kind/assets/7604648/ecf85877-4f08-40d4-90f2-8a726aef2534)

The cert expired, renewed by exec `kubeadm certs renew all` in `kind-control-plane` container, 

Then exit container and restart the container

And more, copied the `admin.conf` from container to default kubeconfig

```sh
sudo docker cp kind-control-plane:/etc/kubernetes/admin.conf $HOME/.kube/config
```

Finally update the serve address to the localhost instead, also update the port as container exposed

![image](https://github.com/kubernetes-sigs/kind/assets/7604648/48e01b92-f161-45dd-81c3-e5b8952e2a61)

![image](https://github.com/kubernetes-sigs/kind/assets/7604648/bd285fb4-7651-41fa-a03b-ce18aa50d433)

**Comment by BenTheElder** [comment]
How long have you had this cluster running? 🤯

**Comment by WeihanLi** [comment]
> How long have you had this cluster running? 🤯 

For a long time, over one year.

I use it in my vm to tryout k8s features, had no updates for a long long time.
