### ISSUE TITLE
Can we please get a newer version o kindest/node image?

### ISSUE THREAD

**Issue by HummingMind** [kubernetes-sigs/kind#3431]
Hello!
Can we please get a newer version of the kindest/node image? Specifically 1.28.4?

Thank you!

**Comment by BenTheElder** [comment]
We build them as needed / upon kind releases. You can build images at ~any version following: https://kind.sigs.k8s.io/docs/user/quick-start/#building-images

See: past issues with this question.

We expect to have a release soon around K8s v1.29

**Comment by HummingMind** [comment]
@BenTheElder 
I appreciate everything you guys do as an open source project. But the last release of kind was 5 months ago. 😢 And building images does not work on a Windows host. (at least it's not documented how to do this)

Sounds like it's pretty easy for you guys to build/publish, since you have the tool chain set up already. It would be really nice to have newer kind node-images between kind releases.

For now, I have to use minikube, since k8s 1.29 won't be out for another two weeks. I just prefer kind to minikube.

Thank you! Happy holidays!

**Comment by aojea** [comment]
you have to use a linux environment, run a VM or something , and then

```sh
# clone kubernetes
git clone --single-branch --branch v1.28.3 https://github.com/kubernetes/kubernetes 
# install kind 
curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
chmod +x ./kind
# build your image
kind build node-image ./kubernetes
```

**Comment by HummingMind** [comment]
@aojea thank you. I was able to buld it in WSL2. Didn't realize all the tools were already installed.
So I was able to get this to work.

Thank you guys!
