### ISSUE TITLE
didn't seem to work with `/kind/images` of node image

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kind#3432]
I did the documentation to pre-load the image tar into /kind/images before creating the cluster, but it didn't seem to work

https://github.com/kubernetes-sigs/kind/blob/a4bcc7b382d6f2d4fc8d83d6d8ce0c2d44ce2419/site/content/docs/design/node-image.md?plain=1#L25

https://github.com/kubernetes-sigs/kind/blob/a4bcc7b382d6f2d4fc8d83d6d8ce0c2d44ce2419/images/node/README.md?plain=1#L10

```
$ kind version
kind v0.20.0 go1.20.5 darwin/amd64
```

**Comment by BenTheElder** [comment]
> I did the documentation to pre-load the image tar into /kind/images before creating the cluster, but it didn't seem to work

That's a historical document, it doesn't work this way anymore and you shouldn't depend on the internals of node images 🙃 

We have an open issue / PR for implementing pre-loading as a supported API when building custom node images.

**Comment by wzshiming** [comment]
I see. Thank you for your clarification

/close
