### ISSUE TITLE
RFC: Refactor role specific logic

### ISSUE THREAD

**Issue by pablochacin** [kubernetes-sigs/kind#344]
I have been reviewing the code to understand what it would take to implement a new node role. The initial motivation is to implement a node type for exposing `NodePort` services addressing #99. However the proposal in RFC is generic and could help experimenting with other node roles in general.

Presently the knowledge about the different node roles scattered in many places of the code.  The main objective would be to encapsulate and isolate as much as possible. 

The overall idea is to introduce the type  `NodeRoleDescriptor` which defines the contract for new node roles.

```
// registered roles
var  NodeRoles [NodeRole]NodeRoleDescriptor = {}

// Describe the node role and supporting functions
type NodeRoleDescriptor struct {
        Role NodeRole
        // Order on which this role must be provisioned with respect of other roles
        ProvisionOrder int
        // Name of node roles this role depends on
        Dependencies NodeRole[]
        // Function to build nodes of this role
        Create NodeBuilder
        // Configuraton validator
        Validate NodeValidator
        // Min Replicas (0=optional)
        MinReplicas int
        // Max Replicas (0=unlimited)
        MaxReplicas int
}

// Creates a Node instance
type NodeBuilder func(name, image, clusterLabel string, mounts []cri.Mount) (node *Node, err error)

// Validates the node configration
type NodeValidator func(*Node) error
```
Each role implementation much register itself in the `NodeRoles` variable. 

```
//Register as NodeBuilder for ControlPlane Role
func init(){
   NodeRoles[ContolPlaneRole] = NodeRoleRescriptor {
                Role: ControlPlaneRole,
                ProvisioningOrder: 3,
                Create:  createControlPlaneNode,
                Validate: validateControlPlaneNode,
                MinInstances: 1,
                MaxInstances: 0,
        }
}
```
I have made a significant progress in this refactoring, limiting the knowledge to the existing roles to only two o three places in all the code (and only related to the `control-plane` and `external-load-balancer`). 

There's a significant amount of code which has been deleted, mostly related to having to deal with specific node roles in different parts of the code. But more importantly, adding new node roles should not require changing this core logic for building a cluster.

There's only an issue regarding circular dependencies between the `config` and the new `roles` package I introduced, which I'm afraid will require some other refactoring. Maybe move the new types to the `config`  package. 

The objective of this RFC is to gather some feedback about the idea before investing more time implementing and testing the changes. 

Your comments are welcome.

**Comment by BenTheElder** [comment]
Refactor the logic logic? +1
This particular form? -1

Being generic comes with a cost, and I don't think we should take on that cost for node types. How many more node types are we going to add?

We are moving to have `workers`, and `control planes` as the two reasonable user facing types, and then internal / implicit nodes (`load-balancer` and eventually `external-etcd`).  Adding maybe one or two more doesn't require a generic mechanism. 

I'm not terrifically thrilled with load balancer and external-etcd  / non-Kubernetes nodes as things kind needs to handle to begin with, but they're necessary for useful testing.

> But more importantly, adding new node roles should not require changing this core logic for building a cluster.

I do not think this is an important thing. Adding new roles _does_ change the logic for building a cluster, this is WAI.

**Comment by BenTheElder** [comment]
For this specific abstraction outlined:

 - `ProvisionOrder int`,  `Dependencies NodeRole[]` -- Provision order and interdependency is absolutely logic that belongs internal to `Create` and not anywhere else. Putting the provision order as an int in a role type is going to be complex to track, and will require refactoring for each new type anyhow. This will lead to "oops we had `ProvisionOrder: 1`  and a `ProvisionOrder: 2` , but now we want a `ProvisionOrder: 1.5`". This is more confusing to track than an explicit ordering encoded in `Create`
   - If we implement `Dependencies NodeRole[]` then we have to create a runtime solver to validate node dependency order! This is a big red flag. This should be written out at compile time.

 - `Validate NodeValidator` -- Validation should also be performed at the config level, and be versioned with the config.
   - `MinReplicas int` and `MaxReplicas int` -- these are a property of config validation and should happen there.

- `Create NodeBuilder` - again, why do we have a generic node builder? Node creation is internal to `nodes`, one small function per type with a helper, I don't think this warrants an abstraction, these types are concrete to cluster creation.

- `Role NodeRole` -- This is redundant data

**Comment by pablochacin** [comment]
> * Putting the provision order as an int in a role type is going to be complex to track, and will require refactoring for each new type anyhow. This will lead to "oops we had `ProvisionOrder: 1`  and a `ProvisionOrder: 2` , but now we want a `ProvisionOrder: 1.5`". This is more confusing to track than an explicit ordering encoded in `Crea`

I agree, I don't like it much. That's why I started playing with the idea of dependencies

>* If we implement `Dependencies NodeRole[]` then we have to create a runtime solver to validate node dependency order! This is a big red flag. This should be written out at compile time.

The check can be done at compile time as the dependencies references `NodeRoles` that must be defined somewhere. 

I had an initial idea of resolution that results in a provisioning ordering which is not more complex than an standard technical interview exercise.

>* `MinReplicas int` and `MaxReplicas int` -- these are a property of config validation and should happen there

The whole idea of refactoring was to move some logic from the generic config to a per-node validation. 
Making a refactoring and leaving things as they are makes not sense.

> * `Role NodeRole` -- This is redundant data
No it is not. this type is defined in the schema and I wanted to keep it. Also, helps in compile time checking. 

>We are moving to have `workers`, and `control planes` as the two reasonable user facing types, and then internal / implicit nodes (`load-balancer` and eventually `external-etcd`). Adding maybe one or two more doesn't require a generic mechanism.

The idea was to facilitate the 
Closing this issue. As there seems not to have any interest in changing current way of working,
