### ISSUE TITLE
document offline clusters

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#345]
xref: https://github.com/kubernetes-sigs/kind/pull/331#issuecomment-466668764

We should also think about how to start breaking up some of these things into seperate advanced guides to keep the quick start focused. unsure on this one, but https://github.com/kubernetes-sigs/kind/issues/303 will be a good one to split out

/kind documentation
/priority important-soon

**Comment by BenTheElder** [comment]
/help
this should be a new guide under /users, probably titled something like "Offline" or "Working Offline", similar to the "Private Registries" guide.

**Comment by BenTheElder** [comment]
see: `site/` for the documentation sources
/good-first-issue

**Comment by tao12345666333** [comment]
I will launch PR today.
