### ISSUE TITLE
Update KIND to latest patch level versions

### ISSUE THREAD

**Issue by madduci** [kubernetes-sigs/kind#3452]
Hello

would it be possible to update the KIND Docker Images to latest patch levels of Kubernetes?

According to this page (https://kubernetes.io/releases/), the following latest patch levels are available, but on Docker Hub only previous versions are present:

| Version  | Docker Hub   | Latest Patch Level  |   
|---|---|---|
| 1.29 | 1.29.0  | **1.29.0**  | 
| 1.28 | 1.28.0  | **1.28.4**  | 
| 1.27 | 1.27.3 | **1.27.8**  | 
| 1.26 | 1.26.6 | **1.26.11**  |

**Comment by liangyuanpeng** [comment]
Before the community decides to build the corresponding version, you can build the relevant version of kind node according to the document https://kind.sigs.k8s.io/docs/user/working-offline/#building-the-node-imagenode-image 

I have some related images built using github action, format is `{KIND_VERSION}-{K8S_VERSION}`:

 | k8s version    |  kind node version  |  
| --- | --- | 
v1.27.9 | v0.20.0-v1.27.9   |  
v1.28.5 | v0.20.0-v1.28.5   |

**Comment by madduci** [comment]
Hello,

Thanks for answering! I didn't know about it, I will look forward to build
the images myself.

Kind regards and have nice holidays

**Comment by BenTheElder** [comment]
You should be using images corresponding to the release notes (this is covered in the docs) or built yourself.

we will have another kind patch release with new images soon. Folks are on holiday.
