### ISSUE TITLE
The link to the original proposal requires permissions to be viewed

### ISSUE THREAD

**Issue by adriancuadrado** [kubernetes-sigs/kind#3457]
https://kind.sigs.k8s.io/docs/design/initial

![image](https://github.com/kubernetes-sigs/kind/assets/29214635/a23026e8-3979-4787-9841-bd419898d90a)

![image](https://github.com/kubernetes-sigs/kind/assets/29214635/32e21d62-883a-4247-8643-e4c424a7bc0c)

**Comment by BenTheElder** [comment]
You have to join the kubernetes mailing list to access docs, which is true for many docs in the project (which is why major docs are in git instead). As noted it is out of date anyhow.
