### ISSUE TITLE
How is each node scheduled in the kind (Kubernetes in Docker)?

### ISSUE THREAD

**Issue by minseok1335** [kubernetes-sigs/kind#3478]
Hello,

I hit a wall, so I’m writing this question.

I’m looking for how nodes operating in kind(Kubernetes in Docker) are scheduled, whether each node concurrently works or works with time multiplex.

Which point in the code I should check to get an answer to this question?

Thank you.

**Comment by aojea** [comment]
I don't fully understand the question or the intent?

kind creates the nodes with `docker run` commands , you can follow the code from here

https://github.com/kubernetes-sigs/kind/blob/40c81f187425254daf2bf84360a6257a278252df/pkg/cluster/internal/create/create.go#L100-L142

**Comment by minseok1335** [comment]
Sorry. I misunderstood KIND.

Now I understand properly and solved the problem.

Thank you!
