### ISSUE TITLE
Go modules error while building base image 

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes-sigs/kind#349]
Tried building the base image from the latest on master and I keep getting the following error:
```
$ ./kind build base-image --loglevel debug
INFO[12:45:52] Building base image in: /tmp/kind-base-image062118502/images/base 
INFO[12:45:52] Building entrypoint binary ...               
DEBU[12:45:52] Running: /usr/local/go/bin/go [go build -v -o /tmp/kind-base-image062118502/images/base/entrypoint/entrypoint /tmp/kind-base-image062118502/images/base/entrypoint/main.go] 
go: cannot use modules with build cache disabled
ERRO[12:45:52] Entrypoint build Failed! exit status 1       
Error: build failed: exit status 1
```

Had to do `export GO111MODULE=on` and run `hack/update-deps.sh` to build kind.
Running on ubuntu 18.04, Go version 1.11.5.

**Comment by BenTheElder** [comment]
Where is your checkout located and do you have a gopath? You should not need to do that unless it's outside of gopath.

**Comment by alejandrox1** [comment]
I'm trying to build from `$GOPATH/sigs.k8s.io/kind`. Tried building the base image with `GO111MODULE` on and off.

**Comment by neolit123** [comment]
@alejandrox1 try with latest master
i sent patch for that yesterday.

**Comment by alejandrox1** [comment]
Thank you @neolit123 !
Guess I didn't actually have the latest, missing just that PR of yours.
/close
