### ISSUE TITLE
kind load docker-image fails with error error=\"wrong diff id calculated on extraction on docker version 25

### ISSUE THREAD

**Issue by gpooleoneiro** [kubernetes-sigs/kind#3490]
Kind load docker-image command fails with the following docker error on Docker version 25

error=\"wrong diff id calculated on extraction

Full error below

kind load docker-image [docker.io/library/keycloak_dev:d3b0f69b87c0b7f57b3487e6629d12e58528ed95a79f7b29d015b7174bebfd93](http://docker.io/library/keycloak_dev:d3b0f69b87c0b7f57b3487e6629d12e58528ed95a79f7b29d015b7174bebfd93)
Image: "docker.io/library/keycloak_dev:d3b0f69b87c0b7f57b3487e6629d12e58528ed95a79f7b29d015b7174bebfd93" with ID "sha256:d3b0f69b87c0b7f57b3487e6629d12e58528ed95a79f7b29d015b7174bebfd93" not yet present on node "kind-control-plane", loading...
ERROR: failed to load image: command "docker exec --privileged -i kind-control-plane ctr --namespace=k8s.io images import --all-platforms --digests --snapshotter=overlayfs -" failed with error: exit status 1
Command Output: unpacking docker.io/library/keycloak_dev:d3b0f69b87c0b7f57b3487e6629d12e58528ed95a79f7b29d015b7174bebfd93 (sha256:a9c1284362d7d64c807a9875232f576025ee3f52d8922050fec8d18e4d1c89ab)...time="2024-01-24T15:26:17Z" level=info msg="apply failure, attempting cleanup" error="wrong diff id calculated on extraction \"sha256:4ac1c61fddeb3e910c192f1f7dd0b8d8e4146d80ead804b3f259b61100830d09\"" key="extract-419216328-UV1f sha256:80a3f0b229f61dfcdaee710c74201f383ef99e1dde651fc5c2a53b3aefc9b095"
ctr: wrong diff id calculated on extraction "sha256:4ac1c61fddeb3e910c192f1f7dd0b8d8e4146d80ead804b3f259b61100830d09"

This does not occur when loading docker images from tar archive on version 25 though.

I was building my images using skaffold build/run commands - skaffold version v2.10.0

**Comment by stmcginnis** [comment]
I believe this is an issue with Docker 25. You will need to downgrade for now, otherwise wait for the bugfix release to come out.

https://github.com/kubernetes-sigs/kind/issues/3488#issuecomment-1907813348

**Comment by BenTheElder** [comment]
ref: https://github.com/moby/moby/pull/47161

**Comment by BenTheElder** [comment]
There are other issues with kind and v25 (https://github.com/kubernetes-sigs/kind/pull/3487), but the error in this issue is just a bug in docker. v25.0.1 contains a fix.

**Comment by BenTheElder** [comment]
/triage duplicate
pinned https://github.com/kubernetes-sigs/kind/issues/3488 for visibility
