### ISSUE TITLE
docs(quick-start): Broken kind-example-config link

### ISSUE THREAD

**Issue by lachie83** [kubernetes-sigs/kind#350]
The link to the kind-example-config is broken here - https://kind.sigs.k8s.io/docs/user/quick-start/#configuring-your-kind-cluster.

**Comment by lachie83** [comment]
Here is the source - https://github.com/kubernetes-sigs/kind/blob/master/site/content/docs/user/quick-start.md#configuring-your-kind-cluster

**Comment by BenTheElder** [comment]
Thanks @tao12345666333!
