### ISSUE TITLE
Interaction between kind/kubeadm and new metallb versions breaks single-node metallb usage

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kind#3506]
metallb issue: https://github.com/metallb/metallb/issues/2274

As of 0.14, metallb respects the `node.kubernetes.io/exclude-from-external-load-balancers` and will not make announcements for these nodes.

As of k8s 1.21:

> Kubeadm: apply the "node.kubernetes.io/exclude-from-external-load-balancers" label on control plane nodes during "init", "join" and "upgrade" to preserve backwards compatibility with the lagacy LB mode where nodes labeled as "master" where excluded. To opt-out you can remove the label from a node. See #97543 and the linked KEP for more details. ([#98269](https://github.com/kubernetes/kubernetes/pull/98269), [@neolit123](https://github.com/neolit123)) [SIG Cluster Lifecycle]

As a result, this documentation https://kind.sigs.k8s.io/docs/user/loadbalancer/ does not work on single-node clusters with recent metallb versions.

Possible paths forward:
* Change metallb
* Document to remove the label from the node
* Default to removing the label from the node

**Comment by BenTheElder** [comment]
Ouch, I didn't expect this to still be unhandled.

We should not change the labeling behavior in kind, most software will have already switched since 1.21 is pretty old now and changing it again will just confuse everyone.

Most likely we should fix metallb, if they're unwilling to accept this then we can fallback to just documenting the workaround.

**Comment by BenTheElder** [comment]
[prior comment deleted, I skimmed this => confused with another kubeadm label change around the same time frame]

Auto-removing this for single-node clusters seems reasonable given we auto-remove the comparable general scheduling taint, in the meantime we can document the workaround.

**Comment by BenTheElder** [comment]
v0.22.0 is out with this fix, thanks @howardjohn !
