### ISSUE TITLE
Improve kind as a library for loading images

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes-sigs/kind#351]
kind's load command wraps the `docker save` command to save a container image as a tar archive and 
https://github.com/kubernetes-sigs/kind/blob/2c5195712b0b0edbe06d5ca5e777ab97d11cb029/cmd/kind/load/docker-image/docker-image.go#L103-L122

The `loadImage` function provides a good API for using kind as a library, however, this leaves the user to "docker save" any container image. My proposal is to decouple saving-image from the runE command so that it can be used as:

```go
import (
    "sigs.k8s.io/kind/pkg/cluster"
    "sigs.k8s.io/kind/load/cmd/kind/load"
)

func main() {
     ctx := cluster.NewContext(clusterName)                                     
                                                                                
    // Create a kind cluster and all that...                                            
                                                                                
    nodes, _ := ctx.ListNodes()
    // "docker save" and "docker load".
    load.SaveImage("image:tag", nodes)
```

Also, the code for `loadImage` is replicated in [docker-image](https://github.com/kubernetes-sigs/kind/blob/master/cmd/kind/load/docker-image/docker-image.go#L125) and [image-archive](https://github.com/kubernetes-sigs/kind/blob/master/cmd/kind/load/image-archive/image-archive.go#L109).
Would it be good to move the code somewhere like `sigs.k8s.io/kind/cmd/kind/load/utils` (please suggest a name that is not "utils").

/assign
cc @BenTheElder @neolit123

**Comment by BenTheElder** [comment]
imo this should go in pkg/ (see comments on the PR) 👍 

thanks for looking at this

**Comment by BenTheElder** [comment]
This should be in pretty good shape after #461
