### ISSUE TITLE
kind create cluster fails on arch linux

### ISSUE THREAD

**Issue by samuelzokovich** [kubernetes-sigs/kind#3514]
`[zoko@archlinux ~]$ kind create cluster
enabling experimental podman provider
Creating cluster "kind" ...
ERROR: failed to create cluster: failed to ensure podman network: command "podman network create -d=bridge --ipv6 --subnet fc00:f853:ccd:e793::/64 kind" failed with error: exit status 125
Command Output: Error: subnet fc00:f853:ccd:e793::/64 is already used on the host or by another config`

**Comment by aojea** [comment]
this was fixed here AFAIK https://github.com/kubernetes-sigs/kind/pull/2910, please try with a version of kind that contains that fix

**Comment by kundan2707** [comment]
@samuelzokovich  i tried with latest kind version and its working.
Are you able to create ?

**Comment by kundan2707** [comment]
@samuelzokovich 
can yuou close it if no further issue ?
