### ISSUE TITLE
kubectl example not working, what to do next?

### ISSUE THREAD

**Issue by ebengt** [kubernetes-sigs/kind#3515]
Greetings,
I have installed kind v0.21.0 go1.20.13 linux/amd64
on my laptop, Linux nb029-HP-EliteBook-840-G3 6.5.0-17-generic #17-Ubuntu SMP PREEMPT_DYNAMIC Thu Jan 11 14:01:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Docker is version 24.0.5

I have no kubeconfig, and do
kind create cluster
This gives me a cluster.
kind get clusters (and nodes) work.
But
```
$ kubectl cluster-info --context kind-kind
E0209 16:35:44.977787   39140 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:36725/api?timeout=32s": tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```
I have tried kubectl 1.29, 1.28 and 1.27
I have deleted and re-created the cluster.
openssl can decode the certificates in .kube/config, but I do not know how to check if they are correct.

**Comment by BenTheElder** [comment]
Is it possible you have a proxy interfering?

**Comment by ebengt** [comment]
Is there a way to find out?
This is a new VM with Fedora 39. Freshly stared to test Kubernetes.

**Comment by BenTheElder** [comment]
It would be a locally configured proxy, check e.g. `env`, though if you're not sure there probably isn't one.

you can also run `kind get kubeconfig` and compare to the kubeconfig being used by your kubectl client (`kubectl config view`)

**Comment by ebengt** [comment]
After adding `--raw` to `kubectl config view`, I saved both commands to a file (each) and did:
```
$ diff /tmp/?file
20d19
<
```
They are very much alike. I would think this means there is nothing wrong with the config file.
However, I still get `tls failed to verify`.

`$ env | grep -i PROX`
shows nothing.

What kind of network issues would result in this problem? I am trying to access 127.0.0.1 on the **lo** interface

**Comment by BenTheElder** [comment]
Docker implements this part of the networking, we just ask docker "forward 127.0.0.1:randomPort to the api server port on the node container". (`docker run -p 127.0.0.1:$port:container::6443`), it varies by docker installation.

**Comment by BenTheElder** [comment]
You could also try something like `docker exec $node kubectl get po -A` to test the api-server from within the cluster, to narrow down where things are not working.

**Comment by ebengt** [comment]
$ docker exec cdf1e96fef2c kubectl get po -A
NAMESPACE            NAME                                         READY   STATUS    RESTARTS      AGE
kube-system          coredns-5d78c9869d-95pbl                     1/1     Running   2 (92s ago)   5d23h
kube-system          coredns-5d78c9869d-zk2lz                     1/1     Running   2 (92s ago)   5d23h
kube-system          etcd-kind-control-plane                      1/1     Running   2 (92s ago)   5d23h
kube-system          kindnet-gzjm4                                1/1     Running   2 (92s ago)   5d23h
kube-system          kube-apiserver-kind-control-plane            1/1     Running   2 (92s ago)   5d23h
kube-system          kube-controller-manager-kind-control-plane   1/1     Running   2 (92s ago)   5d23h
kube-system          kube-proxy-xrfw6                             1/1     Running   2 (92s ago)   5d23h
kube-system          kube-scheduler-kind-control-plane            1/1     Running   2 (92s ago)   5d23h
local-path-storage   local-path-provisioner-6bc4bddd6b-2mkw9      1/1     Running   4 (47s ago)   5d23h

**Comment by BenTheElder** [comment]
So the api server works and this confirms that it's a networking issue between the host and the docker container.

Can you access the forwarded ports of any other containers?

are you sure no firewalls are running?

**Comment by ebengt** [comment]
I know very little about firewalls, and installed a graphical interface. it says the firewall is disabled.
Is there a beter way to check?

**Comment by ebengt** [comment]
I have tried
`docker run -d -p 8080:80 nginex`
With that I can load **http://localhopst:8080** in Firefox.

Perhaps of importance. I can not stop nginex. `docker stop xxx `only timeout with insufficient privelidge.
I reboot my laptop everytime I need to get rid of nginex

**Comment by BenTheElder** [comment]
> it says the firewall is disabled.
Is there a beter way to check?

(Un)fortunately linux networking is pretty flexible so this isn't straightforward to outline.

**Comment by ebengt** [comment]
I will, when work permits, replace docker with podman and see if kind/kubectl improve.

**Comment by ebengt** [comment]
I installed podman (I use it instead of docker on Fedora 39, together with kind). I had to add to the command line (all additions suggested by kind itself) but podman also fail. Is this easier to solve than the docker problem?
```
$  KIND_EXPERIMENTAL_PROVIDER=podman systemd-run --scope --user kind create cluster
Running scope as unit: run-r1c8cbd01ab504f53b6fd5b6f48c72acd.scope
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.29.1) 🖼
 ✗ Preparing nodes 📦  
Deleted nodes: ["kind-control-plane"]
ERROR: failed to create cluster: command "podman run --name kind-control-plane --hostname kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --tmpfs /tmp --tmpfs /run --volume 0eb6d913d3e4919dbfdf501a4f5f62b460f29136416a230b760067d2e331d5a7:/var:suid,exec,dev --volume /lib/modules:/lib/modules:ro -e KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER --detach --tty --net kind --label io.x-k8s.kind.cluster=kind -e container=podman --cgroupns=private --device /dev/fuse --publish=127.0.0.1:42011:6443/tcp -e KUBECONFIG=/etc/kubernetes/admin.conf [docker.io/kindest/node@sha256:a0cc28af37cf39b019e2b448c54d1a3f789de32536cb5a5db61a49623e527144](http://docker.io/kindest/node@sha256:a0cc28af37cf39b019e2b448c54d1a3f789de32536cb5a5db61a49623e527144)" failed with error: exit status 126
Command Output: Error: OCI runtime error: crun: chmod `run/shm`: Operation not supported
```

**Comment by BenTheElder** [comment]
If you're running rootless see: https://kind.sigs.k8s.io/docs/user/rootless/

I'm not sure what your docker issue is, and fixing docker installs is somewhat out of scope for the project.

**Comment by ebengt** [comment]
Yes, kind can not solve docker problems. Closing the issue.

**Comment by VictorioBerra** [comment]
Having exact same issue on Mint 22.04

`kubectl config view --raw` and `kind get kubeconfig` matches.

`docker exec be616057ecbb kubectl get po -A` works.

`docker ps` shows the container and port.

```
docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED       STATUS       PORTS                       NAMES
be616057ecbb   kindest/node:v1.33.1   "/usr/local/bin/entr…"   6 hours ago   Up 6 hours   127.0.0.1:38617->6443/tcp   kind-control-plane
```

but this fails:

```
$ kubectl get node --kubeconfig ~/.kube/config 
E0801 20:22:44.777863   27087 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:38617/api?timeout=32s\": net/http: TLS handshake timeout"
```

I do not have issues getting to other containers in Docker when I run them.

This also works:

```
$ telnet 127.0.0.1 38617
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'
```

**Comment by Goend** [comment]
Sometimes, you need to check whether the Docker network bridge or the subnet assigned to your kind cluster conflicts with your local network routes. If there is a conflict, simply remove the conflicting route from your local network configuration.

example:
```
➜  kubernetes git:(v1.32.2-es) docker network inspect b27af0f59738            
[
    {
        "Name": "kind",
        "Id": "b27af0f59738b58737be6b01892025f08f3697dc060a3ae85b76460b02919f41",
        "Created": "2023-02-07T17:29:45.457115087+08:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                },
                {
                    "Subnet": "fc00:f853:ccd:e793::/64",
                    "Gateway": "fc00:f853:ccd:e793::1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "c03758c1f6f70b6e4fb6c37585c6d1ec7c3f5fb1991fda875713e1990cc22126": {
                "Name": "test-control-plane",
                "EndpointID": "b93420261770c2adfd9cce427b631dfebba5ad4a8e1530f1882ae89034fda90f",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": "fc00:f853:ccd:e793::2/64"
            }
        },
        "Options": {
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]

```
```
ip r del 172.18.0.0/24 via 10.9.0.1 dev tun0 proto static metric 50
```
then,it;s ok
```
➜ kubernetes git:(v1.32.2-es)   kubectl --kubeconfig /root/.kube/kind_config  get pod
NAME                   READY   STATUS    RESTARTS   AGE
test-958c74695-87wkb   1/1     Running   0          7m23s
```
