### ISSUE TITLE
Increase log file size or disable log rotation on `kind` cluster

### ISSUE THREAD

**Issue by NikitaSkrynnik** [kubernetes-sigs/kind#3538]
Hello! Is it possible to increase log file size or disable log rotation at all on `kind` cluster?

**Comment by aojea** [comment]
>  Hello! Is it possible to increase log file size or disable log rotation at all on kind cluster?

what do you mean exactly?

you can pass configuration options to the different kubernetes components to modify its behavior https://kind.sigs.k8s.io/docs/user/configuration/#cluster-wide-options

/close
