### ISSUE TITLE
handle lowercase _proxy variables

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#354]
see previous discussion: https://github.com/kubernetes-sigs/kind/issues/306

**Comment by BenTheElder** [comment]
This should be a very easy change, see [the nodes package](https://github.com/kubernetes-sigs/kind/blob/master/pkg/cluster/nodes/node.go), `NeedProxy` and `SetProxy` methods, Ideally these should be refactored to:
- move the proxy environment variable strings & detection into the common function
  - return a private struct with proxy metadata
  - make both `NeedProxy` and `SetProxy` use this method
- support lowercase versions of `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`

There will need to be a priority between these values, arbitrarily I will say uppercase should be preferred over lowercase, since uppercase variables are common practice for exported environment variables.


/good-first-issue

**Comment by aojea** [comment]
@BenTheElder PR was merged, can we close it?
