### ISSUE TITLE
how we can access application in local network which is deploy in KinD cluster.

### ISSUE THREAD

**Issue by Sagarbud** [kubernetes-sigs/kind#3542]
Hello,

We have installed and configured KinD in Linux VM. The Linux VM is hosted in our local infrastructure. Also, we have deployed application in KinD cluster. We have exposed the application service as NodePort and able to access the application inside the Linux VM using Worker nodes IP address. But We're unable to access the application from our local network.

We have a Sophos Firewall to mange our local infrastructure. How we can allow or make some routing in firewall to allow POD IP range, service IP range and Worker node IP range to access the application in our local network which is deployed in KinD cluster.

Thank you in advance...

**Comment by aojea** [comment]
you may  use port forward or any solution that allows to circumvent this problems https://goteleport.com/docs/kubernetes-access/introduction/ , but you need to expose the apiserver endpoint on the VM and allow acccess to it https://kind.sigs.k8s.io/docs/user/configuration/#networking

**Comment by Sagarbud** [comment]
Hello @aojea 

Thank you for your response. 

I think previously i am unable to explain my Kind cluster scenario. Let me clarify again.

I have configured KinD cluster in Linux VM. Linux VM is hosted in Hyper-V. Then, we have deploy nginx in KinD cluster and able to access it in Linux VM with KinD's node IP address. Ex (172.18.0.4) but not able to access it using Linux VM IP address (10.0.1.36)from my workstation.

Worker node IP range: 172.18.0.0/16
 POD IP range: 10.244.0.0/16
Service IP range: 10.96.0.0/16

The above IP addresses range are virtual IP which is created by KinD cluster. 

Linux VM IP: 10.0.1.36
Hyper-v IP: 10.0.1.23

How we can access the application using Linux VM IP address(10.0.1.36)? 

For better understanding, I have attached screen shot with the response.
![MicrosoftTeams-image](https://github.com/kubernetes-sigs/kind/assets/115458338/c301b31e-4cb6-45cc-bfa2-c725c49d2cd3)

Thank you in advance.

**Comment by stmcginnis** [comment]
Your drawing is missing, or skipping over, Docker and the Docker networking in that picture. You will need to using some sort of ingress: https://kind.sigs.k8s.io/docs/user/ingress/

But for your scenario, maybe kind isn't the right tool for the use case. You might be better off just using kubeadm to deploy a cluster in your vm.
