### ISSUE TITLE
I hope to add the operation of exposing a range of IP in Extra Port Mappings

### ISSUE THREAD

**Issue by gitlayzer** [kubernetes-sigs/kind#3551]
What I hope is that a segment of IP can be added to Extra Port Mappings for exposure, so that there will be better support for K8S's NodePort.

**Comment by BenTheElder** [comment]
You can assign ports to nodeports and avoid depending on asking docker to forward *the entire range*.

It would not be reliable to attempt to reserve all of these ports on the host.
