### ISSUE TITLE
bridge network is not working for metallb   

### ISSUE THREAD

**Issue by JCzz** [kubernetes-sigs/kind#3556]
**What happened**:
MacOs M1
Docker Desktop

1. I have create a cluster and it gets default "bridge" docker network.
2. I have "kubectl apply"'ed metallb with:

```
SUBNET=$(docker network inspect --format='{{(index .IPAM.Config 0).Subnet}}' kind)

SUBNET_CONFIG=$(prips "$SUBNET" | sed -n '1p;$p' | xargs -n 2 | awk '{ print $1"-"$2 }')

echo "$SUBNET_CONFIG"

cat <<EOF | kubectl apply -f -
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example
  namespace: metallb-system
spec:
  addresses:
  - $SUBNET_CONFIG
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
EOF
```

I would have expected the bridge(switch) network to be reachable from the host into Docker Desktop(VM):
```
kubectl get svc
NAME          TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
foo-service   LoadBalancer   10.96.83.72   172.18.0.0    5678:32161/TCP   3m55s
kubernetes    ClusterIP      10.96.0.1     <none>        443/TCP          2d11h
```

kind version
kind v0.20.0 go1.20.5 darwin/arm64

docker info
Client:
 Version:    25.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/christian/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     /Users/christian/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /Users/christian/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/christian/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     /Users/christian/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/christian/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     /Users/christian/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/christian/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     /Users/christian/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/christian/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/christian/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 4
  Running: 2
  Paused: 0
  Stopped: 2
 Images: 58
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.755GiB
 Name: docker-desktop
 ID: 3aa65111-0b64-4c72-95d8-e46c2a06df9a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  192.170.1.170:5000
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile

kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
WARNING: version difference between client (1.29) and server (1.27) exceeds the supported minor version skew of +/-1

**Comment by aojea** [comment]
it is explained in the docs that, because of how it is implemented, it is not reachable https://kind.sigs.k8s.io/docs/user/loadbalancer/ ,

**Comment by MeCode4Food** [comment]
Please, let me know where in the docs that explains why this does not work, as the link you provided https://kind.sigs.k8s.io/docs/user/loadbalancer/  does not have any such explanation

**Comment by MeCode4Food** [comment]
Ah, so it is an OS level issue. I saw some notes on that here: https://github.com/kubernetes-sigs/cloud-provider-kind?tab=readme-ov-file#mac-and-windows-support
