### ISSUE TITLE
KIND_EXPERIMENTAL_PROVIDER=nerdctl  is not supported with kind v0.22.0

### ISSUE THREAD

**Issue by hillbun** [kubernetes-sigs/kind#3559]
kind version
kind v0.22.0 go1.20.13 linux/amd64

export KIND_EXPERIMENTAL_PROVIDER=nerdctl
kind create cluster --name kind-4
ignoring unknown value "nerdctl" for KIND_EXPERIMENTAL_PROVIDER

**Comment by stmcginnis** [comment]
That is correct, nerdctl is not supported in kind v0.22.0.

You will need to wait for the v0.23.0 release where [nerdctl support is being added](https://github.com/kubernetes-sigs/kind/pull/3429).

/close

**Comment by BenTheElder** [comment]
Right, there are still PRs in flight to iron out nerdctl support, e.g. https://github.com/kubernetes-sigs/kind/pull/3557 just merged
