### ISSUE TITLE
How to name nodes from different groups from a list of predefined named

### ISSUE THREAD

**Issue by torsina** [kubernetes-sigs/kind#3562]
Hi, I want to name my control plane nodes and worker nodes with specific naming schemes each, and I really don't know which way I can make this work. I know of the `--node-name` flag for `kubeadm` and `--hostname-override` for `kubelet`, but do not know how to translate this into naming each node from an item from those 2 lists. I saw the [`kubeadm` config patches](https://kind.sigs.k8s.io/docs/user/configuration/#kubeadm-config-patches) in the kind docs, but I still do not know how to put all those bricks together to do what I want, could someone help me with this please ? 

concrete examples not with the names I want to go with:

so for control-plane nodes I would have a list: 
+ Alpha 
+ Beta 
+ Charlie

for master node: 
+ Zeta 
+ Carbon 
+ Foo

for worker nodes: 
+ Alice 
+ Peter 
+ Lilith

The names would be picked either at random or from top to bottom depending on the feasability of this.

**Comment by BenTheElder** [comment]
We don't support this, you should not depend on node names, it's not portable. Labels and taints _may_ be somewhat portable. Labels are supported.
