### ISSUE TITLE
Kind Support for 1.30 kubernetes

### ISSUE THREAD

**Issue by vasireddy99** [kubernetes-sigs/kind#3589]
**What would you like to be added**:

[Kuberntes 1.30](https://www.kubernetes.dev/resources/release/) is released n April-2024, This issue is to request that the Kind project adds support for creating and managing Kubernetes 1.30 clusters.

Having Kind support for the latest Kubernetes release will be beneficial for development and testing purposes, allowing users to easily create and experiment with the latest features and enhancements introduced in Kubernetes 1.30.

Ref [issue for otel-operator](https://github.com/open-telemetry/opentelemetry-operator/issues/2881)

**Comment by BenTheElder** [comment]
It's supported. You will need to build your own image until we publish new images but kind works with the latest unreleased code and we have docs for building an image.

See past issues and currently open issues discussing image management for pre-published images.

**Comment by mathieu-benoit** [comment]
+1, this would be very convenient to have a most recent version that this one dated for 4 months ago: https://hub.docker.com/r/kindest/node/tags?page=&page_size=&ordering=&name=1.30, and without requiring everyone "building their own node image".

**Comment by BenTheElder** [comment]
Note: 4 Months is the length of a Kubernetes release cycle and approximately our target for kind release cycles (which have some variation due to availability, critical bug fix releases, etc)

**Comment by BenTheElder** [comment]
> without requiring everyone "building their own node image".

Others are also free to share their own images, or contribute to outlining plans for future image management (see open issues as mentioned above). There's some things to consider and we've had very little participation here.

As mentioned above, we do plan to do a release soon and that will have a 1.30 image.

**Comment by mathieu-benoit** [comment]
> As mentioned above, we do plan to do a release soon and that will have a 1.30 image.

Thanks, much appreciated!

**Comment by ssurovich** [comment]
@mathieu-benoit - I needed 1.30 to update our Kubernetes book, so I built a 1.30 from the K8s source.  The KinD team has made making a node-image really easy, just need the K8s source and run the kind build command.  I have a working image if you want to use it in my Docker Hub, just use the image surovich/kindest:v1.30

When you deploy the KinD cluster, just use the image option to use my 1.30 image:

kind create cluster --name cluster01 --image surovich/node:v1.30

**Comment by BenTheElder** [comment]
Longer than expected but now published in https://github.com/kubernetes-sigs/kind/releases/tag/v0.23.0

There's some ongoing discussions again about future releases.
