### ISSUE TITLE
The node NotReady

### ISSUE THREAD

**Issue by txbxxx** [kubernetes-sigs/kind#3603]
I encountered an issue while setting up a cluster using Kind. After the setup was completed, I noticed that my node remained in a NotReady state. Initially, I suspected it was due to Taints, so I attempted to remove them. However, something peculiar happened: the taints reappeared on their own, and the node persisted in being NotReady. Subsequently, I altered the taint to PreferNoSchedule, but to my surprise, an additional taint was automatically added. 

docker-info:
Client: Docker Engine - Community
 Version:    26.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 4
  Running: 2
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 25.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.146.1-microsoft-standard-WSL2
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 11.66GiB
 Name: Tc-Server
 ID: e643db02-803b-454d-98d0-e56b3195cef3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

kind-version:  kind v0.22.0 go1.21.10 linux/amd64

system:
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

erros:
NAME                       STATUS     ROLES           AGE   VERSION
clusterone-control-plane   NotReady   control-plane   22h   v1.28.7
clusterone-worker          NotReady   <none>          22h   v1.28.7

Name:               clusterone-control-plane
Roles:              control-plane
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=clusterone-control-plane
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=
                    node.kubernetes.io/exclude-from-external-load-balancers=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: unix:///run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 08 May 2024 21:05:54 +0800
Taints:             node.kubernetes.io/not-ready:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  clusterone-control-plane
  AcquireTime:     <unset>
  RenewTime:       Thu, 09 May 2024 19:55:50 +0800
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 09 May 2024 19:55:40 +0800   Wed, 08 May 2024 21:05:52 +0800   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 09 May 2024 19:55:40 +0800   Wed, 08 May 2024 21:05:52 +0800   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 09 May 2024 19:55:40 +0800   Wed, 08 May 2024 21:05:52 +0800   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Thu, 09 May 2024 19:55:40 +0800   Wed, 08 May 2024 21:05:52 +0800   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
Addresses:
  InternalIP:  172.18.0.2
  Hostname:    clusterone-control-plane
Capacity:
  cpu:                12
  ephemeral-storage:  1055762868Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             12225784Ki
  pods:               110
Allocatable:
  cpu:                12
  ephemeral-storage:  1055762868Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             12225784Ki
  pods:               110
System Info:
  Machine ID:                 6d13ccdea64045cf8b9946324fdd9b52
  System UUID:                6d13ccdea64045cf8b9946324fdd9b52
  Boot ID:                    652f4887-79c9-443e-9d4a-0987a04cfe45
  Kernel Version:             5.15.146.1-microsoft-standard-WSL2
  OS Image:                   Debian GNU/Linux 12 (bookworm)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.7.13
  Kubelet Version:            v1.28.7
  Kube-Proxy Version:         v1.28.7
PodCIDR:                      10.10.0.0/24
PodCIDRs:                     10.10.0.0/24
ProviderID:                   kind://docker/clusterone/clusterone-control-plane
Non-terminated Pods:          (5 in total)
  Namespace                   Name                                                CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                                ------------  ----------  ---------------  -------------  ---
  kube-system                 etcd-clusterone-control-plane                       100m (0%)     0 (0%)      100Mi (0%)       0 (0%)         92m
  kube-system                 kube-apiserver-clusterone-control-plane             250m (2%)     0 (0%)      0 (0%)           0 (0%)         92m
  kube-system                 kube-controller-manager-clusterone-control-plane    200m (1%)     0 (0%)      0 (0%)           0 (0%)         22h
  kube-system                 kube-proxy-tmph5                                    0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  kube-system                 kube-scheduler-clusterone-control-plane             100m (0%)     0 (0%)      0 (0%)           0 (0%)         22h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                650m (5%)   0 (0%)
  memory             100Mi (0%)  0 (0%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
Events:              <none>

Name:               clusterone-worker
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=clusterone-worker
                    kubernetes.io/os=linux
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: unix:///run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 08 May 2024 21:06:13 +0800
Taints:             node.kubernetes.io/not-ready:NoSchedule
                    node.kubernetes.io/not-ready:PreferNoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  clusterone-worker
  AcquireTime:     <unset>
  RenewTime:       Thu, 09 May 2024 19:55:57 +0800
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 09 May 2024 19:55:40 +0800   Wed, 08 May 2024 21:06:13 +0800   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 09 May 2024 19:55:40 +0800   Wed, 08 May 2024 21:06:13 +0800   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 09 May 2024 19:55:40 +0800   Wed, 08 May 2024 21:06:13 +0800   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Thu, 09 May 2024 19:55:40 +0800   Wed, 08 May 2024 21:06:13 +0800   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
Addresses:
  InternalIP:  172.18.0.3
  Hostname:    clusterone-worker
Capacity:
  cpu:                12
  ephemeral-storage:  1055762868Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             12225784Ki
  pods:               110
Allocatable:
  cpu:                12
  ephemeral-storage:  1055762868Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             12225784Ki
  pods:               110
System Info:
  Machine ID:                 de7f987f2cf143389267d6baee0f1a69
  System UUID:                de7f987f2cf143389267d6baee0f1a69
  Boot ID:                    652f4887-79c9-443e-9d4a-0987a04cfe45
  Kernel Version:             5.15.146.1-microsoft-standard-WSL2
  OS Image:                   Debian GNU/Linux 12 (bookworm)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.7.13
  Kubelet Version:            v1.28.7
  Kube-Proxy Version:         v1.28.7
ProviderID:                   kind://docker/clusterone/clusterone-worker
Non-terminated Pods:          (5 in total)
  Namespace                   Name                                       CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                       ------------  ----------  ---------------  -------------  ---
  default                     nginx                                      0 (0%)        0 (0%)      0 (0%)           0 (0%)         40m
  kube-system                 coredns-5dd5756b68-l5thg                   100m (0%)     0 (0%)      70Mi (0%)        170Mi (1%)     61m
  kube-system                 coredns-5dd5756b68-mlgnv                   100m (0%)     0 (0%)      70Mi (0%)        170Mi (1%)     61m
  kube-system                 kube-proxy-pqrwr                           0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  local-path-storage          local-path-provisioner-7577fdbbfb-ffhgf    0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
Allocated resources:

**Comment by aojea** [comment]
> KubeletNotReady container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized

how are you creating the cluster? are you adding some special parameters?

**Comment by txbxxx** [comment]
> > KubeletNotReady container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
> 
> how are you creating the cluster? are you adding some special parameters?

apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: clusterone
networking:
  podSubnet: 10.10.0.0/24
  serviceSubnet: 10.20.0.0/24
  disableDefaultCNI: true
nodes:
- role: control-plane
  image: kindest/node:v1.28.7@sha256:9bc6c451a289cf96ad0bbaf33d416901de6fd632415b076ab05f5fa7e4f65c58
  extraMounts:
  - hostPath: /opt/masterOne
    containerPath: /file
    readOnly: false
  extraPortMappings:
  - containerPort: 22
    hostPort: 31022
    protocol: TCP
- role: worker
  image: kindest/node:v1.28.7@sha256:9bc6c451a289cf96ad0bbaf33d416901de6fd632415b076ab05f5fa7e4f65c58
  extraMounts:
  - hostPath: /opt/nodeOne
    containerPath: /file
    readOnly: false
  extraPortMappings:
  - containerPort: 22
    hostPort: 31023
    protocol: TCP

**Comment by txbxxx** [comment]
> > KubeletNotReady container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
> 
> how are you creating the cluster? are you adding some special parameters?

I'm sorry. I think I solved it. I think it was CNI,

**Comment by aojea** [comment]
> disableDefaultCNI: true

yep

/close
