### ISSUE TITLE
Some problems of foreign visits

### ISSUE THREAD

**Issue by txbxxx** [kubernetes-sigs/kind#3616]
After setting up the kubernetes server using wsl and kind, I have a mysql service that needs to be opened to the outside world. What should I do if I use the nodeport of service to open the port, which can only be accessed on the current wsl but cannot be accessed externally?

**Comment by txbxxx** [comment]
The network segment of nodes in my cluster is 172.18.0.0/16. My windows can ping 172.18.0.1, but cannot ping the same two container nodes. Why?

**Comment by stmcginnis** [comment]
Some useful information can be found here: https://kind.sigs.k8s.io/docs/user/using-wsl2/#accessing-a-kubernetes-service-running-in-wsl2

**Comment by txbxxx** [comment]
> WSL 在其自己的 VM 中运行容器
Yes, I am currently unable to make Pods in kubernetes accessible to wsl hosts

**Comment by txbxxx** [comment]
> Some useful information can be found here: https://kind.sigs.k8s.io/docs/user/using-wsl2/#accessing-a-kubernetes-service-running-in-wsl2

https://kind.sigs.k8s.io/docs/user/using-wsl2/#kubernetes-service-with-session-affinity Is it executed directly on the wsl host? Or in a kind of cluster node?

**Comment by txbxxx** [comment]
> > 它是否直接在 wsl 主机上执行？还是在一种集群节点中？
> 
> 主机。

thanks!
