### ISSUE TITLE
Example setup with Kong ingress is outdated

### ISSUE THREAD

**Issue by dmipeck** [kubernetes-sigs/kind#3625]
**What would you like to be documented**:

An working installation example for [using Kong ingress with KinD](https://kind.sigs.k8s.io/docs/user/ingress/#ingress-kong).
Also, a valid link to Kong's docs (currently a 404)

**Why is this needed**:

Current installation command:
```sh
kubectl apply -f https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-dbless.yaml

```
 fails with the error:

```
error: resource mapping not found for name: "" namespace: "" from "https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-dbless.yaml": no matches for kind "Deprecated" in version "please-use-helm-to-install-kong"
ensure CRDs are installed first
```

**Comment by aojea** [comment]
yeah, this is the concern we raised with having documentation for external projects, we should reconsider  this and remove these guides and  let the projects to host their own documentation

cc: @BenTheElder

**Comment by BenTheElder** [comment]
Yeah, I think we should probably drop this, we don't have the bandwidth to maintain it and we have alternative options that are part of the Kubernetes project. 

The current page is cluttered and it's best to let the ingress maintainers keep their own docs. I think we should permit linking out to other options but not attempt to maintain multiple.

**Comment by jglick** [comment]
Beware that https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx does not appear to have any matching instructions in https://kubernetes.github.io/ingress-nginx/deploy/#local-development-clusters currently. Not sure if that is known; https://github.com/kubernetes/ingress-nginx/issues?q=kind is useless since the word is also used in labels (`/kind support`) and YAML (`kind: ConfigMap`) etc.

**Comment by kundan2707** [comment]
I can add updated link and steps also which will make it valid and useful.
https://docs.konghq.com/kubernetes-ingress-controller/latest/get-started/

**Comment by BenTheElder** [comment]
> I can add updated link and steps also which will make it valid and useful.
> https://docs.konghq.com/kubernetes-ingress-controller/latest/get-started/

The problem is this is not the first time we've seen this and it's a recurring issue, so we should consider not attempting to host kong docs in this repo where they're not being maintained versus kong can document anything necessary to use it with kind.

**Comment by kundan2707** [comment]
@BenTheElder then we can simply put link of Kong Ingress Controller (https://konghq.com/products/kong-ingress-controller) as they will maintain it and user can check updated one whenever need.

**Comment by aojea** [comment]
please do that

**Comment by kundan2707** [comment]
As suggested by @BenTheElder  that there is no kind specific steps available for kong ingress so its better to remove complete kong ingress sestion.
