### ISSUE TITLE
Can I use the kubectl executable in the control plane container?

### ISSUE THREAD

**Issue by steveiliop56** [kubernetes-sigs/kind#3629]
Hello,

I noticed that the control plane container includes the kubectl command which I tested and it works fine. Is it ok to use that instead of downloading kubectl on my machine or is there any reason not to do so? Also I noticed that /lib/modules is being mounted that's read only right?

**Comment by aojea** [comment]
yeah, you can use it

```
# mount | grep modules
...  on /usr/lib/modules type ext4 (ro,relatime,errors=remount-ro)
```

**Comment by steveiliop56** [comment]
Thank you!
