### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by hjacobs** [kubernetes-sigs/kind#363]
The current 0.1 release does not work for me yet and I'm eagerly waiting for the next release. Building from source is not an option for me as an "end user" :smirk: 

What would be the ETA for the next binary release? Thanks!

**Comment by BenTheElder** [comment]
Optimistically sometime next week, few more changes in flight. 🤞
The next release should offer some major improvements 😅

**Comment by hjacobs** [comment]
Thanks for the quick response, looking forward to it! :clap:

**Comment by BenTheElder** [comment]
slipped again :(, but on the plus side this is the last thing in the milestone: https://github.com/kubernetes-sigs/kind/pull/390

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/milestone/4 just needs the network options, need to test it a bit more and get it reviewed and then we're ready to ship 0.2 with v1alpha3 :crossed_fingers:

**Comment by BenTheElder** [comment]
#390 is in, will upgrade the images and start writing release notes :-)

**Comment by BenTheElder** [comment]
it's out https://github.com/kubernetes-sigs/kind/releases/tag/0.2.0

**Comment by hjacobs** [comment]
@BenTheElder thanks! The new release works for me and I already created my first issue (#398) :smile:
