### ISSUE TITLE
Way to prevent the "kind-" prefix when creating a cluster

### ISSUE THREAD

**Issue by nirs** [kubernetes-sigs/kind#3633]
**What would you like to be added**:

When creating a cluster using --name my-cluster, add an option to create the context as "my-cluster" instead of "kind-my-cluster".

Possible way to add this feature without changing the default behavior:

    kind create cluster --name foo --no-prefix

And probably have the same option in the cluster config:

    kind: Cluster
    name: foo
    prefix: false

Another option is to add a --context option:

    kind create cluster --name foo --context foo

And probably have the same option in the cluster config:

    kind: Cluster
    name: foo
    context: foo

**Why is this needed**:

With "kind-" prefix, I have to strip the kind prefix in multiple places expecting the actual cluster name. I know this is a considered a feature, but this is harmful for my use case.

I'm trying to port code using minikube to kind, and now I need to go and strip the "kind-" prefix in multiple places, possibly breaking actual cluster name called "kind-cluster" (which will have context kind-kind-cluster" in kind.

I think this will help adoption of kind, making it easy to switch between tools.

Example code dealing with this the "kind-" prefix that will be much simpler without the prefix:
https://github.com/open-cluster-management-io/ocm/blob/main/solutions/setup-dev-environment/local-up.sh

Example code that does not work with kind because of the prefix:
https://github.com/RamenDR/ramen/blob/main/test/addons/ocm-cluster/start

To port the code above to kind, we need to add something like this in multiple places:

    cluster_name = cluster.replace("kind-", "")

**Comment by BenTheElder** [comment]
Sorr but we don't support this and I don't think we should, we've never seen this requested before and  having tooling be sensitive to KUBECONFIG entry names is super brittle / non-portable. We prefer not to take on additional complexity and potential bugs to encourage non-conformant behaviors.


If you _really_ can't make your tooling work without different naming schemes you can just substitute the context name in the kubeconfig and it will still work. Something like `kind get kubeconfig --name=$NAME | sed s/kind-$NAME/$NAME/g > ./KUBECONFIG`

The names in $KUBECONFIG are ~arbitrary and the "actual cluster name" doesn't matter unless tools are test tools that _also_ calling into `kind` directly to e.g. side-load images (and not through kubernetes API), in which case they have other options to discover the "cluster name", e.g. the kubeadm configmap or the labels on the node containers.

**Comment by BenTheElder** [comment]
If your tools are going to support other cluster tools or user managed kubeconfigs the names of the config entries might well have exactly nothing to do with anything else and expecting that they will is a bad / non-portable assumption.

In general Kubernetes doesn't even have a concept of a cluster-scoped name (kubeadm does, but not all clusters are kubeadm clsuters), only API endpoints and node names (and control plane nodes may not be registered).

**Comment by nirs** [comment]
Sure I can fix the kubeconfig after creating the clusters, but will it break

    kind delete --name foo

Looking for context "kind-foo"?

**Comment by nirs** [comment]
Here is other code fixing up the "kind-" prefix:
https://github.com/submariner-io/shipyard/blob/f98f329f1072a0a30c476a58950405e6ced0ee96/scripts/shared/lib/clusters_kind#L59

**Comment by BenTheElder** [comment]
> So renaming the contexts/clusters/users the kubeconfig does not seems like a good workaround. 

I would recommend moving them into a dedicated config file which you can delete. KUBECONFIG env can point to multiple if you're doing this yourself.

If you're accepting arbitrary user-supplied kubeconfigs, you should not be depending on naming schemes.

> seems that I need to either add "kind-" prefix in the code and use the real cluster names, or use the context name and strip the "kind-" prefix to get the real cluster names. Both are not great options.

I mean we added the kind- prefix to prevent collisions and because other cluster creation tools were prefixing their entries.

And again, you should not really be depending on the mapping to cluster name, because the user supplied kubeconfigs can have arbitrary names here.

**Comment by BenTheElder** [comment]
(e.g. gke will have `gke_`, k3d will have `k3d-` and rejected the same feature https://github.com/k3d-io/k3d/issues/387, ...)

**Comment by nirs** [comment]
> > So renaming the contexts/clusters/users the kubeconfig does not seems like a good workaround.
> 
> I would recommend moving them into a dedicated config file which you can delete. KUBECONFIG env can point to multiple if you're doing this yourself.

Using separate kubeconfig is a problem for users. Now you need to use hidden and fragile KUBECONFIG environment variable or add --kubeconfig ... to all commands.

> If you're accepting arbitrary user-supplied kubeconfigs, you should not be depending on naming schemes.

My tool is creating multiple test clusters in the default or user provided kubeconfig, so I control the naming scheme, and can make the user experience better by having no mapping.

Users choose the cluster names, and they can change them to avoid clashes without maintaining any mapping in the tool.

**Comment by stmcginnis** [comment]
> Using separate kubeconfig is a problem for users. Now you need to use hidden and fragile KUBECONFIG environment variable or add --kubeconfig ... to all commands.

This is actually the default pattern for many users. I've even known people to symlink `~/.kube/config` to `/dev/null` to enforce the use of independent kubeconfig files. So it really isn't too difficult to do if you make it a normal practice.

**Comment by BenTheElder** [comment]
There are multiple alternatives mentioned above.

`kubectl config rename-context` is available as a cleaner solution to sed, and failing to delete the entires is not a big deal, unless you're renaming them to a unique name each time or unique paths each time.

In that case the caller is going to be responsible for cleanup which is also ... pretty straightforward and reasonable out of scope for us. the kubeconfig deletion in `kind delete cluster` is a convenience and `kubectl config` has commands for deleting entries as well.

**Comment by arthur-c** [comment]
I would also enjoy an option to remove this enforced prefix, it adds unnecessary steps to control the cluster name when writing automation.

**Comment by nirs** [comment]
What I'm doing to mitigate this issue for kind test clusters:
- Create the clusters with temporary kubeconfig per cluster
- Fixup the kubeconfig (rename context, cluster, user, current context)
- Merge the clusters kubeconfigs to a temporary kubeconfig
- When done, delete the temporary kubeconfigs
