### ISSUE TITLE
Kind does not validate if cluster exists before delete it

### ISSUE THREAD

**Issue by reysonbarros** [kubernetes-sigs/kind#3639]
**What happened**:

If deleting a non-existent cluster, kind shows up a message saying that the cluster was deleted.

**What you expected to happen**:
Kind should thrown a message saying that the cluster does not exist

**How to reproduce it (as _minimally_ and precisely as possible)**:
kind create cluster --name test
kind delete cluster --name test1
Deleting cluster "test1" ...
kind delete clusters test1
Deleted clusters: ["test1"]
**Anything else we need to know?**:
No
**Environment:**

- kind version: (use `kind version`): kind version 0.20.0
- Runtime info: (use `docker info`, `podman info` or `nerdctl info`): Docker version 26.1.3, build b72abbb
- OS (e.g. from `/etc/os-release`): 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
- Kubernetes version: (use `kubectl version`): Client Version: v1.28.2
- Any proxies or other special environment settings?:No

**Comment by stmcginnis** [comment]
This is working as designed. The delete call is idempotent, so you should be able to call it many times without it failing.

This of it more as saying "I don't want cluster X to exist" and kind making sure that it does not. If it didn't exist in the first place, there's just less work that kind needs to do to match the requested state.

/close

**Comment by BenTheElder** [comment]
(think of this like `rm -f`)
