### ISSUE TITLE
kind create cluster failed 

### ISSUE THREAD

**Issue by snji** [kubernetes-sigs/kind#3647]
**What happened**:
`kind create cluster` failed

<details>
    <summary> reuslt </summary>

    Creating cluster "kind" ...
     ✓ Ensuring node image (kindest/node:v1.30.0) 🖼
     ✓ Preparing nodes 📦
     ✗ Writing configuration 📜
    ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 1
    Command Output: Error response from daemon: Container 9a850b08d4d126f19a768b7a440c2e9a6a6711957b664967766d109aaca3580b is restarting, wait until the container is running

</details> 

**Anything else we need to know?**:
 <details>
    <summary> docker logs kind-control-plane</summary>
    
    INFO: ensuring we can execute mount/umount even with userns-remap
    INFO: remounting /sys read-only
    INFO: making mounts shared
    INFO: detected cgroup v1
    INFO: detected cgroupns
    INFO: removing misc controller
    INFO: clearing and regenerating /etc/machine-id
    Initializing machine ID from random generator.
    INFO: faking /sys/class/dmi/id/product_name to be "kind"
    INFO: faking /sys/class/dmi/id/product_uuid to be random
    INFO: faking /sys/devices/virtual/dmi/id/product_uuid as well
    INFO: setting iptables to detected mode: legacy
    Bad argument `[unsupported'
    Error occurred at line: 12
    Try `iptables-restore -h' or 'iptables-restore --help' for more information.
    INFO: ensuring we can execute mount/umount even with userns-remap
    INFO: remounting /sys read-only
    INFO: making mounts shared
    INFO: detected cgroup v1
    INFO: detected cgroupns
    INFO: removing misc controller
    INFO: clearing and regenerating /etc/machine-id
    Initializing machine ID from random generator.
    INFO: faking /sys/class/dmi/id/product_name to be "kind"
    INFO: faking /sys/class/dmi/id/product_uuid to be random
    INFO: faking /sys/devices/virtual/dmi/id/product_uuid as well
    INFO: setting iptables to detected mode: legacy
    Bad argument `[unsupported'
    Error occurred at line: 12
    Try `iptables-restore -h' or 'iptables-restore --help' for more information.
     
</details>

**Environment:**

- **kind version**: (use `kind version`): 
  `kind v0.23.0 go1.21.10 linux/amd64`
- **Runtime info**: (use `docker info`, `podman info` or `nerdctl info`):
    <details>
    <summary>docker info</summary>
    
         Client:
         Context:    default
         Debug Mode: false
         Plugins:
          app: Docker App (Docker Inc., v0.9.1-beta3)
          buildx: Docker Buildx (Docker Inc., v0.10.4-docker)
          compose: Docker Compose (Docker Inc., v2.27.0)
        
        Server:
         Containers: 5
          Running: 3
          Paused: 0
          Stopped: 2
         Images: 42
         Server Version: 20.10.24
         Storage Driver: overlay2
          Backing Filesystem: extfs
          Supports d_type: true
          Native Overlay Diff: false
          userxattr: false
         Logging Driver: json-file
         Cgroup Driver: cgroupfs
         Cgroup Version: 1
         Plugins:
          Volume: local
          Network: bridge host ipvlan macvlan null overlay
          Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
         Swarm: inactive
         Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
         Default Runtime: runc
         Init Binary: docker-init
         containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
         runc version: v1.1.7-0-g860f061
         init version: de40ad0
         Security Options:
          seccomp
           Profile: default
         Kernel Version: 5.4.203-1-tlinux4-0011.2
         Operating System: Tencent tlinux 2.6
         OSType: linux
         Architecture: x86_64
         CPUs: 16
         Total Memory: 31.1GiB
         Name: VM-152-123-tencentos
         ID: ZVHZ:77WV:AAP4:ZVZ4:3OBH:EZJN:Y6AH:75XU:EYDU:KXH4:345I:XVBU
         Docker Root Dir: /data/docker/lib
         Debug Mode: false
    </details>

- **OS** (e.g. from `/etc/os-release`):
   <details> 
       <summary>/etc/os-release</summary>

      
          NAME="Tencent tlinux"
          VERSION="2.6"
          ID="tlinux"
          ID_LIKE="rhel fedora centos"
          VERSION_ID="2.6"
          PRETTY_NAME="Tencent tlinux 2.6"
          ANSI_COLOR="0;31"
          CPE_NAME="cpe:/o:tlinux:linux:2"
          HOME_URL="https://tlinux.qq.com/" 
      

   </details>
- **Kubernetes version**: (use `kubectl version`):
   <details> 
       <summary>kubectl version</summary>

        Client Version: v1.28.4
        Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
        Server Version: v1.28.3
   </details>

**Comment by stmcginnis** [comment]
This appears to be the same issue as https://github.com/kubernetes-sigs/kind/issues/3641

This distro is too old. You will need to upgrade to a more recent release or run with a newer distro in a VM.

/kind support
/remove-kind bug

**Comment by snji** [comment]
> This appears to be the same issue as #3641
> 
> This distro is too old. You will need to upgrade to a more recent release or run with a newer distro in a VM.
> 
> /kind support /remove-kind bug

Do you mean that OS Version is too low? 

- cat /etc/redhat-release

  `CentOS Linux release 7.6 (Final)`

- uname -a
`Linux VM-152-123-tencentos 5.4.203-1-tlinux4-0011.2 #1 SMP Tue May 30 10:52:22 CST 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by stmcginnis** [comment]
Yep, exactly.

https://kind.sigs.k8s.io/docs/user/known-issues/#older-linux-distributions

You will need something RHEL/CentOS 8 based, or another more recent Linux distro.

**Comment by snji** [comment]
> Yep, exactly.
> 
> https://kind.sigs.k8s.io/docs/user/known-issues/#older-linux-distributions
> 
> You will need something RHEL/CentOS 8 based, or another more recent Linux distro.

Yeah. I successfully resolved the issue by upgrading the operating system to CentOS 8. Thanks @stmcginnis
