### ISSUE TITLE
Kind cluster not able to pull public images from ghcr.io

### ISSUE THREAD

**Issue by rohitagg2020** [kubernetes-sigs/kind#3663]
**What happened**:

I have created a kind cluster. But when I try to create a deployment (which pulls images from ghcr.io), it fails. 

Error:
```
^ Pending: ErrImagePull (message: failed to pull and unpack image "ghcr.io/carvel-dev/kapp-controller@sha256:b83bd139c42777bb4428c2ae421f93675a7d6147dff3147471d1be112d9c1eec": 
failed to resolve reference "ghcr.io/carvel-dev/kapp-controller@sha256:b83bd139c42777bb4428c2ae421f93675a7d6147dff3147471d1be112d9c1eec": 
failed to do request: Head "https://ghcr.io/v2/carvel-dev/kapp-controller/manifests/sha256:b83bd139c42777bb4428c2ae421f93675a7d6147dff3147471d1be112d9c1eec": 
tls: failed to verify certificate: x509: certificate signed by unknown authority)
```

It has been working fine until last month. I thnk I have messed up my environment, because of which I am facing this issue. 

Things I have tried:
* Uninstall and install kind.
* Deleted and created new kind cluster.
* Uninstalled and reinstalled docker desktop.

But still, I am not able to get around the error. How can I get back to things working again?

**What you expected to happen**:
Deployment to be created successfully.
**How to reproduce it (as _minimally_ and precisely as possible)**:
kubectl apply -f https://github.com/carvel-dev/kapp-controller/releases/latest/download/release.yml
**Anything else we need to know?**:
As this is a public image, I guess the ca certs are not being picked up when kind cluster is created. 
**Environment:**

- kind version: (use `kind version`): kind v0.23.0
- Runtime info: (use `docker info`, `podman info` or `nerdctl info`):
 Client: Docker Engine - Community
 Version:    26.1.4
 Context:    desktop-linux
 Debug Mode: false
- OS (e.g. from `/etc/os-release`): macOS
- Kubernetes version: (use `kubectl version`):
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.9
- Any proxies or other special environment settings?:

**Comment by stmcginnis** [comment]
/remove-kind bug
/kind support

Please fill in the full "Environment" details from the issue template.

Are you in an environment that uses a proxy?

You could try deleting any cluster you have, then delete the `kind` Docker network, then try creating again. It will try to recreate the network to make sure there isn't something odd with the existing setup.

You can also do `kind create cluster --retain`, then use `docker ps` to see the created containers. Then you can `docker exec` into the kind container(s) to perform troubleshooting.

**Comment by BenTheElder** [comment]
This looks like a MITM proxy causing issues.

**Comment by rohitagg2020** [comment]
Are you in an environment that uses a proxy?
> No

You could try deleting any cluster you have, then delete the kind Docker network, then try creating again. It will try to recreate the network to make sure there isn't something odd with the existing setup.
> How can I do this?

**Comment by aojea** [comment]
`docker network rm kind`

https://docs.docker.com/reference/cli/docker/network/rm/

**Comment by rohitagg2020** [comment]
I already tried `docker network rm kind` and it didnt work.

**Comment by tao12345666333** [comment]
What's your steps to create kind cluster?

I saw your post server version is Server Version: v1.27.9

And kind version is 0.23

I think maybe you have changed some configurations

**Comment by BenTheElder** [comment]
no, you would've specified it https://kind.sigs.k8s.io/docs/user/configuration/

**Comment by hridyeshpant** [comment]
what is the solution ? i am also hitting same issue . i am able to pull the image in my mac box but failing to pull image inside the kind cluster .

**Comment by stmcginnis** [comment]
> what is the solution ? i am also hitting same issue . i am able to pull the image in my mac box but failing to pull image inside the kind cluster .

Are you running into this? https://github.com/kubernetes-sigs/kind/issues/3795#issuecomment-2488735728

If not, feel free to file a new issue or ask for assistance on Slack.

**Comment by BenTheElder** [comment]
> what is the solution ? i am also hitting same issue . i am able to pull the image in my mac box but failing to pull image inside the kind cluster .

this is usual a problem with firewalls and/or proxies, and will be specific to your environment.

**Comment by devent** [comment]
Hi. I get the same problem with kind v0.27.0

If I go into the running docker container node, the Zscaler certificates are not installed in /etc/ssl/certs. I can download docker images from ghcr.io via docker locally. But in the kind cluster, I always get the error unknown authority. If the Zscaler certificates are not installed in the container node, I don't understand how you would expect to pull anything from ghcr.io.

```
message: 'Back-off pulling image "ghcr.io/fluxcd/helm-controller:v1.2.0":
          ErrImagePull: failed to pull and unpack image "ghcr.io/fluxcd/helm-controller:v1.2.0":
          failed to resolve reference "ghcr.io/fluxcd/helm-controller:v1.2.0": failed
          to do request: Head "https://ghcr.io/v2/fluxcd/helm-controller/manifests/v1.2.0":
          tls: failed to verify certificate: x509: certificate signed by unknown authority'
```

I have the certificates available on my local Ubuntu. How can I pass them to kind?

**Comment by BenTheElder** [comment]
> If I go into the running docker container node, the Zscaler certificates are not installed in /etc/ssl/certs. I can download docker images from ghcr.io via docker locally. But in the kind cluster, I always get the error unknown authority. If the Zscaler certificates are not installed in the container node, I don't understand how you would expect to pull anything from ghcr.io.

Zscalar is some kind of cyber security tool intercepting connections with a proxy?

Of course kind does not ship with their MITM certs, please search the issue tracker "proxy cert" and check the docs page for private registries. There are multiple possibilities to plumb through certificates, or to pull from the host and then pass to the nodes.

ghcr.io works on other hosts and the original issue here was not conclusively defined due to lack of information.  The original poster specified that they are not using a proxy so we shouldn't assume it's the same issue.

**Comment by devent** [comment]
No, sorry. It's a Zscaler certificate. If you go to `https://ghcr.io/v2/` repository and look at the SSL certificate, you see the chain is Zscaler Root CA, Zscaler Intermediate Root CA (zscalerthree.net), Zscaler Intermediate Root CA (zscalerthree.net) (t) , *.ghcr.io by Zscaler Inc. All of those certificates are missing in the node under /etc/ssl/certs. If the certs are missing on the node then no images can be downloaded from ghcr.io. This issue for example affect me in deploying FluxCD on Kind.
