### ISSUE TITLE
Publish node images for v.1.13.4, v1.14.0-beta.1

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/kind#369]
Ideally, there should be a kindest/node-images for each alpha, beta, rc, minor, major.
It will be great to get this automatically triggered...

**Comment by fabriziopandini** [comment]
PS. if I could help in managing image publication, let me know

**Comment by BenTheElder** [comment]
I can publish these, automation is tracked in https://github.com/kubernetes-sigs/kind/issues/197

/assign
/priority important-soon

**Comment by BenTheElder** [comment]
I published 1.13.4 for https://github.com/kubernetes-sigs/kind/pull/394, we still need automation for the rest. I think at least https://github.com/kubernetes-sigs/kind/issues/381 will make it easier / cheaper to consume the existing non-kind CI builds.

**Comment by BenTheElder** [comment]
not sure how we want to handle the betas etc. ideally this should be consistent and automated.

**Comment by BenTheElder** [comment]
I don't think we're going to do these specific tags for now, and the image format is being re-stabilized after the CRI and CNI improvements. We need to work more on making that flexible.
