### ISSUE TITLE
Kind cluster fails at creation

### ISSUE THREAD

**Issue by AdrianXIA** [kubernetes-sigs/kind#3691]
Hello!

I am trying to configure a KinD cluster with Gitlab. Many times, cluster creation fails, but sometimes it passes.
Creation  fails when the logs in docker container looks like(yellow lines):
![image](https://github.com/user-attachments/assets/d710c631-fce3-4385-9fc7-b40eea1bd578)

Versions/Components:
1. docker: docker:27-dind
2. kindest/node = 1.30.2
3. KIND CLI = v0.23.0

 What can be the problem?
 
 Thank you

**Comment by stmcginnis** [comment]
There can be many reasons for failures in the process. It's hard to tell with the limited information here where to start. Please add the environment information from the issue template so we can better understand the environment this is running in:

```txt
**Environment:**

- kind version: (use `kind version`):
- Runtime info: (use `docker info`, `podman info` or `nerdctl info`):
- OS (e.g. from `/etc/os-release`):
- Kubernetes version: (use `kubectl version`):
- Any proxies or other special environment settings?:
```

**Comment by stmcginnis** [comment]
> Alpine Linux v3.20 (containerized)

So you are running Kubernetes in Docker in Docker?

There have been known issues with using Alpine as a host OS for kind ([example](https://github.com/kubernetes-sigs/kind/issues/3277#issuecomment-1915667598)). Are you able to use something else? Ideally something that supports cgroupv2 instead of v1 that is in use here.

Note: please paste text output directly, not screenshots of text.

**Comment by BenTheElder** [comment]
> The runner runs inside an AWS EKS cluster and I use Gitlab Service feature.

https://github.com/kubernetes-sigs/kind/issues/303

There's a LOT of problems with trying to run kubernetes in kubernetes, see some of them above

**Comment by AdrianXIA** [comment]
Hello! 

Yes, I have downgraded some versions and it works..
I cannot use cgroupv2 at the moment. I will keep this in mind when I will try to use the latest  versions.

Thank you for help.
