### ISSUE TITLE
Failed to deploy a kind cluster

### ISSUE THREAD

**Issue by Monokaix** [kubernetes-sigs/kind#3694]
**What happened**:
Failed to deplopy a kind cluster

**What you expected to happen**:
Deployed a cluster successfully

**How to reproduce it (as _minimally_ and precisely as possible)**:
use kind create cluster test
**Anything else we need to know?**:
**Environment:**

- kind version: (use `kind version`):kind v0.23.0 go1.21.11 linux/amd64
- Runtime info: (use `docker info`, `podman info` or `nerdctl info`):
Client: Docker Engine - Community
 Version:    26.1.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 51
 Server Version: 26.1.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 6.10.1-1.el8.elrepo.x86_64
 Operating System: CentOS Linux 8
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.63GiB
 Name: ecs-4b42-0001
 ID: b3d59d78-846c-444a-b840-9b4226d2c85a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: volcanosh
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

- OS (e.g. from `/etc/os-release`):
 CentOS Linux release 8.5.2111
6.10.1-1.el8.elrepo.x86_64

- Kubernetes version: (use `kubectl version`):
-1.30
- Any proxies or other special environment settings?:

**Comment by Monokaix** [comment]
log file: 
[log.tar.gz](https://github.com/user-attachments/files/16391034/log.tar.gz)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/3558

**Comment by kundan2707** [comment]
/retitle Failed to deploy a kind cluster
