### ISSUE TITLE
How to disable cgroupv2 by default?

### ISSUE THREAD

**Issue by Monokaix** [kubernetes-sigs/kind#3697]
Hi, I want to local up a kind cluster with cgroupv2 disabled, how can I get this？

**Comment by aojea** [comment]
can you elaborate more on why do you need this?

**Comment by Monokaix** [comment]
> can you elaborate more on why do you need this? cgroups v1 is being deprecated across the entire ecosystem

Some components have not adapted to cgroupv2 yet, and it doesn't work well with cgroup v2 kind cluster, such as https://github.com/koordinator-sh/koordinator/issues/800#issuecomment-1316168150

**Comment by stmcginnis** [comment]
I believe you would need to update `/etc/default/grub` to have `GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"`. Then run `grub2-mkconfig -o /boot/grub2/grub.cfg` and reboot for the new setting to take effect.

**Comment by Monokaix** [comment]
> I believe you would need to update `/etc/default/grub` to have `GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"`. Then run `grub2-mkconfig -o /boot/grub2/grub.cfg` and reboot for the new setting to take effect.

Aha, seems there is no such file in kind image, I want to disable it in kind cluster: ）

**Comment by stmcginnis** [comment]
I'm not 100% sure, but I think you need to disable it on the host machine. It wouldn't be a setting specific to the container running the k8s node.

**Comment by Monokaix** [comment]
> I'm not 100% sure, but I think you need to disable it on the host machine. It wouldn't be a setting specific to the container running the k8s node.

Thanks！got that.

**Comment by aojea** [comment]
just be aware since 1.31 cgrouspv1 will not receive features in kubernetes https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4569-cgroup-v1-maintenance-mode

**Comment by BenTheElder** [comment]
I wouldn't recommend this, but as noted above it comes from the host. You can't change this in kind because kind node containers share the kernel with the host environment. You have to change it on the host, and c group v2 is highly recommended.

kubernetes has supported v2 since 1.19, released about 4 years ago now.

**Comment by Monokaix** [comment]
Thanks all you guys! : )
