### ISSUE TITLE
kind cluster doesn't come up on mac m3

### ISSUE THREAD

**Issue by ViswanathB** [kubernetes-sigs/kind#3723]
[debug.zip](https://github.com/user-attachments/files/16789213/debug.zip)

Bringing up kind cluster doesn't work. Attached zip

**What happened**:
 Kind cluster doesn't come up, waits for 4 min and timeouts.
 
**What you expected to happen**:
Kind cluster expected to come up. I opened a shell inside container and tried to `kubectl` doesn't work either. 

**How to reproduce it (as _minimally_ and precisely as possible)**:

1. brew install kind
2. docker latest version installed from docker instructions https://docs.docker.com/desktop/install/mac-install/. 
3. `kubectl` installed  with brew as well
3. `kind create cluster` fails with timeout to health check.

Verified other docker containers work as expected and port mapping works too.

**Anything else we need to know?**:
N/A

**Environment:**

boga$ kind version
kind v0.24.0 go1.22.6 darwin/arm64
boga$ docker version
Client:
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:54:12 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.33.0 (160616)
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:14 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
boga$ 

- OS (e.g. from `/etc/os-release`):
Sonoma 14.6.1

- Kubernetes version: (use `kubectl version`):
boga$ kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
The connection to the server localhost:8080 was refused - did you specify the right host or port?

- Any proxies or other special environment settings?
don't think it applies, health check is on loopback 127.0.0.1

**Comment by wbrefvem** [comment]
@ViswanathB After running `kind create cluster` but before the timeout, could you open a second terminal on the host, run `docker logs -f kind-control-plane`, and provide any errors that appear?

**Comment by stmcginnis** [comment]
That's a new one for me:

> Failed to run Kubelet: could not detect clock speed from output

Hopefully someone else has seen something like that and might know what is needed.

> could you open a second terminal on the host, run docker logs -f kind-control-plane, and provide any errors that appear?

The probably easier approach is what I believe was done to get the zip file. If there are failures you usually want to run `kind cluster create --retain` to keep the container(s) around, then `kind export logs` to get a collection several useful log files. Then `kind delete cluster` to clean up after the export is complete.

**Comment by stmcginnis** [comment]
_Maybe_ related: https://github.com/google/cadvisor/issues/2237#issuecomment-1401981320

**Comment by ViswanathB** [comment]
@stmcginnis zip is included in the description, FYI and no error in docker logs.
[docker_logs.log](https://github.com/user-attachments/files/16800127/docker_logs.log)

**Comment by ViswanathB** [comment]
> _Maybe_ related: [google/cadvisor#2237 (comment)](https://github.com/google/cadvisor/issues/2237#issuecomment-1401981320)

Yes, this fixed the issue. thx.

**Comment by BenTheElder** [comment]
This looks like #2718 

Are you successfully running amd64 on arm64 now? In the past this has not worked

**Comment by BenTheElder** [comment]
Ah yes, https://github.com/google/cadvisor/issues/2237#issuecomment-1401981320 looks like the same, you have to match the host architecture still unfortunately. There's more details in #2718

**Comment by ViswanathB** [comment]
> This looks like #2718
> 
> Are you successfully running amd64 on arm64 now? In the past this has not worked

Nope, I have to use arm64.
