### ISSUE TITLE
BETA release status

### ISSUE THREAD

**Issue by axsaucedo** [kubernetes-sigs/kind#3727]
As the project continues to evolve and grow in adoption I am curious on the perspective towards BETA / GA release. Looking at the roadmap checklist it seems to me the key milestones are all met, so was curious on whether there are current views to move towards 1.0 BETA vs whether there are further milestones to bridge the gap https://kind.sigs.k8s.io/docs/contributing/1.0-roadmap/

**Comment by BenTheElder** [comment]
The config format would need to be beta ,and it has some deficiencies, but we could consider it.

There's no concrete timeline, we spend most of our time keeping after bugs and user support / PR reviews / ... currently.

**Comment by BenTheElder** [comment]
By far the biggest issue is the config format (e.g. config patches need a rewrite but we'll have to support both for a small time window at least), I think also the gaps in docker vs podman vs nerdctl.
