### ISSUE TITLE
unable to interact with pods 

### ISSUE THREAD

**Issue by devaraj2002** [kubernetes-sigs/kind#3728]
k exec -it app1-64ff88b6dc-vgvfe -- /bin/bash

Unable to use a TTV input is not a terminal or the right kind of file

error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "b669dle78b302e235b2ad8e3d0484d99a538ded2ca83fa28dc7dcd4ceealc423": OCI runtime exec faile d: exec failed: container linux.go: 380: starting container process caused: exec: "C:/Program Files/Git/usr/bin/bash": stat C:/Program Files/Git/usr/bin/bash: no such file or directory: unknown

**Comment by aojea** [comment]
are you running windows containers?

**Comment by bob2204** [comment]
Hello

Are you sure there a /bin/bash file in your container image ?

**Comment by devaraj2002** [comment]
My issue git resolved earlier I am using gitbash as cli so it was raising error now it is working fine with mobaexterm, now I am facing issue with ' kubectl edit po pod1' edit  command
