### ISSUE TITLE
Adding support for `.deb` packages

### ISSUE THREAD

**Issue by harsh098** [kubernetes-sigs/kind#3740]
**Adding `.deb` builds to kind releases**:
- I observed that there are no `.deb` releases for kind and also no PPA/APT repository exists.
- This makes managing upgrades and updates for kind a manual process.
- This is not a big enhancement and can be useful in future

**I have already put in some work**
- I have created a `.deb` package (binary release) for version `0.24.0` which can be tested directly on `amd64` systems with Ubuntu and Debian.
- The `.deb` package is available for download at [https://downloads.hmx86.cloud/kind_0.24.0_amd64.deb](https://downloads.hmx86.cloud/kind_0.24.0_amd64.deb).
- I can put in the work to add a small CI workflow to build `.deb` packages and push the latest ones to an apt-repository if needed
 
**Why is this needed ?**:
- Many Ubuntu and Debian users have to rely on the curl scripts for installing kind cli on their systems.
- If a PPA is added to launchpad, installaion process will be pretty straightforward.
- Updating kind would be just one command.

**Comment by afbjorklund** [comment]
Other parts of Kubernetes is using [OBS](https://build.opensuse.org/project/subprojects/isv:kubernetes) for making packages:

https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/


But it is yet unclear whether this packaging/hosting effort will extend to kind and minikube*, or not?

\* minikube is currently building .deb and .rpm packages, but they are only on github (no apt or yum)

**Comment by harsh098** [comment]
I wanted to extend help as I always found it frustrating on going to installation websites. deleting the previous binaries and reinstalling via a curl or wget.
So, I did it. 
I think if there can be a community census on if people really want this then we can proceed forward or else I can always have an unofficial distribution for myself and anybody else who wishes to use it via launchpad for ubuntu atleast.

**Comment by harsh098** [comment]
Shall we create a poll in slack ?

**Comment by afbjorklund** [comment]
I thought you already did? (created a poll)

**Comment by harsh098** [comment]
I meant a more formal one.

**Comment by aojea** [comment]
I just found out this week someone added kind to debian and since recently is in the testing distro https://packages.debian.org/trixie/kind

**Comment by BenTheElder** [comment]
We don't really have the bandwidth to maintain more packages.

> Many Ubuntu and Debian users have to rely on the curl scripts for installing kind cli on their systems.

The binaries are just a popular shortcut, `go install` is quick, _relatively_ secure, and recommended.

**Comment by BenTheElder** [comment]
> We don't really have the bandwidth to maintain more packages.

We do however reference third party packaging as an option in the install docs, with a note clarifying that we're not managing these.

And it seems debian is adding this upstream 😅

**Comment by afbjorklund** [comment]
> And it seems debian is adding this upstream 😅

Probably just needs a mention over on https://kind.sigs.k8s.io/docs/user/quick-start#installing-with-a-package-manager

**Comment by harsh098** [comment]
Had no Idea about it 😅.
