### ISSUE TITLE
Hi Team I am unable to see this files $(go env GOPATH)/src/k8s.io/kubernetes

### ISSUE THREAD

**Issue by rajk764** [kubernetes-sigs/kind#3741]
I unable to find this files $(go env GOPATH)/src/k8s.io/kubernetes 
after install

rajkumarprabakaran@Rajkumars-MacBook-Pro ~ % go install sigs.k8s.io/kind@v0.24.0
rajkumarprabakaran@Rajkumars-MacBook-Pro ~ % ls -ltr go 
total 0
drwxr-xr-x  4 rajkumarprabakaran  staff  128 Sep  8 14:25 pkg
drwxr-xr-x  3 rajkumarprabakaran  staff   96 Sep  8 14:26 bin
rajkumarprabakaran@Rajkumars-MacBook-Pro ~ %

src dir is missing, please help me to fix it

**Comment by BenTheElder** [comment]
/remove-kind bug
/kind support

This is expected, installing `kind` like this installs the kind tool.

If you want to build kubernetes from source, you need to setup your kubernetes clone yourself, please see: https://kind.sigs.k8s.io/docs/user/quick-start/#building-images
