### ISSUE TITLE
Make kind load docker-image only load if the image is not already on the nodes

### ISSUE THREAD

**Issue by bouk** [kubernetes-sigs/kind#380]
Currently `kind load docker-image` always tars up the image and sends it, even if the nodes already contains the exact image. To make image loading faster, Kind should look at the image ID and only load over the image if the nodes don't have it yet.

**Comment by BenTheElder** [comment]
So the tar loading on the node should more or less skip reading images that are already present, for large enough images skipping the tar on the host after checking may still speed up a bit though.

/kind feature
/priority important-longterm

**Comment by rohansingh** [comment]
I'm not sure if this should be a separate issue, but I think `kind` should also only load layers that are not already present on any given node. Here's an example of that kind of incremental load logic:
https://github.com/bazelbuild/rules_docker/blob/master/container/incremental_load.sh.tpl

I'm using that internally to wrap `kind load image-archive` and only providing layers that are missing in a single-node cluster, and it is significantly faster when pushing changes.

**Comment by rohansingh** [comment]
Here's the key insight from that script, by the way:

> Docker elides layer reads from the tarball when it already has a copy of the layer with the same basis as it has within the tarball.  This means that once we have found the lowest layer in our image of which Docker is unaware we must load all of the remaining layers.  So to determine existence, iterate through the layers attempting to load the image without it's tarball.  As soon as one fails, break and synthesize a "docker save" tarball of all of the remaining layers.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/382 fixed this.
