### ISSUE TITLE
kind node-images vs kind version

### ISSUE THREAD

**Issue by ppalucki** [kubernetes-sigs/kind#3810]
How kind version is related to node-image version?

Why I'm asking. I want to use new feature of local-path-provisioner ([feature](https://github.com/rancher/local-path-provisioner?tab=readme-ov-file#storage-classes) added "custom path patterns" ([commit](https://github.com/rancher/local-path-provisioner/commit/af85381fd304f3a65999687a5da18536e8a1b1ea)) to version v0.0.30 and v0.0.29.
and then:
- local-path-provisioner version v0.0.29 - was released 8/oct/2024 ([release here](https://github.com/rancher/local-path-provisioner/releases/tag/v0.0.30))
- local-path-provisioner version v0.0.30 - was released 3/Sep/2024 ([release here](https://github.com/rancher/local-path-provisioner/releases/tag/v0.0.29))
 
Then we have commit in kind about bumping local-path-provisioner image from v20240813 to v20241108 [here](https://github.com/kubernetes-sigs/kind/commit/3b84129bbb6a5ea42198e676001b5bc0a8f4fb76)

and we can even see image is build and published ([here](https://hub.docker.com/r/kindest/local-path-provisioner/tags)) - we can both images there:

![image](https://github.com/user-attachments/assets/49e2f5b0-17e6-491c-b554-133a9f399ba5)

and the node image is also fresh enough (Nov 8 > Oct 8)

![image](https://github.com/user-attachments/assets/8a61fa1a-2846-4562-83e2-6cc6314f8488)

**Then the issue is: when deploying latests kind (0.25) it still deploys old version of local-path-priovisioner image which is 20240813 instead of expected v20241108 !**. 

kind release 0.25 **supossedly** created new node-images as described [here](https://github.com/kubernetes-sigs/kind/releases/tag/v0.25.0) 
and as we can see below deployed image sha256 matches the one referend in on release page **"Image": "kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e",**

**Is it a bug or am I missing something kind/node image relase cycle/relationship?** 

``` bash
# kind version
kind v0.25.0 go1.22.9 linux/amd64
# kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.31.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
# kind export kubeconfig
Set kubectl context to "kind-kind"
# kubectl get pod -A | grep local
local-path-storage   local-path-provisioner-57c5987fd4-q4v44      1/1     Running   0          81s
# kubectl describe pod -n local-path-storage local-path-provisioner-57c5987fd4-q4v44 | grep -i image
    Image:         docker.io/kindest/local-path-provisioner:v20240813-c6f155d6                                                                             <---------- local path provisioner is old 20240813 instead of new commited 2024
    Image ID:      sha256:3a195b56ff1540463285c7f6287ef0d4ec18754013f68a3666b363b7893a62ad
      --helper-image
  Normal   Pulled            116s   kubelet            Container image "docker.io/kindest/local-path-provisioner:v20240813-c6f155d6" already present on machine
# docker inspect kind-control-plane | grep -i image
        "Image": "sha256:6f8c6c7369706d82fccee4c7cc352ec1abd76a1d5468a9694b4e440af20a1b3a",
        "Image": "kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e",

```

**Comment by aojea** [comment]
The images for the addons are defined in the code, in this case here

https://github.com/kubernetes-sigs/kind/blob/74acdf744a3566279ddf7e4d7d2e2b364b1ec5bd/pkg/build/nodeimage/const_storage.go#L28-L29

and seems the PR to update the images https://github.com/kubernetes-sigs/kind/pull/3785 is correct ... @BenTheElder is it possible there was an oversight in the build process

**Comment by BenTheElder** [comment]
> is it possible there was an oversight in the build process

It's possible, the node image could've been built with a prior commit.

> Why I'm asking. I want to use new feature of local-path-provisioner ([feature](https://github.com/rancher/local-path-provisioner?tab=readme-ov-file#storage-classes) added "custom path patterns" ([commit](https://github.com/rancher/local-path-provisioner/commit/af85381fd304f3a65999687a5da18536e8a1b1ea)) to version v0.0.30 and v0.0.29.

the local-path-provisioner is still on v0.0.24 currently:
https://github.com/kubernetes-sigs/kind/blob/813f39e43326930ae39226e0b5a7f604836f21d8/images/local-path-provisioner/Makefile#L14

To upgrade it we have to analyze for any other changes required aside from building a new image.

**Comment by BenTheElder** [comment]
If you build your own images they should include it, as a stop-gap https://kind.sigs.k8s.io/docs/user/quick-start/#building-images

But that won't have v0.0.30 / v0.0.29 without further work.

**Comment by BenTheElder** [comment]
We're on v0.0.30 at HEAD, that said, customizing things like the storage class config are very "here be dragons", we consider local-path-provisioner an implementation detail of having a basic functioning PV driver for the standard storage class, and subject to future change if something else meets our needs better.
