### ISSUE TITLE
podman: Unable To Create Cluster Networking on Fedora 41

### ISSUE THREAD

**Issue by adambkaplan** [kubernetes-sigs/kind#3817]
**What happened**:

Podman provider fails to create a cluster running rootless on Fedora 41. This may only impact developers whose machines upgraded to Fedora 41 from Fedora 40 or earlier.

_**Note to community - this is more of a public service announcement than actual bug. Root cause is at the podman/Fedora level**_.

Error:

```
Command Output: Error: netavark: nftables error: unable to execute nft: No such file or directory (os error 2)
```

**What you expected to happen**:

KinD is able to create the cluster

**How to reproduce it (as _minimally_ and precisely as possible)**:

1. Upgrade host from Fedora 40 to Fedora 41 (if this happens on a clean Fedora 41 install, there is a much larger regression in Fedora).
2. Create a default cluster with `kind`

**Anything else we need to know?**:

Related Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=2331672

**Environment:**

- kind version: (use `kind version`): `kind v0.25.0 go1.23.3 linux/amd64`
- Runtime info: (use `docker info`, `podman info` or `nerdctl info`): 

Client:       Podman Engine
Version:      5.3.1
API Version:  5.3.1
Go Version:   go1.23.3
Built:        Wed Nov 20 19:00:00 2024
OS/Arch:      linux/amd64

- OS (e.g. from `/etc/os-release`): Fedora 41
- Kubernetes version: (use `kubectl version`):
- Any proxies or other special environment settings?:

**Comment by aojea** [comment]
> Related Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=2331672

I see the bug was solved so I think we can close this

It seems it was some environmtal issue

/close

**Comment by adambkaplan** [comment]
Yep - was user error on my part.
