### ISSUE TITLE
consider skipping cluster validation from `kind get kube-config`

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/kind#388]
currently `kind get kubeconfig-path` checks if a cluster with `--name x` exists before returning the kubeconfig path. this is not a bug, as the command can also be used as a validator.

in this discussion:
https://kubernetes.slack.com/archives/CEKK1KTN2/p1552940528530500
it was proposed that this command can just return the path even if a cluster doesn't exists and don't fail. commands such as `kind get nodes` can still return errors for non-existent clusters.

/kind design
/priority backlog
/assign @neolit123 @BenTheElder

**Comment by neolit123** [comment]
unless there are objections i will send a PR for this?

**Comment by tao12345666333** [comment]
https://github.com/kubernetes-sigs/kind/blob/fae116145c4cd7885bb334d286a9a9080d91490e/cmd/kind/get/kubeconfigpath/kubeconfigpath.go#L56-L63

Is this part? I agree. 
Thanks. :heart:

**Comment by neolit123** [comment]
@tao12345666333 yes, that's the code.
