### ISSUE TITLE
update CNI version

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#391]
Seems that[ kubernetes bump the CNI version](https://github.com/kubernetes/kubernetes/pull/75455/files) to [0.7.5 ](https://github.com/containernetworking/plugins/releases )to deal with some portmap bugs, it also fixes the Docker IPv6 problem.

I think that we should do the same https://github.com/kubernetes-sigs/kind/blob/0c1210661b5c796eb8953d5dc3b158661e6236cb/images/base/Dockerfile#L80

**Comment by BenTheElder** [comment]
any breaking changes for older kubernetes?

**Comment by aojea** [comment]
this update installs the latest CNI plugins, it doesn't affect Kubernetes per se, only the network plugins that use the standard CNI plugins.
In the `kind` case it's good because `weave` seems to use the standard ` portmap` plugin and this version address some issues with it
