### ISSUE TITLE
0.2.1 release?

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#414]
So far the major changes since 0.2 are:
- Fix for panic on bringup error (less critical since the CLI is exiting with a failure anyhow) https://github.com/kubernetes-sigs/kind/pull/407
- Fix for building on mac / not-linux (fairly critical for kubernetes iteration) https://github.com/kubernetes-sigs/kind/pull/413

I think the latter in particular might warrant a quick patch release.

**Comment by tao12345666333** [comment]
:+1: 

and should we change default node image to kubernetes v1.14 ?

**Comment by BenTheElder** [comment]
a patch release probably shouldn't do that. just bug fixes.

**Comment by neolit123** [comment]
+1

**Comment by tao12345666333** [comment]
Maybe we should fix #417 before publish 0.2.1 ?

**Comment by BenTheElder** [comment]
I don't think so, 0.2.1 had some critical bugs for zero-options usage of kind and is already tagged, users of HA / affected by #417 should be good to install from HEAD once we get a fix in.

**Comment by tao12345666333** [comment]
ok, I agree. :+1:

**Comment by BenTheElder** [comment]
perhaps a second patch release?? :thinking:

I'd like to make releases relatively frequent, but I really want to get these fixes out ASAP (posting the binaries / release notes right now, had to get dinner...)

We should definitely get #417 fixed soon, HA testing is an important feature too.

**Comment by BenTheElder** [comment]
release is done. will look into #417

**Comment by tao12345666333** [comment]
> perhaps a second patch release??

maybe we need. HA is 0.2's important feature.
