### ISSUE TITLE
Too many control plane nodes being built when using tip.

### ISSUE THREAD

**Issue by mauilion** [kubernetes-sigs/kind#436]
**What happened**:
When starting an HA control plane with three nodes. Kind created 4.

**What you expected to happen**:
I expected three.

**How to reproduce it (as minimally and precisely as possible)**:
using:
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
```
creates 8 nodes. 4 control plane 3 workers and an external-load-balancer 

**Anything else we need to know?**:
If I use this:
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
```
Kind will create 3 cp 3 workers and 1 external-load-balancer.

I build kind locally against: 
git rev-parse HEAD
578ac5843ea324e1aa3b05ee4326f9eae26d76ad

You can catch me on #kind in the kubernetes slack.

**Environment:**
- kind version: (use `kind version`): 0.3.0-alpha
- Kubernetes version: (use `kubectl version`): 1.13.4
- Docker version: (use `docker info`): 18.06.0-ce
- OS (e.g. from `/etc/os-release`): ubuntu 18.04.2 LTS

**Comment by mauilion** [comment]
the quintessential off by one error @BenTheElder :)

**Comment by BenTheElder** [comment]
/assign
/priority important-soon
First glance through didn't post this, will debug 🤔🤔🤔

**Comment by neolit123** [comment]
latest master gives me:
```
ERRO[10:52:58] docker run error: exit status 125            
DEBU[10:52:58] Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\t{{.Label "io.k8s.sigs.kind.cluster"}} --filter label=io.k8s.sigs.kind.cluster=kind] 
ERRO[10:52:58] docker: invalid reference format.
```

```
docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
...
```

**Comment by neolit123** [comment]
something seems wrong with 18.06.3-ce - it just fails and ha-proxy stage in a HA setup and i couldn't get more details why. will inivestigate, but this used to work with docker 17*

**Comment by aojea** [comment]
I can't reproduce it on master, I can't see any additional node

I have docker ` 18.09.0` 

```
$ git rev-parse HEAD
c6ef81cab146ffd66a6545dd8c23437659def55c
$ cat issue436.yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
$ ./kind create cluster --config issue436.yaml
...
$ ./kind get nodes
kind-control-plane
kind-control-plane2
kind-control-plane3
kind-worker
kind-worker3
kind-external-load-balancer
kind-worker2
```

**Comment by mauilion** [comment]
that was my bad I am running 18.06.0-ce

**Comment by mauilion** [comment]
Also I found the issue. incomplete data on my side.

my original config was
https://gist.githubusercontent.com/mauilion/03f708f39c518a169b30aa3341848f84/raw/kind%2520config

and kind was apparently creating a node for every entry in nodes. 

The odd thing is that the kubeadm patch applied cleanly!

I've moved the kubeadm patch bit up to the `node:` level and things work as expected.

**Comment by BenTheElder** [comment]
Right, your patch is being defaulted to control plane role, nodes is a list of nodes :^). The patch behavior is currently cluster wide only. v1alpha2 was misleading vs the implementation. Better patch behavior is in the works 😅

**Comment by mauilion** [comment]
awesome I will close this for now :)
