### ISSUE TITLE
go get:Unrecognized import path sigs.k8s.io/kind

### ISSUE THREAD

**Issue by chenliu1993** [kubernetes-sigs/kind#438]
I am using go get to install kind following the instructions listed in README.md. My computer has set proxy. But I got this error "unrecognized import path 'sigs.k8s.io/kind'. connection refused.......". And I also try to install kind on VM , issue still  exists. 
What solutions can I use to solve this problem? Much appreciated by your help!

**Comment by chenliu1993** [comment]
Docker and go are installed. Centos,  Ubuntu and Mac all have the same issue.

**Comment by tao12345666333** [comment]
please run `go get -v -u sigs.k8s.io/kind` to show detail logs.

**Comment by chenliu1993** [comment]
> please run `go get -v -u sigs.k8s.io/kind` to show detail logs.

It only shows "Fetching from https://sigs.k8s.io/kind/go&&get==1", then next line is the issue.

**Comment by tao12345666333** [comment]
> My computer has set proxy.

you can check your proxy. 
and try to run `curl -vvv https://sigs.k8s.io/kind`.

**Comment by chenliu1993** [comment]
> > My computer has set proxy.
> 
> you can check your proxy.
> and try to run `curl -vvv https://sigs.k8s.io/kind`.

Thank you! I will try out right now.

**Comment by chenliu1993** [comment]
> > My computer has set proxy.
> 
> you can check your proxy.
> and try to run `curl -vvv https://sigs.k8s.io/kind`.

Sorry , my computer just broke down. 
I tried your advice ,still can't install
command:go get will get this 
![image](https://user-images.githubusercontent.com/13761170/55791899-14428500-5af2-11e9-8ef6-095cb710c1b4.png)
command curl -vvv https://sigs.k8s.io/kind get this:
![image](https://user-images.githubusercontent.com/13761170/55791933-2a504580-5af2-11e9-8a66-03990d889748.png)

**Comment by chenliu1993** [comment]
![image](https://user-images.githubusercontent.com/13761170/55792005-4fdd4f00-5af2-11e9-85e6-02db92450d3d.png)
![image](https://user-images.githubusercontent.com/13761170/55791966-40f69c80-5af2-11e9-8858-51370bbba121.png)

**Comment by tao12345666333** [comment]
Your network seems to hang up. 

```
[zhang@localhost ~]$ curl -vvv https://sigs.k8s.io/kind
* About to connect() to sigs.k8s.io port 443 (#0)
*   Trying 35.201.71.162...
* Connected to sigs.k8s.io (35.201.71.162) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=k8s.io
*       start date: 1月 11 21:27:54 2019 GMT
*       expire date: 4月 11 21:27:54 2019 GMT
*       common name: k8s.io
*       issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
> GET /kind HTTP/1.1
> User-Agent: curl/7.29.0
> Host: sigs.k8s.io
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.10.3
< Date: Tue, 09 Apr 2019 10:11:29 GMT
< Content-Type: text/html
< Content-Length: 185
< Location: https://github.com/kubernetes-sigs/kind
< Via: 1.1 google
< Alt-Svc: clear
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
* Connection #0 to host sigs.k8s.io left intact
```

**Comment by tao12345666333** [comment]
@chenliu1993 you should check your proxy.

when i run `curl -vvv https://sigs.k8s.io/kind` without proxy I can get the same error.

```
[root@no-proxy ~]$ curl -vvv https://sigs.k8s.io/kind
* About to connect() to sigs.k8s.io port 443 (#0)
*   Trying 35.201.71.162...
* Connection timed out
* Failed connect to sigs.k8s.io:443; Connection timed out
* Closing connection 0
curl: (7) Failed connect to sigs.k8s.io:443; Connection timed out

```

**Comment by chenliu1993** [comment]
> @chenliu1993 you should check your proxy.
> when i run curl -vvv https://sigs.k8s.io/kind without proxy I can get the same error.
> [root@no-proxy ~]$ curl -vvv https://sigs.k8s.io/kind
> * About to connect() to sigs.k8s.io port 443 (#0)
> *   Trying 35.201.71.162...
> * Connection timed out
> * Failed connect to sigs.k8s.io:443; Connection timed out
> * Closing connection 0
> curl: (7) Failed connect to sigs.k8s.io:443; Connection timed out

Ok, it seems proxy doesn't take effect like you say......, I will check this out. much appreciated.

**Comment by tao12345666333** [comment]
i will close this issue now. if you still have problems, feel free to reopen it.

/close
