### ISSUE TITLE
Is Kubernetes Kind cluster node running as a pod in the whole cluster container?

### ISSUE THREAD

**Issue by yuchen9459** [kubernetes-sigs/kind#441]
I'm using kind to create Kubernetes clusters and learn some stuff about Kubernetes and service mesh. I went through the documents of kind, but I still have a question.

As I know, the minikube launch a cluster in a Virtual Machine. If uses create 2 Minikube clusters, there are two VMs running. If I understand it correctly, kind cluster runs in a container, and a kind cluster can be composed with several nodes, does that mean each node is a pod running in the kind cluster container?

**Comment by tao12345666333** [comment]
> each node is a pod running in the kind cluster container

no. each node is a container on your host machine. please see https://kind.sigs.k8s.io/docs/design/node-image/#the-node-image

**Comment by tao12345666333** [comment]
if you run any pod in your kind cluster, each pod will in your container. (means docker in docker) 

ref: https://kind.sigs.k8s.io/docs/design/initial/#overview
![image](https://user-images.githubusercontent.com/3264292/55949357-fce7d100-5c84-11e9-8b40-030d0a3bf6e6.png)

**Comment by yuchen9459** [comment]
> if you run any pod in your kind cluster, each pod will in your container. (means docker in docker)
> 
> ref: https://kind.sigs.k8s.io/docs/design/initial/#overview
> ![image](https://user-images.githubusercontent.com/3264292/55949357-fce7d100-5c84-11e9-8b40-030d0a3bf6e6.png)

Thanks! If both control-plane and worker nodes are running as a container, clusters are separated by docker object label key. Does that mean the cluster is a logical cluster defined by the cluster name/ID, but they are just a bunch of running container nodes in the same host machine?

**Comment by neolit123** [comment]
you can create multiple clusters on the same host and their containers (nodes) will be prefixed with the cluster name:
`kind create cluster some-cluster`
would give you containers (nodes) called `some-cluster-worker2`

**Comment by BenTheElder** [comment]
> Does that mean the cluster is a logical cluster defined by the cluster name/ID, but they are just a bunch of running container nodes in the same host machine?

~ yes, the "node" containers are labeled with their cluster name (`--name` flag).

We do run kind in a pod sometimes #303, but locally each node is a container.

**Comment by BenTheElder** [comment]
Let me know if you have more questions 😊
