### ISSUE TITLE
Errors compile: version "go1.12.1" does not match go tool version "go1.10.2"

### ISSUE THREAD

**Issue by csantanapr** [kubernetes-sigs/kind#444]
**What happened**:
Can't get started with `kind`
The command `go get -u sigs.k8s.io/kind` gives errors
```
go get -u sigs.k8s.io/kind
# errors
compile: version "go1.12.1" does not match go tool version "go1.10.2"
# internal/race
compile: version "go1.12.1" does not match go tool version "go1.10.2"
# unicode/utf8
```

**What you expected to happen**:
kind to be in `$GOPATH/bin/kind`

**How to reproduce it (as minimally and precisely as possible)**:
Setup go 1.12.1 on mac and run command 
**Anything else we need to know?**:

**Environment:**
```
$ go version
go version go1.10.2 darwin/amd64
$ uname -a
Darwin MBP.attlocal.net 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

- kind version: (use `kind version`):
latest from master

**Comment by BenTheElder** [comment]
Something is wrong with your go setup.

You say:
> Setup go 1.12.1 on mac and run command

But your output showed:
```
$ go version
go version go1.10.2 darwin/amd
```

This is not a bug in kind, I'm not sure how this state happened. How did you setup go?

**Comment by BenTheElder** [comment]
Similar issue: https://github.com/golang/go/issues/22814

**Comment by csantanapr** [comment]
Thanks 💯 @BenTheElder for the fast response, I will look at my path and gopath, I’m using gimme so it must be an old Go in my PATH

**Comment by shankernaik** [comment]
Thanks @BenTheElder
