### ISSUE TITLE
Start Node Suffix at "1"

### ISSUE THREAD

**Issue by phenixblue** [kubernetes-sigs/kind#447]
**What would you like to be added**:

Modify `makeNodeNamer` to start node suffix with `1` instead of `""`

**Why is this needed**:

This will make node names more uniform by following a standard pattern for all nodes:

`<cluster_name>-<node_type><node_instance>`

**Comment by BenTheElder** [comment]
This is a breaking change for anyone depending on the node names that isn't obtaining them from eg `kubectl get no`.

**Comment by phenixblue** [comment]
After chatting with @BenTheElder I'm going to close this. Seems out of scope for pushing towards stability in core features.
