### ISSUE TITLE
[Question] How to use HELM via KIND

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kind#450]
Just a question here, can I use helm when using KIND? If this is supported, how to enable helm with KIND?

**Comment by neolit123** [comment]
/remove-kind bug
/triage support
you should be able to use helm the same way you can use kubectl on the running cluster.
please read here:
https://helm.sh/docs/using_helm/

**Comment by gyliu513** [comment]
make sense, thanks @neolit123
