### ISSUE TITLE
Support more port forwards

### ISSUE THREAD

**Issue by costinm** [kubernetes-sigs/kind#459]
**What would you like to be added**:

An option to kind to expose more ports on the host, in addition to the apiserver port.

**Why is this needed**:

Running an Istio Gateway - which may expose various TCP and HTTP ports. We need to test 
multi-cluster and other features.

**Comment by costinm** [comment]
Currently the workaround is to attach a docker container to the same network namespace and expose the ports via some socat or gateway - but it seems complex and fragile. We'll probably try it if this can't be solved in a reasonable timeframe...

**Comment by BenTheElder** [comment]
this is https://github.com/kubernetes-sigs/kind/issues/99

the other option for most kind users is `kubectl port-forward` but that's not going to work here.

have plans to add options for this, it will get slightly confusing for multi-node clusters, interested in proposed solutions.

**Comment by costinm** [comment]
The workaround would work for any container - so I assume it can be use to expose 'nodePort' from multi-node clusters as well, as long as each node runs in a separate container.
 
Could we have some 'kind expose port' command taking a 'node' and port pair ? Would work for multi-cluster and multi-node clusters.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/99#issuecomment-505662768

this can be done at node (cluster) creation time now, we'll revisit a more complex solution in the future if necessary.
