### ISSUE TITLE
[ChromeOS] Error Preparing Nodes. Exit 32

### ISSUE THREAD

**Issue by luckielordie** [kubernetes-sigs/kind#462]
**What happened**:
Running `kind create cluster` results in the application halting at "preparing node" step and responding with exit status 32

**What you expected to happen**:
A cluster being created successfully

**How to reproduce it (as minimally and precisely as possible)**:
I'm running on a pixelbook. Given this, I assume this could be reproduced by running kind from inside and LXD container. Although I haven't tried given my limited understanding. 

**Anything else we need to know?**:
Here is an output log of the command `kind create cluster --loglevel debug`
```
time="09:56:50" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}}]"
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.13.4) 🖼  ...
time="09:56:51" level=debug msg="Running: /usr/bin/docker [docker inspect --type=image kindest/node:v1.13.4]"
time="09:56:51" level=info msg="Image: kindest/node:v1.13.4 present locally"
 ✓ Ensuring node image (kindest/node:v1.13.4) 🖼
 • Preparing nodes 📦  ...
time="09:56:51" level=debug msg="Running: /usr/bin/docker [docker info --format '{{json .SecurityOptions}}']"
time="09:56:52" level=debug msg="Running: /usr/bin/docker [docker run -d --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname kind-control-plane --name kind-control-plane --label io.k8s.sigs.kind.cluster=kind --label io.k8s.sigs.kind.role=control-plane --entrypoint=/usr/local/bin/entrypoint --expose 43865 -p 127.0.0.1:43865:6443 kindest/node:v1.13.4 /sbin/init]"
time="09:56:53" level=debug msg="Running: /usr/bin/docker [docker exec --privileged kind-control-plane rm -f /etc/machine-id]"
time="09:56:53" level=debug msg="Running: /usr/bin/docker [docker exec --privileged kind-control-plane systemd-machine-id-setup]"
time="09:56:54" level=debug msg="Running: /usr/bin/docker [docker info --format '{{json .SecurityOptions}}']"
time="09:56:54" level=debug msg="Running: /usr/bin/docker [docker exec --privileged kind-control-plane mount -o remount,ro /sys]"
 ✗ Preparing nodes 📦
time="09:56:54" level=error msg="exit status 32"
time="09:56:54" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}} --filter label=io.k8s.sigs.kind.cluster=kind]"
time="09:56:54" level=debug msg="Running: /usr/bin/docker [docker rm -f -v kind-control-plane]"
```
**Environment:**

- kind version: (use `kind version`): 0.3.0-alpha
- Kubernetes version: (use `kubectl version`): v1.14.1
- Docker version: (use `docker info`): 19.03.0-beta3
- OS (e.g. from `/etc/os-release`):Debian 9 (stretch) Running inside the Linux Beta on a Google Pixelbook

**Comment by aojea** [comment]
@lucperkins please check if this solution to run under LXD works for you https://github.com/kubernetes-sigs/kind/issues/455

**Comment by luckielordie** [comment]
So I've done the same as the user there and ran 
```docker run -it --privileged --rm ubuntu
root@4ee4aacd1f88:/# cat /proc/sys/kernel/panic_on_oops
0
root@4ee4aacd1f88:/# cat /proc/sys/vm/overcommit_memory
0
```
I'm not sure what the user found useful in those links. Sorry if I'm missing something.

**Comment by aojea** [comment]
@luckielordie check https://github.com/kubernetes-sigs/kind/issues/455#issuecomment-487262075 it seems that the default apparmor profile is too restrictive

**Comment by luckielordie** [comment]
I guess I need to find a way to change these settings for ChromeOS

**Comment by BenTheElder** [comment]
FWIW I'd love to see this work, I just haven't had a chance to get my hands on a chromebook with enough resources and try setting this up. I would guess this is indeed the security restrictions getting in the way, and we may not be able to make this work though.

**Comment by BenTheElder** [comment]
[removing bug because I don't think there's any changes to the kind binary that will fix this, I suspect there may be some workaround outside of kind though, which we should document when / if we find it]

**Comment by luckielordie** [comment]
I'm looking at this at the moment, enlisted some friendly chaps from the ChromeOS Discord server.

**Comment by BenTheElder** [comment]
this one is older, however we have more details here: https://github.com/kubernetes-sigs/kind/issues/763

de-duping 😬
