### ISSUE TITLE
remove base-image sources from kind binary

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#488]
**What should be cleaned up or changed**: we should remove the code generation / baked in sources for `kind build base-image`.

**Why is this needed**: These are unnecessary bloat in retrospect, if you wish to build the base image you're going to want to be able to tweak the sources, we did not wind up exposing any other configuration options for this build related to the contents.

We can remove this, and instead by default autodetect the kind sources location the same as we do for kubernetes, we already have an explicit option to select the sources.

/assign

cc @aojea @neolit123 @tao12345666333 @fabriziopandini

**Comment by BenTheElder** [comment]
this is a breaking change, but hopefully unlikely to break many (any?) users

**Comment by tao12345666333** [comment]
SGTM  :+1: 

Now is the alpha stage, we can do something like this. :thinking:
