### ISSUE TITLE
Use go modules compatible tags

### ISSUE THREAD

**Issue by tommyknows** [kubernetes-sigs/kind#499]
**What happened**:

The tags in this repository are named `0.2.1`, `0.2.0`, `0.1.0`, `0.0.1`
When executing go get with modules enabled, it always gets the latest version, not a tagged one, because it expects semver tags prefixed with a `v`, meaning tags like `v0.2.1`.

**What you expected to happen**:

Go get fetches the last tagged (valid) semver release.

> In this section, "latest" is the latest version with a semver tag, or the latest known commit if there are no semver tags. 

https://github.com/golang/go/wiki/Modules#how-to-upgrade-and-downgrade-dependencies

**How to reproduce it (as minimally and precisely as possible)**:

`go get sigs.k8s.io/kind`

**Comment by BenTheElder** [comment]
That's a bit annoying, https://semver.org/ does not use a leading v 🙄

**Comment by BenTheElder** [comment]
We will use vX.Y.Z going forward.
/assign

**Comment by BenTheElder** [comment]
I've pushed vX.Y.Z tags for every existing X.Y.Z tag, please let me know if you have any problems. I'm looking at converting the repo fully to modules now :sweat_smile:
