### ISSUE TITLE
kind install <pkg>

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#506]
**What would you like to be added**:

I would like a new command that allows the user to install the pkgs provided in the command line in all the nodes or in a subset of them. Similar to the curren ` kind load-image` command.

` kind install tcpdump vim` 
` kind install tcpdump vim --nodes ...` 

**Why is this needed**:

In order to reduce the image size there are a lot of tools that are removed because are no needed and is difficult to reach a consensus as we can see in #339. However, sometimes you need to install your own set of tools to troubleshoot problems or to develop new features, having this feature will simplify the process.

**Comment by BenTheElder** [comment]
I don't think this should be a kind command. you can simply do:

```
FROM kindest/node:foo-version
RUN clean-install foo
```

or
`docker exec kind-control-plane clean-install foo`

**Comment by BenTheElder** [comment]
installing packages correctly also comes with things like supporting selecting specific package versions, managing the apt repository lists / gpg keys, locking ourselves into using an apt / debian based image ...

advanced users can pretty easily customize this today without a built in kind command.

**Comment by tao12345666333** [comment]
I agree with @BenTheElder . This is not necessary bind kind with package manage tool.

**Comment by aojea** [comment]
👍 you've convinced me
