### ISSUE TITLE
Document different hacks to expose ports

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#507]
**What would you like to be documented**:

We should document the different methods to forward ports so users can access cluster services in all the supported OS (Mac, Linux, Windows)

**Why is this needed**:

Supporting port forwards is very demanded #459 #99  and there are several hacks that can be used.
Aggregating and documenting the different options can give users different choices and help the `kind` community to understand better the use cases.

**Comment by BenTheElder** [comment]
[also just noting that we intend to support something first class, these are options that can potentially be enabled with built-in support]

**Comment by aojea** [comment]
I think that we had some kind of agreement that ideally we should have a `kind` load balancer provider that allows users to reach services with Virtual IPs independently of the OS

**Comment by michael-burt** [comment]
Is there a standard way to simply port-forward into a pod? Is there documentation about how to accomplish this?

**Comment by aojea** [comment]
@michael-burt please check the draft document and provide your feedback https://github.com/kubernetes-sigs/kind/pull/546 in the PR

**Comment by BenTheElder** [comment]
`kubectl port-forward` is the most standard way applicable to any kubernetes setup not just kind. but we'd like something a little more robust for kind.

on linux you can also reach the node IPs directly and go from there (EG with a nodePort)

**Comment by BenTheElder** [comment]
not sure how much we need this now that we have extra ports via https://github.com/kubernetes-sigs/kind/issues/99#issuecomment-505662768

**Comment by BenTheElder** [comment]
(which is documented)

**Comment by aojea** [comment]
Indeed
