### ISSUE TITLE
There is no more docker executable inside the kind container

### ISSUE THREAD

**Issue by mitar** [kubernetes-sigs/kind#508]
**What happened**:

Since few days ago our CI started failing.

**What you expected to happen**:

To not fail.

**How to reproduce it (as minimally and precisely as possible)**:

```
go get -u sigs.k8s.io/kind
kind create cluster
docker exec -i kind-control-plane docker ps
```

I get this error:

```
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"docker\": executable file not found in $PATH": unknown
```

- kind version: (use `kind version`): `0.3.0-alpha`
- Kubernetes version: (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-05-05T22:08:19Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version: (use `docker info`): 18.09.5
- OS (e.g. from `/etc/os-release`): Ubunut 18.04.2 LTS

**Comment by BenTheElder** [comment]
This is intended, we're running containerd in HEAD now

**Comment by mitar** [comment]
Hm, maybe I should then not be installing kind using `go get -u sigs.k8s.io/kind` if such types of changes are occurring?

**Comment by BenTheElder** [comment]
yeah, sorry about that :(

I intend to cut a new release before kubecon NA (~next week) with detailed release notes, we finally decided to make some big improvements that required breaking changes 😬

**Comment by mitar** [comment]
Is there a way to pin which version is installed?

**Comment by mitar** [comment]
So how would I get the latest version with `docker`?

**Comment by BenTheElder** [comment]
if you do `git clone https://github.com/kubernetes-sigs/kind` somewhere and build it with new enough go to use go modules you should be able to check out a commit before building

**Comment by costinm** [comment]
Can you add a tag or branch on a version that works ? We are using kind in pipelines and it breaks pretty much everything.

**Comment by costinm** [comment]
Or even better: do breaking changes in a separate branch and keep master stable.

**Comment by BenTheElder** [comment]
we do have release tags currently, and we'll have another one soon. there are also pre-built binaries from the releases.

**Comment by BenTheElder** [comment]
To clarify: kind works fine in HEAD, we have continuous integration with conformance tests, most of the "breaking" changes involve when unspecified details like the node CRI are being used, which is not intended. 

`v0.2.1` is the most recent release tag. ref: #499 

In this case the only other breaking change is that kind at HEAD requires newly built images, the default image is one.

**Comment by mitar** [comment]
Hm, `go get -u sigs.k8s.io/kind@0.2.1` does not seem to work. I am not too familiar with go though.

**Comment by BenTheElder** [comment]
`GO111MODULE="on" go get -u sigs.k8s.io/kind@v0.2.1` except that is failing due to https://github.com/golang/lint/issues/436 :/

will fixup for the next tag, in the meantime:

`git clone https://github.com/kubernetes-sigs/kind && cd kind && git checkout v0.2.1 && go install .`

**Comment by mitar** [comment]
Now working for me:

```
Cloning into 'kind'...
Note: checking out 'v0.2.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 5e29284 version 0.2.1
main.go:21:2: cannot find package "sigs.k8s.io/kind/cmd/kind" in any of:
	/usr/lib/go-1.10/src/sigs.k8s.io/kind/cmd/kind (from $GOROOT)
	/usr/local/go/src/sigs.k8s.io/kind/cmd/kind (from $GOPATH)
```

**Comment by BenTheElder** [comment]
that output looks like you are building with a go old enough to not auto-enable modules when not in go path, or you've cloned into go path but not at `$GOPATH/src/sigs.k8s.io/kind` and module mode is not enabled.

either:
- upgrade go
- clone to ${GOPATH}/src/sigs.k8s.io/kind as if downloaded by `go get`

**Comment by mitar** [comment]
I am using `go` available with Ubuntu 18.04 LTS: https://packages.ubuntu.com/bionic/golang

I would hope kind can work with what is available on LTS of Ubuntu?

FYI, it worked just until few days ago. I just replaced `go get sigs.k8s.io/kind` with what you linked: https://gitlab.com/datadrivendiscovery/images/commit/5a2c352cc048e36c71d5537127f8a2fc55f4fa35

**Comment by mitar** [comment]
OK, I think I did the second thing here: https://gitlab.com/datadrivendiscovery/images/commit/1a19bed2aee91a05304674382b3c80d31a53ddf7

**Comment by BenTheElder** [comment]
yeah unfortunately kubernetes does not support building with https://packages.ubuntu.com/bionic/golang (go1.10) either, ubuntu's package is often rather behind.

go 1.10 is not even supported upstream by golang now (as 1.11 and 1.12 are out https://golang.org/doc/devel/release.html#policy), go versions are supported for about 1 year.

Kubernetes provides make + docker target that will not use the host go to avoid these issues, we are providing the same now.

**Comment by BenTheElder** [comment]
I apologize for the `docker` breakage here, but we are going to move forward with that particular change as the stability and performance gains are significant so far:
- smaller images by 100s of MBs just from dockerd -> containerd and trimming related packages
- fully preloaded images, no load step at runtime (possible due to containerd architecture and guarantees)
  - smaller images by 100s of MBs from this as well, as images are preloaded by layers instead
  - faster boot (if the node image is already pulled, can be ~40% faster for single node)
- using CRI paths in kubernetes, which should be the supported path forward vs dockershim
- ...

We discussed this quite a bit on slack, in the project meeting, and on the PRs. I'll make sure the 0.3 release notes at least cover this properly, I'm not sure how else to best communicate this sort of change. The main hope currently is to rapidly identify changes we should make and get to beta grade. 

ref #509 for build changes.
