### ISSUE TITLE
node "localhost.localdomain" not found

### ISSUE THREAD

**Issue by chenliu1993** [kubernetes-sigs/kind#521]
Hi all,
    I am using kind node image to run the kubernetes. But each time I use command "kind create cluster", the control-plane node fails at kubeadm init step. The error is "node 'localhost.localdomain' not found".  But kubelet and docker is active while the images like etcd and api server are loaded but not running.
  "cat /etc/hosts" shows "127.0.0.1   localhost.localdomain".
  "hostname" shows localhost.localdomain.
  The kernel is Linux 4.9.137, kubernetes version os v1.13.4 and there is no proxy settings 
  Any advice will be much appreciated.

**Comment by BenTheElder** [comment]
Docker will filter out any localhost references from /etc/hosts when creating the node container because the host's loopback interface (localhost) is not reachable from inside the container.

We explicitly set the node's hostname though, I'm not sure why Kubernetes / kubeadm would be using this entry. In the past there was a bug where resolv.conf was missing from the components, but that should be true anymore 🤔

**Comment by BenTheElder** [comment]
What is your DNS resolver on the host?
/assign

I think we may need to stop inheriting the host's DNS...

**Comment by chenliu1993** [comment]
> DNS resolver

Thanks for your advice!
This is the content  of /etc/resolv.conf:
  search localdomain
  nameserver 192.168.5.2
This is the content  of /etc/hosts:
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1   localhost localhost.localdomain localhost4 localhost4.localdomain4

**Comment by chenliu1993** [comment]
> What is your DNS resolver on the host?
> /assign
> 
> I think we may need to stop inheriting the host's DNS...

Thanks for your advice!
This is the content of /etc/resolv.conf:
search localdomain
nameserver 192.168.5.2
This is the content of /etc/hosts:
127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
::1 localhost localhost.localdomain localhost4 localhost4.localdomain4

**Comment by chenliu1993** [comment]
> What is your DNS resolver on the host?
> /assign
> 
> I think we may need to stop inheriting the host's DNS...

This is the output of "systemctl status kubelet -l":
**ΓùÅ kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/kind/systemd/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           ΓööΓöÇ10-kubeadm.conf
   Active: active (running) since Mon 2019-05-13 13:55:27 UTC; 4min 43s ago
     Docs: http://kubernetes.io/docs/
 Main PID: 702 (kubelet)
   CGroup: /system.slice/kubelet.service
           ΓööΓöÇ702 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=cgroupfs --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1 --fail-swap-on=false

May 13 13:59:16 localhost.localdomain kubelet[702]: W0513 13:59:16.038722     702 pod_container_deletor.go:75] Container "743b67d1d40cdea0ab805ce83b6bcfa6795c98c4caf1bc41c8939436910ff639" not found in pod's containers
May 13 13:59:16 localhost.localdomain kubelet[702]: I0513 13:59:16.093699     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:16 localhost.localdomain kubelet[702]: I0513 13:59:16.094217     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:16 localhost.localdomain kubelet[702]: E0513 13:59:16.099552     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:16 localhost.localdomain kubelet[702]: W0513 13:59:16.106422     702 pod_container_deletor.go:75] Container "3222cf97634a609eb10a435925e9800f2d7b38ad6c4b5f04cbade60a9d964b90" not found in pod's containers
May 13 13:59:16 localhost.localdomain kubelet[702]: I0513 13:59:16.161232     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:16 localhost.localdomain kubelet[702]: I0513 13:59:16.161762     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:16 localhost.localdomain kubelet[702]: W0513 13:59:16.165015     702 pod_container_deletor.go:75] Container "f0c1e39ae91ab2df59d3f07ae0572ecc811773b19175ea0f67c5dca7ed2a271e" not found in pod's containers
May 13 13:59:16 localhost.localdomain kubelet[702]: E0513 13:59:16.200252     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:16 localhost.localdomain kubelet[702]: E0513 13:59:16.300671     702 kubelet.go:2266] node "localhost.localdomain" not found**
This is part of the output of "journalctl -xeu kubelet":
**reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://192.168.5.130:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.5.130:6443: connect: connection refused
May 13 13:59:14 localhost.localdomain kubelet[702]: E0513 13:59:14.464673     702 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://192.168.5.130:6443/api/v1/nodes?fieldSelector=metadata.name%3Dlocalhost.localdomain&limit=500&resourceVersion=0: dial tcp 192.168.5.130:6443: connect: connection refused
May 13 13:59:14 localhost.localdomain kubelet[702]: E0513 13:59:14.465857     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:14 localhost.localdomain kubelet[702]: E0513 13:59:14.566821     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:14 localhost.localdomain kubelet[702]: E0513 13:59:14.667732     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:14 localhost.localdomain kubelet[702]: I0513 13:59:14.729315     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:14 localhost.localdomain kubelet[702]: I0513 13:59:14.730753     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:14 localhost.localdomain kubelet[702]: W0513 13:59:14.739964     702 pod_container_deletor.go:75] Container "9844496a8c96f9924b32d73b09690ddfd4c273d28185f3580e545b49d55ed9a9" not found in pod's containers
May 13 13:59:14 localhost.localdomain kubelet[702]: I0513 13:59:14.769250     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:14 localhost.localdomain kubelet[702]: I0513 13:59:14.769911     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:14 localhost.localdomain kubelet[702]: E0513 13:59:14.770373     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:14 localhost.localdomain kubelet[702]: W0513 13:59:14.779690     702 pod_container_deletor.go:75] Container "63cc19d0fd4a3717198d0694db9bae6dd3ac2d0e3de5591021f06e2141a5e950" not found in pod's containers
May 13 13:59:14 localhost.localdomain kubelet[702]: I0513 13:59:14.828469     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:14 localhost.localdomain kubelet[702]: I0513 13:59:14.829302     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:14 localhost.localdomain kubelet[702]: W0513 13:59:14.855652     702 pod_container_deletor.go:75] Container "538ccee9fe62f3664be0a8704ba5a556d541fdc29027584a85814fdcf9dc868f" not found in pod's containers
May 13 13:59:14 localhost.localdomain kubelet[702]: E0513 13:59:14.875185     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:14 localhost.localdomain kubelet[702]: I0513 13:59:14.904175     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:14 localhost.localdomain kubelet[702]: I0513 13:59:14.904495     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:14 localhost.localdomain kubelet[702]: W0513 13:59:14.906360     702 pod_container_deletor.go:75] Container "d74c5207581dde30e51386592ef547572401e90a8aa6d4f47d08385d2d23f588" not found in pod's containers
May 13 13:59:14 localhost.localdomain kubelet[702]: E0513 13:59:14.975725     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.076109     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.176583     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.277725     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.326944     702 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-apiserver-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.326966     702 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "kube-apiserver-localhost.localdomain_kube-system(a9b7dd24584050387fb803d4e69019ca)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-apiserver-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.326977     702 kuberuntime_manager.go:662] createPodSandbox for pod "kube-apiserver-localhost.localdomain_kube-system(a9b7dd24584050387fb803d4e69019ca)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-apiserver-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.327005     702 pod_workers.go:190] Error syncing pod a9b7dd24584050387fb803d4e69019ca ("kube-apiserver-localhost.localdomain_kube-system(a9b7dd24584050387fb803d4e69019ca)"), skipping: failed to "CreatePodSandbox" for "kube-apiserver-localhost.localdomain_kube-system(a9b7dd24584050387fb803d4e69019ca)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-apiserver-localhost.localdomain_kube-system(a9b7dd24584050387fb803d4e69019ca)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"kube-apiserver-localhost.localdomain\": Error response from daemon: cgroups: cgroup deleted: unknown"
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.378486     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.379064     702 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "etcd-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.379081     702 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "etcd-localhost.localdomain_kube-system(a361a9003854b880f1b896a25e6d91b9)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "etcd-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.379090     702 kuberuntime_manager.go:662] createPodSandbox for pod "etcd-localhost.localdomain_kube-system(a361a9003854b880f1b896a25e6d91b9)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "etcd-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.379117     702 pod_workers.go:190] Error syncing pod a361a9003854b880f1b896a25e6d91b9 ("etcd-localhost.localdomain_kube-system(a361a9003854b880f1b896a25e6d91b9)"), skipping: failed to "CreatePodSandbox" for "etcd-localhost.localdomain_kube-system(a361a9003854b880f1b896a25e6d91b9)" with CreatePodSandboxError: "CreatePodSandbox for pod \"etcd-localhost.localdomain_kube-system(a361a9003854b880f1b896a25e6d91b9)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"etcd-localhost.localdomain\": Error response from daemon: cgroups: cgroup deleted: unknown"
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.382320     702 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-controller-manager-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.382337     702 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "kube-controller-manager-localhost.localdomain_kube-system(721a27dac190bee34730703b3377eca9)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-controller-manager-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.382345     702 kuberuntime_manager.go:662] createPodSandbox for pod "kube-controller-manager-localhost.localdomain_kube-system(721a27dac190bee34730703b3377eca9)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-controller-manager-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.382369     702 pod_workers.go:190] Error syncing pod 721a27dac190bee34730703b3377eca9 ("kube-controller-manager-localhost.localdomain_kube-system(721a27dac190bee34730703b3377eca9)"), skipping: failed to "CreatePodSandbox" for "kube-controller-manager-localhost.localdomain_kube-system(721a27dac190bee34730703b3377eca9)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-controller-manager-localhost.localdomain_kube-system(721a27dac190bee34730703b3377eca9)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"kube-controller-manager-localhost.localdomain\": Error response from daemon: cgroups: cgroup deleted: unknown"
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.391382     702 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-scheduler-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.391403     702 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "kube-scheduler-localhost.localdomain_kube-system(4b52d75cab61380f07c0c5a69fb371d4)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-scheduler-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.391412     702 kuberuntime_manager.go:662] createPodSandbox for pod "kube-scheduler-localhost.localdomain_kube-system(4b52d75cab61380f07c0c5a69fb371d4)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-scheduler-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.391443     702 pod_workers.go:190] Error syncing pod 4b52d75cab61380f07c0c5a69fb371d4 ("kube-scheduler-localhost.localdomain_kube-system(4b52d75cab61380f07c0c5a69fb371d4)"), skipping: failed to "CreatePodSandbox" for "kube-scheduler-localhost.localdomain_kube-system(4b52d75cab61380f07c0c5a69fb371d4)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-scheduler-localhost.localdomain_kube-system(4b52d75cab61380f07c0c5a69fb371d4)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"kube-scheduler-localhost.localdomain\": Error response from daemon: cgroups: cgroup deleted: unknown"
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.452167     702 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.5.130:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dlocalhost.localdomain&limit=500&resourceVersion=0: dial tcp 192.168.5.130:6443: connect: connection refused
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.465916     702 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://192.168.5.130:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.5.130:6443: connect: connection refused
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.467308     702 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://192.168.5.130:6443/api/v1/nodes?fieldSelector=metadata.name%3Dlocalhost.localdomain&limit=500&resourceVersion=0: dial tcp 192.168.5.130:6443: connect: connection refused
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.483256     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.586410     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.692258     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.793126     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.894129     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:15 localhost.localdomain kubelet[702]: I0513 13:59:15.984908     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:15 localhost.localdomain kubelet[702]: I0513 13:59:15.985568     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:15 localhost.localdomain kubelet[702]: W0513 13:59:15.995545     702 pod_container_deletor.go:75] Container "2a46f25d14c7d970261626329b0aa1b770dcfaad901c61176376d230eb14a14a" not found in pod's containers
May 13 13:59:15 localhost.localdomain kubelet[702]: E0513 13:59:15.999355     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:16 localhost.localdomain kubelet[702]: I0513 13:59:16.034482     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:16 localhost.localdomain kubelet[702]: I0513 13:59:16.034966     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:16 localhost.localdomain kubelet[702]: W0513 13:59:16.038722     702 pod_container_deletor.go:75] Container "743b67d1d40cdea0ab805ce83b6bcfa6795c98c4caf1bc41c8939436910ff639" not found in pod's containers
May 13 13:59:16 localhost.localdomain kubelet[702]: I0513 13:59:16.093699     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:16 localhost.localdomain kubelet[702]: I0513 13:59:16.094217     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:16 localhost.localdomain kubelet[702]: E0513 13:59:16.099552     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:16 localhost.localdomain kubelet[702]: W0513 13:59:16.106422     702 pod_container_deletor.go:75] Container "3222cf97634a609eb10a435925e9800f2d7b38ad6c4b5f04cbade60a9d964b90" not found in pod's containers
May 13 13:59:16 localhost.localdomain kubelet[702]: I0513 13:59:16.161232     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:16 localhost.localdomain kubelet[702]: I0513 13:59:16.161762     702 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
May 13 13:59:16 localhost.localdomain kubelet[702]: W0513 13:59:16.165015     702 pod_container_deletor.go:75] Container "f0c1e39ae91ab2df59d3f07ae0572ecc811773b19175ea0f67c5dca7ed2a271e" not found in pod's containers
May 13 13:59:16 localhost.localdomain kubelet[702]: E0513 13:59:16.200252     702 kubelet.go:2266] node "localhost.localdomain" not found
May 13 13:59:16 localhost.localdomain kubelet[702]: E0513 13:59:16.300671     702 kubelet.go:2266] node "localhost.localdomain" not found**

**Comment by aojea** [comment]
is the address 192.168.5.130 part of your docker network?
```**reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://192.168.5.130:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.5.130:6443: connect: connection refused```

what's the ip address of your control-plane node/container?

**Comment by chenliu1993** [comment]
> is the address 192.168.5.130 part of your docker network?
> `**reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://192.168.5.130:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.5.130:6443: connect: connection refused`
> 
> what's the ip address of your control-plane node/container?

192.168.5.130 is my host IP address, the node control-plane container IP address is the same one

**Comment by aojea** [comment]
@chenliu1993 can you give more details about how are you creating the cluster? each node/container should have their own IP address, bear in mind that they are "representing" physical nodes?
Per example, if I execute `ip a` inside the control plane node 
```
 docker exec -it kind-control-plane ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ae:31:76:5e:08:5b brd ff:ff:ff:ff:ff:ff
    inet6 fd00:100:64::1/80 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::ac31:76ff:fe5e:85b/64 scope link
       valid_lft forever preferred_lft forever
3: vethbba338b9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master cni0 state UP group default
    link/ether aa:75:b3:7c:bd:d1 brd ff:ff:ff:ff:ff:ff link-netns cni-3044bdee-9c60-44e4-38e2-ecaa8faa7b60
    inet6 fe80::a875:b3ff:fe7c:bdd1/64 scope link
       valid_lft forever preferred_lft forever
4: vethe7efbba3@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master cni0 state UP group default
    link/ether fe:8a:2a:cb:98:d0 brd ff:ff:ff:ff:ff:ff link-netns cni-04b6ee5d-eb40-8647-a91c-2279917ee0be
    inet6 fe80::fc8a:2aff:fecb:98d0/64 scope link
       valid_lft forever preferred_lft forever
378: eth0@if379: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.4/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:db8:1::242:ac11:4/64 scope global nodad
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:4/64 scope link
       valid_lft forever preferred_lft forever
```

can you share yours?

**Comment by chenliu1993** [comment]
> @chenliu1993 can you give more details about how are you creating the cluster? each node/container should have their own IP address, bear in mind that they are "representing" physical nodes?
> Per example, if I execute `ip a` inside the control plane node
> 
> ```
>  docker exec -it kind-control-plane ip a
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host
>        valid_lft forever preferred_lft forever
> 2: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     link/ether ae:31:76:5e:08:5b brd ff:ff:ff:ff:ff:ff
>     inet6 fd00:100:64::1/80 scope global
>        valid_lft forever preferred_lft forever
>     inet6 fe80::ac31:76ff:fe5e:85b/64 scope link
>        valid_lft forever preferred_lft forever
> 3: vethbba338b9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master cni0 state UP group default
>     link/ether aa:75:b3:7c:bd:d1 brd ff:ff:ff:ff:ff:ff link-netns cni-3044bdee-9c60-44e4-38e2-ecaa8faa7b60
>     inet6 fe80::a875:b3ff:fe7c:bdd1/64 scope link
>        valid_lft forever preferred_lft forever
> 4: vethe7efbba3@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master cni0 state UP group default
>     link/ether fe:8a:2a:cb:98:d0 brd ff:ff:ff:ff:ff:ff link-netns cni-04b6ee5d-eb40-8647-a91c-2279917ee0be
>     inet6 fe80::fc8a:2aff:fecb:98d0/64 scope link
>        valid_lft forever preferred_lft forever
> 378: eth0@if379: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
>     link/ether 02:42:ac:11:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
>     inet 172.17.0.4/16 brd 172.17.255.255 scope global eth0
>        valid_lft forever preferred_lft forever
>     inet6 2001:db8:1::242:ac11:4/64 scope global nodad
>        valid_lft forever preferred_lft forever
>     inet6 fe80::42:acff:fe11:4/64 scope link
>        valid_lft forever preferred_lft forever
> ```
> 
> can you share yours?

Sure. of course.
**ip a output**
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:50:56:28:ea:b3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.130/24 brd 192.168.5.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe28:eab3/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:03:da:98:bc brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

The command is "kind create cluster --config simple.yaml --loglevel debug" where simple.yaml is the example from kind official website.

**Comment by tao12345666333** [comment]
Can you try the latest version of `kind`?

**Comment by chenliu1993** [comment]
> Can you try the latest version of `kind`?

you mean v1.14.0? It is the same issue.

**Comment by tao12345666333** [comment]
> > Can you try the latest version of `kind`?
> 
> you mean v1.14.0? It is the same issue.

upgrade your `kind`. `go get -u sigs.k8s.io/kind`

**Comment by chenliu1993** [comment]
> > > Can you try the latest version of `kind`?
> > 
> > 
> > you mean v1.14.0? It is the same issue.
> 
> upgrade your `kind`. `go get -u sigs.k8s.io/kind`

ok, I will try

**Comment by chenliu1993** [comment]
docker0 doesn't have label "RUNNING" like eth0 and lo. could this be the problem?

**Comment by aojea** [comment]
This is interesting, indeed the docker0 bridge is down and should be up. Can you give us more details about your environment? Operating system, are you running in bare metal or inside a container? `docker info`, ...
do you mean that the output of `ip a` on the host is the same as  `docker exec -it kind-control-plane ip a` ?

**Comment by chenliu1993** [comment]
> This is interesting, indeed the docker0 bridge is down and should be up.
> Can you give us more details about your environment? Operating system, are you running in bare metal or inside a container? `docker info`, ...
> 
> Do you mean that the output of `ip a` on the host is the same as `docker exec -it kind-control-plane ip a` ?

**Ok, docker info is:**
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 9
Server Version: 18.06.3-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.137-1.ph2
Operating System: Ubuntu 18.04.1 LTS (containerized)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 5.823GiB
Name: localhost.localdomain
ID: B7PG:GH2V:4NH2:SQ7R:MO7D:TWN2:U4YZ:Y4CH:MNLN:D7D3:IDJU:QKNU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

I am running 
And yes,  the output of ip a on the host is the same as docker exec -it kind-control-plane ip a.
Maybe there is something wrong about my host environment.

**Comment by chenliu1993** [comment]
dmesg -c shows this :

 IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready

**Comment by aojea** [comment]
@chenliu1993 I guess that the problem is because of your host environment? are you running inside a LXD or something similar?

> Operating System: Ubuntu 18.04.1 LTS (containerized)
> Storage Driver: vfs

**Comment by chenliu1993** [comment]
> LXD

Emmm, the host environment is configured by myself, the needed modules are loaded manually. As you say, the host environment may be where the problem is.
Thanks. Once the issue solved I will update
