### ISSUE TITLE
zsh completions can't be sourced

### ISSUE THREAD

**Issue by Mikewl** [kubernetes-sigs/kind#522]
**What happened**:
Running `source <(kind completion zsh)` fails with the following error
```
_arguments:comparguments:325: can only be called from completion function
_arguments:comparguments:325: can only be called from completion function
```

**What you expected to happen**:
The completions to import and be available

**How to reproduce it (as minimally and precisely as possible)**:
Run `source <(kind completion zsh)` in zsh

**Anything else we need to know?**:

**Environment:**
- zsh version:  zsh 5.7.1 (x86_64-apple-darwin18.2.0)
- kind version: (use `kind version`): 0.3.0-alpha
- Kubernetes version: (use `kubectl version`): 1.14
- Docker version: (use `docker info`): 18.09.2
- OS (e.g. from `/etc/os-release`): MacOS 10.14

**Comment by BenTheElder** [comment]
hmm, I wonder if this is a bug upstream in cobra, we are generating these with that library
https://github.com/spf13/cobra

**Comment by nirnanaaa** [comment]
Might be related to https://github.com/spf13/cobra/pull/646

**Comment by rsteube** [comment]
Did this work before? As afaik you don't source completions (as in bash) but instead add the folders containing them to fpath: https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org#telling-zsh-which-function-to-use-for-completing-a-command

e.g:
`kind completion zsh > /somedir/_kind` (once to generate it)
and in .zshrc
```
fpath=(/somedir $fpath)`
# and something like this (normally done by plugin managers - ideally only once for performance)
autoload -Uz compinit && \
   compinit -C
```

**Comment by paranoidaditya** [comment]
👋 

I added the autocompletion subcommand. 

If you run kind completion

 `
Outputs kind shell completion for the given shell (bash or zsh)
This depends on the bash-completion binary.  Example installation instructions:
# for bash users
	$ kind completion bash > ~/.kind-completion
	$ source ~/.kind-completion
# for zsh users
	% kind completion zsh > /usr/local/share/zsh/site-functions/_kind
	% autoload -U compinit && compinit
Additionally, you may want to output the completion to a file and source in your .bashrc
Note for zsh users: [1] zsh completions are only supported in versions of zsh >= 5.2
`

There's a PR in `spf13/cobra` which lets you source autocompletion in zsh directly like bash but that's hasn't been merged yet

**Comment by BenTheElder** [comment]
Thanks @paranoidaditya ! :-)

**Comment by BenTheElder** [comment]
The upstream PR was closed.
I'm not a zsh user, but it looks like you should be using the instructions in `kind completion` rather than doing a `source <(kind completion zsh)`.

ref: https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org#telling-zsh-which-function-to-use-for-completing-a-command

**Comment by BenTheElder** [comment]
IMO it looks like we should probably encourage installing the completion script output instead, which `kind completion` currently does.

**Comment by itay-grudev** [comment]
I think the confusion comes from the fact that `kind completion` outputs the important information in the beginning (which on small terminal screens is off-screen) and general help and usage at the end, which tricks users into thinking it just expects a parameter like `kind completion zsh`.

If you do that you miss the lovely note in the beginning with detailed explanation. I think if he order is swapped it'd be nicer.

**Comment by stmcginnis** [comment]
That output comes from cobra. You may want to provide usability suggestions there: https://github.com/spf13/cobra
