### ISSUE TITLE
Don't proxy docker network automatically when using proxies

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#525]
**What would you like to be added**:

Add the docker network automatically to the NO_PROXY variable.

**Why is this needed**:

In environments where proxies are needed is easy to forget to add the docker network where the `kind` cluster runs to the NO_PROXY environment variable, and this causes a failure trying to create the cluster.

We added the docker network to the NO_PROXY environment in containerd using the entrypoint script, however seems that `kubeadm init` and maybe other components use the environment variables.

I've tried different options to avoid to use the `docker -e` option without any luck.

```
configure_proxy() {
  # Don't use proxy for the local network
  LOCAL_NETWORK=$(ip route list dev eth0 proto kernel | awk '{ print $1 }')

  cat <<EOF > /etc/profile.d/kind-noproxy.sh
export NO_PROXY=${NO_PROXY:-localhost},${LOCAL_NETWORK}"
EOF

  mkdir -p /etc/systemd/system.conf.d/
  cat <<EOF >/etc/systemd/system.conf.d/kind-proxy.conf
[Manager]
DefaultEnvironment="HTTP_PROXY=${HTTP_PROXY:-}" "HTTPS_PROXY=${HTTPS_PROXY:-}" "NO_PROXY=${NO_PROXY:-localhost},${LOCAL_NETWORK}"
EOF

  mkdir -p /etc/systemd/system/containerd.service.d/
  cat <<EOF >/etc/systemd/system/containerd.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=${HTTP_PROXY:-}"
Environment="HTTPS_PROXY=${HTTPS_PROXY:-}"
Environment="NO_PROXY=${NO_PROXY:-localhost},${LOCAL_NETWORK}"
EOF

}

**Comment by BenTheElder** [comment]
I think we need to go ahead and get 0.3 out ASAP (just going to let a little more testing happen after kindnetd), but we definitely need to fix this problem, this is harming a lot of users unnecessarily.

I will prioritize this and other networking issues for 0.4

**Comment by aojea** [comment]
We should wait for https://github.com/kubernetes-sigs/kind/pull/484, once it's merged is just adding a new method to get the docker network address of the cluster.
I guess that the code should be something like this 

```
diff --git a/pkg/cluster/nodes/create.go b/pkg/cluster/nodes/create.go
index 84a9811..f68f0d5 100644
--- a/pkg/cluster/nodes/create.go
+++ b/pkg/cluster/nodes/create.go
@@ -146,6 +146,16 @@ func createNode(name, image, clusterLabel, role string, mounts []cri.Mount, extr

        // pass proxy environment variables to be used by node's docker deamon
        proxyDetails := getProxyDetails()
+       dockerNetwork, err := docker.NetworkAddress(clusterLabel)
+       if err != nil {
+               return nil, errors.Wrap(err, "could not obtain the docker network address")
+       }
+       noproxy, ok := proxyDetails["NO_PROXY"]
+       if ok {
+               proxyDetails["NO_PROXY"] = fmt.Sprintf("%s,127.0.0.0/8,localhost,%s", noproxy, dockerNetwork)
+       } else {
+               proxyDetails["NO_PROXY"] = fmt.Sprintf("%s,127.0.0.0/8,localhost,%s", dockerNetwork)
+       }
        for key, val := range proxyDetails.Envs {
                runArgs = append(runArgs, "-e", fmt.Sprintf("%s=%s", key, val))
        }

```
