### ISSUE TITLE
go get   sigs.k8s.io/kind undefined: k8sdeps.NewFactory

### ISSUE THREAD

**Issue by latermonk** [kubernetes-sigs/kind#532]
hi , i  get kind use command "go get sigs.k8s.io/kind" , get the error
```
go get -u sigs.k8s.io/kind
# sigs.k8s.io/kind/pkg/kustomize
sigs.k8s.io/kind/pkg/kustomize/kustomize.go:108:7: undefined: k8sdeps.NewFactory
sigs.k8s.io/kind/pkg/kustomize/kustomize.go:109:26: not enough arguments in call to build.NewCmdBuild
"  ,
and my go env is :
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build373427122=/tmp/go-build -gno-record-gcc-switches"

```
, can anyone help with this  ?

**Comment by BenTheElder** [comment]
please see https://github.com/kubernetes-sigs/kind#installation-and-usage or https://kind.sigs.k8s.io/docs/user/quick-start/#installation

**Comment by BenTheElder** [comment]
What go version are you using? Or do you have `make` and docker?

Either the instructions linked above (note the actual go get command) should work with recent go, or cloning and using thr makefile should work with just make and docker.

**Comment by latermonk** [comment]
> 
> 
> What go version are you using? Or do you have `make` and docker?
> 
> Either the instructions linked above (note the actual go get command) should work with recent go, or cloning and using the makefile should work with just make and docker.

**Comment by latermonk** [comment]
> 
> 
> What go version are you using? Or do you have `make` and docker?
> 
> Either the instructions linked above (note the actual go get command) should work with recent go, or cloning and using the makefile should work with just make and docker.

both Ubuntu 18.04 ， go version go1.12.5 linux/amd64  and centos  7, go version go1.11.5 linux/amd64 , find the same issue .

**Comment by ZhengZhenyu** [comment]
Why is this closed? I tested with Bazel and both master k8s and master Kind, with go 1.12.1, and I think it is not related to any of these since KinD did call k8sdeps.NewFactory() in https://github.com/kubernetes-sigs/kind/blob/master/pkg/kustomize/kustomize.go#L108 and it has been removed since: https://github.com/kubernetes-sigs/kustomize/commit/7764dee59df9199a5aa2c4949540a90996fedc11

**Comment by ZhengZhenyu** [comment]
@BenTheElder @latermonk @dims

**Comment by tao12345666333** [comment]
@ZhengZhenyu you need set `GO111MODULE="on"`

**Comment by ZhengZhenyu** [comment]
@tao12345666333 Thanks for the reply, set it in where?

**Comment by BenTheElder** [comment]
Quick reply from kubecon :-)
See an example: https://github.com/kubernetes-sigs/kind#installation-and-usage
This is in the readme in a few places and in the [quick start](https://kind.sigs.k8s.io/).

See also https://github.com/golang/go/wiki/Modules https://blog.golang.org/using-go-modules

Or you can just install a release binary (also in the installation guide).

**Comment by tao12345666333** [comment]
> @tao12345666333 Thanks for the reply, set it in where?

set `GO111MODULE=on`  as your environment variable. ref: https://github.com/kubernetes-sigs/kind#installation-and-usage

**Comment by ZhengZhenyu** [comment]
@BenTheElder @tao12345666333 Thanks for the reply, but actually I'm trying to fix our KinD ARM CI for the OpenLab, and I guess the idea of the CI is to test(build and test) latest KinD on ARM architecture so I guess the walkaround option might not be appropriate for our case?

**Comment by BenTheElder** [comment]
Ah, the same "go get" command in the readme but @master instead of @v0.3.0 will do HEAD of that branch.

**Comment by ZhengZhenyu** [comment]
@BenTheElder Thanks for the reply, I will have a try
