### ISSUE TITLE
Running Nginx: iptables unable to setup DNAT.

### ISSUE THREAD

**Issue by chenliu1993** [kubernetes-sigs/kind#550]
**Hi all, I am new to kubernetes. Now I am using command "kubectl run nginx-1 --image=nginx:latest --expose=true --hostport=8081 --port=80" to run nginx in container. While nginx pod is stuck at "ContainerCreating" status. I "describe" the pod and got the following error:**

 Normal   SandboxChanged          106s (x12 over 117s)  kubelet, localhost.localdomain  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  105s (x4 over 108s)   kubelet, localhost.localdomain  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "53a55e20faba86f3eed54f9b5e518b6db9afeae8f63245f380852af90217f034" network for pod "nginx-1-6d79cd684d-vg4ml": NetworkPlugin cni failed to set up pod "nginx-1-6d79cd684d-vg4ml_default" network: unable to setup DNAT: running [/sbin/iptables -t nat -A CNI-HOSTPORT-DNAT -m comment --comment dnat name: "weave" id: "53a55e20faba86f3eed54f9b5e518b6db9afeae8f63245f380852af90217f034" -m multiport -p tcp --destination-ports 8081 -j CNI-DN-35dacff15508f16b78b24 --wait]: exit status 1: iptables: No chain/target/match by that name.

**Seems that CNI-NI-*** does not exists in iptables -t nat -L output.**

Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
CNI-HOSTPORT-DNAT  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
CNI-HOSTPORT-DNAT  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
CNI-HOSTPORT-MASQ  all  --  anywhere             anywhere             /* CNI portfwd requiring masquerade */
KUBE-POSTROUTING  all  --  anywhere             anywhere             /* kubernetes postrouting rules */
MASQUERADE  all  --  172.17.0.0/16        anywhere
WEAVE      all  --  anywhere             anywhere

Chain CNI-HOSTPORT-DNAT (2 references)
target     prot opt source               destination

Chain CNI-HOSTPORT-MASQ (1 references)
target     prot opt source               destination
MASQUERADE  all  --  anywhere             anywhere             mark match 0x2000/0x2000

Chain CNI-HOSTPORT-SETMARK (0 references)
target     prot opt source               destination
MARK       all  --  anywhere             anywhere             /* CNI portfwd masquerade mark */ MARK or 0x2000

Chain DOCKER (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain KUBE-MARK-DROP (0 references)
target     prot opt source               destination
MARK       all  --  anywhere             anywhere             MARK or 0x8000

Chain KUBE-MARK-MASQ (3 references)
target     prot opt source               destination
MARK       all  --  anywhere             anywhere             MARK or 0x4000

Chain KUBE-NODEPORTS (1 references)
target     prot opt source               destination

Chain KUBE-POSTROUTING (1 references)
target     prot opt source               destination
MASQUERADE  all  --  anywhere             anywhere             /* kubernetes service traffic requiring SNAT */ mark match 0x4000/0x4000

Chain KUBE-SEP-3DU66DE6VORVEQVD (1 references)
target     prot opt source               destination
KUBE-MARK-MASQ  all  --  10.32.0.3            anywhere
DNAT       udp  --  anywhere             anywhere             udp to:10.32.0.3:53

Chain KUBE-SEP-RX6HK3A6QAQ6ADFY (1 references)
target     prot opt source               destination
KUBE-MARK-MASQ  all  --  192.168.5.130        anywhere
DNAT       tcp  --  anywhere             anywhere             tcp to:192.168.5.130:6443

Chain KUBE-SEP-S4MK5EVI7CLHCCS6 (1 references)
target     prot opt source               destination
KUBE-MARK-MASQ  all  --  10.32.0.3            anywhere
DNAT       tcp  --  anywhere             anywhere             tcp to:10.32.0.3:53

Chain KUBE-SERVICES (2 references)
target     prot opt source               destination
KUBE-SVC-NPX46M4PTMTKRN6Y  tcp  --  anywhere             10.96.0.1            /* default/kubernetes:https cluster IP */ tcp dpt:443
KUBE-SVC-ERIFXISQEP7F7OF4  tcp  --  anywhere             10.96.0.10           /* kube-system/kube-dns:dns-tcp cluster IP */ tcp dpt:53
KUBE-SVC-TCOU7JCQXEZGVUNU  udp  --  anywhere             10.96.0.10           /* kube-system/kube-dns:dns cluster IP */ udp dpt:53
KUBE-NODEPORTS  all  --  anywhere             anywhere             /* kubernetes service nodeports; NOTE: this must be the last rule in this chain */ ADDRTYPE match dst-type LOCAL

Chain KUBE-SVC-ERIFXISQEP7F7OF4 (1 references)
target     prot opt source               destination
KUBE-SEP-S4MK5EVI7CLHCCS6  all  --  anywhere             anywhere

Chain KUBE-SVC-NPX46M4PTMTKRN6Y (1 references)
target     prot opt source               destination
KUBE-SEP-RX6HK3A6QAQ6ADFY  all  --  anywhere             anywhere

Chain KUBE-SVC-TCOU7JCQXEZGVUNU (1 references)
target     prot opt source               destination
KUBE-SEP-3DU66DE6VORVEQVD  all  --  anywhere             anywhere

Chain WEAVE (1 references)
target     prot opt source               destination
RETURN     all  --  10.32.0.0/12         base-address.mcast.net/4
MASQUERADE  all  -- !10.32.0.0/12         10.32.0.0/12
MASQUERADE  all  --  10.32.0.0/12        !10.32.0.0/12

**There is one node in the cluster and it is untainted. What is the issue here? It is really confusing because I used to deploy this nginx using the same run command to a worker in a two-node cluster and on worker-node it worked just fine.**

**Comment by chenliu1993** [comment]
And also I found that kube-proxy conainer's logs keep giving error" iptables-restore failed, exit status 1"

**Comment by chenliu1993** [comment]
Now I found if I add -m multiport then iptables will output No chain/target/match by that name

**Comment by BenTheElder** [comment]
what version are you using? it looks like there's weave in there?

I'm not sure what the issue is from those log snippets, could you possibly upload more of the logs? eg the files from `kind export logs`

**Comment by tao12345666333** [comment]
based on the issue you mentioned before #521 #440, I hope that you can provide more information, especially your system and environment information.

**Comment by chenliu1993** [comment]
> what version are you using? it looks like there's weave in there?
> 
> I'm not sure what the issue is from those log snippets, could you possibly upload more of the logs? eg the files from `kind export logs`

Yes, it is weave. kubernetes version is v1.13.4, My Linux version is 
**Linux localhost.localdomain 4.9.137-1.ph2 #507  SMP Tue Nov 20 14:26:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux**
#521 and #440 has already been solved. Becaus they are about the control group. I need to re-establish one cgroup to make it work.
I am not using" kind create" to create the one-node cluster. I am trying to set-up the cluster step-by-step as the what kind code executes. So I guess export logs are impossible. But in the node container, docker logs of kube-proxy are provides if it could help.
 
W0524 07:48:35.105652       1 proxier.go:493] Failed to load kernel module ip_vs_wrr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0524 07:48:35.106188       1 proxier.go:493] Failed to load kernel module ip_vs_sh with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0524 07:48:35.108970       1 server_others.go:295] Flag proxy-mode="" unknown, assuming iptables proxy
I0524 07:48:35.116020       1 server_others.go:148] Using iptables Proxier.
W0524 07:48:35.116184       1 proxier.go:319] clusterCIDR not specified, unable to distinguish between internal and external traffic
I0524 07:48:35.116253       1 server_others.go:178] Tearing down inactive rules.
I0524 07:48:35.122357       1 server.go:483] Version: v1.13.4
I0524 07:48:35.128279       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I0524 07:48:35.128380       1 conntrack.go:52] Setting nf_conntrack_max to 131072
I0524 07:48:35.128746       1 conntrack.go:83] Setting conntrack hashsize to 32768
I0524 07:48:35.129008       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0524 07:48:35.129085       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I0524 07:48:35.130141       1 config.go:202] Starting service config controller
I0524 07:48:35.130195       1 controller_utils.go:1027] Waiting for caches to sync for service config controller
I0524 07:48:35.130241       1 config.go:102] Starting endpoints config controller
I0524 07:48:35.130272       1 controller_utils.go:1027] Waiting for caches to sync for endpoints config controller
I0524 07:48:35.231079       1 controller_utils.go:1034] Caches are synced for endpoints config controller
I0524 07:48:35.231360       1 controller_utils.go:1034] Caches are synced for service config controller
E0524 07:54:46.425214       1 proxier.go:1335] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 41 failed
)
E0524 07:55:16.438381       1 proxier.go:1335] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 41 failed

**Comment by chenliu1993** [comment]
The iptables-restore stuck at this line:
-A KUBE-SEP-RX6HK3A6QAQ6ADFY -s 192.168.5.130/32 -j KUBE-MARK-MASQ

**Comment by chenliu1993** [comment]
Solved. lack of module: xt_multiport

**Comment by tao12345666333** [comment]
> I am not using" kind create" to create the one-node cluster. I am trying to set-up the cluster step-by-step as the what kind code executes.

although this may be a good idea for learning. :thinking:   If you don't use `kind create cluster` directly, then the problem is obviously not related to `kind`. 

from the log above, it is obviously related to the kernel module.
