### ISSUE TITLE
Make behind a proxy

### ISSUE THREAD

**Issue by graham2071** [kubernetes-sigs/kind#551]
**What happened**:
Although http_proxy, https_proxy and no_proxy env var are configured, `make build` fails witha lot of:
go: golang.org/x/net@v0.0.0-20190514140710-3ec191127204: Get https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20190514140710-3ec191127204.info: dial tcp: lookup proxy.golang.org on x.x.x.x:53: no such host

**What you expected to happen**:
Make success

**How to reproduce it (as minimally and precisely as possible)**:
Run `make build` behind a proxy (docker daemon must also be correctly configured)

**Anything else we need to know?**:
Adding 
``` -e http_proxy=$(http_proxy) \``` 
to `Makefile` in `docker run` makes the build pass.

**Environment:**

- kind version: (use `kind version`): 0.4.0-alpha
- Kubernetes version: (use `kubectl version`): not yet installed
- Docker version: (use `docker info`): 18.09.6
- OS (e.g. from `/etc/os-release`): CentOS Linux release 7.6.1810 (Core)

**Comment by tao12345666333** [comment]
I think this problem is caused by your own environment.

If we simply pass `http_proxy`/`https_proxy`/`no_proxy` via `-e` to `docker run` then we need to consider if the proxy is set to an intranet address or localhost which will cause make to fail. :worried:
