### ISSUE TITLE
Improved error message when Docker is not running

### ISSUE THREAD

**Issue by zegl** [kubernetes-sigs/kind#554]
**What happened**:

If you run `kind create cluster` when no Docker daemon is running, kind exits with a unclear message:

```
Error: could not list clusters: failed to list nodes: exit status 1
```

**What you expected to happen**:

A clearer error message, making the experience nicer for the user.

Since the errors are wrapped, and `docker` is executed fairly deep in the codebase, I suggest the following error message:

```
Error: could not list clusters: failed to list nodes, docker might be unavailable: exit status 1
```

**How to reproduce it (as minimally and precisely as possible)**:

1. Don't run a docker daemon
2. Run `kind create cluster` 

**Environment:**

- kind version: (use `kind version`): v0.4.0-alpha (bed5b7ef6c8ceb69606bfa656bd772e0834ff428)

---

I'll submit a PR with a fix for this, if you think that this is a good idea.

**Comment by aojea** [comment]
@BenTheElder should we add some preflight checks to avoid this kind of problems?

**Comment by aojea** [comment]
this is kind of duplicate of #575

**Comment by BenTheElder** [comment]
combining with #575
