### ISSUE TITLE
better error output when docker isn't/can't log in

### ISSUE THREAD

**Issue by squillace** [kubernetes-sigs/kind#575]
**What would you like to be added**:
The ability get better error output in the non-default case when creating a new cluster and not specifying the default `kind create cluster`. 

**Why is this needed**:
I stumbled around for the better part of a week trying to understand why this didn't work, below. only when I ran it as the default command did it appear to output the error -- it's picking up my docker login and I'd changed the password but had not re-logged in. After logging in properly, it is creating properly. 

```
╭─ralph at surfacebook in ~/work/go/bin using
╰─○ kind create cluster --image=kindest/node:v1.14.0 --name kindly
Creating cluster "kindly" ...
 ✓ Ensuring node image (kindest/node:v1.14.0) 🖼
 ✓ Preparing nodes 📦
 ✓ Creating kubeadm config 📜
 ✗ Starting control-plane 🕹️
Error: failed to create cluster: failed to init node with kubeadm: exit status 1
╭─ralph at surfacebook in ~/work/go/bin using
╰─○ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.14.2) 🖼
ERRO[17:42:25] Unable to find image 'kindest/node:v1.14.2@sha256:33539d830a6cf20e3e0a75d0c46a4e94730d78c7375435e6b49833d81448c319' locally
ERRO[17:42:25] docker: Error response from daemon: Get https://registry-1.docker.io/v2/kindest/node/manifests/sha256:33539d830a6cf20e3e0a75d0c46a4e94730d78c7375435e6b49833d81448c319: unauthorized: incorrect username or password.
ERRO[17:42:25] See 'docker run --help'.
 ✗ Preparing nodes 📦
ERRO[17:42:25] docker run error: exit status 125
Error: failed to create cluster: docker run error: exit status 125
```

**Comment by BenTheElder** [comment]
cc @amwat exactly the kind of self-diagnosis I was talking about earlier ^^

xref: #39 
/priority important-longterm

**Comment by squillace** [comment]
@BenTheElder this was why it was failing on my machine at KubeCon. :-)

**Comment by philips** [comment]
Hit this issue on a debian machine where I didn't have access to the docker socket.

**Comment by BenTheElder** [comment]
/remove-lifecycle stale

Yep, error handling / reporting / logging is something I'm back at reshaping right now, it's subpar :(

We do at least have a note about the docker socket in the known issues guide now..

**Comment by aojea** [comment]
I think that @BenTheElder fixed this with the new logging mechanism
Currently, the error that kind shows is meaningful

```
./kind create cluster
ERROR: failed to list clusters: command "docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster=kind --format '{{.Names}}'" failed with error: exec: "docker": executable file not found in $PATH
```

/close

**Comment by estensen** [comment]
IMO, as a beginner, this is not beginner-friendly:
```
$ kind create cluster
ERROR: failed to list clusters: command "docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster=kind --format '{{.Names}}'" failed with error: exit status 1
```

There should be a hint that Docker is not running

**Comment by aojea** [comment]
> IMO, as a beginner, this is not beginner-friendly:
> 
> ```
> $ kind create cluster
> ERROR: failed to list clusters: command "docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster=kind --format '{{.Names}}'" failed with error: exit status 1
> ```
> 
> There should be a hint that Docker is not running

the problem is that it may be caused by another reasons, not just that Docker is not running, so it can be wrong to always return an error saying "Docker is not running"

**Comment by BenTheElder** [comment]
What aojea said.

Sorry, we know this isn't friendly, there's just a LOT to do and initially we were targeting kubernetes (literally kubernetes itself) developers. There's a lot to do. I have a sketch for more sophisticated help in the command but we've got some deep rework that needs doing to fix e.g. host reboot support first.

**Comment by BenTheElder** [comment]
I recommend running again with `-v 1` on the latest release when you encounter errors until that rework is published.

**Comment by BenTheElder** [comment]
Especially now that we auto-detect between multiple backends (podman, docker), it would be helpful to write some code specifically to probe for "is the host capable of hosting a cluster"

We have some of this now related to e.g. cgroupsv2 and rootless where we will throw more descriptive errors, but not for this case yet.

This also has some overlap with https://github.com/kubernetes-sigs/kind/issues/39

**Comment by linuxem** [comment]
Still having this error 
Docker is running I can run docker ps 
But kine create cluster gives an error 

![image](https://github.com/kubernetes-sigs/kind/assets/936059/8d98ae92-94ed-4d30-a427-075116f950e2)
 
Error 

![image](https://github.com/kubernetes-sigs/kind/assets/936059/8a19b606-4e88-4562-9b64-c306d4a83efe)

even the docker gives error when running this 
docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}
see this:
![image](https://github.com/kubernetes-sigs/kind/assets/936059/5989252e-e297-4c83-9ed7-567a5474e602)

"just information about this docker installation it is Docker Desktop 4.20.0"
Any suggestions?

**Comment by linuxem** [comment]
update to the newest kind fixed the problem.
 
![image](https://github.com/kubernetes-sigs/kind/assets/936059/64472b6b-54a6-4e0f-855c-e94ec9ea32ae)

**Comment by stmcginnis** [comment]
Based on the previous comment, going to reclose this issue. I think further improvements can be tracked somewhat with #39.

/close
