### ISSUE TITLE
Add pre-pulled images during build

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/kind#58]
I would like to add some pre-pulled images (e.g. weave, core-dns) on the node image in order to make kubeadm init faster.

If the idea is fine, I'm happy to contribute it but I need a little bit of guidance in order make this feature good citizen of kind. From what I can see:
- This feature could be implemented as new bits, that gets triggered if the user pass a path where pre-pulled images are stored. Yes/No?
- Currently BuildContext handles only a bits, that is the apt install/kubernetes build bits. Should I change BuildContext.bits into []Bits?

Any other preferred/suggested approach?

**Comment by BenTheElder** [comment]
I'd definitely like to see this! This relates to #30 I think, as well as #28.

#30 should actually cover specifically etcd and dns images, which I do intend to add into the existing Bits implementations, IE at build time we should just always pull these too. (The `apt` provider should also pull kubernetes standard images as if we'd built them too).

For any nonstandard images, I'm still debating how we should do #28. I think users will generally need support to pre-pull images used for testing etc.

Overlay / weave I'd also still debate, I think we'll need to revisit how overlay is handled more generally once we implement multi-node again, but pre-pulling it for now would be nice... possibly related to #28

@munnerz any thoughts?

**Comment by BenTheElder** [comment]
I think maybe we should not do `[]Bits` as it will make it complicated to handle EG bits that provide the same paths?

I think side-loaded images could probably be handled specially via another mechanism, possibly the same one used for side-loaded test images, at at least for core-dns and etcd we can ask the kubernetes we've just built what versions of those to pull (via kubeadm) and always pull those in the standard bits implementations. (again #28 and #30)

**Comment by fabriziopandini** [comment]
/close 
in favour of #28 and #30
