### ISSUE TITLE
Reorganize documentation and define a document content strategy

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#592]
**What should be cleaned up or changed**:

Documentation content should be organized in a different way, an example of the problem is that `Quick Start Guide` that starts to be a catch-all document.

**Why is this needed**:

The documentation content starts to grow and some of the topics documented are recurringly being asked in Slack, that can mean that users are not finding it easily.
We should define a document content strategy that allows us to grow, and users to find the information quickly.

**Comment by BenTheElder** [comment]
I think quick-start is relatively OK right now, it covers roughly the things you need to know to get started in various ways, but maybe could use some shuffling within the page.

going forward we need new categories to avoid it remaining the only catch all. :sweat_smile:

**Comment by tao12345666333** [comment]
/remove-lifecycle rotten

There is a lot of content in the documentation now. Maybe we should do something.

**Comment by BenTheElder** [comment]
I don't want to break up the current content I think (and break inbound links to useful content), but we should start creating new guides under the user guide. similar to https://kind.sigs.k8s.io/docs/user/private-registries/

we've already begun doing that

**Comment by tao12345666333** [comment]
Hi @BenTheElder I agree with you. Then should my PR https://github.com/kubernetes-sigs/kind/pull/671 be closed? It doesn’t seem to make much sense.
