### ISSUE TITLE
add credentials programattically docs are out of date

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#594]
https://kind.sigs.k8s.io/docs/user/private-registries/#add-credentials-programmatically is currently out of date, specifically it leverages `docker login` on the nodes which is not going to work.

roughly the same sample can be used, but the login needs to be on the host, or something else equivalent.

**Comment by BenTheElder** [comment]
This would be easy to fix. The `docker login` generated credentials just need to be generated by another means or on the host. The upstream kubernetes docs have a guide for this I believe.

/good-first-issue

**Comment by paranoidaditya** [comment]
@BenTheElder Should we point users at https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ or maintain a copy of instructions?

**Comment by BenTheElder** [comment]
sorry I missed this, yes, I think we should probably point to that and maybe just note ourselves how you could copy the credentials to the node and ensure kubelet picks them up instead of using them natively in kubernetes

**Comment by WalkerGriggs** [comment]
Saw the 'help wanted' / 'good first issue' label and thought I'd pitch in. Changes in script tested with personal, private GCR. 

Aside from updating the snippet to generate credentials on the host machine, is there anything else worth mentioning?

**Comment by BenTheElder** [comment]
> Saw the 'help wanted' / 'good first issue' label and thought I'd pitch in. Changes in script tested with personal, private GCR.

Thank you!

> Aside from updating the snippet to generate credentials on the host machine, is there anything else worth mentioning?

Just anything you needed to know / you think would be helpful here. I'm not currently using this but I know some users trip over it and I'd like to make sure we keep this up to date / helpful 😅

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/compare/master...WalkerGriggs:private-registry-docs looks great, please do send a PR!
