### ISSUE TITLE
[docs] Is it possible to explicitly specify k8s version?

### ISSUE THREAD

**Issue by artemnikitin** [kubernetes-sigs/kind#597]
**What would you like to be documented**:
Is it possible to explicitly specify Kubernetes version to run with `kind create cluster`? At the moment, if create cluster,  then version 1.14.2 will be used. It's unclear if it's possible to change that.

**Why is this needed**:
At the moment it's not clear if it's possible or not. If it's possible, then it's not clear how to do that.

**Comment by tao12345666333** [comment]
You can specify the tag of node image
```
kind create cluster  --image kindest/node:v1.14.1
```

**Comment by tao12345666333** [comment]
or follow this https://kind.sigs.k8s.io/#installation-and-usage

**Comment by artemnikitin** [comment]
Thanks for info! Sorry for missing this

**Comment by ryanhartje** [comment]
How can you configure this via a manifest?

**Comment by BenTheElder** [comment]
the `image` field on each node in `nodes`, currently `--image` maps to over-ridding these.
`nodes` has a default like:
```
nodes:
- role: control-plane
   image: <default for kind version>
```

**Comment by ryanhartje** [comment]
Thank you!!!
