### ISSUE TITLE
a ambiguity error info

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes-sigs/kind#599]
docker is not running and run kind to create a new cluster, the error info is ambiguity. 

```
kind create cluster --name=clusterapi
Error: could not list clusters: failed to list nodes: exit status 1
```

**Comment by aojea** [comment]
Thanks for reporting it, but this is a duplicate of https://github.com/kubernetes-sigs/kind/issues/575
If you don't mint is better to close this and use the other issue to track it

**Comment by Sn0rt** [comment]
@aojea ok, I will close this. This is a similar question, maybe you should do some pre-run check work.
