### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#611]
**What would you like to be added**:

Kubernetes has an automated release process defined in https://github.com/kubernetes/release/blob/master/docs/release-notes.md , I think that `kind` can use the same model.

**Why is this needed**:

The more automation the less human work :-)

**Comment by BenTheElder** [comment]
/shrug
PR templates are a good idea, but I'm not a fan of automated release notes. It's important to explain and categorize changes etc.

Kubernetes has much more of a scaling problem and as a result also has the release notes browsing tool 😅

**Comment by aojea** [comment]
that's fair enough 😄
