### ISSUE TITLE
document how to use a kind image as gitlab service

### ISSUE THREAD

**Issue by TheErk** [kubernetes-sigs/kind#620]
**What would you like to be added**:

Would it be possible to explain/support the usage of a kind image that enables the use
of kind as a gitlab service: https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service

**Why is this needed**:

It would ease the use of kind in order to do simple in gitlab CI tests of k8s usage.

**Comment by TheErk** [comment]
This is linked to the usage describe in #619

**Comment by BenTheElder** [comment]
This should probably go against https://github.com/kind-ci/examples.

kind works anywhere docker works properly + you can get the static binary so we don't publish images like this currently.

Note that gitlab will not have a free tier for CI soon, so after September we are exceedingly unlikely to do any support from the examples repo... https://about.gitlab.com/2019/03/21/six-more-months-ci-cd-github/

**Comment by TheErk** [comment]
Ok I see your point.
Our use case was in our privately hosted gitlab CI, but that use case I guess we could go along either with bringing the kind binary into our job image or craft such a service image ourselves.
Thank you for the fast answer.

**Comment by BenTheElder** [comment]
👍

An example for gitlab in the CI examples repo would be awesome, I don't think we'll be able to maintain it easily though. I don't have access to a paid gitlab and the free CI is going away 😬

**Comment by BenTheElder** [comment]
I think the only core contributor using gitlab CI is @munnerz and I'm pretty sure only with the Kubernetes executor. We'll want external help for documenting this one.
/help

**Comment by TheErk** [comment]
Once I'll manage to find a proper configuration working (kind and gitlab) I'll definitely post something here in order to share with others.

**Comment by BenTheElder** [comment]
there is currently https://github.com/kind-ci/examples/blob/master/.gitlab-ci.yml

**Comment by aojea** [comment]
@TheErk can we close this? is that link in the previous comment solving the issue?

**Comment by TheErk** [comment]
I'll try the solution of the link today and come back here right away.

**Comment by TheErk** [comment]
So the provided solution does not work for me because my current gitlab-ci config does not seem allow me to run `docker:dind` as a service (service is not starting) as done https://github.com/kind-ci/examples/blob/9021a580cbe505a5eaca98d9ab09c43e92adbe07/.gitlab-ci.yml#L6

We should nevertheless close this issue because this appear to be a gitlab ci config issue on my side and nothing else.

**Comment by mitar** [comment]
I think this issue should be reopen. I do not see/find any documentation how to use kind as a **GitLab service**, only how to use Docker-in-Docker GitLab service to deploy kind to it. This is slightly different. Ideally, one could deploy kind as a service (so a sidecar container) to the main job container, and then run inside the main job container kind in "configure only" way to finish the setup of the service container. So I think the documentation really boils down to: if you were to run the kind docker container manually using `docker run`, how would you do that (and is such image readily available), and then how to map that to GitLab's service configuration.

Using it as a service would remove one layer of Dockerization from the execution.

**Comment by BenTheElder** [comment]
We have another repo dedicated to CI services with community supplied examples, as many as we can actually running against the repo
https://kind.sigs.k8s.io/docs/user/resources/#using-kind-in-ci

We don't do support for CI services here, and we couldn't enable them here due to org policies even if we wanted to.

**Comment by BenTheElder** [comment]
> if you were to run the kind docker container manually using docker run, how would you do that (and is such image readily available), and then how to map that to GitLab's service configuration.

We don't support this, and won't be supporting this.
There's too much we need to coordinate after the entrypoint is started and too many fiddly flags to get right running the image, sometimes with changes depending on the host etc.

**Comment by BenTheElder** [comment]
If it were just a simple docker run the binary wouldn't exist. As it stands it's a single ~7MB statically linked binary. You can always run a service that invokes the binary against the host socket (potentially using your own simple custom image with the binary + docker cli), but that would be documented in the CI examples project.

**Comment by mitar** [comment]
Thank you for your comments. Very helpful.

**Comment by BenTheElder** [comment]
I just checked and the .gitlab-ci.yml is using the dind service currently, but I think an example with this approach would be welcome. we've relied pretty heavily on user contributions for platforms like gitlab far, it could use more attention around "best practices" etc 😞 

amusingly the gitlab "badge" there is a static example badge ... we must have missed that previously 🔥

**Comment by mitar** [comment]
Yes, but based on your comments above I do not think using it as a service is possible. Currently you can set only very basic configuration of the image used in the service: https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#available-settings-for-services

I think at least mounting external files should be needed. But you said that:

> too much we need to coordinate after the entrypoint is started and too many fiddly flags to get right running the image

So if it is not possible to get to `docker run` you could manually run on GitLab CI (knowing the host is Linux, etc.) then I think services is not really possible. Or, we could open issues in GitLab for missing features. I could help here a bit and play with this, but there seems to be some road blocks currently.

**Comment by mitar** [comment]
> but I think an example with this approach would be welcome.

Oh, you are talking about using host's Docker socket? Yes, that could be documented. Sadly I am not in position to do that because my target is gitlab.com and not local runner. We could open an issue in examples repository soliciting somebody to provide such example.
