### ISSUE TITLE
gracefully detect <= kubernetes v1.12 nodes for secondary control plane and fail

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#631]
**What would you like to be added**: `kubeadm join --control-plane` (IE "HA") only exists for v 1.12+. if the node image for any secondary control plane nodes (possibly the primary too?) is using a lower version of kubernetes we should detect this.

**Why is this needed**: To give a more understandable error to the user rather than the join failing.

**Comment by neolit123** [comment]
in 1.14 and >= 1.12 it's `join --experimental-control-plane` in 1.15 it's `--control-plane` and `--experimental-control-plane` is deprecated and will be removed in 1.16.
this is following the existing k8s alpha->beta graduation process for flags.

**Comment by BenTheElder** [comment]
thanks, we should probably have another issue to track that specifically.

**Comment by aojea** [comment]
is this an issue with kind or with kubeadm?

**Comment by BenTheElder** [comment]
good question :-)

kubeadm 1.11 cannot be patched at this point sadly, so unless we ban 1.11 from kind then kind needs to handle it either way.

**Comment by neolit123** [comment]
even if 1.11 was in the support skew we cannot backport `join --experimental-control-plane` to it, as it's a major feature.

i think kind should just fail if the primary control-plane image has 1.11 and the user fed more than one CP nodes in the kind config.

**Comment by BenTheElder** [comment]
Er right, we need to detect and handle the version here in kind. My point
was that even if kind dropped support for 1.11 it's unlikely that 1.12
would see changes related to this, and for other versions we should be
switching the flag based on versions.

**Comment by aojea** [comment]
@BenTheElder ???
 I think that with the new logging it would be easier to spot these problems, besides that 1.11 sounds a bit old 😅

**Comment by BenTheElder** [comment]
iit's a problem to fail on. it's not supported for these versions.

kind provides low effort support for 1.11+ currently, with high effort support for upstream supported versions. we've not abandoned any 1.11 support code. This matters to less than OR equal to 1.12, and 1.12 was still on it's last legs of support upstream when I filed this issue IIRC.

**Comment by aojea** [comment]
/close 

per last comment
