### ISSUE TITLE
Add CI job to test single node clusters

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#634]
**What would you like to be added**:

I´d like to add a job that tests single node clusters in current `kind` CI

**Why is this needed**:

Single node clusters have different characteristics than the multi node ones and seem that is started to be used more in the CI based on the slack channel comments.
We have to test them independently because we had a bug that was not found with current CI jobs.

**Comment by neolit123** [comment]
The single node will need to run only parallel tests. Currently if you run
serial there is a daemonset test under sig apps that needs multinode. Also
the node needs to allow workloads by removing the master taint.

**Comment by neolit123** [comment]
Frankly the serial vs parallel situation is unstable wrt to single node
conformance. Afaik the idea was that single node should not be conformant
at all, but i cant fetch the discussion link right now.
On Jun 20, 2019 17:39, "Lubomir I. Ivanov" <neolit123@gmail.com> wrote:

The single node will need to run only parallel tests. Currently if you run
serial there is a daemonset test under sig apps that needs multinode. Also
the node needs to allow workloads by removing the master taint.

**Comment by aojea** [comment]
let me expand on the goal, I didn´t mean to run the full conformance suite, is just to guarantee that the single node cluster has at least a smoke test, there are some issue that users are hitting that could´ve been avoided if we have this job

**Comment by BenTheElder** [comment]
So we're already not running the serial tests in presubmit for performance reasons. Note that this is generally true in the main repo as well.

We're also not trying to test conformance in the kind repo, that's just a convenient selector for reasonable tests. We'll want to expand that out soon.

**Comment by aojea** [comment]
let´s close this, it should be part of the testplan deciding on these things
