### ISSUE TITLE
go get: inconsistent versions: when trying to install

### ISSUE THREAD

**Issue by alexeadem** [kubernetes-sigs/kind#638]
**What happened**:

GO111MODULE="on" go get sigs.k8s.io/kind@v0.3.0
go get: inconsistent versions:

**What you expected to happen**:
Expected to install

**How to reproduce it (as minimally and precisely as possible)**:
GO111MODULE="on" go get sigs.k8s.io/kind@v0.3.0
go get: inconsistent versions

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
sudo docker info
[sudo] password for alex: 
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 9c3c5f853ebf0ffac0d087e94daef462133b69c7 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-957.21.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 7.628 GiB
Name: www.qbo.io
ID: 2DXU:Q7A5:ICZB:O4KZ:WRNN:O4FN:A6WM:5ZSD:BGXY:DQKH:36QR:YXYJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
- OS (e.g. from `/etc/os-release`):
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by alexeadem** [comment]
Got it working by running cloning the repo and running:

make build

**Comment by BenTheElder** [comment]
The make build uses go in a container, this suggests that your go on the host is too old to support modules. All officially supported versions of go support modules (and the most recent unsupported version).

What does `go version` give?

**Comment by BenTheElder** [comment]
I don't think we can direclty support go this old, none of the kubernetes code does, however we offer the `make` route that only needs docker / POSIX to work.
