### ISSUE TITLE
the hardcoded CNI manifest fails to apply against current k/k master

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/kind#639]
**What happened**:
in the current k/k master `extensions/v1beta1` is going away for DaemonSets:
https://github.com/kubernetes/kubernetes/pull/70672

this broke applying our hardcoded CNI manifest:
https://github.com/kubernetes-sigs/kind/blob/6110fdc6af652e25c6e9cc3b7eb50e5546141743/pkg/build/node/cni.go#L165
https://k8s-testgrid.appspot.com/sig-testing-kind#conformance,%20master%20(dev)

i can try sending a fix later, though we me might have to template the manifest with the GroupVersion. a major problem is that older versions of kind will fail deploying against the latest k/k master.

unfortunately hardcoding the manifest is a double edge sword.

the kubeadm/kind jobs are also failing on 0.2, but there is no solution there because we cannot backport a patch (no branches in k-sigs/kind). this means we have to move the job to latest kind master.

**What you expected to happen**:
a CNI config to be applied.

**How to reproduce it (as minimally and precisely as possible)**:
https://k8s-testgrid.appspot.com/sig-testing-kind#conformance,%20master%20(dev)

**Anything else we need to know?**:
NO

**Environment:**
CI
latest k/k master
latest k-sigs/kind master

**Comment by aojea** [comment]
We are safe in the sense that the `disableCNI` option is there, I mean, all versions can choose to disable the CNI and add an extra step to set it up.

Ben demonstrates to have a great vision 🥇

**Comment by aojea** [comment]
It seems that we only need to do this change
```

apiVersion: v1/beta2 # For Kubernetes version 1.9 and later, use apps/v1
```

**Comment by aojea** [comment]
/assign @aojea 
This https://github.com/kubernetes-sigs/kind/pull/641 fixes the problem

**Comment by BenTheElder** [comment]
apps/v1 exists in all supported kind versions, we just shouldn't have used extensions the switch should solve this.

this could still bite us someday, will think about this some more...

**Comment by BenTheElder** [comment]
we should also look at:
- getting more tests running under kind (expand scope beyond conformance)
- making kind a default (though non-blocking initially) kubernetes presubmit ... there's been a lot of talk about doing this from SIG Testing / SIG Cluster Lifecycle, we should probably at least look at  running it.

**Comment by aojea** [comment]
I think we should start adding some periodic tests with a bigger scope
+1 to kubernetes presubmit

**Comment by neolit123** [comment]
please LGTM this PR for the kubeadm/kind jobs:
https://github.com/kubernetes/test-infra/pull/13133

**Comment by neolit123** [comment]
also thanks for fixing the problem in https://github.com/kubernetes-sigs/kind/pull/641 @aojea 
i had to go AFK.
