### ISSUE TITLE
Documentation: how to run something before kubelet

### ISSUE THREAD

**Issue by mitar** [kubernetes-sigs/kind#64]
I would like to run `docker login` before `kubelet` gets started so that it can find and use docker config file with credentials. I have not found in documentation a way to do so.

**Comment by BenTheElder** [comment]
sorry I missed this, it is possible but is intentionally not documented as I don't know that the config for it is in the right shape yet so it's still a power-user / alpha feature. the node lifecycle hooks cover this.

**Comment by BenTheElder** [comment]
I'll document this in the user guides xref: https://github.com/kubernetes-sigs/kind/issues/79

**Comment by mitar** [comment]
I do not see that this has been documented as part of #79?

**Comment by BenTheElder** [comment]
It was not, which is why this is still open.

It's also an open question if we want to commit to running user commands on the nodes as opposed to saying "we provide kubernetes, use the kubernetes tools to do this and don't depend on contents of the node image" (EG use [image pull secrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) which are CRI independent as opposed to docker login)

**Comment by mitar** [comment]
In this particular case though, `docker login` is a documented and supported Kubernetes feature. :-) (See [here](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#log-in-to-docker).)

**Comment by BenTheElder** [comment]
That's not true, kubernetes makes zero guarantees about which CRI is used and what can be run on nodes, you're supposed to run things on top of kubernetes instead.

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#log-in-to-docker

note that it says (emphasis mine)
> **On your laptop**, you must authenticate with a registry in order to pull a private image:

and then the next step is to set that credential up on the cluster instead:
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-in-the-cluster-that-holds-your-authorization-token

The [second link](https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry) documents some provider specific options. kind is of course not in that listing.

**Comment by mitar** [comment]
Sure, but using `kind` on the laptop to quickly setup a cluster is one of use cases, no? So it should also be easy to setup access to private images, no?

**Comment by BenTheElder** [comment]
Correct, but we can do that w/o the user running "docker login" on the kind node, the first link covers one of the ways to do that which works correctly today, and is supported on _any_ kubernetes cluster.

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-in-the-cluster-that-holds-your-authorization-token

**Comment by mitar** [comment]
So I do not want to argue here too much. Just wanted to explain the use case here. So the issue with secrets is that you have to modify your pod file to use them. So if in your cluster you use Docker login then for testing you cannot just test with same pod files.

**Comment by BenTheElder** [comment]
we document login and private registries now: https://kind.sigs.k8s.io/docs/user/private-registries/

however, in the future I want to figure out a workflow that involves producing this credential without using login on the nodes, and then just supplying it to kubelet at startup, particularly so we can switch to containerd on the nodes.

**Comment by mitar** [comment]
Thanks!
