### ISSUE TITLE
Release 1.15 node images

### ISSUE THREAD

**Issue by omerlh** [kubernetes-sigs/kind#640]
**What would you like to be added**:
Kubernetes 1.15 was released last week, I'll be happy to run kind clusters with this version

**Why is this needed**:
Local evaluation of this version, testing etc

**Comment by BenTheElder** [comment]
You can run kind clusters now by building an image (see the docs). We'll be releasing some prebuilt images to go with the 0.4 release.

**Comment by omerlh** [comment]
Thanks, I'll do that.

**Comment by BenTheElder** [comment]
New Images for kind `v0.4.0` (pending, will release shortly)

- `kindest/node:v1.15.0@sha256:b4d092fd2b507843dd096fe6c85d06a27a0cbd740a0b32a880fe61aba24bb478` 
- `kindest/node:v1.14.3@sha256:583166c121482848cd6509fbac525dd62d503c52a84ff45c338ee7e8b5cfe114`
- `kindest/node:v1.13.7@sha256:f3f1cfc2318d1eb88d91253a9c5fa45f6e9121b6b1e65aea6c7ef59f1549aaaf`
- `kindest/node:v1.12.9@sha256:bcb79eb3cd6550c1ba9584ce57c832dcd6e442913678d2785307a7ad9addc029`
- `kindest/node:v1.11.10@sha256:176845d919899daef63d0dbd1cf62f79902c38b8d2a86e5fa041e491ab795d33`
