### ISSUE TITLE
/hack/ci/e2e.sh should support build new base image for arch other than x86

### ISSUE THREAD

**Issue by ZhengZhenyu** [kubernetes-sigs/kind#668]
**What would you like to be added**:
Allow /hack/ci/e2e.sh to check arch and build new base image if arch is not
x86.

**Why is this needed**:
The default base image is built for x86 arch, which makes it impossible to
use this script directly for testing on other arch, adding this to allow
build a new base image from scrach will make the arch scope wider.

**Comment by BenTheElder** [comment]
So the scripts in hack/ are not really meant to be reused and are not stable, I think this is probably reasonable but it might be better to copy this and maintain a version that does..

I'm pretty wary that we will change or remove this and break your use case. This script is meant to be a stopgap until test-infra's tools improve (kubetest / kubetest2) and have better integration with kind.

**Comment by ZhengZhenyu** [comment]
@BenTheElder Ah, thanks I was putting up a patch on this, as you know, I have been working on KinD on ARM for quite a while, I did have some findings now, and I will reported latter. I have refactored the test cases in openlab CI, and now we are using this script directly for test, since our system uses zuul which uses ansible, for this kind of script, we have to save it to somewhere and download it and we cannot find a suitable place for it. And besides, using this directly will be able to make the tests on ARM and amd be the same, which seems better? And I can report if there is something broken because of changes on this file and during the meantime, I will think of better choices.

**Comment by aojea** [comment]
I thought that we were building node and base images for most common architectures : thinking

**Comment by BenTheElder** [comment]
>  have refactored the test cases in openlab CI, and now we are using this script directly for test, since our system uses zuul which uses ansible, for this kind of script, we have to save it to somewhere and download it and we cannot find a suitable place for it. And besides, using this directly will be able to make the tests on ARM and amd be the same, which seems better? And I can report if there is something broken because of changes on this file and during the meantime, I will think of better choices.

The issue is that we will stop using this at some point it was never supposed to be a permanent feature, just something used to bootstrap the project. And if users need some complex script that is too difficult to replicate to use kind then we are failing. :thinking: 

---

> I thought that we were building node and base images for most common architecture thinking

not node and base, they're much more painful to do this for and much slower. we will in the future.

**Comment by BenTheElder** [comment]
I am going to replace this script shortly with a much better tool, I'll be sure to include this.

**Comment by BenTheElder** [comment]
Revisiting this: Please just fork this script, I do not think we ultimately intend to support anything in hack/ as a downstream reused artifact. It's too hard to support the ""api surface"" of shell scripts and the script is not very complex.
