### ISSUE TITLE
Broken link to conformance testing

### ISSUE THREAD

**Issue by zfi** [kubernetes-sigs/kind#672]
**What would you like to be documented**:
The link to conformance testing in the root level README.md is currently referencing https://github.com/kubernetes/community/blob/master/contributors/devel/conformance-tests.md  in the kubernetes/community that is no longer there - (404 error). The new URL is https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md

**Why is this needed**:
The link should reference a valid URI.

**Comment by tao12345666333** [comment]
Thanks for your point.

/assign
