### ISSUE TITLE
Kind load command doesn't check whether the image digest is different from existing?

### ISSUE THREAD

**Issue by TommyLike** [kubernetes-sigs/kind#680]
**What happened**:

When the original image has been updated, after re-executing command `kind load docker-image xxxxxx` the images used in container keep unchanged.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: 0.4.0:
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by asitaru** [comment]
This is also happening to us after #382

**Comment by aojea** [comment]
Upps , my fault , nasty bug , sorry
/assign

**Comment by BenTheElder** [comment]
Ah this is a nasty bug :(
We should be checking and comparing the SHA, but it looks like we aren't.
/priority critical-urgent

**Comment by BenTheElder** [comment]
this _should_ be fixed now and in the next release, thanks @aojea

**Comment by BenTheElder** [comment]
this is still incorrect, finally got a chance to look at this.
/assign
/lifecycle active
