### ISSUE TITLE
syscall.Mkfifo issue on Windows

### ISSUE THREAD

**Issue by gombasp** [kubernetes-sigs/kind#681]
Hi,

after 

go get sigs.k8s.io/kind

i get the error

execplugin.go:111:2: undefined: syscall.Mkfifo

...and kind is not created. 

Using Windows 10 with go 1.12.6 windows/386.  Can you pls propose a solution?

**Comment by BenTheElder** [comment]
Are you installing with modules enabled? We have binaries built for windows with each release so the code should compile.

If you don't use modules though, you'll wind up with inconsistent versions of dependencies.

This environment variable must be set: GO111MODULE="on"

**Comment by BenTheElder** [comment]
closing due to lack of follow up, I suspect go modules were not enabled.
