### ISSUE TITLE
NO_PROXY is missing required subnets for kubectl proxy to work when using http(s) proxies

### ISSUE THREAD

**Issue by electrofelix** [kubernetes-sigs/kind#689]
**What happened**:

Launching a cluster behind a corporate proxy is unable to complete the steps from https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/ interactive tutorial successfully.

**What you expected to happen**:

To complete the steps in that module locally to confirm that the k8s cluster in kind on my workstation passed a minimal test by confirming the return of output similar to the following from a curl request:
```Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-b94cb9bff-vvmzp | v=1```

**How to reproduce it (as minimally and precisely as possible)**:

Have HTTP_PROXY, HTTPS_PROXY and NO_PROXY defined locally

Ran through the following commands and output
```
$ kind create cluster --image kindest/node:v1.14.2
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.14.2) 🖼
 ✓ Preparing nodes 📦 
 ✓ Creating kubeadm config 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
kubectl cluster-info

$ export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"

# you can do a `docker pull gcr.io/google-samples/kubernetes-bootcamp:v1` and
# `kind load docker-image gcr.io/google-samples/kubernetes-bootcamp:v1` at this point
# if iterating as a quicker loop
$ kubectl run kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1 --port=8080
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/kubernetes-bootcamp created

$ kubectl proxy &
Starting to serve on 127.0.0.1:8001

$ POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')

# run the following and wait until container running
$ watch -n1 "kubectl get pods"

$ http_proxy="" https_proxy="" curl -L  localhost:8001/api/v1/namespaces/default/pods/${POD_NAME}/proxy/
<html><head>
<title>Network Error</TITLE>
</HEAD>
<body>
<font face="Helvetica">
<big><strong></strong></big><br>
</FONT>
<blockquote>
<table border="0" cellpadding="1" width="80%">
<tr><td>
<font face="Helvetica">
<big>Network Error (dns_unresolved_hostname)</big>
<br>
<br>
</FONT>
</TD></TR>
<tr><td>
<font face="Helvetica">
Your requested host "localhost" could not be resolved by DNS.
</FONT>
</TD></TR>
<tr><td>
<font face="Helvetica">

</FONT>
</TD></TR>
<tr><td>
<font face="Helvetica" size="2">
<br>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
```
The exact output will depend on how your proxy is configured, in my case they return a webpage output. Addition of '-vv' to the curl options shows that it is not the curl process connecting to the proxy. 

**Anything else we need to know?**:

Eventually established that it was the apiserver and looking at the values of NO_PROXY there suggested that `localhost` shouldn't be proxied, however once I stumbled across the output of `ip addr` contained `cni0` using the 10.244.0.1/24 subnet I realised that the pod was likely using an IP address in this subnet. Looking at the 
```
kubectl get pod/kubernetes-bootcamp-b94cb9bff-h42wh -o yaml | grep podIP
  podIP: 10.244.0.4
```
Obviously if NO_PROXY is set to `172.17.0.0/16,localhost,127.0.0.1` and the internal podIP is on a different subnet, the apiserver will forward the proxy endpoint request to the external network.

Verified that this problem is solved by adding the subnet `10.244.0.0/16` subnet to NO_PROXY before creating the cluster. This appears to be used internally by default along with `10.96.0.0/12` based on the following:
https://github.com/kubernetes-sigs/kind/blob/edbae5fdd1f1670eef0323018ccb18ced552fd29/pkg/cluster/config/default.go#L55-L70

Potentially both of `obj.Networking.PodSubnet` and `obj.Networking.ServiceSubnet` for the cluster should be added to NO_PROXY along with the docker network subnet automatically when proxy support is enabled.

**Environment:**

- kind version: (use `kind version`):
`v0.4.0
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-17T00:58:35Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 779
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-54-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 23.52GiB
Name: <redacted>
ID: J7RJ:IJA2:LON5:KVYI:MSMZ:AG7X:JOQK:HU5M:GS66:GQV3:GYYQ:2LSG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: <redacted>
HTTPS Proxy: <redacted>
No Proxy: localhost,127.0.0.1,localaddress,.localdomain.com,192.168.0.0/16
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```
- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by aojea** [comment]
@BenTheElder @amwat this will require access to the provided configuration to access `ServiceSubnet` and `PodSubnet`. 
I think that the only way to do that with current implementations is by adding them to https://github.com/kubernetes-sigs/kind/blob/a8cd6c72eee23a71730179f5ff4bf50c9c7cc9a2/pkg/cluster/internal/create/nodes.go#L125

**Comment by electrofelix** [comment]
Is this the correct way? Or should the node struct contain an environment variables struct and the proxy support be pulled up to a higher layer that uses the cluster config to add additional environment variables if proxy support is determined? That might open the door for additional environment variable injection support as well, so I guess it depends on whether that is useful or to be avoided?

Might be a few weeks before I can get to this (depending on adoption internally), but wouldn't mind trying assuming a few people here starting using as I'm sure they will bump into this due to forgetting to set NO_PROXY at creation time correctly

**Comment by BenTheElder** [comment]
The node API is getting significantly overhauled in ~0.6, we'll plumb through the right info then.

The node struct is for runtime access and may not have the config, this should be handled at creation time, via plumbing through the subnets from config.

**Comment by BenTheElder** [comment]
/lifecycle active
https://github.com/BenTheElder/kind/tree/nodes -- node API overhaul in progress, I will fix this in that patchset as the node creation is more streamlined and explicitly has access to this information

**Comment by BenTheElder** [comment]
that overhaul mostly landed, and https://github.com/kubernetes-sigs/kind/pull/882 will fix this
