### ISSUE TITLE
Enable custom proxy settings for containerd

### ISSUE THREAD

**Issue by Jingru** [kubernetes-sigs/kind#693]
**What would you like to be added**:
I'm wondering if kind could support custom proxy settings for containerd by any means like generating a new containerd.service file and mounting it in node containers.

**Why is this needed**:
I'm using kind in a host behind proxy, which means all the outgoing traffic must use this proxy. 

Although node containers have already supported proxy settings, containerd in nodes cannot recognize  those settings. Those proxy environment variables must be set in containerd.service, which is now fixed in node image, and I have to change service files manually or change node.go to build my own node image.

**Comment by aojea** [comment]
Hi @Jingru thanks for reporting it, but this is a duplicate of https://github.com/kubernetes-sigs/kind/issues/688 , I think that we can close this and follow up on the other issue

**Comment by Jingru** [comment]
OK. I'm closing this.
