### ISSUE TITLE
Kind unload the image and load it again

### ISSUE THREAD

**Issue by adibrastegarnia** [kubernetes-sigs/kind#695]
**What happened**:
Suppose a kind cluster is running, we load an image and then we update our image to load it again. It looks like in the new version doesn't support that. 

**What you expected to happen**:
I should be able load a new image everytime that I make a change in the image without shutting down the cluster. 

**How to reproduce it (as minimally and precisely as possible)**:
Load an image multiple times and make sure when you change the image the new image will be loaded to the cluster.

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.4.0
- Kubernetes version: (use `kubectl version`):
lient Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-25T23:41:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Docker version: (use `docker info`): 
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
- OS (e.g. from `/etc/os-release`): Mac

**Comment by BenTheElder** [comment]
yeah sorry about this, this is a known issue that was fixed recently.
we need to document that somewhere. the fix will be in 0.5.0 and could be installed from cb35e540987e58257c842aaeef0fee350d8967fb

`GO111MODULE=on go get sigs.k8s.io/kind@cb35e540987e58257c842aaeef0fee350d8967fb`

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/680

**Comment by adibrastegarnia** [comment]
Great thanks.

**Comment by aojea** [comment]
@adibrastegarnia is this solved? Can we close it?

**Comment by adibrastegarnia** [comment]
Yes. I will close it.
