### ISSUE TITLE
Inform another namespace when the image is loaded

### ISSUE THREAD

**Issue by adibrastegarnia** [kubernetes-sigs/kind#696]
I have a quick question. Suppose we load an image to the kind cluster. Is it possible to inform another namespace when that happens to redeploy the Pod?

**Comment by BenTheElder** [comment]
there is not, but you can use `kubectl rollout restart` to do a rolling update of a deployment without changing it in Kubernetes 1.15+

**Comment by BenTheElder** [comment]
`kind load image:foo && kubectl rollout restart deployment-using-the-image` should work I think.

**Comment by adibrastegarnia** [comment]
OK I will try and then update you

**Comment by adibrastegarnia** [comment]
@BenTheElder 
What should be the input of rollout restart? A Pod?

**Comment by BenTheElder** [comment]
something like: `kubectl rollout restart deployment/deployment-name`, `kubectl rollout restart daemonset/name`

see also: `kubectl rollout restart --help`

**Comment by adibrastegarnia** [comment]
Thanks.

**Comment by aojea** [comment]
@adibrastegarnia can we close?

**Comment by adibrastegarnia** [comment]
resolved and closed.  Thanks
