### ISSUE TITLE
Explore user mode linux

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#697]
Requires recent docker and kernel https://twitter.com/_AkihiroSuda_/status/1148543910882361345
https://github.com/weber-software/diuid

/assign
/priority backlog

Doesn't look like something we could roll out yet, but a very interesting potential avenue for the future.

**Comment by aojea** [comment]
is this exclusive with ignite?

**Comment by BenTheElder** [comment]
not really, I suspect this won't work well for us but we should explore the option which would allow unpriv container nodes.

**Comment by BenTheElder** [comment]
it's pretty neat, but I think rootless is probably the more realistic target atm, which is happening without user mode linux. user mode linux is probably far too expensive to emulate kubernetes under, and we just can't prioritize this.
