### ISSUE TITLE
Increase number of e2e tests run

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#698]
**What would you like to be added**:

Run more e2e tests with kind

**Why is this needed**:

We are running only conformance tests, that´s about 210/4414

**Comment by BenTheElder** [comment]
❤️ We definitely need this.
/priority important-longterm

To be clear: We're looking to do this mainly for testing Kubernetes proper, not necessarily the kind repo.

We also definitely aren't interested in all 4000 or so tests, many of those are provider (GCE, AWS) specific or arguably don't make sense at all (`[Feature:Dashboard]`) but certainly there are many tests beyond conformance that would be useful for testing Kubernetes, which will also give us some more CI signal...

**Comment by BenTheElder** [comment]
Some work towards getting kind to run roughly what `pull-kubernetes-e2e-gce` runs:
- https://github.com/kubernetes/kubernetes/pull/80044
- https://github.com/kubernetes/kubernetes/pull/80329

**Comment by aojea** [comment]
those patches were merged

**Comment by BenTheElder** [comment]
/assign
/lifecycle active
More than 2x now
