### ISSUE TITLE
support all the kubeadm config flavors in templates

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/kind#7]
the kubeadm configuration is moving fast and ever changing.
it was `v1alpha2` in 1.11 and in 1.12 it would be `v1alpha3`.
even more changes are planned for `v1beta1` in 1.13.

based on a parseable `kuberentes-version` flag of sorts, kind would have to pick the right template to construct a kubeadm config.

for ref:
https://github.com/kubernetes-sigs/kind/blob/130a7fe9212c3fba6fc84d785759785218ce5128/pkg/cluster/kubeadm/config.go#L55
kubeadm's api:
https://github.com/kubernetes/kubernetes/tree/master/cmd/kubeadm/app/apis/kubeadm

/assign
/kind feature
/priority important-longterm

**Comment by BenTheElder** [comment]
Definitely, thanks for filing this.

We know the Kubernetes version from `/kind/version` (a regular text file containing `gitVersion` for the kubernetes installed at build time) [in the node image](https://github.com/kubernetes-sigs/kind/blob/master/docs/node-image.md#design), the value of which is supplied to the template as an arg. We probably want to supply a parsed version of this to the template so it can select over minor / patch etc.

**Comment by neolit123** [comment]
understood, just had a look how the version is passed to the template.

**Comment by BenTheElder** [comment]
Counting the PR above and discussion here as making it active for now :-)
Trying out the active label for tracking in this repo.

**Comment by neolit123** [comment]
> Counting the PR above and discussion here as making it active for now

ok, makes sense :+1:

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/68922 merged but kind is currently broken and we'll need to wait for it to be synced out by the publishing bot

**Comment by neolit123** [comment]
i need to figure out what is the best way vendor `pkg/util/version` in the manifest list e2e that i'm doing too, because i homebrew a semVer in there.

the code has to live in `k/kubeadm` for this test.

**Comment by neolit123** [comment]
looking into this right now with pseudo version checks.
do we have to vendor `util/version` in the kind tree at this point?

**Comment by BenTheElder** [comment]
Thanks again! fixed in https://github.com/kubernetes-sigs/kind/pull/46

Will probably follow up with revisiting the templates a bit, but we do have support now :-)
