### ISSUE TITLE
failed to delete cluster

### ISSUE THREAD

**Issue by yangquan1982** [kubernetes-sigs/kind#708]
kind launched as follows:
`CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                  NAMES
80b238c9e4b0        kindest/node:v1.15.0   "/usr/local/bin/entr…"   17 hours ago        Up 17 hours         58543/tcp, 127.0.0.1:58543->6443/tcp   kind-control-plane`

**What happened**:
When I tried to run `kind delete cluster`, it shows
`Deleting cluster "kind" ...
$KUBECONFIG is still set to use /Users/quan.yang/.kube/kind-config-kind even though that file has been deleted, remember to unset it
Error: failed to delete cluster: exit status 1`

**What you expected to happen**:
Stop running kind docker

**How to reproduce it (as minimally and precisely as possible)**:
1- Start kind
2- Create Service Account
3- Create ClusterRoleBinding
4- Bearer Token
5- Sign in with Token from UI Dashboard
6- Sign out
7- Type `kind delete cluster` from CLI

**Anything else we need to know?**:
Even couldn't stop docker container `kind-control-plane` with `docker stop` command

**Environment:**
- kind version: (use `kind version`):
v0.4.0
- Kubernetes version: (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}`
- Docker version: (use `docker info`): 
Docker Desktop Version 2.0.0.3 (31259)
- OS (e.g. from `/etc/os-release`): 
MacOS version 10.14.5

**Comment by BenTheElder** [comment]
is docker running? delete is roughly `docker rm -f <node-name>`

**Comment by BenTheElder** [comment]
what is the output of trying to stop the container yourself?

**Comment by aojea** [comment]
running the command with debug log level can give us more information,

what´s the output of  ` kind delete cluster --loglevel debug` ?

**Comment by yangquan1982** [comment]
`DEBU[07:51:39] Running: /usr/local/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\t{{.Label "io.k8s.sigs.kind.cluster"}}]
Deleting cluster "kind" ...
DEBU[07:51:40] Running: /usr/local/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\t{{.Label "io.k8s.sigs.kind.cluster"}} --filter label=io.k8s.sigs.kind.cluster=kind]
DEBU[07:51:40] Running: /usr/local/bin/docker [docker rm -f -v kind-control-plane]
Error: failed to delete cluster: exit status 1`

**Comment by yangquan1982** [comment]
I try to do `docker stop kind-control-plane`, but my CLI is just hanging, I have to type `ctrl C` to exit
as follows:
`Edwards-MBP:~ quan.yang$ docker stop kind-control-plane
^C
Edwards-MBP:~ quan.yang$`

**Comment by aojea** [comment]
try `docker ps -q -a` and see if the node `kind-control-plane` there

**Comment by yangquan1982** [comment]
Yes, it's always there
`Edwards-MBP:~ quan.yang$ docker ps -q -a`
`80b238c9e4b0`
`63a1e044aac1`
here `80b238c9e4b0` is the CONTAINER ID of `kind-control-plane` which I can't make it stop running

**Comment by BenTheElder** [comment]
This seems like a bug in your docker version, kind does `docker rm -f node` which should not fail if node exists...

**Comment by BenTheElder** [comment]
Cannot reproduce this yet with the edge version of docker for mac, switching to stable is a bit involved :disappointed: 

what is the output of `docker rm -f kind-control-plane` ?

I suspect docker has gotten into a bad state on disk, it might require manually purging. I've not seen this happen with kind before.

**Comment by yangquan1982** [comment]
It shows
`Error response from daemon: removal of container kind-control-plane is already in progress`
when I do `docker rm -f kind-control-plane`, which seems like non-halting issue

**Comment by yangquan1982** [comment]
Here is my `docker version` output
`Client: Docker Engine - Community`
 `Version:           18.09.2`
 `API version:       1.39`
 `Go version:        go1.10.8`
 `Git commit:        6247962`
 `Built:             Sun Feb 10 04:12:39 2019`
 `OS/Arch:           darwin/amd64`
 `Experimental:      false`

`Server: Docker Engine - Community`
 `Engine:`
  `Version:          18.09.2`
  `API version:      1.39 (minimum version 1.12)`
  `Go version:       go1.10.6`
 `Git commit:       6247962`
  `Built:            Sun Feb 10 04:13:06 2019`
  `OS/Arch:          linux/amd64`
  `Experimental:     false`

**Comment by BenTheElder** [comment]
> Error response from daemon: removal of container kind-control-plane is already in progress

that looks like a docker bug, there was at least one previous bug like this where containers would get in a partially removed state and the only fix was manually removing them w/o docker. looking for current issues upstream.

**Comment by BenTheElder** [comment]
Example of upstream issues like this: https://github.com/docker/compose/issues/3434 https://github.com/moby/moby/issues/22312

I think what you can try is restart the docker daemon and do a `docker system prune -a`

**Comment by yangquan1982** [comment]
Yes, it's resolved after I restarted docker, thanks.

**Comment by BenTheElder** [comment]
thanks for working through this! sorry for the trouble :sweat_smile:
