### ISSUE TITLE
Add note in README file

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/kind#713]
**What would you like to be documented**:
In README file under [Installation and usage](https://github.com/kubernetes-sigs/kind#installation-and-usage), there might be a need to add a note for the requirement of running docker as a non root user (running without sudo).
Good idea to add a [link](https://docs.docker.com/install/linux/linux-postinstall/) too.

**Why is this needed**:
As a new user when I was trying to run `kind create cluster`, I got an error "Error: could not list clusters: invalid output when listing nodes: WARNING: Error loading config file: /home/necuser/.docker/config.json: open /home/necuser/.docker/config.json: permission denied" and thus get a little confusing.

**Comment by tao12345666333** [comment]
Thanks.

/assign

**Comment by BenTheElder** [comment]
Technically kind needs to run as any user that has access to the docker socket, which may or may not be root depending on how you install docker. This is also true if using the `docker` CLI or other tools  though.

**Comment by prankul88** [comment]
@BenTheElder Thanks for replying. I am not well aware of how to run docker without binding to UNIX socket, but feel this might be the most common way of installation. So maybe this will be a nice addition in README file.

**Comment by BenTheElder** [comment]
> I am not well aware of how to run Docker without binding to UNIX socket, but feel this might be the most common way of installation.

You definitely normally run it on a UNIX socket (can also be remote / TCP though), however a couple points / clarifications:

- It's not about root / not-root users, it's about being a user with permission to the socket when executing `kind` or `docker`, which on Linux is typically the `docker` [**group**](https://wiki.archlinux.org/index.php/users_and_groups), which very likely includes the root user, but technically depends on your specific installation of Docker.
- On macOS / Windows this is a pretty much a non-issue, on Linux the upstream Docker installation docs document this:

https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-convenience-script
> If you would like to use Docker as a non-root user, you should now consider adding your user to the “docker” group with something like:
> ```
>   sudo usermod -aG docker your-user
> ```

- `kind` has the same requirements to run as `docker` which I wouldn't expect to be surprising? If `docker ps` requires `sudo docker ps` to succeed on a system then `kind` requires `sudo kind`.

I don't feel the repo README is quite the correct place to bring this up, as we also don't get into docker installation details and I haven't seen any comparable docker tooling (including say, docker itself) discuss this there.

I do think this at least belongs in the known-issue guide however. :sweat_smile:

**Comment by prankul88** [comment]
@BenTheElder Great, I totally agree with you now. Thanks for sharing this informarion.
However I have a small doubt ,

> If docker ps requires sudo docker ps to succeed on a system then kind requires sudo kind.

If I run command `sudo kind` it shows command not found. I am new to this and might be confusing myself a bit.

**Comment by BenTheElder** [comment]
Ah, so if you installed kind with go or the make build it was likely installed to `$HOME/go/bin/kind` for that user, `sudo` will not inherent your environment variables, so there are a few options:
- copy it to a system-wide PATH directory (eg possibly /usr/local/bin/kind)
- use `sudo env "PATH=$PATH" kind ...` to preserve your PATH under sudo
- install it again as root
- use the full path to kind instead of just the command name

**Comment by tao12345666333** [comment]
> If I run command `sudo kind` it shows command not found. I am new to this and might be confusing myself a bit.

If you install `kind` via `go get` it will be install at `$GOPATH/bin/kind` and you should add your `$GOPATH/bin` to your `$PATH` so that you can using `kind` derectly. 

If you using `sudo kind`, your current environment variables will not be maintained. xref https://superuser.com/questions/232231/how-do-i-make-sudo-preserve-my-environment-variables

**Comment by prankul88** [comment]
Closing since a PR has been created fixing this issue.
