### ISSUE TITLE
Minor version tags for published node images (kindest/node:v1.14, kindest/node:v1.13, etc)

### ISSUE THREAD

**Issue by endzyme** [kubernetes-sigs/kind#718]
**What would you like to be added**:
In a similar vein to https://github.com/kubernetes-sigs/kind/issues/197, I think it would be great if you could include `kindest/node:v1.14` so people can get the latest minor without continually knowing the latest patch release.

**Why is this needed**:
Benefits
- Would allow people to "automatically" get the latest patch for new clusters

I'm happy to help with this feature if you could point me in the right direction :)

**Comment by BenTheElder** [comment]
As noted in the release notes we'd in fact prefer that you pin to an _exact_ image (including the hash) currently as we've had to make changes to startup before that necessitated new images. If we publish this tag and encourage using it (or a "latest" tag) then we can't make a change like that.

kind is still alpha grade in terms of https://kubernetes.io/docs/reference/using-api/deprecation-policy/

For current exact images see: https://github.com/kubernetes-sigs/kind/releases/tag/v0.4.0#new-features
For the note about breaking image changes: https://github.com/kubernetes-sigs/kind/releases/tag/v0.3.0#breaking-changes

When we're not alpha or possibly have a better strategy for image discovery I'd love to have this under https://github.com/kubernetes-sigs/kind/issues/197.

**Comment by endzyme** [comment]
woops - thanks for that heads up @BenTheElder - sorry for the noise :) 

I'll close this for now and thanks for the prompt response

**Comment by BenTheElder** [comment]
No no, thanks for the issue! It's good to have input on what people are looking for. 

I definitely think we should be doing this at some point, maybe even some form of "latest" Kubernetes, but I think we should probably get more stability in kind first 😄

**Comment by endzyme** [comment]
Cool beans! Thanks for the follow up :) I appreciate it. Feel free to keep the issue closed for or open it back up in the future.

:) Thanks again!
