### ISSUE TITLE
Rename kind CLI to kindly

### ISSUE THREAD

**Issue by amwat** [kubernetes-sigs/kind#72]
It would be awesome to have the commands be like `kindly create cluster`  :smile: 

/woof

**Comment by BenTheElder** [comment]
hmmmm. @munnerz 
xref: #71 
/shrug

We have a fair bit of link juice headed this way, renaming would also break all of the go imports, but we can consider it :upside_down_face:

**Comment by neolit123** [comment]
> /woof

what a majestic doggo.

**Comment by BenTheElder** [comment]
I've been informed offline that this was a joke with amusing timing :^)
