### ISSUE TITLE
Update client-go to v12.0.0

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/kind#732]
**What should be cleaned up or changed**:

Currently if you want to include `kind` as a library in another tool it will hold your `client-go` version at `v11.0.0` by default. The latest release for `client-go` is now [v12.0.0](https://github.com/kubernetes/client-go/releases/tag/v12.0.0) and it would be helpful to update kind to this version.

**Why is this needed**:

This makes it a bit easier to integrate with `kind` as a library.

**Comment by BenTheElder** [comment]
Relatedly please know that the library form is significantly less stable, @munnerz and I have been working on a plan to clear that up, expect future versions of the library to change quite a bit. 

We export much more than we should.

**Comment by shaneutt** [comment]
Thanks for the heads up @BenTheElder, currently I only have a lightweight integration. I will be cautious about going deeper with that integration. :+1:

**Comment by BenTheElder** [comment]
We're still working on the library interface but it's actively coming along 😅

I beleive https://github.com/kubernetes-sigs/kind/pull/744 removed client-go from being tracked here.

**Comment by shaneutt** [comment]
When trying current master it seems that #744 didn't stop client-go from getting pulled in at `v11.0.0+incompatible` when kind is used as a library.

In case others run into this I've just been using a simple workaround in my `go.mod` with the `replace` verb e.g.:

```
replace k8s.io/client-go v11.0.0+incompatible => k8s.io/client-go v0.0.0-20190819141724-e14f31a72a77
```

**Comment by BenTheElder** [comment]
thanks!

I admit i've not imported a recent version of kind into another project yet, I'm currently working on refining the library surface and usability more.

I think the replace is probably the right solution long term, it looks like we'll want to actually start using client go for https://github.com/kubernetes-sigs/kind/issues/850 in the future possibly...
