### ISSUE TITLE
Error: failed to create cluster: failed to apply overlay network: exit status 126

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kind#736]
**What happened**:
`kind create cluster` fails with `Error: failed to create cluster: failed to apply overlay network: exit status 126`

Prow logs: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15812/integ-framework-k8s-presubmit-tests-master/3694

Exported kind logs: https://gcsweb.k8s.io/gcs/istio-prow/pr-logs/pull/istio_istio/15812/integ-framework-k8s-presubmit-tests-master/3694/artifacts/kind/istio-testing-control-plane/
**What you expected to happen**:
Kind cluster created properly

**How to reproduce it (as minimally and precisely as possible)**:
Not sure :slightly_frowning_face: 

**Environment:**

- kind version: (use `kind version`): v0.3.0
- Kubernetes version: (use `kubectl version`): 1.14.2

This does not happen very often for us, so not a high priority

**Comment by BenTheElder** [comment]
Which version of kind is this?

**Comment by howardjohn** [comment]
This is 0.3.0, been meaning to update to 0.4 but haven't gotten around to it yet

**Comment by aojea** [comment]
@howardjohn does it only failed once? https://prow.istio.io/job-history/istio-prow/pr-logs/directory/integ-framework-k8s-presubmit-tests-master

or there are more occurrences of the same problem

**Comment by aojea** [comment]
ping @howardjohn :)

**Comment by howardjohn** [comment]
Seems like its only happened once from an (incomplete) grep of some of our logs. We recently upgrade to 0.4 and fixed https://github.com/kubernetes-sigs/kind/issues/759 so this probably isn't relevant, kind has been pretty stable for us. I just moved almost all of our tests over to kind now and haven't ran into any problems :slightly_smiling_face: 

Going to close this since I don't think it is relevant anymore

**Comment by BenTheElder** [comment]
🎉
