### ISSUE TITLE
`list` swallows docker errors

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/kind#742]
**What happened**:
My application eventually makes a call to `list` in nodes.go. However, the docker command is presumably returning an error because I see the message "failed to list nodes", coming from line 90 in this file.

https://github.com/kubernetes-sigs/kind/blob/master/pkg/cluster/nodes/nodes.go#L88

**What you expected to happen**:
I would expect stderr to get logged or perhaps wrapped up in the error context.

**How to reproduce it (as minimally and precisely as possible)**:
if you substitute a phony command instead of trying to list, you will see no output and only see "failed to list nodes" as the function swallows the error.

**Comment by BenTheElder** [comment]
there's significantly more details in errors now, if you run kind with `-v 1` (or any non-zero verbosity) it will dump the stack and command output (which is in the errors)
