### ISSUE TITLE
clarify go version requirements

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/kind#747]
# go get sigs.k8s.io/kind
package sigs.k8s.io/kustomize/v3/k8sdeps/kunstruct: cannot find package "sigs.k8s.io/kustomize/v3/k8sdeps/kunstruct" in any of:
        /usr/lib/golang/src/sigs.k8s.io/kustomize/v3/k8sdeps/kunstruct (from $GOROOT)
        /root/go/src/sigs.k8s.io/kustomize/v3/k8sdeps/kunstruct (from $GOPATH)
package sigs.k8s.io/kustomize/v3/k8sdeps/transformer: cannot find package "sigs.k8s.io/kustomize/v3/k8sdeps/transformer" in any of:
        /usr/lib/golang/src/sigs.k8s.io/kustomize/v3/k8sdeps/transformer (from $GOROOT)
        /root/go/src/sigs.k8s.io/kustomize/v3/k8sdeps/transformer (from $GOPATH)
package sigs.k8s.io/kustomize/v3/k8sdeps/validator: cannot find package "sigs.k8s.io/kustomize/v3/k8sdeps/validator" in any of:
        /usr/lib/golang/src/sigs.k8s.io/kustomize/v3/k8sdeps/validator (from $GOROOT)
        /root/go/src/sigs.k8s.io/kustomize/v3/k8sdeps/validator (from $GOPATH)
package sigs.k8s.io/kustomize/v3/pkg/commands/build: cannot find package "sigs.k8s.io/kustomize/v3/pkg/commands/build" in any of:
        /usr/lib/golang/src/sigs.k8s.io/kustomize/v3/pkg/commands/build (from $GOROOT)
        /root/go/src/sigs.k8s.io/kustomize/v3/pkg/commands/build (from $GOPATH)
package sigs.k8s.io/kustomize/v3/pkg/fs: cannot find package "sigs.k8s.io/kustomize/v3/pkg/fs" in any of:
        /usr/lib/golang/src/sigs.k8s.io/kustomize/v3/pkg/fs (from $GOROOT)
        /root/go/src/sigs.k8s.io/kustomize/v3/pkg/fs (from $GOPATH)
package sigs.k8s.io/kustomize/v3/pkg/resmap: cannot find package "sigs.k8s.io/kustomize/v3/pkg/resmap" in any of:
        /usr/lib/golang/src/sigs.k8s.io/kustomize/v3/pkg/resmap (from $GOROOT)
        /root/go/src/sigs.k8s.io/kustomize/v3/pkg/resmap (from $GOPATH)
package sigs.k8s.io/kustomize/v3/pkg/resource: cannot find package "sigs.k8s.io/kustomize/v3/pkg/resource" in any of:
        /usr/lib/golang/src/sigs.k8s.io/kustomize/v3/pkg/resource (from $GOROOT)
        /root/go/src/sigs.k8s.io/kustomize/v3/pkg/resource (from $GOPATH)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by BenTheElder** [comment]
You need a supported go version. Go supports 1.11 and 1.12 for which this error will not happen https://golang.org/doc/devel/release.html

**Comment by BenTheElder** [comment]
the alternative install directions cover how to install without having newer go on your host, we have a docker / make based installation that doesn't need go at all, and pre-built binaries https://kind.sigs.k8s.io/docs/user/quick-start/#installation

**Comment by BenTheElder** [comment]
To elaborate: the issue is is not using go modules, which means the dependencies are not handled properly. [kustomize](https://github.com/kubernetes-sigs/kustomize) requires go [modules](https://github.com/golang/go/wiki/Modules) to version & use correctly, we depend on this package.

if you are on go 1.11+ then it's possible `GO111MODULE=on` was not set correctly.

**Comment by BenTheElder** [comment]
I filed https://github.com/kubernetes-sigs/kind/issues/747 to be clear on this
