### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/kind#748]
@BenTheElder , I wanted to open an issue to keep track of our twitter conversation: https://twitter.com/timothysc/status/1156937259020640256

**What would you like to be documented**:

- [ ] How does LB type service behave? Can my e2e tests running on host directly connect with a NodePort/LB type service inside KIND?

- [ ]  If my operator/webhook server running on host directly, can KIND's kube-apiserver reach my host for validationwebhook calls? With Minikube + VB, I could do https://stackoverflow.com/questions/9537751/virtualbox-port-forward-from-guest-to-host . We would create an APIService like this link to make Minikube's kube-apiserver to reach my webhook server running on host directly during dev work https://github.com/kubedb/postgres/blob/master/hack/dev/apiregistration.yaml#L16

- [ ] How to enable PSP in KIND provisioned cluster?

- [ ] How do I deploy and enable metric-server in KIND provisioned cluster? I added some docs for minikube here: https://github.com/kubernetes-incubator/metrics-server#deployment

- [ ] How to create a Audit Sink-enabled KIND cluster?

- [x] How to enable various flags of Kubernetes control plane components in KIND cluster? Usually we use this with minikube to test against alpha k8s  features.

Thanks taking time to respond to my tweets!

**Comment by aojea** [comment]
Thanks, let me add some references, some of those questions are already documented or tracked in another issues

> **What would you like to be documented**:
> 
> * [ ]  How does LB type service behave? Can my e2e tests running on host directly connect with a NodePort/LB type service inside KIND?

https://mauilion.dev/posts/kind-metallb/
https://kind.sigs.k8s.io/docs/user/quick-start/#mapping-ports-to-the-host-machine



> * [ ]   If my operator/webhook server running on host directly, can KIND's kube-apiserver reach my host for validationwebhook calls? With Minikube + VB, I could do https://stackoverflow.com/questions/9537751/virtualbox-port-forward-from-guest-to-host . We would create an APIService like this link to make Minikube's kube-apiserver to reach my webhook server running on host directly during dev work https://github.com/kubedb/postgres/blob/master/hack/dev/apiregistration.yaml#L16
> * [ ]  How to enable PSP in KIND provisioned cluster?

https://github.com/kubernetes-sigs/kind/pull/725

> * [ ]  How do I deploy and enable metric-server in KIND provisioned cluster? I added some docs for minikube here: https://github.com/kubernetes-incubator/metrics-server#deployment

https://github.com/kubernetes-sigs/kind/issues/398

> * [ ]  How to create a Audit Sink-enabled KIND cluster?
> * [ ]  How to enable various flags of Kubernetes control plane components in KIND cluster? 

https://kind.sigs.k8s.io/docs/user/quick-start/#enable-feature-gates-in-your-cluster

**Comment by BenTheElder** [comment]
>  How to create a Audit Sink-enabled KIND cluster?

this seems to be the one remaining one. it will be some variant on https://kind.sigs.k8s.io/docs/user/quick-start/#enable-feature-gates-in-your-cluster

**Comment by BenTheElder** [comment]
- https://github.com/kubernetes-sigs/kind/pull/457 had some audit logging setup. we're not likely to do that for a bit but...

I think @aojea addressed the rest.
Some more of these should definitely filter into kind.sigs.k8s.io or various other repo docs though...
