### ISSUE TITLE
`get kubeconfig-path` should warn or exit if no cluster with flags.Name exists

### ISSUE THREAD

**Issue by WalkerGriggs** [kubernetes-sigs/kind#750]
**What would you like to be added**:

If no cluster with flags.Name exists, `get kubeconfig-path` should either print a warning or exit with a non-zero exit code.

**Why is this needed**:

Currently, when no name flag is provided, the command builds a new context using the default cluster name (kind) and returns that kubeconfig path. In the situation where only clusters with non-default names exist, the printed path points to a file that doesn't exist.

This can lead to a mis-assigned `KUBECONFIG` and connection issues as a result, especially with the documented `export KUBECONFIG="$(kind get kubeconfig-path)"`

Yes, forgetting to supply the `--name` flag is a user error, but alerting them to their mistake would be better than handing them an incorrect path.

**Comment by BenTheElder** [comment]
The KUBECONFIG path doesn't depend on the cluster existing though, `kind get kubeconfig` should error, kubeconfig-path on the other hand won't because you can know it before creating the cluster. Or after to clean up the file (which kind won't delete)

**Comment by BenTheElder** [comment]
Printing a warning might be OK in this case when we fix stdout vs stderr output (in progress) but I don't think we should exit error here.

**Comment by WalkerGriggs** [comment]
Exiting with error here doesn't make much sense, I agree. I'll set this enhancement aside for when stdout/err output have been fixed.

Thanks for considering it, @BenTheElder

**Comment by BenTheElder** [comment]
Thanks, I'm actively working on fixing this / logging at the moment and
will keep this particular case in mind, we really messed up being
consistent about where / how we do output 😞

**Comment by BenTheElder** [comment]
we've mostly fixed the stdout / stderr logging issue now, time to add a warning here
/assign
/lifecycle active

**Comment by BenTheElder** [comment]
(we also have a `-q` / `--quiet` flag now)

**Comment by BenTheElder** [comment]
In https://github.com/kubernetes-sigs/kind/issues/850 I'm proposing to change how we manage `KUBECONFIG`

**Comment by neolit123** [comment]
> If no cluster with flags.Name exists, get kubeconfig-path should either print a warning or exit with a non-zero exit code.

when we added the feature we decided against that. think of `get kubeconfig-path` as a tool to form paths. if you want to check if a cluster exists use `get clusters`.

**Comment by BenTheElder** [comment]
This command was removed as part of overhauling kubeconfig management to match other tools, ref #850
