### ISSUE TITLE
How to enable RBAC in kind?

### ISSUE THREAD

**Issue by cig0** [kubernetes-sigs/kind#761]
Hi,

I know how to manage the RBAC authorization in a K8s cluster, like:

`$ kubectl start apiserver --authorization-mode=RBAC`

How can accomplish the same thing with kind?
Thanks in advance!

**Comment by aojea** [comment]
cc @neolit123 , I think RBAC is enabled by default, isn´t it?

**Comment by neolit123** [comment]
hi, kind uses kubeadm for cluster creation and kubeadm adds `--authorization-mode=Node,RBAC` to the default flags of the kube-apiserver.

RBAC is already enabled for you.
for using RBAC see here:
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

/close

**Comment by cig0** [comment]
Thank you!
