### ISSUE TITLE
use service account instead of access token for private registry example

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#765]
https://github.com/kubernetes-sigs/kind/pull/756#discussion_r310884414

/cc @chemikadze

**Comment by WalkerGriggs** [comment]
@BenTheElder I might as well take this one on, too, since I started us down this path. 

I added Service Account documentation but left the access token snippet in as well -- gives people the option. Let me know what you think

**Comment by BenTheElder** [comment]
that looks great, thanks!
