### ISSUE TITLE
Update docs.k8s.io/setup/learning-environment/minikube/

### ISSUE THREAD

**Issue by mauilion** [kubernetes-sigs/kind#766]
**What would you like to be documented**:
We should update the docs on docs.k8s.io/setup/learning-environment/minikube/
to have a "kind" example.

**Why is this needed**:
kind may not yet be stable enough to provide for this but when it is we should document kind as a learning environment! With the capabilities around multinode I think it can be a more useful learning env than minikube in many ways.

**Comment by BenTheElder** [comment]
so minikube recently followed with [minikube.sigs.k8s.io](https://minikube.sigs.k8s.io) for docs, I think the plan going forward is to link out to upstream docs, we could probably link to our [quick-start page](https://kind.sigs.k8s.io/docs/user/quick-start/) once that is settled.

cc @zacharysarah

**Comment by BenTheElder** [comment]
I think all the docs like this are external now, is there anything else we should still do here?

**Comment by tao12345666333** [comment]
:+1:

**Comment by BenTheElder** [comment]
I think this is a good plan 👍

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
D: nobody wants to take docs issues it seems .. guess I'll need to bump this up my own TODOs

**Comment by vanou** [comment]
Hi @BenTheElder ! If possible I'll try this.
/assign

**Comment by BenTheElder** [comment]
Sorry for missing this comment, I think this happened! https://kubernetes.io/docs/setup/#learning-environment 

they may both be removed though if I skimmed that correctly.

**Comment by zacharysarah** [comment]
@BenTheElder 
> they may both be removed though if I skimmed that correctly.

Maybe not--we're weighing the boundaries of third-party content to "in-project" rather than "in-tree", which would allow KinD (among others) to stay in k/website docs.

This specific issue may require discussion before action, given https://github.com/kubernetes/website/issues/15969.
