### ISSUE TITLE
Where to check the containers in node images?

### ISSUE THREAD

**Issue by rjshrjndrn** [kubernetes-sigs/kind#769]
Hi,
Thank you for this wonderful tool.
One quick question.
I know, we don't have docker running in agent nodes. Is there any way to see the pods, means the actual containers?

Regards,
Rajesh

**Comment by BenTheElder** [comment]
Hi 🙂

I'm not certain in which way you mean so I'll list multiple:
- Pods in the cluster: `kubectl get pods --all-namespaces`
- Containers on a node: `docker exec node-name crictl ps`

**Comment by aojea** [comment]
crictl has a nice documentation to debug issues https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/
