### ISSUE TITLE
KinD inside docker-machine

### ISSUE THREAD

**Issue by subokita** [kubernetes-sigs/kind#774]
Why does KinD spout out error like this: 
`docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown`
When it's run inside a docker-machine (e.g. after eval `$(docker-machine env)`)

Is it possible to run in after `eval $(docker-machine env)`, do I need to change some of the ENV values? Or it's simply impossible to do so.

**Comment by BenTheElder** [comment]
Hi, I don't think docker-machine works, but can't confirm one way or the other at the moment. We've seen limited interest..
I test manually on docker desktop for macOS / Windows and in CI + manually with docker-ce (the open source Linux packages).

**Comment by aojea** [comment]
I' ve documented my experience with docker-machine here
https://github.com/kubernetes-sigs/kind/issues/377

I was only able to solve that problem rebooting the virtualbox VM used by docker :(

The conclusion was to use DockerDesktop , also docker is considering docker-machine legacy 
https://github.com/kubernetes-sigs/kind/issues/377#issuecomment-489005588

**Comment by BenTheElder** [comment]
I'm going to say https://github.com/kubernetes-sigs/kind/issues/377#issuecomment-489005588 covers this. Closing due to lack of inactivity and information. We've clarified what we test with in https://kind.sigs.k8s.io/docs/user/known-issues/#older-docker-installations

In the future I'd like CI for docker desktop, currently we test offline with that, but not docker machine.

**Comment by forfin** [comment]
I'm facing this problem too, Turn out that doing this inside the docker-machine fixed my problem.
```sh
sudo mkdir /sys/fs/cgroup/systemd
sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
```

Ref: https://github.com/docker/for-linux/issues/219#issuecomment-375160449
