### ISSUE TITLE
Create development guide(s)

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#78]
we should have documentation with details for developing kind
/assign
/priority important-soon
/kind documentation

**Comment by alejandrox1** [comment]
Lost track of this but will resume updating it.
I'll start this time by digging though the hack dir.
/assign

**Comment by alejandrox1** [comment]
#341  covers the utility scripts in `/hack/*.sh`.

After that is merged, will continue to cover `/hack/{build,ci,release}`

**Comment by BenTheElder** [comment]
We could use more, but these do in fact exist! Thanks again @alejandrox1 :-)
