### ISSUE TITLE
Create user guide(s)

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#79]
we should have documentation with details for:
- common usage
- known issues and workarounds
- power user features

/assign
/priority important-soon
/kind documentation

**Comment by alejandrox1** [comment]
Hi, Benjamin. Could I help out with this?

**Comment by BenTheElder** [comment]
Sure, that would be great! PRs are always welcome :-)
I hope to get to this soon, but may not. Trying to get some other key fixes in.

**Comment by BenTheElder** [comment]
this is done! or at least, there are guides, we will continue to enhance them

thanks @alejandrox1!! :-)
