### ISSUE TITLE
v0.5.0 has no darwin build

### ISSUE THREAD

**Issue by sudermanjr** [kubernetes-sigs/kind#791]
**What happened**:

The 0.5.0 release seems to be missing a darwin binary.  There is now a linux-arm binary (awesome), but no darwin.

**Comment by sudermanjr** [comment]
Seems to be there now.  I'm trying it out.

**Comment by BenTheElder** [comment]
this specifically is fixed, however we have a larger problem which I'm filing a more specific bug for.

**Comment by sudermanjr** [comment]
👍

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/792

**Comment by BenTheElder** [comment]
sorry about that! working on this ... :man_facepalming:

**Comment by sudermanjr** [comment]
No worries.  Thanks for the fast response!
