### ISSUE TITLE
v1.14.6 node image in v0.5.0 release is not available on Docker hub

### ISSUE THREAD

**Issue by sudermanjr** [kubernetes-sigs/kind#793]
**What happened**:
```
Creating cluster "test-infra" ...
 ✓ Ensuring node image (kindest/node:v1.14.6) 🖼
ERRO[11:55:40] Unable to find image 'kindest/node:v1.14.6@sha256:4d53072ec035d82a70e9d88972d0eb63846706a892438238b6b54a4531c33a9d' locally
ERRO[11:55:40] docker: Error response from daemon: manifest for kindest/node@sha256:4d53072ec035d82a70e9d88972d0eb63846706a892438238b6b54a4531c33a9d not found.
```

**What you expected to happen**:

That image manifest (specifically mentioned in the v0.5.0 release), should be available to pull from Docker hub when creating a new cluster from this version of kind.

**How to reproduce it (as minimally and precisely as possible)**:

```
kind create cluster --image=kindest/node:v1.14.6@sha256:4d53072ec035d82a70e9d88972d0eb63846706a892438238b6b54a4531c33a9d
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): v0.5.0
- Kubernetes version: (use `kubectl version`): N/A
- Docker version: (use `docker info`):

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

- OS (e.g. from `/etc/os-release`): OSX 10.14.5

**Comment by sudermanjr** [comment]
This is extra confusing as the image appears to exist:

```
└─ docker images kindest/node
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
kindest/node        v1.14.6             4d53072ec035        23 hours ago        1.28GB

└─ docker inspect 4d53072ec035
[
    {
        "Id": "sha256:4d53072ec035d82a70e9d88972d0eb63846706a892438238b6b54a4531c33a9d",
        "RepoTags": [
            "kindest/node:v1.14.6"
        ],

```

**Comment by BenTheElder** [comment]
now that #792 is more or less sorted
/assign
it looks like the correct hash is `sha256:464a43f5cf6ad442f100b0ca881a3acae37af069d5f96849c1d06ced2870888d`

I'm going to double check each of these...

**Comment by BenTheElder** [comment]
the rest of them appear to work fine, specifically the v.14.6 image hash was wrong for some reason. I've updated it in the notes to `kindest/node:v1.14.6@sha256:464a43f5cf6ad442f100b0ca881a3acae37af069d5f96849c1d06ced2870888d`

**Comment by BenTheElder** [comment]
I'm not sure how that happened (bad copy + paste into the release notes?) but I _think_ this is fixed now, please let me know if it is not!

**Comment by sudermanjr** [comment]
Yep, that worked.  Thanks!
