### ISSUE TITLE
Improve usage of Kubernetes API tooling for config

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#80]
... to make the internals more idiomatic

/kind cleanup
/priority important-longterm
xref: https://github.com/kubernetes-sigs/kind/issues/21
/assign
/assign @munnerz

**Comment by BenTheElder** [comment]
@munnerz mind outlining what exactly you had in mind? I have a few thoughts but you have more experience here :-)

**Comment by luxas** [comment]
This is basically solved by #107

**Comment by BenTheElder** [comment]
/lifecycle active
We've definitely made progress here. WDYT @munnerz?

**Comment by munnerz** [comment]
Yep I think this can be closed off now! 🎉

/close
