### ISSUE TITLE
Update kubeconfig when creating cluster

### ISSUE THREAD

**Issue by barkbay** [kubernetes-sigs/kind#802]
**What would you like to be added**:

Would be neat that Kind automatically updates the `kubeconfig` of the user instead of creating a new one that should be imported manually.

Some things to consider:

## Patch and merge
One of the tricky part is that we have to patch the `kubeconfig` as it is provided by `kubeadm`:
1. host and port must be fixed in order to be used from an external host
2. if we want to be able to merge it into a larger `kubeconfig` we have to rename the `AuthInfo` to avoid collisions because `kubeadm` always uses the key `kubernetes-admin`. For example we can suffix it with the name of the cluster.

How to do that:
#### Pros
* `go-client` [already provides what we need to do that](https://github.com/kubernetes/client-go/tree/release-11.0/tools/clientcmd)
#### Cons
* We want to avoid a direct dependency on client-go, it may make `Kind` harder to depend on in test harnesses

### Copy [types.go](https://github.com/kubernetes/client-go/blob/release-11.0/tools/clientcmd/api/types.go) from `go-client` into the `Kind` sources
Seems we only need the `Config` structure from the `client-go` project.
#### Pros
* No dependency on client-go
* `Config` seems stable. De we really care to be not up to date ?
#### Cons
* It's code duplication
* Could be seen as a dependency because the struct may evolve and we may have to keep it in sync

#### Pros
* No dependancies
#### Cons
* Maybe verbose to implement

#### Pros
* User friendly, the context is automatically updated
#### Cons
* How to manage backward compatibility ? Maybe that some existing tools/systems are relying on the current behavior ?

related issues/PR: #113 #512 #520 #517 #790

**Comment by BenTheElder** [comment]
I put some more thought into this and looked around at all the feedback and usage I can find and I think perhaps we should both do this and make it the default mode.

More details in https://github.com/kubernetes-sigs/kind/issues/850 which cross references this and a few other issues.

**Comment by BenTheElder** [comment]
I've mostly implemented this under #850, will PR once some fun cases are handled.

The initial implementation was pretty small and simple, but we need a bit more code to handle with `KUBECONFIG` is multiple files.

**Comment by BenTheElder** [comment]
I'm going to fold this into #850 which has more specific details on how to update the UX around kubeconfig.

Also: going the not-client-go route. We recently stopped needing it as a dependency in the command line, and with dropping everything the binary got much smaller and library management got much easier.
