### ISSUE TITLE
Deployed pod isn't LISTENing

### ISSUE THREAD

**Issue by Mike-S2** [kubernetes-sigs/kind#826]
**What happened**:

Overview is that I created a kind cluster, then deployed nginx to a single worker.
Upon connected to the node, I see the nginx process running, yet, the OS of that container is not showing a LISTEN socket **internal** to the container/node/pod.

Duplication is roughly the following step.  Any output from files referenced or commands run is enclosed below it in the code block.

kind create cluster --config cluster.yaml
```kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    listenAddress: "0.0.0.0"
```

kubectl apply -f nginx.yaml
```apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

kubectl describe pods
```
Name:               nginx-deployment-5754944d6c-qtbfb
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               kind-worker/172.17.0.2
Start Time:         Wed, 28 Aug 2019 17:08:29 -0500
Labels:             app=nginx
                    pod-template-hash=5754944d6c
Annotations:        <none>
Status:             Running
IP:                 10.244.1.2
Controlled By:      ReplicaSet/nginx-deployment-5754944d6c
Containers:
  nginx:
    Container ID:   containerd://4de23bf0f16eec1f1b79e9d3b0d9cbbb9a757d065aa4a97bb14dcf923d2d8622
    Image:          nginx:1.7.9
    Image ID:       sha256:35d28df486f6150fa3174367499d1eb01f22f5a410afe4b9581ac0e0e58b3eaf
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 28 Aug 2019 17:08:44 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tp6cj (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-tp6cj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-tp6cj
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                  Message
  ----    ------     ----  ----                  -------
  Normal  Scheduled  37s   default-scheduler     Successfully assigned default/nginx-deployment-5754944d6c-qtbfb to **kind-worker**
  Normal  Pulling    37s   kubelet, kind-worker  Pulling image "nginx:1.7.9"
  Normal  Pulled     23s   kubelet, kind-worker  Successfully pulled image "nginx:1.7.9"
  Normal  Created    23s   kubelet, kind-worker  Created container nginx
  Normal  Started    22s   kubelet, kind-worker  Started container nginx
```

docker exec kind-worker ps aux | grep nginx
```
root      1583  0.0  0.2  31072  4976 ?        Ss   22:08   0:00 nginx: master process nginx -g daemon off;
systemd+  1607  0.0  0.1  31448  2784 ?        S    22:08   0:00 nginx: worker process
```

Both of the following commands returned nothing for listen sockets.
(ss option -n is disable service name resolution, -l is show listeners, -p is show process)
docker exec kind-worker ss -nlp | grep 1583
docker exec kind-worker ss -nlp | grep 1607

**What you expected to happen**:

I know that I don't have the connectivity outside of the cluster or pod configured yet.
However, when I do that the result is the same.
There is **always** no LISTEN socket inside the container on port 80.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): v0.5.0
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T18:57:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- Docker version: (use `docker info`):
docker info
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 3
  Paused: 0
  Stopped: 3
 Images: 13
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: 3V2V:3F22:OLLQ:C5EJ:ICZK:4TSW:FSZB:ISRW:JJDZ:B3BM:HEQB:K5AJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 49
  Goroutines: 60
  System Time: 2019-08-28T20:23:21.3034704Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
- OS (e.g. from `/etc/os-release`):
Darwin MacBookPro-2.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

**Comment by BenTheElder** [comment]
your nginx pod isn't using a hostport or host network so you shouldn't see it listening on the host interface.

**Comment by Mike-S2** [comment]
Shouldn't it be listening inside the node/pod/container?
I ran the 'ps' and 'ss' commands within the 'kind-worker' container and expected it would be listening regardless of the hostport/nodeport configuration.

**Comment by Mike-S2** [comment]
@BenTheElder, apologies for the kind/bug label... I think that was a default and I should have chose triage first... my bad.  I looked for a slack channel for kind, but wasn't sure if there was one separate from the main Kubernetes community.

**Comment by BenTheElder** [comment]
no worries, just trying to keep the issue tracker in order :-)

so:

> I ran the 'ps' and 'ss' commands within the 'kind-worker' container and expected it would be listening regardless of the hostport/nodeport configuration.

That's like the "node" / host for the pod. Without hostport or host network you won't see it listening there

You should see nginx listening on whatever port that process is listening on _inside the pod_ which is another container "inside" the `kind-worker` container. If you go inside the nginx container from there you should see it listening.

**Comment by Mike-S2** [comment]
Aha!  Okay, I am in way over my head.  Is there some Slack channel I can join for generally help.  I have read most of the kind wiki.  If you can point me somewhere, I would be grateful.

**Comment by BenTheElder** [comment]
#kind in kubernetes.slack.com, it's actually in the README / the homepage :upside_down_face: 

https://github.com/kubernetes-sigs/kind#community-discussion-contribution-and-support

**Comment by BenTheElder** [comment]
http://slack.k8s.io/ to join the slack (also linked there) :sweat_smile:

**Comment by Mike-S2** [comment]
BTW, I did add a hostPort to the nginx.yaml, as shown below and still no LISTEN.
Thanks BenTheElder for your relentless help!

```
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
          hostPort: 80
```

**Comment by Nadra187** [comment]
I faced the same issue, and I saw that the app is actually listening but on the default port: 5050, not on the specified port:8080.
