### ISSUE TITLE
kind cluster stop and start

### ISSUE THREAD

**Issue by bygui86** [kubernetes-sigs/kind#831]
Good morning guys,

Thank you for this amazing project.
I'm testing kind on my MacBookPro with 6 CPUs and 8gb RAM.

Once created the cluster, can I stop and start it again without deleting it? which is the command?
I found nothing on the doc.

I tried with `docker stop` and `docker start` commands: kind cluster container stops but it never starts again.

What am I doing wrong?

Thanks in advance!

**Comment by neolit123** [comment]
hi, i think you can pause the kind containers using docker pause:
- list the containers using `docker ps -a`
- call `docker pause` on them

cluster restart is tracked here:
https://github.com/kubernetes-sigs/kind/issues/148

please re-open if you have further questions.
thanks

/close

**Comment by bygui86** [comment]
Hi @neolit123, thanks for the fast reply!
I will test `docker pause` asap, but I have a question about this: will kind cluster survive to a docker daemon stop and start? for example after a complete laptop reboot?

**Comment by neolit123** [comment]
@bygui86 no, the linked issue #148 explains that the cluster will not reboot on docker daemon restart or OS restart. the are proposals on how to solve this, but it's tricky.

**Comment by bygui86** [comment]
Ok thanks! I'm reading the flow right now.
I will probably add a comment on the issue #148

**Comment by hsafe** [comment]
It is unfortunate that there is no stop and start for a fantastic solution like this ... my experience on a core i7 U processor and running a cluster of 4 no real load and complexity was getting the laptop freeze up, almost always the culprit was the kind cluster

**Comment by BenTheElder** [comment]
#2715
