### ISSUE TITLE
README.md: Getting Started on Windows

### ISSUE THREAD

**Issue by Vaccano** [kubernetes-sigs/kind#837]
**What would you like to be documented**:
Getting started on Windows

**Why is this needed**:
The current "Windows" download (in the "Assets" section of the release notes) is a file without an extension.  This leads to confusion on what you are supposed to do with it.

Additionally, the main page says to run `curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.5.1/kind-$(uname)-amd64` and place it in the path.  But running that on Windows (powershell) gives the error :

> uname : The term 'uname' is not recognized as the name of a cmdlet, function, script file, or operable program.

Addionally the next instruction uses `chmod`, which also errors out on Windows.

Some instructions similar to this would have helped me:
 * Go to https://github.com/kubernetes-sigs/kind/releases
 * Find the "► Assets" dropdown and then the Windows download.
 * Renamed the downloaded file to `kind.exe`
 * Place the downloaded file in your PATH
 * open PowerShell/Command Prompt and run `kind`.  You should get the help output  for kind.

**Comment by BenTheElder** [comment]
actually we have windows instructions at:
https://kind.sigs.k8s.io/docs/user/quick-start/ 

we just need to do something about the README.md

tempted to just point install instructions to the docs site instead of maintaining them twice.

**Comment by Vaccano** [comment]
Yep, that would have worked for me.  

Kind of sad that I missed the HUGE text saying to see the full documentation for more info.  

Sorry for the bad docs request.

**Comment by BenTheElder** [comment]
not at all, I think the README should be fixed to either include the windows details or point to that page and not include the linux shell snippet either. :sweat_smile:

**Comment by BenTheElder** [comment]
this should be an easy one ... just copy the details from the getting started guide that match the command blob from linux.

IE the "on mac / linux" and "windows" part of https://kind.sigs.k8s.io/docs/user/quick-start/#installation should replace the bit that is currently POSIX specific:

https://github.com/kubernetes-sigs/kind#installation-and-usage

**Comment by PatrickLang** [comment]
/assign

I'm about to update the WSL2 section too. I'll include this in the same PR.

**Comment by PatrickLang** [comment]
@Vaccano - does the change in #959 look good to you?

**Comment by Vaccano** [comment]
@PatrickLang - It looks good.

My only concern would be that that it is made clear that while running kind on windows is supported, windows containers are not supported on kind.  

I may have missed that in there somewhere, but it was my major confusion when starting out with kind.

Other than that, it looks like a good change.
