### ISSUE TITLE
Error Creating Cluster on Windows

### ISSUE THREAD

**Issue by Vaccano** [kubernetes-sigs/kind#838]
**What happened**:
Running `kind create cluster` (in PowerShell) gives an error:

>PS C:\kind> kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.15.3) 🖼
[31mERRO[0m[14:30:39] docker: Error response from daemon: Windows does not support privileged mode.
[31mERRO[0m[14:30:39] See 'docker run --help'.
 ✗ Preparing nodes 📦
[31mERRO[0m[14:30:39] docker run error: exit status 125
Error: failed to create cluster: docker run error: exit status 125

**What you expected to happen**:
For the cluster to be created (like shown on the home screen).

**How to reproduce it (as minimally and precisely as possible)**:
* Go to https://github.com/kubernetes-sigs/kind/releases
* For Release 0.5.1, Find the "► Assets" dropdown and then the Windows download.
* Download the file.
* Move the downloaded file to `c:\kind`
* Rename the downloaded file to kind.exe
* Added `c:\kind` to my PATH
* Opened PowerShell and ran `kind create cluster`

Got the following error:
>Error: failed to create cluster: docker run error: exit status 125

**Anything else we need to know?**:
No

**Environment:**

- kind version: (use `kind version`): v0.5.1
- Kubernetes version: (use `kubectl version`): 
-- Client: 1.14 (Platform: windows/amd64)
-- Server: 1.15 (Platform: linux/amd64)
- Docker version: (use `docker info`):
-- Server 19.03.1
-- Kernel 10.0 18362
- OS (e.g. from `/etc/os-release`): Windows 10 Enterprise Version 1903

**Comment by BenTheElder** [comment]
you need linux containers, kind cannot create windows nodes (it's not feasible) but it can create liux nodes on windows

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes-sigs/kind/issues/410
https://github.com/kubernetes-sigs/kind/issues/814
cc @tao12345666333, we should clarify usage of linux containers in the docs

**Comment by BenTheElder** [comment]
https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10-linux

(don't switch to windows containers, https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10#switch-to-windows-containers won't work)

**Comment by Vaccano** [comment]
Once I switched to Linux Mode, it worked fine.

I mistook windows support to mean that it supported windows containers. (Instead of, that it runs on Windows for Linux containers.)

**Comment by BenTheElder** [comment]
> Once I switched to Linux Mode, it worked fine.

:tada: 

> I mistook windows support to mean that it supported windows containers. (Instead of, that it runs on Windows for Linux containers.)

Yeah, I don't think we call this out explicitly anywhere. We should be clear that limited windows support is _for the host_. Not sure where this should go (known issues maybe?)

**Comment by Vaccano** [comment]
For me, it would have been helpful to see it in the "Why kind?" section of the readme.  It has an item that reads:

* kind supports Windows in addition to MacOS and Linux

I think I would have understood better if that had read:

* kind supports Linux containers on Windows in addition to MacOS and Linux

Or 

* kind supports Windows in addition to MacOS and Linux (Linux Containers Only)

**Comment by tao12345666333** [comment]
> xref: #410
> #814
> cc @tao12345666333, we should clarify usage of linux containers in the docs

OK. I will submit a PR later today to improve it.



> Yeah, I don't think we call this out explicitly anywhere. We should be clear that limited windows support is _for the host_. Not sure where this should go (known issues maybe?)

> For me, it would have been helpful to see it in the "Why kind?" section of the readme.

Known issues may be the good choice. (Most people will go directly to see this content.)

In the "Why kind" section, a link may be added for "Windows" to explain how to use Linux Containers on Windows (in known issues).
