### ISSUE TITLE
Failed to apply overlay network issue with 1.16 Kubernetes built images

### ISSUE THREAD

**Issue by boluisa** [kubernetes-sigs/kind#852]
**What happened**:

I built v1.16.0-rc.1 Kubernetes image and ran kind create and got the following result.
```
kind create cluster --name debug --image node:dev
Creating cluster "debug" ...
 ✓ Ensuring node image (node:dev) 🖼
 ✓ Preparing nodes 📦 
 ✓ Creating kubeadm config 📜 
 ✓ Starting control-plane 🕹️ 
 ✗ Installing CNI 🔌 
Error: failed to create cluster: failed to apply overlay network: exit status 1
```
**What you expected to happen**:
create cluster successfully
**How to reproduce it (as minimally and precisely as possible)**:
build v1.16.0-rc.1 kubernetes  and run kind create using the resulting image from the build
**Anything else we need to know?**:
I see this a known issue but none of the causes of the issue apply to my environment.
**Environment:**
- kind version: (use `kind version`): 0.3.0
- Kubernetes version: (use `kubectl version`): v1.16.0-rc.1
- Docker version: (use `docker info`): 19.03.1

**Comment by neolit123** [comment]
hi, can you see more in the logs if you add `--loglevel=debug`?

**Comment by boluisa** [comment]
I got it to work with kind version v0.5.0

**Comment by neolit123** [comment]
> kind version: (use kind version): 0.3.0

missed this part. this kind version is too old for deploying 1.16.

thanks
/close
