### ISSUE TITLE
Kind "unofficial" basic usage examples

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#858]
**What would you like to be documented**:

- [ ] How to use network policies with kind
- [ ] How to map a k8s service using port mapping on Windows or Mac
- [ ] How to install a different CNI plugin
- [ ] How can I have dynamic storage
...

**Why is this needed**:

There are common scenarios and requests from users that should be documented so they don't have to understand all the internals needed to make it work, improving the UX and reducing the # of questions for support.

xref: https://kubernetes.io/docs/tutorials/kubernetes-basics/

**Comment by BenTheElder** [comment]
I would expect the rest of these to be official though

**Comment by aojea** [comment]
> if we document provisional solutions, they're not provisional anymore, users will reasonably expect to continue to depend on them

yeah, that can be a biiig problem

> I would expect the rest of these to be official though

agreed

**Comment by aojea** [comment]
I'm starting to add some examples in my fork wiki, they can be used for reference 
https://github.com/aojea/kind/wiki
