### ISSUE TITLE
Amazon ECR images are accessible in KIND?

### ISSUE THREAD

**Issue by mithunvikram** [kubernetes-sigs/kind#866]
Im using Amazon ECR images for security purpose.When I deployed my helm charts in local it unable to pull the ECR images.(401 unauthorized).

**Comment by BenTheElder** [comment]
You'll need to configure access to your private registry, the nodes have their own container runtime and don't inherent the host access.

Alternatively: You can pull each image to your host and side load them with `kind load docker-image` 

https://kind.sigs.k8s.io/docs/user/private-registries/

**Comment by mithunvikram** [comment]
> You'll need to configure access to your private registry, the nodes have their own container runtime and don't inherent the host access.
> 
> Alternatively: You can pull each image to your host and side load them with `kind load docker-image`
> 
> https://kind.sigs.k8s.io/docs/user/private-registries/

I have fixed this using "imagePullSecrets".Thanks.

**Comment by mithunvikram** [comment]
> You'll need to configure access to your private registry, the nodes have their own container runtime and don't inherent the host access.
> 
> Alternatively: You can pull each image to your host and side load them with `kind load docker-image`
> 
> https://kind.sigs.k8s.io/docs/user/private-registries/

Fixed this issue using "imagePullSecrets".

**Comment by BenTheElder** [comment]
Great! :-)
