### ISSUE TITLE
Using kind in server

### ISSUE THREAD

**Issue by izzatzr** [kubernetes-sigs/kind#867]
Is it suitable to use kind in production server ?
i've tried kind and really amazed about how it works . kind allows me to get k8s cluster in my local machine in easier way.

**Comment by BenTheElder** [comment]
I'm very glad that it allows you to easily get a local cluster.

Kind is for testing Kubernetes or testing Kubernetes applications. It is not suitable for production usage.

In particular these clusters do not yet tolerate host restarts (see the tracking issue, there's a lengthy existing discussion) and there are various tradeoffs that make kind better for cheap ephemeral test clusters that are not suitable for production clusters.

Please do not host production servers using kind 😅

**Comment by izzatzr** [comment]
> I'm very glad that it allows you to easily get a local cluster.
> 
> Kind is for testing Kubernetes or testing Kubernetes applications. It is not suitable for production usage.
> 
> In particular these clusters do not yet tolerate host restarts (see the tracking issue, there's a lengthy existing discussion) and there are various tradeoffs that make kind better for cheap ephemeral test clusters that are not suitable for production clusters.
> 
> Please do not host production servers using kind sweat_smile

hahaha ok , thanks for the answer sweat_smile
