### ISSUE TITLE
Port-forward problem

### ISSUE THREAD

**Issue by mithunvikram** [kubernetes-sigs/kind#869]
Im trying to port-forward my pod

```kubectl port-forward camunda-79bddd6df4-ft5jx -n dev-201902 5010:6000```

But when trying to access in localhost it throws,

```E0926 10:48:40.346646   76692 portforward.go:331] an error occurred forwarding 5010 -> 6000: error forwarding port 6000 to pod 972bb77690ac0b73273e3fb10b8ee0d6f723737f58e4157c48eccfbfd1bdb8bf, uid : failed to execute portforward in network namespace "/var/run/netns/cni-ae95d4df-5e26-da3c-10b5-621ed7c56627": socat command returns error: exit status 1, stderr: "2019/09/26 05:18:40 socat[96552] E connect(5, AF=2 127.0.0.1:6000, 16): Connection refused\n"```

Expected Result:To access my pod in localhost.

**Comment by aojea** [comment]
@mithunvikram that error typically happens when the pod doesn't have anything listen on that port.

Can you check that the pod `camunda-79bddd6df4-ft5jx` has something listening on port 6000?

**Comment by mithunvikram** [comment]
Hey @aojea .Yes.I found out.Thanks.

**Comment by eightlimbed** [comment]
> @mithunvikram that error typically happens when the pod doesn't have anything listen on that port.
> 
> Can you check that the pod `camunda-79bddd6df4-ft5jx` has something listening on port 6000?

thanks :)

**Comment by jamesdube** [comment]
Thanks, issue was in the Dockerfile

**Comment by rthamrin** [comment]
what is the solution, my problem exactly the same, btw I don't use docker

**Comment by jiere** [comment]
@mithunvikram , I met exactly the same issue, could you share what was your solution?

**Comment by pingsutw** [comment]
I met exactly the same issue, could you share what was your solution?
