### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/kind#88]
After kind is released it'd be great to have a homebrew formula for macOS users to use to install kind. Definitely a nice to have :)

**Comment by BenTheElder** [comment]
SGTM, cc @munnerz 👍

We definitely need to think more about releases and versioning, this would be great to have when we figure that out.

**Comment by BenTheElder** [comment]
We do have a minimal test release out, so this might actually be viable in the not incredibly distant future. :-)

**Comment by aojea** [comment]
hi @alisondy , are you going to work on this?

**Comment by alisondy** [comment]
sure, willing to give it a go ✨

**Comment by alisondy** [comment]
not a part of the org..yet ✨

**Comment by BenTheElder** [comment]
you should join :-)

**Comment by alisondy** [comment]
> you should join :-)

soon ✨
Also working on this now

**Comment by alisondy** [comment]
Things that need to be done 
[ ] release binaries in zips, Homebrew is picky... see [here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md)
[ ] writing formulae
[ ] testing formulae
[ ] Document usage

**Comment by alisondy** [comment]
Forked homebrew, you can find the cask I'm working on [here](https://github.com/alisondy/homebrew-cask/tree/kind-cask)

**Comment by zegl** [comment]
@alisondy Isn't "casks" only used for applications that are installed into `/Applications`? Binary applications can go into [`homebrew-core`](https://github.com/Homebrew/homebrew-core/).

**Comment by alisondy** [comment]
> @alisondy Isn't "casks" only used for applications that are installed into `/Applications`? Binary applications can go into [`homebrew-core`](https://github.com/Homebrew/homebrew-core/).

didn't know that, thank you for pointing that out, will check that out

**Comment by kaleocheng** [comment]
@alisondy you can follow the kubectl release in https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubernetes-cli.rb

**Comment by cblecker** [comment]
@alisondy Are you still working on this? If you're not, I can snap it up.

**Comment by alisondy** [comment]
Go for it 👍✨

**Comment by cblecker** [comment]
Okay, so the one issue I ran into as I'm going down the checklist is that kind isn't "stable". There's no green tagged, latest release; they're all pre-release.

So we can't quite submit a Formula yet for inclusion in homebrew-core.

I do have a tap with the Formula I made though: https://github.com/cblecker/homebrew-tap/blob/master/Formula/kind.rb

To install:
```
brew install cblecker/tap/kind
```

To view:
```
brew info cblecker/tap/kind
brew cat cblecker/tap/kind
```

Once we have a green, stable version, then we can submit it upstream to homebrew-core.

**Comment by BenTheElder** [comment]
Sorry about that @cblecker, I will not mark v0.6 as prelease. I'm also trying to ensure we think about and finish landing obvious breaking changes before that drops this week.

**Comment by cblecker** [comment]
Sounds good. Please ping here when v0.6 drops and I can help submit my formula upstream to Homebrew.

**Comment by BenTheElder** [comment]
Thanks! Aiming for ASAP this week, just closing out some things in the
milestone :-)

**Comment by vincepri** [comment]
🎉 This is exciting!

**Comment by BenTheElder** [comment]
@cblecker v0.6.0 is out and NOT tagged as a pre-release

**Comment by cblecker** [comment]
https://github.com/Homebrew/homebrew-core/pull/46886

**Comment by BenTheElder** [comment]
This is done, thank you @cblecker!
