### ISSUE TITLE
node images for 1.16.x?

### ISSUE THREAD

**Issue by cofyc** [kubernetes-sigs/kind#887]
**What would you like to be added**:

Publish pre-built node images for 1.16.x.

**Why is this needed**:

Test against Kubernetes 1.16.x with kind.

**Comment by aojea** [comment]
this is a duplicate of https://github.com/kubernetes-sigs/kind/issues/863

**Comment by cofyc** [comment]
Thanks! Hope automated image pushing tools can be rolled out soon.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/863#issuecomment-539348706
