### ISSUE TITLE
use strict config parsing

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/kind#907]
**What would you like to be added**:
When I pass a configuration file to kind, e.g., to define extra mounts for the containers, I would like some confirmation that it read and applied this configuration.

This is not output in the debug or trace-level logs.

**Why is this needed**:
The non-strict unmarshalling  ignores configuration malformed in a specific way (e.g. `extraMounts` field has a typo). So it would be nice to realize this without having to resort to inspecting the container after it's up.

**Comment by BenTheElder** [comment]
I plan to switch to strict marshaling O(soon).

**Comment by dlipovetsky** [comment]
Strict marshaling would be... strictly better :smile:

**Comment by BenTheElder** [comment]
I've got two PRs open for strict marshalling, just need to do a little more work to determine which route we go forward with.

**Comment by BenTheElder** [comment]
(hijacking this to track that actually merging)

**Comment by BenTheElder** [comment]
we have some strict config loading now :sweat_smile:

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/912
