### ISSUE TITLE
Command: kind get nodes / kind get kubeconfig reports "Error: unknown cluster "kind"

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes-sigs/kind#915]
## Issue

The commands : `kind get nodes` or `kind get kubeconfig` outputs `Error: unknown cluster "kind"`
Version used:  v0.5.1

Commands issued
```
kind create cluster --name halkyon
Creating cluster "halkyon" ...
 ✓ Ensuring node image (kindest/node:v1.15.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Creating kubeadm config 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="halkyon")"
kubectl cluster-info

and

kind get clusters
halkyon

kind get nodes
Error: unknown cluster "kind"

kind get kubeconfig
Error: unknown cluster "kind"
```

the docker ps is well started
```
docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                  NAMES
60249751c157        kindest/node:v1.15.3   "/usr/local/bin/entr…"   11 minutes ago      Up 11 minutes       57659/tcp, 127.0.0.1:57659->6443/tcp   halkyon-control-plane
```

**Comment by aojea** [comment]
you have to specify the cluster name, otherwise uses `kind` by default
```
ists existing kind nodes by their name

Usage:
  kind get nodes [flags]

Flags:
  -h, --help          help for nodes
      --name string   the cluster context name (default "kind")

Global Flags:
      --loglevel string   logrus log level [panic, fatal, error, warning, info, debug, trace] (default "warning")
```

try `kind get nodes --name "halkyon"` and it will work

**Comment by cmoulliard** [comment]
Then the message displayed should be `Error: No nodes found for the cluster - kind` instead of `Error: unknown cluster "kind"` for `kind get nodes`

**Comment by aojea** [comment]
> Then the message displayed should be `Error: No nodes found for the cluster - kind` instead of `Error: unknown cluster "kind"` for `kind get nodes`

errors messages can be improved for sure, in this case, kind is assuming that you are asking to list the nodes in a cluster named `"kind"` , thus the error `Error: unknown cluster "kind"`
Using `Error: No nodes found for the cluster - kind` can mean that there is currently a cluster named "kind" without nodes, that's not true.

Anyway, agree with you should use a more descriptive error message

**Comment by aojea** [comment]
/assign
In master, we've lost the log error

```
 aojeagarcia   errorlog  …  src  sigs.k8s.io  kind  ./kind get nodes --name nonexistantcluster -v3
DEBUG: exec/local.go:88] Running: "docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster=nonexistantcluster --format '{{.Names}}'"
```

**Comment by BenTheElder** [comment]
not finding nodes is not an error if there are none ... we can improve the message printed though to something like `No nodes found for cluster "kind"` to stderr

compare to `kubectl get`.

`kind get kubeconfig` should absolutely error if it can't obtain the kubeconfig, which requires the control plane nodes.

**Comment by aojea** [comment]
> not finding nodes is not an error if there are none ... we can improve the message printed though to something like `No nodes found for cluster "kind"` to stderr

but ... what happens if the cluster doesn't exist or never existed? should try to list the nodes too?

**Comment by BenTheElder** [comment]
> but ... what happens if the cluster doesn't exist or never existed? should try to list the nodes too?

yes. this is the same for checking if resources exist with kubectl.

we can't know if the cluster ever existed, and our internal "does this cluster exist" check is just listing nodes ...

**Comment by aojea** [comment]
Ups, then I have to correct my comment here https://github.com/kubernetes-sigs/kind/issues/915#issuecomment-537946679 , I didn't get it that way

**Comment by BenTheElder** [comment]
this is fixed in HEAD
