### ISSUE TITLE
kind load docker-image doesn't work when adjunct containers are added to the cluster

### ISSUE THREAD

**Issue by danderson** [kubernetes-sigs/kind#923]
**What happened**:

In response to #728, I did as suggested and started tagging "adjunct" containers to my kind cluster with `io.k8s.sigs.kind.cluster=kind-cluster-name`, so that they would get cleaned up by `kind delete cluster` and simplify my E2E testing harness.

Unfortunately, this breaks `kind load docker-image`, because it tries to import the image on all containers having that label. Truncated output, where `kind-ip-1` is one of my "adjunct" containers that don't run the k8s stack.

```
$ kind load docker-image --name=kind metallb/controller:dev-amd64 --loglevel trace
[...snip...]
DEBU[21:58:38] Running: /usr/bin/docker [docker exec --privileged -i kind-ip-1 ctr --namespace=k8s.io images import -] 
Error: failed to load image: exit status 1
```

**What you expected to happen**:

Per #728, I expected adding this label to only matter for cluster teardown.

**How to reproduce it (as minimally and precisely as possible)**:

```
kind create cluster --name=repro
docker run -d --rm --name repro-foo-bar --label='io.k8s.sigs.kind.cluster=repro' debian /bin/bash -c 'while true; do sleep 3600; done'
kind load docker-image --name=repro debian
```

**Anything else we need to know?**:

The trick I use was fairly janky from the start, but I still think the "feature" from #728 would be worth having.

Maybe selecting on `io.k8s.sigs.kind.role` being `worker` or `control-plane` would be a solution? Alternatively I'll have to implement my own additional state management, which I'd obviously prefer to avoid :(

**Environment:**

- kind version: (use `kind version`): v0.5.1
- Kubernetes version: (use `kubectl version`): v1.15.3
- Docker version: (use `docker info`): 19.03.1-ce
- OS (e.g. from `/etc/os-release`): Arch Linux (rolling distro)

**Comment by danderson** [comment]
To be clear, I suspect this is probably "wontfix, working as intended, please don't subvert kind's container labeling system". I'm opening this to check that this is the right outcome (I think it probably is), so that I can add an epilogue to #728 for anyone who finds that bug via a web search.

**Comment by aojea** [comment]
You can specify a list of nodes to `kind load docker-image`

`      --nodes strings   comma separated list of nodes to load images into `

can this solve your problem?

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/commit/67e13f83a83ce002d4dd6dab39ea6eaf2f9bb597

We have actually been selecting on roles for a few months now, however the logic is currently "if not external loadbalancer" rather than "if worker or control plane"

**Comment by BenTheElder** [comment]
swapping that in https://github.com/kubernetes-sigs/kind/pull/924

**Comment by BenTheElder** [comment]
I think this should be fixed in HEAD now by https://github.com/kubernetes-sigs/kind/pull/924 but I didn't actually check yet.

**Comment by BenTheElder** [comment]
pretty sure this is fixed, please re-open if not!
