### ISSUE TITLE
`kind load image-archive` from stdin

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kind#927]
**What would you like to be added**:

Pass `-` as the argument for `load image-archive` to read from stdin

**Why is this needed**:

Its not *needed*, but it would allow us to do `docker save image1 image2 | kind load image-archive -` with no intermediate step.

I am not sure if this is more performant, a good idea, or feasible though

**Comment by BenTheElder** [comment]
we can do this, but we'll need to hold at least part of it in memory and there are tradeoffs there..

you can do this in bash already with `kind load image-archive <(docker save image1 image2)`

https://en.wikipedia.org/wiki/Process_substitution

**Comment by howardjohn** [comment]
Good point about process substitution, I forgot about that. I'll try that out in CI and see how it goes

Right now we are only using a single node

Given we can do this in bash this probably is very low priority or not needed at all -- feel free to close if you want

**Comment by howardjohn** [comment]
Interesting:

our current approach, using load docker-image
```
+ docker images 'istio-testing/*:istio-testing' --format '{{.Repository}}:{{.Tag}}'
+ xargs -n1 -P16 kind --loglevel debug --name istio-testing load docker-image

real	4m29.004s
user	8m52.204s
sys	3m8.361s
```

Using image-archive
```
++ xargs docker save
++ docker images 'istio-testing/*:istio-testing' --format '{{.Repository}}:{{.Tag}}'
time="16:45:21" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}}]"
time="16:45:21" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}} --filter label=io.k8s.sigs.kind.cluster=istio-testing]"
time="16:45:21" level=debug msg="Running: /usr/bin/docker [docker inspect -f {{index .Config.Labels \"io.k8s.sigs.kind.role\"}} istio-testing-control-plane]"
time="16:45:21" level=debug msg="Running: /usr/bin/docker [docker exec --privileged -i istio-testing-control-plane ctr --namespace=k8s.io images import -]"
real	5m36.302s
user	9m10.026s
sys	3m15.851s
```

Will test again not using the process substitution

**Comment by aojea** [comment]
different disks in CI? you can test the speed with `dd` to try to find out the bottleneck https://www.cyberciti.biz/faq/howto-linux-unix-test-disk-performance-with-dd-command/

**Comment by BenTheElder** [comment]
That is disappointing.

I think the next step performance wise is to compare to using a local registry, though I have doubts for the single node case... 

Now that we've spun up containerd build infra and have kind on 1.3+ it should be easier to get a good option for local registries.

One more option is to consider tuning the CI to back kind memory, but that might be a bit expensive. I want to experiment with this in Kubernetes CI as well...

**Comment by BenTheElder** [comment]
ER to back kind with RAM instead of disk, by using a memory backed emptyDir.

**Comment by BenTheElder** [comment]
I think we'll close out this feature for now, I don't see a good way to surface the tradeoffs versus just letting the caller allocate and pass it (EG by using process subsitution) but I want to follow up in another channel about image load performance options..
