### ISSUE TITLE
load images even if images exist in nodes

### ISSUE THREAD

**Issue by cofyc** [kubernetes-sigs/kind#933]
**What would you like to be added**:

Able to overwrite images in nodes, e.g. `kind load docker-image --force <image>`.

**Why is this needed**:

Useful in building and testing images in local cluster started by the kind.

Workarounds:

- use different tag each time

**Comment by BenTheElder** [comment]
we load images if the tags are different OR if the image digest is different.

why would we load an image if the tag and digest are the same?

**Comment by BenTheElder** [comment]
what version are you using? https://github.com/kubernetes-sigs/kind/issues/680

**Comment by cofyc** [comment]
it's better to check the image ID. I was using `kind version v0.5.0-alpha`. After upgrading to `0.5.1`, it works now!

**Comment by cofyc** [comment]
Thanks!

**Comment by BenTheElder** [comment]
phew, thanks! I was worried that bug came back 😅
