### ISSUE TITLE
Question: comparison with kubeadm-dind-cluster?

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes-sigs/kind#94]

**Comment by neolit123** [comment]
one would be, dind-cluster is written in bash, while kind is written in go. :)

**Comment by BenTheElder** [comment]
We should probably document some kind of comparison, I kinda loathe these things because it's hard to write a fair, objective one that brings up all useful points... there are tradeoffs with any Kubernetes setup.

/assign

**Comment by BenTheElder** [comment]
Please re-open or file another issue if you have further questions. I'm going to hold off documenting anything further until `kind` has a proper support & release model in place, discussing this more today with @munnerz.

**Comment by AkihiroSuda** [comment]
Thanks!
