### ISSUE TITLE
x509 error Unknown Authority

### ISSUE THREAD

**Issue by ksk4242** [kubernetes-sigs/kind#941]
I have been trying to create a KinD cluster with a master and 2 worker nodes.  However, when I go to load images into the cluster, the pods are created but they stay in the "Not Ready" status.  When I check the error that is where I find the x509 error "Unknown Authority."  So to try and remedy things I have created the certs as per the Kubernetes pages (at least I believe I have followed the steps as per the Kubernetes page) and still get the same error.  Could someone PLEASE help walk me through the proper process to avoid this error and get the images loaded  properly.  

My apologies as I can't provide captures of the errors right now.  Once I can get to my laptop I will be able to post them.  I was just hoping to get this out for now.

**Comment by BenTheElder** [comment]
> I have been trying to create a KinD cluster with a master and 2 worker nodes. However, when I go to load images into the cluster, the pods are created but they stay in the "Not Ready" status. 

There shouldn't be any certs involved in loading to the cluster. are you using `:latest` tags maybe?

https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

> When I check the error that is where I find the x509 error "Unknown Authority." So to try and remedy things I have created the certs as per the Kubernetes pages (at least I believe I have followed the steps as per the Kubernetes page) and still get the same error. 

where are you seeing the x509 error, exactly?
what certs have you created?

> Could someone PLEASE help walk me through the proper process to avoid this error and get the images loaded properly.

if you provide more details about what you're trying to do, absolutely.

see also https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

**Comment by zcc35357949** [comment]
> > I have been trying to create a KinD cluster with a master and 2 worker nodes. However, when I go to load images into the cluster, the pods are created but they stay in the "Not Ready" status.
> 
> There shouldn't be any certs involved in loading to the cluster. are you using `:latest` tags maybe?
> 
> https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
> 
> > When I check the error that is where I find the x509 error "Unknown Authority." So to try and remedy things I have created the certs as per the Kubernetes pages (at least I believe I have followed the steps as per the Kubernetes page) and still get the same error.
> 
> where are you seeing the x509 error, exactly?
> what certs have you created?
> 
> > Could someone PLEASE help walk me through the proper process to avoid this error and get the images loaded properly.
> 
> if you provide more details about what you're trying to do, absolutely.
> 
> see also https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

I had trouble with this too. I want to pull the image from my private registry,such as harbor...
But pod can not come to ready with X509 error, although I have configured the registry self-signed cert in /etc/docker/certs.d/xxx.

Now I know that in fact kind's k8s nodes  use containerd  directly instead of dockerd, so the cert directory may not be loaded.

Is there any solution to config the registry's ca in kind nodes?

**Comment by BenTheElder** [comment]
> Now I know that in fact kind's k8s nodes use containerd directly instead of dockerd, so the cert directory may not be loaded.

kind's nodes need to run their own container runtime in general, kubelet cannot share them, so they won't have host files.

the nodes are ~ubuntu, so you can `docker exec` to them and install certs https://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate

**Comment by zcc35357949** [comment]
> > Now I know that in fact kind's k8s nodes use containerd directly instead of dockerd, so the cert directory may not be loaded.
> 
> kind's nodes need to run their own container runtime in general, kubelet cannot share them, so they won't have host files.
> 
> the nodes are ~ubuntu, so you can `docker exec` to them and install certs https://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate

I copy my self-signed certificate to /usr/local/share/ca-certificates/ and use `update-ca-certificates` add it. 
```
root@kind-control-plane:/# cp /etc/docker/certs.d/hub.bilibili.co/ca.crt /usr/local/share/ca-certificates/hub.crt
root@kind-control-plane:/# ls /etc/docker/certs.d/hub.bilibili.co/ca.crt
/etc/docker/certs.d/hub.bilibili.co/ca.crt
root@kind-control-plane:/# update-ca-certificates
Updating certificates in /etc/ssl/certs...
rehash: warning: skipping hub.pem,it does not contain exactly one certificate or CRL
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```
But it doesn't work.
```
Warning  Failed     8s (x2 over 23s)  kubelet, kind-worker  Failed to pull image "hub.bilibili.co/ops-demo/beego-demo:ea852577a0bde69f16801c3afec28cda4e3c6d62-uat": rpc error: code = Unknown desc = failed to resolve image "hub.bilibili.co/ops-demo/beego-demo:ea852577a0bde69f16801c3afec28cda4e3c6d62-uat": no available registry endpoint: failed to do request: Head https://hub.bilibili.co/v2/ops-demo/beego-demo/manifests/ea852577a0bde69f16801c3afec28cda4e3c6d62-uat: x509: certificate signed by unknown authority
```

**Comment by ksk4242** [comment]
I will give that a try as well!  Much like zcc35357949, i was trying to pull an image (from my Docker repo) with no luck.  I am also trying to run KinD in a Ubuntu 18.04 VirtualBox VM.  Here is an example I used from the Kubernetes site to execute my deployment:

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx

**Comment by ksk4242** [comment]
@BenTheElder That worked!!  I now have my containers running in my cluster...thank you very much!

**Comment by zcc35357949** [comment]
> @BenTheElder That worked!! I now have my containers running in my cluster...thank you very much!
Is your certificate self-signed?

**Comment by BenTheElder** [comment]
Excellent @ksk4242, sorry that's such a pain. I'm going to work on some more options for this soon... keep en eye on #602, the requirements should be ~similar.

**Comment by BenTheElder** [comment]
@zcc35357949 could you ask for help in slack or file another support ticket with more details? It seems the original ticket here is resolved.

**Comment by Sispheor** [comment]
Hello guys,
How to inject a private certificate in the node container?
I would like to add the certificate of my corporate proxy in `/usr/local/share/ca-certificates/` and persist the configuration.
Is there a config to mount a volume or something?
Thanks.

**Comment by capcom923** [comment]
Please make sure the hub.crt you mentioned is in correct format. It should be as below:
-----BEGIN CERTIFICATE-----
MII<a long text>
-----END CERTIFICATE-----

Actually, there are 2 kinds of .crt file. The one is DER format, the other one is plain text format. The update-ca-certificates command could not deal with the DER format crt file. It will say "it does not contain exactly one certificate or CRL". You need to use below command to convert it
```
openssl x509 -inform DER -in your-ca-in-DER.crt -out your-ca.pem -text
openssl x509 -in your-ca.pem -inform PEM -out your-ca.crt
```
