### ISSUE TITLE
Docker Hub tags for v1.15.4 and v1.14.7?

### ISSUE THREAD

**Issue by jdolitsky** [kubernetes-sigs/kind#948]
Wondering if these versions can be built and pushed to [kindest/node](https://hub.docker.com/r/kindest/node/tags) repo on Docker Hub? 

If there is somewhere in automation scripts to enable this please let me know and I can add.

**Comment by aojea** [comment]
this is a duplicate of https://github.com/kubernetes-sigs/kind/issues/863#issuecomment-538765735 , please read the comment I linked to understanding current status

**Comment by BenTheElder** [comment]
This is https://github.com/kubernetes-sigs/kind/issues/197. I will be working on this in Q4.

**Comment by BenTheElder** [comment]
Also, the issue will be infra mainly rather than the scripts. The Kubernetes CI infra is not suitably secure for publishing images. We'll figure something out.

**Comment by jdolitsky** [comment]
ok thank you!
