### ISSUE TITLE
Support host resolvable IP as the kubeconfig's server

### ISSUE THREAD

**Issue by nmiculinic** [kubernetes-sigs/kind#950]
**What would you like to be added**:

By default the created cluster kubeconfig list the server as:
```
server: https://127.0.0.1:<some port>
```
Which isn't resolvable from inside the created kind cluster or across multiple kind clusters on the same host.

**Why is this needed**:

This is primarily needed for multicluster scenarios, federation, cross-cluster controllers and that kind of usecase.

By having multiple kind clusters, A & B for example, an operator running in A can connect to cluster B only if the `server` field properly resolves itself. Usually the following steps are performed.

```
NAME=example
kind create cluster --name ${NAME} 
export KUBECONFIG="$(kind get kubeconfig-path --name="${NAME}")"
export clusterIP=$(docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAd
dress}}{{end}}" "${NAME}-control-plane" | tr -d '\n ')
kubectl config set "clusters.${NAME}.server" "https://${clusterIP}:6443" 
kubectl cluster-info
```

It would be awesome having native kind tool support for this kind of cluster creation (( or even be default if that's possible ))

**Comment by BenTheElder** [comment]
Pretty sure this already exists 🙃

`kind get kubeconfig --internal` for one usable inside the docker network (IE using the node container IP). Note that on some platforms this is resolvable on the host but not on all platforms (docker for Mac)

Use this config to set the listen IP at creation time (if you want to use some host interface addr other than loopback...)
```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
networking:
  apiServerAddress: 1.2.3.4
```

**Comment by nmiculinic** [comment]
You're right! Thank you for the reply!
