### ISSUE TITLE
Add a chocolatey package for Windows users

### ISSUE THREAD

**Issue by shahiddev** [kubernetes-sigs/kind#956]
**What would you like to be added**:
Add a chocolatey package to make installation simpler for Windows users

**Why is this needed**:
Currently the release binary doesn't have any extension and requires the user to install KinD into their path either manually or via a Powershell script.
Chocolatey can automate this so users simply need to run `choco install Kind` to install KinD and upgrades to newer versions are much easier too

**Comment by BenTheElder** [comment]
xref: #88 

I agree that it's about time for this

**Comment by digitalcoyote** [comment]
I'm actually working a few packages right now (I have an AU repo setup to keep them up to  date). I can add this project's maintainers as maintainers for the package after it's published (gives management rights to the package). Best of all, it should require no changes to your current release process. Should be as simple as making sure the pre-reqs are dependencies and then running through the install directions.

**Comment by digitalcoyote** [comment]
Pushed the package to Chocolatey. Their Gitter chat indicates they are behind on moderation to an abnormally large queue, so I expect the package to be live in a few days to a week. I'll ready a PR with install instructions for when it goes live.

**Comment by digitalcoyote** [comment]
https://chocolatey.org/packages/kind

Package is approved :)

**Comment by BenTheElder** [comment]
awesome, what will we need to do to release future versions?

**Comment by digitalcoyote** [comment]
It's automatic if it continues to use my repo (setup based on chocolatey recommended AU CI scripts). If you want to integrate it into your, you need a chocolatey account (to get a key to push updates) and I can help with integration as necessary. Otherwise, it'll auto-publish updates as soon as my AU scripts detect a new version/URL to put in the chocolatey scripts.

**Comment by BenTheElder** [comment]
awesome, thanks. we should probably circle back on how to manage a ""project owned"" account (or at least add the kind repo maintainers) but I'm very happy to have it auto-published for now, thank you very much :-)

**Comment by BenTheElder** [comment]
thanks!
