### ISSUE TITLE
If there is only one cluster, kind delete cluster should just delete it

### ISSUE THREAD

**Issue by yashbhutwala** [kubernetes-sigs/kind#958]
**What would you like to be added**:
If there is only one cluster, `kind delete cluster` should just delete it, instead of having to specify the name.  Currently, it only does this for the default name `kind`. 

**Why is this needed**:
Better user experience

**Comment by BenTheElder** [comment]
The kind CLI consistently requires specifying a `--name` if you use a non-default name.

I'm not a fan of changing that. This is inline with eg minikube's --profile, gcloud container clusters, kops, ...

However, we are going to introduce other ways to manage the name #850

**Comment by BenTheElder** [comment]
since delete is irreversable, I would really prefer that the user specify which cluster they want to delete. if you `kind create cluster` without specifiyng the name then `kind delete cluster` will delete it.

we could have a `kind delete clusters --all` or something like that in the future, but that's not quite the same.

**Comment by yashbhutwala** [comment]
> since delete is irreversable, I would really prefer that the user specify which cluster they want to delete. if you `kind create cluster` without specifiyng the name then `kind delete cluster` will delete it.

Personally, when I'm using `kind delete cluster` and there is only one cluster to `delete`, it's kinda annoying to have to input the name of it.  But yea I could see how one can bikeshed either way haha.  I guess, explicit is better than implicit.

> we could have a `kind delete clusters --all` or something like that in the future, but that's not quite the same.

^^ Definitely could change this ticket into a request for this feature, if you want.

**Comment by BenTheElder** [comment]
kind delete clusters --all was implemented 😅 
still finishing up the UX etc. but the basic functionality is in HEAD though thanks to @danielhelfand
