### ISSUE TITLE
do unstructured patch with json-patch library directly

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#962]
**What should be cleaned up or changed**: rewrite our kubeadm patching logic to use https://github.com/evanphx/json-patch directly.

**Why is this needed**: 
- kustomize is > 3/4 of our binary size 
  - macOS binary as of 7d8bbb4 is 34M
  - macOS binary as of 7d8bbb4 + a trivial patch to no-op patching is 8.3M (!)
- kustomize brings in heavy dependencies (in terms of managing a `go get`-able / embeddable tool) like client-go.
  - In fact most of our transitive dependencies are due to kustomize. 
  - The latest kustomize go.mod even includes things like golangci-lint

Most of these things are perfectly reasonable for kustomize to do as a tool, however we're not seeing the benefits of them in kind specifically because the types were are patching are totally unstructured anyhow without type definitions.

A tool like kubeadm on the other hand sees the strategic-merge benefits because it patches objects that are core k8s api types.

In addition, we can loosen the restrictions around matching patches. It will be easier to write trivial kubeadm config patches if you don't _have_ to specify the apiVersion, many of the fields are the same anyhow.

We can also get rid of the in memory filesystem and windows work arounds, and hopefully generally have a simpler implementation of patching.

/assign

**Comment by BenTheElder** [comment]
for the record, the diff used to obtain those binary sizes:
```patch
diff --git a/pkg/internal/util/kustomize/kustomize.go b/pkg/internal/util/kustomize/kustomize.go
index 4c217b7..212aca7 100644
--- a/pkg/internal/util/kustomize/kustomize.go
+++ b/pkg/internal/util/kustomize/kustomize.go
@@ -18,6 +18,8 @@ limitations under the License.
 package kustomize
 
 import (
+       "strings"
+/*
        "fmt"
        "path/filepath"
        "runtime"
@@ -37,7 +39,7 @@ import (
        "sigs.k8s.io/yaml"
 
        "sigs.k8s.io/kind/pkg/errors"
-
+*/
        "sigs.k8s.io/kind/pkg/internal/apis/config"
 )
 
@@ -46,6 +48,8 @@ import (
 // and returns the `kustomize build` result as a yaml blob
 // It does this in-memory using the build cobra command
 func Build(resources, patches []string, patchesJSON6902 []config.PatchJSON6902) (string, error) {
+       return strings.Join(resources, "---\n"), nil
+/*
        // write the resources and patches to an in memory fs with a generated
        // kustomization.yaml
        memFS := fs.MakeFakeFS() // fs.MakeFsInMemory()
@@ -137,4 +141,5 @@ func Build(resources, patches []string, patchesJSON6902 []config.PatchJSON6902)
                return "", errors.Wrap(err, "error executing kustomize build")
        }
        return string(yamlResources), nil
+*/
 }
```

**Comment by aojea** [comment]
:+1: better, faster, lighter ... :1st_place_medal:

**Comment by neolit123** [comment]
before we added kustomize support in kubeadm and was wondering whether it is better to just use apimachinery's utils. @fabriziopandini 's argument was that kustomize is what the ecosystem is supposed to use.

> kustomize brings in heavy dependencies (in terms of managing a go get-able / embeddable tool) like client-go.

IIRC adding kustomize to kubeadm only contributed a few MB, probably because we already had client-go.

> A tool like kubeadm on the other hand sees the strategic-merge benefits because it patches objects that are core k8s api types.

yet, IMO all of that is still possible with regular patches.

> We can also get rid of the in memory filesystem and windows work arounds, and hopefully generally have a simpler implementation of patching.

we also ended up workarounds in kubeadm for JSON patches.

> kustomize is > 3/4 of our binary size

for me, that alone would be a good enough reason to consider the change.
so +1.

**Comment by tao12345666333** [comment]
+1 for lighter

**Comment by BenTheElder** [comment]
> before we added kustomize support in kubeadm and was wondering whether it is better to just use apimachinery's utils. @fabriziopandini 's argument was that kustomize is what the ecosystem is supposed to use.

I think this is a good argument for many cases, but what kind is exposing is pretty trivial and unstructured. I implemented our use case intermittently in an afternoon (need to clean and add test cases though)..

> IIRC adding kustomize to kubeadm only contributed a few MB, probably because we already had client-go.

yeah, this is because kubeadm and kubectl already pull in the same dependencies.
kind doesn't need most of them.

> yet, IMO all of that is still possible with regular patches.

strategic merge patch is pretty nice for types where you have the spec and are willing to implement the extra effort ...

> for me, that alone would be a good enough reason to consider the change.

current WIP macOS binary is 9.1M 👍
