### ISSUE TITLE
ensure go modules are tidy in verify checks

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#996]
**What should be cleaned up or changed**:

https://github.com/kubernetes-sigs/kind/blob/master/hack/verify/generated.sh already verifies that generated code is up to date and the repo is `gofmt`ed

we should also ensure that `go mod tidy` has run over the modules, this can be a pretty trivial "lint" that runs this and diffs.

to do this, you need to make sure that no go commands have run before it in CI, as some of them can update the file, or you need to verify in git that the file is unchanged.

**Why is this needed**: 

this is pretty minor, but we want to avoid spurious entries in go.mod and go.sum for our modules

note that there are multiple modules, starting with the main module would be simplest.

**Comment by jan25** [comment]
Hi @BenTheElder ! Looks like we already have tidy happening here https://github.com/kubernetes-sigs/kind/blob/master/hack/update/generated.sh#L32 which is used in `verify/generated.sh` you linked in the issue. Or am i missing something?

**Comment by BenTheElder** [comment]
I'm not sure what we're missing, it seemed some spurious changes slipped through though :thinking: 
https://github.com/kubernetes-sigs/kind/pull/995

**Comment by BenTheElder** [comment]
not seeing further evidence of this. tentatively closing for now
